DELETE FROM Buildings WHERE BuildingType = 'BUILDING_LEANING_TOWER';
DELETE FROM Buildings WHERE BuildingType = 'BUILDING_PORCELAIN_TOWER';
DELETE FROM Resources WHERE ResourceType = 'RESOURCE_PORCELAIN';