DELETE FROM TraitModifiers WHERE TraitType='TRAIT_LEADER_MAJOR_CIV' AND ModifierId='STANDARD_DIPLOMATIC_SAILOR_VALKRANA';

DELETE FROM Leaders WHERE LeaderType='LEADER_SAILOR_VALKRANA';

DELETE FROM BuildingModifiers WHERE  ModifierId='SAILOR_VALKRANA_UU_ABILITY_LIBRARY';
DELETE FROM BuildingModifiers WHERE ModifierId='SAILOR_VALKRANA_UU_ABILITY_UNIVERSITY';
DELETE FROM BuildingModifiers WHERE ModifierId='SAILOR_VALKRANA_UU_ABILITY_RESEARCHLAB';

DELETE FROM TypeTags WHERE Type='ABILITY_SAILOR_VALKRANA_SPELL2';

DELETE FROM Building_GreatWorks WHERE BuildingType='BUILDING_LIBRARY';

DELETE FROM Religions WHERE ReligionType='RELIGION_SAILOR_ILYANA';
DELETE FROM FavoredReligions WHERE ReligionType='RELIGION_SAILOR_ILYANA';

DELETE FROM Units WHERE UnitType='UNIT_SAILOR_VALKRANA_UU';
DELETE FROM UnitUpgrades WHERE Unit='UNIT_SAILOR_VALKRANA_UU';
DELETE FROM UnitReplaces WHERE CivUniqueUnitType='UNIT_SAILOR_VALKRANA_UU';
DELETE FROM UnitAiInfos WHERE UnitType='UNIT_SAILOR_VALKRANA_UU';

DELETE FROM Units WHERE UnitType ='UNIT_MECHANIZED_INFANTRY';

DELETE FROM Buildings WHERE BuildingType ='BUILDING_TEMPLE_ARTEMIS';
-- DELETE FROM Buildings WHERE BuildingType ='BUILDING_MONT_ST_MICHEL';         -- we keep it
-- DELETE FROM Buildings WHERE BuildingType ='BUILDING_LIBRARY';
DELETE FROM Buildings WHERE BuildingType ='BUILDING_UNIVERSITY';
-- DELETE FROM Buildings WHERE BuildingType ='BUILDING_RESEARCH_LAB';
