INSERT INTO IconDefinitions(Name, Atlas, 'Index')VALUES
('ICON_PROJECT_DEEPENING', 'ICON_ATLAS_EXPANSION_2_UNIT_ACTIONS', 0),
('ICON_PROJECT_THE_DRAW', 'ICON_ATLAS_EXPANSION_2_UNIT_ACTIONS', 13),
('ICON_PROJECT_ASCENSION', 'ICON_ATLAS_UNIT_ACTIONS', 73),
('ICON_PROJECT_STIR_FROM_SLUMBER', 'ICON_ATLAS_UNIT_ACTIONS', 77),
('ICON_PROJECT_HALLOWING_OF_ELOHIM', 'ICON_ATLAS_UNIT_ACTIONS', 86);

