INSERT INTO IconTextureAtlases(Name, IconSize, IconsPerRow, IconsPerColumn, Filename) VALUES
('ICON_SLTH_RESOURCE_ATLAS_0', '256', '5', '1', 'Slth_Resource_Atlas_0_256.dds'),
('ICON_SLTH_RESOURCE_ATLAS_0', '64', '5', '1', 'Slth_Resource_Atlas_0_64.dds'),
('ICON_SLTH_RESOURCE_ATLAS_0', '50', '5', '1', 'Slth_Resource_Atlas_0_50.dds'),
('ICON_SLTH_RESOURCE_ATLAS_0', '38', '5', '1', 'Slth_Resource_Atlas_0_38.dds'),
('ICON_SLTH_RESOURCE_ATLAS_0', '32', '5', '1', 'Slth_Resource_Atlas_0_32.dds'),
('ICON_SLTH_RESOURCE_ATLAS_FOW_0', '256', '5', '1', 'Slth_Resource_Atlas_Fow_0_256.dds'),
('ICON_SLTH_RESOURCE_ATLAS_FOW_0', '64', '5', '1', 'Slth_Resource_Atlas_Fow_0_64.dds'),
('ICON_SLTH_RESOURCE_ATLAS_FOW_0', '50', '5', '1', 'Slth_Resource_Atlas_Fow_0_50.dds'),
('ICON_SLTH_RESOURCE_ATLAS_FOW_0', '38', '5', '1', 'Slth_Resource_Atlas_Fow_0_38.dds'),
('ICON_SLTH_RESOURCE_ATLAS_FOW_0', '32', '5', '1', 'Slth_Resource_Atlas_Fow_0_32.dds'),
('ICON_SLTH_RESOURCE_ATLAS_FOW_0', '22', '5', '1', 'Slth_Resource_Atlas_Fow_0_22.dds'),
('ICON_SLTH_RESOURCE_ATLAS_FONT', '22', '5', '1', 'Slth_Resource_Atlas_0_22.dds');

INSERT INTO IconTextureAtlases(Name, IconSize, IconsPerRow, IconsPerColumn, Baseline, Filename) VALUES
('ICON_SLTH_RESOURCE_ATLAS_0', '22', '5', '1', '6', 'Slth_Resource_Atlas_0_22.dds');

-- base icons
INSERT INTO IconDefinitions (Name, Atlas, 'Index') VALUES
('ICON_RESOURCE_HORSE', 'ICON_ATLAS_RESOURCES', '42'),
('ICON_RESOURCE_HORSE_FOW', 'ICON_ATLAS_RESOURCES_FOW', '42'),
('ICON_RESOURCE_PEARL', 'ICON_ATLAS_RESOURCES', '23'),
('ICON_RESOURCE_PEARL_FOW', 'ICON_ATLAS_RESOURCES_FOW', '23');



INSERT INTO IconDefinitions (Name, Atlas, 'Index') VALUES
('RESOURCE_MANA_AIR', 'ICON_SLTH_RESOURCE_ATLAS_0', 1),
('RESOURCE_MANA_BODY', 'ICON_SLTH_RESOURCE_ATLAS_0', 2),
('RESOURCE_MANA_CHAOS', 'ICON_SLTH_RESOURCE_ATLAS_0', 3),
('RESOURCE_MANA_DEATH', 'ICON_SLTH_RESOURCE_ATLAS_0', 4),
('RESOURCE_MANA_EARTH', 'ICON_SLTH_RESOURCE_ATLAS_0', 5),
('RESOURCE_MANA_ENCHANTMENT', 'ICON_SLTH_RESOURCE_ATLAS_0', 6),
('RESOURCE_MANA_ENTROPY', 'ICON_SLTH_RESOURCE_ATLAS_0', 7),
('RESOURCE_MANA_FIRE', 'ICON_SLTH_RESOURCE_ATLAS_0', 8),
('RESOURCE_MANA_LAW', 'ICON_SLTH_RESOURCE_ATLAS_0', 9),
('RESOURCE_MANA_LIFE', 'ICON_SLTH_RESOURCE_ATLAS_0', 10),
('RESOURCE_MANA_METAMAGIC', 'ICON_SLTH_RESOURCE_ATLAS_0', 11),
('RESOURCE_MANA_MIND', 'ICON_SLTH_RESOURCE_ATLAS_0', 12),
('RESOURCE_MANA_NATURE', 'ICON_SLTH_RESOURCE_ATLAS_0', 13),
('RESOURCE_MANA_SHADOW', 'ICON_SLTH_RESOURCE_ATLAS_0', 17),
('RESOURCE_MANA_SPIRIT', 'ICON_SLTH_RESOURCE_ATLAS_0', 18),
('RESOURCE_MANA_SUN', 'ICON_SLTH_RESOURCE_ATLAS_0', 19),
('RESOURCE_MANA_WATER', 'ICON_SLTH_RESOURCE_ATLAS_0', 20),
('RESOURCE_NIGHTMARE', 'ICON_SLTH_RESOURCE_ATLAS_0', 21),
('RESOURCE_TOADS', 'ICON_SLTH_RESOURCE_ATLAS_0', 22);

INSERT INTO IconDefinitions (Name, Atlas, 'Index') VALUES
('ICON_RESOURCE_MANA_ICE', 'ICON_SLTH_RESOURCE_ATLAS_0', 20),
('RESOURCE_MANA_ICE' ,'ICON_SLTH_RESOURCE_ATLAS_0' ,'20');