INSERT INTO IconTextureAtlases
		(Name,									IconSize,	IconsPerRow,	IconsPerColumn,		Filename					)
VALUES	('ICON_ATLAS_LEADER_ALEXIS',				32,	 		1,				1,					'ICON_LEADER_ALEXIS_32.dds'		),
		('ICON_ATLAS_LEADER_ALEXIS',				45,	 		1,				1,					'ICON_LEADER_ALEXIS_45.dds'		),
		('ICON_ATLAS_LEADER_ALEXIS',				48,	 		1,				1,					'ICON_LEADER_ALEXIS_48.dds'		),
		('ICON_ATLAS_LEADER_ALEXIS',				50,	 		1,				1,					'ICON_LEADER_ALEXIS_50.dds'		),
		('ICON_ATLAS_LEADER_ALEXIS',				55,	 		1,				1,					'ICON_LEADER_ALEXIS_55.dds'		),
		('ICON_ATLAS_LEADER_ALEXIS',				64,			1,				1,					'ICON_LEADER_ALEXIS_64.dds'		),
		('ICON_ATLAS_LEADER_ALEXIS',				200,	 	1,				1,					'ICON_LEADER_ALEXIS_200.dds'	),
		('ICON_ATLAS_LEADER_ALEXIS',				80,	 		1,				1,					'ICON_LEADER_ALEXIS_80.dds'		),
		('ICON_ATLAS_LEADER_ALEXIS',				256,	 	1,				1,					'ICON_LEADER_ALEXIS_256.dds'	),
		('ICON_ATLAS_LANUN',					    22,	 		1,				1,					'LanunAtlasWhite22.dds'			),
		('ICON_ATLAS_LANUN',					    30,	 		1,				1,					'LanunAtlasWhite30.dds'			),
		('ICON_ATLAS_LANUN',					    36,	 		1,				1,					'LanunAtlasWhite36.dds'			),
		('ICON_ATLAS_LANUN',					    44,	 		1,				1,					'LanunAtlasWhite44.dds'			),
		('ICON_ATLAS_LANUN',					    48,	 		1,				1,					'LanunAtlasWhite48.dds'			),
		('ICON_ATLAS_LANUN',					    50,	 		1,				1,					'LanunAtlasWhite50.dds'			),
		('ICON_ATLAS_LANUN',					    64,	 		1,				1,					'LanunAtlasWhite64.dds'			),
		('ICON_ATLAS_LANUN',					    80,	 		1,				1,					'LanunAtlasWhite80.dds'			),
		('ICON_ATLAS_LANUN',					    200, 		1,				1,					'LanunAtlasWhite200.dds'		),
		('ICON_ATLAS_LANUN',					    256, 		1,				1,					'LanunAtlasWhite256.dds'		),
		('ICON_ATLAS_KHAZAD',					    22,	 		1,				1,					'KhazadAtlas22.dds'			    ),
		('ICON_ATLAS_KHAZAD',					    30,	 		1,				1,					'KhazadAtlas30.dds'			    ),
		('ICON_ATLAS_KHAZAD',					    36,	 		1,				1,					'KhazadAtlas36.dds'			    ),
		('ICON_ATLAS_KHAZAD',					    44,	 		1,				1,					'KhazadAtlas44.dds'			    ),
		('ICON_ATLAS_KHAZAD',					    48,	 		1,				1,					'KhazadAtlas48.dds'			    ),
		('ICON_ATLAS_KHAZAD',					    50,	 		1,				1,					'KhazadAtlas50.dds'			    ),
		('ICON_ATLAS_KHAZAD',					    64,	 		1,				1,					'KhazadAtlas64.dds'			    ),
		('ICON_ATLAS_KHAZAD',					    80,	 		1,				1,					'KhazadAtlas80.dds'			    ),
		('ICON_ATLAS_KHAZAD',					    200, 		1,				1,					'KhazadAtlas200.dds'			),
		('ICON_ATLAS_KHAZAD',					    256, 		1,				1,					'KhazadAtlas256.dds'			),

		('ICON_ATLAS_BANNOR',					    22,	 		1,				1,					'BannorAtlas22.dds'			    ),
		('ICON_ATLAS_BANNOR',					    30,	 		1,				1,					'BannorAtlas30.dds'			    ),
		('ICON_ATLAS_BANNOR',					    36,	 		1,				1,					'BannorAtlas36.dds'			    ),
		('ICON_ATLAS_BANNOR',					    44,	 		1,				1,					'BannorAtlas44.dds'			    ),
		('ICON_ATLAS_BANNOR',					    48,	 		1,				1,					'BannorAtlas48.dds'			    ),
		('ICON_ATLAS_BANNOR',					    50,	 		1,				1,					'BannorAtlas50.dds'			    ),
		('ICON_ATLAS_BANNOR',					    64,	 		1,				1,					'BannorAtlas64.dds'			    ),
		('ICON_ATLAS_BANNOR',					    80,	 		1,				1,					'BannorAtlas80.dds'			    ),
		('ICON_ATLAS_BANNOR',					    200, 		1,				1,					'BannorAtlas200.dds'			),
		('ICON_ATLAS_BANNOR',					    256, 		1,				1,					'BannorAtlas256.dds'			),

		('ICON_ATLAS_DOVIELLO',					    22,	 		1,				1,					'DovielloAtlas22.dds'			    ),
		('ICON_ATLAS_DOVIELLO',					    30,	 		1,				1,					'DovielloAtlas30.dds'			    ),
		('ICON_ATLAS_DOVIELLO',					    36,	 		1,				1,					'DovielloAtlas36.dds'			    ),
		('ICON_ATLAS_DOVIELLO',					    44,	 		1,				1,					'DovielloAtlas44.dds'			    ),
		('ICON_ATLAS_DOVIELLO',					    48,	 		1,				1,					'DovielloAtlas48.dds'			    ),
		('ICON_ATLAS_DOVIELLO',					    50,	 		1,				1,					'DovielloAtlas50.dds'			    ),
		('ICON_ATLAS_DOVIELLO',					    64,	 		1,				1,					'DovielloAtlas64.dds'			    ),
		('ICON_ATLAS_DOVIELLO',					    80,	 		1,				1,					'DovielloAtlas80.dds'			    ),
		('ICON_ATLAS_DOVIELLO',					    200, 		1,				1,					'DovielloAtlas200.dds'			),
		('ICON_ATLAS_DOVIELLO',					    256, 		1,				1,					'DovielloAtlas256.dds'			),

		('ICON_ATLAS_ELOHIM',					    22,	 		1,				1,					'ElohimAtlas22.dds'			    ),
		('ICON_ATLAS_ELOHIM',					    30,	 		1,				1,					'ElohimAtlas30.dds'			    ),
		('ICON_ATLAS_ELOHIM',					    36,	 		1,				1,					'ElohimAtlas36.dds'			    ),
		('ICON_ATLAS_ELOHIM',					    44,	 		1,				1,					'ElohimAtlas44.dds'			    ),
		('ICON_ATLAS_ELOHIM',					    48,	 		1,				1,					'ElohimAtlas48.dds'			    ),
		('ICON_ATLAS_ELOHIM',					    50,	 		1,				1,					'ElohimAtlas50.dds'			    ),
		('ICON_ATLAS_ELOHIM',					    64,	 		1,				1,					'ElohimAtlas64.dds'			    ),
		('ICON_ATLAS_ELOHIM',					    80,	 		1,				1,					'ElohimAtlas80.dds'			    ),
		('ICON_ATLAS_ELOHIM',					    200, 		1,				1,					'ElohimAtlas200.dds'			),
		('ICON_ATLAS_ELOHIM',					    256, 		1,				1,					'ElohimAtlas256.dds'			),

		('ICON_ATLAS_GRIGORI',					    22,	 		1,				1,					'GrigoriAtlas22.dds'			    ),
		('ICON_ATLAS_GRIGORI',					    30,	 		1,				1,					'GrigoriAtlas30.dds'			    ),
		('ICON_ATLAS_GRIGORI',					    36,	 		1,				1,					'GrigoriAtlas36.dds'			    ),
		('ICON_ATLAS_GRIGORI',					    44,	 		1,				1,					'GrigoriAtlas44.dds'			    ),
		('ICON_ATLAS_GRIGORI',					    48,	 		1,				1,					'GrigoriAtlas48.dds'			    ),
		('ICON_ATLAS_GRIGORI',					    50,	 		1,				1,					'GrigoriAtlas50.dds'			    ),
		('ICON_ATLAS_GRIGORI',					    64,	 		1,				1,					'GrigoriAtlas64.dds'			    ),
		('ICON_ATLAS_GRIGORI',					    80,	 		1,				1,					'GrigoriAtlas80.dds'			    ),
		('ICON_ATLAS_GRIGORI',					    200, 		1,				1,					'GrigoriAtlas200.dds'			),
		('ICON_ATLAS_GRIGORI',					    256, 		1,				1,					'GrigoriAtlas256.dds'			),

		('ICON_ATLAS_INFERNAL',					    22,	 		1,				1,					'InfernalAtlas22.dds'			    ),
		('ICON_ATLAS_INFERNAL',					    30,	 		1,				1,					'InfernalAtlas30.dds'			    ),
		('ICON_ATLAS_INFERNAL',					    36,	 		1,				1,					'InfernalAtlas36.dds'			    ),
		('ICON_ATLAS_INFERNAL',					    44,	 		1,				1,					'InfernalAtlas44.dds'			    ),
		('ICON_ATLAS_INFERNAL',					    48,	 		1,				1,					'InfernalAtlas48.dds'			    ),
		('ICON_ATLAS_INFERNAL',					    50,	 		1,				1,					'InfernalAtlas50.dds'			    ),
		('ICON_ATLAS_INFERNAL',					    64,	 		1,				1,					'InfernalAtlas64.dds'			    ),
		('ICON_ATLAS_INFERNAL',					    80,	 		1,				1,					'InfernalAtlas80.dds'			    ),
		('ICON_ATLAS_INFERNAL',					    200, 		1,				1,					'InfernalAtlas200.dds'			),
		('ICON_ATLAS_INFERNAL',					    256, 		1,				1,					'InfernalAtlas256.dds'			),

		('ICON_ATLAS_AMURITE',					    22,	 		1,				1,					'AmuriteAtlas22.dds'			    ),
		('ICON_ATLAS_AMURITE',					    30,	 		1,				1,					'AmuriteAtlas30.dds'			    ),
		('ICON_ATLAS_AMURITE',					    36,	 		1,				1,					'AmuriteAtlas36.dds'			    ),
		('ICON_ATLAS_AMURITE',					    44,	 		1,				1,					'AmuriteAtlas44.dds'			    ),
		('ICON_ATLAS_AMURITE',					    48,	 		1,				1,					'AmuriteAtlas48.dds'			    ),
		('ICON_ATLAS_AMURITE',					    50,	 		1,				1,					'AmuriteAtlas50.dds'			    ),
		('ICON_ATLAS_AMURITE',					    64,	 		1,				1,					'AmuriteAtlas64.dds'			    ),
		('ICON_ATLAS_AMURITE',					    80,	 		1,				1,					'AmuriteAtlas80.dds'			    ),
		('ICON_ATLAS_AMURITE',					    200, 		1,				1,					'AmuriteAtlas200.dds'			),
		('ICON_ATLAS_AMURITE',					    256, 		1,				1,					'AmuriteAtlas256.dds'			),

		('ICON_ATLAS_BALSERAPH',					    22,	 		1,				1,					'BalseraphAtlas22.dds'			    ),
		('ICON_ATLAS_BALSERAPH',					    30,	 		1,				1,					'BalseraphAtlas30.dds'			    ),
		('ICON_ATLAS_BALSERAPH',					    36,	 		1,				1,					'BalseraphAtlas36.dds'			    ),
		('ICON_ATLAS_BALSERAPH',					    44,	 		1,				1,					'BalseraphAtlas44.dds'			    ),
		('ICON_ATLAS_BALSERAPH',					    48,	 		1,				1,					'BalseraphAtlas48.dds'			    ),
		('ICON_ATLAS_BALSERAPH',					    50,	 		1,				1,					'BalseraphAtlas50.dds'			    ),
		('ICON_ATLAS_BALSERAPH',					    64,	 		1,				1,					'BalseraphAtlas64.dds'			    ),
		('ICON_ATLAS_BALSERAPH',					    80,	 		1,				1,					'BalseraphAtlas80.dds'			    ),
		('ICON_ATLAS_BALSERAPH',					    200, 		1,				1,					'BalseraphAtlas200.dds'			),
		('ICON_ATLAS_BALSERAPH',					    256, 		1,				1,					'BalseraphAtlas256.dds'			),

		('ICON_ATLAS_CALABIM',					    22,	 		1,				1,					'CalabimAtlas22.dds'			    ),
		('ICON_ATLAS_CALABIM',					    30,	 		1,				1,					'CalabimAtlas30.dds'			    ),
		('ICON_ATLAS_CALABIM',					    36,	 		1,				1,					'CalabimAtlas36.dds'			    ),
		('ICON_ATLAS_CALABIM',					    44,	 		1,				1,					'CalabimAtlas44.dds'			    ),
		('ICON_ATLAS_CALABIM',					    48,	 		1,				1,					'CalabimAtlas48.dds'			    ),
		('ICON_ATLAS_CALABIM',					    50,	 		1,				1,					'CalabimAtlas50.dds'			    ),
		('ICON_ATLAS_CALABIM',					    64,	 		1,				1,					'CalabimAtlas64.dds'			    ),
		('ICON_ATLAS_CALABIM',					    80,	 		1,				1,					'CalabimAtlas80.dds'			    ),
		('ICON_ATLAS_CALABIM',					    200, 		1,				1,					'CalabimAtlas200.dds'			),
		('ICON_ATLAS_CALABIM',					    256, 		1,				1,					'CalabimAtlas256.dds'			),

		('ICON_ATLAS_HIPPUS',					    22,	 		1,				1,					'HippusAtlas22.dds'			    ),
		('ICON_ATLAS_HIPPUS',					    30,	 		1,				1,					'HippusAtlas30.dds'			    ),
		('ICON_ATLAS_HIPPUS',					    36,	 		1,				1,					'HippusAtlas36.dds'			    ),
		('ICON_ATLAS_HIPPUS',					    44,	 		1,				1,					'HippusAtlas44.dds'			    ),
		('ICON_ATLAS_HIPPUS',					    48,	 		1,				1,					'HippusAtlas48.dds'			    ),
		('ICON_ATLAS_HIPPUS',					    50,	 		1,				1,					'HippusAtlas50.dds'			    ),
		('ICON_ATLAS_HIPPUS',					    64,	 		1,				1,					'HippusAtlas64.dds'			    ),
		('ICON_ATLAS_HIPPUS',					    80,	 		1,				1,					'HippusAtlas80.dds'			    ),
		('ICON_ATLAS_HIPPUS',					    200, 		1,				1,					'HippusAtlas200.dds'			),
		('ICON_ATLAS_HIPPUS',					    256, 		1,				1,					'HippusAtlas256.dds'			),

		('ICON_ATLAS_ILLIANS',					    22,	 		1,				1,					'IllianAtlas22.dds'			    ),
		('ICON_ATLAS_ILLIANS',					    30,	 		1,				1,					'IllianAtlas30.dds'			    ),
		('ICON_ATLAS_ILLIANS',					    36,	 		1,				1,					'IllianAtlas36.dds'			    ),
		('ICON_ATLAS_ILLIANS',					    44,	 		1,				1,					'IllianAtlas44.dds'			    ),
		('ICON_ATLAS_ILLIANS',					    48,	 		1,				1,					'IllianAtlas48.dds'			    ),
		('ICON_ATLAS_ILLIANS',					    50,	 		1,				1,					'IllianAtlas50.dds'			    ),
		('ICON_ATLAS_ILLIANS',					    64,	 		1,				1,					'IllianAtlas64.dds'			    ),
		('ICON_ATLAS_ILLIANS',					    80,	 		1,				1,					'IllianAtlas80.dds'			    ),
		('ICON_ATLAS_ILLIANS',					    200, 		1,				1,					'IllianAtlas200.dds'			),
		('ICON_ATLAS_ILLIANS',					    256, 		1,				1,					'IllianAtlas256.dds'			),

		('ICON_ATLAS_KURIOTATES',					    22,	 		1,				1,					'KuriotatesAtlas22.dds'			    ),
		('ICON_ATLAS_KURIOTATES',					    30,	 		1,				1,					'KuriotatesAtlas30.dds'			    ),
		('ICON_ATLAS_KURIOTATES',					    36,	 		1,				1,					'KuriotatesAtlas36.dds'			    ),
		('ICON_ATLAS_KURIOTATES',					    44,	 		1,				1,					'KuriotatesAtlas44.dds'			    ),
		('ICON_ATLAS_KURIOTATES',					    48,	 		1,				1,					'KuriotatesAtlas48.dds'			    ),
		('ICON_ATLAS_KURIOTATES',					    50,	 		1,				1,					'KuriotatesAtlas50.dds'			    ),
		('ICON_ATLAS_KURIOTATES',					    64,	 		1,				1,					'KuriotatesAtlas64.dds'			    ),
		('ICON_ATLAS_KURIOTATES',					    80,	 		1,				1,					'KuriotatesAtlas80.dds'			    ),
		('ICON_ATLAS_KURIOTATES',					    200, 		1,				1,					'KuriotatesAtlas200.dds'			),
		('ICON_ATLAS_KURIOTATES',					    256, 		1,				1,					'KuriotatesAtlas256.dds'			),

		('ICON_ATLAS_LJOSALFAR',					    22,	 		1,				1,					'LjosalfarAtlas22.dds'			    ),
		('ICON_ATLAS_LJOSALFAR',					    30,	 		1,				1,					'LjosalfarAtlas30.dds'			    ),
		('ICON_ATLAS_LJOSALFAR',					    36,	 		1,				1,					'LjosalfarAtlas36.dds'			    ),
		('ICON_ATLAS_LJOSALFAR',					    44,	 		1,				1,					'LjosalfarAtlas44.dds'			    ),
		('ICON_ATLAS_LJOSALFAR',					    48,	 		1,				1,					'LjosalfarAtlas48.dds'			    ),
		('ICON_ATLAS_LJOSALFAR',					    50,	 		1,				1,					'LjosalfarAtlas50.dds'			    ),
		('ICON_ATLAS_LJOSALFAR',					    64,	 		1,				1,					'LjosalfarAtlas64.dds'			    ),
		('ICON_ATLAS_LJOSALFAR',					    80,	 		1,				1,					'LjosalfarAtlas80.dds'			    ),
		('ICON_ATLAS_LJOSALFAR',					    200, 		1,				1,					'LjosalfarAtlas200.dds'			),
		('ICON_ATLAS_LJOSALFAR',					    256, 		1,				1,					'LjosalfarAtlas256.dds'			),

		('ICON_ATLAS_LUCHUIRP',					    22,	 		1,				1,					'LuchuirpAtlas22.dds'			    ),
		('ICON_ATLAS_LUCHUIRP',					    30,	 		1,				1,					'LuchuirpAtlas30.dds'			    ),
		('ICON_ATLAS_LUCHUIRP',					    36,	 		1,				1,					'LuchuirpAtlas36.dds'			    ),
		('ICON_ATLAS_LUCHUIRP',					    44,	 		1,				1,					'LuchuirpAtlas44.dds'			    ),
		('ICON_ATLAS_LUCHUIRP',					    48,	 		1,				1,					'LuchuirpAtlas48.dds'			    ),
		('ICON_ATLAS_LUCHUIRP',					    50,	 		1,				1,					'LuchuirpAtlas50.dds'			    ),
		('ICON_ATLAS_LUCHUIRP',					    64,	 		1,				1,					'LuchuirpAtlas64.dds'			    ),
		('ICON_ATLAS_LUCHUIRP',					    80,	 		1,				1,					'LuchuirpAtlas80.dds'			    ),
		('ICON_ATLAS_LUCHUIRP',					    200, 		1,				1,					'LuchuirpAtlas200.dds'			),
		('ICON_ATLAS_LUCHUIRP',					    256, 		1,				1,					'LuchuirpAtlas256.dds'			),

		('ICON_ATLAS_MALAKIM',					    22,	 		1,				1,					'MalakimAtlas22.dds'			    ),
		('ICON_ATLAS_MALAKIM',					    30,	 		1,				1,					'MalakimAtlas30.dds'			    ),
		('ICON_ATLAS_MALAKIM',					    36,	 		1,				1,					'MalakimAtlas36.dds'			    ),
		('ICON_ATLAS_MALAKIM',					    44,	 		1,				1,					'MalakimAtlas44.dds'			    ),
		('ICON_ATLAS_MALAKIM',					    48,	 		1,				1,					'MalakimAtlas48.dds'			    ),
		('ICON_ATLAS_MALAKIM',					    50,	 		1,				1,					'MalakimAtlas50.dds'			    ),
		('ICON_ATLAS_MALAKIM',					    64,	 		1,				1,					'MalakimAtlas64.dds'			    ),
		('ICON_ATLAS_MALAKIM',					    80,	 		1,				1,					'MalakimAtlas80.dds'			    ),
		('ICON_ATLAS_MALAKIM',					    200, 		1,				1,					'MalakimAtlas200.dds'			),
		('ICON_ATLAS_MALAKIM',					    256, 		1,				1,					'MalakimAtlas256.dds'			),

		('ICON_ATLAS_MERCURIAN',					    22,	 		1,				1,					'MercurianAtlas22.dds'			    ),
		('ICON_ATLAS_MERCURIAN',					    30,	 		1,				1,					'MercurianAtlas30.dds'			    ),
		('ICON_ATLAS_MERCURIAN',					    36,	 		1,				1,					'MercurianAtlas36.dds'			    ),
		('ICON_ATLAS_MERCURIAN',					    44,	 		1,				1,					'MercurianAtlas44.dds'			    ),
		('ICON_ATLAS_MERCURIAN',					    48,	 		1,				1,					'MercurianAtlas48.dds'			    ),
		('ICON_ATLAS_MERCURIAN',					    50,	 		1,				1,					'MercurianAtlas50.dds'			    ),
		('ICON_ATLAS_MERCURIAN',					    64,	 		1,				1,					'MercurianAtlas64.dds'			    ),
		('ICON_ATLAS_MERCURIAN',					    80,	 		1,				1,					'MercurianAtlas80.dds'			    ),
		('ICON_ATLAS_MERCURIAN',					    200, 		1,				1,					'MercurianAtlas200.dds'			),
		('ICON_ATLAS_MERCURIAN',					    256, 		1,				1,					'MercurianAtlas256.dds'			),

		('ICON_ATLAS_SHEAIM',					    22,	 		1,				1,					'SheaimAtlas22.dds'			    ),
		('ICON_ATLAS_SHEAIM',					    30,	 		1,				1,					'SheaimAtlas30.dds'			    ),
		('ICON_ATLAS_SHEAIM',					    36,	 		1,				1,					'SheaimAtlas36.dds'			    ),
		('ICON_ATLAS_SHEAIM',					    44,	 		1,				1,					'SheaimAtlas44.dds'			    ),
		('ICON_ATLAS_SHEAIM',					    48,	 		1,				1,					'SheaimAtlas48.dds'			    ),
		('ICON_ATLAS_SHEAIM',					    50,	 		1,				1,					'SheaimAtlas50.dds'			    ),
		('ICON_ATLAS_SHEAIM',					    64,	 		1,				1,					'SheaimAtlas64.dds'			    ),
		('ICON_ATLAS_SHEAIM',					    80,	 		1,				1,					'SheaimAtlas80.dds'			    ),
		('ICON_ATLAS_SHEAIM',					    200, 		1,				1,					'SheaimAtlas200.dds'			),
		('ICON_ATLAS_SHEAIM',					    256, 		1,				1,					'SheaimAtlas256.dds'			),

		('ICON_ATLAS_SIDAR',					    22,	 		1,				1,					'SidarAtlas22.dds'			    ),
		('ICON_ATLAS_SIDAR',					    30,	 		1,				1,					'SidarAtlas30.dds'			    ),
		('ICON_ATLAS_SIDAR',					    36,	 		1,				1,					'SidarAtlas36.dds'			    ),
		('ICON_ATLAS_SIDAR',					    44,	 		1,				1,					'SidarAtlas44.dds'			    ),
		('ICON_ATLAS_SIDAR',					    48,	 		1,				1,					'SidarAtlas48.dds'			    ),
		('ICON_ATLAS_SIDAR',					    50,	 		1,				1,					'SidarAtlas50.dds'			    ),
		('ICON_ATLAS_SIDAR',					    64,	 		1,				1,					'SidarAtlas64.dds'			    ),
		('ICON_ATLAS_SIDAR',					    80,	 		1,				1,					'SidarAtlas80.dds'			    ),
		('ICON_ATLAS_SIDAR',					    200, 		1,				1,					'SidarAtlas200.dds'			),
		('ICON_ATLAS_SIDAR',					    256, 		1,				1,					'SidarAtlas256.dds'			),

		('ICON_ATLAS_SVARTALFAR',					    22,	 		1,				1,					'SvartalfarAtlas22.dds'			    ),
		('ICON_ATLAS_SVARTALFAR',					    30,	 		1,				1,					'SvartalfarAtlas30.dds'			    ),
		('ICON_ATLAS_SVARTALFAR',					    36,	 		1,				1,					'SvartalfarAtlas36.dds'			    ),
		('ICON_ATLAS_SVARTALFAR',					    44,	 		1,				1,					'SvartalfarAtlas44.dds'			    ),
		('ICON_ATLAS_SVARTALFAR',					    48,	 		1,				1,					'SvartalfarAtlas48.dds'			    ),
		('ICON_ATLAS_SVARTALFAR',					    50,	 		1,				1,					'SvartalfarAtlas50.dds'			    ),
		('ICON_ATLAS_SVARTALFAR',					    64,	 		1,				1,					'SvartalfarAtlas64.dds'			    ),
		('ICON_ATLAS_SVARTALFAR',					    80,	 		1,				1,					'SvartalfarAtlas80.dds'			    ),
		('ICON_ATLAS_SVARTALFAR',					    200, 		1,				1,					'SvartalfarAtlas200.dds'			),
		('ICON_ATLAS_SVARTALFAR',					    256, 		1,				1,					'SvartalfarAtlas256.dds'			);

INSERT INTO IconDefinitions
		(Name,										Atlas,							'Index'				)
VALUES	('ICON_LEADER_ALEXIS',					    'ICON_ATLAS_LEADER_ALEXIS',		0					),
        ('ICON_SLTH_CIVILIZATION_LANUN',		    'ICON_ATLAS_LANUN',			    0			        ),
        ('ICON_SLTH_CIVILIZATION_KHAZAD',		    'ICON_ATLAS_KHAZAD',			0			        ),
        ('ICON_SLTH_CIVILIZATION_BANNOR',		    'ICON_ATLAS_BANNOR',			0			        ),
        ('ICON_SLTH_CIVILIZATION_DOVIELLO',		    'ICON_ATLAS_DOVIELLO',			0			        ),
        ('ICON_SLTH_CIVILIZATION_ELOHIM',		    'ICON_ATLAS_ELOHIM',			0			        ),
        ('ICON_SLTH_CIVILIZATION_GRIGORI',		    'ICON_ATLAS_GRIGORI',			0			        ),
        ('ICON_SLTH_CIVILIZATION_AMURITES',		    'ICON_ATLAS_AMURITE',			0			        ),
        ('ICON_SLTH_CIVILIZATION_BALSERAPHS',		'ICON_ATLAS_BALSERAPH',			0			        ),

        ('ICON_SLTH_CIVILIZATION_CALABIM',		    'ICON_ATLAS_CALABIM',			0			        ),
        ('ICON_SLTH_CIVILIZATION_HIPPUS',		    'ICON_ATLAS_HIPPUS',			0			        ),
        ('ICON_SLTH_CIVILIZATION_ILLIANS',		    'ICON_ATLAS_ILLIANS',			0			        ),
        ('ICON_SLTH_CIVILIZATION_KURIOTATES',		'ICON_ATLAS_KURIOTATES',		0			        ),
        ('ICON_SLTH_CIVILIZATION_LJOSALFAR',		'ICON_ATLAS_LJOSALFAR',			0			        ),
        ('ICON_SLTH_CIVILIZATION_LUCHUIRP',		    'ICON_ATLAS_LUCHUIRP',			0			        ),

        ('ICON_SLTH_CIVILIZATION_MALAKIM',		    'ICON_ATLAS_MALAKIM',			0			        ),
        ('ICON_SLTH_CIVILIZATION_MERCURIANS',		'ICON_ATLAS_MERCURIAN',			0			        ),
        ('ICON_SLTH_CIVILIZATION_SHEAIM',		    'ICON_ATLAS_SHEAIM',			0			        ),
        ('ICON_SLTH_CIVILIZATION_SIDAR',		    'ICON_ATLAS_SIDAR',			    0			        ),
        ('ICON_SLTH_CIVILIZATION_SVARTALFAR',		'ICON_ATLAS_SVARTALFAR',		0			        ),
        ('ICON_SLTH_CIVILIZATION_CLAN_OF_EMBERS',   'ICON_ATLAS_EXPANSION_1_CIVILIZATIONS',		2	    );
