INSERT INTO IconTextureAtlases
		(Name,									IconSize,	IconsPerRow,	IconsPerColumn,		Filename					)
VALUES	('ICON_ATLAS_LEADER_ALEXIS',				32,	 		1,				1,					'ICON_LEADER_ALEXIS_32.dds'		),
		('ICON_ATLAS_LEADER_ALEXIS',				45,	 		1,				1,					'ICON_LEADER_ALEXIS_45.dds'		),
		('ICON_ATLAS_LEADER_ALEXIS',				48,	 		1,				1,					'ICON_LEADER_ALEXIS_48.dds'		),
		('ICON_ATLAS_LEADER_ALEXIS',				50,	 		1,				1,					'ICON_LEADER_ALEXIS_50.dds'		),
		('ICON_ATLAS_LEADER_ALEXIS',				55,	 		1,				1,					'ICON_LEADER_ALEXIS_55.dds'		),
		('ICON_ATLAS_LEADER_ALEXIS',				64,			1,				1,					'ICON_LEADER_ALEXIS_64.dds'		),
		('ICON_ATLAS_LEADER_ALEXIS',				80,	 		1,				1,					'ICON_LEADER_ALEXIS_80.dds'		),
		('ICON_ATLAS_LEADER_ALEXIS',				200,	 	1,				1,					'ICON_LEADER_ALEXIS_200.dds'	),
		('ICON_ATLAS_LEADER_ALEXIS',				256,	 	1,				1,					'ICON_LEADER_ALEXIS_256.dds'	),

		('ICON_ATLAS_LEADER_AMELANCHIER',				32,	 		1,				1,					'ICON_LEADER_AMELANCHIER32.dds'		),
		('ICON_ATLAS_LEADER_AMELANCHIER',				45,	 		1,				1,					'ICON_LEADER_AMELANCHIER45.dds'		),
		('ICON_ATLAS_LEADER_AMELANCHIER',				48,	 		1,				1,					'ICON_LEADER_AMELANCHIER48.dds'		),
		('ICON_ATLAS_LEADER_AMELANCHIER',				50,	 		1,				1,					'ICON_LEADER_AMELANCHIER50.dds'		),
		('ICON_ATLAS_LEADER_AMELANCHIER',				55,	 		1,				1,					'ICON_LEADER_AMELANCHIER55.dds'		),
		('ICON_ATLAS_LEADER_AMELANCHIER',				64,			1,				1,					'ICON_LEADER_AMELANCHIER64.dds'		),
		('ICON_ATLAS_LEADER_AMELANCHIER',				80,	 		1,				1,					'ICON_LEADER_AMELANCHIER80.dds'		),
		('ICON_ATLAS_LEADER_AMELANCHIER',				200,	 	1,				1,					'ICON_LEADER_AMELANCHIER200.dds'	),
		('ICON_ATLAS_LEADER_AMELANCHIER',				256,	 	1,				1,					'ICON_LEADER_AMELANCHIER256.dds'	),

		('ICON_ATLAS_LEADER_ARENDEL',				32,	 		1,				1,					'ICON_LEADER_ARENDEL32.dds'		),
		('ICON_ATLAS_LEADER_ARENDEL',				45,	 		1,				1,					'ICON_LEADER_ARENDEL45.dds'		),
		('ICON_ATLAS_LEADER_ARENDEL',				48,	 		1,				1,					'ICON_LEADER_ARENDEL48.dds'		),
		('ICON_ATLAS_LEADER_ARENDEL',				50,	 		1,				1,					'ICON_LEADER_ARENDEL50.dds'		),
		('ICON_ATLAS_LEADER_ARENDEL',				55,	 		1,				1,					'ICON_LEADER_ARENDEL55.dds'		),
		('ICON_ATLAS_LEADER_ARENDEL',				64,			1,				1,					'ICON_LEADER_ARENDEL64.dds'		),
		('ICON_ATLAS_LEADER_ARENDEL',				80,	 		1,				1,					'ICON_LEADER_ARENDEL80.dds'		),
		('ICON_ATLAS_LEADER_ARENDEL',				200,	 	1,				1,					'ICON_LEADER_ARENDEL200.dds'	),
		('ICON_ATLAS_LEADER_ARENDEL',				256,	 	1,				1,					'ICON_LEADER_ARENDEL256.dds'	),

		('ICON_ATLAS_LEADER_ARTURUS',				32,	 		1,				1,					'ICON_LEADER_ARTURUS32.dds'		),
		('ICON_ATLAS_LEADER_ARTURUS',				45,	 		1,				1,					'ICON_LEADER_ARTURUS45.dds'		),
		('ICON_ATLAS_LEADER_ARTURUS',				48,	 		1,				1,					'ICON_LEADER_ARTURUS48.dds'		),
		('ICON_ATLAS_LEADER_ARTURUS',				50,	 		1,				1,					'ICON_LEADER_ARTURUS50.dds'		),
		('ICON_ATLAS_LEADER_ARTURUS',				55,	 		1,				1,					'ICON_LEADER_ARTURUS55.dds'		),
		('ICON_ATLAS_LEADER_ARTURUS',				64,			1,				1,					'ICON_LEADER_ARTURUS64.dds'		),
		('ICON_ATLAS_LEADER_ARTURUS',				80,	 		1,				1,					'ICON_LEADER_ARTURUS80.dds'		),
		('ICON_ATLAS_LEADER_ARTURUS',				200,	 	1,				1,					'ICON_LEADER_ARTURUS200.dds'	),
		('ICON_ATLAS_LEADER_ARTURUS',				256,	 	1,				1,					'ICON_LEADER_ARTURUS256.dds'	),

		('ICON_ATLAS_LEADER_AURIC',				32,	 		1,				1,					'ICON_LEADER_AURIC32.dds'		),
		('ICON_ATLAS_LEADER_AURIC',				45,	 		1,				1,					'ICON_LEADER_AURIC45.dds'		),
		('ICON_ATLAS_LEADER_AURIC',				48,	 		1,				1,					'ICON_LEADER_AURIC48.dds'		),
		('ICON_ATLAS_LEADER_AURIC',				50,	 		1,				1,					'ICON_LEADER_AURIC50.dds'		),
		('ICON_ATLAS_LEADER_AURIC',				55,	 		1,				1,					'ICON_LEADER_AURIC55.dds'		),
		('ICON_ATLAS_LEADER_AURIC',				64,			1,				1,					'ICON_LEADER_AURIC64.dds'		),
		('ICON_ATLAS_LEADER_AURIC',				80,	 		1,				1,					'ICON_LEADER_AURIC80.dds'		),
		('ICON_ATLAS_LEADER_AURIC',				200,	 	1,				1,					'ICON_LEADER_AURIC200.dds'	),
		('ICON_ATLAS_LEADER_AURIC',				256,	 	1,				1,					'ICON_LEADER_AURIC256.dds'	),

		('ICON_ATLAS_LEADER_BASIUM',				32,	 		1,				1,					'ICON_LEADER_BASIUM32.dds'		),
		('ICON_ATLAS_LEADER_BASIUM',				45,	 		1,				1,					'ICON_LEADER_BASIUM45.dds'		),
		('ICON_ATLAS_LEADER_BASIUM',				48,	 		1,				1,					'ICON_LEADER_BASIUM48.dds'		),
		('ICON_ATLAS_LEADER_BASIUM',				50,	 		1,				1,					'ICON_LEADER_BASIUM50.dds'		),
		('ICON_ATLAS_LEADER_BASIUM',				55,	 		1,				1,					'ICON_LEADER_BASIUM55.dds'		),
		('ICON_ATLAS_LEADER_BASIUM',				64,			1,				1,					'ICON_LEADER_BASIUM64.dds'		),
		('ICON_ATLAS_LEADER_BASIUM',				80,	 		1,				1,					'ICON_LEADER_BASIUM80.dds'		),
		('ICON_ATLAS_LEADER_BASIUM',				200,	 	1,				1,					'ICON_LEADER_BASIUM200.dds'	),
		('ICON_ATLAS_LEADER_BASIUM',				256,	 	1,				1,					'ICON_LEADER_BASIUM256.dds'	),

		('ICON_ATLAS_LEADER_BEERI',				32,	 		1,				1,					'ICON_LEADER_BEERI32.dds'		),
		('ICON_ATLAS_LEADER_BEERI',				45,	 		1,				1,					'ICON_LEADER_BEERI45.dds'		),
		('ICON_ATLAS_LEADER_BEERI',				48,	 		1,				1,					'ICON_LEADER_BEERI48.dds'		),
		('ICON_ATLAS_LEADER_BEERI',				50,	 		1,				1,					'ICON_LEADER_BEERI50.dds'		),
		('ICON_ATLAS_LEADER_BEERI',				55,	 		1,				1,					'ICON_LEADER_BEERI55.dds'		),
		('ICON_ATLAS_LEADER_BEERI',				64,			1,				1,					'ICON_LEADER_BEERI64.dds'		),
		('ICON_ATLAS_LEADER_BEERI',				80,	 		1,				1,					'ICON_LEADER_BEERI80.dds'		),
		('ICON_ATLAS_LEADER_BEERI',				200,	 	1,				1,					'ICON_LEADER_BEERI200.dds'	),
		('ICON_ATLAS_LEADER_BEERI',				256,	 	1,				1,					'ICON_LEADER_BEERI256.dds'	),

		('ICON_ATLAS_LEADER_CAPRIA',				32,	 		1,				1,					'ICON_LEADER_CAPRIA32.dds'		),
		('ICON_ATLAS_LEADER_CAPRIA',				45,	 		1,				1,					'ICON_LEADER_CAPRIA45.dds'		),
		('ICON_ATLAS_LEADER_CAPRIA',				48,	 		1,				1,					'ICON_LEADER_CAPRIA48.dds'		),
		('ICON_ATLAS_LEADER_CAPRIA',				50,	 		1,				1,					'ICON_LEADER_CAPRIA50.dds'		),
		('ICON_ATLAS_LEADER_CAPRIA',				55,	 		1,				1,					'ICON_LEADER_CAPRIA55.dds'		),
		('ICON_ATLAS_LEADER_CAPRIA',				64,			1,				1,					'ICON_LEADER_CAPRIA64.dds'		),
		('ICON_ATLAS_LEADER_CAPRIA',				80,	 		1,				1,					'ICON_LEADER_CAPRIA80.dds'		),
		('ICON_ATLAS_LEADER_CAPRIA',				200,	 	1,				1,					'ICON_LEADER_CAPRIA200.dds'	),
		('ICON_ATLAS_LEADER_CAPRIA',				256,	 	1,				1,					'ICON_LEADER_CAPRIA256.dds'	),

		('ICON_ATLAS_LEADER_CARDITH',				32,	 		1,				1,					'ICON_LEADER_CARDITH32.dds'		),
		('ICON_ATLAS_LEADER_CARDITH',				45,	 		1,				1,					'ICON_LEADER_CARDITH45.dds'		),
		('ICON_ATLAS_LEADER_CARDITH',				48,	 		1,				1,					'ICON_LEADER_CARDITH48.dds'		),
		('ICON_ATLAS_LEADER_CARDITH',				50,	 		1,				1,					'ICON_LEADER_CARDITH50.dds'		),
		('ICON_ATLAS_LEADER_CARDITH',				55,	 		1,				1,					'ICON_LEADER_CARDITH55.dds'		),
		('ICON_ATLAS_LEADER_CARDITH',				64,			1,				1,					'ICON_LEADER_CARDITH64.dds'		),
		('ICON_ATLAS_LEADER_CARDITH',				80,	 		1,				1,					'ICON_LEADER_CARDITH80.dds'		),
		('ICON_ATLAS_LEADER_CARDITH',				200,	 	1,				1,					'ICON_LEADER_CARDITH200.dds'	),
		('ICON_ATLAS_LEADER_CARDITH',				256,	 	1,				1,					'ICON_LEADER_CARDITH256.dds'	),

		('ICON_ATLAS_LEADER_CASSIEL',				32,	 		1,				1,					'ICON_LEADER_CASSIEL32.dds'		),
		('ICON_ATLAS_LEADER_CASSIEL',				45,	 		1,				1,					'ICON_LEADER_CASSIEL45.dds'		),
		('ICON_ATLAS_LEADER_CASSIEL',				48,	 		1,				1,					'ICON_LEADER_CASSIEL48.dds'		),
		('ICON_ATLAS_LEADER_CASSIEL',				50,	 		1,				1,					'ICON_LEADER_CASSIEL50.dds'		),
		('ICON_ATLAS_LEADER_CASSIEL',				55,	 		1,				1,					'ICON_LEADER_CASSIEL55.dds'		),
		('ICON_ATLAS_LEADER_CASSIEL',				64,			1,				1,					'ICON_LEADER_CASSIEL64.dds'		),
		('ICON_ATLAS_LEADER_CASSIEL',				80,	 		1,				1,					'ICON_LEADER_CASSIEL80.dds'		),
		('ICON_ATLAS_LEADER_CASSIEL',				200,	 	1,				1,					'ICON_LEADER_CASSIEL200.dds'	),
		('ICON_ATLAS_LEADER_CASSIEL',				256,	 	1,				1,					'ICON_LEADER_CASSIEL256.dds'	),

		('ICON_ATLAS_LEADER_CHARADON',				32,	 		1,				1,					'ICON_LEADER_CHARADON32.dds'		),
		('ICON_ATLAS_LEADER_CHARADON',				45,	 		1,				1,					'ICON_LEADER_CHARADON45.dds'		),
		('ICON_ATLAS_LEADER_CHARADON',				48,	 		1,				1,					'ICON_LEADER_CHARADON48.dds'		),
		('ICON_ATLAS_LEADER_CHARADON',				50,	 		1,				1,					'ICON_LEADER_CHARADON50.dds'		),
		('ICON_ATLAS_LEADER_CHARADON',				55,	 		1,				1,					'ICON_LEADER_CHARADON55.dds'		),
		('ICON_ATLAS_LEADER_CHARADON',				64,			1,				1,					'ICON_LEADER_CHARADON64.dds'		),
		('ICON_ATLAS_LEADER_CHARADON',				80,	 		1,				1,					'ICON_LEADER_CHARADON80.dds'		),
		('ICON_ATLAS_LEADER_CHARADON',				200,	 	1,				1,					'ICON_LEADER_CHARADON200.dds'	),
		('ICON_ATLAS_LEADER_CHARADON',				256,	 	1,				1,					'ICON_LEADER_CHARADON256.dds'	),

		('ICON_ATLAS_LEADER_DAIN',				32,	 		1,				1,					'ICON_LEADER_DAIN32.dds'		),
		('ICON_ATLAS_LEADER_DAIN',				45,	 		1,				1,					'ICON_LEADER_DAIN45.dds'		),
		('ICON_ATLAS_LEADER_DAIN',				48,	 		1,				1,					'ICON_LEADER_DAIN48.dds'		),
		('ICON_ATLAS_LEADER_DAIN',				50,	 		1,				1,					'ICON_LEADER_DAIN50.dds'		),
		('ICON_ATLAS_LEADER_DAIN',				55,	 		1,				1,					'ICON_LEADER_DAIN55.dds'		),
		('ICON_ATLAS_LEADER_DAIN',				64,			1,				1,					'ICON_LEADER_DAIN64.dds'		),
		('ICON_ATLAS_LEADER_DAIN',				80,	 		1,				1,					'ICON_LEADER_DAIN80.dds'		),
		('ICON_ATLAS_LEADER_DAIN',				200,	 	1,				1,					'ICON_LEADER_DAIN200.dds'	),
		('ICON_ATLAS_LEADER_DAIN',				256,	 	1,				1,					'ICON_LEADER_DAIN256.dds'	),

		('ICON_ATLAS_LEADER_DECIUS',				32,	 		1,				1,					'ICON_LEADER_DECIUS32.dds'		),
		('ICON_ATLAS_LEADER_DECIUS',				45,	 		1,				1,					'ICON_LEADER_DECIUS45.dds'		),
		('ICON_ATLAS_LEADER_DECIUS',				48,	 		1,				1,					'ICON_LEADER_DECIUS48.dds'		),
		('ICON_ATLAS_LEADER_DECIUS',				50,	 		1,				1,					'ICON_LEADER_DECIUS50.dds'		),
		('ICON_ATLAS_LEADER_DECIUS',				55,	 		1,				1,					'ICON_LEADER_DECIUS55.dds'		),
		('ICON_ATLAS_LEADER_DECIUS',				64,			1,				1,					'ICON_LEADER_DECIUS64.dds'		),
		('ICON_ATLAS_LEADER_DECIUS',				80,	 		1,				1,					'ICON_LEADER_DECIUS80.dds'		),
		('ICON_ATLAS_LEADER_DECIUS',				200,	 	1,				1,					'ICON_LEADER_DECIUS200.dds'	),
		('ICON_ATLAS_LEADER_DECIUS',				256,	 	1,				1,					'ICON_LEADER_DECIUS256.dds'	),

		('ICON_ATLAS_LEADER_EINION',				32,	 		1,				1,					'ICON_LEADER_EINION32.dds'		),
		('ICON_ATLAS_LEADER_EINION',				45,	 		1,				1,					'ICON_LEADER_EINION45.dds'		),
		('ICON_ATLAS_LEADER_EINION',				48,	 		1,				1,					'ICON_LEADER_EINION48.dds'		),
		('ICON_ATLAS_LEADER_EINION',				50,	 		1,				1,					'ICON_LEADER_EINION50.dds'		),
		('ICON_ATLAS_LEADER_EINION',				55,	 		1,				1,					'ICON_LEADER_EINION55.dds'		),
		('ICON_ATLAS_LEADER_EINION',				64,			1,				1,					'ICON_LEADER_EINION64.dds'		),
		('ICON_ATLAS_LEADER_EINION',				80,	 		1,				1,					'ICON_LEADER_EINION80.dds'		),
		('ICON_ATLAS_LEADER_EINION',				200,	 	1,				1,					'ICON_LEADER_EINION200.dds'	),
		('ICON_ATLAS_LEADER_EINION',				256,	 	1,				1,					'ICON_LEADER_EINION256.dds'	),

		('ICON_ATLAS_LEADER_ETHNE',				32,	 		1,				1,					'ICON_LEADER_ETHNE32.dds'		),
		('ICON_ATLAS_LEADER_ETHNE',				45,	 		1,				1,					'ICON_LEADER_ETHNE45.dds'		),
		('ICON_ATLAS_LEADER_ETHNE',				48,	 		1,				1,					'ICON_LEADER_ETHNE48.dds'		),
		('ICON_ATLAS_LEADER_ETHNE',				50,	 		1,				1,					'ICON_LEADER_ETHNE50.dds'		),
		('ICON_ATLAS_LEADER_ETHNE',				55,	 		1,				1,					'ICON_LEADER_ETHNE55.dds'		),
		('ICON_ATLAS_LEADER_ETHNE',				64,			1,				1,					'ICON_LEADER_ETHNE64.dds'		),
		('ICON_ATLAS_LEADER_ETHNE',				80,	 		1,				1,					'ICON_LEADER_ETHNE80.dds'		),
		('ICON_ATLAS_LEADER_ETHNE',				200,	 	1,				1,					'ICON_LEADER_ETHNE200.dds'	),
		('ICON_ATLAS_LEADER_ETHNE',				256,	 	1,				1,					'ICON_LEADER_ETHNE256.dds'	),

		('ICON_ATLAS_LEADER_FAERYL',				32,	 		1,				1,					'ICON_LEADER_FAERYL32.dds'		),
		('ICON_ATLAS_LEADER_FAERYL',				45,	 		1,				1,					'ICON_LEADER_FAERYL45.dds'		),
		('ICON_ATLAS_LEADER_FAERYL',				48,	 		1,				1,					'ICON_LEADER_FAERYL48.dds'		),
		('ICON_ATLAS_LEADER_FAERYL',				50,	 		1,				1,					'ICON_LEADER_FAERYL50.dds'		),
		('ICON_ATLAS_LEADER_FAERYL',				55,	 		1,				1,					'ICON_LEADER_FAERYL55.dds'		),
		('ICON_ATLAS_LEADER_FAERYL',				64,			1,				1,					'ICON_LEADER_FAERYL64.dds'		),
		('ICON_ATLAS_LEADER_FAERYL',				80,	 		1,				1,					'ICON_LEADER_FAERYL80.dds'		),
		('ICON_ATLAS_LEADER_FAERYL',				200,	 	1,				1,					'ICON_LEADER_FAERYL200.dds'	),
		('ICON_ATLAS_LEADER_FAERYL',				256,	 	1,				1,					'ICON_LEADER_FAERYL256.dds'	),

		('ICON_ATLAS_LEADER_FALAMAR',				32,	 		1,				1,					'ICON_LEADER_FALAMAR32.dds'		),
		('ICON_ATLAS_LEADER_FALAMAR',				45,	 		1,				1,					'ICON_LEADER_FALAMAR45.dds'		),
		('ICON_ATLAS_LEADER_FALAMAR',				48,	 		1,				1,					'ICON_LEADER_FALAMAR48.dds'		),
		('ICON_ATLAS_LEADER_FALAMAR',				50,	 		1,				1,					'ICON_LEADER_FALAMAR50.dds'		),
		('ICON_ATLAS_LEADER_FALAMAR',				55,	 		1,				1,					'ICON_LEADER_FALAMAR55.dds'		),
		('ICON_ATLAS_LEADER_FALAMAR',				64,			1,				1,					'ICON_LEADER_FALAMAR64.dds'		),
		('ICON_ATLAS_LEADER_FALAMAR',				80,	 		1,				1,					'ICON_LEADER_FALAMAR80.dds'		),
		('ICON_ATLAS_LEADER_FALAMAR',				200,	 	1,				1,					'ICON_LEADER_FALAMAR200.dds'	),
		('ICON_ATLAS_LEADER_FALAMAR',				256,	 	1,				1,					'ICON_LEADER_FALAMAR256.dds'	),

		('ICON_ATLAS_LEADER_FLAUROS',				32,	 		1,				1,					'ICON_LEADER_FLAUROS32.dds'		),
		('ICON_ATLAS_LEADER_FLAUROS',				45,	 		1,				1,					'ICON_LEADER_FLAUROS45.dds'		),
		('ICON_ATLAS_LEADER_FLAUROS',				48,	 		1,				1,					'ICON_LEADER_FLAUROS48.dds'		),
		('ICON_ATLAS_LEADER_FLAUROS',				50,	 		1,				1,					'ICON_LEADER_FLAUROS50.dds'		),
		('ICON_ATLAS_LEADER_FLAUROS',				55,	 		1,				1,					'ICON_LEADER_FLAUROS55.dds'		),
		('ICON_ATLAS_LEADER_FLAUROS',				64,			1,				1,					'ICON_LEADER_FLAUROS64.dds'		),
		('ICON_ATLAS_LEADER_FLAUROS',				80,	 		1,				1,					'ICON_LEADER_FLAUROS80.dds'		),
		('ICON_ATLAS_LEADER_FLAUROS',				200,	 	1,				1,					'ICON_LEADER_FLAUROS200.dds'	),
		('ICON_ATLAS_LEADER_FLAUROS',				256,	 	1,				1,					'ICON_LEADER_FLAUROS256.dds'	),

		('ICON_ATLAS_LEADER_GARRIM',				32,	 		1,				1,					'ICON_LEADER_GARRIM32.dds'		),
		('ICON_ATLAS_LEADER_GARRIM',				45,	 		1,				1,					'ICON_LEADER_GARRIM45.dds'		),
		('ICON_ATLAS_LEADER_GARRIM',				48,	 		1,				1,					'ICON_LEADER_GARRIM48.dds'		),
		('ICON_ATLAS_LEADER_GARRIM',				50,	 		1,				1,					'ICON_LEADER_GARRIM50.dds'		),
		('ICON_ATLAS_LEADER_GARRIM',				55,	 		1,				1,					'ICON_LEADER_GARRIM55.dds'		),
		('ICON_ATLAS_LEADER_GARRIM',				64,			1,				1,					'ICON_LEADER_GARRIM64.dds'		),
		('ICON_ATLAS_LEADER_GARRIM',				80,	 		1,				1,					'ICON_LEADER_GARRIM80.dds'		),
		('ICON_ATLAS_LEADER_GARRIM',				200,	 	1,				1,					'ICON_LEADER_GARRIM200.dds'	),
		('ICON_ATLAS_LEADER_GARRIM',				256,	 	1,				1,					'ICON_LEADER_GARRIM256.dds'	),

		('ICON_ATLAS_LEADER_HANNAH',				32,	 		1,				1,					'ICON_LEADER_HANNAH32.dds'		),
		('ICON_ATLAS_LEADER_HANNAH',				45,	 		1,				1,					'ICON_LEADER_HANNAH45.dds'		),
		('ICON_ATLAS_LEADER_HANNAH',				48,	 		1,				1,					'ICON_LEADER_HANNAH48.dds'		),
		('ICON_ATLAS_LEADER_HANNAH',				50,	 		1,				1,					'ICON_LEADER_HANNAH50.dds'		),
		('ICON_ATLAS_LEADER_HANNAH',				55,	 		1,				1,					'ICON_LEADER_HANNAH55.dds'		),
		('ICON_ATLAS_LEADER_HANNAH',				64,			1,				1,					'ICON_LEADER_HANNAH64.dds'		),
		('ICON_ATLAS_LEADER_HANNAH',				80,	 		1,				1,					'ICON_LEADER_HANNAH80.dds'		),
		('ICON_ATLAS_LEADER_HANNAH',				200,	 	1,				1,					'ICON_LEADER_HANNAH200.dds'	),
		('ICON_ATLAS_LEADER_HANNAH',				256,	 	1,				1,					'ICON_LEADER_HANNAH256.dds'	),

		('ICON_ATLAS_LEADER_HYBOREM',				32,	 		1,				1,					'ICON_LEADER_HYBOREM32.dds'		),
		('ICON_ATLAS_LEADER_HYBOREM',				45,	 		1,				1,					'ICON_LEADER_HYBOREM45.dds'		),
		('ICON_ATLAS_LEADER_HYBOREM',				48,	 		1,				1,					'ICON_LEADER_HYBOREM48.dds'		),
		('ICON_ATLAS_LEADER_HYBOREM',				50,	 		1,				1,					'ICON_LEADER_HYBOREM50.dds'		),
		('ICON_ATLAS_LEADER_HYBOREM',				55,	 		1,				1,					'ICON_LEADER_HYBOREM55.dds'		),
		('ICON_ATLAS_LEADER_HYBOREM',				64,			1,				1,					'ICON_LEADER_HYBOREM64.dds'		),
		('ICON_ATLAS_LEADER_HYBOREM',				80,	 		1,				1,					'ICON_LEADER_HYBOREM80.dds'		),
		('ICON_ATLAS_LEADER_HYBOREM',				200,	 	1,				1,					'ICON_LEADER_HYBOREM200.dds'	),
		('ICON_ATLAS_LEADER_HYBOREM',				256,	 	1,				1,					'ICON_LEADER_HYBOREM256.dds'	),

		('ICON_ATLAS_LEADER_JONAS',				32,	 		1,				1,					'ICON_LEADER_JONAS32.dds'		),
		('ICON_ATLAS_LEADER_JONAS',				45,	 		1,				1,					'ICON_LEADER_JONAS45.dds'		),
		('ICON_ATLAS_LEADER_JONAS',				48,	 		1,				1,					'ICON_LEADER_JONAS48.dds'		),
		('ICON_ATLAS_LEADER_JONAS',				50,	 		1,				1,					'ICON_LEADER_JONAS50.dds'		),
		('ICON_ATLAS_LEADER_JONAS',				55,	 		1,				1,					'ICON_LEADER_JONAS55.dds'		),
		('ICON_ATLAS_LEADER_JONAS',				64,			1,				1,					'ICON_LEADER_JONAS64.dds'		),
		('ICON_ATLAS_LEADER_JONAS',				80,	 		1,				1,					'ICON_LEADER_JONAS80.dds'		),
		('ICON_ATLAS_LEADER_JONAS',				200,	 	1,				1,					'ICON_LEADER_JONAS200.dds'	),
		('ICON_ATLAS_LEADER_JONAS',				256,	 	1,				1,					'ICON_LEADER_JONAS256.dds'	),

		('ICON_ATLAS_LEADER_KANDROS',				32,	 		1,				1,					'ICON_LEADER_KANDROS32.dds'		),
		('ICON_ATLAS_LEADER_KANDROS',				45,	 		1,				1,					'ICON_LEADER_KANDROS45.dds'		),
		('ICON_ATLAS_LEADER_KANDROS',				48,	 		1,				1,					'ICON_LEADER_KANDROS48.dds'		),
		('ICON_ATLAS_LEADER_KANDROS',				50,	 		1,				1,					'ICON_LEADER_KANDROS50.dds'		),
		('ICON_ATLAS_LEADER_KANDROS',				55,	 		1,				1,					'ICON_LEADER_KANDROS55.dds'		),
		('ICON_ATLAS_LEADER_KANDROS',				64,			1,				1,					'ICON_LEADER_KANDROS64.dds'		),
		('ICON_ATLAS_LEADER_KANDROS',				80,	 		1,				1,					'ICON_LEADER_KANDROS80.dds'		),
		('ICON_ATLAS_LEADER_KANDROS',				200,	 	1,				1,					'ICON_LEADER_KANDROS200.dds'	),
		('ICON_ATLAS_LEADER_KANDROS',				256,	 	1,				1,					'ICON_LEADER_KANDROS256.dds'	),

		('ICON_ATLAS_LEADER_KEELYN',				32,	 		1,				1,					'ICON_LEADER_KEELYN32.dds'		),
		('ICON_ATLAS_LEADER_KEELYN',				45,	 		1,				1,					'ICON_LEADER_KEELYN45.dds'		),
		('ICON_ATLAS_LEADER_KEELYN',				48,	 		1,				1,					'ICON_LEADER_KEELYN48.dds'		),
		('ICON_ATLAS_LEADER_KEELYN',				50,	 		1,				1,					'ICON_LEADER_KEELYN50.dds'		),
		('ICON_ATLAS_LEADER_KEELYN',				55,	 		1,				1,					'ICON_LEADER_KEELYN55.dds'		),
		('ICON_ATLAS_LEADER_KEELYN',				64,			1,				1,					'ICON_LEADER_KEELYN64.dds'		),
		('ICON_ATLAS_LEADER_KEELYN',				80,	 		1,				1,					'ICON_LEADER_KEELYN80.dds'		),
		('ICON_ATLAS_LEADER_KEELYN',				200,	 	1,				1,					'ICON_LEADER_KEELYN200.dds'	),
		('ICON_ATLAS_LEADER_KEELYN',				256,	 	1,				1,					'ICON_LEADER_KEELYN256.dds'	),

		('ICON_ATLAS_LEADER_MAHALA',				32,	 		1,				1,					'ICON_LEADER_MAHALA32.dds'		),
		('ICON_ATLAS_LEADER_MAHALA',				45,	 		1,				1,					'ICON_LEADER_MAHALA45.dds'		),
		('ICON_ATLAS_LEADER_MAHALA',				48,	 		1,				1,					'ICON_LEADER_MAHALA48.dds'		),
		('ICON_ATLAS_LEADER_MAHALA',				50,	 		1,				1,					'ICON_LEADER_MAHALA50.dds'		),
		('ICON_ATLAS_LEADER_MAHALA',				55,	 		1,				1,					'ICON_LEADER_MAHALA55.dds'		),
		('ICON_ATLAS_LEADER_MAHALA',				64,			1,				1,					'ICON_LEADER_MAHALA64.dds'		),
		('ICON_ATLAS_LEADER_MAHALA',				80,	 		1,				1,					'ICON_LEADER_MAHALA80.dds'		),
		('ICON_ATLAS_LEADER_MAHALA',				200,	 	1,				1,					'ICON_LEADER_MAHALA200.dds'	),
		('ICON_ATLAS_LEADER_MAHALA',				256,	 	1,				1,					'ICON_LEADER_MAHALA256.dds'	),

		('ICON_ATLAS_LEADER_OSGABELLA',				32,	 		1,				1,					'ICON_LEADER_OSGABELLA32.dds'		),
		('ICON_ATLAS_LEADER_OSGABELLA',				45,	 		1,				1,					'ICON_LEADER_OSGABELLA45.dds'		),
		('ICON_ATLAS_LEADER_OSGABELLA',				48,	 		1,				1,					'ICON_LEADER_OSGABELLA48.dds'		),
		('ICON_ATLAS_LEADER_OSGABELLA',				50,	 		1,				1,					'ICON_LEADER_OSGABELLA50.dds'		),
		('ICON_ATLAS_LEADER_OSGABELLA',				55,	 		1,				1,					'ICON_LEADER_OSGABELLA55.dds'		),
		('ICON_ATLAS_LEADER_OSGABELLA',				64,			1,				1,					'ICON_LEADER_OSGABELLA64.dds'		),
		('ICON_ATLAS_LEADER_OSGABELLA',				80,	 		1,				1,					'ICON_LEADER_OSGABELLA80.dds'		),
		('ICON_ATLAS_LEADER_OSGABELLA',				200,	 	1,				1,					'ICON_LEADER_OSGABELLA200.dds'	),
		('ICON_ATLAS_LEADER_OSGABELLA',				256,	 	1,				1,					'ICON_LEADER_OSGABELLA256.dds'	),

		('ICON_ATLAS_LEADER_PERPENTACH',				32,	 		1,				1,					'ICON_LEADER_PERPENTACH32.dds'		),
		('ICON_ATLAS_LEADER_PERPENTACH',				45,	 		1,				1,					'ICON_LEADER_PERPENTACH45.dds'		),
		('ICON_ATLAS_LEADER_PERPENTACH',				48,	 		1,				1,					'ICON_LEADER_PERPENTACH48.dds'		),
		('ICON_ATLAS_LEADER_PERPENTACH',				50,	 		1,				1,					'ICON_LEADER_PERPENTACH50.dds'		),
		('ICON_ATLAS_LEADER_PERPENTACH',				55,	 		1,				1,					'ICON_LEADER_PERPENTACH55.dds'		),
		('ICON_ATLAS_LEADER_PERPENTACH',				64,			1,				1,					'ICON_LEADER_PERPENTACH64.dds'		),
		('ICON_ATLAS_LEADER_PERPENTACH',				80,	 		1,				1,					'ICON_LEADER_PERPENTACH80.dds'		),
		('ICON_ATLAS_LEADER_PERPENTACH',				200,	 	1,				1,					'ICON_LEADER_PERPENTACH200.dds'	),
		('ICON_ATLAS_LEADER_PERPENTACH',				256,	 	1,				1,					'ICON_LEADER_PERPENTACH256.dds'	),

		('ICON_ATLAS_LEADER_RHOANNA',				32,	 		1,				1,					'ICON_LEADER_RHOANNA32.dds'		),
		('ICON_ATLAS_LEADER_RHOANNA',				45,	 		1,				1,					'ICON_LEADER_RHOANNA45.dds'		),
		('ICON_ATLAS_LEADER_RHOANNA',				48,	 		1,				1,					'ICON_LEADER_RHOANNA48.dds'		),
		('ICON_ATLAS_LEADER_RHOANNA',				50,	 		1,				1,					'ICON_LEADER_RHOANNA50.dds'		),
		('ICON_ATLAS_LEADER_RHOANNA',				55,	 		1,				1,					'ICON_LEADER_RHOANNA55.dds'		),
		('ICON_ATLAS_LEADER_RHOANNA',				64,			1,				1,					'ICON_LEADER_RHOANNA64.dds'		),
		('ICON_ATLAS_LEADER_RHOANNA',				80,	 		1,				1,					'ICON_LEADER_RHOANNA80.dds'		),
		('ICON_ATLAS_LEADER_RHOANNA',				200,	 	1,				1,					'ICON_LEADER_RHOANNA200.dds'	),
		('ICON_ATLAS_LEADER_RHOANNA',				256,	 	1,				1,					'ICON_LEADER_RHOANNA256.dds'	),

		('ICON_ATLAS_LEADER_SABATHIEL',				32,	 		1,				1,					'ICON_LEADER_SABATHIEL32.dds'		),
		('ICON_ATLAS_LEADER_SABATHIEL',				45,	 		1,				1,					'ICON_LEADER_SABATHIEL45.dds'		),
		('ICON_ATLAS_LEADER_SABATHIEL',				48,	 		1,				1,					'ICON_LEADER_SABATHIEL48.dds'		),
		('ICON_ATLAS_LEADER_SABATHIEL',				50,	 		1,				1,					'ICON_LEADER_SABATHIEL50.dds'		),
		('ICON_ATLAS_LEADER_SABATHIEL',				55,	 		1,				1,					'ICON_LEADER_SABATHIEL55.dds'		),
		('ICON_ATLAS_LEADER_SABATHIEL',				64,			1,				1,					'ICON_LEADER_SABATHIEL64.dds'		),
		('ICON_ATLAS_LEADER_SABATHIEL',				80,	 		1,				1,					'ICON_LEADER_SABATHIEL80.dds'		),
		('ICON_ATLAS_LEADER_SABATHIEL',				200,	 	1,				1,					'ICON_LEADER_SABATHIEL200.dds'	),
		('ICON_ATLAS_LEADER_SABATHIEL',				256,	 	1,				1,					'ICON_LEADER_SABATHIEL256.dds'	),

		('ICON_ATLAS_LEADER_SANDALPHON',				32,	 		1,				1,					'ICON_LEADER_SANDALPHON32.dds'		),
		('ICON_ATLAS_LEADER_SANDALPHON',				45,	 		1,				1,					'ICON_LEADER_SANDALPHON45.dds'		),
		('ICON_ATLAS_LEADER_SANDALPHON',				48,	 		1,				1,					'ICON_LEADER_SANDALPHON48.dds'		),
		('ICON_ATLAS_LEADER_SANDALPHON',				50,	 		1,				1,					'ICON_LEADER_SANDALPHON50.dds'		),
		('ICON_ATLAS_LEADER_SANDALPHON',				55,	 		1,				1,					'ICON_LEADER_SANDALPHON55.dds'		),
		('ICON_ATLAS_LEADER_SANDALPHON',				64,			1,				1,					'ICON_LEADER_SANDALPHON64.dds'		),
		('ICON_ATLAS_LEADER_SANDALPHON',				80,	 		1,				1,					'ICON_LEADER_SANDALPHON80.dds'		),
		('ICON_ATLAS_LEADER_SANDALPHON',				200,	 	1,				1,					'ICON_LEADER_SANDALPHON200.dds'	),
		('ICON_ATLAS_LEADER_SANDALPHON',				256,	 	1,				1,					'ICON_LEADER_SANDALPHON256.dds'	),

		('ICON_ATLAS_LEADER_SHEELBA',				32,	 		1,				1,					'ICON_LEADER_SHEELBA32.dds'		),
		('ICON_ATLAS_LEADER_SHEELBA',				45,	 		1,				1,					'ICON_LEADER_SHEELBA45.dds'		),
		('ICON_ATLAS_LEADER_SHEELBA',				48,	 		1,				1,					'ICON_LEADER_SHEELBA48.dds'		),
		('ICON_ATLAS_LEADER_SHEELBA',				50,	 		1,				1,					'ICON_LEADER_SHEELBA50.dds'		),
		('ICON_ATLAS_LEADER_SHEELBA',				55,	 		1,				1,					'ICON_LEADER_SHEELBA55.dds'		),
		('ICON_ATLAS_LEADER_SHEELBA',				64,			1,				1,					'ICON_LEADER_SHEELBA64.dds'		),
		('ICON_ATLAS_LEADER_SHEELBA',				80,	 		1,				1,					'ICON_LEADER_SHEELBA80.dds'		),
		('ICON_ATLAS_LEADER_SHEELBA',				200,	 	1,				1,					'ICON_LEADER_SHEELBA200.dds'	),
		('ICON_ATLAS_LEADER_SHEELBA',				256,	 	1,				1,					'ICON_LEADER_SHEELBA256.dds'	),

		('ICON_ATLAS_LEADER_TASUNKE',				32,	 		1,				1,					'ICON_LEADER_TASUNKE32.dds'		),
		('ICON_ATLAS_LEADER_TASUNKE',				45,	 		1,				1,					'ICON_LEADER_TASUNKE45.dds'		),
		('ICON_ATLAS_LEADER_TASUNKE',				48,	 		1,				1,					'ICON_LEADER_TASUNKE48.dds'		),
		('ICON_ATLAS_LEADER_TASUNKE',				50,	 		1,				1,					'ICON_LEADER_TASUNKE50.dds'		),
		('ICON_ATLAS_LEADER_TASUNKE',				55,	 		1,				1,					'ICON_LEADER_TASUNKE55.dds'		),
		('ICON_ATLAS_LEADER_TASUNKE',				64,			1,				1,					'ICON_LEADER_TASUNKE64.dds'		),
		('ICON_ATLAS_LEADER_TASUNKE',				80,	 		1,				1,					'ICON_LEADER_TASUNKE80.dds'		),
		('ICON_ATLAS_LEADER_TASUNKE',				200,	 	1,				1,					'ICON_LEADER_TASUNKE200.dds'	),
		('ICON_ATLAS_LEADER_TASUNKE',				256,	 	1,				1,					'ICON_LEADER_TASUNKE256.dds'	),

		('ICON_ATLAS_LEADER_TEBRYN',				32,	 		1,				1,					'ICON_LEADER_TEBRYN32.dds'		),
		('ICON_ATLAS_LEADER_TEBRYN',				45,	 		1,				1,					'ICON_LEADER_TEBRYN45.dds'		),
		('ICON_ATLAS_LEADER_TEBRYN',				48,	 		1,				1,					'ICON_LEADER_TEBRYN48.dds'		),
		('ICON_ATLAS_LEADER_TEBRYN',				50,	 		1,				1,					'ICON_LEADER_TEBRYN50.dds'		),
		('ICON_ATLAS_LEADER_TEBRYN',				55,	 		1,				1,					'ICON_LEADER_TEBRYN55.dds'		),
		('ICON_ATLAS_LEADER_TEBRYN',				64,			1,				1,					'ICON_LEADER_TEBRYN64.dds'		),
		('ICON_ATLAS_LEADER_TEBRYN',				80,	 		1,				1,					'ICON_LEADER_TEBRYN80.dds'		),
		('ICON_ATLAS_LEADER_TEBRYN',				200,	 	1,				1,					'ICON_LEADER_TEBRYN200.dds'	),
		('ICON_ATLAS_LEADER_TEBRYN',				256,	 	1,				1,					'ICON_LEADER_TEBRYN256.dds'	),

		('ICON_ATLAS_LEADER_THESSA',				32,	 		1,				1,					'ICON_LEADER_THESSA32.dds'		),
		('ICON_ATLAS_LEADER_THESSA',				45,	 		1,				1,					'ICON_LEADER_THESSA45.dds'		),
		('ICON_ATLAS_LEADER_THESSA',				48,	 		1,				1,					'ICON_LEADER_THESSA48.dds'		),
		('ICON_ATLAS_LEADER_THESSA',				50,	 		1,				1,					'ICON_LEADER_THESSA50.dds'		),
		('ICON_ATLAS_LEADER_THESSA',				55,	 		1,				1,					'ICON_LEADER_THESSA55.dds'		),
		('ICON_ATLAS_LEADER_THESSA',				64,			1,				1,					'ICON_LEADER_THESSA64.dds'		),
		('ICON_ATLAS_LEADER_THESSA',				80,	 		1,				1,					'ICON_LEADER_THESSA80.dds'		),
		('ICON_ATLAS_LEADER_THESSA',				200,	 	1,				1,					'ICON_LEADER_THESSA200.dds'	),
		('ICON_ATLAS_LEADER_THESSA',				256,	 	1,				1,					'ICON_LEADER_THESSA256.dds'	),

		('ICON_ATLAS_LEADER_VALLEDIA',				32,	 		1,				1,					'ICON_LEADER_VALLEDIA32.dds'		),
		('ICON_ATLAS_LEADER_VALLEDIA',				45,	 		1,				1,					'ICON_LEADER_VALLEDIA45.dds'		),
		('ICON_ATLAS_LEADER_VALLEDIA',				48,	 		1,				1,					'ICON_LEADER_VALLEDIA48.dds'		),
		('ICON_ATLAS_LEADER_VALLEDIA',				50,	 		1,				1,					'ICON_LEADER_VALLEDIA50.dds'		),
		('ICON_ATLAS_LEADER_VALLEDIA',				55,	 		1,				1,					'ICON_LEADER_VALLEDIA55.dds'		),
		('ICON_ATLAS_LEADER_VALLEDIA',				64,			1,				1,					'ICON_LEADER_VALLEDIA64.dds'		),
		('ICON_ATLAS_LEADER_VALLEDIA',				80,	 		1,				1,					'ICON_LEADER_VALLEDIA80.dds'		),
		('ICON_ATLAS_LEADER_VALLEDIA',				200,	 	1,				1,					'ICON_LEADER_VALLEDIA200.dds'	),
		('ICON_ATLAS_LEADER_VALLEDIA',				256,	 	1,				1,					'ICON_LEADER_VALLEDIA256.dds'	),

		('ICON_ATLAS_LEADER_THESSALONICA',				32,	 		1,				1,					'ICON_LEADER_THESSALONICA32.dds'		),
		('ICON_ATLAS_LEADER_THESSALONICA',				45,	 		1,				1,					'ICON_LEADER_THESSALONICA45.dds'		),
		('ICON_ATLAS_LEADER_THESSALONICA',				48,	 		1,				1,					'ICON_LEADER_THESSALONICA48.dds'		),
		('ICON_ATLAS_LEADER_THESSALONICA',				50,	 		1,				1,					'ICON_LEADER_THESSALONICA50.dds'		),
		('ICON_ATLAS_LEADER_THESSALONICA',				55,	 		1,				1,					'ICON_LEADER_THESSALONICA55.dds'		),
		('ICON_ATLAS_LEADER_THESSALONICA',				64,			1,				1,					'ICON_LEADER_THESSALONICA64.dds'		),
		('ICON_ATLAS_LEADER_THESSALONICA',				80,	 		1,				1,					'ICON_LEADER_THESSALONICA80.dds'		),
		('ICON_ATLAS_LEADER_THESSALONICA',				200,	 	1,				1,					'ICON_LEADER_THESSALONICA200.dds'	),
		('ICON_ATLAS_LEADER_THESSALONICA',				256,	 	1,				1,					'ICON_LEADER_THESSALONICA256.dds'	),

		('ICON_ATLAS_LEADER_VARN',				32,	 		1,				1,					'ICON_LEADER_VARN32.dds'		),
		('ICON_ATLAS_LEADER_VARN',				45,	 		1,				1,					'ICON_LEADER_VARN45.dds'		),
		('ICON_ATLAS_LEADER_VARN',				48,	 		1,				1,					'ICON_LEADER_VARN48.dds'		),
		('ICON_ATLAS_LEADER_VARN',				50,	 		1,				1,					'ICON_LEADER_VARN50.dds'		),
		('ICON_ATLAS_LEADER_VARN',				55,	 		1,				1,					'ICON_LEADER_VARN55.dds'		),
		('ICON_ATLAS_LEADER_VARN',				64,			1,				1,					'ICON_LEADER_VARN64.dds'		),
		('ICON_ATLAS_LEADER_VARN',				80,	 		1,				1,					'ICON_LEADER_VARN80.dds'		),
		('ICON_ATLAS_LEADER_VARN',				200,	 	1,				1,					'ICON_LEADER_VARN200.dds'	),
		('ICON_ATLAS_LEADER_VARN',				256,	 	1,				1,					'ICON_LEADER_VARN256.dds'	),

		('ICON_ATLAS_LANUN',					    22,	 		1,				1,					'LanunAtlasWhite22.dds'			),
		('ICON_ATLAS_LANUN',					    30,	 		1,				1,					'LanunAtlasWhite30.dds'			),
		('ICON_ATLAS_LANUN',					    36,	 		1,				1,					'LanunAtlasWhite36.dds'			),
		('ICON_ATLAS_LANUN',					    44,	 		1,				1,					'LanunAtlasWhite44.dds'			),
		('ICON_ATLAS_LANUN',					    48,	 		1,				1,					'LanunAtlasWhite48.dds'			),
		('ICON_ATLAS_LANUN',					    50,	 		1,				1,					'LanunAtlasWhite50.dds'			),
		('ICON_ATLAS_LANUN',					    64,	 		1,				1,					'LanunAtlasWhite64.dds'			),
		('ICON_ATLAS_LANUN',					    80,	 		1,				1,					'LanunAtlasWhite80.dds'			),
		('ICON_ATLAS_LANUN',					    200, 		1,				1,					'LanunAtlasWhite200.dds'		),
		('ICON_ATLAS_LANUN',					    256, 		1,				1,					'LanunAtlasWhite256.dds'		),
		('ICON_ATLAS_KHAZAD',					    22,	 		1,				1,					'KhazadAtlas22.dds'			    ),
		('ICON_ATLAS_KHAZAD',					    30,	 		1,				1,					'KhazadAtlas30.dds'			    ),
		('ICON_ATLAS_KHAZAD',					    36,	 		1,				1,					'KhazadAtlas36.dds'			    ),
		('ICON_ATLAS_KHAZAD',					    44,	 		1,				1,					'KhazadAtlas44.dds'			    ),
		('ICON_ATLAS_KHAZAD',					    48,	 		1,				1,					'KhazadAtlas48.dds'			    ),
		('ICON_ATLAS_KHAZAD',					    50,	 		1,				1,					'KhazadAtlas50.dds'			    ),
		('ICON_ATLAS_KHAZAD',					    64,	 		1,				1,					'KhazadAtlas64.dds'			    ),
		('ICON_ATLAS_KHAZAD',					    80,	 		1,				1,					'KhazadAtlas80.dds'			    ),
		('ICON_ATLAS_KHAZAD',					    200, 		1,				1,					'KhazadAtlas200.dds'			),
		('ICON_ATLAS_KHAZAD',					    256, 		1,				1,					'KhazadAtlas256.dds'			),

		('ICON_ATLAS_BANNOR',					    22,	 		1,				1,					'BannorAtlas22.dds'			    ),
		('ICON_ATLAS_BANNOR',					    30,	 		1,				1,					'BannorAtlas30.dds'			    ),
		('ICON_ATLAS_BANNOR',					    36,	 		1,				1,					'BannorAtlas36.dds'			    ),
		('ICON_ATLAS_BANNOR',					    44,	 		1,				1,					'BannorAtlas44.dds'			    ),
		('ICON_ATLAS_BANNOR',					    48,	 		1,				1,					'BannorAtlas48.dds'			    ),
		('ICON_ATLAS_BANNOR',					    50,	 		1,				1,					'BannorAtlas50.dds'			    ),
		('ICON_ATLAS_BANNOR',					    64,	 		1,				1,					'BannorAtlas64.dds'			    ),
		('ICON_ATLAS_BANNOR',					    80,	 		1,				1,					'BannorAtlas80.dds'			    ),
		('ICON_ATLAS_BANNOR',					    200, 		1,				1,					'BannorAtlas200.dds'			),
		('ICON_ATLAS_BANNOR',					    256, 		1,				1,					'BannorAtlas256.dds'			),

		('ICON_ATLAS_DOVIELLO',					    22,	 		1,				1,					'DovielloAtlas22.dds'			    ),
		('ICON_ATLAS_DOVIELLO',					    30,	 		1,				1,					'DovielloAtlas30.dds'			    ),
		('ICON_ATLAS_DOVIELLO',					    36,	 		1,				1,					'DovielloAtlas36.dds'			    ),
		('ICON_ATLAS_DOVIELLO',					    44,	 		1,				1,					'DovielloAtlas44.dds'			    ),
		('ICON_ATLAS_DOVIELLO',					    48,	 		1,				1,					'DovielloAtlas48.dds'			    ),
		('ICON_ATLAS_DOVIELLO',					    50,	 		1,				1,					'DovielloAtlas50.dds'			    ),
		('ICON_ATLAS_DOVIELLO',					    64,	 		1,				1,					'DovielloAtlas64.dds'			    ),
		('ICON_ATLAS_DOVIELLO',					    80,	 		1,				1,					'DovielloAtlas80.dds'			    ),
		('ICON_ATLAS_DOVIELLO',					    200, 		1,				1,					'DovielloAtlas200.dds'			),
		('ICON_ATLAS_DOVIELLO',					    256, 		1,				1,					'DovielloAtlas256.dds'			),

		('ICON_ATLAS_ELOHIM',					    22,	 		1,				1,					'ElohimAtlas22.dds'			    ),
		('ICON_ATLAS_ELOHIM',					    30,	 		1,				1,					'ElohimAtlas30.dds'			    ),
		('ICON_ATLAS_ELOHIM',					    36,	 		1,				1,					'ElohimAtlas36.dds'			    ),
		('ICON_ATLAS_ELOHIM',					    44,	 		1,				1,					'ElohimAtlas44.dds'			    ),
		('ICON_ATLAS_ELOHIM',					    48,	 		1,				1,					'ElohimAtlas48.dds'			    ),
		('ICON_ATLAS_ELOHIM',					    50,	 		1,				1,					'ElohimAtlas50.dds'			    ),
		('ICON_ATLAS_ELOHIM',					    64,	 		1,				1,					'ElohimAtlas64.dds'			    ),
		('ICON_ATLAS_ELOHIM',					    80,	 		1,				1,					'ElohimAtlas80.dds'			    ),
		('ICON_ATLAS_ELOHIM',					    200, 		1,				1,					'ElohimAtlas200.dds'			),
		('ICON_ATLAS_ELOHIM',					    256, 		1,				1,					'ElohimAtlas256.dds'			),

		('ICON_ATLAS_GRIGORI',					    22,	 		1,				1,					'GrigoriAtlas22.dds'			    ),
		('ICON_ATLAS_GRIGORI',					    30,	 		1,				1,					'GrigoriAtlas30.dds'			    ),
		('ICON_ATLAS_GRIGORI',					    36,	 		1,				1,					'GrigoriAtlas36.dds'			    ),
		('ICON_ATLAS_GRIGORI',					    44,	 		1,				1,					'GrigoriAtlas44.dds'			    ),
		('ICON_ATLAS_GRIGORI',					    48,	 		1,				1,					'GrigoriAtlas48.dds'			    ),
		('ICON_ATLAS_GRIGORI',					    50,	 		1,				1,					'GrigoriAtlas50.dds'			    ),
		('ICON_ATLAS_GRIGORI',					    64,	 		1,				1,					'GrigoriAtlas64.dds'			    ),
		('ICON_ATLAS_GRIGORI',					    80,	 		1,				1,					'GrigoriAtlas80.dds'			    ),
		('ICON_ATLAS_GRIGORI',					    200, 		1,				1,					'GrigoriAtlas200.dds'			),
		('ICON_ATLAS_GRIGORI',					    256, 		1,				1,					'GrigoriAtlas256.dds'			),

		('ICON_ATLAS_INFERNAL',					    22,	 		1,				1,					'InfernalAtlas22.dds'			    ),
		('ICON_ATLAS_INFERNAL',					    30,	 		1,				1,					'InfernalAtlas30.dds'			    ),
		('ICON_ATLAS_INFERNAL',					    36,	 		1,				1,					'InfernalAtlas36.dds'			    ),
		('ICON_ATLAS_INFERNAL',					    44,	 		1,				1,					'InfernalAtlas44.dds'			    ),
		('ICON_ATLAS_INFERNAL',					    48,	 		1,				1,					'InfernalAtlas48.dds'			    ),
		('ICON_ATLAS_INFERNAL',					    50,	 		1,				1,					'InfernalAtlas50.dds'			    ),
		('ICON_ATLAS_INFERNAL',					    64,	 		1,				1,					'InfernalAtlas64.dds'			    ),
		('ICON_ATLAS_INFERNAL',					    80,	 		1,				1,					'InfernalAtlas80.dds'			    ),
		('ICON_ATLAS_INFERNAL',					    200, 		1,				1,					'InfernalAtlas200.dds'			),
		('ICON_ATLAS_INFERNAL',					    256, 		1,				1,					'InfernalAtlas256.dds'			),

		('ICON_ATLAS_AMURITE',					    22,	 		1,				1,					'AmuriteAtlas22.dds'			    ),
		('ICON_ATLAS_AMURITE',					    30,	 		1,				1,					'AmuriteAtlas30.dds'			    ),
		('ICON_ATLAS_AMURITE',					    36,	 		1,				1,					'AmuriteAtlas36.dds'			    ),
		('ICON_ATLAS_AMURITE',					    44,	 		1,				1,					'AmuriteAtlas44.dds'			    ),
		('ICON_ATLAS_AMURITE',					    48,	 		1,				1,					'AmuriteAtlas48.dds'			    ),
		('ICON_ATLAS_AMURITE',					    50,	 		1,				1,					'AmuriteAtlas50.dds'			    ),
		('ICON_ATLAS_AMURITE',					    64,	 		1,				1,					'AmuriteAtlas64.dds'			    ),
		('ICON_ATLAS_AMURITE',					    80,	 		1,				1,					'AmuriteAtlas80.dds'			    ),
		('ICON_ATLAS_AMURITE',					    200, 		1,				1,					'AmuriteAtlas200.dds'			),
		('ICON_ATLAS_AMURITE',					    256, 		1,				1,					'AmuriteAtlas256.dds'			),

		('ICON_ATLAS_BALSERAPH',					    22,	 		1,				1,					'BalseraphAtlas22.dds'			    ),
		('ICON_ATLAS_BALSERAPH',					    30,	 		1,				1,					'BalseraphAtlas30.dds'			    ),
		('ICON_ATLAS_BALSERAPH',					    36,	 		1,				1,					'BalseraphAtlas36.dds'			    ),
		('ICON_ATLAS_BALSERAPH',					    44,	 		1,				1,					'BalseraphAtlas44.dds'			    ),
		('ICON_ATLAS_BALSERAPH',					    48,	 		1,				1,					'BalseraphAtlas48.dds'			    ),
		('ICON_ATLAS_BALSERAPH',					    50,	 		1,				1,					'BalseraphAtlas50.dds'			    ),
		('ICON_ATLAS_BALSERAPH',					    64,	 		1,				1,					'BalseraphAtlas64.dds'			    ),
		('ICON_ATLAS_BALSERAPH',					    80,	 		1,				1,					'BalseraphAtlas80.dds'			    ),
		('ICON_ATLAS_BALSERAPH',					    200, 		1,				1,					'BalseraphAtlas200.dds'			),
		('ICON_ATLAS_BALSERAPH',					    256, 		1,				1,					'BalseraphAtlas256.dds'			),

		('ICON_ATLAS_CALABIM',					    22,	 		1,				1,					'CalabimAtlas22.dds'			    ),
		('ICON_ATLAS_CALABIM',					    30,	 		1,				1,					'CalabimAtlas30.dds'			    ),
		('ICON_ATLAS_CALABIM',					    36,	 		1,				1,					'CalabimAtlas36.dds'			    ),
		('ICON_ATLAS_CALABIM',					    44,	 		1,				1,					'CalabimAtlas44.dds'			    ),
		('ICON_ATLAS_CALABIM',					    48,	 		1,				1,					'CalabimAtlas48.dds'			    ),
		('ICON_ATLAS_CALABIM',					    50,	 		1,				1,					'CalabimAtlas50.dds'			    ),
		('ICON_ATLAS_CALABIM',					    64,	 		1,				1,					'CalabimAtlas64.dds'			    ),
		('ICON_ATLAS_CALABIM',					    80,	 		1,				1,					'CalabimAtlas80.dds'			    ),
		('ICON_ATLAS_CALABIM',					    200, 		1,				1,					'CalabimAtlas200.dds'			),
		('ICON_ATLAS_CALABIM',					    256, 		1,				1,					'CalabimAtlas256.dds'			),

		('ICON_ATLAS_HIPPUS',					    22,	 		1,				1,					'HippusAtlas22.dds'			    ),
		('ICON_ATLAS_HIPPUS',					    30,	 		1,				1,					'HippusAtlas30.dds'			    ),
		('ICON_ATLAS_HIPPUS',					    36,	 		1,				1,					'HippusAtlas36.dds'			    ),
		('ICON_ATLAS_HIPPUS',					    44,	 		1,				1,					'HippusAtlas44.dds'			    ),
		('ICON_ATLAS_HIPPUS',					    48,	 		1,				1,					'HippusAtlas48.dds'			    ),
		('ICON_ATLAS_HIPPUS',					    50,	 		1,				1,					'HippusAtlas50.dds'			    ),
		('ICON_ATLAS_HIPPUS',					    64,	 		1,				1,					'HippusAtlas64.dds'			    ),
		('ICON_ATLAS_HIPPUS',					    80,	 		1,				1,					'HippusAtlas80.dds'			    ),
		('ICON_ATLAS_HIPPUS',					    200, 		1,				1,					'HippusAtlas200.dds'			),
		('ICON_ATLAS_HIPPUS',					    256, 		1,				1,					'HippusAtlas256.dds'			),

		('ICON_ATLAS_ILLIANS',					    22,	 		1,				1,					'IllianAtlas22.dds'			    ),
		('ICON_ATLAS_ILLIANS',					    30,	 		1,				1,					'IllianAtlas30.dds'			    ),
		('ICON_ATLAS_ILLIANS',					    36,	 		1,				1,					'IllianAtlas36.dds'			    ),
		('ICON_ATLAS_ILLIANS',					    44,	 		1,				1,					'IllianAtlas44.dds'			    ),
		('ICON_ATLAS_ILLIANS',					    48,	 		1,				1,					'IllianAtlas48.dds'			    ),
		('ICON_ATLAS_ILLIANS',					    50,	 		1,				1,					'IllianAtlas50.dds'			    ),
		('ICON_ATLAS_ILLIANS',					    64,	 		1,				1,					'IllianAtlas64.dds'			    ),
		('ICON_ATLAS_ILLIANS',					    80,	 		1,				1,					'IllianAtlas80.dds'			    ),
		('ICON_ATLAS_ILLIANS',					    200, 		1,				1,					'IllianAtlas200.dds'			),
		('ICON_ATLAS_ILLIANS',					    256, 		1,				1,					'IllianAtlas256.dds'			),

		('ICON_ATLAS_KURIOTATES',					    22,	 		1,				1,					'KuriotatesAtlas22.dds'			    ),
		('ICON_ATLAS_KURIOTATES',					    30,	 		1,				1,					'KuriotatesAtlas30.dds'			    ),
		('ICON_ATLAS_KURIOTATES',					    36,	 		1,				1,					'KuriotatesAtlas36.dds'			    ),
		('ICON_ATLAS_KURIOTATES',					    44,	 		1,				1,					'KuriotatesAtlas44.dds'			    ),
		('ICON_ATLAS_KURIOTATES',					    48,	 		1,				1,					'KuriotatesAtlas48.dds'			    ),
		('ICON_ATLAS_KURIOTATES',					    50,	 		1,				1,					'KuriotatesAtlas50.dds'			    ),
		('ICON_ATLAS_KURIOTATES',					    64,	 		1,				1,					'KuriotatesAtlas64.dds'			    ),
		('ICON_ATLAS_KURIOTATES',					    80,	 		1,				1,					'KuriotatesAtlas80.dds'			    ),
		('ICON_ATLAS_KURIOTATES',					    200, 		1,				1,					'KuriotatesAtlas200.dds'			),
		('ICON_ATLAS_KURIOTATES',					    256, 		1,				1,					'KuriotatesAtlas256.dds'			),

		('ICON_ATLAS_LJOSALFAR',					    22,	 		1,				1,					'LjosalfarAtlas22.dds'			    ),
		('ICON_ATLAS_LJOSALFAR',					    30,	 		1,				1,					'LjosalfarAtlas30.dds'			    ),
		('ICON_ATLAS_LJOSALFAR',					    36,	 		1,				1,					'LjosalfarAtlas36.dds'			    ),
		('ICON_ATLAS_LJOSALFAR',					    44,	 		1,				1,					'LjosalfarAtlas44.dds'			    ),
		('ICON_ATLAS_LJOSALFAR',					    48,	 		1,				1,					'LjosalfarAtlas48.dds'			    ),
		('ICON_ATLAS_LJOSALFAR',					    50,	 		1,				1,					'LjosalfarAtlas50.dds'			    ),
		('ICON_ATLAS_LJOSALFAR',					    64,	 		1,				1,					'LjosalfarAtlas64.dds'			    ),
		('ICON_ATLAS_LJOSALFAR',					    80,	 		1,				1,					'LjosalfarAtlas80.dds'			    ),
		('ICON_ATLAS_LJOSALFAR',					    200, 		1,				1,					'LjosalfarAtlas200.dds'			),
		('ICON_ATLAS_LJOSALFAR',					    256, 		1,				1,					'LjosalfarAtlas256.dds'			),

		('ICON_ATLAS_LUCHUIRP',					    22,	 		1,				1,					'LuchuirpAtlas22.dds'			    ),
		('ICON_ATLAS_LUCHUIRP',					    30,	 		1,				1,					'LuchuirpAtlas30.dds'			    ),
		('ICON_ATLAS_LUCHUIRP',					    36,	 		1,				1,					'LuchuirpAtlas36.dds'			    ),
		('ICON_ATLAS_LUCHUIRP',					    44,	 		1,				1,					'LuchuirpAtlas44.dds'			    ),
		('ICON_ATLAS_LUCHUIRP',					    48,	 		1,				1,					'LuchuirpAtlas48.dds'			    ),
		('ICON_ATLAS_LUCHUIRP',					    50,	 		1,				1,					'LuchuirpAtlas50.dds'			    ),
		('ICON_ATLAS_LUCHUIRP',					    64,	 		1,				1,					'LuchuirpAtlas64.dds'			    ),
		('ICON_ATLAS_LUCHUIRP',					    80,	 		1,				1,					'LuchuirpAtlas80.dds'			    ),
		('ICON_ATLAS_LUCHUIRP',					    200, 		1,				1,					'LuchuirpAtlas200.dds'			),
		('ICON_ATLAS_LUCHUIRP',					    256, 		1,				1,					'LuchuirpAtlas256.dds'			),

		('ICON_ATLAS_MALAKIM',					    22,	 		1,				1,					'MalakimAtlas22.dds'			    ),
		('ICON_ATLAS_MALAKIM',					    30,	 		1,				1,					'MalakimAtlas30.dds'			    ),
		('ICON_ATLAS_MALAKIM',					    36,	 		1,				1,					'MalakimAtlas36.dds'			    ),
		('ICON_ATLAS_MALAKIM',					    44,	 		1,				1,					'MalakimAtlas44.dds'			    ),
		('ICON_ATLAS_MALAKIM',					    48,	 		1,				1,					'MalakimAtlas48.dds'			    ),
		('ICON_ATLAS_MALAKIM',					    50,	 		1,				1,					'MalakimAtlas50.dds'			    ),
		('ICON_ATLAS_MALAKIM',					    64,	 		1,				1,					'MalakimAtlas64.dds'			    ),
		('ICON_ATLAS_MALAKIM',					    80,	 		1,				1,					'MalakimAtlas80.dds'			    ),
		('ICON_ATLAS_MALAKIM',					    200, 		1,				1,					'MalakimAtlas200.dds'			),
		('ICON_ATLAS_MALAKIM',					    256, 		1,				1,					'MalakimAtlas256.dds'			),

		('ICON_ATLAS_MERCURIAN',					    22,	 		1,				1,					'MercurianAtlas22.dds'			    ),
		('ICON_ATLAS_MERCURIAN',					    30,	 		1,				1,					'MercurianAtlas30.dds'			    ),
		('ICON_ATLAS_MERCURIAN',					    36,	 		1,				1,					'MercurianAtlas36.dds'			    ),
		('ICON_ATLAS_MERCURIAN',					    44,	 		1,				1,					'MercurianAtlas44.dds'			    ),
		('ICON_ATLAS_MERCURIAN',					    48,	 		1,				1,					'MercurianAtlas48.dds'			    ),
		('ICON_ATLAS_MERCURIAN',					    50,	 		1,				1,					'MercurianAtlas50.dds'			    ),
		('ICON_ATLAS_MERCURIAN',					    64,	 		1,				1,					'MercurianAtlas64.dds'			    ),
		('ICON_ATLAS_MERCURIAN',					    80,	 		1,				1,					'MercurianAtlas80.dds'			    ),
		('ICON_ATLAS_MERCURIAN',					    200, 		1,				1,					'MercurianAtlas200.dds'			),
		('ICON_ATLAS_MERCURIAN',					    256, 		1,				1,					'MercurianAtlas256.dds'			),

		('ICON_ATLAS_SHEAIM',					    22,	 		1,				1,					'SheaimAtlas22.dds'			    ),
		('ICON_ATLAS_SHEAIM',					    30,	 		1,				1,					'SheaimAtlas30.dds'			    ),
		('ICON_ATLAS_SHEAIM',					    36,	 		1,				1,					'SheaimAtlas36.dds'			    ),
		('ICON_ATLAS_SHEAIM',					    44,	 		1,				1,					'SheaimAtlas44.dds'			    ),
		('ICON_ATLAS_SHEAIM',					    48,	 		1,				1,					'SheaimAtlas48.dds'			    ),
		('ICON_ATLAS_SHEAIM',					    50,	 		1,				1,					'SheaimAtlas50.dds'			    ),
		('ICON_ATLAS_SHEAIM',					    64,	 		1,				1,					'SheaimAtlas64.dds'			    ),
		('ICON_ATLAS_SHEAIM',					    80,	 		1,				1,					'SheaimAtlas80.dds'			    ),
		('ICON_ATLAS_SHEAIM',					    200, 		1,				1,					'SheaimAtlas200.dds'			),
		('ICON_ATLAS_SHEAIM',					    256, 		1,				1,					'SheaimAtlas256.dds'			),

		('ICON_ATLAS_SIDAR',					    22,	 		1,				1,					'SidarAtlas22.dds'			    ),
		('ICON_ATLAS_SIDAR',					    30,	 		1,				1,					'SidarAtlas30.dds'			    ),
		('ICON_ATLAS_SIDAR',					    36,	 		1,				1,					'SidarAtlas36.dds'			    ),
		('ICON_ATLAS_SIDAR',					    44,	 		1,				1,					'SidarAtlas44.dds'			    ),
		('ICON_ATLAS_SIDAR',					    48,	 		1,				1,					'SidarAtlas48.dds'			    ),
		('ICON_ATLAS_SIDAR',					    50,	 		1,				1,					'SidarAtlas50.dds'			    ),
		('ICON_ATLAS_SIDAR',					    64,	 		1,				1,					'SidarAtlas64.dds'			    ),
		('ICON_ATLAS_SIDAR',					    80,	 		1,				1,					'SidarAtlas80.dds'			    ),
		('ICON_ATLAS_SIDAR',					    200, 		1,				1,					'SidarAtlas200.dds'			),
		('ICON_ATLAS_SIDAR',					    256, 		1,				1,					'SidarAtlas256.dds'			),

		('ICON_ATLAS_SVARTALFAR',					    22,	 		1,				1,					'SvartalfarAtlas22.dds'			    ),
		('ICON_ATLAS_SVARTALFAR',					    30,	 		1,				1,					'SvartalfarAtlas30.dds'			    ),
		('ICON_ATLAS_SVARTALFAR',					    36,	 		1,				1,					'SvartalfarAtlas36.dds'			    ),
		('ICON_ATLAS_SVARTALFAR',					    44,	 		1,				1,					'SvartalfarAtlas44.dds'			    ),
		('ICON_ATLAS_SVARTALFAR',					    48,	 		1,				1,					'SvartalfarAtlas48.dds'			    ),
		('ICON_ATLAS_SVARTALFAR',					    50,	 		1,				1,					'SvartalfarAtlas50.dds'			    ),
		('ICON_ATLAS_SVARTALFAR',					    64,	 		1,				1,					'SvartalfarAtlas64.dds'			    ),
		('ICON_ATLAS_SVARTALFAR',					    80,	 		1,				1,					'SvartalfarAtlas80.dds'			    ),
		('ICON_ATLAS_SVARTALFAR',					    200, 		1,				1,					'SvartalfarAtlas200.dds'			),
		('ICON_ATLAS_SVARTALFAR',					    256, 		1,				1,					'SvartalfarAtlas256.dds'			);

INSERT INTO IconDefinitions
		(Name,										Atlas,							'Index'				)
VALUES	('ICON_LEADER_ALEXIS',					    'ICON_ATLAS_LEADER_ALEXIS',		0					),
        ('ICON_LEADER_AMELANCHIER',					'ICON_ATLAS_LEADER_AMELANCHIER',		0					),
        ('ICON_LEADER_ARTURUS',					    'ICON_ATLAS_LEADER_ARTURUS',		0					),
        ('ICON_LEADER_ARENDEL',					    'ICON_ATLAS_LEADER_ARENDEL',		0					),
        ('ICON_LEADER_AURIC',					    'ICON_ATLAS_LEADER_AURIC',		0					),
        ('ICON_LEADER_BASIUM',					    'ICON_ATLAS_LEADER_BASIUM',		0					),
        ('ICON_LEADER_BEERI',					    'ICON_ATLAS_LEADER_BEERI',		0					),
        ('ICON_LEADER_CAPRIA',					    'ICON_ATLAS_LEADER_CAPRIA',		0					),
        ('ICON_LEADER_CARDITH',					    'ICON_ATLAS_LEADER_CARDITH',		0					),
        ('ICON_LEADER_CASSIEL',					    'ICON_ATLAS_LEADER_CASSIEL',		0					),
        ('ICON_LEADER_CHARADON',					'ICON_ATLAS_LEADER_CHARADON',		0					),
        ('ICON_LEADER_DAIN',					    'ICON_ATLAS_LEADER_DAIN',		0					),
        ('ICON_LEADER_DECIUS_BANNOR',					    'ICON_ATLAS_LEADER_DECIUS',		0					),
        ('ICON_LEADER_DECIUS_CALABIM',					    'ICON_ATLAS_LEADER_DECIUS',		0					),
        ('ICON_LEADER_DECIUS_MALAKIM',					    'ICON_ATLAS_LEADER_DECIUS',		0					),
        ('ICON_LEADER_EINION',					    'ICON_ATLAS_LEADER_EINION',		0					),
        ('ICON_LEADER_ETHNE',					    'ICON_ATLAS_LEADER_ETHNE',		0					),
        ('ICON_LEADER_FAERYL',					    'ICON_ATLAS_LEADER_FAERYL',		0					),
        ('ICON_LEADER_FALAMAR',					    'ICON_ATLAS_LEADER_FALAMAR',		0					),
        ('ICON_LEADER_FLAUROS',					    'ICON_ATLAS_LEADER_FLAUROS',		0					),
        ('ICON_LEADER_GARRIM',					    'ICON_ATLAS_LEADER_GARRIM',		0					),
        ('ICON_LEADER_HANNAH',					    'ICON_ATLAS_LEADER_HANNAH',		0					),
        ('ICON_LEADER_HYBOREM',					    'ICON_ATLAS_LEADER_HYBOREM',		0					),
        ('ICON_LEADER_JONAS',					    'ICON_ATLAS_LEADER_JONAS',		0					),
        ('ICON_LEADER_KANDROS',					    'ICON_ATLAS_LEADER_KANDROS',		0					),
        ('ICON_LEADER_KEELYN',					    'ICON_ATLAS_LEADER_KEELYN',		0					),
        ('ICON_LEADER_MAHALA',					    'ICON_ATLAS_LEADER_MAHALA',		0					),
        ('ICON_LEADER_OSGABELLA',					'ICON_ATLAS_LEADER_OSGABELLA',		0					),
        ('ICON_LEADER_PERPENTACH',					    'ICON_ATLAS_LEADER_PERPENTACH',		0					),
        ('ICON_LEADER_RHOANNA',					    'ICON_ATLAS_LEADER_RHOANNA',		0					),
        ('ICON_LEADER_SABATHIEL',					    'ICON_ATLAS_LEADER_SABATHIEL',		0					),
        ('ICON_LEADER_SANDALPHON',					    'ICON_ATLAS_LEADER_SANDALPHON',		0					),
        ('ICON_LEADER_SHEELBA',					    'ICON_ATLAS_LEADER_SHEELBA',		0					),
        ('ICON_LEADER_TASUNKE',					    'ICON_ATLAS_LEADER_TASUNKE',		0					),
        ('ICON_LEADER_TEBRYN',					    'ICON_ATLAS_LEADER_TEBRYN',		0					),
        ('ICON_LEADER_THESSA',					    'ICON_ATLAS_LEADER_THESSA',		0					),
        ('ICON_LEADER_THESSALONICA',					    'ICON_ATLAS_LEADER_THESSALONICA',		0					),
        ('ICON_LEADER_VALLEDIA',					    'ICON_ATLAS_LEADER_VALLEDIA',		0					),
        ('ICON_LEADER_VARN',					    'ICON_ATLAS_LEADER_VARN',		0					),
        ('ICON_SLTH_CIVILIZATION_LANUN',		    'ICON_ATLAS_LANUN',			    0			        ),
        ('ICON_SLTH_CIVILIZATION_KHAZAD',		    'ICON_ATLAS_KHAZAD',			0			        ),
        ('ICON_SLTH_CIVILIZATION_BANNOR',		    'ICON_ATLAS_BANNOR',			0			        ),
        ('ICON_SLTH_CIVILIZATION_DOVIELLO',		    'ICON_ATLAS_DOVIELLO',			0			        ),
        ('ICON_SLTH_CIVILIZATION_ELOHIM',		    'ICON_ATLAS_ELOHIM',			0			        ),
        ('ICON_SLTH_CIVILIZATION_GRIGORI',		    'ICON_ATLAS_GRIGORI',			0			        ),
        ('ICON_SLTH_CIVILIZATION_AMURITES',		    'ICON_ATLAS_AMURITE',			0			        ),
        ('ICON_SLTH_CIVILIZATION_BALSERAPHS',		'ICON_ATLAS_BALSERAPH',			0			        ),
        ('ICON_SLTH_CIVILIZATION_CALABIM',		    'ICON_ATLAS_CALABIM',			0			        ),
        ('ICON_SLTH_CIVILIZATION_HIPPUS',		    'ICON_ATLAS_HIPPUS',			0			        ),
        ('ICON_SLTH_CIVILIZATION_ILLIANS',		    'ICON_ATLAS_ILLIANS',			0			        ),
        ('ICON_SLTH_CIVILIZATION_KURIOTATES',		'ICON_ATLAS_KURIOTATES',		0			        ),
        ('ICON_SLTH_CIVILIZATION_LJOSALFAR',		'ICON_ATLAS_LJOSALFAR',			0			        ),
        ('ICON_SLTH_CIVILIZATION_LUCHUIRP',		    'ICON_ATLAS_LUCHUIRP',			0			        ),
        ('ICON_SLTH_CIVILIZATION_MALAKIM',		    'ICON_ATLAS_MALAKIM',			0			        ),
        ('ICON_SLTH_CIVILIZATION_MERCURIANS',		'ICON_ATLAS_MERCURIAN',			0			        ),
        ('ICON_SLTH_CIVILIZATION_SHEAIM',		    'ICON_ATLAS_SHEAIM',			0			        ),
        ('ICON_SLTH_CIVILIZATION_SIDAR',		    'ICON_ATLAS_SIDAR',			    0			        ),
        ('ICON_SLTH_CIVILIZATION_SVARTALFAR',		'ICON_ATLAS_SVARTALFAR',		0			        ),
        ('ICON_SLTH_CIVILIZATION_CLAN_OF_EMBERS',   'ICON_ATLAS_EXPANSION_1_CIVILIZATIONS',		2	    );
