INSERT INTO IconTextureAtlases(Name, IconSize, IconsPerRow, IconsPerColumn, Filename) VALUES
('ICON_SLTH_BUILDINGS_ATLAS_0', '256', '8', '1', 'Slth_Buildings_Atlas_0_256.dds'),
('ICON_SLTH_BUILDINGS_ATLAS_0', '128', '8', '1', 'Slth_Buildings_Atlas_0_128.dds'),
('ICON_SLTH_BUILDINGS_ATLAS_0', '80', '8', '1', 'Slth_Buildings_Atlas_0_80.dds'),
('ICON_SLTH_BUILDINGS_ATLAS_0', '50', '8', '1', 'Slth_Buildings_Atlas_0_50.dds'),
('ICON_SLTH_BUILDINGS_ATLAS_0', '38', '8', '1', 'Slth_Buildings_Atlas_0_38.dds'),
('ICON_SLTH_BUILDINGS_ATLAS_0', '32', '8', '1', 'Slth_Buildings_Atlas_0_32.dds'),
('ICON_SLTH_BUILDINGS_ATLAS_1', '256', '3', '1', 'Slth_Buildings_Atlas_1_256.dds'),
('ICON_SLTH_BUILDINGS_ATLAS_1', '128', '3', '1', 'Slth_Buildings_Atlas_1_128.dds'),
('ICON_SLTH_BUILDINGS_ATLAS_1', '80', '3', '1', 'Slth_Buildings_Atlas_1_80.dds'),
('ICON_SLTH_BUILDINGS_ATLAS_1', '50', '3', '1', 'Slth_Buildings_Atlas_1_50.dds'),
('ICON_SLTH_BUILDINGS_ATLAS_1', '38', '3', '1', 'Slth_Buildings_Atlas_1_38.dds'),
('ICON_SLTH_BUILDINGS_ATLAS_1', '32', '3', '1', 'Slth_Buildings_Atlas_1_32.dds');

INSERT INTO IconDefinitions(Name, Atlas, 'Index')VALUES
('ICON_BUILDING_ACHERONS_LAIR', 'ICON_SLTH_BUILDINGS_ATLAS_0', 0),
('ICON_SLTH_BUILDING_ADULARIA_CHAMBER', 'ICON_SLTH_BUILDINGS_ATLAS_0', 3),
('ICON_SLTH_BUILDING_ALTAR_OF_THE_LUONNOTAR', 'ICON_SLTH_BUILDINGS_ATLAS_0', 4),
('ICON_SLTH_BUILDING_AQUEDUCT', 'ICON_SLTH_BUILDINGS_ATLAS_0', 6),
('ICON_SLTH_BUILDING_ARCHERY_RANGE', 'ICON_SLTH_BUILDINGS_ATLAS_0', 7),
('ICON_SLTH_BUILDING_ASYLUM', 'ICON_SLTH_BUILDINGS_ATLAS_0', 8),
('ICON_SLTH_BUILDING_BLASTING_WORKSHOP', 'ICON_SLTH_BUILDINGS_ATLAS_0', 9),
('ICON_SLTH_BUILDING_CAVE_OF_ANCESTORS', 'ICON_SLTH_BUILDINGS_ATLAS_0', 10),
('ICON_SLTH_BUILDING_CELESTIAL_COMPASS', 'ICON_SLTH_BUILDINGS_ATLAS_0', 11),
('ICON_SLTH_BUILDING_CITADEL_OF_LIGHT', 'ICON_SLTH_BUILDINGS_ATLAS_0', 12),
('ICON_SLTH_BUILDING_CODE_OF_JUNIL', 'ICON_SLTH_BUILDINGS_ATLAS_0', 14),
('ICON_SLTH_BUILDING_CROWN_OF_AKHARIEN', 'ICON_SLTH_BUILDINGS_ATLAS_0', 15),
('ICON_SLTH_BUILDING_DANCING_BEAR', 'ICON_SLTH_BUILDINGS_ATLAS_0', 16),
('ICON_SLTH_BUILDING_DESERT_SHRINE', 'ICON_SLTH_BUILDINGS_ATLAS_0', 17),
('ICON_SLTH_BUILDING_DUNGEON', 'ICON_SLTH_BUILDINGS_ATLAS_0', 18),
('ICON_SLTH_BUILDING_DWARF_CAGE', 'ICON_SLTH_BUILDINGS_ATLAS_0', 19),
('ICON_SLTH_BUILDING_DWARVEN_SMITHY', 'ICON_SLTH_BUILDINGS_ATLAS_0', 20),
('ICON_SLTH_BUILDING_ELDER_COUNCIL', 'ICON_SLTH_BUILDINGS_ATLAS_0', 21),
('ICON_SLTH_BUILDING_ELF_CAGE', 'ICON_SLTH_BUILDINGS_ATLAS_0', 22),
('ICON_SLTH_BUILDING_EYES_AND_EARS_NETWORK', 'ICON_SLTH_BUILDINGS_ATLAS_0', 23),
('ICON_SLTH_BUILDING_FREAK_SHOW', 'ICON_SLTH_BUILDINGS_ATLAS_0', 24),
('ICON_SLTH_BUILDING_GAMBLING_HOUSE', 'ICON_SLTH_BUILDINGS_ATLAS_0', 25),
('ICON_SLTH_BUILDING_GORILLA_CAGE', 'ICON_SLTH_BUILDINGS_ATLAS_0', 26),
('ICON_SLTH_BUILDING_GOVERNORS_MANOR', 'ICON_SLTH_BUILDINGS_ATLAS_0', 27),
('ICON_SLTH_BUILDING_GUILD_OF_HAMMERS', 'ICON_SLTH_BUILDINGS_ATLAS_0', 28),
('ICON_SLTH_BUILDING_HALL_OF_MIRRORS', 'ICON_SLTH_BUILDINGS_ATLAS_0', 29),
('ICON_SLTH_BUILDING_HARBOR_LANUN', 'ICON_SLTH_BUILDINGS_ATLAS_0', 30),
('ICON_SLTH_BUILDING_HEROIC_EPIC', 'ICON_SLTH_BUILDINGS_ATLAS_0', 31),
('ICON_SLTH_BUILDING_HUMAN_CAGE', 'ICON_SLTH_BUILDINGS_ATLAS_0', 32),
('ICON_SLTH_BUILDING_HUNTING_LODGE', 'ICON_SLTH_BUILDINGS_ATLAS_0', 33),
('ICON_SLTH_BUILDING_INFERNAL_GRIMOIRE', 'ICON_SLTH_BUILDINGS_ATLAS_0', 34),
('ICON_SLTH_BUILDING_INN', 'ICON_SLTH_BUILDINGS_ATLAS_0', 35),
('ICON_SLTH_BUILDING_JEWELER', 'ICON_SLTH_BUILDINGS_ATLAS_0', 36),
('ICON_SLTH_BUILDING_LION_CAGE', 'ICON_SLTH_BUILDINGS_ATLAS_0', 37),
('ICON_SLTH_BUILDING_MERCURIAN_GATE', 'ICON_SLTH_BUILDINGS_ATLAS_0', 38),
('ICON_SLTH_BUILDING_MOKKAS_CAULDRON', 'ICON_SLTH_BUILDINGS_ATLAS_0', 39),
('ICON_SLTH_BUILDING_NATIONAL_EPIC', 'ICON_SLTH_BUILDINGS_ATLAS_0', 40),
('ICON_SLTH_BUILDING_NOX_NOCTIS', 'ICON_SLTH_BUILDINGS_ATLAS_0', 41),
('ICON_SLTH_BUILDING_OBSIDIAN_GATE', 'ICON_SLTH_BUILDINGS_ATLAS_0', 42),
('ICON_SLTH_BUILDING_ORC_CAGE', 'ICON_SLTH_BUILDINGS_ATLAS_0', 43),
('ICON_SLTH_BUILDING_PALLENS_ENGINE', 'ICON_SLTH_BUILDINGS_ATLAS_0', 44),
('ICON_SLTH_BUILDING_PLANAR_GATE', 'ICON_SLTH_BUILDINGS_ATLAS_0', 46),
('ICON_SLTH_BUILDING_PUBLIC_BATHS', 'ICON_SLTH_BUILDINGS_ATLAS_0', 47),
('ICON_SLTH_BUILDING_RELIQUARY', 'ICON_SLTH_BUILDINGS_ATLAS_0', 48),
('ICON_SLTH_BUILDING_RIDE_OF_THE_NINE_KINGS', 'ICON_SLTH_BUILDINGS_ATLAS_0', 49),
('ICON_SLTH_BUILDING_SCULPTORS_STUDIO', 'ICON_SLTH_BUILDINGS_ATLAS_0', 50),
('ICON_SLTH_BUILDING_SIEGE_WORKSHOP', 'ICON_SLTH_BUILDINGS_ATLAS_0', 51),
('ICON_SLTH_BUILDING_SMOKEHOUSE', 'ICON_SLTH_BUILDINGS_ATLAS_0', 52),
('ICON_SLTH_BUILDING_SMUGGLERS_PORT', 'ICON_SLTH_BUILDINGS_ATLAS_0', 53),
('ICON_SLTH_BUILDING_SONG_OF_AUTUMN', 'ICON_SLTH_BUILDINGS_ATLAS_0', 54),
('ICON_SLTH_BUILDING_SOUL_FORGE', 'ICON_SLTH_BUILDINGS_ATLAS_0', 55),
('ICON_SLTH_BUILDING_STIGMATA_ON_THE_UNBORN', 'ICON_SLTH_BUILDINGS_ATLAS_0', 56),
('ICON_SLTH_BUILDING_TABLETS_OF_BAMBUR', 'ICON_SLTH_BUILDINGS_ATLAS_0', 57),
('ICON_SLTH_BUILDING_TAILOR', 'ICON_SLTH_BUILDINGS_ATLAS_0', 58),
('ICON_SLTH_BUILDING_TEMPLE_OF_THE_HAND', 'ICON_SLTH_BUILDINGS_ATLAS_0', 59),
('ICON_SLTH_BUILDING_THE_DRAGONS_HORDE', 'ICON_SLTH_BUILDINGS_ATLAS_0', 60),
('ICON_SLTH_BUILDING_THE_NECRONOMICON', 'ICON_SLTH_BUILDINGS_ATLAS_0', 61),
('ICON_SLTH_BUILDING_THE_NEXUS', 'ICON_SLTH_BUILDINGS_ATLAS_0', 62),
('ICON_SLTH_BUILDING_TIGER_CAGE', 'ICON_SLTH_BUILDINGS_ATLAS_0', 63),
('ICON_SLTH_BUILDING_WARRENS', 'ICON_SLTH_BUILDINGS_ATLAS_1', 1),
('ICON_SLTH_BUILDING_WOLF_PEN', 'ICON_SLTH_BUILDINGS_ATLAS_1', 2),
('ICON_SLTH_BUILDING_ALTAR_OF_THE_LUONNOTAR_ANOINTED', 'ICON_SLTH_BUILDINGS_ATLAS_1', 3),
('ICON_SLTH_BUILDING_ALTAR_OF_THE_LUONNOTAR_BLESSED', 'ICON_SLTH_BUILDINGS_ATLAS_1', 4),
('ICON_SLTH_BUILDING_ALTAR_OF_THE_LUONNOTAR_CONSECRATED', 'ICON_SLTH_BUILDINGS_ATLAS_1', 5),
('ICON_SLTH_BUILDING_ALTAR_OF_THE_LUONNOTAR_DIVINE', 'ICON_SLTH_BUILDINGS_ATLAS_1', 6),                 -- missed ALD
('ICON_SLTH_BUILDING_ALTAR_OF_THE_LUONNOTAR_EXALTED', 'ICON_SLTH_BUILDINGS_ATLAS_1', 6),
('ICON_SLTH_BUILDING_ALTAR_OF_THE_LUONNOTAR_FINAL', 'ICON_SLTH_BUILDINGS_ATLAS_1', 7);

-- reuse
INSERT INTO IconDefinitions(Name, Atlas, 'Index')VALUES
('ICON_SLTH_BUILDING_HARBOR', 'ICON_SLTH_BUILDINGS_ATLAS_1', 0),                    --
('ICON_BUILDING_MAGE_GUILD', 'ICON_ATLAS_BUILDINGS', 19),                     -- madrasa
('ICON_SLTH_BUILDING_CHANCEL', 'ICON_ATLAS_EXPANSION_1_DISTRICT_BUILDINGS', 5),                 -- consulate but unneeded
('ICON_SLTH_BUILDING_CARNIVAL', 'ICON_ATLAS_BUILDINGS', 31),                                 -- zoo
('ICON_SLTH_BUILDING_TAVERN', 'ICON_ATLAS_EXPANSION_2_BUILDINGS', 0),                                  -- guildhall xp2 (black death)
('ICON_SLTH_BUILDING_SYLIVENS_PERFECT_LYRE', 'ICON_ATLAS_EXPANSION_2_BUILDINGS', 3);                -- mass graev lol


-- spider pen
-- adventurers Guild
-- Altar of Luonnotar D
-- Dwarf Cage
-- ELF cage
-- gorilla cage
-- Sea Haven
-- The Necronomicon
-- Dwarven Smithy

-- missing carnival as Ca

-- ICON_SLTH_BUILDING_TAVERN

-- NULL Buildings

INSERT INTO IconDefinitions(Name, Atlas, 'Index')VALUES
('ICON_SLTH_BUILDING_NULL_CIVILIZATION_GRIGORI_PAGAN_TEMPLE', 'ICON_ATLAS_UNIT_ACTIONS', 28),
('ICON_SLTH_BUILDING_NULL_CIVILIZATION_GRIGORI_TEMPLE_OF_KILMORPH', 'ICON_ATLAS_UNIT_ACTIONS', 28),
('ICON_SLTH_BUILDING_NULL_CIVILIZATION_GRIGORI_TEMPLE_OF_LEAVES', 'ICON_ATLAS_UNIT_ACTIONS', 28),
('ICON_SLTH_BUILDING_NULL_CIVILIZATION_GRIGORI_TEMPLE_OF_THE_EMPYREAN', 'ICON_ATLAS_UNIT_ACTIONS', 28),
('ICON_SLTH_BUILDING_NULL_CIVILIZATION_GRIGORI_TEMPLE_OF_THE_ORDER', 'ICON_ATLAS_UNIT_ACTIONS', 28),
('ICON_SLTH_BUILDING_NULL_CIVILIZATION_GRIGORI_TEMPLE_OF_THE_OVERLORDS', 'ICON_ATLAS_UNIT_ACTIONS', 28),
('ICON_SLTH_BUILDING_NULL_CIVILIZATION_GRIGORI_TEMPLE_OF_THE_VEIL', 'ICON_ATLAS_UNIT_ACTIONS', 28),
('ICON_SLTH_BUILDING_NULL_CIVILIZATION_KURIOTATES_STABLE', 'ICON_ATLAS_UNIT_ACTIONS', 28),
('ICON_SLTH_BUILDING_NULL_CIVILIZATION_HIPPUS_ALCHEMY_LAB', 'ICON_ATLAS_UNIT_ACTIONS', 28),
('ICON_SLTH_BUILDING_NULL_CIVILIZATION_DOVIELLO_ALCHEMY_LAB', 'ICON_ATLAS_UNIT_ACTIONS', 28),
('ICON_SLTH_BUILDING_NULL_CIVILIZATION_DOVIELLO_LIBRARY', 'ICON_ATLAS_UNIT_ACTIONS', 28),
('ICON_SLTH_BUILDING_NULL_CIVILIZATION_DOVIELLO_MAGE_GUILD', 'ICON_ATLAS_UNIT_ACTIONS', 28),
('ICON_SLTH_BUILDING_NULL_CIVILIZATION_CLAN_OF_EMBERS_ALCHEMY_LAB', 'ICON_ATLAS_UNIT_ACTIONS', 28),
('ICON_SLTH_BUILDING_NULL_CIVILIZATION_CLAN_OF_EMBERS_LIBRARY', 'ICON_ATLAS_UNIT_ACTIONS', 28),
('ICON_SLTH_BUILDING_NULL_CIVILIZATION_CLAN_OF_EMBERS_MAGE_GUILD', 'ICON_ATLAS_UNIT_ACTIONS', 28),
('ICON_SLTH_BUILDING_NULL_CIVILIZATION_CLAN_OF_EMBERS_STABLE', 'ICON_ATLAS_UNIT_ACTIONS', 28),
('ICON_SLTH_BUILDING_NULL_CIVILIZATION_CALABIM_ALCHEMY_LAB', 'ICON_ATLAS_UNIT_ACTIONS', 28),
('ICON_SLTH_BUILDING_NULL_CIVILIZATION_CALABIM_ELDER_COUNCIL', 'ICON_ATLAS_UNIT_ACTIONS', 28),
('ICON_SLTH_BUILDING_NULL_CIVILIZATION_INFERNAL_AQUEDUCT', 'ICON_ATLAS_UNIT_ACTIONS', 28),
('ICON_SLTH_BUILDING_NULL_CIVILIZATION_INFERNAL_GRANARY', 'ICON_ATLAS_UNIT_ACTIONS', 28),
('ICON_SLTH_BUILDING_NULL_CIVILIZATION_INFERNAL_HERBALIST', 'ICON_ATLAS_UNIT_ACTIONS', 28),
('ICON_SLTH_BUILDING_NULL_CIVILIZATION_INFERNAL_INFIRMARY', 'ICON_ATLAS_UNIT_ACTIONS', 28),
('ICON_SLTH_BUILDING_NULL_CIVILIZATION_INFERNAL_PUBLIC_BATHS', 'ICON_ATLAS_UNIT_ACTIONS', 28),
('ICON_SLTH_BUILDING_NULL_CIVILIZATION_INFERNAL_SMOKEHOUSE', 'ICON_ATLAS_UNIT_ACTIONS', 28),

('ICON_SLTH_BUILDING_NULL_CIVILIZATION_SHEAIM_TRAINING_YARD', 'ICON_ATLAS_UNIT_ACTIONS', 28),
('ICON_SLTH_BUILDING_NULL_CIVILIZATION_LJOSALFAR_ALCHEMY_LAB', 'ICON_ATLAS_UNIT_ACTIONS', 28),
('ICON_SLTH_BUILDING_NULL_CIVILIZATION_LJOSALFAR_SIEGE_WORKSHOP', 'ICON_ATLAS_UNIT_ACTIONS', 28),
('ICON_SLTH_BUILDING_NULL_CIVILIZATION_SVARTALFAR_ALCHEMY_LAB', 'ICON_ATLAS_UNIT_ACTIONS', 28),
('ICON_SLTH_BUILDING_NULL_CIVILIZATION_SVARTALFAR_SIEGE_WORKSHOP', 'ICON_ATLAS_UNIT_ACTIONS', 28);