-- reuse existing

INSERT INTO IconDefinitions(Name, Atlas, 'Index')VALUES
('ICON_IMPROVEMENT_CASTLE', 'ICON_ATLAS_UNIT_ACTIONS', 18),
('ICON_IMPROVEMENT_CITADEL', 'ICON_SLTH_BUILDINGS_ATLAS_0', 1),
('ICON_IMPROVEMENT_COTTAGE', 'ICON_ATLAS_EXPANSION_1_IMPROVEMENTS', 0),
('ICON_IMPROVEMENT_VILLAGE', 'ICON_ATLAS_UNIT_ACTIONS', 20),
('ICON_IMPROVEMENT_ENCLAVE', 'ICON_ATLAS_UNIT_ACTIONS', 16),
('ICON_IMPROVEMENT_WINDMILL', 'ICON_ATLAS_EXPANSION_1_IMPROVEMENTS', 2),
('ICON_IMPROVEMENT_WINERY', 'ICON_ATLAS_UNIT_ACTIONS', 22),
('ICON_IMPROVEMENT_MANA_EARTH', 'ICON_ATLAS_UNIT_ACTIONS', 19),
('ICON_IMPROVEMENT_MANA_WATER', 'ICON_ATLAS_EXPANSION_1_IMPROVEMENTS', 5),
('ICON_IMPROVEMENT_MANA_NATURE', 'ICON_ATLAS_EXPANSION_2_UNIT_ACTIONS', 4),
('ICON_IMPROVEMENT_MANA_DEATH', 'ICON_ATLAS_UNIT_ACTIONS', 30),
('ICON_IMPROVEMENT_MANA_ENTROPY', 'ICON_ATLAS_EXPANSION_2_UNIT_ACTIONS', 2),
('ICON_IMPROVEMENT_MANA_MIND', 'ICON_ATLAS_EXPANSION_2_UNIT_ACTIONS', 1),
('ICON_IMPROVEMENT_MANA_ENCHANTMENT', 'ICON_ATLAS_UNIT_ACTIONS', 49),
('ICON_IMPROVEMENT_MANA_BODY', 'ICON_ATLAS_UNIT_ACTIONS', 17),
('ICON_IMPROVEMENT_MANA_CHAOS', 'ICON_ATLAS_UNIT_ACTIONS', 78),
('ICON_IMPROVEMENT_MANA_SUN', 'ICON_ATLAS_UNIT_ACTIONS', 27),
('ICON_IMPROVEMENT_MANA_SHADOW', 'ICON_ATLAS_UNIT_ACTIONS', 72),
('ICON_IMPROVEMENT_MANA_LAW', 'ICON_ATLAS_EXPANSION_2_UNIT_ACTIONS', 6),
('ICON_IMPROVEMENT_MANA_AIR', 'ICON_ATLAS_EXPANSION_2_UNIT_ACTIONS', 17);

-- ('ICON_IMPROVEMENT_MANA_FIRE', 'ICON_ATLAS_ZOMBIES_UNIT_ACTIONS', 2);            -- done in xml

-- todos metamagic


    -- ICON_ATLAS_ETHIOPIA_UNIT_ACTIONS 0,1,4
-- himiko activem dance of blades
-- hippo active, enchanted blade
-- oya active, air 2?
-- sinbad active, loki gold?

-- anasni, chaos 3 wonder?


