INSERT INTO IconDefinitions(Name, Atlas, 'Index')VALUES
('ICON_PROJECT_DEEPENING', 'ICON_ATLAS_EXPANSION_2_UNIT_ACTIONS', 0),
('ICON_PROJECT_THE_DRAW', 'ICON_ATLAS_EXPANSION_2_UNIT_ACTIONS', 13),
('ICON_PROJECT_ASCENSION', 'ICON_ATLAS_UNIT_ACTIONS', 73),
('ICON_PROJECT_STIR_FROM_SLUMBER', 'ICON_ATLAS_UNIT_ACTIONS', 77),
('ICON_PROJECT_HALLOWING_OF_ELOHIM', 'ICON_ATLAS_UNIT_ACTIONS', 86),
('ICON_PROJECT_BANE_DIVINE', 'ICON_ATLAS_EXPANSION_2_UNIT_ACTIONS', 8),
('ICON_PROJECT_PHOENIX', 'ICON_ATLAS_EXPANSION_1_IMPROVEMENTS', 6),
('ICON_PROJECT_GENESIS', 'ICON_ATLAS_UNIT_ACTIONS', 65),
('ICON_PROJECT_NATURES_REVOLT', 'ICON_ATLAS_EXPANSION_1_IMPROVEMENTS', 7),
('ICON_PROJECT_RITES_OGHMA', 'ICON_ATLAS_EXPANSION_2_UNIT_ACTIONS', 7),
('ICON_PURGE_THE_UNFAITHFUL', 'ICON_ATLAS_UNIT_ACTIONS', 58),
('ICON_PROJECT_PACT_OF_NILHORN', 'ICON_ATLAS_XP1_PROJECTS', 0);

INSERT INTO IconTextureAtlases(Name, IconSize, IconsPerRow, IconsPerColumn, Filename) VALUES
('ICON_ATLAS_ETHIOPIA_UNIT_ACTIONS', '38', '4', '1', 'Ethiopia_UnitActions38'),
('ICON_ATLAS_ETHIOPIA_UNIT_ACTIONS', '50', '4', '1', 'Ethiopia_UnitActions50'),
('ICON_ATLAS_ETHIOPIA_UNIT_ACTIONS', '70', '4', '1', 'Ethiopia_UnitActions80'),
('ICON_ATLAS_ETHIOPIA_UNIT_ACTIONS', '256','4', '1', 'Ethiopia_UnitActions256');


INSERT INTO IconDefinitions(Name, Atlas, 'Index')VALUES
('ICON_PROJECT_GLORY_EVERLASTING', 'ICON_ATLAS_ETHIOPIA_UNIT_ACTIONS', 1),
