INSERT INTO IconDefinitions(Name, Atlas, 'Index')VALUES
('ICON_IMPROVEMENT_PIRATE_COVE', 'ICON_ATLAS_INDONESIA_KHMER_UNITACTIONS', 0),
('ICON_IMPROVEMENT_PIRATE_HARBOR', 'ICON_ATLAS_INDONESIA_KHMER_UNITACTIONS', 0);

INSERT INTO IconDefinitions(Name, Atlas, 'Index')VALUES                     -- units
('ICON_SLTH_UNIT_MAN_O_WAR', 'ICON_ATLAS_INDONESIA_KHMER_UNITS' , '0');
