INSERT INTO IconDefinitions(Name, Atlas, 'Index')VALUES                             -- improvements
('ICON_IMPROVEMENT_TOWN', 'ICON_ATLAS_GRAN_COLOMBIA_MAYA_UNIT_ACTIONS', 0);


INSERT INTO IconDefinitions(Name, Atlas, 'Index') VALUES                                     -- resources
('ICON_RESOURCE_CORN', 'ICON_ATLAS_GRAN_COLOMBIA_MAYA_RESOURCES', '1'),
('ICON_RESOURCE_CORN_FOW', 'ICON_ATLAS_GRAN_COLOMBIA_MAYA_RESOURCES_FOW', '1');

INSERT INTO IconDefinitions(Name, Atlas, 'Index') VALUES                                     -- units
('ICON_SLTH_UNIT_JAVELIN_THROWER', 'ICON_ATLAS_GRAN_COLOMBIA_MAYA_UNITS' , '0'),
('ICON_SLTH_UNIT_TASKMASTER', 'ICON_ATLAS_GRAN_COLOMBIA_MAYA_UNITS' , '3'),
('ICON_SLTH_UNIT_SHAMAN', 'ICON_ATLAS_GRAN_COLOMBIA_MAYA_UNITS' , '4'),
('ICON_SLTH_UNIT_YERSINIA', 'ICON_ATLAS_GRAN_COLOMBIA_MAYA_UNITS' , '1');
