INSERT INTO IconDefinitions(Name, Atlas, 'Index')VALUES                     -- units
('ICON_SLTH_UNIT_PHALANX', 'ICON_ATLAS_MACEDON_PERSIA_UNITS' , '1'),
('ICON_SLTH_UNIT_STEPHANOS', 'ICON_ATLAS_MACEDON_PERSIA_UNITS' , '0'),
('ICON_SLTH_UNIT_RADIANT_GUARD', 'ICON_ATLAS_MACEDON_PERSIA_UNITS' , '2');
