-- Buildings
INSERT INTO IconDefinitions(Name, Atlas, 'Index')VALUES
('ICON_SLTH_BUILDING_INFIRMARY', 'ICON_ATLAS_ETHIOPIA_BUILDINGS', 2),                 -- Chancery
('ICON_SLTH_BUILDING_DEMONS_ALTAR', 'ICON_ATLAS_ETHIOPIA_BUILDINGS', 5);                 -- old god obelisk

-- Improvements
INSERT INTO IconDefinitions(Name, Atlas, 'Index')VALUES
('ICON_IMPROVEMENT_MANA_LIFE', 'ICON_ATLAS_ETHIOPIA_UNIT_ACTIONS', 3);

-- Projects
INSERT INTO IconDefinitions(Name, Atlas, 'Index')VALUES
('ICON_PROJECT_ELEGY_OF_THE_SHEAIM', 'ICON_ATLAS_ETHIOPIA_UNIT_ACTIONS', 0),
('ICON_PROJECT_BIRTHRIGHT_REGAINED', 'ICON_ATLAS_ETHIOPIA_UNIT_ACTIONS', 4);


INSERT INTO IconDefinitions(Name, Atlas, 'Index')VALUES                     -- units
('ICON_SLTH_UNIT_VAMPIRE', 'ICON_ATLAS_ETHIOPIA_UNITS' , '1'),
('ICON_SLTH_UNIT_HIGH_PRIEST_OF_THE_VEIL', 'ICON_ATLAS_ETHIOPIA_UNITS' , '0');
