INSERT INTO IconDefinitions(Name, Atlas, 'Index')VALUES                 -- units
('ICON_SLTH_UNIT_CHANTER', 'ICON_ATLAS_BABYLON_UNITS' , '0'),
('ICON_SLTH_UNIT_DEVOUT', 'ICON_ATLAS_BABYLON_UNITS' , '0'),
('ICON_SLTH_UNIT_DUIN', 'ICON_ATLAS_BABYLON_UNITS' , '4'),
('ICON_SLTH_UNIT_KITHRA', 'ICON_ATLAS_BABYLON_UNITS' , '9'),
('ICON_SLTH_UNIT_SHADOWRIDER', 'ICON_ATLAS_BABYLON_UNITS' , '13');

INSERT INTO IconDefinitions(Name, Atlas, 'Index')VALUES                 -- improvements
('ICON_IMPROVEMENT_WORKSHOP', 'ICON_ATLAS_BABYLON_UNIT_ACTIONS', 12);
