INSERT INTO Traits(TraitType, Name, Description) VALUES
('SLTH_TRAIT_CIVILIZATION_UNIT_DWARVEN_SLINGER', 'LOC_SLTH_TRAIT_CIVILIZATION_UNIT_DWARVEN_SLINGER_NAME', 'LOC_SLTH_TRAIT_CIVILIZATION_UNIT_DWARVEN_SLINGER_DESCRIPTION'),
('SLTH_TRAIT_CIVILIZATION_UNIT_DWARVEN_DRUID', 'LOC_SLTH_TRAIT_CIVILIZATION_UNIT_DWARVEN_DRUID_NAME', 'LOC_SLTH_TRAIT_CIVILIZATION_UNIT_DWARVEN_DRUID_DESCRIPTION'),
('SLTH_TRAIT_CIVILIZATION_UNIT_BOAR_RIDER', 'LOC_SLTH_TRAIT_CIVILIZATION_UNIT_BOAR_RIDER_NAME', 'LOC_SLTH_TRAIT_CIVILIZATION_UNIT_BOAR_RIDER_DESCRIPTION'),
('SLTH_TRAIT_CIVILIZATION_UNIT_HORNGUARD', 'LOC_SLTH_TRAIT_CIVILIZATION_UNIT_HORNGUARD_NAME', 'LOC_SLTH_TRAIT_CIVILIZATION_UNIT_HORNGUARD_DESCRIPTION'),
('SLTH_TRAIT_CIVILIZATION_UNIT_DWARVEN_SHADOW', 'LOC_SLTH_TRAIT_CIVILIZATION_UNIT_DWARVEN_SHADOW_NAME', 'LOC_SLTH_TRAIT_CIVILIZATION_UNIT_DWARVEN_SHADOW_DESCRIPTION');

INSERT INTO Modifiers(ModifierId, ModifierType, RunOnce, Permanent, SubjectRequirementSetId) VALUES
('GRANT_DWARF_ABILITY_HILLS_DOUBLE_MOVE_CITY_ATTACH', 'MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER', 0, 0, NULL),
('GRANT_DWARF_ABILITY_HILLS_DOUBLE_MOVE_CITY', 'MODIFIER_SINGLE_CITY_GRANT_ABILITY_FOR_TRAINED_UNITS', '0', '0', NULL);

INSERT INTO ModifierArguments(ModifierId, Name, Type, Value) VALUES
('GRANT_DWARF_ABILITY_HILLS_DOUBLE_MOVE_CITY_ATTACH', 'ModifierId', 'ARGTYPE_IDENTITY', 'GRANT_DWARF_ABILITY_HILLS_DOUBLE_MOVE_CITY'),
('GRANT_DWARF_ABILITY_HILLS_DOUBLE_MOVE_CITY', 'AbilityType', 'ARGTYPE_IDENTITY', 'DWARF_ABILITY_HILLS_DOUBLE_MOVE');

INSERT INTO UnitReplaces(CivUniqueUnitType, ReplacesUnitType) VALUES
('SLTH_UNIT_DWARVEN_SLINGER', 'SLTH_UNIT_ARCHER'),
('SLTH_UNIT_DWARVEN_DRUID', 'SLTH_UNIT_DRUID'),
('SLTH_UNIT_BOAR_RIDER', 'SLTH_UNIT_HORSEMAN'),
('SLTH_UNIT_DWARVEN_SHADOW', 'SLTH_UNIT_SHADOW'),
('SLTH_UNIT_HORNGUARD', 'SLTH_UNIT_KNIGHT');

INSERT INTO Unit_BuildingPrereqs(Unit, PrereqBuilding) VALUES           -- dont upgrade from anything so fine
('SLTH_UNIT_DWARVEN_DRUID', 'BUILDING_GROVE');


INSERT INTO TypeTags(Type, Tag) VALUES
('SLTH_UNIT_DWARVEN_SLINGER', 'CLASS_RANGED'),
('SLTH_UNIT_DWARVEN_SLINGER', 'RACE_DWARVEN'),
('SLTH_UNIT_DWARVEN_DRUID', 'CLASS_DISCIPLE'),
('SLTH_UNIT_BOAR_RIDER', 'CLASS_LIGHT_CAVALRY'),
('SLTH_UNIT_DWARVEN_SHADOW', 'CLASS_RECON'),
('SLTH_UNIT_DWARVEN_DRUID', 'RACE_DWARVEN'),
('SLTH_UNIT_BOAR_RIDER', 'RACE_DWARVEN'),
('SLTH_UNIT_DWARVEN_SHADOW', 'RACE_DWARVEN'),
('SLTH_UNIT_HORNGUARD', 'RACE_DWARVEN'),
('SLTH_UNIT_HORNGUARD', 'CLASS_LIGHT_CAVALRY');

INSERT INTO Types(Type, Kind) VALUES
('SLTH_UNIT_DWARVEN_SLINGER', 'KIND_UNIT'),
('SLTH_TRAIT_CIVILIZATION_UNIT_DWARVEN_SLINGER', 'KIND_TRAIT'),
('SLTH_TRAIT_CIVILIZATION_UNIT_DWARVEN_DRUID', 'KIND_TRAIT'),
('SLTH_TRAIT_CIVILIZATION_UNIT_BOAR_RIDER', 'KIND_TRAIT'),
('SLTH_TRAIT_CIVILIZATION_UNIT_DWARVEN_SHADOW', 'KIND_TRAIT'),
('SLTH_UNIT_DWARVEN_DRUID', 'KIND_UNIT'),
('SLTH_UNIT_BOAR_RIDER', 'KIND_UNIT'),
('SLTH_UNIT_DWARVEN_SHADOW', 'KIND_UNIT'),
('SLTH_UNIT_HORNGUARD', 'KIND_UNIT');