INSERT OR REPLACE INTO LocalizedText(Tag, Text, Language) VALUES
('LOC_BUILDING_ALCHEMICAL_SOCIETY_NAME', 'Academy', 'en_US'),
('LOC_BUILDING_AMPHITHEATER_NAME', 'Theatre', 'en_US'),
('LOC_BUILDING_ANGKOR_WAT_NAME', 'Dies Diei', 'en_US'),
('LOC_BUILDING_ARENA_NAME', 'Arena', 'en_US'),
('LOC_BUILDING_BANK_NAME', 'Moneychanger', 'en_US'),
('LOC_BUILDING_TRAINING_YARD_NAME', 'Training Yard', 'en_US'),
('LOC_BUILDING_TOWER_OF_COMPLACENCY_NAME', 'Tower Of Complacency', 'en_US'),
('LOC_BUILDING_THEATER_OF_DREAMS_NAME', 'Theatre Of Dreams', 'en_US'),
('LOC_BUILDING_TEMPLE_OF_THE_ORDER_NAME', 'Temple Of The Order', 'en_US'),
('LOC_SLTH_BUILDING_INFIRMARY_NAME', 'Infirmary', 'en_US'),
('LOC_SLTH_BUILDING_INN_NAME', 'Inn', 'en_US'),
('LOC_BUILDING_SHRINE_OF_SIRONA_NAME', 'Shrine Of Sirona', 'en_US'),
('LOC_SLTH_BUILDING_TOWER_OF_MASTERY_NAME', 'Tower Of Mastery', 'en_US'),
('LOC_BUILDING_SUMMER_PALACE_NAME', 'Forbidden Palace', 'en_US'),
('LOC_BUILDING_TAX_OFFICE_NAME', 'Tax Office', 'en_US'),
('LOC_SLTH_BUILDING_CHANCEL_NAME', 'Chancel Of Guardians', 'en_US'),
('LOC_BUILDING_GRANARY_NAME', 'Granary', 'en_US'),
('LOC_BUILDING_BAZAAR_OF_MAMMON_NAME', 'Bazaar Of Mammon', 'en_US'),
('LOC_BUILDING_GREAT_LIBRARY_NAME', 'Great Library', 'en_US'),
('LOC_BUILDING_GREAT_LIGHTHOUSE_NAME', 'Great Lighthouse', 'en_US'),
('LOC_BUILDING_GROVE_NAME', 'Grove', 'en_US'),
('LOC_BUILDING_TEMPLE_OF_THE_EMPYREAN_NAME', 'Temple Of The Empyrean', 'en_US'),
('LOC_BUILDING_TEMPLE_OF_TEMPORENCE_NAME', 'Temple Of Temporence', 'en_US'),
('LOC_BUILDING_HERON_THRONE_NAME', 'Heron Throne', 'en_US'),
('LOC_BUILDING_MINES_OF_GALDUR_NAME', 'Mines Of Galdur', 'en_US'),
('LOC_BUILDING_KOTOKU_IN_NAME', 'Shrine Of The Champion', 'en_US'),
('LOC_BUILDING_LIBRARY_NAME', 'Library', 'en_US'),
('LOC_BUILDING_LIGHTHOUSE_NAME', 'Lighthouse', 'en_US'),
('LOC_BUILDING_MAGE_GUILD_NAME', 'Mage Guild', 'en_US'),
('LOC_SLTH_BUILDING_TOWER_OF_ALTERATION_NAME', 'Tower Of Alteration', 'en_US'),
('LOC_SLTH_BUILDING_HUNTING_LODGE_NAME', 'Hunting Lodge', 'en_US'),
('LOC_BUILDING_MARKET_NAME', 'Market', 'en_US'),
('LOC_BUILDING_MEETING_HOUSE_NAME', 'Herbalist', 'en_US'),
('LOC_BUILDING_MONUMENT_NAME', 'Monument', 'en_US'),
('LOC_BUILDING_TEMPLE_OF_THE_OVERLORDS_NAME', 'Temple Of The Overlords', 'en_US'),
('LOC_SLTH_BUILDING_DEMONS_ALTAR_NAME', 'Demons Altar', 'en_US'),
('LOC_SLTH_BUILDING_TOWER_OF_DIVINATION_NAME', 'Tower Of Divination', 'en_US'),
('LOC_BUILDING_BREEDING_PIT_NAME', 'Breeding Pit', 'en_US'),
('LOC_BUILDING_WINTER_PALACE_NAME', 'Winter Palace', 'en_US'),
('LOC_BUILDING_PALGUM_NAME', 'Brewery', 'en_US'),
('LOC_BUILDING_CATACOMB_LIBRALUS_NAME', 'Catacomb Libralus', 'en_US'),
('LOC_BUILDING_QUEENS_BIBLIOTHEQUE_NAME', 'Courthouse', 'en_US'),
('LOC_BUILDING_RESEARCH_LAB_NAME', 'Alchemy Lab', 'en_US'),
('LOC_BUILDING_TEMPLE_OF_LEAVES_NAME', 'Temple Of Leaves', 'en_US'),
('LOC_BUILDING_SHIPYARD_NAME', 'Shipyard', 'en_US'),
('LOC_BUILDING_SHRINE_NAME', 'Pagan Temple', 'en_US'),
('LOC_BUILDING_STABLE_NAME', 'Stable', 'en_US'),
('LOC_BUILDING_TEMPLE_OF_THE_VEIL_NAME', 'Temple Of The Veil', 'en_US'),
('LOC_BUILDING_HALL_OF_KINGS_NAME', 'Hall Of Kings', 'en_US'),
('LOC_BUILDING_SYNAGOGUE_NAME', 'Basilica', 'en_US'),
('LOC_BUILDING_BONE_PALACE_NAME', 'Bone Palace', 'en_US'),
('LOC_BUILDING_GRAND_MENAGERIE_NAME', 'Grand Menagerie', 'en_US'),
('LOC_BUILDING_GUILD_OF_THE_NINE_NAME', 'Guild Of The Nine', 'en_US'),
('LOC_BUILDING_WALLS_NAME', 'Palisade', 'en_US'),
('LOC_BUILDING_TEMPLE_OF_KILMORPH_NAME', 'Temple Of Kilmorph', 'en_US'),
('LOC_BUILDING_FORGE_NAME', 'Forge', 'en_US'),
('LOC_SLTH_BUILDING_ADULARIA_CHAMBER_NAME', 'Adularia Chamber', 'en_US'),
('LOC_SLTH_BUILDING_ADVENTURERS_GUILD_NAME', 'Adventurer''s Guild', 'en_US'),
('LOC_SLTH_BUILDING_ALTAR_OF_THE_LUONNOTAR_ANOINTED_NAME', 'Altar Of The Luonnotar: Anointed', 'en_US'),
('LOC_SLTH_BUILDING_ALTAR_OF_THE_LUONNOTAR_BLESSED_NAME', 'Altar Of The Luonnotar: Blessed', 'en_US'),
('LOC_SLTH_BUILDING_ALTAR_OF_THE_LUONNOTAR_CONSECRATED_NAME', 'Altar Of The Luonnotar: Consecrated', 'en_US'),
('LOC_SLTH_BUILDING_ALTAR_OF_THE_LUONNOTAR_DIVINE_NAME', 'Altar Of The Luonnotar: Divine', 'en_US'),
('LOC_SLTH_BUILDING_ALTAR_OF_THE_LUONNOTAR_EXALTED_NAME', 'Altar Of The Luonnotar: Exalted', 'en_US'),
('LOC_SLTH_BUILDING_ALTAR_OF_THE_LUONNOTAR_FINAL_NAME', 'Altar Of The Luonnotar: Final', 'en_US'),
('LOC_SLTH_BUILDING_ALTAR_OF_THE_LUONNOTAR_NAME', 'Altar Of The Luonnotar', 'en_US'),
('LOC_BUILDING_AQUAE_SUCELLUS_NAME', 'Aquae Sucellus', 'en_US'),
('LOC_SLTH_BUILDING_AQUEDUCT_NAME', 'Aqueduct', 'en_US'),
('LOC_SLTH_BUILDING_ARCHERY_RANGE_NAME', 'Archery Range', 'en_US'),
('LOC_SLTH_BUILDING_ASYLUM_NAME', 'Asylum', 'en_US'),
('LOC_SLTH_BUILDING_BLASTING_WORKSHOP_NAME', 'Blasting Workshop', 'en_US'),
('LOC_SLTH_BUILDING_CARNIVAL_NAME', 'Carnival', 'en_US'),
('LOC_SLTH_BUILDING_CAVE_OF_ANCESTORS_NAME', 'Cave Of Ancestors', 'en_US'),
('LOC_SLTH_BUILDING_CELESTIAL_COMPASS_NAME', 'Celestial Compass', 'en_US'),
('LOC_SLTH_BUILDING_CITADEL_OF_LIGHT_NAME', 'Citadel Of Light', 'en_US'),
('LOC_BUILDING_CITY_OF_A_THOUSAND_SLUMS_NAME', 'City Of A Thousand Slums', 'en_US'),
('LOC_SLTH_BUILDING_CODE_OF_JUNIL_NAME', 'Code Of Junil', 'en_US'),
('LOC_SLTH_BUILDING_COMMAND_POST_NAME', 'Command Post', 'en_US'),
('LOC_SLTH_BUILDING_CROWN_OF_AKHARIEN_NAME', 'Crown Of Akharien', 'en_US'),
('LOC_SLTH_BUILDING_DANCING_BEAR_NAME', 'Dancing Bear', 'en_US'),
('LOC_SLTH_BUILDING_DEMONIC_CITIZENS_NAME', 'Demonic Citizens', 'en_US'),
('LOC_SLTH_BUILDING_DESERT_SHRINE_NAME', 'Desert Shrine', 'en_US'),
('LOC_SLTH_BUILDING_DUNGEON_NAME', 'Dungeon', 'en_US'),
('LOC_SLTH_BUILDING_DWARF_CAGE_NAME', 'Dwarf Cage', 'en_US'),
('LOC_SLTH_BUILDING_DWARVEN_SMITHY_NAME', 'Dwarven Smithy', 'en_US'),
('LOC_SLTH_BUILDING_DWARVEN_VAULT_ABUNDANT_NAME', 'Dwarven Vault Abundant', 'en_US'),
('LOC_SLTH_BUILDING_DWARVEN_VAULT_EMPTY_NAME', 'Dwarven Vault Empty', 'en_US'),
('LOC_SLTH_BUILDING_DWARVEN_VAULT_FULL_NAME', 'Dwarven Vault Full', 'en_US'),
('LOC_SLTH_BUILDING_DWARVEN_VAULT_LOW_NAME', 'Dwarven Vault Low', 'en_US'),
('LOC_SLTH_BUILDING_DWARVEN_VAULT_NAME', 'Dwarven Vault', 'en_US'),
('LOC_SLTH_BUILDING_DWARVEN_VAULT_OVERFLOWING_NAME', 'Dwarven Vault Overflowing', 'en_US'),
('LOC_SLTH_BUILDING_DWARVEN_VAULT_STOCKED_NAME', 'Dwarven Vault Stocked', 'en_US'),
('LOC_SLTH_BUILDING_ELDER_COUNCIL_NAME', 'Elder Council', 'en_US'),
('LOC_SLTH_BUILDING_ELF_CAGE_NAME', 'Elf Cage', 'en_US'),
('LOC_SLTH_BUILDING_EYES_AND_EARS_NETWORK_NAME', 'Eyes And Ears Network', 'en_US'),
('LOC_SLTH_BUILDING_FORM_OF_THE_TITAN_NAME', 'Form Of The Titan', 'en_US'),
('LOC_SLTH_BUILDING_FREAK_SHOW_NAME', 'Freak Show', 'en_US'),
('LOC_SLTH_BUILDING_GAMBLING_HOUSE_NAME', 'Gambling House', 'en_US'),
('LOC_SLTH_BUILDING_GORILLA_CAGE_NAME', 'Gorilla Cage', 'en_US'),
('LOC_SLTH_BUILDING_GOVERNORS_MANOR_NAME', 'Governor''s Manor', 'en_US'),
('LOC_SLTH_BUILDING_GUILD_OF_HAMMERS_NAME', 'Guild Of Hammers', 'en_US'),
('LOC_SLTH_BUILDING_HALL_OF_MIRRORS_NAME', 'Hall Of Mirrors', 'en_US'),
('LOC_SLTH_BUILDING_HARBOR_LANUN_NAME', 'Sea Haven', 'en_US'),
('LOC_SLTH_BUILDING_HARBOR_NAME', 'Harbor', 'en_US'),
('LOC_SLTH_BUILDING_HEROIC_EPIC_NAME', 'Heroic Epic', 'en_US'),
('LOC_SLTH_BUILDING_HUMAN_CAGE_NAME', 'Human Cage', 'en_US'),
('LOC_SLTH_BUILDING_INFERNAL_GRIMOIRE_NAME', 'Infernal Grimoire', 'en_US'),
('LOC_SLTH_BUILDING_JEWELER_NAME', 'Jeweler', 'en_US'),
('LOC_SLTH_BUILDING_LION_CAGE_NAME', 'Lion Cage', 'en_US'),
('LOC_SLTH_BUILDING_MERCURIAN_GATE_NAME', 'Mercurian Gate', 'en_US'),
('LOC_SLTH_BUILDING_MOKKAS_CAULDRON_NAME', 'Mokkas Cauldron', 'en_US'),
('LOC_SLTH_BUILDING_NATIONAL_EPIC_NAME', 'National Epic', 'en_US'),
('LOC_SLTH_BUILDING_NOX_NOCTIS_NAME', 'Nox Noctis', 'en_US'),
('LOC_SLTH_BUILDING_NULL_NAME', 'ZZ_Banned for Civ', 'en_US'),
('LOC_SLTH_BUILDING_OBSIDIAN_GATE_NAME', 'Obsidian Gate', 'en_US'),
('LOC_SLTH_BUILDING_ORC_CAGE_NAME', 'Orc Cage', 'en_US'),
('LOC_SLTH_BUILDING_PALLENS_ENGINE_NAME', 'Pallens Engine', 'en_US'),
('LOC_BUILDING_PILLAR_OF_CHAINS_NAME', 'Pillar Of Chains', 'en_US'),
('LOC_SLTH_BUILDING_PLANAR_GATE_NAME', 'Planar Gate', 'en_US'),
('LOC_SLTH_BUILDING_PROPHECY_OF_RAGNAROK_NAME', 'Prophecy Of Ragnarok', 'en_US'),
('LOC_SLTH_BUILDING_PUBLIC_BATHS_NAME', 'Public Baths', 'en_US'),
('LOC_SLTH_BUILDING_RELIQUARY_NAME', 'Reliquary', 'en_US'),
('LOC_SLTH_BUILDING_RIDE_OF_THE_NINE_KINGS_NAME', 'Ride Of The Nine Kings', 'en_US'),
('LOC_SLTH_BUILDING_SCULPTORS_STUDIO_NAME', 'Sculptors Studio', 'en_US'),
('LOC_SLTH_BUILDING_SIEGE_WORKSHOP_NAME', 'Siege Workshop', 'en_US'),
('LOC_SLTH_BUILDING_SMOKEHOUSE_NAME', 'Smokehouse', 'en_US'),
('LOC_SLTH_BUILDING_SMUGGLERS_PORT_NAME', 'Smuggler''s Port', 'en_US'),
('LOC_SLTH_BUILDING_SONG_OF_AUTUMN_NAME', 'Song Of Autumn', 'en_US'),
('LOC_SLTH_BUILDING_SOUL_FORGE_NAME', 'Soul Forge', 'en_US'),
('LOC_SLTH_BUILDING_SPIDER_PEN_NAME', 'Spider Pen', 'en_US'),
('LOC_SLTH_BUILDING_STIGMATA_ON_THE_UNBORN_NAME', 'Stigmata On The Unborn', 'en_US'),
('LOC_SLTH_BUILDING_SYLIVENS_PERFECT_LYRE_NAME', 'Sylivens Perfect Lyre', 'en_US'),
('LOC_SLTH_BUILDING_TABLETS_OF_BAMBUR_NAME', 'Tablets Of Bambur', 'en_US'),
('LOC_SLTH_BUILDING_TAILOR_NAME', 'Tailor', 'en_US'),
('LOC_SLTH_BUILDING_TAVERN_GRIGORI_NAME', 'Tavern Grigori', 'en_US'),
('LOC_SLTH_BUILDING_TAVERN_NAME', 'Tavern', 'en_US'),
('LOC_SLTH_BUILDING_TEMPLE_OF_THE_HAND_NAME', 'Temple Of The Hand', 'en_US'),
('LOC_SLTH_BUILDING_THE_DRAGONS_HORDE_NAME', 'The Dragons Horde', 'en_US'),
('LOC_SLTH_BUILDING_THE_NECRONOMICON_NAME', 'The Necronomicon', 'en_US'),
('LOC_SLTH_BUILDING_THE_NEXUS_NAME', 'The Nexus', 'en_US'),
('LOC_SLTH_BUILDING_TIGER_CAGE_NAME', 'Tiger Cage', 'en_US'),
('LOC_BUILDING_TOWER_OF_EYES_NAME', 'Tower Of Eyes', 'en_US'),
('LOC_SLTH_BUILDING_TOWER_OF_NECROMANCY_NAME', 'Tower Of Necromancy', 'en_US'),
('LOC_SLTH_BUILDING_TOWER_OF_THE_ELEMENTS_NAME', 'Tower Of The Elements', 'en_US'),
('LOC_SLTH_BUILDING_WALLS_NAME', 'Walls', 'en_US'),
('LOC_SLTH_BUILDING_WARRENS_NAME', 'Warrens', 'en_US'),
('LOC_SLTH_BUILDING_WOLF_PEN_NAME', 'Wolf Pen', 'en_US'),
('LOC_BUILDING_ALCHEMICAL_SOCIETY_DESCRIPTION', '50% [ICON_Science]Science in this City.', 'en_US'),
('LOC_BUILDING_ANGKOR_WAT_DESCRIPTION', 'Grants a source of [ICON_RESOURCE_MANA_SUN]Sun Mana. Disciple Units trained in this city gain +16 experience. Can support a Priest and a Sage. Reveals invisible units within your borders*.', 'en_US'),
('LOC_SLTH_BUILDING_ADULARIA_CHAMBER_DESCRIPTION', 'Golems trained in this city start with the Invisible Ability.*+3%[ICON_Production].', 'en_US'),
('LOC_SLTH_BUILDING_AQUEDUCT_DESCRIPTION', 'PLACEHOLDER', 'en_US'),
('LOC_SLTH_BUILDING_ARENA_DESCRIPTION', 'PLACEHOLDER', 'en_US'),
('LOC_SLTH_BUILDING_SYNAGOGUE_DESCRIPTION', 'PLACEHOLDER BASILICA', 'en_US'),
('LOC_SLTH_BUILDING_BLASTING_WORKSHOP_DESCRIPTION', 'Golems trained in this city can cast Fireball*.+3%[ICON_Production].', 'en_US'),
('LOC_SLTH_BUILDING_CAVE_OF_ANCESTORS_DESCRIPTION', 'Amurite Unique Building. Grants 1 Experience per type of Mana owned to Magic units trained in this city.', 'en_US'),
('LOC_SLTH_BUILDING_CHANCEL_DESCRIPTION', 'Grants built units the Defensive ability.*', 'en_US'),
('LOC_SLTH_BUILDING_BIBLIOTHEQUE_DESCRIPTION', 'Reduces Maintenance of this City by 40%. +1 [ICON_Amenities]Amenity with Social Order.', 'en_US'),
('LOC_SLTH_BUILDING_FREAK_SHOW_DESCRIPTION', 'Balseraph Unique Building. Unlocked with Festivals. Grants +1 [ICON_Amenities]Amenity, +2 [ICON_Culture]Culture, and a Bard Specialist slot. Allows Slaves to be used to build Cage Buildings of the different races.', 'en_US'),
('LOC_BUILDING_GRANARY_DESCRIPTION', '20% increased Growth Rate in this city. +1[ICON_Housing] Housing for having a source of [ICON_RESOURCE_MAIZE]Corn, [ICON_RESOURCE_RICE]Rice and [ICON_RESOURCE_WHEAT]Wheat, respectively.', 'en_US'),
('LOC_SLTH_BUILDING_HALL_OF_MIRRORS_DESCRIPTION', 'Balseraph Unique Building. Unlocked with Alteration and requires a Carnival. Creates a copy of the strongest Unit adjacent to the city. The copy lasts for 3 turns.', 'en_US'),
('LOC_SLTH_BUILDING_INFIRMARY_DESCRIPTION', 'Units heal 25% faster in this city.*', 'en_US'),
('LOC_SLTH_BUILDING_MONUMENT_DESCRIPTION', 'Cheap, simple Culture Building.', 'en_US'),
('LOC_SLTH_BUILDING_PALLENS_ENGINE_DESCRIPTION', 'Golems trained in this city start with the Perfect Sight Ability, seeing Invisible Units.*+3%[ICON_Production].', 'en_US'),
('LOC_SLTH_BUILDING_PLANAR_GATE_DESCRIPTION', 'Sheaim Unique Building. Spawns special units randomly depending on other Buildings present in city, chance and number increased by the Armageddon Counter. ', 'en_US'),
('LOC_SLTH_BUILDING_SMOKEHOUSE_DESCRIPTION', '20% Growth Rate in this City. +1 Housing from [ICON_RESOURCE_CATTLE]Cow, [ICON_RESOURCE_TRUFFLES]Pig, [ICON_RESOURCE_SHEEP]Sheep and [ICON_RESOURCE_TOAD]Toad.', 'en_US'),
('LOC_SLTH_BUILDING_AMPITHEATRE_DESCRIPTION', '+1 [ICON_Amenities]Amenity for having a source of Dyes. +1 [ICON_Amenities]Amenity per 10% of [ICON_Culture]Culture converted from [ICON_Faith]Commerce.*+1 [ICON_Amenities]Amenity with the Consumption Policy.', 'en_US'),
('LOC_SLTH_BUILDING_BONE_PALACE_DESCRIPTION', 'Starts a Golden Age*. Units in the city are 50% resistant to Magic*.', 'en_US'),
('LOC_BUILDING_CITY_OF_A_THOUSAND_SLUMS_DESCRIPTION', 'Would grant allow a city to have 4 radius of working tiles, if it worked! which it doesn''t.', 'en_US'),
('LOC_SLTH_BUILDING_GREAT_LIBRARY_DESCRIPTION', 'PLACEHOLDER GREAT LIB', 'en_US'),
('LOC_SLTH_BUILDING_DESERT_UNIVERSITY_DESCRIPTION', 'PLACEHOLDER GUILD OF THE NINE', 'en_US'),
('LOC_SLTH_BUILDING_ST_BASILS_DESCRIPTION', 'PLACEHOLDER HALL OF KINGS', 'en_US'),
('LOC_SLTH_BUILDING_CRISTO_REDENTOR_DESCRIPTION', 'PLACEHOLDER SIRONA', 'en_US'),
('LOC_SLTH_BUILDING_HAGIA_SOPHIA_DESCRIPTION', 'PLACEHOLDER TEMPLE OF TEMPORANCE', 'en_US'),
('LOC_SLTH_BUILDING_ORZAGHAZ_DESCRIPTION', 'PLACEHOLDER WINTER PALACE', 'en_US'),
('LOC_BUILDING_BANK_DESCRIPTION', '25% [ICON_Gold] Gold in this City.', 'en_US'),
('LOC_BUILDING_TRAINING_YARD_DESCRIPTION', 'Required to train Axemen, Champion, Phalanx and Berserkers.[NEWLINE] +1 [ICON_Amenities]Amenity with Nationhood.', 'en_US'),
('LOC_BUILDING_TOWER_OF_COMPLACENCY_DESCRIPTION', '-10% [ICON_Production]Production to Military Units. -50% reduced Maintenance. ', 'en_US'),
('LOC_BUILDING_THEATER_OF_DREAMS_DESCRIPTION', '+1 [ICON_Amenities]Amenity per city.', 'en_US'),
('LOC_BUILDING_TEMPLE_OF_THE_ORDER_DESCRIPTION', '+10% [ICON_Production]Production towards Military Units. 20% [ICON_Culture]Culture in this City. +1 [ICON_Amenities]Amenity from [ICON_RESOURCE_INCENSE]Incense. +1 [ICON_Amenities]Amenity with the Religion Policy. Required to train Acolyte, Confessor and Crusader.', 'en_US'),
('LOC_SLTH_BUILDING_INN_DESCRIPTION', 'Units heal 25% faster in this city*. +1 Trade Route Capacity. +25 to all international Trade Route yields. +1 [ICON_Amenities]Amenity for having a source of [ICON_RESOURCE_WINE]Wine.', 'en_US'),
('LOC_SLTH_BUILDING_TOWER_OF_MASTERY_DESCRIPTION', 'Building this Wonder wins you the Tower of Mastery Victory. Requires the 4 preceding Towers, Tower of Elements, Tower of Divination, Tower of Alteration. Tower of Necromancy.', 'en_US'),
('LOC_BUILDING_TAX_OFFICE_DESCRIPTION', '25% [ICON_Gold] Gold in this City.', 'en_US'),
('LOC_BUILDING_BAZAAR_OF_MAMMON_DESCRIPTION', '100% [ICON_Gold] Gold in this City. Allows slotting 3 Merchants.', 'en_US'),
('LOC_BUILDING_GREAT_LIGHTHOUSE_DESCRIPTION', '+2 Trade Route Capacity per coastal city.', 'en_US'),
('LOC_BUILDING_GROVE_DESCRIPTION', 'Required to train Beastmasters and Druids. They also grants +2[ICON_Amenities] Amenities with the Guardian of Nature Policy.', 'en_US'),
('LOC_BUILDING_TEMPLE_OF_THE_EMPYREAN_DESCRIPTION', '10% [ICON_Science] Science in this City. 20% [ICON_Culture] Culture in this City. +1 [ICON_Amenities]Amenity from [ICON_RESOURCE_INCENSE]Incense. +1 [ICON_Amenities]Amenity with the Religion Policy. Required to build Ecclesiastic and Vicars.', 'en_US'),
('LOC_BUILDING_HERON_THRONE_DESCRIPTION', '+1 [ICON_Production]Production on Water tiles in this city.', 'en_US'),
('LOC_BUILDING_MINES_OF_GALDUR_DESCRIPTION', 'Provides +3 [ICON_RESOURCE_IRON]Iron per turn. -2 Housing. 1 Great Engineer point. Allows 3 Engineer specialists.*', 'en_US'),
('LOC_BUILDING_LIBRARY_DESCRIPTION', '25% [ICON_Science] Science in this City.+1 [ICON_Amenities]Amenity with the Scholarship Policy.', 'en_US'),
('LOC_BUILDING_LIGHTHOUSE_DESCRIPTION', '+1 Trade Route Capacity. +1 [ICON_Food] Food from Water tiles in this city.', 'en_US'),
('LOC_BUILDING_MAGE_GUILD_DESCRIPTION', 'Required to train Adepts.', 'en_US'),
('LOC_SLTH_BUILDING_TOWER_OF_ALTERATION_DESCRIPTION', 'This tower both increases your own units resistance to spells and reduces your enemies resistance to your spells*.[NEWLINE]Requires 4 Mana Resources: [ICON_RESOURCE_MANA_BODY]Body, [ICON_RESOURCE_MANA_ENCHANTMENT]Enchantment, [ICON_RESOURCE_MANA_LIFE]Life, [ICON_RESOURCE_MANA_NATURE]Nature.[NEWLINE]Required to build the Tower of Mastery, which wins the game', 'en_US'),
('LOC_SLTH_BUILDING_HUNTING_LODGE_DESCRIPTION', 'Required to train Hunters, Hawks, Rangers and Assassins. +1[ICON_Housing] Housing and +1 [ICON_Amenities] Amenity if you have a source of [ICON_RESOURCE_DEER]Deer*.', 'en_US'),
('LOC_BUILDING_MARKET_DESCRIPTION', 'Cheap easy way to bankroll a civ. Comes at a Science penalty.', 'en_US'),
('LOC_BUILDING_TEMPLE_OF_THE_OVERLORDS_DESCRIPTION', '20% [ICON_Culture] Culture in this City. Can slot an additional Sage. +1 [ICON_Amenities]Amenity from [ICON_RESOURCE_INCENSE]Incense. +1 [ICON_Amenities]Amenity with the Religion Policy. Required to train Zealot, Cultist and Stygian Guard. Allows converting Warriors to Drowns.', 'en_US'),
('LOC_SLTH_BUILDING_TOWER_OF_DIVINATION_DESCRIPTION', 'Grant a random technology.[NEWLINE]Requires 4 Mana Resources: [ICON_RESOURCE_MANA_LAW]Law, [ICON_RESOURCE_MANA_MIND]Mind, [ICON_RESOURCE_MANA_SPIRIT]Spirit, [ICON_RESOURCE_MANA_SUN]Sun.[NEWLINE]Required to build the Tower of Mastery, which wins the game', 'en_US'),
('LOC_BUILDING_BREEDING_PIT_IMPRACTICAL_DESCRIPTION', 'Increases the food available to the city, making it grow faster. Little care is given to the nutritional value or method of delivery of the food, however, and the health of the city is lowered by one.', 'en_US'),
('LOC_BUILDING_PALGUM_DESCRIPTION', '+2 Ale Luxury Resource.[NEWLINE]10% [Icon_Faith]Commerce in this city for having a source of [ICON_RESOURCE_MAIZE]Corn, [ICON_RESOURCE_RICE]Rice and [ICON_RESOURCE_WHEAT]Wheat, respectively.[NEWLINE]Must be built in a city next to a river.', 'en_US'),
('LOC_BUILDING_CATACOMB_LIBRALUS_DESCRIPTION', 'Grants a free Mage Guild in all cities.', 'en_US'),
('LOC_BUILDING_RESEARCH_LAB_DESCRIPTION', '10% [ICON_Science] Science in this City.', 'en_US'),
('LOC_BUILDING_TEMPLE_OF_LEAVES_DESCRIPTION', '20% [ICON_Culture] Culture in this City. Can slot an additional Bard. +1 [ICON_Amenities]Amenity from [ICON_RESOURCE_INCENSE]Incense. +1 [ICON_Amenities]Amenity with the Religion Policy. Required to train Disciple and Priest of the Leaves. Triples the chance of Treant spawning to defend Ancient Forests*.', 'en_US'),
('LOC_BUILDING_SHIPYARD_DESCRIPTION', 'Naval units are granted +32 experience. +25% production towards Naval units in this city. Required to train Queen of the Line.', 'en_US'),
('LOC_BUILDING_SHRINE_DESCRIPTION', '10% [ICON_Culture] Culture in this City. +1 [ICON_Amenities]Amenity from [ICON_RESOURCE_INCENSE]Incense. +1 [ICON_Amenities]Amenity with the Religion Policy.', 'en_US'),
('LOC_BUILDING_SHRINE_OF_SIRONA_DESCRIPTION', 'Allows you to heal one of your units per turn.', 'en_US'),
('LOC_BUILDING_STABLE_DESCRIPTION', 'Required to train Horsemen, Horse Archers and Knights.', 'en_US'),
('LOC_BUILDING_TEMPLE_OF_THE_VEIL_DESCRIPTION', '20% [ICON_Culture] Culture in this City. Can slot an additional Sage. +1 [ICON_Amenities]Amenity from [ICON_RESOURCE_SPICES]Reagents. +1 [ICON_Amenities]Amenity with the Religion Policy. Required to train Savant, Ritualist and Beast of Agares.', 'en_US'),
('LOC_BUILDING_GRAND_MENAGERIE_DESCRIPTION', 'Grant a free Carnival in all cities. +2 [ICON_Amenities]Amenities per city. 20% [ICON_Culture] Culture in this City.', 'en_US'),
('LOC_BUILDING_WALLS_DESCRIPTION', 'While not as strong as Walls, Palisades provide a cheap defense of a city to fend off early aggression.', 'en_US'),
('LOC_BUILDING_TEMPLE_OF_KILMORPH_DESCRIPTION', '20% [ICON_Culture] Culture in this City. Can slot an additional Merchant. +1 [ICON_Amenities]Amenity from [ICON_RESOURCE_DIAMONDS]Gems. +1 [ICON_Amenities]Amenity with the Religion Policy. Required to train Thane, Stonewarden and Paramander.', 'en_US'),
('LOC_BUILDING_FORGE_DESCRIPTION', '25% [ICON_Production] Production in this City. Removes the Rusted promotion from units. +1 [ICON_Amenities]Amenity from [ICON_RESOURCE_GOLD]Gold.', 'en_US'),
('LOC_SLTH_BUILDING_ADVENTURERS_GUILD_DESCRIPTION', 'Grigori unique Building. 25% Great Person points generated per turn. Land units trained in this city get +16 experience.', 'en_US'),
('LOC_SLTH_BUILDING_ALTAR_OF_THE_LUONNOTAR_ANOINTED_DESCRIPTION', 'New Disciple units recieve +32 experience. Can support a Priest Specialist.', 'en_US'),
('LOC_SLTH_BUILDING_ALTAR_OF_THE_LUONNOTAR_BLESSED_DESCRIPTION', '+1 [ICON_Amenities]Amenities in all your cities. +1 [ICON_Production]Production to all Priest Specialists and this city can host one more Priest. Free Blessed Ability for all Units produced in this city. New Disciple class Units trained in this city receive +25 experience.', 'en_US'),
('LOC_SLTH_BUILDING_ALTAR_OF_THE_LUONNOTAR_CONSECRATED_DESCRIPTION', '+2 [ICON_Amenities]Amenities in all your cities. +1 [ICON_Production]Production to all Priest Specialists and this city can host two more Priests. Free Blessed Ability for all Units produced in this city. New Disciple class Units trained in this city receive +33 experience.', 'en_US'),
('LOC_SLTH_BUILDING_ALTAR_OF_THE_LUONNOTAR_DESCRIPTION', 'Disciple units trained in this city gain +16 experience. Can support a Priest Specialist.', 'en_US'),
('LOC_SLTH_BUILDING_ALTAR_OF_THE_LUONNOTAR_DIVINE_DESCRIPTION', '+2 [ICON_Amenities]Amenities in all your cities. +2 [ICON_Production]Production to all Priest Specialists and this city can host two more Priests. Free Blessed Ability for all Units produced in this city. New Disciple class Units trained in this city receive +49 experience.', 'en_US'),
('LOC_SLTH_BUILDING_ALTAR_OF_THE_LUONNOTAR_EXALTED_DESCRIPTION', '+3 [ICON_Amenities]Amenities in all your cities. +2 [ICON_Production]Production to all Priest Specialists and this city can host two more Priests. Free Blessed Ability for all Units produced in this city. New Disciple class Units trained in this city receive +58 experience.', 'en_US'),
('LOC_SLTH_BUILDING_ALTAR_OF_THE_LUONNOTAR_FINAL_DESCRIPTION', '+3 [ICON_Amenities]Amenities in all your cities. +3 [ICON_Production]Production to all Priest Specialists. Free Blessed Ability for all Units produced in this city. New Disciple class Units trained in this city receive +67 experience. Starts a Golden Age.', 'en_US'),
('LOC_BUILDING_AQUAE_SUCELLUS_DESCRIPTION', '+1[ICON_Housing] Housing in each city.', 'en_US'),
('LOC_SLTH_BUILDING_ARCHERY_RANGE_DESCRIPTION', 'Required to train Archers, Longbowmen, Crossbowmen and Marksmen.', 'en_US'),
('LOC_SLTH_BUILDING_ASYLUM_DESCRIPTION', 'Accumulate -25% less war weariness than usual. 15% [ICON_Science] Science in this City.', 'en_US'),
('LOC_SLTH_BUILDING_CARNIVAL_DESCRIPTION', '20% [ICON_Culture] Culture in this City. Required to build Animal Cages from captured Animals.', 'en_US'),
('LOC_SLTH_BUILDING_CELESTIAL_COMPASS_DESCRIPTION', '50% [Icon_Production]Production to Projects in all cities', 'en_US'),
('LOC_SLTH_BUILDING_CITADEL_OF_LIGHT_DESCRIPTION', 'I do not know what this does.', 'en_US'),
('LOC_SLTH_BUILDING_CODE_OF_JUNIL_DESCRIPTION', '+1 [ICON_RESOURCE_MANA_LAW]Law Mana from city. +1[Icon_Gold] per city with [ICON_RELIGION_UH] Order. Allows slotting 2 additional Prophets and 1 additional Merchant. Can only be constructed in The Order Holy City, by a Great Prophet or Great Commander.', 'en_US'),
('LOC_SLTH_BUILDING_COMMAND_POST_DESCRIPTION', '+20% Bonus Production to Military Units. +16 experience to all trained units.', 'en_US'),
('LOC_SLTH_BUILDING_CROWN_OF_AKHARIEN_DESCRIPTION', '100% [ICON_Science] Science in this City. Can be picked up as Equipment.', 'en_US'),
('LOC_SLTH_BUILDING_DANCING_BEAR_DESCRIPTION', 'Built by a captured Bear unit, grants +1[ICON_Amenities]Amenity.', 'en_US'),
('LOC_SLTH_BUILDING_DESERT_SHRINE_DESCRIPTION', 'Malakim Pagan Temple Replacement. 10% [ICON_Culture] Culture in this City. +16  experience to trained Disciple units. +1 [ICON_Amenities]Amenity from [ICON_RESOURCE_INCENSE]Incense.', 'en_US'),
('LOC_SLTH_BUILDING_DUNGEON_DESCRIPTION', 'Accumulate -25% less war weariness than usual.', 'en_US'),
('LOC_SLTH_BUILDING_DWARF_CAGE_DESCRIPTION', 'Built by a captured Slave with the Dwarf promotion, grants +1[ICON_Amenities]Amenity', 'en_US'),
('LOC_SLTH_BUILDING_DWARVEN_SMITHY_DESCRIPTION', 'Khazad Forge Replacement. 20% [ICON_Production] Production in this City. 10% more [ICON_Production] Production for having a source of [ICON_RESOURCE_COPPER]Copper, [ICON_RESOURCE_IRON]Iron and [ICON_RESOURCE_SILVER]Mithril, respectively.', 'en_US'),
('LOC_SLTH_BUILDING_DWARVEN_VAULT_ABUNDANT_DESCRIPTION', '10% [ICON_Production] Production in this City.', 'en_US'),
('LOC_SLTH_BUILDING_DWARVEN_VAULT_FULL_DESCRIPTION', '25% [ICON_Production] Production in this City.', 'en_US'),
('LOC_SLTH_BUILDING_DWARVEN_VAULT_OVERFLOWING_DESCRIPTION', '25% Great Person Great People points generated per turn. 40% [ICON_Production] Production in this City.', 'en_US'),
('LOC_SLTH_BUILDING_ELDER_COUNCIL_DESCRIPTION', 'Cheap, simple Science building.', 'en_US'),
('LOC_SLTH_BUILDING_ELF_CAGE_DESCRIPTION', 'Built by a captured Slave with the Elf promotion, grants +1 [ICON_Amenities]Amenity', 'en_US'),
('LOC_SLTH_BUILDING_EYES_AND_EARS_NETWORK_DESCRIPTION', 'Grants a technology to your civilization for free, if three players you have open borders agreements with already have it.', 'en_US'),
('LOC_SLTH_BUILDING_FORM_OF_THE_TITAN_DESCRIPTION', '+16 experience to all trained units. Requires a unit of level 6 or more to produce*. Produced twice as fast with [ICON_RESOURCE_COPPER]Copper.', 'en_US'),
('LOC_SLTH_BUILDING_GAMBLING_HOUSE_DESCRIPTION', 'A Gambling House grants some happiness per 10% of the gold rate*. It does tend to draw crime* and increases the maintenance cost of the city.', 'en_US'),
('LOC_SLTH_BUILDING_GORILLA_CAGE_DESCRIPTION', 'Built by a captured Gorilla unit, grants +1 [ICON_Amenities]Amenity.', 'en_US'),
('LOC_SLTH_BUILDING_GOVERNORS_MANOR_DESCRIPTION', 'Calabim Courthouse replacement. -1 [ICON_Amenities]Amenities. +1 production per required[ICON_Amenities]Amenity. -20% Maintenance in this city. Accumulate -25% less war weariness than usual.', 'en_US'),
('LOC_SLTH_BUILDING_GUILD_OF_HAMMERS_DESCRIPTION', 'Grant a free Forge in all cities. +1[ICON_Production] to all Engineers.', 'en_US'),
('LOC_SLTH_BUILDING_HARBOR_DESCRIPTION', '+50% to all international Trade Route yields. +1[ICON_Housing] Housing for having a source of [ICON_RESOURCE_TURTLES]Clam, [ICON_RESOURCE_CRABS]Crabs and [ICON_RESOURCE_FISH]Fish, respectively.', 'en_US'),
('LOC_SLTH_BUILDING_HARBOR_LANUN_DESCRIPTION', 'Lanun Harbor Replacement. International Trade Route yields grant 50% more yields. +25% production towards Naval units in this city. +1[ICON_Housing] Housing if you have a source of [ICON_RESOURCE_TURTLES]Clam, [ICON_RESOURCE_CRABS]Crabs and [ICON_RESOURCE_FISH]Fish, respectively.', 'en_US'),
('LOC_SLTH_BUILDING_HEROIC_EPIC_DESCRIPTION', '+100% Bonus Production to Military Units.', 'en_US'),
('LOC_SLTH_BUILDING_HUMAN_CAGE_DESCRIPTION', 'Built by a captured Slave without any racial promotion, grants +1 [ICON_Amenities]Amenity', 'en_US'),
('LOC_SLTH_BUILDING_INFERNAL_GRIMOIRE_DESCRIPTION', 'The secrets of Hell allows unlocking a random Technology... but may come at a price. Can be picked up as Equipment, allowing the user to cast Read Grimoire, casting a random spell.', 'en_US'),
('LOC_SLTH_BUILDING_JEWELER_DESCRIPTION', 'Grants the Jewels Luxury Resource. +1 [ICON_Amenities]Amenity, +5% [ICON_Gold]Gold from having a source of [ICON_RESOURCE_GOLD]Gold, [ICON_RESOURCE_DIAMONDS]Gems, and [ICON_RESOURCE_PEARLS]Pearls.', 'en_US'),
('LOC_SLTH_BUILDING_LION_CAGE_DESCRIPTION', 'Built by a captured Lion unit, grants +1 [ICON_Amenities]Amenity.', 'en_US'),
('LOC_SLTH_BUILDING_MERCURIAN_GATE_DESCRIPTION', 'Accumulate -100% less war weariness than usual.', 'en_US'),
('LOC_SLTH_BUILDING_MOKKAS_CAULDRON_DESCRIPTION', 'Raises units that die in the city as demons.', 'en_US'),
('LOC_SLTH_BUILDING_NATIONAL_EPIC_DESCRIPTION', '100% Great Person Great People points generated per turn.', 'en_US'),
('LOC_SLTH_BUILDING_NOX_NOCTIS_DESCRIPTION', 'Grants a source of [ICON_RESOURCE_MANA_SHADOW]Shadow Mana. +16 experience to Recon units. Makes units in your borders not in cities invisible*. Supports a Bard and a Merchant. +1 Gold per city with Council of Esus.', 'en_US'),
('LOC_SLTH_BUILDING_OBSIDIAN_GATE_DESCRIPTION', 'Can teleport a unit in this city to any of your other cities*. +1 Trade Route Capacity.', 'en_US'),
('LOC_SLTH_BUILDING_ORC_CAGE_DESCRIPTION', 'Built by a captured Slave with the Orc ability, grants +1 [ICON_Amenities]Amenity', 'en_US'),
('LOC_BUILDING_PILLAR_OF_CHAINS_DESCRIPTION', 'Accumulate -10% less war weariness than usual. +4 to the Armageddon Counter. +1 [ICON_Production] per required [ICON_Amenities]Amenity in this city*.', 'en_US'),
('LOC_SLTH_BUILDING_PROPHECY_OF_RAGNAROK_DESCRIPTION', 'Units trained in this city gain the Prophecy Mark ability, increasing Armageddon count by 1 while alive. Can support an additional Priest.', 'en_US'),
('LOC_SLTH_BUILDING_PUBLIC_BATHS_DESCRIPTION', 'A lot more than bathing goes on at a Public Bathhouse. Because of these side activities, the happiness of the city is increased, but the health is reduced.', 'en_US'),
('LOC_SLTH_BUILDING_RELIQUARY_DESCRIPTION', 'Grants built units the Spirit Guide ability. -1 [ICON_Housing]Housing.', 'en_US'),
('LOC_SLTH_BUILDING_RIDE_OF_THE_NINE_KINGS_DESCRIPTION', 'Free Morale ability applied to all units trained in this city. +41 Experience to all Light Cavalry units trained in this City.', 'en_US'),
('LOC_SLTH_BUILDING_SCULPTORS_STUDIO_DESCRIPTION', 'Luichuirp Training Yard Replacement. Unlocked at Construction. Allows the production of Golems.', 'en_US'),
('LOC_SLTH_BUILDING_SHRINE_OF_THE_CHAMPION_DESCRIPTION', 'Free promotion to trained units.', 'en_US'),
('LOC_SLTH_BUILDING_SIEGE_WORKSHOP_DESCRIPTION', 'Required to train Chariots, Catapults and Cannons.', 'en_US'),
('LOC_SLTH_BUILDING_SMUGGLERS_PORT_DESCRIPTION', '+1 Trade Route Capacity. 25% [ICON_Gold]Gold in this City.', 'en_US'),
('LOC_SLTH_BUILDING_SONG_OF_AUTUMN_DESCRIPTION', '+1 [ICON_RESOURCE_MANA_NATURE]Nature Mana from city.', 'en_US'),
('LOC_SLTH_BUILDING_SOUL_FORGE_DESCRIPTION', 'World Wonder. +1 [ICON_RESOURCE_MANA_DEATH]Death Mana from city. When a unit is killed within this cities borders, gain [ICON_Production] Production equal to the unit''s experience + 10.*', 'en_US'),
('LOC_SLTH_BUILDING_SPIDER_PEN_DESCRIPTION', '+1 Silk from city.', 'en_US'),
('LOC_SLTH_BUILDING_STIGMATA_ON_THE_UNBORN_DESCRIPTION', 'Grants a source of [ICON_RESOURCE_MANA_ENTROPY]Entropy Mana. Free Stigmata ability granted to all units trained in the city. Supports two Priests and one Sage. +5 to Armageddon Count. +1 [ICON_Science]Science per city with Veil Religion. ', 'en_US'),
('LOC_SLTH_BUILDING_SYLIVENS_PERFECT_LYRE_DESCRIPTION', '100% [ICON_Culture] Culture in this City.Can be picked up as Equipment.', 'en_US'),
('LOC_SLTH_BUILDING_TABLETS_OF_BAMBUR_DESCRIPTION', '+1 [ICON_RESOURCE_MANA_EARTH]Earth Mana from city.', 'en_US'),
('LOC_SLTH_BUILDING_TAILOR_DESCRIPTION', 'Grants the Fine Clothes Luxury Resource. +1 [ICON_Amenities]Amenity, +5% [ICON_Gold]Gold from having [ICON_RESOURCE_DYES]Dye, [ICON_RESOURCE_COTTON]Cotton and [ICON_RESOURCE_SILK]Silk', 'en_US'),
('LOC_SLTH_BUILDING_TAVERN_DESCRIPTION', '10% increased Maintenance. +1 Trade Route Capacity. +25 to all international Trade Route yields.', 'en_US'),
('LOC_SLTH_BUILDING_TAVERN_GRIGORI_DESCRIPTION', 'Grigori Tavern Replacement. +1 Trade Route Capacity and +25% to all international Trade Route yields.', 'en_US'),
('LOC_SLTH_BUILDING_TEMPLE_OF_THE_HAND_DESCRIPTION', 'Illian Pagan Temple replacement. Converts all tiles in the city to Snow*. 10% [ICON_Culture] Culture in this City. +1 [ICON_Amenities]Amenity from [ICON_RESOURCE_INCENSE]Incense.', 'en_US'),
('LOC_SLTH_BUILDING_THE_DRAGONS_HORDE_DESCRIPTION', '+1 [ICON_RESOURCE_DIAMONDS]Gems resource. +1 [ICON_RESOURCE_GOLD]Gold resource. Grants Enchanted Blade ability to units trained in the city.', 'en_US'),
('LOC_SLTH_BUILDING_THE_NECRONOMICON_DESCRIPTION', '+1 [ICON_RESOURCE_MANA_WATER]Water Mana from city.', 'en_US'),
('LOC_SLTH_BUILDING_THE_NEXUS_DESCRIPTION', 'Grant a free Obsidian Gate in all cities.', 'en_US'),
('LOC_SLTH_BUILDING_TIGER_CAGE_DESCRIPTION', 'Built by a captured Tiger unit, grants +1 [ICON_Amenities]Amenity.', 'en_US'),
('LOC_BUILDING_TOWER_OF_EYES_DESCRIPTION', 'Grants free Dungeon in all cities. All trained units in this city gain the Sentry promotion.', 'en_US'),
('LOC_SLTH_BUILDING_TOWER_OF_NECROMANCY_DESCRIPTION', '+1 [ICON_RESOURCE_MANA_DEATH]Death Mana from city. All Undead units recieve +4[ICON_STRENGTH] Combat Strength. Can summon 5 additional Skeletons.[NEWLINE]Requires 4 Mana Resources: [ICON_RESOURCE_MANA_CHAOS]Chaos, [ICON_RESOURCE_MANA_DEATH]Death, [ICON_RESOURCE_MANA_ENTROPY]Entropy, [ICON_RESOURCE_MANA_SHADOW]Shadow.[NEWLINE]Required to build the Tower of Mastery, which wins the game', 'en_US'),
('LOC_SLTH_BUILDING_TOWER_OF_THE_ELEMENTS_DESCRIPTION', 'Elemental Summons have +4[ICON_STRENGTH] Combat Strength *. Summons a Elemental Guardian to defend this city.[NEWLINE]Requires 4 Mana Resources: [ICON_RESOURCE_MANA_AIR]Air, [ICON_RESOURCE_MANA_EARTH]Earth, [ICON_RESOURCE_MANA_FIRE]Fire, [ICON_RESOURCE_MANA_WATER]Water.[NEWLINE]Required to build the Tower of Mastery, which wins the game.', 'en_US'),
('LOC_SLTH_BUILDING_WALLS_DESCRIPTION', 'Stronger walls, that allow ranged attacks and protect a city from attack.', 'en_US'),
('LOC_SLTH_BUILDING_WOLF_PEN_DESCRIPTION', 'Built by a captured Wolf unit, grants +1 [ICON_Amenities]Amenity.', 'en_US'),
('LOC_BUILDING_ACHERONS_LAIR_NAME', 'Acheron''s lair', 'en_US'),
('LOC_BUILDING_ACHERONS_LAIR_DESCRIPTION', 'The city Acheron has designated to rest upon. Contains valuable jewels.', 'en_US'),
('LOC_SLTH_BUILDING_SHRINE_OF_THE_CHAMPION_NAME', 'Shrine of the Champion', 'en_US'),
('LOC_BUILDING_BREEDING_PIT_DESCRIPTION', '20% Growth Rate in this city.', 'en_US'),
('LOC_SLTH_BUILDING_WARRENS_DESCRIPTION', 'Built Units spawn a second copy. Excludes Siege, Naval, Hero and National Units.', 'en_US'),
('LOC_BUILDING_ARENA_DESCRIPTION', 'Balseraph Training Yard replacement. Units may cast Arena battle, gaining experience, Gold, and +2 [ICON_Amenities]Amenities briefly*, if they win. They die otherwise.', 'en_US'),
('LOC_PLACEHOLDER_QUOTE', '“Placeholder.”[NEWLINE]– A Wise Man', 'en_US'),
('LOC_BUILDING_HERBALIST_DESCRIPTION', '10% Increased Healing for units stationed in this city*. +1[ICON_Housing] Housing if you have a source of [ICON_RESOURCE_SPICES]Reagents.*', 'en_US'),
('LOC_BUILDING_COURTHOUSE_DESCRIPTION', '-40% reduced maintenance for this city. +1 [ICON_Amenities]Amenity when you have the Social Order policy.', 'en_US'),
('LOC_BUILDING_BASILICA_DESCRIPTION', '-40% reduced maintenance for this city. +1 [ICON_Amenities]Amenity when you have the Social Order policy. Requires the Order State Religion and The Order in this city.', 'en_US'),
('LOC_SLTH_BUILDING_DEMONS_ALTAR_DESCRIPTION', '-1 [ICON_Amenities]Amenity. Built units start with the Scourge promotion.* Demon Units start with +16 experience. Living units can cast Sacrifice, converting them into Science.', 'en_US'),
('LOC_BUILDING_GUILD_OF_THE_NINE_DESCRIPTION', 'Allows the owner to hire Mercenary Units.*', 'en_US'),
('LOC_BUILDING_HALL_OF_KINGS_DESCRIPTION', '+2 [ICON_Culture]Culture to all Specialists.[NEWLINE]Double [ICON_Production]Production with [ICON_RESOURCE_MARBLE]Marble.', 'en_US'),
('LOC_BUILDING_TEMPLE_OF_TEMPORENCE_DESCRIPTION', '+1 [ICON_Amenities]Amenity in all cities.[NEWLINE]Double [ICON_Production]Production with [ICON_RESOURCE_MARBLE]Marble.', 'en_US'),
('LOC_SLTH_BUILDING_DUMMY_NAME', '', 'en_US'),
('LOC_SLTH_BUILDING_DUMMY_DESCRIPTION', '', 'en_US');
