INSERT OR REPLACE INTO LocalizedText(Tag, Text, Language) VALUES
('LOC_PROJECT_SAMHAIN_SHORT', 'Samhain', 'en_US'),
('LOC_PROJECT_WHITE_HAND_SHORT', 'The White Hand', 'en_US'),
('LOC_PROJECT_DEEPENING_SHORT', 'The Deepening', 'en_US'),
('LOC_PROJECT_THE_DRAW_SHORT', 'The Draw', 'en_US'),
('LOC_PROJECT_ASCENSION_SHORT', 'Ascension', 'en_US'),
('LOC_PROJECT_STIR_FROM_SLUMBER_SHORT', 'Stir From Slumber', 'en_US'),
('LOC_PROJECT_ELEGY_OF_THE_SHEAIM_SHORT', 'Elegy of the Sheaim', 'en_US'),
('LOC_PROJECT_HALLOWING_OF_ELOHIM_SHORT', 'Hallowing of the Elohim', 'en_US'),
('LOC_PROJECT_BANE_DIVINE_SHORT', 'Bane Divine', 'en_US'),
('LOC_PROJECT_GLORY_EVERLASTING_SHORT', 'Glory Everlasting', 'en_US'),
('LOC_PROJECT_BIRTHRIGHT_REGAINED_SHORT', 'Birthright Regained', 'en_US'),
('LOC_PROJECT_PHOENIX_SHORT', 'Blood of the Phoenix', 'en_US'),
('LOC_PROJECT_GENESIS_SHORT', 'Genesis', 'en_US'),
('LOC_PROJECT_NATURES_REVOLT_SHORT', 'Nature''s Revolt', 'en_US'),
('LOC_PROJECT_RITES_OGHMA_SHORT', 'Rites of Oghma', 'en_US'),
('LOC_PROJECT_PURGE_THE_UNFAITHFUL_SHORT', 'Purge the Unfaithful', 'en_US'),
('LOC_PROJECT_PACT_OF_NILHORN_SHORT', 'Pact of the Nilhorn', 'en_US'),
('LOC_PROJECT_SAMHAIN_NAME', 'Samhain', 'en_US'),
('LOC_PROJECT_WHITE_HAND_NAME', 'The White Hand', 'en_US'),
('LOC_PROJECT_DEEPENING_NAME', 'The Deepening', 'en_US'),
('LOC_PROJECT_THE_DRAW_NAME', 'The Draw', 'en_US'),
('LOC_PROJECT_ASCENSION_NAME', 'Ascension', 'en_US'),
('LOC_PROJECT_STIR_FROM_SLUMBER_NAME', 'Stir From Slumber', 'en_US'),
('LOC_PROJECT_ELEGY_OF_THE_SHEAIM_NAME', 'Elegy of the Sheaim', 'en_US'),
('LOC_PROJECT_HALLOWING_OF_ELOHIM_NAME', 'Hallowing of the Elohim', 'en_US'),
('LOC_PROJECT_BANE_DIVINE_NAME', 'Bane Divine', 'en_US'),
('LOC_PROJECT_GLORY_EVERLASTING_NAME', 'Glory Everlasting', 'en_US'),
('LOC_PROJECT_BIRTHRIGHT_REGAINED_NAME', 'Birthright Regained', 'en_US'),
('LOC_PROJECT_PHOENIX_NAME', 'Blood of the Phoenix', 'en_US'),
('LOC_PROJECT_GENESIS_NAME', 'Genesis', 'en_US'),
('LOC_PROJECT_NATURES_REVOLT_NAME', 'Nature''s Revolt', 'en_US'),
('LOC_PROJECT_RITES_OGHMA_NAME', 'Rites of Oghma', 'en_US'),
('LOC_PROJECT_PURGE_THE_UNFAITHFUL_NAME', 'Purge the Unfaithful', 'en_US'),
('LOC_PROJECT_PACT_OF_NILHORN_NAME', 'Pact of the Nilhorn', 'en_US'),
('LOC_PROJECT_SAMHAIN_DESCRIPTION', 'Ritual. Unlocks access to the White Hand Ritual with Philosophy. Spawns barbarian frostlings across the map, as well as the frostling hero Mokka.', 'en_US'),
('LOC_PROJECT_WHITE_HAND_DESCRIPTION', 'Ritual. Unlocks access to the Deepening Ritual. Completing this ritual makes three Priest''s of Winter.', 'en_US'),
('LOC_PROJECT_DEEPENING_DESCRIPTION', 'Ritual. Unlocks access to The Draw Ritual with Strength of Will. Cool the world, changing some deserts to plains, plains and grasslands to tundra, tundra to snow.* It will also spawn occasional Blizzard''s around the map*.', 'en_US'),
('LOC_PROJECT_THE_DRAW_DESCRIPTION', 'Ritual. Unlocks access to the Ascension Ritual with Omniscience. Halves all your cities'' populations, damages all your units and causes you to declare permanent war on every player in the game.', 'en_US'),
('LOC_PROJECT_ASCENSION_DESCRIPTION', 'Ritual. Summons Auric the Ascended.', 'en_US'),
('LOC_PROJECT_STIR_FROM_SLUMBER_DESCRIPTION', 'Ritual. Awakens the White Dragon Drifa to your cause. To perform this ritual you must first remove another player from the game*.', 'en_US'),
('LOC_PROJECT_ELEGY_OF_THE_SHEAIM_DESCRIPTION', 'Repeatable project that increases the Armageddon counter by a small amount.', 'en_US'),
('LOC_PROJECT_HALLOWING_OF_ELOHIM_DESCRIPTION', 'Repeatable project that decreases the Armageddon counter by a small amount.', 'en_US'),
('LOC_PROJECT_BANE_DIVINE_DESCRIPTION', 'Ritual. Bane Divine severs the connection between the faithful and their deities. It turns all the world''s Disciple units into level 1 disciples with no promotions, even your own. It requires 70 Armageddon Count to start.', 'en_US'),
('LOC_PROJECT_GLORY_EVERLASTING_DESCRIPTION', 'Ritual. Destroys all demons in the world once. Requires a Armageddon Count of 70 to start.', 'en_US'),
('LOC_PROJECT_BIRTHRIGHT_REGAINED_DESCRIPTION', 'Ritual. Grants an additional use of your World Spell.', 'en_US'),
('LOC_PROJECT_PHOENIX_DESCRIPTION', 'Ritual. Grants the Immortal promotion to all of your current units.*', 'en_US'),
('LOC_PROJECT_GENESIS_DESCRIPTION', 'Ritual. Upgrades the terrain in your empire.*', 'en_US'),
('LOC_PROJECT_NATURES_REVOLT_DESCRIPTION', 'Ritual. Turns most of the world''s barbarian units into animals. All animals'' combat strength is increased.', 'en_US'),
('LOC_PROJECT_RITES_OGHMA_DESCRIPTION', 'Ritual. Creates new raw mana nodes throughout the world.', 'en_US'),
('LOC_PROJECT_PURGE_THE_UNFAITHFUL_DESCRIPTION', 'Repeatable Project. Removes all non-state religions and non-state religions'' buildings from all of the player''s cities.* It can cause rioting in the player''s affected cities. Increases the Armageddon Count.', 'en_US'),
('LOC_PROJECT_PACT_OF_NILHORN_DESCRIPTION', 'Ritual. Recruits 3 Hill Giants to the player''s cause.', 'en_US');