INSERT OR REPLACE INTO LocalizedText(Tag, Text, Language) VALUES
('LOC_SLTH_NULL_CIVILIZATION_CALABIM_NAME', 'ZZ_Banned for Civ', 'en_US'),
('LOC_SLTH_NULL_CIVILIZATION_CLAN_OF_EMBERS_NAME', 'ZZ_Banned for Civ', 'en_US'),
('LOC_SLTH_NULL_CIVILIZATION_DOVIELLO_NAME', 'ZZ_Banned for Civ', 'en_US'),
('LOC_SLTH_NULL_CIVILIZATION_GRIGORI_NAME', 'ZZ_Banned for Civ', 'en_US'),
('LOC_SLTH_NULL_CIVILIZATION_HIPPUS_NAME', 'ZZ_Banned for Civ', 'en_US'),
('LOC_SLTH_NULL_CIVILIZATION_INFERNAL_NAME', 'ZZ_Banned for Civ', 'en_US'),
('LOC_SLTH_NULL_CIVILIZATION_KURIOTATES_NAME', 'ZZ_Banned for Civ', 'en_US'),
('LOC_SLTH_NULL_CIVILIZATION_LJOSALFAR_NAME', 'ZZ_Banned for Civ', 'en_US'),
('LOC_SLTH_NULL_CIVILIZATION_SHEAIM_NAME', 'ZZ_Banned for Civ', 'en_US'),
('LOC_SLTH_NULL_CIVILIZATION_SVARTALFAR_NAME', 'ZZ_Banned for Civ', 'en_US');