INSERT OR REPLACE INTO LocalizedText(Tag, Text, Language) VALUES
('LOC_BELIEF_THE_ORDER_PANTH_SLTH_NAME', '', 'en_US'),
('LOC_BELIEF_EMPYREAN_PANTH_SLTH_NAME', '', 'en_US'),
('LOC_BELIEF_KILMORPH_PANTH_SLTH_NAME', '', 'en_US'),
('LOC_BELIEF_LEAVES_PANTH_SLTH_NAME', '', 'en_US'),
('LOC_BELIEF_OVERLORDS_PANTH_SLTH_NAME', '', 'en_US'),
('LOC_BELIEF_ESUS_PANTH_SLTH_NAME', '', 'en_US'),
('LOC_BELIEF_VEIL_PANTH_SLTH_NAME', '', 'en_US'),
('LOC_BELIEF_UNITS_GRANTED_WITHOUT_STATE_SLTH_NAME', 'Religious cities can build:', 'en_US'),
('LOC_THE_ORDER_BELIEFS', 'The Acolyte and Temple of the Order', 'en_US'),
('LOC_EMPYREAN_BELIEFS', 'The Ecclesiastic and Temple of the Empyrean', 'en_US'),
('LOC_KILMORPH_BELIEFS', 'Thane of Kilmorph and Temple of Kilmorph', 'en_US'),
('LOC_LEAVES_BELIEFS', 'Disciple of Leaves and Temple of Leaves', 'en_US'),
('LOC_OVERLORDS_BELIEFS', 'Zealot and Temple of the Overlords', 'en_US'),
('LOC_ESUS_BELIEFS', 'The Nightwatch to spread religion for a Gold cost, comparable to the Longbowman, and the ShadowRider, a National mounted unit that ignores fortifications.', 'en_US'),
('LOC_VEIL_BELIEFS', 'The Savant, and Temple of the Veil', 'en_US'),
('LOC_BELIEF_BUILDINGS_WITH_STATE_SLTH_NAME', 'As State Religion, Buildings:', 'en_US'),
('LOC_THE_ORDER_STATE_BUILDINGS', 'Basilicas acts as a second courthouse.', 'en_US'),
('LOC_EMPYREAN_STATE_BUILDINGS', 'Holy Wonder Dies Diei grants Sun Mana, along with the Perfect Sight ability for units', 'en_US'),
('LOC_KILMORPH_STATE_BUILDINGS', 'Mines of Gal-Dur Wonder provides a source of Iron', 'en_US'),
('LOC_LEAVES_STATE_BUILDINGS', 'Holy Wonder Song of Autumn provides nature mana', 'en_US'),
('LOC_OVERLORDS_STATE_BUILDINGS', 'Asylums grant science and Lunatic production, while reducing amenities by 1. The Tower of Complacency prevents city unhappiness.', 'en_US'),
('LOC_ESUS_STATE_BUILDINGS', 'Holy Wonder Nox Noctis provides a lot of experience to Recon units in its city.', 'en_US'),
('LOC_VEIL_STATE_BUILDINGS', 'Demons Altar allows sacrificing units for research, XP for demon units and the Scourge Ability. Holy Wonder Stigmata on the Unborn grants the Stigmata ability, increasing strength based on the Armageddon counter.', 'en_US'),
('LOC_BELIEF_UNITS_WITH_STATE_SLTH_NAME', 'As State Religion, Units:', 'en_US'),
('LOC_THE_ORDER_STATE_UNITS', 'Heros Valin and Sphener, and Crusaders, Confessors and Priors.', 'en_US'),
('LOC_EMPYREAN_STATE_UNITS', 'Hero Chalid, Radiant Guard, Ratha, Vicar and Luridus', 'en_US'),
('LOC_KILMORPH_STATE_UNITS', 'Heros Arthedain, Bambur and the Mithril Golem. Alongside Soldier of Kilmorph, Paramanders, Stonewardens and Runekeepers.', 'en_US'),
('LOC_LEAVES_STATE_UNITS', 'Heros Kithra Kyriel and Yvain, alongside Fawns and their upgrade Satyrs, Priest and High Priests of the Leaves', 'en_US'),
('LOC_OVERLORDS_STATE_UNITS', 'Heros Saverous and Hemah, alongside Drowns, Lunatics, Stygian Guards, Cultists and Speakers.', 'en_US'),
('LOC_ESUS_STATE_UNITS', 'Hero Gibbon Goetia and Shadows, the strongest assassin unit, being invisible to most units and able to snipe high value targets.', 'en_US'),
('LOC_VEIL_STATE_UNITS', 'Heros Rosier and Mardero, alongside Diseased Corpses to spread Plague, Beast of Agares which take a city population but are strong, and Ritualists and Profane.', 'en_US'),
('LOC_BELIEF_SPECIAL_WITH_STATE_SLTH_NAME', 'As State Religion, also grants:', 'en_US'),
('LOC_THE_ORDER_STATE_SPECIAL', 'The Civic Social Order, and 75% Acolyte spawn chance on converting a new city, Crusader after Fanatacism.', 'en_US'),
('LOC_EMPYREAN_STATE_SPECIAL', '', 'en_US'),
('LOC_KILMORPH_STATE_SPECIAL', 'The Arete Technology and Policy, granting mine production and GPP', 'en_US'),
('LOC_LEAVES_STATE_SPECIAL', 'The Hidden Paths Civic and Guardian of Nature Policy, forest will transform into Ancient Forest over time, and Treants may spawn in to defend Ancient Forests from invaders', 'en_US'),
('LOC_OVERLORDS_STATE_SPECIAL', 'Allows access to the Mind Staping civic, as well as the ability to convert any unit to a Drown.', 'en_US'),
('LOC_ESUS_STATE_SPECIAL', 'Any unit with the Esus religion can spread it, for a price. Recon units with the religion can cast Steal to steal gold from enemy cities and Mask to appear to others as barbarians (TODO). Prevents units from being removed from enemy territory on war declaration. Religion choice hidden from other players.', 'en_US'),
('LOC_VEIL_STATE_SPECIAL', 'Raises Armageddon count per city it is in. The Sacrifice the Weak civic reduces food consumption to 1, but also reduces GPP. One of the best Veil cities can be taken by Hyborem using his world spell.', 'en_US');
