INSERT OR REPLACE INTO LocalizedText(Tag, Text, Language) VALUES
('LOC_SLTH_EQUIPMENT_ATHAME_NAME', 'Athame', 'en_US'),
('LOC_SLTH_EQUIPMENT_BLACK_MIRROR_NAME', 'Black Mirror', 'en_US'),
('LOC_SLTH_EQUIPMENT_CROWN_OF_AKHARIEN_NAME', 'Crown Of Akharien', 'en_US'),
('LOC_SLTH_EQUIPMENT_CROWN_OF_COMMAND_NAME', 'Crown Of Command', 'en_US'),
('LOC_SLTH_EQUIPMENT_DRAGONS_HORDE_NAME', 'Dragons Horde', 'en_US'),
('LOC_SLTH_EQUIPMENT_EMPTY_BIER_NAME', 'Empty Bier', 'en_US'),
('LOC_SLTH_EQUIPMENT_GELA_NAME', 'Gela', 'en_US'),
('LOC_SLTH_EQUIPMENT_GODSLAYER_NAME', 'Godslayer', 'en_US'),
('LOC_SLTH_EQUIPMENT_GOLDEN_HAMMER_NAME', 'Golden Hammer', 'en_US'),
('LOC_SLTH_EQUIPMENT_HEALING_SALVE_NAME', 'Healing Salve', 'en_US'),
('LOC_SLTH_EQUIPMENT_INFERNAL_GRIMOIRE_NAME', 'Infernal Grimoire', 'en_US'),
('LOC_SLTH_EQUIPMENT_JADE_TORC_NAME', 'Jade Torc', 'en_US'),
('LOC_SLTH_EQUIPMENT_NETHER_BLADE_NAME', 'Nether Blade', 'en_US'),
('LOC_SLTH_EQUIPMENT_ORTHUSS_AXE_NAME', 'Orthuss Axe', 'en_US'),
('LOC_SLTH_EQUIPMENT_PIECES_OF_BARNAXUS_NAME', 'Pieces Of Barnaxus', 'en_US'),
('LOC_SLTH_EQUIPMENT_POTION_OF_INVISIBILITY_NAME', 'Potion Of Invisibility', 'en_US'),
('LOC_SLTH_EQUIPMENT_POTION_OF_RESTORATION_NAME', 'Potion Of Restoration', 'en_US'),
('LOC_SLTH_EQUIPMENT_ROD_OF_WINDS_NAME', 'Rod Of Winds', 'en_US'),
('LOC_SLTH_EQUIPMENT_SCORCHED_STAFF_NAME', 'Scorched Staff', 'en_US'),
('LOC_SLTH_EQUIPMENT_STAFF_OF_SOULS_NAME', 'Staff Of Souls', 'en_US'),
('LOC_SLTH_EQUIPMENT_SYLIVENS_PERFECT_LYRE_NAME', 'Sylivens Perfect Lyre', 'en_US'),
('LOC_SLTH_EQUIPMENT_TIMOR_MASK_NAME', 'Timor Mask', 'en_US'),
('LOC_SLTH_EQUIPMENT_TREASURE_NAME', 'Treasure', 'en_US'),
('LOC_SLTH_EQUIPMENT_WAR_NAME', 'War', 'en_US'),
('LOC_SLTH_EQUIPMENT_ATHAME_DESCRIPTION', 'When Equipped, gives +18 Poison Combat Strength, and passes the Plagued debuff onto units.', 'en_US'),
('LOC_SLTH_EQUIPMENT_BLACK_MIRROR_DESCRIPTION', 'When Equipped, allows casting Mirror Ability.', 'en_US'),
('LOC_SLTH_EQUIPMENT_CROWN_OF_AKHARIEN_DESCRIPTION', 'The Crown of Akharien Building can be transported between cities by a unit.', 'en_US'),
('LOC_SLTH_EQUIPMENT_CROWN_OF_COMMAND_DESCRIPTION', 'When Equipped, gives units a 30% chance to capture defeated units.', 'en_US'),
('LOC_SLTH_EQUIPMENT_DRAGONS_HORDE_DESCRIPTION', 'When Equipped, uhhhh', 'en_US'),
('LOC_SLTH_EQUIPMENT_EMPTY_BIER_DESCRIPTION', 'When Equipped, gives +12 Strength on Defense, and doubles Fortification Bonus.', 'en_US'),
('LOC_SLTH_EQUIPMENT_GELA_DESCRIPTION', 'When Equipped, gives +2 Unholy Combat Strength.', 'en_US'),
('LOC_SLTH_EQUIPMENT_GODSLAYER_DESCRIPTION', 'When Equipped, gives an unstoppable bonus against Avatar Class units.', 'en_US'),
('LOC_SLTH_EQUIPMENT_GOLDEN_HAMMER_DESCRIPTION', 'When Equipped, gives a a bonus build charge. When added to a city, gives production and Great Engineer Points.', 'en_US'),
('LOC_SLTH_EQUIPMENT_HEALING_SALVE_DESCRIPTION', 'When Equipped, allows Apply Salve, restoring health to full.', 'en_US'),
('LOC_SLTH_EQUIPMENT_INFERNAL_GRIMOIRE_DESCRIPTION', 'Provides a free tech when built, and can be read by a unit after being picked up for a random spell effect. Some say there is a cost to using the dark tome, but many risk it for the chance at power.', 'en_US'),
('LOC_SLTH_EQUIPMENT_JADE_TORC_DESCRIPTION', 'When Equipped, grants 20% spell resistance, and 25% poison resistance.', 'en_US'),
('LOC_SLTH_EQUIPMENT_NETHER_BLADE_DESCRIPTION', 'When Equipped, gives +12 Death Combat Strength, 80% Combat Strength vs Heros, and preventing resurrection of killed units and the addition to the Mane/Angel pool.', 'en_US'),
('LOC_SLTH_EQUIPMENT_ORTHUSS_AXE_DESCRIPTION', 'When Equipped, allows attacking multiple times per turn if movement allows and +1 Fire Combat Strength.', 'en_US'),
('LOC_SLTH_EQUIPMENT_PIECES_OF_BARNAXUS_DESCRIPTION', 'If brought back to a Luichuirp city, allows building of Barnaxus.', 'en_US'),
('LOC_SLTH_EQUIPMENT_POTION_OF_INVISIBILITY_DESCRIPTION', 'When Equipped, allows casting Hide to make a unit invisible.', 'en_US'),
('LOC_SLTH_EQUIPMENT_POTION_OF_RESTORATION_DESCRIPTION', 'When Equipped, allows Drink Potion, restoring health to full.', 'en_US'),
('LOC_SLTH_EQUIPMENT_ROD_OF_WINDS_DESCRIPTION', 'When Equipped, gives +1 Affinity for [ICON_RESOURCE_MANA_AIR]Air mana.', 'en_US'),
('LOC_SLTH_EQUIPMENT_SCORCHED_STAFF_DESCRIPTION', 'When Equipped, gives +1 Affinity for [ICON_RESOURCE_MANA_FIRE]Fire mana.', 'en_US'),
('LOC_SLTH_EQUIPMENT_STAFF_OF_SOULS_DESCRIPTION', 'When Equipped, gives +18 Combat Strength and +1 Affinity for [ICON_RESOURCE_MANA_DEATH]Death mana.', 'en_US'),
('LOC_SLTH_EQUIPMENT_SPELL_STAFF_NAME', 'SpellStaff', 'en_US'),
('LOC_SLTH_EQUIPMENT_SPELL_STAFF_DESCRIPTION', 'Equipment: Can be broken by a Depleted Mage to cast another spell this turn.', 'en_US'),
('LOC_SLTH_EQUIPMENT_SYLIVENS_PERFECT_LYRE_DESCRIPTION', 'When Equipped, uhhh', 'en_US'),
('LOC_SLTH_EQUIPMENT_TIMOR_MASK_DESCRIPTION', 'When Equipped, Allows Waterwalking, and makes unit immune to Fear.', 'en_US'),
('LOC_SLTH_EQUIPMENT_TREASURE_DESCRIPTION', 'Activate this Treasure Chest to unlock it, revealing a result.', 'en_US'),
('LOC_SLTH_EQUIPMENT_WAR_DESCRIPTION', 'When Equipped, gives +18 Unholy Combat Strength and any unit killed increases the Armageddon Counter by 1.', 'en_US');