INSERT OR REPLACE INTO LocalizedText(Tag, Text, Language) VALUES
('LOC_CITY_AMURITES_10_NAME', 'Seaneriel', 'en_US'),
('LOC_CITY_AMURITES_11_NAME', 'Angostendil', 'en_US'),
('LOC_CITY_AMURITES_12_NAME', 'Wendar', 'en_US'),
('LOC_CITY_AMURITES_13_NAME', 'Kevar', 'en_US'),
('LOC_CITY_AMURITES_14_NAME', 'Sylvair', 'en_US'),
('LOC_CITY_AMURITES_15_NAME', 'Doriath', 'en_US'),
('LOC_CITY_AMURITES_16_NAME', 'Surewatch', 'en_US'),
('LOC_CITY_AMURITES_17_NAME', 'Baamor', 'en_US'),
('LOC_CITY_AMURITES_18_NAME', 'Korrigan', 'en_US'),
('LOC_CITY_AMURITES_1_NAME', 'Cevedes', 'en_US'),
('LOC_CITY_AMURITES_2_NAME', 'Udenarat', 'en_US'),
('LOC_CITY_AMURITES_3_NAME', 'Nimarail', 'en_US'),
('LOC_CITY_AMURITES_4_NAME', 'Ciriail', 'en_US'),
('LOC_CITY_AMURITES_5_NAME', 'Glorairine', 'en_US'),
('LOC_CITY_AMURITES_6_NAME', 'Enaillellion', 'en_US'),
('LOC_CITY_AMURITES_7_NAME', 'Orrondhuir', 'en_US'),
('LOC_CITY_AMURITES_8_NAME', 'Sierundirel', 'en_US'),
('LOC_CITY_AMURITES_9_NAME', 'Coranttilli', 'en_US'),
('LOC_CITY_BALSERAPHS_10_NAME', 'Umbracle', 'en_US'),
('LOC_CITY_BALSERAPHS_11_NAME', 'Drassanes', 'en_US'),
('LOC_CITY_BALSERAPHS_12_NAME', 'Sant Mapfre', 'en_US'),
('LOC_CITY_BALSERAPHS_13_NAME', 'Nouveau', 'en_US'),
('LOC_CITY_BALSERAPHS_14_NAME', 'Girona', 'en_US'),
('LOC_CITY_BALSERAPHS_15_NAME', 'Horta', 'en_US'),
('LOC_CITY_BALSERAPHS_16_NAME', 'Tapas', 'en_US'),
('LOC_CITY_BALSERAPHS_17_NAME', 'Manresa', 'en_US'),
('LOC_CITY_BALSERAPHS_18_NAME', 'Ciutat', 'en_US'),
('LOC_CITY_BALSERAPHS_19_NAME', 'Bispe', 'en_US'),
('LOC_CITY_BALSERAPHS_1_NAME', 'Jubilee', 'en_US'),
('LOC_CITY_BALSERAPHS_20_NAME', 'Torre Paisos', 'en_US'),
('LOC_CITY_BALSERAPHS_2_NAME', 'Coombe View', 'en_US'),
('LOC_CITY_BALSERAPHS_3_NAME', 'Hexam', 'en_US'),
('LOC_CITY_BALSERAPHS_4_NAME', 'Argenteria', 'en_US'),
('LOC_CITY_BALSERAPHS_5_NAME', 'Gaudium', 'en_US'),
('LOC_CITY_BALSERAPHS_6_NAME', 'Guell', 'en_US'),
('LOC_CITY_BALSERAPHS_7_NAME', 'Ocells', 'en_US'),
('LOC_CITY_BALSERAPHS_8_NAME', 'Vincon', 'en_US'),
('LOC_CITY_BALSERAPHS_9_NAME', 'Miro', 'en_US'),
('LOC_CITY_BANNOR_10_NAME', 'Censura', 'en_US'),
('LOC_CITY_BANNOR_11_NAME', 'Domus Novus', 'en_US'),
('LOC_CITY_BANNOR_12_NAME', 'Fides', 'en_US'),
('LOC_CITY_BANNOR_13_NAME', 'Judicium', 'en_US'),
('LOC_CITY_BANNOR_14_NAME', 'Vis Vires', 'en_US'),
('LOC_CITY_BANNOR_15_NAME', 'Pactum', 'en_US'),
('LOC_CITY_BANNOR_16_NAME', 'Re Vera', 'en_US'),
('LOC_CITY_BANNOR_17_NAME', 'Barak-Tor', 'en_US'),
('LOC_CITY_BANNOR_18_NAME', 'Clar Manaul', 'en_US'),
('LOC_CITY_BANNOR_19_NAME', 'Athel Maraya', 'en_US'),
('LOC_CITY_BANNOR_1_NAME', 'Torrolerial', 'en_US'),
('LOC_CITY_BANNOR_20_NAME', 'Ithmariar', 'en_US'),
('LOC_CITY_BANNOR_21_NAME', 'Chaend', 'en_US'),
('LOC_CITY_BANNOR_2_NAME', 'Vallus', 'en_US'),
('LOC_CITY_BANNOR_3_NAME', 'Trinity', 'en_US'),
('LOC_CITY_BANNOR_4_NAME', 'Tentatio-onis', 'en_US'),
('LOC_CITY_BANNOR_5_NAME', 'Astrum', 'en_US'),
('LOC_CITY_BANNOR_6_NAME', 'Caelestis', 'en_US'),
('LOC_CITY_BANNOR_7_NAME', 'Ventry', 'en_US'),
('LOC_CITY_BANNOR_8_NAME', 'Corona', 'en_US'),
('LOC_CITY_BANNOR_9_NAME', 'Solium', 'en_US'),
('LOC_CITY_CALABIM_10_NAME', 'Maron', 'en_US'),
('LOC_CITY_CALABIM_11_NAME', 'Pinadom', 'en_US'),
('LOC_CITY_CALABIM_12_NAME', 'Amapia', 'en_US'),
('LOC_CITY_CALABIM_13_NAME', 'Kasava', 'en_US'),
('LOC_CITY_CALABIM_14_NAME', 'Pevas', 'en_US'),
('LOC_CITY_CALABIM_15_NAME', 'Anaea', 'en_US'),
('LOC_CITY_CALABIM_16_NAME', 'Strages', 'en_US'),
('LOC_CITY_CALABIM_1_NAME', 'Prespur', 'en_US'),
('LOC_CITY_CALABIM_2_NAME', 'Nubia', 'en_US'),
('LOC_CITY_CALABIM_3_NAME', 'Acaia', 'en_US'),
('LOC_CITY_CALABIM_4_NAME', 'Morrtanar', 'en_US'),
('LOC_CITY_CALABIM_5_NAME', 'Adonias', 'en_US'),
('LOC_CITY_CALABIM_6_NAME', 'Santaron', 'en_US'),
('LOC_CITY_CALABIM_7_NAME', 'Pavunar', 'en_US'),
('LOC_CITY_CALABIM_8_NAME', 'Krinera', 'en_US'),
('LOC_CITY_CALABIM_9_NAME', 'Itos', 'en_US'),
('LOC_CITY_CLAN_OF_EMBERS_10_NAME', 'Nezhev', 'en_US'),
('LOC_CITY_CLAN_OF_EMBERS_11_NAME', 'Nagas Tail', 'en_US'),
('LOC_CITY_CLAN_OF_EMBERS_12_NAME', 'Shavraim', 'en_US'),
('LOC_CITY_CLAN_OF_EMBERS_13_NAME', 'Dark Sky', 'en_US'),
('LOC_CITY_CLAN_OF_EMBERS_14_NAME', 'Ator', 'en_US'),
('LOC_CITY_CLAN_OF_EMBERS_15_NAME', 'Baal', 'en_US'),
('LOC_CITY_CLAN_OF_EMBERS_16_NAME', 'Gurrash', 'en_US'),
('LOC_CITY_CLAN_OF_EMBERS_17_NAME', 'Mephisto', 'en_US'),
('LOC_CITY_CLAN_OF_EMBERS_18_NAME', 'Wallara', 'en_US'),
('LOC_CITY_CLAN_OF_EMBERS_19_NAME', 'Deep Dark', 'en_US'),
('LOC_CITY_CLAN_OF_EMBERS_1_NAME', 'Braduk the Burning', 'en_US'),
('LOC_CITY_CLAN_OF_EMBERS_20_NAME', 'Shahav', 'en_US'),
('LOC_CITY_CLAN_OF_EMBERS_21_NAME', 'Ghouls Touch', 'en_US'),
('LOC_CITY_CLAN_OF_EMBERS_22_NAME', 'Cay', 'en_US'),
('LOC_CITY_CLAN_OF_EMBERS_23_NAME', 'Heavens Bane', 'en_US'),
('LOC_CITY_CLAN_OF_EMBERS_24_NAME', 'Tueth', 'en_US'),
('LOC_CITY_CLAN_OF_EMBERS_25_NAME', 'Deaths Head', 'en_US'),
('LOC_CITY_CLAN_OF_EMBERS_26_NAME', 'Dark Heart', 'en_US'),
('LOC_CITY_CLAN_OF_EMBERS_2_NAME', 'Renegade Hill', 'en_US'),
('LOC_CITY_CLAN_OF_EMBERS_3_NAME', 'Shazak', 'en_US'),
('LOC_CITY_CLAN_OF_EMBERS_4_NAME', 'Hezickul', 'en_US'),
('LOC_CITY_CLAN_OF_EMBERS_5_NAME', 'Sorodh', 'en_US'),
('LOC_CITY_CLAN_OF_EMBERS_6_NAME', 'Pain', 'en_US'),
('LOC_CITY_CLAN_OF_EMBERS_7_NAME', 'Ahroog', 'en_US'),
('LOC_CITY_CLAN_OF_EMBERS_8_NAME', 'Belphemon', 'en_US'),
('LOC_CITY_CLAN_OF_EMBERS_9_NAME', 'Death Fort', 'en_US'),
('LOC_CITY_DOVIELLO_10_NAME', 'Hyttaholm', 'en_US'),
('LOC_CITY_DOVIELLO_11_NAME', 'Bjarkavig', 'en_US'),
('LOC_CITY_DOVIELLO_12_NAME', 'Vidarheim', 'en_US'),
('LOC_CITY_DOVIELLO_13_NAME', 'Aesirvig', 'en_US'),
('LOC_CITY_DOVIELLO_14_NAME', 'Volsbaek', 'en_US'),
('LOC_CITY_DOVIELLO_15_NAME', 'Rotundvig', 'en_US'),
('LOC_CITY_DOVIELLO_16_NAME', 'Volpirsvig', 'en_US'),
('LOC_CITY_DOVIELLO_17_NAME', 'Gnistvag', 'en_US'),
('LOC_CITY_DOVIELLO_18_NAME', 'Bjarkoy', 'en_US'),
('LOC_CITY_DOVIELLO_19_NAME', 'Ildelver', 'en_US'),
('LOC_CITY_DOVIELLO_1_NAME', 'Urslo', 'en_US'),
('LOC_CITY_DOVIELLO_20_NAME', 'Urgathastad', 'en_US'),
('LOC_CITY_DOVIELLO_21_NAME', 'Iskvard', 'en_US'),
('LOC_CITY_DOVIELLO_22_NAME', 'Grottiburg', 'en_US'),
('LOC_CITY_DOVIELLO_23_NAME', 'Tongurstad', 'en_US'),
('LOC_CITY_DOVIELLO_24_NAME', 'Graelingvig', 'en_US'),
('LOC_CITY_DOVIELLO_25_NAME', 'Steinvik', 'en_US'),
('LOC_CITY_DOVIELLO_2_NAME', 'Fjirgard', 'en_US'),
('LOC_CITY_DOVIELLO_3_NAME', 'Mortensholm', 'en_US'),
('LOC_CITY_DOVIELLO_4_NAME', 'Heimseter', 'en_US'),
('LOC_CITY_DOVIELLO_5_NAME', 'Suderholm', 'en_US'),
('LOC_CITY_DOVIELLO_6_NAME', 'Olricstaad', 'en_US'),
('LOC_CITY_DOVIELLO_7_NAME', 'Stavgard', 'en_US'),
('LOC_CITY_DOVIELLO_8_NAME', 'Finnsvik', 'en_US'),
('LOC_CITY_DOVIELLO_9_NAME', 'Thorshafn', 'en_US'),
('LOC_CITY_ELOHIM_10_NAME', 'Ring of Sion', 'en_US'),
('LOC_CITY_ELOHIM_11_NAME', 'Glencar Lough', 'en_US'),
('LOC_CITY_ELOHIM_12_NAME', 'Foxford', 'en_US'),
('LOC_CITY_ELOHIM_13_NAME', 'Einions Hold', 'en_US'),
('LOC_CITY_ELOHIM_14_NAME', 'Drogheda Oratory', 'en_US'),
('LOC_CITY_ELOHIM_15_NAME', 'Oriel', 'en_US'),
('LOC_CITY_ELOHIM_16_NAME', 'Rosguill', 'en_US'),
('LOC_CITY_ELOHIM_17_NAME', 'Valentia', 'en_US'),
('LOC_CITY_ELOHIM_18_NAME', 'Achill', 'en_US'),
('LOC_CITY_ELOHIM_19_NAME', 'Inishmaan', 'en_US'),
('LOC_CITY_ELOHIM_1_NAME', 'Cahir Abbey', 'en_US'),
('LOC_CITY_ELOHIM_20_NAME', 'Sapientia', 'en_US'),
('LOC_CITY_ELOHIM_2_NAME', 'Glens of Killybegs', 'en_US'),
('LOC_CITY_ELOHIM_3_NAME', 'Inishbofin', 'en_US'),
('LOC_CITY_ELOHIM_4_NAME', 'Slane', 'en_US'),
('LOC_CITY_ELOHIM_5_NAME', 'Garryvoe', 'en_US'),
('LOC_CITY_ELOHIM_6_NAME', 'Cafes', 'en_US'),
('LOC_CITY_ELOHIM_7_NAME', 'Ballinasloe', 'en_US'),
('LOC_CITY_ELOHIM_8_NAME', 'Warrenpoint', 'en_US'),
('LOC_CITY_ELOHIM_9_NAME', 'Niveus', 'en_US'),
('LOC_CITY_GRIGORI_10_NAME', 'Mideel', 'en_US'),
('LOC_CITY_GRIGORI_11_NAME', 'North Corel', 'en_US'),
('LOC_CITY_GRIGORI_12_NAME', 'Fort Condor', 'en_US'),
('LOC_CITY_GRIGORI_13_NAME', 'Bon Birejji', 'en_US'),
('LOC_CITY_GRIGORI_14_NAME', 'Wasuraruru To', 'en_US'),
('LOC_CITY_GRIGORI_15_NAME', 'Nemuri no Mori', 'en_US'),
('LOC_CITY_GRIGORI_16_NAME', 'Aishikuru Rojji', 'en_US'),
('LOC_CITY_GRIGORI_17_NAME', 'Daihyoga', 'en_US'),
('LOC_CITY_GRIGORI_18_NAME', 'Gaia no Zeppeki', 'en_US'),
('LOC_CITY_GRIGORI_19_NAME', 'Tatsumaki no Meikyu', 'en_US'),
('LOC_CITY_GRIGORI_1_NAME', 'Midgar', 'en_US'),
('LOC_CITY_GRIGORI_20_NAME', 'Kita no Daikudo', 'en_US'),
('LOC_CITY_GRIGORI_21_NAME', 'Saboten Airando', 'en_US'),
('LOC_CITY_GRIGORI_22_NAME', 'Misuriru Main', 'en_US'),
('LOC_CITY_GRIGORI_23_NAME', 'Gorudo Sosa', 'en_US'),
('LOC_CITY_GRIGORI_24_NAME', 'Roketto Mura', 'en_US'),
('LOC_CITY_GRIGORI_25_NAME', 'Materia Dokutsu', 'en_US'),
('LOC_CITY_GRIGORI_26_NAME', 'Midiru', 'en_US'),
('LOC_CITY_GRIGORI_2_NAME', 'Junon', 'en_US'),
('LOC_CITY_GRIGORI_3_NAME', 'Kalm', 'en_US'),
('LOC_CITY_GRIGORI_4_NAME', 'Edge', 'en_US'),
('LOC_CITY_GRIGORI_5_NAME', 'Corel', 'en_US'),
('LOC_CITY_GRIGORI_6_NAME', 'Costa del Sol', 'en_US'),
('LOC_CITY_GRIGORI_7_NAME', 'Gongaga', 'en_US'),
('LOC_CITY_GRIGORI_8_NAME', 'Nibelheim', 'en_US'),
('LOC_CITY_GRIGORI_9_NAME', 'Wutai', 'en_US'),
('LOC_CITY_HIPPUS_10_NAME', 'Kaselorne', 'en_US'),
('LOC_CITY_HIPPUS_11_NAME', 'Ukanevar', 'en_US'),
('LOC_CITY_HIPPUS_12_NAME', 'Glorairmor', 'en_US'),
('LOC_CITY_HIPPUS_13_NAME', 'Drathastine', 'en_US'),
('LOC_CITY_HIPPUS_14_NAME', 'Manar Gandar', 'en_US'),
('LOC_CITY_HIPPUS_15_NAME', 'Enekandril', 'en_US'),
('LOC_CITY_HIPPUS_16_NAME', 'Caranaad', 'en_US'),
('LOC_CITY_HIPPUS_17_NAME', 'Nimharuan', 'en_US'),
('LOC_CITY_HIPPUS_18_NAME', 'Iosichaard', 'en_US'),
('LOC_CITY_HIPPUS_19_NAME', 'Mengostlox', 'en_US'),
('LOC_CITY_HIPPUS_1_NAME', 'Altheriol-ta-Mealthiel', 'en_US'),
('LOC_CITY_HIPPUS_20_NAME', 'Lamistuis', 'en_US'),
('LOC_CITY_HIPPUS_21_NAME', 'Ardien', 'en_US'),
('LOC_CITY_HIPPUS_22_NAME', 'Clar Nasacar', 'en_US'),
('LOC_CITY_HIPPUS_23_NAME', 'Khanec', 'en_US'),
('LOC_CITY_HIPPUS_2_NAME', 'Conrond Mor', 'en_US'),
('LOC_CITY_HIPPUS_3_NAME', 'Radonnor', 'en_US'),
('LOC_CITY_HIPPUS_4_NAME', 'Feiss Mabdon', 'en_US'),
('LOC_CITY_HIPPUS_5_NAME', 'Murousbane', 'en_US'),
('LOC_CITY_HIPPUS_6_NAME', 'Clar Marrachir', 'en_US'),
('LOC_CITY_HIPPUS_7_NAME', 'Urgortheth', 'en_US'),
('LOC_CITY_HIPPUS_8_NAME', 'Gaene', 'en_US'),
('LOC_CITY_HIPPUS_9_NAME', 'Ihara', 'en_US'),
('LOC_CITY_ILLIANS_10_NAME', 'Suspiro', 'en_US'),
('LOC_CITY_ILLIANS_11_NAME', 'Drakon', 'en_US'),
('LOC_CITY_ILLIANS_12_NAME', 'Rorkat', 'en_US'),
('LOC_CITY_ILLIANS_13_NAME', 'Latkor', 'en_US'),
('LOC_CITY_ILLIANS_14_NAME', 'Tarkar', 'en_US'),
('LOC_CITY_ILLIANS_15_NAME', 'Tenura', 'en_US'),
('LOC_CITY_ILLIANS_16_NAME', 'Gelu', 'en_US'),
('LOC_CITY_ILLIANS_17_NAME', 'Roxar', 'en_US'),
('LOC_CITY_ILLIANS_18_NAME', 'Caltakk', 'en_US'),
('LOC_CITY_ILLIANS_19_NAME', 'Retlan', 'en_US'),
('LOC_CITY_ILLIANS_1_NAME', 'Garduk', 'en_US'),
('LOC_CITY_ILLIANS_20_NAME', 'Telkar', 'en_US'),
('LOC_CITY_ILLIANS_2_NAME', 'Lakis', 'en_US'),
('LOC_CITY_ILLIANS_3_NAME', 'Tolero', 'en_US'),
('LOC_CITY_ILLIANS_4_NAME', 'Gostai', 'en_US'),
('LOC_CITY_ILLIANS_5_NAME', 'Sopor', 'en_US'),
('LOC_CITY_ILLIANS_6_NAME', 'Hooplak', 'en_US'),
('LOC_CITY_ILLIANS_7_NAME', 'Sliktor', 'en_US'),
('LOC_CITY_ILLIANS_8_NAME', 'Ashtuk', 'en_US'),
('LOC_CITY_ILLIANS_9_NAME', 'Gigno', 'en_US'),
('LOC_CITY_INFERNAL_10_NAME', 'Astori', 'en_US'),
('LOC_CITY_INFERNAL_11_NAME', 'Utomach', 'en_US'),
('LOC_CITY_INFERNAL_12_NAME', 'Heradh', 'en_US'),
('LOC_CITY_INFERNAL_13_NAME', 'Defalos', 'en_US'),
('LOC_CITY_INFERNAL_14_NAME', 'Charack', 'en_US'),
('LOC_CITY_INFERNAL_15_NAME', 'Phobas', 'en_US'),
('LOC_CITY_INFERNAL_16_NAME', 'Krakatorum', 'en_US'),
('LOC_CITY_INFERNAL_17_NAME', 'Linkbone', 'en_US'),
('LOC_CITY_INFERNAL_18_NAME', 'Draed', 'en_US'),
('LOC_CITY_INFERNAL_19_NAME', 'Astrakan', 'en_US'),
('LOC_CITY_INFERNAL_1_NAME', 'Dis', 'en_US'),
('LOC_CITY_INFERNAL_20_NAME', 'Hic Jacet', 'en_US'),
('LOC_CITY_INFERNAL_21_NAME', 'Locus Desperatus', 'en_US'),
('LOC_CITY_INFERNAL_22_NAME', 'Felo de se', 'en_US'),
('LOC_CITY_INFERNAL_23_NAME', 'Diligere Errorem', 'en_US'),
('LOC_CITY_INFERNAL_24_NAME', 'Interfice Errantem', 'en_US'),
('LOC_CITY_INFERNAL_25_NAME', 'Uxor', 'en_US'),
('LOC_CITY_INFERNAL_26_NAME', 'Peccavi', 'en_US'),
('LOC_CITY_INFERNAL_27_NAME', 'Tacet', 'en_US'),
('LOC_CITY_INFERNAL_28_NAME', 'Abuti', 'en_US'),
('LOC_CITY_INFERNAL_29_NAME', 'Lachryma', 'en_US'),
('LOC_CITY_INFERNAL_2_NAME', 'Despero', 'en_US'),
('LOC_CITY_INFERNAL_30_NAME', 'Dies Irae', 'en_US'),
('LOC_CITY_INFERNAL_3_NAME', 'Poena', 'en_US'),
('LOC_CITY_INFERNAL_4_NAME', 'Bastradam', 'en_US'),
('LOC_CITY_INFERNAL_5_NAME', 'Raglame', 'en_US'),
('LOC_CITY_INFERNAL_6_NAME', 'Kador', 'en_US'),
('LOC_CITY_INFERNAL_7_NAME', 'Longrud', 'en_US'),
('LOC_CITY_INFERNAL_8_NAME', 'Patior', 'en_US'),
('LOC_CITY_INFERNAL_9_NAME', 'Ordstone', 'en_US'),
('LOC_CITY_KHAZAD_10_NAME', 'Boulder Falls', 'en_US'),
('LOC_CITY_KHAZAD_11_NAME', 'Granite Village', 'en_US'),
('LOC_CITY_KHAZAD_12_NAME', 'Nampo', 'en_US'),
('LOC_CITY_KHAZAD_13_NAME', 'Gridmok', 'en_US'),
('LOC_CITY_KHAZAD_14_NAME', 'Eruo', 'en_US'),
('LOC_CITY_KHAZAD_15_NAME', 'Earlwin', 'en_US'),
('LOC_CITY_KHAZAD_16_NAME', 'Hulraden', 'en_US'),
('LOC_CITY_KHAZAD_17_NAME', 'Tiros', 'en_US'),
('LOC_CITY_KHAZAD_18_NAME', 'Roilnboil', 'en_US'),
('LOC_CITY_KHAZAD_19_NAME', 'Sher', 'en_US'),
('LOC_CITY_KHAZAD_1_NAME', 'Khazak', 'en_US'),
('LOC_CITY_KHAZAD_20_NAME', 'Shorisy', 'en_US'),
('LOC_CITY_KHAZAD_21_NAME', 'Lonkris', 'en_US'),
('LOC_CITY_KHAZAD_22_NAME', 'Boradon', 'en_US'),
('LOC_CITY_KHAZAD_23_NAME', 'Arkran', 'en_US'),
('LOC_CITY_KHAZAD_2_NAME', 'Halowell', 'en_US'),
('LOC_CITY_KHAZAD_3_NAME', 'Riylod', 'en_US'),
('LOC_CITY_KHAZAD_4_NAME', 'Kadar', 'en_US'),
('LOC_CITY_KHAZAD_5_NAME', 'Glulynn', 'en_US'),
('LOC_CITY_KHAZAD_6_NAME', 'Stoville', 'en_US'),
('LOC_CITY_KHAZAD_7_NAME', 'Wercer', 'en_US'),
('LOC_CITY_KHAZAD_8_NAME', 'Rockhomme', 'en_US'),
('LOC_CITY_KHAZAD_9_NAME', 'Deep Well', 'en_US'),
('LOC_CITY_KURIOTATES_10_NAME', 'Ghrond', 'en_US'),
('LOC_CITY_KURIOTATES_11_NAME', 'Tiranoc', 'en_US'),
('LOC_CITY_KURIOTATES_12_NAME', 'Pax', 'en_US'),
('LOC_CITY_KURIOTATES_13_NAME', 'Ghaba Ghanaf', 'en_US'),
('LOC_CITY_KURIOTATES_14_NAME', 'Cairn Lotherl', 'en_US'),
('LOC_CITY_KURIOTATES_15_NAME', 'Nagarythe', 'en_US'),
('LOC_CITY_KURIOTATES_16_NAME', 'Maledor', 'en_US'),
('LOC_CITY_KURIOTATES_17_NAME', 'Sith Rionnasc', 'en_US'),
('LOC_CITY_KURIOTATES_18_NAME', 'Khaef Korrond', 'en_US'),
('LOC_CITY_KURIOTATES_19_NAME', 'Anlec', 'en_US'),
('LOC_CITY_KURIOTATES_1_NAME', 'Kwythellar', 'en_US'),
('LOC_CITY_KURIOTATES_20_NAME', 'Calith', 'en_US'),
('LOC_CITY_KURIOTATES_21_NAME', 'Argond', 'en_US'),
('LOC_CITY_KURIOTATES_22_NAME', 'Giaf Gabh Dion', 'en_US'),
('LOC_CITY_KURIOTATES_23_NAME', 'Shathirob', 'en_US'),
('LOC_CITY_KURIOTATES_2_NAME', 'Naggarond', 'en_US'),
('LOC_CITY_KURIOTATES_3_NAME', 'Avelorn', 'en_US'),
('LOC_CITY_KURIOTATES_4_NAME', 'Karond Kar', 'en_US'),
('LOC_CITY_KURIOTATES_5_NAME', 'Caledor', 'en_US'),
('LOC_CITY_KURIOTATES_6_NAME', 'Clar Karond', 'en_US'),
('LOC_CITY_KURIOTATES_7_NAME', 'Lothern', 'en_US'),
('LOC_CITY_KURIOTATES_8_NAME', 'Har Ganeth', 'en_US'),
('LOC_CITY_KURIOTATES_9_NAME', 'Hag Graef', 'en_US'),
('LOC_CITY_LANUN_10_NAME', 'Boscobelle', 'en_US'),
('LOC_CITY_LANUN_11_NAME', 'Speightstown', 'en_US'),
('LOC_CITY_LANUN_12_NAME', 'Willikies', 'en_US'),
('LOC_CITY_LANUN_13_NAME', 'Garrislyr', 'en_US'),
('LOC_CITY_LANUN_14_NAME', 'Villanon', 'en_US'),
('LOC_CITY_LANUN_15_NAME', 'Undertow', 'en_US'),
('LOC_CITY_LANUN_16_NAME', 'Bren Bagage', 'en_US'),
('LOC_CITY_LANUN_1_NAME', 'Innsmouth', 'en_US'),
('LOC_CITY_LANUN_2_NAME', 'Dunwich', 'en_US'),
('LOC_CITY_LANUN_3_NAME', 'Kingsport', 'en_US'),
('LOC_CITY_LANUN_4_NAME', 'Aylesbury', 'en_US'),
('LOC_CITY_LANUN_5_NAME', 'Paradera', 'en_US'),
('LOC_CITY_LANUN_6_NAME', 'Bolans', 'en_US'),
('LOC_CITY_LANUN_7_NAME', 'Seroe Vakas', 'en_US'),
('LOC_CITY_LANUN_8_NAME', 'Bathsheba', 'en_US'),
('LOC_CITY_LANUN_9_NAME', 'Oistins', 'en_US'),
('LOC_CITY_LJOSALFAR_10_NAME', 'Idul', 'en_US'),
('LOC_CITY_LJOSALFAR_11_NAME', 'Elendiwe', 'en_US'),
('LOC_CITY_LJOSALFAR_12_NAME', 'Helion', 'en_US'),
('LOC_CITY_LJOSALFAR_13_NAME', 'Gon Gatha', 'en_US'),
('LOC_CITY_LJOSALFAR_14_NAME', 'Mazenshire', 'en_US'),
('LOC_CITY_LJOSALFAR_15_NAME', 'Tivix', 'en_US'),
('LOC_CITY_LJOSALFAR_16_NAME', 'Lan Neual', 'en_US'),
('LOC_CITY_LJOSALFAR_17_NAME', 'Wispolen', 'en_US'),
('LOC_CITY_LJOSALFAR_18_NAME', 'Cerrolan', 'en_US'),
('LOC_CITY_LJOSALFAR_19_NAME', 'Pauleun', 'en_US'),
('LOC_CITY_LJOSALFAR_1_NAME', 'Evermore', 'en_US'),
('LOC_CITY_LJOSALFAR_20_NAME', 'Organum', 'en_US'),
('LOC_CITY_LJOSALFAR_21_NAME', 'Kalos', 'en_US'),
('LOC_CITY_LJOSALFAR_22_NAME', 'Camena', 'en_US'),
('LOC_CITY_LJOSALFAR_23_NAME', 'Natura', 'en_US'),
('LOC_CITY_LJOSALFAR_2_NAME', 'Hyll', 'en_US'),
('LOC_CITY_LJOSALFAR_3_NAME', 'Bruti', 'en_US'),
('LOC_CITY_LJOSALFAR_4_NAME', 'Yonna', 'en_US'),
('LOC_CITY_LJOSALFAR_5_NAME', 'Dendrom', 'en_US'),
('LOC_CITY_LJOSALFAR_6_NAME', 'Eaca', 'en_US'),
('LOC_CITY_LJOSALFAR_7_NAME', 'Eodd', 'en_US'),
('LOC_CITY_LJOSALFAR_8_NAME', 'Berk', 'en_US'),
('LOC_CITY_LJOSALFAR_9_NAME', 'Khandar', 'en_US'),
('LOC_CITY_LUCHUIRP_10_NAME', 'Silron', 'en_US'),
('LOC_CITY_LUCHUIRP_11_NAME', 'Shanaron', 'en_US'),
('LOC_CITY_LUCHUIRP_12_NAME', 'Vinubar', 'en_US'),
('LOC_CITY_LUCHUIRP_13_NAME', 'Ashimarr', 'en_US'),
('LOC_CITY_LUCHUIRP_14_NAME', 'Atenia', 'en_US'),
('LOC_CITY_LUCHUIRP_15_NAME', 'Leticia', 'en_US'),
('LOC_CITY_LUCHUIRP_16_NAME', 'Suminar', 'en_US'),
('LOC_CITY_LUCHUIRP_17_NAME', 'Manaus', 'en_US'),
('LOC_CITY_LUCHUIRP_18_NAME', 'Ithis', 'en_US'),
('LOC_CITY_LUCHUIRP_19_NAME', 'Paradom', 'en_US'),
('LOC_CITY_LUCHUIRP_1_NAME', 'Ithralia', 'en_US'),
('LOC_CITY_LUCHUIRP_2_NAME', 'Mutanbo', 'en_US'),
('LOC_CITY_LUCHUIRP_3_NAME', 'Tiaran', 'en_US'),
('LOC_CITY_LUCHUIRP_4_NAME', 'Morrtebio', 'en_US'),
('LOC_CITY_LUCHUIRP_5_NAME', 'Valron', 'en_US'),
('LOC_CITY_LUCHUIRP_6_NAME', 'Tianadom', 'en_US'),
('LOC_CITY_LUCHUIRP_7_NAME', 'Nubilar', 'en_US'),
('LOC_CITY_LUCHUIRP_8_NAME', 'Aborlenia', 'en_US'),
('LOC_CITY_LUCHUIRP_9_NAME', 'Tiaminar', 'en_US'),
('LOC_CITY_MALAKIM_10_NAME', 'Udgul', 'en_US'),
('LOC_CITY_MALAKIM_11_NAME', 'Uros', 'en_US'),
('LOC_CITY_MALAKIM_12_NAME', 'Grison', 'en_US'),
('LOC_CITY_MALAKIM_13_NAME', 'Minolow', 'en_US'),
('LOC_CITY_MALAKIM_14_NAME', 'Chish', 'en_US'),
('LOC_CITY_MALAKIM_15_NAME', 'Adihaniel', 'en_US'),
('LOC_CITY_MALAKIM_16_NAME', 'Shotaka', 'en_US'),
('LOC_CITY_MALAKIM_1_NAME', 'Golden Leane', 'en_US'),
('LOC_CITY_MALAKIM_2_NAME', 'Timberling', 'en_US'),
('LOC_CITY_MALAKIM_3_NAME', 'Balderham', 'en_US'),
('LOC_CITY_MALAKIM_4_NAME', 'Lodente', 'en_US'),
('LOC_CITY_MALAKIM_5_NAME', 'Froihk', 'en_US'),
('LOC_CITY_MALAKIM_6_NAME', 'Bryn', 'en_US'),
('LOC_CITY_MALAKIM_7_NAME', 'Belerien', 'en_US'),
('LOC_CITY_MALAKIM_8_NAME', 'Tiriyn', 'en_US'),
('LOC_CITY_MALAKIM_9_NAME', 'Stormgul', 'en_US'),
('LOC_CITY_MERCURIANS_10_NAME', 'Newell Green', 'en_US'),
('LOC_CITY_MERCURIANS_11_NAME', 'Kennet Carn', 'en_US'),
('LOC_CITY_MERCURIANS_12_NAME', 'Swidon', 'en_US'),
('LOC_CITY_MERCURIANS_13_NAME', 'Aldworth', 'en_US'),
('LOC_CITY_MERCURIANS_14_NAME', 'Ains Field', 'en_US'),
('LOC_CITY_MERCURIANS_15_NAME', 'Llangar', 'en_US'),
('LOC_CITY_MERCURIANS_16_NAME', 'Lammas Mead', 'en_US'),
('LOC_CITY_MERCURIANS_17_NAME', 'Bulpit', 'en_US'),
('LOC_CITY_MERCURIANS_1_NAME', 'Bourne the Gleaming', 'en_US'),
('LOC_CITY_MERCURIANS_2_NAME', 'Gap of Lond', 'en_US'),
('LOC_CITY_MERCURIANS_3_NAME', 'Spera', 'en_US'),
('LOC_CITY_MERCURIANS_4_NAME', 'High Clere', 'en_US'),
('LOC_CITY_MERCURIANS_5_NAME', 'Ranelagh Cres', 'en_US'),
('LOC_CITY_MERCURIANS_6_NAME', 'Vigilo', 'en_US'),
('LOC_CITY_MERCURIANS_7_NAME', 'Locks', 'en_US'),
('LOC_CITY_MERCURIANS_8_NAME', 'Priory Hold', 'en_US'),
('LOC_CITY_MERCURIANS_9_NAME', 'Warrage', 'en_US'),
('LOC_CITY_SHEAIM_10_NAME', 'Bjoernlingburg', 'en_US'),
('LOC_CITY_SHEAIM_11_NAME', 'Morkurburg', 'en_US'),
('LOC_CITY_SHEAIM_12_NAME', 'Jordekburg', 'en_US'),
('LOC_CITY_SHEAIM_13_NAME', 'Stromstad', 'en_US'),
('LOC_CITY_SHEAIM_14_NAME', 'Frost', 'en_US'),
('LOC_CITY_SHEAIM_15_NAME', 'Lade', 'en_US'),
('LOC_CITY_SHEAIM_16_NAME', 'Skeggi', 'en_US'),
('LOC_CITY_SHEAIM_17_NAME', 'Kvellig', 'en_US'),
('LOC_CITY_SHEAIM_18_NAME', 'Aghol', 'en_US'),
('LOC_CITY_SHEAIM_19_NAME', 'Raunvake', 'en_US'),
('LOC_CITY_SHEAIM_1_NAME', 'Galveholm', 'en_US'),
('LOC_CITY_SHEAIM_20_NAME', 'Sjoktraken', 'en_US'),
('LOC_CITY_SHEAIM_2_NAME', 'Grottiburg', 'en_US'),
('LOC_CITY_SHEAIM_3_NAME', 'Tongurstad', 'en_US'),
('LOC_CITY_SHEAIM_4_NAME', 'Graelingvig', 'en_US'),
('LOC_CITY_SHEAIM_5_NAME', 'Steinvik', 'en_US'),
('LOC_CITY_SHEAIM_6_NAME', 'Kuldevind', 'en_US'),
('LOC_CITY_SHEAIM_7_NAME', 'Vargstad', 'en_US'),
('LOC_CITY_SHEAIM_8_NAME', 'Skadistad', 'en_US'),
('LOC_CITY_SHEAIM_9_NAME', 'Nidhoggstad', 'en_US'),
('LOC_CITY_SIDAR_10_NAME', 'Kartlost', 'en_US'),
('LOC_CITY_SIDAR_11_NAME', 'Provectus', 'en_US'),
('LOC_CITY_SIDAR_12_NAME', 'Priscus', 'en_US'),
('LOC_CITY_SIDAR_13_NAME', 'Bogz', 'en_US'),
('LOC_CITY_SIDAR_14_NAME', 'Verminaard', 'en_US'),
('LOC_CITY_SIDAR_15_NAME', 'Sark', 'en_US'),
('LOC_CITY_SIDAR_16_NAME', 'Rrackon', 'en_US'),
('LOC_CITY_SIDAR_17_NAME', 'Asrassiv', 'en_US'),
('LOC_CITY_SIDAR_18_NAME', 'Varza', 'en_US'),
('LOC_CITY_SIDAR_19_NAME', 'Zratos', 'en_US'),
('LOC_CITY_SIDAR_1_NAME', 'Celo', 'en_US'),
('LOC_CITY_SIDAR_20_NAME', 'Drakor', 'en_US'),
('LOC_CITY_SIDAR_2_NAME', 'Vetus', 'en_US'),
('LOC_CITY_SIDAR_3_NAME', 'Zarlra', 'en_US'),
('LOC_CITY_SIDAR_4_NAME', 'Skarlas', 'en_US'),
('LOC_CITY_SIDAR_5_NAME', 'Latito', 'en_US'),
('LOC_CITY_SIDAR_6_NAME', 'Stakrus', 'en_US'),
('LOC_CITY_SIDAR_7_NAME', 'Velius', 'en_US'),
('LOC_CITY_SIDAR_8_NAME', 'Shadow Mist', 'en_US'),
('LOC_CITY_SIDAR_9_NAME', 'Senectus', 'en_US'),
('LOC_CITY_SVARTALFAR_10_NAME', 'Geffron', 'en_US'),
('LOC_CITY_SVARTALFAR_11_NAME', 'Malor', 'en_US'),
('LOC_CITY_SVARTALFAR_12_NAME', 'Avien', 'en_US'),
('LOC_CITY_SVARTALFAR_13_NAME', 'Essuria', 'en_US'),
('LOC_CITY_SVARTALFAR_14_NAME', 'Lothenar', 'en_US'),
('LOC_CITY_SVARTALFAR_15_NAME', 'Crepusculum', 'en_US'),
('LOC_CITY_SVARTALFAR_16_NAME', 'Black Axe', 'en_US'),
('LOC_CITY_SVARTALFAR_17_NAME', 'Wolf Claw', 'en_US'),
('LOC_CITY_SVARTALFAR_18_NAME', 'Evil Eye', 'en_US'),
('LOC_CITY_SVARTALFAR_19_NAME', 'Beast Clan', 'en_US'),
('LOC_CITY_SVARTALFAR_1_NAME', 'Thariss', 'en_US'),
('LOC_CITY_SVARTALFAR_20_NAME', 'Goathorns', 'en_US'),
('LOC_CITY_SVARTALFAR_21_NAME', 'Tarka', 'en_US'),
('LOC_CITY_SVARTALFAR_22_NAME', 'Helshaven', 'en_US'),
('LOC_CITY_SVARTALFAR_23_NAME', 'Terror', 'en_US'),
('LOC_CITY_SVARTALFAR_24_NAME', 'Herath', 'en_US'),
('LOC_CITY_SVARTALFAR_25_NAME', 'Sickly Mist', 'en_US'),
('LOC_CITY_SVARTALFAR_2_NAME', 'Gereth Minar', 'en_US'),
('LOC_CITY_SVARTALFAR_3_NAME', 'Nameless Tower', 'en_US'),
('LOC_CITY_SVARTALFAR_4_NAME', 'Idris', 'en_US'),
('LOC_CITY_SVARTALFAR_5_NAME', 'Brakkah', 'en_US'),
('LOC_CITY_SVARTALFAR_6_NAME', 'Enoreth', 'en_US'),
('LOC_CITY_SVARTALFAR_7_NAME', 'Geron', 'en_US'),
('LOC_CITY_SVARTALFAR_8_NAME', 'Aeleriss Pits', 'en_US'),
('LOC_CITY_SVARTALFAR_9_NAME', 'Drax Tallen', 'en_US'),
('LOC_SLTH_GREAT_ADVENTURER_1', 'Branding', 'en_US'),
('LOC_SLTH_GREAT_ADVENTURER_10', 'Hamlyn Ka', 'en_US'),
('LOC_SLTH_GREAT_ADVENTURER_11', 'Kimble der Flinke', 'en_US'),
('LOC_SLTH_GREAT_ADVENTURER_12', 'Melusine', 'en_US'),
('LOC_SLTH_GREAT_ADVENTURER_13', 'Bakabushi', 'en_US'),
('LOC_SLTH_GREAT_ADVENTURER_14', 'Sidhelle', 'en_US'),
('LOC_SLTH_GREAT_ADVENTURER_15', 'Carrow der Gejagte', 'en_US'),
('LOC_SLTH_GREAT_ADVENTURER_16', 'Khord Tenhare', 'en_US'),
('LOC_SLTH_GREAT_ADVENTURER_17', 'Pinchete', 'en_US'),
('LOC_SLTH_GREAT_ADVENTURER_18', 'Needles', 'en_US'),
('LOC_SLTH_GREAT_ADVENTURER_19', 'Bahamet der Zweite', 'en_US'),
('LOC_SLTH_GREAT_ADVENTURER_2', 'Cabal Tenhare', 'en_US'),
('LOC_SLTH_GREAT_ADVENTURER_20', 'Groo der Wanderer', 'en_US'),
('LOC_SLTH_GREAT_ADVENTURER_3', 'Panlupan', 'en_US'),
('LOC_SLTH_GREAT_ADVENTURER_4', 'Volanna', 'en_US'),
('LOC_SLTH_GREAT_ADVENTURER_5', 'Pater Jeon', 'en_US'),
('LOC_SLTH_GREAT_ADVENTURER_6', 'Llangru', 'en_US'),
('LOC_SLTH_GREAT_ADVENTURER_7', 'Nosamonce', 'en_US'),
('LOC_SLTH_GREAT_ADVENTURER_8', 'Bhalira', 'en_US'),
('LOC_SLTH_GREAT_ADVENTURER_9', 'Comillo', 'en_US'),
('LOC_SLTH_GREAT_ARTIST_1', 'Dain von Cythera', 'en_US'),
('LOC_SLTH_GREAT_ARTIST_10', 'Dhaunae der Illusionist', 'en_US'),
('LOC_SLTH_GREAT_ARTIST_11', 'Ofeofae', 'en_US'),
('LOC_SLTH_GREAT_ARTIST_12', 'KÃƒÆ’Ã‚Â¶nig der EichhÃƒÆ’Ã‚Â¶rnchen', 'en_US'),
('LOC_SLTH_GREAT_ARTIST_13', 'Airodaunt Balon', 'en_US'),
('LOC_SLTH_GREAT_ARTIST_14', 'Caspian Loch', 'en_US'),
('LOC_SLTH_GREAT_ARTIST_15', 'Taneath', 'en_US'),
('LOC_SLTH_GREAT_ARTIST_16', 'Pramas Olds', 'en_US'),
('LOC_SLTH_GREAT_ARTIST_17', 'Hodkamset', 'en_US'),
('LOC_SLTH_GREAT_ARTIST_18', 'Samawen der Geist', 'en_US'),
('LOC_SLTH_GREAT_ARTIST_19', 'Pelia die TÃƒÆ’Ã‚Â¤nzerin', 'en_US'),
('LOC_SLTH_GREAT_ARTIST_2', 'Argase der ZauberkÃƒÆ’Ã‚Â¼nstler', 'en_US'),
('LOC_SLTH_GREAT_ARTIST_20', 'Vernadot', 'en_US'),
('LOC_SLTH_GREAT_ARTIST_3', 'Furia', 'en_US'),
('LOC_SLTH_GREAT_ARTIST_4', 'Clairone', 'en_US'),
('LOC_SLTH_GREAT_ARTIST_5', 'Persellus', 'en_US'),
('LOC_SLTH_GREAT_ARTIST_6', 'Melisandre', 'en_US'),
('LOC_SLTH_GREAT_ARTIST_7', 'Cladius die Stimme der Verdammten', 'en_US'),
('LOC_SLTH_GREAT_ARTIST_8', 'Kamen Shandoun', 'en_US'),
('LOC_SLTH_GREAT_ARTIST_9', 'Dianchete', 'en_US'),
('LOC_SLTH_GREAT_ENGINEER_1', 'Khmer Otterfig', 'en_US'),
('LOC_SLTH_GREAT_ENGINEER_10', 'Thorion Vo', 'en_US'),
('LOC_SLTH_GREAT_ENGINEER_11', 'Faber Ozzie', 'en_US'),
('LOC_SLTH_GREAT_ENGINEER_12', 'Aegeus Isildur', 'en_US'),
('LOC_SLTH_GREAT_ENGINEER_13', 'Hoyden Drew', 'en_US'),
('LOC_SLTH_GREAT_ENGINEER_14', 'Milana', 'en_US'),
('LOC_SLTH_GREAT_ENGINEER_15', 'Zoot Ghent Gear', 'en_US'),
('LOC_SLTH_GREAT_ENGINEER_16', 'Ethel Agames', 'en_US'),
('LOC_SLTH_GREAT_ENGINEER_17', 'Fodgel Thor', 'en_US'),
('LOC_SLTH_GREAT_ENGINEER_18', 'Bareke', 'en_US'),
('LOC_SLTH_GREAT_ENGINEER_19', 'Zehanpuryuh', 'en_US'),
('LOC_SLTH_GREAT_ENGINEER_2', 'Vesta die Glorreiche', 'en_US'),
('LOC_SLTH_GREAT_ENGINEER_20', 'Valoel', 'en_US'),
('LOC_SLTH_GREAT_ENGINEER_3', 'Tilonas Sal', 'en_US'),
('LOC_SLTH_GREAT_ENGINEER_4', 'Hulik Darkanus', 'en_US'),
('LOC_SLTH_GREAT_ENGINEER_5', 'Athos Ulthane', 'en_US'),
('LOC_SLTH_GREAT_ENGINEER_6', 'Gregamir', 'en_US'),
('LOC_SLTH_GREAT_ENGINEER_7', 'Haldayne Ozark', 'en_US'),
('LOC_SLTH_GREAT_ENGINEER_8', 'Schrewneil', 'en_US'),
('LOC_SLTH_GREAT_ENGINEER_9', 'Pistis Sophia', 'en_US'),
('LOC_SLTH_GREAT_MERCHANT_1', 'Jenkin', 'en_US'),
('LOC_SLTH_GREAT_MERCHANT_10', 'Enos der SchlÃƒÆ’Ã‚Â¤ger', 'en_US'),
('LOC_SLTH_GREAT_MERCHANT_11', 'Sopheriel Mehayye', 'en_US'),
('LOC_SLTH_GREAT_MERCHANT_12', 'Rusa Pariek', 'en_US'),
('LOC_SLTH_GREAT_MERCHANT_13', 'Sopheriel Memeth', 'en_US'),
('LOC_SLTH_GREAT_MERCHANT_14', 'Omar von Turin', 'en_US'),
('LOC_SLTH_GREAT_MERCHANT_15', 'Abdulkani der Schwindler', 'en_US'),
('LOC_SLTH_GREAT_MERCHANT_16', 'Belarchass der SklavenhÃƒÆ’Ã‚Â¤ndler', 'en_US'),
('LOC_SLTH_GREAT_MERCHANT_17', 'Mavreen Mawklistyr', 'en_US'),
('LOC_SLTH_GREAT_MERCHANT_18', 'Maaerun', 'en_US'),
('LOC_SLTH_GREAT_MERCHANT_19', 'Joffa von Barakite', 'en_US'),
('LOC_SLTH_GREAT_MERCHANT_2', 'Florina von Lorinwood', 'en_US'),
('LOC_SLTH_GREAT_MERCHANT_20', 'Goodreau', 'en_US'),
('LOC_SLTH_GREAT_MERCHANT_3', 'Agravaine', 'en_US'),
('LOC_SLTH_GREAT_MERCHANT_4', 'Kersasus Actium', 'en_US'),
('LOC_SLTH_GREAT_MERCHANT_5', 'Geogi Bandon', 'en_US'),
('LOC_SLTH_GREAT_MERCHANT_6', 'Oparr der Gauner', 'en_US'),
('LOC_SLTH_GREAT_MERCHANT_7', 'Nephrion Cathwar', 'en_US'),
('LOC_SLTH_GREAT_MERCHANT_8', 'Vohu Manah', 'en_US'),
('LOC_SLTH_GREAT_MERCHANT_9', 'Gonael', 'en_US'),
('LOC_SLTH_GREAT_PROPHET_1', 'Tuatha DÃƒÆ’Ã‚Â© Danann', 'en_US'),
('LOC_SLTH_GREAT_PROPHET_10', 'Fand', 'en_US'),
('LOC_SLTH_GREAT_PROPHET_11', 'Gosea', 'en_US'),
('LOC_SLTH_GREAT_PROPHET_12', 'Aes Sidhe', 'en_US'),
('LOC_SLTH_GREAT_PROPHET_13', 'Vaghan von Lugus', 'en_US'),
('LOC_SLTH_GREAT_PROPHET_14', 'Teutates', 'en_US'),
('LOC_SLTH_GREAT_PROPHET_15', 'Belatu Cadros', 'en_US'),
('LOC_SLTH_GREAT_PROPHET_16', 'Cenn Cruaich', 'en_US'),
('LOC_SLTH_GREAT_PROPHET_17', 'Mag Tuireadh', 'en_US'),
('LOC_SLTH_GREAT_PROPHET_18', 'Nyarlat', 'en_US'),
('LOC_SLTH_GREAT_PROPHET_19', 'Aengus Saone', 'en_US'),
('LOC_SLTH_GREAT_PROPHET_2', 'Calwinna von Junil', 'en_US'),
('LOC_SLTH_GREAT_PROPHET_20', 'Cailleach Beara', 'en_US'),
('LOC_SLTH_GREAT_PROPHET_3', 'Talia Gosam', 'en_US'),
('LOC_SLTH_GREAT_PROPHET_4', 'Lita die Hexe', 'en_US'),
('LOC_SLTH_GREAT_PROPHET_5', 'Abellio', 'en_US'),
('LOC_SLTH_GREAT_PROPHET_6', 'Abnoba', 'en_US'),
('LOC_SLTH_GREAT_PROPHET_7', 'Spross des Himmels', 'en_US'),
('LOC_SLTH_GREAT_PROPHET_8', 'Lanthis', 'en_US'),
('LOC_SLTH_GREAT_PROPHET_9', 'Pontif Elmin', 'en_US'),
('LOC_SLTH_GREAT_SCIENTIST_1', 'Mikel Dylantyr', 'en_US'),
('LOC_SLTH_GREAT_SCIENTIST_10', 'Thessalonica', 'en_US'),
('LOC_SLTH_GREAT_SCIENTIST_11', 'Damabiah', 'en_US'),
('LOC_SLTH_GREAT_SCIENTIST_12', 'Denelcor Hep', 'en_US'),
('LOC_SLTH_GREAT_SCIENTIST_13', 'Magister Cultuum', 'en_US'),
('LOC_SLTH_GREAT_SCIENTIST_14', 'Abruel Azburgah', 'en_US'),
('LOC_SLTH_GREAT_SCIENTIST_15', 'Tephus der NebelgÃƒÆ’Ã‚Â¤nger', 'en_US'),
('LOC_SLTH_GREAT_SCIENTIST_16', 'Bradeline', 'en_US'),
('LOC_SLTH_GREAT_SCIENTIST_17', 'Malchavic', 'en_US'),
('LOC_SLTH_GREAT_SCIENTIST_18', 'Cu Roi', 'en_US'),
('LOC_SLTH_GREAT_SCIENTIST_19', 'Menolly NuValle', 'en_US'),
('LOC_SLTH_GREAT_SCIENTIST_2', 'Ozziel', 'en_US'),
('LOC_SLTH_GREAT_SCIENTIST_20', 'Luciaqua', 'en_US'),
('LOC_SLTH_GREAT_SCIENTIST_3', 'Abdulkani', 'en_US'),
('LOC_SLTH_GREAT_SCIENTIST_4', 'Narsiss', 'en_US'),
('LOC_SLTH_GREAT_SCIENTIST_5', 'Delent Payne', 'en_US'),
('LOC_SLTH_GREAT_SCIENTIST_6', 'Asher der Denker', 'en_US'),
('LOC_SLTH_GREAT_SCIENTIST_7', 'Othmar der Himmelskundige', 'en_US'),
('LOC_SLTH_GREAT_SCIENTIST_8', 'Shoftiel', 'en_US'),
('LOC_SLTH_GREAT_SCIENTIST_9', 'Willim Marlander', 'en_US');