INSERT OR REPLACE INTO LocalizedText(Tag, Text, Language) VALUES
('LOC_ABILITY_HERO_NAME', 'Hero', 'en_US'),
('LOC_SLTH_DEMON_ABILITY_HELL_TERRAIN_STRENGTH_NAME', 'Hell Terrain Strength', 'en_US'),
('LOC_SLTH_ELF_ABILITY_FEATUREATTACKS_NAME', 'Elven Forest Strength', 'en_US'),
('LOC_SLTH_ELF_ABILITY_FEATUREDOUBLEMOVES_NAME', 'Elf Forest Mobility', 'en_US'),
('LOC_SLTH_FROSTLING_ABILITY_TERRAIN_STRENGTH_NAME', 'Frostling Tundra/Snow Attack', 'en_US'),
('LOC_SLTH_LIZARDMAN_ABILITY_MARSH_DOUBLE_MOVES_NAME', 'Lizardman Marsh Mobility', 'en_US'),
('LOC_SLTH_LIZARDMAN_ABILITY_MARSH_STRENGTH_NAME', 'Lizardman Marsh Strength', 'en_US'),
('LOC_SLTH_NIGHTMARE_ABILITY_HELL_TERRAIN_STRENGTH_NAME', 'Nightmare Hellish Strength', 'en_US'),
('LOC_SLTH_NOMAD_ABILITY_DESERT_STRENGTH_NAME', 'Nomad Desert Power', 'en_US'),
('LOC_SLTH_ORC_ABILITY_JUNGLE_ATTACKS_NAME', 'Orc Jungle Attack', 'en_US'),
('LOC_SLTH_PROMOTION_DWARF_ABILITY_HILLS_DOUBLE_MOVE_NAME', 'Hill Double Movement', 'en_US'),
('LOC_SLTH_PROMOTION_GUERILLA2_ABILITY_HILLS_DOUBLE_MOVE_NAME', 'Hill Strength', 'en_US'),
('LOC_SLTH_PROMOTION_NOMAD_ABILITY_TERRAINDOUBLEMOVES_NAME', 'Nomad', 'en_US'),
('LOC_SLTH_WINTERBORN_ABILITY_TUNDRA_SNOW_STRENGTH_NAME', 'Winterborn Tundra Strength', 'en_US'),
('LOC_SLTH_WOODSMAN1_ABILITY_FEATUREATTACKS_NAME', 'Woods Strength', 'en_US'),
('LOC_SLTH_WOODSMAN2_ABILITY_FEATUREATTACKS_NAME', 'Woods Strength II', 'en_US'),
('LOC_ABILITY_HERO_DESCRIPTION', 'One of a kind Unit. Gains 1 experience per turn.', 'en_US'),
('LOC_ABILITY_HERO_NO_EXP_DESCRIPTION', 'One of a kind Unit.', 'en_US'),
('LOC_DEMON_ABILITY_HELL_TERRAIN_STRENGTH_DESCRIPTION', '10 % stronger in combat on Hell terrain: Burning Sands, Fields of Perdition, Broken Fields.', 'en_US'),
('LOC_ELF_ABILITY_FEATUREATTACKS_DESCRIPTION', '+{1_Amount}[ICON_STRENGTH] Combat Strength while on Woods and Ancient Forest.', 'en_US'),
('LOC_ELF_ABILITY_FEATUREDOUBLEMOVES_DESCRIPTION', '+1[ICON_Movement] Movement while on Forest and Ancient Forest.', 'en_US'),
('LOC_FROSTLING_ABILITY_TERRAIN_STRENGTH_DESCRIPTION', '+25[ICON_Strength] Combat Strength while on Snow.[NEWLINE]+{1_Amount}[ICON_STRENGTH] Combat Strength while on Tundra.[NEWLINE]-25[ICON_Strength] Combat Strength while on Desert.[NEWLINE]', 'en_US'),
('LOC_LIZARDMAN_ABILITY_MARSH_STRENGTH_DESCRIPTION', '+{1_Amount}[ICON_STRENGTH] Combat Strength while on Marsh. +1[ICON_Movement] Movement while on Marsh.', 'en_US'),
('LOC_NIGHTMARE_ABILITY_HELL_TERRAIN_STRENGTH_DESCRIPTION', '+{1_Amount}[ICON_STRENGTH] Combat Strength while on Broken lands, Fields of perdition and Burning sands.', 'en_US'),
('LOC_NIGHTMARE_ABILITY_TERRAINDEFENSES_DESCRIPTION', '+{1_Amount}[ICON_STRENGTH] Combat Strength while on Broken lands, Fields of perdition and Burning sands.', 'en_US'),
('LOC_NOMAD_ABILITY_DESERT_STRENGTH_DESCRIPTION', '+{1_Amount}[ICON_STRENGTH] Combat Strength and +1[ICON_Movement] Movement when Desert.', 'en_US'),
('LOC_NOMAD_ABILITY_TERRAINDEFENSES_DESCRIPTION', '+{1_Amount}[ICON_STRENGTH] Combat Strength while on Desert.', 'en_US'),
('LOC_ORC_ABILITY_JUNGLE_ATTACKS_DESCRIPTION', '+{1_Amount}[ICON_STRENGTH] Combat Strength while on jungle.', 'en_US'),
('LOC_PROMOTION_DARK_ELF_ABILITY_FEATUREDOUBLEMOVES_DESCRIPTION', '+1[ICON_Movement] Movement while on Ancient_forest.', 'en_US'),
('LOC_PROMOTION_DWARF_ABILITY_HILLS_DOUBLE_MOVE_DESCRIPTION', '+1[ICON_Movement] Movement while on Hills.', 'en_US'),
('LOC_PROMOTION_GUERILLA2_ABILITY_HILLS_DOUBLE_MOVE_DESCRIPTION', '+1[ICON_Movement] Movement while on Hills.', 'en_US'),
('LOC_PROMOTION_NOMAD_ABILITY_TERRAINDOUBLEMOVES_DESCRIPTION', '+1[ICON_Movement] Movement while on Desert.', 'en_US'),
('LOC_PROMOTION_WOODSMAN2_ABILITY_FEATUREDOUBLEMOVES_DESCRIPTION', '+1[ICON_Movement] Movement while on Ancient_forest.', 'en_US'),
('LOC_WINTERBORN_ABILITY_TERRAINDEFENSES_DESCRIPTION', '+{1_Amount}[ICON_STRENGTH] Combat Strength while on Snow and Tundra.', 'en_US'),
('LOC_WINTERBORN_ABILITY_TUNDRA_SNOW_STRENGTH_DESCRIPTION', '+{1_Amount}[ICON_STRENGTH] Combat Strength while on Snow and Tundra.', 'en_US'),
('LOC_WOODSMAN1_ABILITY_FEATUREATTACKS_DESCRIPTION', '+{1_Amount}[ICON_STRENGTH] Combat Strength while on jungle, Woods and Ancient Forest.', 'en_US'),
('LOC_WOODSMAN2_ABILITY_FEATUREATTACKS_DESCRIPTION', '+{1_Amount}[ICON_STRENGTH] Combat Strength while on jungle, Woods and Ancient Forest.', 'en_US'),
('LOC_AFFINITY_4_DESCRIPTION', '+{1_Amount}[ICON_STRENGTH] Combat Strength From Resource Affinity', 'en_US'),
('LOC_AFFINITY_8_DESCRIPTION', '+{1_Amount}[ICON_STRENGTH] Combat Strength From Resource Affinity', 'en_US'),
('LOC_AFFINITY_16_DESCRIPTION', '+{1_Amount}[ICON_STRENGTH] Combat Strength From Resource Affinity', 'en_US'),
('LOC_AFFINITY_32_DESCRIPTION', '+{1_Amount}[ICON_STRENGTH] Combat Strength From Resource Affinity', 'en_US'),
('LOC_AFFINITY_64_DESCRIPTION', '+{1_Amount}[ICON_STRENGTH] Combat Strength From Resource Affinity', 'en_US'),
('LOC_SLTH_ABILITY_ALIGNMENT_GOOD_NAME', 'Good Alignment', 'en_US'),
('LOC_SLTH_ABILITY_ALIGNMENT_EVIL_NAME', 'Evil Alignment', 'en_US'),
('LOC_ABILITY_ALIGNMENT_GOOD_DESCRIPTION', 'Good Alignment', 'en_US'),
('LOC_ABILITY_ALIGNMENT_EVIL_DESCRIPTION', 'Evil Alignment', 'en_US');
