INSERT OR REPLACE INTO LocalizedText(Tag, Text, Language) VALUES
('LOC_SLTH_TERRAIN_BROKEN_LANDS_NAME', 'Broken Lands', 'en_US'),
('LOC_SLTH_TERRAIN_BROKEN_LANDS_NAME_HILLS', 'Broken Lands Hills', 'en_US'),
('LOC_SLTH_TERRAIN_BROKEN_LANDS_NAME_MOUNTAIN', 'Broken Lands Mountain', 'en_US'),
('LOC_SLTH_TERRAIN_BURNING_SANDS_NAME', 'Burning Sands', 'en_US'),
('LOC_SLTH_TERRAIN_BURNING_SANDS_NAME_HILLS', 'Burning Sands Hills', 'en_US'),
('LOC_SLTH_TERRAIN_BURNING_SANDS_NAME_MOUNTAIN', 'Burning Sands Mountain', 'en_US'),
('LOC_SLTH_TERRAIN_FIELDS_OF_PERDITION_NAME', 'Fields Of Perdition', 'en_US'),
('LOC_SLTH_TERRAIN_FIELDS_OF_PERDITION_NAME_HILLS', 'Fields Of Perdition Hills', 'en_US'),
('LOC_SLTH_TERRAIN_FIELDS_OF_PERDITION_NAME_MOUNTAIN', 'Fields Of Perdition Mountain', 'en_US'),
('LOC_SLTH_FEATURE_FOREST_ANCIENT_NAME', 'Forest Ancient', 'en_US'),
('LOC_SLTH_FEATURE_OBSIDIAN_PLAINS_NAME', 'Obsidian Plains', 'en_US'),
('LOC_SLTH_FEATURE_SHALLOWS_NAME', 'Shallows', 'en_US'),

('LOC_FEATURE_MAELSTROM_NAME', 'Maelstrom', 'en_US'),
('LOC_FEATURE_POOL_OF_TEARS_NAME', 'Pool of Tears', 'en_US'),
('LOC_FEATURE_MIRROR_OF_HEAVEN_NAME', 'Mirror of Heaven', 'en_US'),
('LOC_FEATURE_PRISTIN_NAME', 'Pristin Pass', 'en_US'),
('LOC_FEATURE_STANDING_STONES_NAME', 'Standing Stones', 'en_US'),
('LOC_FEATURE_TOMB_NAME', 'Tomb of Sucellus', 'en_US'),
('LOC_FEATURE_YGGDRASIL_NAME', 'Yggdrasil', 'en_US'),
('LOC_FEATURE_PATRIA_NAME', 'Remnants of Patria', 'en_US'),
('LOC_FEATURE_FRIGUS_NAME', 'Letum Frigus', 'en_US'),
('LOC_FEATURE_BONES_NAME', 'Dragon Bones', 'en_US'),
('LOC_FEATURE_WELL_NAME', 'Bradeline''s Well', 'en_US'),
('LOC_FEATURE_SEPULCHER_NAME', 'Broken Sepulcher', 'en_US'),
('LOC_FEATURE_PYRE_NAME', 'Pyre of the Seraphic', 'en_US'),
('LOC_FEATURE_MAENALUS_NAME', 'Maenalus', 'en_US'),
('LOC_FEATURE_ODIO_NAME', 'Odio''s Prison', 'en_US'),
('LOC_FEATURE_PINES_NAME', 'Seven Pines', 'en_US'),
('LOC_FEATURE_CARCER_NAME', 'Ring of Carcer', 'en_US'),
('LOC_FEATURE_MAELSTROM_DESCRIPTION', 'The Maelstrom transports a unit to a random Ocean tile.', 'en_US'),
('LOC_FEATURE_POOL_OF_TEARS_DESCRIPTION', 'Provides increased healing and housing, as well as Spirit Mana.', 'en_US'),
('LOC_FEATURE_MIRROR_OF_HEAVEN_DESCRIPTION', 'Provides increased vision, reveals invisible units and provides Sun Mana.', 'en_US'),
('LOC_FEATURE_PRISTIN_DESCRIPTION', 'Pristin Pass is unblemished by civilization for good reason. The first unit adjacent to it spawns two Barbarian Gargoyles.', 'en_US'),
('LOC_FEATURE_STANDING_STONES_DESCRIPTION', 'Provide some amenities and Earth Mana.', 'en_US'),
('LOC_FEATURE_TOMB_DESCRIPTION', 'The resting place of the god of Life. Provides Life Mana.', 'en_US'),
('LOC_FEATURE_YGGDRASIL_DESCRIPTION', 'The World Tree, Yggdrasil provides its fruit, granting Housing and Amenities to all cities of its owner.', 'en_US'),
('LOC_FEATURE_PATRIA_DESCRIPTION', 'The remains of the glorious age of Magic, provides a source of MetaMagic Mana.', 'en_US'),
('LOC_FEATURE_FRIGUS_DESCRIPTION', 'Former Throne of Mulcarn, the God of Winter. Sacred to the Illians who worship him, and the Amurites, who remember Kylorin''s sacrifice to rid the world of Winter. Treasures may still await brave adventurers, but surely there are old terrible things remaining in the ruins.', 'en_US'),
('LOC_FEATURE_BONES_DESCRIPTION', 'Bones of a Dragon, war machines of the gods.', 'en_US'),
('LOC_FEATURE_WELL_DESCRIPTION', 'Site of Bradeline''s ritual to interface with the dead. Treasures may still await brave adventurers, but surely there are old terrible things remaining in the ruins.', 'en_US'),
('LOC_FEATURE_SEPULCHER_DESCRIPTION', 'Barbatos the first Lich was interred here at the end of the age of Magic. Yet the stone is cracked, and nothing remains but Death Mana. Treasures may still await brave adventurers, but surely there are old terrible things remaining in the ruins.', 'en_US'),
('LOC_FEATURE_PYRE_DESCRIPTION', 'Ritual site of the god of Fire, Bhall, provides a source of Fire Mana.. Holds significance to the Clan, who may interact with it. Treasures may still await brave adventurers, but surely there are old terrible things remaining in the ruins.', 'en_US'),
('LOC_FEATURE_MAENALUS_DESCRIPTION', 'The people of the absentee God of Water lived here. None remain. Provides a source of Water Mana.', 'en_US'),
('LOC_FEATURE_ODIO_DESCRIPTION', 'The Archangel Odio was frozen in stone by Kilmorph when the Compact was signed. Perhaps he can be freed when it is broken. Provides a source of Body Mana.', 'en_US'),
('LOC_FEATURE_PINES_DESCRIPTION', 'The Compact was agreed here, and it remains a diplomatic moot. Owner of the Seven Pines may one-time use this to force peace with all warring enemies.', 'en_US'),
('LOC_FEATURE_CARCER_DESCRIPTION', 'When Bhall turned, her Archangel Brigit fought against her. Unable to kill her, Bhall imprisoned her where she would be weakest, in the deep snow. There she lies trapped, until someone worthy can free her to their cause.', 'en_US'),
('LOC_RESOURCE_ALE', 'Ale', 'en_US'),
('LOC_RESOURCE_BANANA', 'Banana', 'en_US'),
('LOC_RESOURCE_CLAM', 'Clam', 'en_US'),
('LOC_RESOURCE_CORN', 'Corn', 'en_US'),
('LOC_RESOURCE_COW', 'Cow', 'en_US'),
('LOC_RESOURCE_CRAB', 'Crab', 'en_US'),
('LOC_RESOURCE_DYE', 'Dye', 'en_US'),
('LOC_RESOURCE_FINE_CLOTHES', 'Fine Clothes', 'en_US'),
('LOC_RESOURCE_FRUIT_OF_YGGDRASIL', 'Fruit Of Yggdrasil', 'en_US'),
('LOC_RESOURCE_FUR', 'Fur', 'en_US'),
('LOC_RESOURCE_GEMS', 'Gems', 'en_US'),
('LOC_RESOURCE_GOLD', 'Gold', 'en_US'),
('LOC_RESOURCE_GULAGARM', 'Gulagarm', 'en_US'),
('LOC_RESOURCE_GUNPOWDER', 'Gunpowder', 'en_US'),
('LOC_RESOURCE_HORSE', 'Horse', 'en_US'),
('LOC_RESOURCE_JEWELS', 'Jewels', 'en_US'),
('LOC_RESOURCE_MANA', 'Raw Mana', 'en_US'),
('LOC_RESOURCE_MANA_AIR', 'Air Mana', 'en_US'),
('LOC_RESOURCE_MANA_BODY', 'Body Mana', 'en_US'),
('LOC_RESOURCE_MANA_CHAOS', 'Chaos Mana', 'en_US'),
('LOC_RESOURCE_MANA_DEATH', 'Death Mana', 'en_US'),
('LOC_RESOURCE_MANA_EARTH', 'Earth Mana', 'en_US'),
('LOC_RESOURCE_MANA_ENCHANTMENT', 'Enchantment Mana', 'en_US'),
('LOC_RESOURCE_MANA_ENTROPY', 'Entropy Mana', 'en_US'),
('LOC_RESOURCE_MANA_FIRE', 'Fire Mana', 'en_US'),
('LOC_RESOURCE_MANA_ICE', 'Ice Mana', 'en_US'),
('LOC_RESOURCE_MANA_LAW', 'Law Mana', 'en_US'),
('LOC_RESOURCE_MANA_LIFE', 'Life Mana', 'en_US'),
('LOC_RESOURCE_MANA_METAMAGIC', 'Metamagic Mana', 'en_US'),
('LOC_RESOURCE_MANA_MIND', 'Mind Mana', 'en_US'),
('LOC_RESOURCE_MANA_NATURE', 'Nature Mana', 'en_US'),
('LOC_RESOURCE_MANA_SHADOW', 'Shadow Mana', 'en_US'),
('LOC_RESOURCE_MANA_SPIRIT', 'Spirit Mana', 'en_US'),
('LOC_RESOURCE_MANA_SUN', 'Sun Mana', 'en_US'),
('LOC_RESOURCE_MANA_WATER', 'Water Mana', 'en_US'),
('LOC_RESOURCE_MITHRIL', 'Mithril', 'en_US'),
('LOC_RESOURCE_NIGHTMARE', 'Nightmare', 'en_US'),
('LOC_RESOURCE_PEARL', 'Pearl', 'en_US'),
('LOC_RESOURCE_PIG', 'Pig', 'en_US'),
('LOC_RESOURCE_RAZORWEED', 'Razorweed', 'en_US'),
('LOC_RESOURCE_REAGENTS', 'Reagents', 'en_US'),
('LOC_RESOURCE_SHEUT_STONE', 'Sheut Stone', 'en_US'),
('LOC_RESOURCE_TOAD', 'Toad', 'en_US'),
('LOC_RESOURCE_WHALE', 'Whale', 'en_US'),
('LOC_IMPROVEMENT_CAMP_NAME', 'Camp', 'en_US'),
('LOC_IMPROVEMENT_CASTLE_NAME', 'Castle', 'en_US'),
('LOC_IMPROVEMENT_CITADEL_NAME', 'Citadel', 'en_US'),
('LOC_IMPROVEMENT_COTTAGE_NAME', 'Cottage', 'en_US'),
('LOC_IMPROVEMENT_ENCLAVE_NAME', 'Enclave', 'en_US'),
('LOC_IMPROVEMENT_FARM_NAME', 'Farm', 'en_US'),
('LOC_IMPROVEMENT_FEITORIA_NAME', 'Pirate Port', 'en_US'),
('LOC_IMPROVEMENT_FISHING_BOATS_NAME', 'Fishing Boats', 'en_US'),
('LOC_IMPROVEMENT_FORT_NAME', 'Fort', 'en_US'),
('LOC_IMPROVEMENT_HAMLET_NAME', 'Hamlet', 'en_US'),
('LOC_IMPROVEMENT_LUMBERMILL_NAME', 'Lumbermill', 'en_US'),
('LOC_IMPROVEMENT_MANA_AIR_NAME', 'Air Node', 'en_US'),
('LOC_IMPROVEMENT_MANA_BODY_NAME', 'Body Node', 'en_US'),
('LOC_IMPROVEMENT_MANA_CHAOS_NAME', 'Chaos Node', 'en_US'),
('LOC_IMPROVEMENT_MANA_DEATH_NAME', 'Death Node', 'en_US'),
('LOC_IMPROVEMENT_MANA_EARTH_NAME', 'Earth Node', 'en_US'),
('LOC_IMPROVEMENT_MANA_ENCHANTMENT_NAME', 'Enchantment Node', 'en_US'),
('LOC_IMPROVEMENT_MANA_ENTROPY_NAME', 'Entropy Node', 'en_US'),
('LOC_IMPROVEMENT_MANA_FIRE_NAME', 'Fire Node', 'en_US'),
('LOC_IMPROVEMENT_MANA_LAW_NAME', 'Law Node', 'en_US'),
('LOC_IMPROVEMENT_MANA_LIFE_NAME', 'Life Node', 'en_US'),
('LOC_IMPROVEMENT_MANA_METAMAGIC_NAME', 'Metamagic Node', 'en_US'),
('LOC_IMPROVEMENT_MANA_MIND_NAME', 'Mind Node', 'en_US'),
('LOC_IMPROVEMENT_MANA_NATURE_NAME', 'Nature Node', 'en_US'),
('LOC_IMPROVEMENT_MANA_SHADOW_NAME', 'Shadow Node', 'en_US'),
('LOC_IMPROVEMENT_MANA_SPIRIT_NAME', 'Spirit Node', 'en_US'),
('LOC_IMPROVEMENT_MANA_SUN_NAME', 'Sun Node', 'en_US'),
('LOC_IMPROVEMENT_MANA_WATER_NAME', 'Water Node', 'en_US'),
('LOC_IMPROVEMENT_MINE_NAME', 'Mine', 'en_US'),
('LOC_IMPROVEMENT_PASTURE_NAME', 'Pasture', 'en_US'),
('LOC_IMPROVEMENT_PIRATE_COVE_NAME', 'Pirate Cove', 'en_US'),
('LOC_IMPROVEMENT_PIRATE_HARBOR_NAME', 'Pirate Harbor', 'en_US'),
('LOC_IMPROVEMENT_PLANTATION_NAME', 'Plantation', 'en_US'),
('LOC_IMPROVEMENT_QUARRY_NAME', 'Quarry', 'en_US'),
('LOC_IMPROVEMENT_TOWN_NAME', 'Town', 'en_US'),
('LOC_IMPROVEMENT_VILLAGE_NAME', 'Village', 'en_US'),
('LOC_IMPROVEMENT_WHALING_BOATS_NAME', 'Whaling Boats', 'en_US'),
('LOC_IMPROVEMENT_WINDMILL_NAME', 'Windmill', 'en_US'),
('LOC_IMPROVEMENT_WINERY_NAME', 'Winery', 'en_US'),
('LOC_IMPROVEMENT_WORKSHOP_NAME', 'Workshop', 'en_US'),
('LOC_IMPROVEMENT_CASTLE_DESCRIPTION', '25% Tile Defense. 10% Heal Defense. 10% Strength to all allied units within 2 tiles. Becomes a Citadel in 40 turns.', 'en_US'),
('LOC_IMPROVEMENT_CITADEL_DESCRIPTION', '40% Tile Defense. 20% Heal Defense. 15% Strength to all allied units within 2 tiles. +1 visibility to unit on tile.', 'en_US'),
('LOC_IMPROVEMENT_COTTAGE_DESCRIPTION', '+1 [ICON_Gold] Gold.Can be worked for 10 turns to convert into Hamlet.', 'en_US'),
('LOC_IMPROVEMENT_ENCLAVE_DESCRIPTION', 'A Town can be converted into an Enclave under the Kuriotates and after working for x turns.', 'en_US'),
('LOC_IMPROVEMENT_FARM_DESCRIPTION', 'Unlocks the Builder ability to construct Farms.[NEWLINE][NEWLINE]+1 [ICON_Food] Food. Can only be built on Grassland or Plains.[NEWLINE][NEWLINE]Constructing farms adjacent to other Farms provides bonuses to Housing.', 'en_US'),
('LOC_IMPROVEMENT_FEITORIA_DESCRIPTION', '30% Tile Defense. +20% Healing Rate. 10% Strength to allied units within 2 tiles. +2 [ICON_Food] Food. +2 [ICON_Production] Production. +4 [ICON_Gold] Gold. Cannot be built within 2 tiles of a Pirate Cove/Pirate Harbor/Pirate Port', 'en_US'),
('LOC_IMPROVEMENT_FISHING_BOATS_DESCRIPTION', 'Unlocks the Builder ability to construct Fishing Boats.[NEWLINE][NEWLINE]+1 [ICON_Food] Food. Can only be built on valid resources.[NEWLINE][NEWLINE]If built on Luxury resources, the city will gain use of that resource.', 'en_US'),
('LOC_IMPROVEMENT_FORT_DESCRIPTION', 'Occupying unit receives +4 [ICON_Strength] Defense Strength, and automatically gains 2 turns of fortification.', 'en_US'),
('LOC_IMPROVEMENT_HAMLET_DESCRIPTION', '+2 [ICON_Gold] Gold. Can be worked for 20 turns to convert into Village.', 'en_US'),
('LOC_IMPROVEMENT_LUMBERMILL_DESCRIPTION', 'Unlocks the Builder ability to construct a Lumber Mill.[NEWLINE][NEWLINE]+1 [ICON_Production] Production. +1 [ICON_Gold] Gold if adjacent to River. Can only be built on Woods.', 'en_US'),
('LOC_IMPROVEMENT_MANA_AIR_DESCRIPTION', 'If built on [ICON_RESOURCE_MANA_AIR] Air Mana, the city will gain use of that resource.[NEWLINE][NEWLINE] Converts raw mana to Air mana.', 'en_US'),
('LOC_IMPROVEMENT_MANA_BODY_DESCRIPTION', 'Converts raw mana to Body mana, and extracts it.', 'en_US'),
('LOC_IMPROVEMENT_MANA_CHAOS_DESCRIPTION', 'Converts raw mana to Chaos mana, and extracts it.', 'en_US'),
('LOC_IMPROVEMENT_MANA_DEATH_DESCRIPTION', 'Converts raw mana to Death mana, and extracts it.', 'en_US'),
('LOC_IMPROVEMENT_MANA_EARTH_DESCRIPTION', 'Converts raw mana to Earth mana, and extracts it.', 'en_US'),
('LOC_IMPROVEMENT_MANA_ENCHANTMENT_DESCRIPTION', 'Converts raw mana to Enchantment mana, and extracts it.', 'en_US'),
('LOC_IMPROVEMENT_MANA_ENTROPY_DESCRIPTION', 'Converts raw mana to Entropy mana, and extracts it.', 'en_US'),
('LOC_IMPROVEMENT_MANA_FIRE_DESCRIPTION', 'Converts raw mana to [ICON_RESOURCE_MANA_FIRE]Fire mana, and extracts it.', 'en_US'),
('LOC_IMPROVEMENT_MANA_LAW_DESCRIPTION', 'Converts raw mana to Law mana, and extracts it.', 'en_US'),
('LOC_IMPROVEMENT_MANA_LIFE_DESCRIPTION', 'Converts raw mana to Life mana, and extracts it.', 'en_US'),
('LOC_IMPROVEMENT_MANA_METAMAGIC_DESCRIPTION', 'Converts raw mana to Metamagic mana, and extracts it.', 'en_US'),
('LOC_IMPROVEMENT_MANA_MIND_DESCRIPTION', 'Converts raw mana to Mind mana, and extracts it.', 'en_US'),
('LOC_IMPROVEMENT_MANA_NATURE_DESCRIPTION', 'Converts raw mana to Nature mana, and extracts it.', 'en_US'),
('LOC_IMPROVEMENT_MANA_SHADOW_DESCRIPTION', 'Converts raw mana to Shadow mana, and extracts it.', 'en_US'),
('LOC_IMPROVEMENT_MANA_SPIRIT_DESCRIPTION', 'Converts raw mana to Spirit mana, and extracts it.', 'en_US'),
('LOC_IMPROVEMENT_MANA_SUN_DESCRIPTION', 'Converts raw mana to Sun mana, and extracts it.', 'en_US'),
('LOC_IMPROVEMENT_MANA_WATER_DESCRIPTION', 'Converts raw mana to Water mana, and extracts it.', 'en_US'),
('LOC_IMPROVEMENT_PIRATE_COVE_DESCRIPTION', 'Becomes a Pirate Harbor in 10 turns. 10% Tile Defense. +2 [ICON_Gold] Gold. Cannot be built within 2 tiles of a Pirate Cove/Pirate Harbor/Pirate Port', 'en_US'),
('LOC_IMPROVEMENT_PIRATE_HARBOR_DESCRIPTION', 'Becomes a Pirate Port in 20 turns. 20% Tile Defense. +1 [ICON_Food] Food. +1 [ICON_Production] Production. +3 [ICON_Gold] Gold. Cannot be built within 2 tiles of a Pirate Cove/Pirate Harbor/Pirate Port.', 'en_US'),
('LOC_IMPROVEMENT_TOWN_DESCRIPTION', '+4 [ICON_Gold] Gold. Made by upgrading a village.', 'en_US'),
('LOC_IMPROVEMENT_VILLAGE_DESCRIPTION', '+3 [ICON_Gold] Gold.Can be worked for 40 turns to convert into Town', 'en_US'),
('LOC_IMPROVEMENT_WHALING_BOATS_DESCRIPTION', 'Unlocks the Builder ability to construct Whaling Boats.[NEWLINE][NEWLINE] +1 [ICON_Production] Production. +2 [ICON_Gold] Gold. Can only be built on valid resources.[NEWLINE][NEWLINE]If built on Luxury resources, the city will gain use of that resource.', 'en_US'),
('LOC_IMPROVEMENT_WINDMILL_DESCRIPTION', 'Unlocks the Builder ability to construct Windmills.[NEWLINE][NEWLINE]+1 [ICON_Food] Food. +1 [ICON_Production] Production. +1 [ICON_Gold] Gold.', 'en_US'),
('LOC_IMPROVEMENT_WINERY_DESCRIPTION', 'Unlocks the Builder ability to construct Wineries.[NEWLINE][NEWLINE] +1 [ICON_Food] Food. +2 [ICON_Gold] Gold. Can only be built on valid resources.[NEWLINE][NEWLINE]If built on Luxury resources, the city will gain use of that resource.', 'en_US'),
('LOC_IMPROVEMENT_WORKSHOP_DESCRIPTION', 'Unlocks the Builder ability to construct Workshops.[NEWLINE][NEWLINE] -1 [ICON_Food] Food. +1 [ICON_Production] Production. +1 [ICON_Gold] Gold.', 'en_US');