-- 'LOC_NOTIFICATION_LAIR_' .. sEvent .. '_NAME'
-- 'LOC_NOTIFICATION_LAIR_' .. sEvent .. '_DESCRIPTION'
INSERT OR REPLACE INTO LocalizedText(Tag, Text, Language) VALUES
('LOC_NOTIFICATION_LAIR_BIGBAD_DESCRIPTION_NAME', 'BIGBAD_DESCRIPTION', 'en_US'),
('LOC_NOTIFICATION_LAIR_DEATH_DESCRIPTION', 'Your unit never returns from the depths of the lair.', 'en_US'),
('LOC_NOTIFICATION_LAIR_COLLAPSE_DESCRIPTION', 'The lair collapses. Your unit scrambles out of the rubble near death.', 'en_US'),
('LOC_NOTIFICATION_LAIR_CRAZED_DESCRIPTION', 'The lower level of the lair is partially submerged, touching the water fills your unit with visions that drive him mad.', 'en_US'),
('LOC_NOTIFICATION_LAIR_DEMONIC_POSSESSION_DESCRIPTION', 'Though it seems empty, occasional moans echo through the lair. Following them your unit encounters a violent spirit that possesses him.', 'en_US'),
('LOC_NOTIFICATION_LAIR_ENRAGED_DESCRIPTION', 'A cruel red sword hangs within the lair. Picking it up your unit is overcome with a powerful rage.', 'en_US'),
('LOC_NOTIFICATION_LAIR_MUTATED_DESCRIPTION', 'Your unit finds a basket of apples within the lair. Eating one transforms your unit.', 'en_US'),
('LOC_NOTIFICATION_LAIR_DISEASED_DESCRIPTION', 'Rotting corpses fill the lair and fat red insects feed on them. One of them stings your unit and infects him with a horrid disease.', 'en_US'),
('LOC_NOTIFICATION_LAIR_PLAGUED_DESCRIPTION', 'A laboratory exists within the lair. Destroying it creates a cloud of black gas that infects your unit with a wasting plague.', 'en_US'),
('LOC_NOTIFICATION_LAIR_POISONED_DESCRIPTION', 'A Scorpion Clan goblin attacks your unit as he explores the lair. Your unit defeats him but not before the goblin stabs him with a poisoned sword.', 'en_US'),
('LOC_NOTIFICATION_LAIR_WITHERED_DESCRIPTION', 'A statue is built at the center of the lair, your unit tries to topple it but when he touches it his arms shrivel and weaken.', 'en_US'),
('LOC_NOTIFICATION_LAIR_RUSTED_DESCRIPTION', 'A goblin shaman curses your unit as he flees the lair. Your units weapons turn to rust.', 'en_US'),
('LOC_NOTIFICATION_LAIR_SPIRIT_GUIDE_DESCRIPTION', 'The lair is full of corpses. After burying them and performing rites a spirit rises from the graves and blesses your unit.', 'en_US'),
('LOC_NOTIFICATION_LAIR_ENCHANTED_BLADE_DESCRIPTION', 'Your unit finds an enchanted blade within the lair.', 'en_US'),
('LOC_NOTIFICATION_LAIR_POISONED_BLADE_DESCRIPTION', 'Your unit finds a poisoned blade within the lair.', 'en_US'),
('LOC_NOTIFICATION_LAIR_FLAMING_ARROWS_DESCRIPTION', 'Your unit finds an enchanted sheath of flaming arrows within the lair.', 'en_US'),
('LOC_NOTIFICATION_LAIR_SHIELD_OF_FAITH_DESCRIPTION', 'You find an old shield inscribed with the symbol of Dagda within the lair.', 'en_US'),
('LOC_NOTIFICATION_LAIR_MITHRIL_WEAPONS_DESCRIPTION', 'You discover a cache of mithril weapons within the lair.', 'en_US'),
('LOC_NOTIFICATION_LAIR_IRON_WEAPONS_DESCRIPTION', 'You discover a cache of iron weapons within the lair.', 'en_US'),
('LOC_NOTIFICATION_LAIR_BRONZE_WEAPONS_DESCRIPTION', 'You discover a cache of bronze weapons within the lair.', 'en_US'),
('LOC_NOTIFICATION_LAIR_CAGE_DESCRIPTION', 'Its a trap, all the units in the tile are held until another unit comes to free them.', 'en_US'),
('LOC_NOTIFICATION_LAIR_SPAWN_DROWN_DESCRIPTION', 'Undead corpses rise from the waters.', 'en_US'),
('LOC_NOTIFICATION_LAIR_SPAWN_SEA_SERPENT_DESCRIPTION', 'There is a Sea Serpent trapped within the wreckage, after freeing it the creature turns on you.', 'en_US'),
('LOC_NOTIFICATION_LAIR_SPAWN_SPIDER_DESCRIPTION', 'The lair is full of webs, there must be a giant spider nearby.', 'en_US'),
('LOC_NOTIFICATION_LAIR_SPAWN_SPECTRE_DESCRIPTION', 'Spectres haunt this area!', 'en_US'),
('LOC_NOTIFICATION_LAIR_SPAWN_SCORPION_BAD_DESCRIPTION', 'Your explorers discover a nest of scorpions.', 'en_US'),
('LOC_NOTIFICATION_LAIR_SPAWN_SKELETON_DESCRIPTION', 'The remains of previous explorers rise up to meet you.', 'en_US'),
('LOC_NOTIFICATION_LAIR_SPAWN_LIZARDMAN_DESCRIPTION', 'Your exploration has angered some local lizardmen.', 'en_US'),
('LOC_NOTIFICATION_LAIR_SPAWN_FROSTLING_DESCRIPTION', 'Your scouts report vicious blue creatures playing in the snow.', 'en_US'),
('LOC_NOTIFICATION_LAIR_SPAWN_SCORPION_DESCRIPTION', 'An angry scorpion is stirred up by your explorers.', 'en_US'),
('LOC_NOTIFICATION_LAIR_SUPPLIES_DESCRIPTION', 'The lair is abandoned, but contains supplies you could use in your cities.', 'en_US'),
('LOC_NOTIFICATION_LAIR_PRISONER_DISCIPLE_ASHEN_DESCRIPTION', 'You find a prisoner trapped within the lair, a Savant who agrees to join you if you release him.', 'en_US'),
('LOC_NOTIFICATION_LAIR_PRISONER_DISCIPLE_EMPYREAN_DESCRIPTION', 'You find a prisoner trapped within the lair, an Ecclesiastic who agrees to join you if you release him.', 'en_US'),
('LOC_NOTIFICATION_LAIR_PRISONER_DISCIPLE_LEAVES_DESCRIPTION', 'You find a prisoner trapped within the lair, a Disciple of Leaves who agrees to join you if you release him.', 'en_US'),
('LOC_NOTIFICATION_LAIR_PRISONER_DISCIPLE_OVERLORDS_DESCRIPTION', 'You find a prisoner trapped within the lair, a Zealot who agrees to join you if you release him.', 'en_US'),
('LOC_NOTIFICATION_LAIR_PRISONER_DISCIPLE_RUNES_DESCRIPTION', 'You find a prisoner trapped within the lair, a Thane of Kilmorph who agrees to join you if you release him.', 'en_US'),
('LOC_NOTIFICATION_LAIR_PRISONER_DISCIPLE_ORDER_DESCRIPTION', 'You find a prisoner trapped within the lair, an Acolyte who agrees to join you if you release him.', 'en_US'),
('LOC_NOTIFICATION_LAIR_PRISONER_SEA_SERPENT_DESCRIPTION', 'There is a Sea Serpent trapped within the wreckage, after freeing it the appreciative creature joins your army.', 'en_US'),
('LOC_NOTIFICATION_LAIR_PRISONER_ADVENTURER_DESCRIPTION', 'You find a prisoner trapped within the lair, an Adventurer who agrees to join you if you release him.', 'en_US'),
('LOC_NOTIFICATION_LAIR_PRISONER_ARTIST_DESCRIPTION', 'You find a prisoner trapped within the lair, a Great Bard who agrees to join you if you release him.', 'en_US'),
('LOC_NOTIFICATION_LAIR_PRISONER_COMMANDER_DESCRIPTION', 'You find a prisoner trapped within the lair, a Great Commander who agrees to join you if you release him.', 'en_US'),
('LOC_NOTIFICATION_LAIR_PRISONER_ENGINEER_DESCRIPTION', 'You find a prisoner trapped within the lair, a Great Engineer who agrees to join you if you release him.', 'en_US'),
('LOC_NOTIFICATION_LAIR_PRISONER_MERCHANT_DESCRIPTION', 'You find a prisoner trapped within the lair, a Great Merchant who agrees to join you if you release him.', 'en_US'),
('LOC_NOTIFICATION_LAIR_PRISONER_PROPHET_DESCRIPTION', 'You find a prisoner trapped within the lair, a Great Prophet who agrees to join you if you release him.', 'en_US'),
('LOC_NOTIFICATION_LAIR_PRISONER_SCIENTIST_DESCRIPTION', 'You find a prisoner trapped within the lair, a Sage who agrees to join you if you release him.', 'en_US'),
('LOC_NOTIFICATION_LAIR_ITEM_HEALING_SALVE_DESCRIPTION', 'Your unit discovers a Healing Salve.', 'en_US'),
('LOC_NOTIFICATION_LAIR_ITEM_JADE_TORC_DESCRIPTION', 'Your unit discovers an ancient artifact, the Jade Torc.', 'en_US'),
('LOC_NOTIFICATION_LAIR_ITEM_ROD_OF_WINDS_DESCRIPTION', 'Your unit discovers an ancient artifact, the Rod of Winds.', 'en_US'),
('LOC_NOTIFICATION_LAIR_ITEM_TIMOR_MASK_DESCRIPTION', 'Your unit discovers an ancient artifact, the Timor Mask.', 'en_US'),
('LOC_NOTIFICATION_LAIR_SPELLSTAFF_DESCRIPTION', 'Your unit finds a spellstaff within the lair.', 'en_US'),
('LOC_NOTIFICATION_LAIR_PRISONER_ANGEL_DESCRIPTION', 'You find a prisoner trapped within the lair, an Angel who agrees to join you if you release him.', 'en_US'),
('LOC_NOTIFICATION_LAIR_PRISONER_MONK_DESCRIPTION', 'You find a prisoner trapped within the lair, a Monk who agrees to join you if you release him.', 'en_US'),
('LOC_NOTIFICATION_LAIR_PRISONER_ASSASSIN_DESCRIPTION', 'You find a prisoner trapped within the lair, an Assassin who agrees to join you if you release him.', 'en_US'),
('LOC_NOTIFICATION_LAIR_PRISONER_CHAMPION_DESCRIPTION', 'You find a prisoner trapped within the lair, a Champion who agrees to join you if you release him.', 'en_US'),
('LOC_NOTIFICATION_LAIR_PRISONER_MAGE_DESCRIPTION', 'You find a prisoner trapped within the lair, a Mage who agrees to join you if you release him.', 'en_US'),
('LOC_NOTIFICATION_LAIR_DEPTHS_DESCRIPTION', '', 'en_US'),
('LOC_NOTIFICATION_LAIR_DWARF_VS_LIZARDMEN_DESCRIPTION', '', 'en_US'),
('LOC_NOTIFICATION_LAIR_PORTAL_DESCRIPTION', 'Your unit comes out far away.', 'en_US'),
('LOC_NOTIFICATION_LAIR_BONUS_CLAM_DESCRIPTION', 'A colony of clams makes its home beneath the wreckage.', 'en_US'),
('LOC_NOTIFICATION_LAIR_BONUS_CRAB_DESCRIPTION', 'Furious crabs defend their home from exploration. Though aggressive they taste wonderful with a nice butter sauce.', 'en_US'),
('LOC_NOTIFICATION_LAIR_BONUS_FISH_DESCRIPTION', 'A huge school of fish make their home in the wreckage.', 'en_US'),
('LOC_NOTIFICATION_LAIR_BONUS_COPPER_DESCRIPTION', 'You discover a thick vein of copper ore beneath the lair.', 'en_US'),
('LOC_NOTIFICATION_LAIR_BONUS_GEMS_DESCRIPTION', 'Your unit is disappointed to find that their isnt any wealth within the lair, until he notices that the earthen walls glitter with raw gemstones.', 'en_US'),
('LOC_NOTIFICATION_LAIR_BONUS_GOLD_DESCRIPTION', 'You discover a thick vein of gold ore beneath the lair.', 'en_US'),
('LOC_NOTIFICATION_LAIR_BONUS_IRON_DESCRIPTION', 'You discover a thick vein of iron ore beneath the lair.', 'en_US'),
('LOC_NOTIFICATION_LAIR_NOTHING_DESCRIPTION', 'The lair is empty; your unit destroys it without incident.', 'en_US'),
('LOC_NOTIFICATION_LAIR_HIGH_GOLD_DESCRIPTION', 'Your unit discovers a cache of gold.', 'en_US'),
('LOC_NOTIFICATION_LAIR_TREASURE_DESCRIPTION', 'You find a map within the lair that gives direction to a distant treasure.', 'en_US'),
('LOC_NOTIFICATION_LAIR_EXPERIENCE_DESCRIPTION', 'Your unit gains experience from exploring the lair.', 'en_US'),
('LOC_NOTIFICATION_LAIR_TREASURE_VAULT_DESCRIPTION', 'Your unit finds a treasure vault within the lair.', 'en_US'),
('LOC_NOTIFICATION_LAIR_NOTHING_DESCRIPTION', 'The lair is empty; your unit destroys it without incident.', 'en_US'),
('LOC_NOTIFICATION_LAIR_GOLDEN_AGE_DESCRIPTION', 'The tale of your armies exploration spreads throughout your empire, sparking a new golden age.', 'en_US'),
('LOC_NOTIFICATION_LAIR_TECH_DESCRIPTION', 'Ancient scrolls are among the remains, you send them to your scholars.', 'en_US'),
('LOC_NOTIFICATION_LAIR_BIGBAD', 'Awoken Monsters!', 'en_US'),
('LOC_NOTIFICATION_LAIR_DEATH_NAME', 'DEATH', 'en_US'),
('LOC_NOTIFICATION_LAIR_COLLAPSE_NAME', 'COLLAPSE', 'en_US'),
('LOC_NOTIFICATION_LAIR_CRAZED_NAME', 'CRAZED', 'en_US'),
('LOC_NOTIFICATION_LAIR_DEMONIC_POSSESSION_NAME', 'DEMONIC_POSSESSION', 'en_US'),
('LOC_NOTIFICATION_LAIR_ENRAGED_NAME', 'ENRAGED', 'en_US'),
('LOC_NOTIFICATION_LAIR_MUTATED_NAME', 'MUTATED', 'en_US'),
('LOC_NOTIFICATION_LAIR_DISEASED_NAME', 'DISEASED', 'en_US'),
('LOC_NOTIFICATION_LAIR_PLAGUED_NAME', 'PLAGUED', 'en_US'),
('LOC_NOTIFICATION_LAIR_POISONED_NAME', 'POISONED', 'en_US'),
('LOC_NOTIFICATION_LAIR_WITHERED_NAME', 'WITHERED', 'en_US'),
('LOC_NOTIFICATION_LAIR_RUSTED_NAME', 'RUSTED', 'en_US'),
('LOC_NOTIFICATION_LAIR_SPIRIT_GUIDE_NAME', 'SPIRIT_GUIDE', 'en_US'),
('LOC_NOTIFICATION_LAIR_ENCHANTED_BLADE_NAME', 'ENCHANTED_BLADE', 'en_US'),
('LOC_NOTIFICATION_LAIR_POISONED_BLADE_NAME', 'POISONED_BLADE', 'en_US'),
('LOC_NOTIFICATION_LAIR_FLAMING_ARROWS_NAME', 'FLAMING_ARROWS', 'en_US'),
('LOC_NOTIFICATION_LAIR_SHIELD_OF_FAITH_NAME', 'SHIELD_OF_FAITH', 'en_US'),
('LOC_NOTIFICATION_LAIR_MITHRIL_WEAPONS_NAME', 'MITHRIL_WEAPONS', 'en_US'),
('LOC_NOTIFICATION_LAIR_IRON_WEAPONS_NAME', 'IRON_WEAPONS', 'en_US'),
('LOC_NOTIFICATION_LAIR_BRONZE_WEAPONS_NAME', 'BRONZE_WEAPONS', 'en_US'),
('LOC_NOTIFICATION_LAIR_CAGE_NAME', 'CAGE', 'en_US'),
('LOC_NOTIFICATION_LAIR_SPAWN_DROWN_NAME', 'SPAWN_DROWN', 'en_US'),
('LOC_NOTIFICATION_LAIR_SPAWN_SEA_SERPENT_NAME', 'SPAWN_SEA_SERPENT', 'en_US'),
('LOC_NOTIFICATION_LAIR_SPAWN_SPIDER_NAME', 'SPAWN_SPIDER', 'en_US'),
('LOC_NOTIFICATION_LAIR_SPAWN_SPECTRE_NAME', 'SPAWN_SPECTRE', 'en_US'),
('LOC_NOTIFICATION_LAIR_SPAWN_SCORPION_BAD_NAME', 'SPAWN_SCORPION_BAD', 'en_US'),
('LOC_NOTIFICATION_LAIR_SPAWN_SKELETON_NAME', 'SPAWN_SKELETON', 'en_US'),
('LOC_NOTIFICATION_LAIR_SPAWN_LIZARDMAN_NAME', 'SPAWN_LIZARDMAN', 'en_US'),
('LOC_NOTIFICATION_LAIR_SPAWN_FROSTLING_NAME', 'SPAWN_FROSTLING', 'en_US'),
('LOC_NOTIFICATION_LAIR_SPAWN_SCORPION_NAME', 'SPAWN_SCORPION', 'en_US'),
('LOC_NOTIFICATION_LAIR_SUPPLIES_NAME', 'SUPPLIES', 'en_US'),
('LOC_NOTIFICATION_LAIR_PRISONER_DISCIPLE_ASHEN_NAME', 'PRISONER_DISCIPLE_ASHEN', 'en_US'),
('LOC_NOTIFICATION_LAIR_PRISONER_DISCIPLE_EMPYREAN_NAME', 'PRISONER_DISCIPLE_EMPYREAN', 'en_US'),
('LOC_NOTIFICATION_LAIR_PRISONER_DISCIPLE_LEAVES_NAME', 'PRISONER_DISCIPLE_LEAVES', 'en_US'),
('LOC_NOTIFICATION_LAIR_PRISONER_DISCIPLE_OVERLORDS_NAME', 'PRISONER_DISCIPLE_OVERLORDS', 'en_US'),
('LOC_NOTIFICATION_LAIR_PRISONER_DISCIPLE_RUNES_NAME', 'PRISONER_DISCIPLE_RUNES', 'en_US'),
('LOC_NOTIFICATION_LAIR_PRISONER_DISCIPLE_ORDER_NAME', 'PRISONER_DISCIPLE_ORDER', 'en_US'),
('LOC_NOTIFICATION_LAIR_PRISONER_SEA_SERPENT_NAME', 'PRISONER_SEA_SERPENT', 'en_US'),
('LOC_NOTIFICATION_LAIR_PRISONER_ADVENTURER_NAME', 'PRISONER_ADVENTURER', 'en_US'),
('LOC_NOTIFICATION_LAIR_PRISONER_ARTIST_NAME', 'PRISONER_ARTIST', 'en_US'),
('LOC_NOTIFICATION_LAIR_PRISONER_COMMANDER_NAME', 'PRISONER_COMMANDER', 'en_US'),
('LOC_NOTIFICATION_LAIR_PRISONER_ENGINEER_NAME', 'PRISONER_ENGINEER', 'en_US'),
('LOC_NOTIFICATION_LAIR_PRISONER_MERCHANT_NAME', 'PRISONER_MERCHANT', 'en_US'),
('LOC_NOTIFICATION_LAIR_PRISONER_PROPHET_NAME', 'PRISONER_PROPHET', 'en_US'),
('LOC_NOTIFICATION_LAIR_PRISONER_SCIENTIST_NAME', 'PRISONER_SCIENTIST', 'en_US'),
('LOC_NOTIFICATION_LAIR_ITEM_HEALING_SALVE_NAME', 'ITEM_HEALING_SALVE', 'en_US'),
('LOC_NOTIFICATION_LAIR_ITEM_JADE_TORC_NAME', 'ITEM_JADE_TORC', 'en_US'),
('LOC_NOTIFICATION_LAIR_ITEM_ROD_OF_WINDS_NAME', 'ITEM_ROD_OF_WINDS', 'en_US'),
('LOC_NOTIFICATION_LAIR_ITEM_TIMOR_MASK_NAME', 'ITEM_TIMOR_MASK', 'en_US'),
('LOC_NOTIFICATION_LAIR_SPELLSTAFF_NAME', 'SPELLSTAFF', 'en_US'),
('LOC_NOTIFICATION_LAIR_PRISONER_ANGEL_NAME', 'PRISONER_ANGEL', 'en_US'),
('LOC_NOTIFICATION_LAIR_PRISONER_MONK_NAME', 'PRISONER_MONK', 'en_US'),
('LOC_NOTIFICATION_LAIR_PRISONER_ASSASSIN_NAME', 'PRISONER_ASSASSIN', 'en_US'),
('LOC_NOTIFICATION_LAIR_PRISONER_CHAMPION_NAME', 'PRISONER_CHAMPION', 'en_US'),
('LOC_NOTIFICATION_LAIR_PRISONER_MAGE_NAME', 'PRISONER_MAGE', 'en_US'),
('LOC_NOTIFICATION_LAIR_DEPTHS_NAME', 'DEPTHS', 'en_US'),
('LOC_NOTIFICATION_LAIR_DWARF_VS_LIZARDMEN_NAME', 'DWARF_VS_LIZARDMEN', 'en_US'),
('LOC_NOTIFICATION_LAIR_PORTAL_NAME', 'PORTAL', 'en_US'),
('LOC_NOTIFICATION_LAIR_BONUS_CLAM_NAME', 'BONUS_CLAM', 'en_US'),
('LOC_NOTIFICATION_LAIR_BONUS_CRAB_NAME', 'BONUS_CRAB', 'en_US'),
('LOC_NOTIFICATION_LAIR_BONUS_FISH_NAME', 'BONUS_FISH', 'en_US'),
('LOC_NOTIFICATION_LAIR_BONUS_COPPER_NAME', 'BONUS_COPPER', 'en_US'),
('LOC_NOTIFICATION_LAIR_BONUS_GEMS_NAME', 'BONUS_GEMS', 'en_US'),
('LOC_NOTIFICATION_LAIR_BONUS_GOLD_NAME', 'BONUS_GOLD', 'en_US'),
('LOC_NOTIFICATION_LAIR_BONUS_IRON_NAME', 'BONUS_IRON', 'en_US'),
('LOC_NOTIFICATION_LAIR_NOTHING_NAME', 'NOTHING', 'en_US'),
('LOC_NOTIFICATION_LAIR_HIGH_GOLD_NAME', 'HIGH_GOLD', 'en_US'),
('LOC_NOTIFICATION_LAIR_TREASURE_NAME', 'TREASURE', 'en_US'),
('LOC_NOTIFICATION_LAIR_EXPERIENCE_NAME', 'EXPERIENCE', 'en_US'),
('LOC_NOTIFICATION_LAIR_TREASURE_VAULT_NAME', 'TREASURE_VAULT', 'en_US'),
('LOC_NOTIFICATION_LAIR_NOTHING_NAME', 'NOTHING', 'en_US'),
('LOC_NOTIFICATION_LAIR_GOLDEN_AGE_NAME', 'GOLDEN_AGE', 'en_US'),
('LOC_NOTIFICATION_LAIR_TECH', 'Tech', 'en_US'),
('LOC_ORTHUS_SPAWN_NOTIFICATION_TITLE', 'Orthus Awakens', 'en_US'),
('LOC_ORTHUS_SPAWN_NOTIFICATION_DESCRIPTION', 'Orthus, the Barbarian King, has entered the lands. This powerful hero is responsible for the deaths of more empires than any in creation. But the unit that defeats Orthus gains his powerful axe.', 'en_US'),
('LOC_WORLDSPELL_LEGENDS_NOTIFICATION_TITLE', 'Legends Cast', 'en_US'),
('LOC_WORLDSPELL_LEGENDS_NOTIFICATION_DESCRIPTION', 'The Kuriotates have cast Legends, gaining Culture in every city.', 'en_US'),
('LOC_WORLDSPELL_RALLY_NOTIFICATION_TITLE', 'Rally Cast', 'en_US'),
('LOC_WORLDSPELL_RALLY_NOTIFICATION_DESCRIPTION', 'The Bannor have cast Rally, gaining Demagogs on every Town Improvement.', 'en_US'),
('LOC_WORLDSPELL_RELIGIOUS_FERVOR_NOTIFICATION_TITLE', 'Religious Fervor Cast', 'en_US'),
('LOC_WORLDSPELL_RELIGIOUS_FERVOR_NOTIFICATION_DESCRIPTION', 'The Malakim have cast Religious Fervor, gaining Priests of their State Religion', 'en_US'),
('LOC_WORLDSPELL_MARCH_OF_THE_TREES_NOTIFICATION_TITLE', 'March of the Trees cast', 'en_US'),
('LOC_WORLDSPELL_MARCH_OF_THE_TREES_NOTIFICATION_DESCRIPTION', 'The Ljolsalfar have cast March of the Trees, converting their woodlands to short-lived Treants.', 'en_US'),
('LOC_WORLDSPELL_MOTHER_LODE_NOTIFICATION_TITLE', 'Mother Lode cast', 'en_US'),
('LOC_WORLDSPELL_MOTHER_LODE_NOTIFICATION_DESCRIPTION', 'The Khazad has cast Mother Lode, Gaining gold for every mine tile and converting 25% of their flatland to Hills.', 'en_US'),
('LOC_WORLDSPELL_ARCANE_LACUNA_NOTIFICATION_TITLE', 'Arcane Lacuna Cast', 'en_US'),
('LOC_WORLDSPELL_ARCANE_LACUNA_NOTIFICATION_DESCRIPTION', 'The Amurites have cast Arcane Lacuna. All other players cannot cast spells.', 'en_US'),
('LOC_WORLDSPELL_WILD_HUNT_NOTIFICATION_TITLE', 'Wild Hunt Cast', 'en_US'),
('LOC_WORLDSPELL_WILD_HUNT_NOTIFICATION_DESCRIPTION', 'The Doviello have cast Wild Hunt, gaining packs of Wolves.', 'en_US'),
('LOC_WORLDSPELL_REVELRY_NOTIFICATION_TITLE', 'Revelry Cast', 'en_US'),
('LOC_WORLDSPELL_REVELRY_NOTIFICATION_DESCRIPTION', 'The Balseraph have cast Revelry.', 'en_US'),
('LOC_WORLDSPELL_FOR_THE_HORDE_NOTIFICATION_TITLE', 'For the Horde Cast', 'en_US'),
('LOC_WORLDSPELL_FOR_THE_HORDE_NOTIFICATION_DESCRIPTION', 'The Clan have cast For the Horde! Half of the non-animal barbarians are converted to their cause.', 'en_US'),
('LOC_WORLDSPELL_INTO_THE_MIST_NOTIFICATION_TITLE', 'Into the Mist Cast', 'en_US'),
('LOC_WORLDSPELL_INTO_THE_MIST_NOTIFICATION_DESCRIPTION', 'The Sidar have cast Into the Mist. All their greivances have been reset, and all their units are Invisible.', 'en_US'),
('LOC_WORLDSPELL_RAGING_SEAS_NOTIFICATION_TITLE', 'Raging Seas Cast', 'en_US'),
('LOC_WORLDSPELL_RAGING_SEAS_NOTIFICATION_DESCRIPTION', 'The Lanun have cast Raging Seas. All non-Lanun units by the Coast are damaged, and improvements pillaged.', 'en_US'),
('LOC_WORLDSPELL_WARCRY_NOTIFICATION_TITLE', 'Warcry Cast', 'en_US'),
('LOC_WORLDSPELL_WARCRY_NOTIFICATION_DESCRIPTION', 'The Hippus have cast Warcry. All their units move faster, and gain more xp for a period.', 'en_US'),
('LOC_WORLDSPELL_GIFTS_NOTIFICATION_TITLE', 'Gifts of Nantosuelta Cast', 'en_US'),
('LOC_WORLDSPELL_GIFTS_NOTIFICATION_DESCRIPTION', 'The Luchuirp have cast Gifts of Nantosuelta, gaining a Golden Hammer in each city.', 'en_US'),
('LOC_WORLDSPELL_WORLDBREAK_NOTIFICATION_TITLE', 'Worldbreak Cast', 'en_US'),
('LOC_WORLDSPELL_WORLDBREAK_NOTIFICATION_DESCRIPTION', 'The Sheaim have cast Worldbreak. All non-sheaim units take damage proportional to the armageddon counter.', 'en_US'),
('LOC_WORLDSPELL_STASIS_NOTIFICATION_TITLE', 'Stasis Cast', 'en_US'),
('LOC_WORLDSPELL_STASIS_NOTIFICATION_DESCRIPTION', 'Illians have cast Stasis. All non-Illians have no Production, Science or Culture for x turns.', 'en_US'),
('LOC_WORLDSPELL_DIVINE_RETRIBUTION_NOTIFICATION_TITLE', 'Divine Retribution Cast', 'en_US'),
('LOC_WORLDSPELL_DIVINE_RETRIBUTION_NOTIFICATION_DESCRIPTION', 'The Mercurians have cast Divine Retribution, damaging all Undead and Demonic units.', 'en_US'),
('LOC_WORLDSPELL_HYBOREMS_WHISPER_NOTIFICATION_TITLE', 'Hyborems Whisper Cast', 'en_US'),
('LOC_WORLDSPELL_HYBOREMS_WHISPER_NOTIFICATION_DESCRIPTION', 'Dreams of Hyborem have infiltrated the minds of most populous Ashen Veil city, X. Fallen to temptation, those followers opened a portal and welcomed Hell into their city, which is now under Infernal control.', 'en_US'),
('LOC_WORLDSPELL_RIVERS_OF_BLOOD_NOTIFICATION_TITLE', 'Rivers of Blood Cast', 'en_US'),
('LOC_WORLDSPELL_RIVERS_OF_BLOOD_NOTIFICATION_DESCRIPTION', 'The Calabim have cast Rivers of Blood, reducing the population of all other players cities by 2, and increasing their own by 2.', 'en_US');


-- 'The lair was set upon a raw mana node.' RAW_MANA

-- POSSESSED 'Though it seems empty, occasional moans echo through the lair. Following them your unit encounters a violent spirit that possesses him.'

-- 'Travellers speak of a mighty Dragon, who wants to make %s1_city his lair'