INSERT OR REPLACE INTO LocalizedText(Tag, Text, Language) VALUES
('LOC_CIV_AMURITES_NAME', 'Amurites', 'en_US'),
('LOC_CIV_BALSERAPHS_NAME', 'Balseraphs', 'en_US'),
('LOC_CIV_BANNOR_NAME', 'Bannor', 'en_US'),
('LOC_CIV_CALABIM_NAME', 'Calabim', 'en_US'),
('LOC_CIV_CLAN_OF_EMBERS_NAME', 'Clan Of Embers', 'en_US'),
('LOC_CIV_DOVIELLO_NAME', 'Doviello', 'en_US'),
('LOC_CIV_ELOHIM_NAME', 'Elohim', 'en_US'),
('LOC_CIV_GRIGORI_NAME', 'Grigori', 'en_US'),
('LOC_CIV_HIPPUS_NAME', 'Hippus', 'en_US'),
('LOC_CIV_ILLIANS_NAME', 'Illians', 'en_US'),
('LOC_CIV_INFERNAL_NAME', 'Infernal', 'en_US'),
('LOC_CIV_KHAZAD_NAME', 'Khazad', 'en_US'),
('LOC_CIV_KURIOTATES_NAME', 'Kuriotates', 'en_US'),
('LOC_CIV_LANUN_NAME', 'Lanun', 'en_US'),
('LOC_CIV_LJOSALFAR_NAME', 'Ljosalfar', 'en_US'),
('LOC_CIV_LUCHUIRP_NAME', 'Luchuirp', 'en_US'),
('LOC_CIV_MALAKIM_NAME', 'Malakim', 'en_US'),
('LOC_CIV_MERCURIANS_NAME', 'Mercurians', 'en_US'),
('LOC_CIV_SHEAIM_NAME', 'Sheaim', 'en_US'),
('LOC_CIV_SIDAR_NAME', 'Sidar', 'en_US'),
('LOC_CIV_SVARTALFAR_NAME', 'Svartalfar', 'en_US'),
('LOC_CIV_AMURITES_DESCRIPTION', 'The Amurites', 'en_US'),
('LOC_CIV_BALSERAPHS_DESCRIPTION', 'The Balseraphs', 'en_US'),
('LOC_CIV_BANNOR_DESCRIPTION', 'The Bannor', 'en_US'),
('LOC_CIV_CALABIM_DESCRIPTION', 'The Calabim', 'en_US'),
('LOC_CIV_CLAN_OF_EMBERS_DESCRIPTION', 'Clan of Embers', 'en_US'),
('LOC_CIV_DOVIELLO_DESCRIPTION', 'The Doviello', 'en_US'),
('LOC_CIV_ELOHIM_DESCRIPTION', 'The Elohim', 'en_US'),
('LOC_CIV_GRIGORI_DESCRIPTION', 'The Grigori', 'en_US'),
('LOC_CIV_HIPPUS_DESCRIPTION', 'The Hippus', 'en_US'),
('LOC_CIV_ILLIANS_DESCRIPTION', 'The Illian', 'en_US'),
('LOC_CIV_INFERNAL_DESCRIPTION', 'The Infernal', 'en_US'),
('LOC_CIV_KHAZAD_DESCRIPTION', 'The Khazad', 'en_US'),
('LOC_CIV_KURIOTATES_DESCRIPTION', 'The Kuriotates', 'en_US'),
('LOC_CIV_LANUN_DESCRIPTION', 'The Lanun', 'en_US'),
('LOC_CIV_LJOSALFAR_DESCRIPTION', 'The Ljosalfar', 'en_US'),
('LOC_CIV_LUCHUIRP_DESCRIPTION', 'The Luichuirp', 'en_US'),
('LOC_CIV_MALAKIM_DESCRIPTION', 'The Malakim', 'en_US'),
('LOC_CIV_MERCURIANS_DESCRIPTION', 'The Mercurian', 'en_US'),
('LOC_CIV_SHEAIM_DESCRIPTION', 'The Sheaim', 'en_US'),
('LOC_CIV_SIDAR_DESCRIPTION', 'The Sidar', 'en_US'),
('LOC_CIV_SVARTALFAR_DESCRIPTION', 'The Svartalfar', 'en_US'),
('LOC_SLTH_CIV_AMURITES_ADJECTIVE', 'Amurite', 'en_US'),
('LOC_SLTH_CIV_BALSERAPHS_ADJECTIVE', 'Balseraph', 'en_US'),
('LOC_SLTH_CIV_BANNOR_ADJECTIVE', 'Bannorian', 'en_US'),
('LOC_SLTH_CIV_CALABIM_ADJECTIVE', 'Calabimian', 'en_US'),
('LOC_SLTH_CIV_CLAN_OF_EMBERS_ADJECTIVE', 'Clan Of Ember', 'en_US'),
('LOC_SLTH_CIV_DOVIELLO_ADJECTIVE', 'Dovielloian', 'en_US'),
('LOC_SLTH_CIV_ELOHIM_ADJECTIVE', 'Elohimian', 'en_US'),
('LOC_SLTH_CIV_GRIGORI_ADJECTIVE', 'Grigoriian', 'en_US'),
('LOC_SLTH_CIV_HIPPUS_ADJECTIVE', 'Hippu', 'en_US'),
('LOC_SLTH_CIV_ILLIANS_ADJECTIVE', 'Illian', 'en_US'),
('LOC_SLTH_CIV_INFERNAL_ADJECTIVE', 'Infernalian', 'en_US'),
('LOC_SLTH_CIV_KHAZAD_ADJECTIVE', 'Khazadian', 'en_US'),
('LOC_SLTH_CIV_KURIOTATES_ADJECTIVE', 'Kuriotate', 'en_US'),
('LOC_SLTH_CIV_LANUN_ADJECTIVE', 'Lanun', 'en_US'),
('LOC_SLTH_CIV_LJOSALFAR_ADJECTIVE', 'Ljosalfarian', 'en_US'),
('LOC_SLTH_CIV_LUCHUIRP_ADJECTIVE', 'Luchuirpian', 'en_US'),
('LOC_SLTH_CIV_MALAKIM_ADJECTIVE', 'Malakimian', 'en_US'),
('LOC_SLTH_CIV_MERCURIANS_ADJECTIVE', 'Mercurian', 'en_US'),
('LOC_SLTH_CIV_SHEAIM_ADJECTIVE', 'Sheaimian', 'en_US'),
('LOC_SLTH_CIV_SIDAR_ADJECTIVE', 'Sidarian', 'en_US'),
('LOC_SLTH_CIV_SVARTALFAR_ADJECTIVE', 'Svartalfarian', 'en_US'),
('LOC_LEADER_ALEXIS_NAME', 'Alexis', 'en_US'),
('LOC_LEADER_AMELANCHIER_NAME', 'Amelanchier', 'en_US'),
('LOC_LEADER_ARENDEL_NAME', 'Arendel', 'en_US'),
('LOC_LEADER_ARTURUS_NAME', 'Arturus', 'en_US'),
('LOC_LEADER_AURIC_NAME', 'Auric', 'en_US'),
('LOC_LEADER_BASIUM_NAME', 'Basium', 'en_US'),
('LOC_LEADER_BEERI_NAME', 'Beeri', 'en_US'),
('LOC_LEADER_CAPRIA_NAME', 'Capria', 'en_US'),
('LOC_LEADER_CARDITH_NAME', 'Cardith', 'en_US'),
('LOC_LEADER_CASSIEL_NAME', 'Cassiel', 'en_US'),
('LOC_LEADER_CHARADON_NAME', 'Charadon', 'en_US'),
('LOC_LEADER_DAIN_NAME', 'Dain', 'en_US'),
('LOC_LEADER_DECIUS_NAME', 'Decius', 'en_US'),
('LOC_LEADER_EINION_NAME', 'Einion', 'en_US'),
('LOC_LEADER_ETHNE_NAME', 'Ethne', 'en_US'),
('LOC_LEADER_FAERYL_NAME', 'Faeryl', 'en_US'),
('LOC_LEADER_FALAMAR_NAME', 'Falamar', 'en_US'),
('LOC_LEADER_FLAUROS_NAME', 'Flauros', 'en_US'),
('LOC_LEADER_GARRIM_NAME', 'Garrim', 'en_US'),
('LOC_LEADER_HANNAH_NAME', 'Hannah', 'en_US'),
('LOC_LEADER_HYBOREM_NAME', 'Hyborem', 'en_US'),
('LOC_LEADER_JONAS_NAME', 'Jonas', 'en_US'),
('LOC_LEADER_KANDROS_NAME', 'Kandros', 'en_US'),
('LOC_LEADER_KEELYN_NAME', 'Keelyn', 'en_US'),
('LOC_LEADER_MAHALA_NAME', 'Mahala', 'en_US'),
('LOC_LEADER_OS_GABELLA_NAME', 'Os Gabella', 'en_US'),
('LOC_LEADER_PERPENTACH_NAME', 'Perpentach', 'en_US'),
('LOC_LEADER_RHOANNA_NAME', 'Rhoanna', 'en_US'),
('LOC_LEADER_SABATHIEL_NAME', 'Sabathiel', 'en_US'),
('LOC_LEADER_SANDALPHON_NAME', 'Sandalphon', 'en_US'),
('LOC_LEADER_SHEELBA_NAME', 'Sheelba', 'en_US'),
('LOC_LEADER_TASUNKE_NAME', 'Tasunke', 'en_US'),
('LOC_LEADER_TEBRYN_NAME', 'Tebryn', 'en_US'),
('LOC_LEADER_THESSA_NAME', 'Thessa', 'en_US'),
('LOC_LEADER_VALLEDIA_NAME', 'Valledia', 'en_US'),
('LOC_LEADER_VARN_NAME', 'Varn', 'en_US');