INSERT OR REPLACE INTO LocalizedText(Text, Tag, Language) VALUES
('Cities have +1 [ICON_Amenities]Amenity, Units earn XP 33% faster [NEWLINE][NEWLINE]Half cost Policy Upkeep, Can Build Command Posts, Double Production[ICON_Production] towards Lighthouse and Courthouses', 'LOC_SABATHIEL_TRAITS_DESCRIPTION', 'en_US'),
('Disciple Units have Potency, earning more XP per turn. Changing Policies never causes Anarchy (NOT DONE). Double Production[ICON_Production] towards Religious Temples and Pagan Temple [NEWLINE][NEWLINE]50% increased Production[ICON_Production] towards Wonders, Double Production[ICON_Production] speed of Forges', 'LOC_CAPRIA_TRAITS_DESCRIPTION', 'en_US'),
('Half cost Policy Upkeep, Can Build Command Posts, Double Production[ICON_Production] towards Lighthouse and Courthouses [NEWLINE][NEWLINE]Double yields from pillaging, Combat units have Commando ability (unimplemented)', 'LOC_DECIUS_TRAITS_DESCRIPTION', 'en_US'),
('Disciple Units have Potency, earning more XP per turn. Changing Policies never causes Anarchy (NOT DONE). Double Production[ICON_Production] towards Religious Temples and Pagan Temple [NEWLINE][NEWLINE]+2[ICON_Culture] Culture in all Cities, Double Production[ICON_Production] towards Monuments and Carnivals', 'LOC_VARN_TRAITS_DESCRIPTION', 'en_US'),
('+2[ICON_Culture] Culture in all Cities, Double Production[ICON_Production] towards Monuments and Carnivals [NEWLINE][NEWLINE]Combat Units have the Homeland ability, making them stronger in friendly territory. Double Production[ICON_Production] towards Archery Ranges, Palisades and Walls', 'LOC_ETHNE_TRAITS_DESCRIPTION', 'en_US'),
('Double [ICON_GreatPerson]Great People points , Double Production[ICON_Production] towards Elder Councils and Libraries  [NEWLINE][NEWLINE]Combat Units have the Homeland ability, making them stronger in friendly territory. Double Production[ICON_Production] towards Archery Ranges, Palisades and Walls', 'LOC_EINION_TRAITS_DESCRIPTION', 'en_US'),
('Combat units start with Combat I promotion, Double Production[ICON_Production] towards Siege Workshop, Shipyard  [NEWLINE][NEWLINE]Double yields from pillaging, Combat units have Commando ability (unimplemented) [NEWLINE][NEWLINE]Starts with 100 Gold, 50% discount on all unit upgrades. [NEWLINE][NEWLINE]', 'LOC_BASIUM_TRAITS_DESCRIPTION', 'en_US'),
('Plots with more than 1 Gold[ICON_Gold] get an additional Gold[ICON_Gold] (NOT DONE). Double Production[ICON_Production] towards Markets and Moneychanger [NEWLINE][NEWLINE]Combat Units have the Homeland ability, making them stronger in friendly territory. Double Production[ICON_Production] towards Archery Ranges, Palisades and Walls', 'LOC_GARRIM_TRAITS_DESCRIPTION', 'en_US'),
('50% increased Production[ICON_Production] towards Wonders, Double Production[ICON_Production] speed of Forges [NEWLINE][NEWLINE]Half cost Policy Upkeep, Can Build Command Posts, Double Production[ICON_Production] towards Lighthouse and Courthouses', 'LOC_BEERI_TRAITS_DESCRIPTION', 'en_US'),
('Double Production[ICON_Production] towards Settlers, Granaries and Harbors, +3 Housing, [NEWLINE][NEWLINE]Double [ICON_GreatPerson]Great People points , Double Production[ICON_Production] towards Elder Councils and Libraries ', 'LOC_CARDITH_TRAITS_DESCRIPTION', 'en_US'),
('Combat Units have the Homeland ability, making them stronger in friendly territory. Double Production[ICON_Production] towards Archery Ranges, Palisades and Walls [NEWLINE][NEWLINE]Double yields from pillaging, Combat units have Commando ability (unimplemented)', 'LOC_AMELANCHIER_TRAITS_DESCRIPTION', 'en_US'),
('Disciple Units have Potency, earning more XP per turn. Changing Policies never causes Anarchy (NOT DONE). Double Production[ICON_Production] towards Religious Temples and Pagan Temple [NEWLINE][NEWLINE]+2[ICON_Culture] Culture in all Cities, Double Production[ICON_Production] towards Monuments and Carnivals', 'LOC_ARENDEL_TRAITS_DESCRIPTION', 'en_US'),
('Arcane Units start with Potency, gaining experience faster. Double Production[ICON_Production] towards Mages Guilds [NEWLINE][NEWLINE]Double Production[ICON_Production] towards Settlers, Granaries and Harbors, +3 Housing,', 'LOC_THESSA_TRAITS_DESCRIPTION', 'en_US'),
('50% increased Production[ICON_Production] towards Wonders, Double Production[ICON_Production] speed of Forges [NEWLINE][NEWLINE]Half cost Policy Upkeep, Can Build Command Posts, Double Production[ICON_Production] towards Lighthouse and Courthouses', 'LOC_ARTURUS_TRAITS_DESCRIPTION', 'en_US'),
('Combat units start with Combat I promotion, Double Production[ICON_Production] towards Siege Workshop, Shipyard  [NEWLINE][NEWLINE]Plots with more than 1 Gold[ICON_Gold] get an additional Gold[ICON_Gold] (NOT DONE). Double Production[ICON_Production] towards Markets and Moneychanger [NEWLINE][NEWLINE]Starts with 100 Gold, 50% discount on all unit upgrades.', 'LOC_KANDROS_TRAITS_DESCRIPTION', 'en_US'),
('Combat Units have the Homeland ability, making them stronger in friendly territory. Double Production[ICON_Production] towards Archery Ranges, Palisades and Walls [NEWLINE][NEWLINE]50% increased Production[ICON_Production] towards Wonders, Double Production[ICON_Production] speed of Forges', 'LOC_SANDALPHON_TRAITS_DESCRIPTION', 'en_US'),
('Cities have +1 [ICON_Amenities]Amenity, Units earn XP 33% faster [NEWLINE][NEWLINE]Double Production[ICON_Production] towards Settlers, Granaries and Harbors, +3 Housing,', 'LOC_FALAMAR_TRAITS_DESCRIPTION', 'en_US'),
('Plots with more than 1 Gold[ICON_Gold] get an additional Gold[ICON_Gold] (NOT DONE). Double Production[ICON_Production] towards Markets and Moneychanger [NEWLINE][NEWLINE]Double yields from pillaging, Combat units have Commando ability (unimplemented)', 'LOC_HANNAH_TRAITS_DESCRIPTION', 'en_US'),
('50% increased Production[ICON_Production] towards Wonders, Double Production[ICON_Production] speed of Forges [NEWLINE][NEWLINE]Double [ICON_GreatPerson]Great People points , Double Production[ICON_Production] towards Elder Councils and Libraries.', 'LOC_CASSIEL_TRAITS_DESCRIPTION', 'en_US'),
('Combat units start with Combat I promotion, Double Production[ICON_Production] towards Siege Workshop, Shipyard  [NEWLINE][NEWLINE]Double yields from pillaging, Combat units have Commando ability (unimplemented)', 'LOC_TASUNKE_TRAITS_DESCRIPTION', 'en_US'),
('Double Production[ICON_Production] towards Settlers, Granaries and Harbors, +3 Housing, [NEWLINE][NEWLINE]Plots with more than 1 Gold[ICON_Gold] get an additional Gold[ICON_Gold] (NOT DONE). Double Production[ICON_Production] towards Markets and Moneychanger', 'LOC_RHOANNA_TRAITS_DESCRIPTION', 'en_US'),
('Arcane Units start with Potency, gaining experience faster. Double Production[ICON_Production] towards Mages Guilds [NEWLINE][NEWLINE]Half cost Policy Upkeep, Can Build Command Posts, Double Production[ICON_Production] towards Lighthouse and Courthouses', 'LOC_VALLEDIA_TRAITS_DESCRIPTION', 'en_US'),
('Arcane Units start with Potency, gaining experience faster. Double Production[ICON_Production] towards Mages Guilds [NEWLINE][NEWLINE]Double [ICON_GreatPerson]Great People points , Double Production[ICON_Production] towards Elder Councils and Libraries ', 'LOC_DAIN_TRAITS_DESCRIPTION', 'en_US'),
('Combat units start with Combat I promotion, Double Production[ICON_Production] towards Siege Workshop, Shipyard  [NEWLINE][NEWLINE]Starts at Peace with the Barbarian Tribes(UNIMPLEMENTED, Free Bribes)', 'LOC_CHARADON_TRAITS_DESCRIPTION', 'en_US'),
('Starts with 100 Gold, 50% discount on all unit upgrades. [NEWLINE][NEWLINE]Double yields from pillaging, Combat units have Commando ability (unimplemented)', 'LOC_MAHALA_TRAITS_DESCRIPTION', 'en_US'),
('Starts with an Extra Trait. Changes traits at random. Starts with Arcane, Charismatic, Creative.', 'LOC_PERPENTACH_TRAITS_DESCRIPTION', 'en_US'),
('+2[ICON_Culture] Culture in all Cities, Double Production[ICON_Production] towards Monuments and Carnivals [NEWLINE][NEWLINE]All Summoned units last an additional turn and start with the Combat I promotion.(UNIMPLEMENTED)', 'LOC_KEELYN_TRAITS_DESCRIPTION', 'en_US'),
('Double Production[ICON_Production] towards Settlers, Granaries and Harbors, +3 Housing, [NEWLINE][NEWLINE]Disciple Units have Potency, earning more XP per turn. Changing Policies never causes Anarchy (NOT DONE). Double Production[ICON_Production] towards Religious Temples and Pagan Temple.', 'LOC_JONAS_TRAITS_DESCRIPTION', 'en_US'),
('Combat units start with Combat I promotion, Double Production[ICON_Production] towards Siege Workshop, Shipyard  [NEWLINE][NEWLINE]Half cost Policy Upkeep, Can Build Command Posts, Double Production[ICON_Production] towards Lighthouse and Courthouses', 'LOC_SHEELBA_TRAITS_DESCRIPTION', 'en_US'),
('Arcane Units start with Potency, gaining experience faster. Double Production[ICON_Production] towards Mages Guilds [NEWLINE][NEWLINE]Double yields from pillaging, Combat units have Commando ability (unimplemented)', 'LOC_FAERYL_TRAITS_DESCRIPTION', 'en_US'),
('Combat units start with Combat I promotion, Double Production[ICON_Production] towards Siege Workshop, Shipyard  [NEWLINE][NEWLINE]Double [ICON_GreatPerson]Great People points , Double Production[ICON_Production] towards Elder Councils and Libraries ', 'LOC_ALEXIS_TRAITS_DESCRIPTION', 'en_US'),
('Plots with more than 1 Gold[ICON_Gold] get an additional Gold[ICON_Gold] (NOT DONE). Double Production[ICON_Production] towards Markets and Moneychanger [NEWLINE][NEWLINE]Half cost Policy Upkeep, Can Build Command Posts, Double Production[ICON_Production] towards Lighthouse and Courthouses', 'LOC_FLAUROS_TRAITS_DESCRIPTION', 'en_US'),
('Arcane Units start with Potency, gaining experience faster. Double Production[ICON_Production] towards Mages Guilds [NEWLINE][NEWLINE]All Summoned units last an additional turn and start with the Combat I promotion.(UNIMPLEMENTED)', 'LOC_TEBRYN_TRAITS_DESCRIPTION', 'en_US'),
('50% increased Production[ICON_Production] towards Wonders, Double Production[ICON_Production] speed of Forges [NEWLINE][NEWLINE]Disciple Units have Potency, earning more XP per turn. Changing Policies never causes Anarchy (NOT DONE). Double Production[ICON_Production] towards Religious Temples and Pagan Temple', 'LOC_OS-GABELLA_TRAITS_DESCRIPTION', 'en_US'),
('Double Production[ICON_Production] towards Settlers, Granaries and Harbors, +3 Housing, [NEWLINE][NEWLINE]All Summoned units last an additional turn and start with the Combat I promotion.(UNIMPLEMENTED)', 'LOC_HYBOREM_TRAITS_DESCRIPTION', 'en_US'),
('Cities have +1[ICON_Amenities]Amenity, Units earn XP 33% faster [NEWLINE][NEWLINE]Combat Units have the Homeland ability, making them stronger in friendly territory. Double Production[ICON_Production] towards Archery Ranges, Palisades and Walls', 'LOC_AURIC_TRAITS_DESCRIPTION', 'en_US'),
('Charismatic, Organized', 'LOC_SABATHIEL_TRAITS_NAME', 'en_US'),
('Spiritual, Industrious', 'LOC_CAPRIA_TRAITS_NAME', 'en_US'),
('Organized, Raiders', 'LOC_DECIUS_TRAITS_NAME', 'en_US'),
('Spiritual, Creative', 'LOC_VARN_TRAITS_NAME', 'en_US'),
('Creative, Defender', 'LOC_ETHNE_TRAITS_NAME', 'en_US'),
('Philosophical, Defender -UH', 'LOC_EINION_TRAITS_NAME', 'en_US'),
('Aggressive, Raiders, Ingenuity,', 'LOC_BASIUM_TRAITS_NAME', 'en_US'),
('Financial, Defender', 'LOC_GARRIM_TRAITS_NAME', 'en_US'),
('Industrious, Organized', 'LOC_BEERI_TRAITS_NAME', 'en_US'),
('Expansive, Philosophical', 'LOC_CARDITH_TRAITS_NAME', 'en_US'),
('Defender, Raiders', 'LOC_AMELANCHIER_TRAITS_NAME', 'en_US'),
('Spiritual, Creative', 'LOC_ARENDEL_TRAITS_NAME', 'en_US'),
('Arcane, Expansive', 'LOC_THESSA_TRAITS_NAME', 'en_US'),
('Industrious, Organized', 'LOC_ARTURUS_TRAITS_NAME', 'en_US'),
('Aggressive, Financial, Ingenuity', 'LOC_KANDROS_TRAITS_NAME', 'en_US'),
('Defender, Industrious', 'LOC_SANDALPHON_TRAITS_NAME', 'en_US'),
('Charismatic, Expansive', 'LOC_FALAMAR_TRAITS_NAME', 'en_US'),
('Financial, Raiders', 'LOC_HANNAH_TRAITS_NAME', 'en_US'),
('Industrious, Philosophical', 'LOC_CASSIEL_TRAITS_NAME', 'en_US'),
('Aggressive, Raiders', 'LOC_TASUNKE_TRAITS_NAME', 'en_US'),
('Expansive, Financial', 'LOC_RHOANNA_TRAITS_NAME', 'en_US'),
('Arcane, Organized', 'LOC_VALLEDIA_TRAITS_NAME', 'en_US'),
('Arcane, Philosophical', 'LOC_DAIN_TRAITS_NAME', 'en_US'),
('Aggressive, BARBARIAN', 'LOC_CHARADON_TRAITS_NAME', 'en_US'),
('Ingenuity, Raiders', 'LOC_MAHALA_TRAITS_NAME', 'en_US'),
('Insane', 'LOC_PERPENTACH_TRAITS_NAME', 'en_US'),
('Creative, Summoner', 'LOC_KEELYN_TRAITS_NAME', 'en_US'),
('Expansive, Spiritual', 'LOC_JONAS_TRAITS_NAME', 'en_US'),
('Aggressive, Organized', 'LOC_SHEELBA_TRAITS_NAME', 'en_US'),
('Arcane, Raiders', 'LOC_FAERYL_TRAITS_NAME', 'en_US'),
('Aggressive, Philosophical', 'LOC_ALEXIS_TRAITS_NAME', 'en_US'),
('Financial, Organized', 'LOC_FLAUROS_TRAITS_NAME', 'en_US'),
('Arcane, Summoner', 'LOC_TEBRYN_TRAITS_NAME', 'en_US'),
('Industrious, Spiritual', 'LOC_OS-GABELLA_TRAITS_NAME', 'en_US'),
('Expansive, Summoner', 'LOC_HYBOREM_TRAITS_NAME', 'en_US'),
('Charismatic, Defender', 'LOC_AURIC_TRAITS_NAME', 'en_US');