INSERT OR REPLACE INTO LocalizedText(Tag, Text, Language) VALUES
('LOC_SLTH_POLICY_AGRARIANISM_NAME', 'Agrarianism', 'en_US'),
('LOC_SLTH_POLICY_APPRENTICESHIP_NAME', 'Apprenticeship', 'en_US'),
('LOC_SLTH_POLICY_ARETE_NAME', 'Arete', 'en_US'),
('LOC_SLTH_POLICY_ARISTOCRACY_NAME', 'Aristocracy', 'en_US'),
('LOC_SLTH_POLICY_CASTE_SYSTEM_NAME', 'Caste System', 'en_US'),
('LOC_SLTH_POLICY_CITY_STATES_NAME', 'City States', 'en_US'),
('LOC_SLTH_POLICY_CONQUEST_NAME', 'Conquest', 'en_US'),
('LOC_SLTH_POLICY_CONSUMPTION_NAME', 'Consumption', 'en_US'),
('LOC_SLTH_POLICY_CRUSADE_NAME', 'Crusade', 'en_US'),
('LOC_SLTH_POLICY_DECENTRALIZATION_NAME', 'Decentralization', 'en_US'),
('LOC_SLTH_POLICY_DESPOTISM_NAME', 'Despotism', 'en_US'),
('LOC_SLTH_POLICY_FOREIGN_TRADE_NAME', 'Foreign Trade', 'en_US'),
('LOC_SLTH_POLICY_GOD_KING_NAME', 'God King', 'en_US'),
('LOC_SLTH_POLICY_GUARDIAN_OF_NATURE_NAME', 'Guardian Of Nature', 'en_US'),
('LOC_SLTH_POLICY_GUILDS_NAME', 'Guilds', 'en_US'),
('LOC_SLTH_POLICY_LIBERTY_NAME', 'Liberty', 'en_US'),
('LOC_SLTH_POLICY_MERCANTILISM_NAME', 'Mercantilism', 'en_US'),
('LOC_SLTH_POLICY_MILITARY_STATE_NAME', 'Military State', 'en_US'),
('LOC_SLTH_POLICY_NATIONHOOD_NAME', 'Nationhood', 'en_US'),
('LOC_SLTH_POLICY_PACIFISM_NAME', 'Pacifism', 'en_US'),
('LOC_SLTH_POLICY_RELIGION_NAME', 'Religion', 'en_US'),
('LOC_SLTH_POLICY_REPUBLIC_NAME', 'Republic', 'en_US'),
('LOC_SLTH_POLICY_SACRIFICE_THE_WEAK_NAME', 'Sacrifice The Weak', 'en_US'),
('LOC_SLTH_POLICY_SCHOLARSHIP_NAME', 'Scholarship', 'en_US'),
('LOC_SLTH_POLICY_SLAVERY_NAME', 'Slavery', 'en_US'),
('LOC_SLTH_POLICY_SOCIAL_ORDER_NAME', 'Social Order', 'en_US'),
('LOC_SLTH_POLICY_THEOCRACY_NAME', 'Theocracy', 'en_US'),
('LOC_SLTH_POLICY_TRIBALISM_NAME', 'Tribalism', 'en_US'),
('LOC_SLTH_POLICY_AGRARIANISM_DESCRIPTION', '+1[ICON_Housing] Housing in all cities. +1 [ICON_Food] Food for each FARM. -1 [ICON_Production] Production for each FARM.', 'en_US'),
('LOC_SLTH_POLICY_APPRENTICESHIP_DESCRIPTION', '+2 experience to all trained Military Units. -10% Bonus Production to Military Units.', 'en_US'),
('LOC_SLTH_POLICY_ARETE_DESCRIPTION', '+1 [ICON_Production] Production for each MINE.', 'en_US'),
('LOC_SLTH_POLICY_ARISTOCRACY_DESCRIPTION', '-1 [ICON_Food] Food for each FARM. +2 [ICON_Gold] Gold for each FARM.', 'en_US'),
('LOC_SLTH_POLICY_CASTE_SYSTEM_DESCRIPTION', 'Builders start with +2 charges.', 'en_US'),
('LOC_SLTH_POLICY_CITY_STATES_DESCRIPTION', 'Accumulate 25% less war weariness than usual. -20% [ICON_Culture] Culture in all Cities.', 'en_US'),
('LOC_SLTH_POLICY_CONQUEST_DESCRIPTION', '+2 Experience points. All military units cost food, but that wasn`t implemented.', 'en_US'),
('LOC_SLTH_POLICY_CONSUMPTION_DESCRIPTION', '20% [ICON_Gold] Gold in all Cities.  Market gives +1 [ICON_Amenities] Amenity.  Tavern gives +1 [ICON_Amenities] Amenity.  Theatre gives +1 [ICON_Amenities] Amenity.', 'en_US'),
('LOC_SLTH_POLICY_CRUSADE_DESCRIPTION', 'Accumulate -75% less war weariness than usual.', 'en_US'),
('LOC_SLTH_POLICY_DECENTRALIZATION_DESCRIPTION', 'Does nothing', 'en_US'),
('LOC_SLTH_POLICY_DESPOTISM_DESCRIPTION', 'Accumulate -50% less war weariness than usual.', 'en_US'),
('LOC_SLTH_POLICY_FOREIGN_TRADE_DESCRIPTION', '+1 Trade Route Capacity. -10% [ICON_Gold] Gold in all Cities. 20% [ICON_Culture] Culture in all Cities. +1 Trade Route Capacity per coastal city.', 'en_US'),
('LOC_SLTH_POLICY_GOD_KING_DESCRIPTION', '50% [ICON_Production] Production in Capital City. 50% [ICON_Gold] Gold in Capital City.', 'en_US'),
('LOC_SLTH_POLICY_GUARDIAN_OF_NATURE_DESCRIPTION', '+5[ICON_Housing] Housing in all cities. -10% Bonus Production to Military Units.  Grove gives +2 [ICON_Amenities] Amenity.', 'en_US'),
('LOC_SLTH_POLICY_GUILDS_DESCRIPTION', 'Can spend gold to finish production, Unlimited merchants, sages, artists and engineers', 'en_US'),
('LOC_SLTH_POLICY_LIBERTY_DESCRIPTION', 'Accumulate 50% less war weariness than usual. 100% [ICON_Culture] Culture in all Cities.', 'en_US'),
('LOC_SLTH_POLICY_MERCANTILISM_DESCRIPTION', 'Foreign Trade provides 0 yields. 20% [ICON_Gold] Gold in all Cities.  Market gives +1 [ICON_Amenities] Amenity.', 'en_US'),
('LOC_SLTH_POLICY_MILITARY_STATE_DESCRIPTION', '+15% Bonus Production to Military Units. -25% [ICON_Culture] Culture in all Cities.', 'en_US'),
('LOC_SLTH_POLICY_NATIONHOOD_DESCRIPTION', '+10% Bonus Production to Military Units. Accumulate -25% less war weariness than usual.  Training Yard gives +1 [ICON_Amenities] Amenity.', 'en_US'),
('LOC_SLTH_POLICY_PACIFISM_DESCRIPTION', '50% Great Person Great People points generated per turn. -20% Bonus Production to Military Units. Accumulate 25% less war weariness than usual.', 'en_US'),
('LOC_SLTH_POLICY_RELIGION_DESCRIPTION', '10% [ICON_Culture] Culture in all Cities.  Temple of Kilmorph gives +1 [ICON_Amenities] Amenity.  Temple of Leaves gives +1 [ICON_Amenities] Amenity.  Temple of The Order gives +1 [ICON_Amenities] Amenity.  Temple of The Overlords gives +1 [ICON_Amenities] Amenity.  Temple of The Veil gives +1 [ICON_Amenities] Amenity.  Temple of The Empyrean gives +1 [ICON_Amenities] Amenity.', 'en_US'),
('LOC_SLTH_POLICY_REPUBLIC_DESCRIPTION', '25% Great Person Great People points generated per turn. 20% [ICON_Culture] Culture in all Cities.', 'en_US'),
('LOC_SLTH_POLICY_SACRIFICE_THE_WEAK_DESCRIPTION', '-20% Great Person Great People points generated per turn. -4[ICON_Housing] Housing in all cities. 10% [ICON_Gold] Gold in all Cities.', 'en_US'),
('LOC_SLTH_POLICY_SCHOLARSHIP_DESCRIPTION', 'Accumulate 20% less war weariness than usual. 10% [ICON_Science] Science in all Cities.  Library gives +1 [ICON_Amenities] Amenity.', 'en_US'),
('LOC_SLTH_POLICY_SLAVERY_DESCRIPTION', '+1 [ICON_Production] Production for each QUARRY. Units now have a chance of capturing a builder from defeating major civilization units.', 'en_US'),
('LOC_SLTH_POLICY_SOCIAL_ORDER_DESCRIPTION', 'Courthouse gives +1 [ICON_Amenities] Amenity.  Basilica gives +1 [ICON_Amenities] Amenity.', 'en_US'),
('LOC_SLTH_POLICY_TRIBALISM_DESCRIPTION', 'Does nothing', 'en_US');