INSERT OR REPLACE INTO LocalizedText(Tag, Text, Language) VALUES
('LOC_SUMMON_AIR_ELEMENTAL_DESCRIPTION', 'Summon Air Elemental', 'en_US'),
('LOC_SUMMON_DJINN_DESCRIPTION', 'Summon Djinn', 'en_US'),
('LOC_SUMMON_EYE_DESCRIPTION', 'Summon Floating Eye', 'en_US'),
('LOC_SUMMON_EARTH_ELEMENTAL_DESCRIPTION', 'Summon Earth Elemental', 'en_US'),
('LOC_SUMMON_FIRE_ELEMENTAL_DESCRIPTION', 'Summon Fire Elemental', 'en_US'),
('LOC_SUMMON_FIREBALL_DESCRIPTION', 'Summon Fireball', 'en_US'),
('LOC_SUMMON_EINHERJAR_DESCRIPTION', 'Summon Einherjar', 'en_US'),
('LOC_SUMMON_AUREALIS_DESCRIPTION', 'Summon Aurealis', 'en_US'),
('LOC_SUMMON_PIT_BEAST_DESCRIPTION', 'Summon Pit Beast', 'en_US'),
('LOC_SUMMON_MISTFORM_DESCRIPTION', 'Summon Mistform', 'en_US'),
('LOC_SUMMON_SPECTRE_DESCRIPTION', 'Summon Spectre', 'en_US'),
('LOC_SUMMON_WATER_ELEMENTAL_DESCRIPTION', 'Summon Water Elemental', 'en_US'),
('LOC_SUMMON_WRAITH_DESCRIPTION', 'Summon Wraith', 'en_US'),
('LOC_SUMMON_FLESH_GOLEM_DESCRIPTION', 'Summon Flesh Golem', 'en_US'),
('LOC_SUMMON_SKELETON_DESCRIPTION', 'Summon Skeleton', 'en_US'),
('LOC_SUMMON_IRA_DESCRIPTION', 'Summon Ira', 'en_US'),
('LOC_GRANT_STONESKIN_SELF_DESCRIPTION', 'Grants this unit Stoneskin. Increased Combat Strength.', 'en_US'),
('LOC_GRANT_WATERWALKING_SELF_DESCRIPTION', 'Grants this unit Waterwalking. No penalties to embarking or disembarking.', 'en_US'),
('LOC_GRANT_SPELL_STAFF_SELF_DESCRIPTION', 'Craft Spell Staff, an Equipment that increases Arcane units experience, and can be used up to cast again.', 'en_US'),
('LOC_GRANT_ENCHANTED_BLADE_AOE_DESCRIPTION', 'Grant adjacent melee units the Enchanted Blade buff, granting +4 [ICON_STRENGTH] Combat Strength. Removes Rusted.', 'en_US'),
('LOC_GRANT_FAIR_WINDS_DESCRIPTION', 'Grant adjacent naval units the Fair Winds buff, granting +1 [ICON_MOVEMENT]Movement. 25% chance of wearing off per turn.', 'en_US'),
('LOC_GRANT_HASTE_AOE_DESCRIPTION', 'Grant adjacent alive units the Haste buff, granting +1 [ICON_MOVEMENT]Movement for a turn.', 'en_US'),
('LOC_GRANT_REGENERATION_AOE_DESCRIPTION', 'Grant adjacent alive units the Regeneration buff, granting increased healing until they are full health.', 'en_US'),
('LOC_GRANT_DANCE_OF_BLADES_AOE_DESCRIPTION', 'Grant adjacent units the Dance of Blades buff, granting +4 [ICON_STRENGTH] Combat Strength for a turn.', 'en_US'),
('LOC_GRANT_FLAMING_ARROWS_AOE_DESCRIPTION', 'Grant adjacent Ranged units the Flaming Arrows buff, granting +6 [ICON_RESOURCE_MANA_FIRE]Fire Strength.', 'en_US'),
('LOC_GRANT_LOYALTY_AOE_DESCRIPTION', 'Grant adjacent alive units the Loyalty buff, cannot be captured*, and resist the Charm debuff*.', 'en_US'),
('LOC_GRANT_VALOR_AOE_DESCRIPTION', 'Grant adjacent alive units the Valor buff, granting increased experience. Also grants 10% Magic Resist*.', 'en_US'),
('LOC_GRANT_POISONED_BLADE_AOE_DESCRIPTION', 'Grant adjacent Recon units the Poisoned buff, granting +6 Poison Strength. ', 'en_US'),
('LOC_GRANT_TREETOP_DEFENSE_AOE_DESCRIPTION', 'Fully fortifies adjacent units on Forest, Jungle or Ancient Forest.', 'en_US'),
('LOC_GRANT_BLUR_AOE_DESCRIPTION', 'Grant adjacent units the Blur buff, granting +4 [ICON_STRENGTH] Combat Strength. 50% chance of wearing off each turn.', 'en_US'),
('LOC_GRANT_SHADOWWALK_AOE_DESCRIPTION', 'Grant adjacent units the ShadowWalk buff, ignoring building defenses when attacking a city. 25% chance of wearing off each turn.', 'en_US'),
('LOC_GRANT_COURAGE_AOE_DESCRIPTION', 'Grant adjacent units the Courage buff, increasing healing. Immune to Fear*', 'en_US'),
('LOC_GRANT_MUTATION_AOE_DESCRIPTION', 'Grant adjacent units the one time Mutation effect. Grants a number of positive and negative promotions and abilities, at random.', 'en_US'),
('LOC_DEBUFF_CHARMED_AOE_DESCRIPTION', 'Debuff adjacent enemies with the Charmed debuff. Charmed units cannot attack you, 20% chance of wearing off each turn.', 'en_US'),
('LOC_DEBUFF_RUSTED_AOE_DESCRIPTION', 'Debuff adjacent enemies with the Rusted debuff. Removes weapon upgrades and reduces [ICON_STRENGTH]Combat Strength by 4. Wears off on entering a city with a Forge.', 'en_US'),
('LOC_DEBUFF_BLINDED_AOE_DESCRIPTION', 'Debuff adjacent enemies with the Blinded debuff. Blinded units cannot move.* Wears off in two turns.', 'en_US'),
('LOC_DEBUFF_SLOW_AOE_DESCRIPTION', 'Debuff adjacent enemies with the Slow debuff. Reduces [ICON_MOVEMENT]Movement by 1. 30% chance of wearing off each turn.', 'en_US'),
('LOC_TERRAIN_CHANGE_SPRING_DESCRIPTION', 'Converts Desert terrain under the user to Plains. Extinguishes adjacent fires*.', 'en_US'),
('LOC_TERRAIN_CHANGE_SCORCH_DESCRIPTION', 'Converts terrain under the user. Snow becomes Tundra, Tundra becomes Plains, Plains becomes Desert, Marsh becomes Grassland*.', 'en_US'),
('LOC_TERRAIN_CHANGE_VITALIZE_DESCRIPTION', 'Converts terrain under the user. Snow becomes Tundra, Tundra becomes Plains, Plains becomes Grassland, empty Grassland gains a New Forest*.', 'en_US'),
('LOC_AOE_DAMAGE_MAELSTROM_DESCRIPTION', 'Deals damage to adjacent hostile units. Deals 10-40 damage. Cannot reduce a unit to below 40 health.', 'en_US'),
('LOC_AOE_DAMAGE_DESTROY_UNDEAD_DESCRIPTION', 'Deals damage to adjacent hostile Undead units. Deals 10-40 damage. Cannot reduce a unit to below 40 health.', 'en_US'),
('LOC_AOE_DAMAGE_WITHER_DESCRIPTION', 'Deals damage to adjacent units. Deals 10-40 damage. Cannot reduce a unit to below 40 health. Also debuffs units with Withered, reducing Combat Strength, Healing and Experience gained.*', 'en_US'),
('LOC_AOE_DAMAGE_SNOWFALL_DESCRIPTION', 'Deals damage to adjacent hostile units. Deals 30-50 damage. Cannot reduce a unit to below 10 health. Converts adjacent tiles to Snow Terrain*.', 'en_US'),
('LOC_WONDER_DESCRIPTION', 'Jesus take the wheel! Casts up to 5 random spells*.', 'en_US'),
('LOC_BLAZE_DESCRIPTION', 'Sets Forest/Jungle on fire*.', 'en_US'),
('LOC_RESURRECTION_DESCRIPTION', 'Cast normally, requires your Hero unit to have died.Takes 7 turns, then resurrects your dead Hero unit*. Cast on a Graveyard, creates a Champion with 30 Experience*.', 'en_US'),
('LOC_DOMINATION_DESCRIPTION', 'Targets an adjacent hostile unit. Converts it to your side*. Can be resisted. If fails, lose ability to cast this spell*.', 'en_US'),
('LOC_TRUST_DESCRIPTION', 'Permanent diplomatic bonus with all leaders*. Can only be cast once per game.', 'en_US'),
('LOC_SANCTIFY_DESCRIPTION', 'Clears City Ruins, reducing the AC counter.* Cleanses Hell Terrain back to normal.* Cast on Graveyards to summon a permanent Host of the Einherjar.*', 'en_US'),
('LOC_DISPELL_MAGIC_DESCRIPTION', 'Removes all magical Buffs from adjacent enemies, and debuffs from your adjacent units. Converts Mana Resources back to raw Mana.', 'en_US'),
('LOC_FEED_ON_CITY_DESCRIPTION', 'Feeds on your city, reducing the population by one, and decreasing Amenities. Gains Experience.', 'en_US'),
('LOC_GRANT_LION_CAGE_DESCRIPTION', 'Converts this unit into a Lion Cage Building in a city with a Carnival. Grants +1 [ICON_Amenities]Amenity and +3 [ICON_Culture]Culture.', 'en_US'),
('LOC_GRANT_WOLF_PEN_DESCRIPTION', 'Converts this unit into a Wolf Pen Building in a city with a Carnival. Grants +2 [ICON_Culture]Culture.', 'en_US'),
('LOC_GRANT_DANCING_BEAR_DESCRIPTION', 'Converts this unit into a Dancing Bear Building in a city. Grants +1 [ICON_Amenities]Amenity and +3 [ICON_Culture]Culture.', 'en_US'),
('LOC_GRANT_GORILLA_CAGE_DESCRIPTION', 'Converts this unit into a Gorilla Cage Building in a city with a Carnival. Grants +1 [ICON_Amenities]Amenity and +3 [ICON_Culture]Culture.', 'en_US'),
('LOC_GRANT_SPIDER_PEN_DESCRIPTION', 'Converts this unit into a Spider Pen Building. Grants +1 [ICON_RESOURCE_SILK] Silk.', 'en_US'),
('LOC_GRANT_TIGER_CAGE_DESCRIPTION', 'Converts this unit into a Tiger Cage Building in a city with a Carnival. Grants +1 [ICON_Amenities]Amenity and +3 [ICON_Culture]Culture.', 'en_US'),
('LOC_GRANT_FREAK_SHOW_DESCRIPTION', 'Converts this unit into a Freak Show Building, which allows adding Slave cages to this city. It also grants +1 [ICON_Amenities]Amenity, +1 [ICON_GreatPerson]Great Bard point and +2 [ICON_Culture]Culture.', 'en_US'),
('LOC_GRANT_BURNING_BLOOD_DESCRIPTION', 'Grants this unit the Burning Blood Buff. +4[ICON_STRENGTH]Combat Strength, +1 [ICON_MOVEMENT]Movement. Immune to Fear*. 10% chance of wearing off per turn. 10% chance of converting to Barbarian.', 'en_US'),
('LOC_CONSUME_SOULS_DESCRIPTION', 'Feeds on your city, reducing the population by one, and decreasing Amenities. Allows casting again this turn.', 'en_US'),
('LOC_GRANT_ELF_CAGE_DESCRIPTION', 'Converts this unit into a Elf Cage Building in a city with a Freak Show. Grants +1 [ICON_Amenities]Amenity, +1 [ICON_GreatPerson]Great Bard point and +1 [ICON_Culture]Culture.', 'en_US'),
('LOC_GRANT_HUMAN_CAGE_DESCRIPTION', 'Converts this unit into a Human Cage Building in a city with a Freak Show. Grants +1 [ICON_Amenities]Amenity, +1 [ICON_GreatPerson]Great Bard point and +1 [ICON_Culture]Culture.', 'en_US'),
('LOC_GRANT_ORC_CAGE_DESCRIPTION', 'Converts this unit into a Orc Cage Building in a city with a Freak Show. Grants +1 [ICON_Amenities]Amenity, +1 [ICON_GreatPerson]Great Bard point and +1 [ICON_Culture]Culture.', 'en_US'),
('LOC_GRANT_DWARF_CAGE_DESCRIPTION', 'Converts this unit into a Dwarf Cage Building in a city with a Freak Show. Grants +1 [ICON_Amenities]Amenity, +1 [ICON_GreatPerson]Great Bard point and +1 [ICON_Culture]Culture.', 'en_US'),
('LOC_GRANT_SUPER_SPECIALIST_DESCRIPTION', 'Converts this Great Person into a Super Specialist in this city, according to their Class. Super Specialists grant yields to the city.', 'en_US'),
('LOC_GRANT_GOLDEN_AGE_DESCRIPTION', 'Consumes this Great Person to instantly enter a Golden Age for 10 turns. Will require 1 additional Great Person per Golden Age granted this way.', 'en_US'),
('LOC_GRANT_CODE_OF_JUNIL_DESCRIPTION', 'Consumes this Great Person to build the Code of Junil Wonder in The Order''s Holy City.', 'en_US'),
('LOC_GRANT_DIES_DEI_DESCRIPTION', 'Consumes this Great Person to build Dies Dei Wonder in The Empyrean''s Holy City.', 'en_US'),
('LOC_GRANT_TABLETS_OF_BAMBUR_DESCRIPTION', 'Consumes this Great Person to build the Tablets of Bambur Wonder in the Rune of Kilmorph''s Holy City.', 'en_US'),
('LOC_GRANT_SONG_OF_AUTUMN_DESCRIPTION', 'Consumes this Great Person to build the Song of Autumn Wonder in the Fellowship of the Leaves'' Holy City.', 'en_US'),
('LOC_GRANT_THE_NECRONOMICON_DESCRIPTION', 'Consumes this Great Person to build The Necronomicon Wonder in the Octopus Overlords'' Holy City.', 'en_US'),
('LOC_GRANT_NOX_NOCTIS_DESCRIPTION', 'Consumes this Great Person to build the Nox Noctis Wonder in the Council of Esus'' Holy City.', 'en_US'),
('LOC_GRANT_STIGMATA_ON_THE_UNBORN_DESCRIPTION', 'Consumes this Great Person to build the Stigmata upon the Unborn Wonder in the Ashen Veil''s Holy City.', 'en_US'),
('LOC_CONSUME_BLOODPET_DESCRIPTION', 'A Vampire can consume a friendly adjacent Warrior to act again this turn.', 'en_US'),
('LOC_REPAIR_GOLEM_DESCRIPTION', 'Heal adjacent targeted Golem unit.', 'en_US'),
('LOC_CAST_MIRROR_DESCRIPTION', 'Creates a illusionary copy of this unit that lasts a turn. The copy cannot reduce a unit''s health below 1*.', 'en_US'),
('LOC_READ_GRIMOIRE_DESCRIPTION', 'Casts a random spell, positive... or negative.*', 'en_US'),
('LOC_BREAK_STAFF_DESCRIPTION', 'Consumes the SpellStaff equipment, allowing your unit to cast again.', 'en_US'),
('LOC_SPREAD_ESUS_DESCRIPTION', 'Spreads the Council of Esus religion to adjacent cities for a price of 25[ICON_GOLD] Gold.', 'en_US'),
('LOC_ESCAPE_DESCRIPTION', 'Teleports this unit to your capital.', 'en_US'),
('LOC_SEVER_SOUL_DESCRIPTION', 'Summons a permanent Divided Soul unit. This unit can cast a spell to be consumed, teleporting this unit to its location.', 'en_US'),
('LOC_CALL_FORM_DESCRIPTION', 'Consumes this unit, teleporting the owner of this summon to this location.', 'en_US'),
('LOC_SUMMON_PUPPET_DESCRIPTION', 'Summons a Puppet that inherits the summoner''s T1 spells.', 'en_US'),
('LOC_GRANT_HERALDS_CALL_DESCRIPTION', 'Grant adjacent alive units the Burning Blood buff, +4[ICON_STRENGTH]Combat Strength, +1 [ICON_MOVEMENT]Movement. Immune to Fear*. 10% chance of wearing off per turn. 10% chance of converting to Barbarian.', 'en_US'),
('LOC_GRANT_MORALE_DESCRIPTION', 'Grant adjacent alive units the Morale buff. Probably gonna make this a passive soon.', 'en_US'),
('LOC_TEACH_SPELLS_DESCRIPTION', 'Grants adjacent units random T1 spell promotions Govannon has*.', 'en_US'),
('LOC_ENTANGLE_DESCRIPTION', 'Debuff a targeted adjacent enemy with the Held debuff, preventing Movement.*', 'en_US'),
('LOC_SPORES_DESCRIPTION', 'Debuff a targeted adjacent enemy with the Sleep debuff, preventing any action next turn. Cannot be resisted.*', 'en_US'),
('LOC_CRUSH_DESCRIPTION', 'Damage a targeted adjacent enemy. Deal 40-50 damage. Cannot reduce a unit to below 20 health. Cannot be resisted.', 'en_US'),
('LOC_HASTURS_RAZOR_DESCRIPTION', 'Deals damage to adjacent units. Cannot reduce a unit to below 10 health. Some randomness im unsure about*', 'en_US'),
('LOC_PILLAR_OF_FIRE_DESCRIPTION', 'Damage a targeted adjacent enemy. Deal 40(?) Fire damage. Cannot reduce a unit to below 10 health.', 'en_US'),
('LOC_MESMERISE_ANIMAL_DESCRIPTION', 'Convert an adjacent hostile Animal unit to your side. Can be resisted.', 'en_US'),
('LOC_HEAL_FULL_ALLY_DESCRIPTION', 'Heals a targeted adjacent unit to full health.', 'en_US'),
('LOC_GRANT_VAMPIRISM_DESCRIPTION', 'Grants an eligible adjacent friendly unit the gift of Vampirism. Unit must normally be at least level 6.', 'en_US'),
('LOC_BECOME_SHADE_DESCRIPTION', 'Converts this unit into a Shade, who can be settled in a city as any SuperSpecialist.', 'en_US'),
('LOC_ABSORB_UNIT_DESCRIPTION', 'Consumes the target unit. If it has any promotions or abilities that the unit does not have, gain those abilities or promotions.*', 'en_US'),
('LOC_ARENA_FIGHT_DESCRIPTION', 'Unit battles in the Arena, granting the city amenities for a short time.* The unit either gains experience or dies.*', 'en_US'),
('LOC_SACRIFICE_ALTAR_DESCRIPTION', 'Sacrifices the unit, granting Science.', 'en_US'),
('LOC_DROWN_WARRIOR_DESCRIPTION', 'Converts the unit into a Drown*. Requires a Temple of the Overlords and the Octopus Overlords State Religion.', 'en_US'),
('LOC_KIDNAP_GREAT_PERSON_DESCRIPTION', 'Has a chance to remove a settled Super Specialist from the city and create the corresponding Great Person under your control.* Chance of success is 8 x Base Strength of Caster. Declares War if unsuccessful*. Has a 50% chance Unit is killed upon failure*. Otherwise Unit is sent to your Capital*. ', 'en_US'),
('LOC_SUMMON_SAND_LION_DESCRIPTION', 'Summons a Sand Lion unit. Requires Desert Terrain, Malakim, and a unit with Channelling II.', 'en_US'),
('LOC_LOKI_DISRUPT_CITY_DESCRIPTION', 'Reduces Loyalty in adjacent enemy city.*', 'en_US'),
('LOC_LOKI_ENTERTAIN_CITY_DESCRIPTION', 'Increases Amenities in adjacent city. Grants Gold equal to the population of the city.*', 'en_US'),
('LOC_CORLINDALE_PEACE_DESCRIPTION', 'Forces Peace between the owner and all players. Halfs the Armageddon count. Kills the user.', 'en_US'),
('LOC_PLACE_BARNAXUS_PIECES_DESCRIPTION', 'Places the Pieces of Barnaxus in a city, allowing Barnaxus to be rebuilt.', 'en_US'),
('LOC_PLACE_GRIMOIRE_DESCRIPTION', 'Converts the user''s Infernal Grimoire equipment into the Infernal Grimoire Building.', 'en_US'),
('LOC_PLACE_CROWN_DESCRIPTION', 'Converts the user''s Crown of Ahkarien equipment into the Crown of Ahkarien Building.', 'en_US'),
('LOC_PLACE_LYRE_DESCRIPTION', 'Converts the user''s Sylivan''s Lyre equipment into the Sylivan''s Perfect Lyre Building.', 'en_US'),
('LOC_HEAL_SIRONA_DESCRIPTION', 'Once per turn, heal this unit, if you have the Shrine of Sirona, and have not healed another unit.', 'en_US'),
('LOC_BECOME_LICH_DESCRIPTION', 'Converts this unit into a Lich.', 'en_US'),
('LOC_SUMMON_BALOR_DESCRIPTION', 'Summon a Balor Unit.', 'en_US'),
('LOC_SUMMON_KRAKEN_DESCRIPTION', 'Summon the naval Kraken unit.', 'en_US'),
('LOC_EARTHQUAKE_DESCRIPTION', 'Deals damage to adjacent hostile units* Pillages Improvements and Buildings adjacent*', 'en_US'),
('LOC_SUMMON_TIGER_DESCRIPTION', 'Summon a permanent Tiger unit.', 'en_US'),
('LOC_BLOOM_DESCRIPTION', 'Upgrades features on the user''s tile. Makes empty/Jungle into a New Forest*. Makes a New Forest into a Forest*. Makes a Forest into a Ancient Forest.', 'en_US'),
('LOC_REVELATION_DESCRIPTION', 'Destroys hostile illusions & removes hidden nationality, hidden and invisible from hostile units within 3 tiles*', 'en_US'),
('LOC_GRANT_SHIELD_OF_FAITH_DESCRIPTION', 'Grant adjacent units the Shield of Faith buff, +2 [ICON_STRENGTH] Combat Strength. Removed after combat.', 'en_US'),
('LOC_TSUNAMI_DESCRIPTION', 'Deals damage to adjacent hostile units next to Coast Terrain*.', 'en_US'),
('LOC_RING_OF_FLAMES_DESCRIPTION', 'Deals damage to adjacent hostile units*.', 'en_US'),
('LOC_PLACE_HORDE_DESCRIPTION', 'Converts the user''s Dragon''s Horde equipment into the Dragon''s Horde Building.', 'en_US'),
('LOC_PLACE_CAULDRON_DESCRIPTION', 'Converts the user''s Mokka''s Cauldron equipment into the Mokka''s Cauldron  Building.', 'en_US'),
('LOC_TAKE_EQUIPMENT_DESCRIPTION', 'Picks up equipment from adjacent unit.', 'en_US');