INSERT OR REPLACE INTO LocalizedText(Tag, Text, Language) VALUES
('LOC_ABILITY_HERO_NAME', 'Hero', 'en_US'),
('LOC_SLTH_CHANNELING_ABILITY_PROMOTION_CHANNELING1_NAME', 'Channeling Promotion Channeling1', 'en_US'),
('LOC_SLTH_CHANNELING_ABILITY_PROMOTION_CHANNELING2_NAME', 'Channeling Promotion Channeling2', 'en_US'),
('LOC_SLTH_CHANNELING_ABILITY_PROMOTION_CHANNELING3_NAME', 'Channeling Promotion Channeling3', 'en_US'),
('LOC_SLTH_CHANNELING_ABILITY_PROMOTION_DEXTEROUS_NAME', 'Channeling Promotion Dexterous', 'en_US'),
('LOC_SLTH_DARK_ELF_ABILITY_FEATUREATTACKS_NAME', 'Dark Elf Featureattacks', 'en_US'),
('LOC_SLTH_DEMON_ABILITY_HELL_TERRAIN_STRENGTH_NAME', 'Hell Terrain Strength', 'en_US'),
('LOC_SLTH_DEMON_ABILITY_TERRAINATTACKS_NAME', 'Demon Terrainattacks', 'en_US'),
('LOC_SLTH_DEMON_ABILITY_TERRAINDEFENSES_NAME', 'Demon Terraindefenses', 'en_US'),
('LOC_SLTH_ELF_ABILITY_FEATUREATTACKS_NAME', 'Elf Featureattacks', 'en_US'),
('LOC_SLTH_ELF_ABILITY_FEATUREDOUBLEMOVES_NAME', 'Promotion Elf Featuredoublemoves', 'en_US'),
('LOC_SLTH_FROSTLING_ABILITY_TERRAINATTACKS_NAME', 'Frostling Terrainattacks', 'en_US'),
('LOC_SLTH_FROSTLING_ABILITY_TERRAINDEFENSES_NAME', 'Frostling Terraindefenses', 'en_US'),
('LOC_SLTH_LIZARDMAN_ABILITY_MARSH_DOUBLE_MOVES_NAME', 'Promotion Lizardman Terraindoublemoves', 'en_US'),
('LOC_SLTH_LIZARDMAN_ABILITY_MARSH_STRENGTH_NAME', 'Lizardman Terrainattacks', 'en_US'),
('LOC_SLTH_LIZARDMAN_ABILITY_TERRAINDEFENSES_NAME', 'Lizardman Terraindefenses', 'en_US'),
('LOC_SLTH_NIGHTMARE_ABILITY_HELL_TERRAIN_STRENGTH_NAME', 'Nightmare Terrainattacks', 'en_US'),
('LOC_SLTH_NIGHTMARE_ABILITY_TERRAINDEFENSES_NAME', 'Nightmare Terraindefenses', 'en_US'),
('LOC_SLTH_NOMAD_ABILITY_DESERT_STRENGTH_NAME', 'Nomad Desert Power', 'en_US'),
('LOC_SLTH_NOMAD_ABILITY_TERRAINDEFENSES_NAME', 'Nomad Terraindefenses', 'en_US'),
('LOC_SLTH_ORC_ABILITY_JUNGLE_ATTACKS_NAME', 'Orc Featureattacks', 'en_US'),
('LOC_SLTH_PROMOTION_DARK_ELF_ABILITY_FEATUREDOUBLEMOVES_NAME', 'Promotion Dark Elf Featuredoublemoves', 'en_US'),
('LOC_SLTH_PROMOTION_DWARF_ABILITY_HILLS_DOUBLE_MOVE_NAME', 'Hill Affinity', 'en_US'),
('LOC_SLTH_PROMOTION_GUERILLA2_ABILITY_HILLS_DOUBLE_MOVE_NAME', 'Promotion Guerilla2 HILLS_DOUBLE_MOVE', 'en_US'),
('LOC_SLTH_PROMOTION_NOMAD_ABILITY_TERRAINDOUBLEMOVES_NAME', 'Promotion Nomad Terraindoublemoves', 'en_US'),
('LOC_SLTH_PROMOTION_WOODSMAN2_ABILITY_FEATUREDOUBLEMOVES_NAME', 'Promotion Woodsman2 Featuredoublemoves', 'en_US'),
('LOC_SLTH_RESOURCE_MANA_AIR_ABILITY_GRANT_SPELL_NAME', 'Resource Mana Air Grant Spell', 'en_US'),
('LOC_SLTH_RESOURCE_MANA_BODY_ABILITY_GRANT_SPELL_NAME', 'Resource Mana Body Grant Spell', 'en_US'),
('LOC_SLTH_RESOURCE_MANA_CHAOS_ABILITY_GRANT_SPELL_NAME', 'Resource Mana Chaos Grant Spell', 'en_US'),
('LOC_SLTH_RESOURCE_MANA_DEATH_ABILITY_GRANT_SPELL_NAME', 'Resource Mana Death Grant Spell', 'en_US'),
('LOC_SLTH_RESOURCE_MANA_EARTH_ABILITY_GRANT_SPELL_NAME', 'Resource Mana Earth Grant Spell', 'en_US'),
('LOC_SLTH_RESOURCE_MANA_ENCHANTMENT_ABILITY_GRANT_SPELL_NAME', 'Resource Mana Enchantment Grant Spell', 'en_US'),
('LOC_SLTH_RESOURCE_MANA_ENTROPY_ABILITY_GRANT_SPELL_NAME', 'Resource Mana Entropy Grant Spell', 'en_US'),
('LOC_SLTH_RESOURCE_MANA_FIRE_ABILITY_GRANT_SPELL_NAME', 'Resource Mana Fire Grant Spell', 'en_US'),
('LOC_SLTH_RESOURCE_MANA_ICE_ABILITY_GRANT_SPELL_NAME', 'Resource Mana Ice Grant Spell', 'en_US'),
('LOC_SLTH_RESOURCE_MANA_LAW_ABILITY_GRANT_SPELL_NAME', 'Resource Mana Law Grant Spell', 'en_US'),
('LOC_SLTH_RESOURCE_MANA_LIFE_ABILITY_GRANT_SPELL_NAME', 'Resource Mana Life Grant Spell', 'en_US'),
('LOC_SLTH_RESOURCE_MANA_METAMAGIC_ABILITY_GRANT_SPELL_NAME', 'Resource Mana Metamagic Grant Spell', 'en_US'),
('LOC_SLTH_RESOURCE_MANA_MIND_ABILITY_GRANT_SPELL_NAME', 'Resource Mana Mind Grant Spell', 'en_US'),
('LOC_SLTH_RESOURCE_MANA_NATURE_ABILITY_GRANT_SPELL_NAME', 'Resource Mana Nature Grant Spell', 'en_US'),
('LOC_SLTH_RESOURCE_MANA_SHADOW_ABILITY_GRANT_SPELL_NAME', 'Resource Mana Shadow Grant Spell', 'en_US'),
('LOC_SLTH_RESOURCE_MANA_SPIRIT_ABILITY_GRANT_SPELL_NAME', 'Resource Mana Spirit Grant Spell', 'en_US'),
('LOC_SLTH_RESOURCE_MANA_SUN_ABILITY_GRANT_SPELL_NAME', 'Resource Mana Sun Grant Spell', 'en_US'),
('LOC_SLTH_RESOURCE_MANA_WATER_ABILITY_GRANT_SPELL_NAME', 'Resource Mana Water Grant Spell', 'en_US'),
('LOC_SLTH_WINTERBORN_ABILITY_TERRAINDEFENSES_NAME', 'Winterborn Terraindefenses', 'en_US'),
('LOC_SLTH_WINTERBORN_ABILITY_TUNDRA_SNOW_STRENGTH_NAME', 'Winterborn Terrainattacks', 'en_US'),
('LOC_SLTH_WOODSMAN1_ABILITY_FEATUREATTACKS_NAME', 'Woodsman1 Featureattacks', 'en_US'),
('LOC_SLTH_WOODSMAN1_ABILITY_FEATUREDEFENSES_NAME', 'Woodsman1 Featuredefenses', 'en_US'),
('LOC_SLTH_WOODSMAN2_ABILITY_FEATUREATTACKS_NAME', 'Woodsman2 Featureattacks', 'en_US'),
('LOC_SLTH_WOODSMAN2_ABILITY_FEATUREDEFENSES_NAME', 'Woodsman2 Featuredefenses', 'en_US'),
('LOC_ABILITY_HERO_DESCRIPTION', 'One of a kind Unit. Gains 1 experience per turn.', 'en_US'),
('LOC_ABILITY_HERO_NO_EXP_DESCRIPTION', 'One of a kind Unit.', 'en_US'),
('LOC_ABILITY_PROMOTION_DEXTEROUS_DESCRIPTION', '+4[ICON_STRENGTH] Combat Strength.', 'en_US'),
('LOC_DARK_ELF_ABILITY_FEATUREATTACKS_DESCRIPTION', '+10[ICON_Strength] Combat Strength while on Woods and Ancient Forest.', 'en_US'),
('LOC_DEMON_ABILITY_HELL_TERRAIN_STRENGTH_DESCRIPTION', '10 % stronger in combat on Hell terrain: Burning Sands, Fields of Perdition, Broken Fields.', 'en_US'),
('LOC_DEMON_ABILITY_TERRAINATTACKS_DESCRIPTION', '+10[ICON_Strength] Combat Strength while on Broken lands, Fields of perdition and Burning sands.', 'en_US'),
('LOC_DEMON_ABILITY_TERRAINDEFENSES_DESCRIPTION', '+10[ICON_Strength] Combat Strength while on Broken lands, Fields of perdition and Burning sands.', 'en_US'),
('LOC_ELF_ABILITY_FEATUREATTACKS_DESCRIPTION', '+10[ICON_Strength] Combat Strength while on Woods and Ancient Forest.', 'en_US'),
('LOC_ELF_ABILITY_FEATUREDOUBLEMOVES_DESCRIPTION', '+1[ICON_Movement] Movement while on Forest and Ancient Forest.', 'en_US'),
('LOC_FROSTLING_ABILITY_TERRAINATTACKS_DESCRIPTION', '+25[ICON_Strength] Combat Strength while on Snow.[NEWLINE]+10[ICON_Strength] Combat Strength while on Tundra.[NEWLINE]-25[ICON_Strength] Combat Strength while on Desert.[NEWLINE]', 'en_US'),
('LOC_FROSTLING_ABILITY_TERRAINDEFENSES_DESCRIPTION', '+25[ICON_Strength] Combat Strength while on Snow.[NEWLINE]+10[ICON_Strength] Combat Strength while on Tundra.[NEWLINE]-25[ICON_Strength] Combat Strength while on Desert.[NEWLINE]', 'en_US'),
('LOC_LIZARDMAN_ABILITY_MARSH_DOUBLE_MOVES_DESCRIPTION', '+1[ICON_Movement] Movement while on Marsh.', 'en_US'),
('LOC_LIZARDMAN_ABILITY_MARSH_STRENGTH_DESCRIPTION', '+10[ICON_Strength] Combat Strength while on Marsh.', 'en_US'),
('LOC_LIZARDMAN_ABILITY_TERRAINDEFENSES_DESCRIPTION', '+10[ICON_Strength] Combat Strength while on Marsh.', 'en_US'),
('LOC_NIGHTMARE_ABILITY_HELL_TERRAIN_STRENGTH_DESCRIPTION', '+10[ICON_Strength] Combat Strength while on Broken lands, Fields of perdition and Burning sands.', 'en_US'),
('LOC_NIGHTMARE_ABILITY_TERRAINDEFENSES_DESCRIPTION', '+10[ICON_Strength] Combat Strength while on Broken lands, Fields of perdition and Burning sands.', 'en_US'),
('LOC_NOMAD_ABILITY_DESERT_STRENGTH_DESCRIPTION', '+20[ICON_Strength] Combat Strength and +1[ICON_Movement] Movement when Desert.', 'en_US'),
('LOC_NOMAD_ABILITY_TERRAINDEFENSES_DESCRIPTION', '+20[ICON_Strength] Combat Strength while on Desert.', 'en_US'),
('LOC_ORC_ABILITY_JUNGLE_ATTACKS_DESCRIPTION', '+10[ICON_Strength] Combat Strength while on jungle.', 'en_US'),
('LOC_PROMOTION_DARK_ELF_ABILITY_FEATUREDOUBLEMOVES_DESCRIPTION', '+1[ICON_Movement] Movement while on Ancient_forest.', 'en_US'),
('LOC_PROMOTION_DWARF_ABILITY_HILLS_DOUBLE_MOVE_DESCRIPTION', '+1[ICON_Movement] Movement while on Hills.', 'en_US'),
('LOC_PROMOTION_GUERILLA2_ABILITY_HILLS_DOUBLE_MOVE_DESCRIPTION', '+1[ICON_Movement] Movement while on Hills.', 'en_US'),
('LOC_PROMOTION_NOMAD_ABILITY_TERRAINDOUBLEMOVES_DESCRIPTION', '+1[ICON_Movement] Movement while on Desert.', 'en_US'),
('LOC_PROMOTION_WOODSMAN2_ABILITY_FEATUREDOUBLEMOVES_DESCRIPTION', '+1[ICON_Movement] Movement while on Ancient_forest.', 'en_US'),
('LOC_WINTERBORN_ABILITY_TERRAINDEFENSES_DESCRIPTION', '+10[ICON_Strength] Combat Strength while on Snow and Tundra.', 'en_US'),
('LOC_WINTERBORN_ABILITY_TUNDRA_SNOW_STRENGTH_DESCRIPTION', '+10[ICON_Strength] Combat Strength while on Snow and Tundra.', 'en_US'),
('LOC_WOODSMAN1_ABILITY_FEATUREATTACKS_DESCRIPTION', '+11[ICON_Strength] Combat Strength while on jungle, Woods and Ancient Forest.', 'en_US'),
('LOC_WOODSMAN1_ABILITY_FEATUREDEFENSES_DESCRIPTION', '+11[ICON_Strength] Combat Strength while on jungle, Woods and Ancient Forest.', 'en_US'),
('LOC_WOODSMAN2_ABILITY_FEATUREATTACKS_DESCRIPTION', '+11[ICON_Strength] Combat Strength while on jungle, Woods and Ancient Forest.', 'en_US'),
('LOC_WOODSMAN2_ABILITY_FEATUREDEFENSES_DESCRIPTION', '+11[ICON_Strength] Combat Strength while on jungle, Woods and Ancient Forest.', 'en_US');