INSERT OR REPLACE INTO LocalizedText(Tag, Text, Language) VALUES
('LOC_PROMOTION_ACCURACY_NAME', 'Accuracy', 'en_US'),
('LOC_PROMOTION_AMPHIBIOUS_NAME', 'Amphibious', 'en_US'),
('LOC_PROMOTION_BARRAGE1_NAME', 'Barrage I', 'en_US'),
('LOC_PROMOTION_BARRAGE2_NAME', 'Barrage II', 'en_US'),
('LOC_PROMOTION_BARRAGE3_NAME', 'Barrage III', 'en_US'),
('LOC_PROMOTION_BLITZ_NAME', 'Blitz', 'en_US'),
('LOC_PROMOTION_BOUNTY_HUNTER_NAME', 'Bounty Hunter', 'en_US'),
('LOC_PROMOTION_CANNIBALIZE_NAME', 'Cannibalize', 'en_US'),
('LOC_PROMOTION_CITY_GARRISON1_NAME', 'City Garrison I', 'en_US'),
('LOC_PROMOTION_CITY_GARRISON2_NAME', 'City Garrison II', 'en_US'),
('LOC_PROMOTION_CITY_GARRISON3_NAME', 'City Garrison III', 'en_US'),
('LOC_PROMOTION_CITY_RAIDER1_NAME', 'City Raider I', 'en_US'),
('LOC_PROMOTION_CITY_RAIDER2_NAME', 'City Raider II', 'en_US'),
('LOC_PROMOTION_CITY_RAIDER3_NAME', 'City Raider III', 'en_US'),
('LOC_PROMOTION_CLASS_ADEPT_NAME', 'Adept', 'en_US'),
('LOC_PROMOTION_CLASS_ANIMAL_NAME', 'Animal', 'en_US'),
('LOC_PROMOTION_CLASS_BEAST_NAME', 'Beast', 'en_US'),
('LOC_PROMOTION_CLASS_DISCIPLE_NAME', 'Disciple', 'en_US'),
('LOC_PROMOTION_COLD_RESISTANCE_NAME', 'Cold Resistance', 'en_US'),
('LOC_PROMOTION_COMBAT1_NAME', 'Combat I', 'en_US'),
('LOC_PROMOTION_COMBAT2_NAME', 'Combat II', 'en_US'),
('LOC_PROMOTION_COMBAT3_NAME', 'Combat III', 'en_US'),
('LOC_PROMOTION_COMBAT4_NAME', 'Combat IV', 'en_US'),
('LOC_PROMOTION_COMBAT5_NAME', 'Combat V', 'en_US'),
('LOC_PROMOTION_COMMAND1_NAME', 'Command I', 'en_US'),
('LOC_PROMOTION_COMMAND2_NAME', 'Command II', 'en_US'),
('LOC_PROMOTION_COMMAND3_NAME', 'Command III', 'en_US'),
('LOC_PROMOTION_COMMAND4_NAME', 'Command IV', 'en_US'),
('LOC_PROMOTION_COMMANDO_NAME', 'Commando', 'en_US'),
('LOC_PROMOTION_COVER2_NAME', 'Cover II', 'en_US'),
('LOC_PROMOTION_COVER_NAME', 'Cover', 'en_US'),
('LOC_PROMOTION_DEFENSIVE_NAME', 'Defensive', 'en_US'),
('LOC_PROMOTION_DEMON_SLAYING_NAME', 'Demon Slaying', 'en_US'),
('LOC_PROMOTION_DRILL1_NAME', 'Drill I', 'en_US'),
('LOC_PROMOTION_DRILL2_NAME', 'Drill II', 'en_US'),
('LOC_PROMOTION_DRILL3_NAME', 'Drill III', 'en_US'),
('LOC_PROMOTION_DRILL4_NAME', 'Drill IV', 'en_US'),
('LOC_PROMOTION_EXPANDED_HULL_NAME', 'Expanded Hull', 'en_US'),
('LOC_PROMOTION_EXTENSION1_NAME', 'Extension I', 'en_US'),
('LOC_PROMOTION_EXTENSION2_NAME', 'Extension II', 'en_US'),
('LOC_PROMOTION_FEAR_NAME', 'Fear', 'en_US'),
('LOC_PROMOTION_FIRE_RESISTANCE_NAME', 'Fire Resistance', 'en_US'),
('LOC_PROMOTION_FLANKING1_NAME', 'Flanking I', 'en_US'),
('LOC_PROMOTION_FLANKING2_NAME', 'Flanking II', 'en_US'),
('LOC_PROMOTION_FLANKING3_NAME', 'Flanking III', 'en_US'),
('LOC_PROMOTION_FORMATION2_NAME', 'Formation II', 'en_US'),
('LOC_PROMOTION_FORMATION_NAME', 'Formation', 'en_US'),
('LOC_PROMOTION_GUARDSMAN_NAME', 'Guardsman', 'en_US'),
('LOC_PROMOTION_GUERILLA1_NAME', 'Guerilla I', 'en_US'),
('LOC_PROMOTION_GUERILLA2_NAME', 'Guerilla II', 'en_US'),
('LOC_PROMOTION_HEROIC_DEFENSE2_NAME', 'Heroic Defense II', 'en_US'),
('LOC_PROMOTION_HEROIC_DEFENSE_NAME', 'Heroic Defense', 'en_US'),
('LOC_PROMOTION_HEROIC_STRENGTH2_NAME', 'Heroic Strength II', 'en_US'),
('LOC_PROMOTION_HEROIC_STRENGTH_NAME', 'Heroic Strength', 'en_US'),
('LOC_PROMOTION_INQUISITOR_NAME', 'Inquisitor', 'en_US'),
('LOC_PROMOTION_KEEN_SIGHT_NAME', 'Keen Sight', 'en_US'),
('LOC_PROMOTION_LIGHTNING_RESISTANCE_NAME', 'Lightning Resistance', 'en_US'),
('LOC_PROMOTION_MAGIC_RESISTANCE_NAME', 'Magic Resistance', 'en_US'),
('LOC_PROMOTION_MARCH_NAME', 'March', 'en_US'),
('LOC_PROMOTION_MARKSMAN_NAME', 'Marksman', 'en_US'),
('LOC_PROMOTION_MOBILITY1_NAME', 'Mobility I', 'en_US'),
('LOC_PROMOTION_MOBILITY2_NAME', 'Mobility II', 'en_US'),
('LOC_PROMOTION_NAVIGATION1_NAME', 'Navigation I', 'en_US'),
('LOC_PROMOTION_NAVIGATION2_NAME', 'Navigation II', 'en_US'),
('LOC_PROMOTION_PERFECT_SIGHT_NAME', 'Perfect Sight', 'en_US'),
('LOC_PROMOTION_POISON_RESISTANCE_NAME', 'Poison Resistance', 'en_US'),
('LOC_PROMOTION_PRECISION_NAME', 'Precision', 'en_US'),
('LOC_PROMOTION_SCOURGE_NAME', 'Scourge', 'en_US'),
('LOC_PROMOTION_SENTRY2_NAME', 'Sentry II', 'en_US'),
('LOC_PROMOTION_SENTRY_NAME', 'Sentry', 'en_US'),
('LOC_PROMOTION_SHOCK2_NAME', 'Shock II', 'en_US'),
('LOC_PROMOTION_SHOCK_NAME', 'Shock', 'en_US'),
('LOC_PROMOTION_SUBDUE_ANIMAL_NAME', 'Subdue Animal', 'en_US'),
('LOC_PROMOTION_SUBDUE_BEASTS_NAME', 'Subdue Beasts', 'en_US'),
('LOC_PROMOTION_SUMMONER_NAME', 'Summoner', 'en_US'),
('LOC_PROMOTION_TWINCAST_NAME', 'Twincast', 'en_US'),
('LOC_PROMOTION_UNDEAD_SLAYING_NAME', 'Undead Slaying', 'en_US'),
('LOC_PROMOTION_WOODSMAN1_NAME', 'Woodsman I', 'en_US'),
('LOC_PROMOTION_WOODSMAN2_NAME', 'Woodsman II', 'en_US'),
('LOC_DEATH_ONE_NAME', '  [ICON_RESOURCE_AMBER]', 'en_US'),             -- spaces for offset as no number
('LOC_FIRE_ONE_NAME', '  [ICON_RESOURCE_AMBER]', 'en_US'),
('LOC_AIR_ONE_NAME', '  [ICON_RESOURCE_AMBER]', 'en_US'),
('LOC_BODY_ONE_NAME', '  [ICON_RESOURCE_AMBER]', 'en_US'),
('LOC_CHAOS_ONE_NAME', '  [ICON_RESOURCE_AMBER]', 'en_US'),
('LOC_EARTH_ONE_NAME', '  [ICON_RESOURCE_AMBER]', 'en_US'),
('LOC_ENCHANTMENT_ONE_NAME', '  [ICON_RESOURCE_AMBER]', 'en_US'),
('LOC_ENTROPY_ONE_NAME', '  [ICON_RESOURCE_AMBER]', 'en_US'),
('LOC_ICE_ONE_NAME', '  [ICON_RESOURCE_AMBER]', 'en_US'),
('LOC_LAW_ONE_NAME', '  [ICON_RESOURCE_AMBER]', 'en_US'),
('LOC_LIFE_ONE_NAME', '  [ICON_RESOURCE_AMBER]', 'en_US'),
('LOC_METAMAGIC_ONE_NAME', '  [ICON_RESOURCE_AMBER]', 'en_US'),
('LOC_MIND_ONE_NAME', '  [ICON_RESOURCE_AMBER]', 'en_US'),
('LOC_NATURE_ONE_NAME', '  [ICON_RESOURCE_AMBER]', 'en_US'),
('LOC_SPIRIT_ONE_NAME', '  [ICON_RESOURCE_AMBER]', 'en_US'),
('LOC_WATER_ONE_NAME', '  [ICON_RESOURCE_AMBER]', 'en_US'),
('LOC_SUN_ONE_NAME', '  [ICON_RESOURCE_AMBER]', 'en_US'),
('LOC_SHADOW_ONE_NAME', '  [ICON_RESOURCE_AMBER]', 'en_US'),
('LOC_DEATH_TWO_NAME', '[ICON_RESOURCE_AMBER]2', 'en_US'),
('LOC_FIRE_TWO_NAME', '[ICON_RESOURCE_AMBER]2', 'en_US'),
('LOC_AIR_TWO_NAME', '[ICON_RESOURCE_AMBER]2', 'en_US'),
('LOC_BODY_TWO_NAME', '[ICON_RESOURCE_AMBER]2', 'en_US'),
('LOC_CHAOS_TWO_NAME', '[ICON_RESOURCE_AMBER]2', 'en_US'),
('LOC_EARTH_TWO_NAME', '[ICON_RESOURCE_AMBER]2', 'en_US'),
('LOC_ENCHANTMENT_TWO_NAME', '[ICON_RESOURCE_AMBER]2', 'en_US'),
('LOC_ENTROPY_TWO_NAME', '[ICON_RESOURCE_AMBER]2', 'en_US'),
('LOC_ICE_TWO_NAME', '[ICON_RESOURCE_AMBER]2', 'en_US'),
('LOC_LAW_TWO_NAME', '[ICON_RESOURCE_AMBER]2', 'en_US'),
('LOC_LIFE_TWO_NAME', '[ICON_RESOURCE_AMBER]2', 'en_US'),
('LOC_METAMAGIC_TWO_NAME', '[ICON_RESOURCE_AMBER]2', 'en_US'),
('LOC_MIND_TWO_NAME', '[ICON_RESOURCE_AMBER]2', 'en_US'),
('LOC_NATURE_TWO_NAME', '[ICON_RESOURCE_AMBER]2', 'en_US'),
('LOC_SPIRIT_TWO_NAME', '[ICON_RESOURCE_AMBER]2', 'en_US'),
('LOC_WATER_TWO_NAME', '[ICON_RESOURCE_AMBER]2', 'en_US'),
('LOC_SUN_TWO_NAME', '[ICON_RESOURCE_AMBER]2', 'en_US'),
('LOC_SHADOW_TWO_NAME', '[ICON_RESOURCE_AMBER]2', 'en_US'),
('LOC_DEATH_THREE_NAME', '[ICON_RESOURCE_AMBER]3', 'en_US'),
('LOC_FIRE_THREE_NAME', '[ICON_RESOURCE_AMBER]3', 'en_US'),
('LOC_AIR_THREE_NAME', '[ICON_RESOURCE_AMBER]3', 'en_US'),
('LOC_BODY_THREE_NAME', '[ICON_RESOURCE_AMBER]3', 'en_US'),
('LOC_CHAOS_THREE_NAME', '[ICON_RESOURCE_AMBER]3', 'en_US'),
('LOC_EARTH_THREE_NAME', '[ICON_RESOURCE_AMBER]3', 'en_US'),
('LOC_ENCHANTMENT_THREE_NAME', '[ICON_RESOURCE_AMBER]3', 'en_US'),
('LOC_ENTROPY_THREE_NAME', '[ICON_RESOURCE_AMBER]3', 'en_US'),
('LOC_ICE_THREE_NAME', '[ICON_RESOURCE_AMBER]3', 'en_US'),
('LOC_LAW_THREE_NAME', '[ICON_RESOURCE_AMBER]3', 'en_US'),
('LOC_LIFE_THREE_NAME', '[ICON_RESOURCE_AMBER]3', 'en_US'),
('LOC_METAMAGIC_THREE_NAME', '[ICON_RESOURCE_AMBER]3', 'en_US'),
('LOC_MIND_THREE_NAME', '[ICON_RESOURCE_AMBER]3', 'en_US'),
('LOC_NATURE_THREE_NAME', '[ICON_RESOURCE_AMBER]3', 'en_US'),
('LOC_SPIRIT_THREE_NAME', '[ICON_RESOURCE_AMBER]3', 'en_US'),
('LOC_WATER_THREE_NAME', '[ICON_RESOURCE_AMBER]3', 'en_US'),
('LOC_SUN_THREE_NAME', '[ICON_RESOURCE_AMBER]3', 'en_US'),
('LOC_SHADOW_THREE_NAME', '[ICON_RESOURCE_AMBER]3', 'en_US'),
('LOC_PROMOTION_ACCURACY_DESCRIPTION', '+14 [ICON_Strength] Combat Strength against District Defenses.', 'en_US'),
('LOC_PROMOTION_BARRAGE2_DESCRIPTION', '+5 [ICON_Strength] Combat Strength against Melee units', 'en_US'),
('LOC_PROMOTION_CITY_GARRISON1_DESCRIPTION', '+21 [ICON_Strength] Combat Strength while in a District', 'en_US'),
('LOC_PROMOTION_CITY_GARRISON2_DESCRIPTION', '+21 [ICON_Strength] Combat Strength while in a District', 'en_US'),
('LOC_PROMOTION_CITY_GARRISON3_DESCRIPTION', '+21 [ICON_Strength] Combat Strength while in a District +4 [ICON_Strength] Combat Strength against Melee units', 'en_US'),
('LOC_PROMOTION_CITY_RAIDER1_DESCRIPTION', '+21 [ICON_Strength] Combat Strength while fighting in a District', 'en_US'),
('LOC_PROMOTION_CITY_RAIDER2_DESCRIPTION', '+21 [ICON_Strength] Combat Strength while fighting in a District', 'en_US'),
('LOC_PROMOTION_CITY_RAIDER3_DESCRIPTION', '+21 [ICON_Strength] Combat Strength while fighting in a District +4 [ICON_Strength] Combat Strength against Melee units', 'en_US'),
('LOC_PROMOTION_COMBAT1_DESCRIPTION', '+4[ICON_Strength] Combat Strength', 'en_US'),
('LOC_PROMOTION_COMBAT2_DESCRIPTION', '+4[ICON_Strength] Combat Strength', 'en_US'),
('LOC_PROMOTION_COMBAT3_DESCRIPTION', '+4[ICON_Strength] Combat Strength', 'en_US'),
('LOC_PROMOTION_COMBAT4_DESCRIPTION', '+4[ICON_Strength] Combat Strength', 'en_US'),
('LOC_PROMOTION_COMBAT5_DESCRIPTION', '+4[ICON_Strength] Combat Strength', 'en_US'),
('LOC_PROMOTION_COVER2_DESCRIPTION', '+7 [ICON_Strength] Combat Strength against Archer units', 'en_US'),
('LOC_PROMOTION_COVER_DESCRIPTION', '+4 [ICON_Strength] Combat Strength against Archer units', 'en_US'),
('LOC_PROMOTION_DRILL4_DESCRIPTION', '+4 [ICON_Strength] Combat Strength against Mounted units', 'en_US'),
('LOC_PROMOTION_FORMATION2_DESCRIPTION', '+7[ICON_Strength] Combat Strength against Mounted units', 'en_US'),
('LOC_PROMOTION_FORMATION_DESCRIPTION', '+4 [ICON_Strength] Combat Strength against Mounted units', 'en_US'),
('LOC_PROMOTION_GUERILLA1_DESCRIPTION', '+14[ICON_Strength] Combat Strength while defending on Hills.', 'en_US'),
('LOC_PROMOTION_GUERILLA2_DESCRIPTION', '+14[ICON_Strength] Combat Strength while on Hills. +1[ICON_MOVEMENT] Movement when starting on Hills.', 'en_US'),
('LOC_PROMOTION_HEROIC_DEFENSE2_DESCRIPTION', '+4 [ICON_Strength] Combat Strength while defending', 'en_US'),
('LOC_PROMOTION_HEROIC_DEFENSE_DESCRIPTION', '+5 [ICON_Strength] Combat Strength while defending', 'en_US'),
('LOC_PROMOTION_HEROIC_STRENGTH2_DESCRIPTION', '+5 [ICON_Strength] Combat Strength while attacking', 'en_US'),
('LOC_PROMOTION_HEROIC_STRENGTH_DESCRIPTION', '+4 [ICON_Strength] Combat Strength while attacking', 'en_US'),
('LOC_PROMOTION_MARCH_DESCRIPTION', 'Always heal at end of turn. +10% Healing in any territory.', 'en_US'),
('LOC_PROMOTION_MOBILITY1_DESCRIPTION', '+1[ICON_Movement] Movement.', 'en_US'),
('LOC_PROMOTION_MOBILITY2_DESCRIPTION', '+1[ICON_Movement] Movement.', 'en_US'),
('LOC_PROMOTION_NAVIGATION1_DESCRIPTION', '+1[ICON_Movement] Movement.', 'en_US'),
('LOC_PROMOTION_NAVIGATION2_DESCRIPTION', '+1[ICON_Movement] Movement.', 'en_US'),
('LOC_PROMOTION_SCOURGE_DESCRIPTION', '+7 [ICON_Strength] Combat Strength against Disciple units', 'en_US'),
('LOC_PROMOTION_SHOCK2_DESCRIPTION', '+14 [ICON_Strength] Combat Strength against Melee units', 'en_US'),
('LOC_PROMOTION_SHOCK_DESCRIPTION', '+7 [ICON_Strength] Combat Strength against Melee units', 'en_US'),
('LOC_PROMOTION_SUBDUE_ANIMAL_DESCRIPTION', '+7 [ICON_Strength] Combat Strength against Animal units Captures defeated Animal units', 'en_US'),
('LOC_PROMOTION_SUBDUE_BEASTS_DESCRIPTION', '+7 [ICON_Strength] Combat Strength against Beast units. Captures defeated Beast units', 'en_US'),
('LOC_DEATH_ONE_DESCRIPTION', 'Skeleton', 'en_US'),
('LOC_FIRE_ONE_DESCRIPTION', 'Blaze', 'en_US'),
('LOC_AIR_ONE_DESCRIPTION', 'Fair Winds', 'en_US'),
('LOC_BODY_ONE_DESCRIPTION', 'Haste', 'en_US'),
('LOC_CHAOS_ONE_DESCRIPTION', 'Dance of Blades', 'en_US'),
('LOC_EARTH_ONE_DESCRIPTION', 'Walls of Stone', 'en_US'),
('LOC_ENCHANTMENT_ONE_DESCRIPTION', 'Enchanted Blade', 'en_US'),
('LOC_ENTROPY_ONE_DESCRIPTION', 'Rust', 'en_US'),
('LOC_ICE_ONE_DESCRIPTION', 'Slow', 'en_US'),
('LOC_LAW_ONE_DESCRIPTION', 'Loyalty', 'en_US'),
('LOC_LIFE_ONE_DESCRIPTION', 'Sanctify', 'en_US'),
('LOC_METAMAGIC_ONE_DESCRIPTION', 'Eye', 'en_US'),
('LOC_MIND_ONE_DESCRIPTION', 'Inspiration', 'en_US'),
('LOC_NATURE_ONE_DESCRIPTION', 'Treetop Defense', 'en_US'),
('LOC_SPIRIT_ONE_DESCRIPTION', 'Courage', 'en_US'),
('LOC_WATER_ONE_DESCRIPTION', 'Spring', 'en_US'),
('LOC_SUN_ONE_DESCRIPTION', 'Scorch', 'en_US'),
('LOC_SHADOW_ONE_DESCRIPTION', 'Blur', 'en_US'),
('LOC_DEATH_TWO_DESCRIPTION', 'Spectre', 'en_US'),
('LOC_FIRE_TWO_DESCRIPTION', 'Fireball', 'en_US'),
('LOC_AIR_TWO_DESCRIPTION', 'Maelstrom', 'en_US'),
('LOC_BODY_TWO_DESCRIPTION', 'Regeneration', 'en_US'),
('LOC_CHAOS_TWO_DESCRIPTION', 'Mutate', 'en_US'),
('LOC_EARTH_TWO_DESCRIPTION', 'Stoneskin', 'en_US'),
('LOC_ENCHANTMENT_TWO_DESCRIPTION', 'Flaming Arrows', 'en_US'),
('LOC_ENTROPY_TWO_DESCRIPTION', 'Pit Beast', 'en_US'),
('LOC_ICE_TWO_DESCRIPTION', 'Ice Elemental', 'en_US'),
('LOC_LAW_TWO_DESCRIPTION', 'Einerhjar', 'en_US'),
('LOC_LIFE_TWO_DESCRIPTION', 'Destroy Undead', 'en_US'),
('LOC_METAMAGIC_TWO_DESCRIPTION', 'Dispel Magic', 'en_US'),
('LOC_MIND_TWO_DESCRIPTION', 'Charm', 'en_US'),
('LOC_NATURE_TWO_DESCRIPTION', 'Poison Blade', 'en_US'),
('LOC_SPIRIT_TWO_DESCRIPTION', 'Hope', 'en_US'),
('LOC_WATER_TWO_DESCRIPTION', 'Water-Walk', 'en_US'),
('LOC_SUN_TWO_DESCRIPTION', 'Blinding Light', 'en_US'),
('LOC_SHADOW_TWO_DESCRIPTION', 'Shadow Walk', 'en_US'),
('LOC_DEATH_THREE_DESCRIPTION', 'Wraith', 'en_US'),
('LOC_FIRE_THREE_DESCRIPTION', 'Fire Elemental', 'en_US'),
('LOC_AIR_THREE_DESCRIPTION', 'Air Elemental', 'en_US'),
('LOC_BODY_THREE_DESCRIPTION', 'Flesh Golem', 'en_US'),
('LOC_CHAOS_THREE_DESCRIPTION', 'Wonder', 'en_US'),
('LOC_EARTH_THREE_DESCRIPTION', 'Earth Elemental', 'en_US'),
('LOC_ENCHANTMENT_THREE_DESCRIPTION', 'Enchant Spellstaff', 'en_US'),
('LOC_ENTROPY_THREE_DESCRIPTION', 'Wither', 'en_US'),
('LOC_ICE_THREE_DESCRIPTION', 'Snowfall', 'en_US'),
('LOC_LAW_THREE_DESCRIPTION', 'Valor', 'en_US'),
('LOC_LIFE_THREE_DESCRIPTION', 'Resurrection', 'en_US'),
('LOC_METAMAGIC_THREE_DESCRIPTION', 'Djinn', 'en_US'),
('LOC_MIND_THREE_DESCRIPTION', 'Domination', 'en_US'),
('LOC_NATURE_THREE_DESCRIPTION', 'Vitalize', 'en_US'),
('LOC_SPIRIT_THREE_DESCRIPTION', 'Mistform', 'en_US'),
('LOC_WATER_THREE_DESCRIPTION', 'Water Elemental', 'en_US'),
('LOC_SUN_THREE_DESCRIPTION', 'Aurealis', 'en_US'),
('LOC_SHADOW_THREE_DESCRIPTION', 'Mistform', 'en_US'),
('LOC_PROMOTION_FEAR_DESCRIPTION', 'Attacking Units pushes units back. Unless the unit is a Hero, or has Courage or Valor buffs.', 'en_US'),
('LOC_PROMOTION_WOODSMAN1_DESCRIPTION', '+11[ICON_Strength] Combat Strength in Forest, Jungle or Ancient Forest.', 'en_US'),
('LOC_PROMOTION_WOODSMAN2_DESCRIPTION', '+11[ICON_Strength] Combat Strength in Forest, Jungle or Ancient Forest. +1[ICON_Movement] Movement on starting on those Features.', 'en_US'),
('LOC_PROMOTION_UNDEAD_SLAYING_DESCRIPTION', '+14[ICON_Strength] Combat Strength against Undead units. (NOT_IMPLEMENTED)', 'en_US'),
('LOC_PROMOTION_DEMON_SLAYING_DESCRIPTION', '+14[ICON_Strength] Combat Strength against Demon units.(NOT_IMPLEMENTED)', 'en_US'),
('LOC_PROMOTION_CANNIBALIZE_DESCRIPTION', 'On Combat Victory, heals 10 points.', 'en_US'),
('LOC_PROMOTION_BLITZ_DESCRIPTION', 'Can attack multiple times per turn.', 'en_US'),
('LOC_PROMOTION_MAGIC_RESISTANCE_DESCRIPTION', '20% Resistance to Cold, Fire, Lightning and Poison Damage. 20% chance to resist debuff Spells.', 'en_US'),
('LOC_PROMOTION_COLD_RESISTANCE_DESCRIPTION', '50% Resistance to Cold damage.', 'en_US'),
('LOC_PROMOTION_FIRE_RESISTANCE_DESCRIPTION', '50% Resistance to Fire damage.', 'en_US'),
('LOC_PROMOTION_POISON_RESISTANCE_DESCRIPTION', '50% Resistance to Poison damage.', 'en_US'),
('LOC_PROMOTION_LIGHTNING_RESISTANCE_DESCRIPTION', '50% Resistance to Lightning damage.', 'en_US'),
('LOC_PROMOTION_BOUNTY_HUNTER_DESCRIPTION', 'Gain Gold on Combat Victory.', 'en_US'),
('LOC_PROMOTION_EXTENSION_DESCRIPTION', 'Summoned Units have +1[ICON_Movement] Movement. (NOT_IMPLEMENTED)', 'en_US'),
('LOC_PROMOTION_EXTENSION2_DESCRIPTION', 'Summoned Units have +1[ICON_Movement] Movement(NOT_IMPLEMENTED', 'en_US'),
('LOC_PROMOTION_SUMMONER_DESCRIPTION', 'uhhh (NOT_IMPLEMENTED)', 'en_US'),
('LOC_PROMOTION_TWINCAST_DESCRIPTION', 'Summoning Spells produce double the number of units. (NOT_IMPLEMENTED)', 'en_US'),
('LOC_PROMOTION_INQUISITOR_DESCRIPTION', 'Can be used to remove all religions bar the Inquisitor''s from the city', 'en_US'),
('LOC_PROMOTION_PRECISION_DESCRIPTION', 'uhhh (NOT_IMPLEMENTED)', 'en_US'),
('LOC_PROMOTION_KEEN_SIGHT_DESCRIPTION', 'uhhh (NOT_IMPLEMENTED)', 'en_US'),
('LOC_PROMOTION_SENTRY1_DESCRIPTION', '+1 Sight Range.', 'en_US'),
('LOC_PROMOTION_SENTRY2_DESCRIPTION', '+2 Sight Range.', 'en_US'),
('LOC_PROMOTION_PERFECT_SIGHT_DESCRIPTION', 'Can see Invisible Units. +Combat vs Illusions. NOT IMPLEMENTED.', 'en_US');