INSERT OR REPLACE INTO LocalizedText(Tag, Text, Language) VALUES
('LOC_TECH_AGRICULTURE_NAME', 'Agriculture', 'en_US'),
('LOC_TECH_ALTERATION_NAME', 'Alteration', 'en_US'),
('LOC_TECH_ANIMAL_HANDLING_NAME', 'Animal Handling', 'en_US'),
('LOC_TECH_ANIMAL_HUSBANDRY_NAME', 'Animal Husbandry', 'en_US'),
('LOC_TECH_ANIMAL_MASTERY_NAME', 'Animal Mastery', 'en_US'),
('LOC_TECH_ARCANE_LORE_NAME', 'Arcane Lore', 'en_US'),
('LOC_TECH_ARCHERY_NAME', 'Archery', 'en_US'),
('LOC_TECH_ASTRONOMY_NAME', 'Astronomy', 'en_US'),
('LOC_TECH_BLASTING_POWDER_NAME', 'Blasting Powder', 'en_US'),
('LOC_TECH_BOWYERS_NAME', 'Bowyers', 'en_US'),
('LOC_TECH_BRONZE_WORKING_NAME', 'Bronze Working', 'en_US'),
('LOC_TECH_CALENDAR_NAME', 'Calendar', 'en_US'),
('LOC_TECH_CARTOGRAPHY_NAME', 'Cartography', 'en_US'),
('LOC_TECH_CONSTRUCTION_NAME', 'Construction', 'en_US'),
('LOC_TECH_CRAFTING_NAME', 'Crafting', 'en_US'),
('LOC_TECH_DIVINATION_NAME', 'Divination', 'en_US'),
('LOC_TECH_ELEMENTALISM_NAME', 'Elementalism', 'en_US'),
('LOC_TECH_ENGINEERING_NAME', 'Engineering', 'en_US'),
('LOC_TECH_EXPLORATION_NAME', 'Exploration', 'en_US'),
('LOC_TECH_FISHING_NAME', 'Fishing', 'en_US'),
('LOC_TECH_FUTURE_TECH_NAME', 'Future', 'en_US'),
('LOC_TECH_HORSEBACK_RIDING_NAME', 'Horseback Riding', 'en_US'),
('LOC_TECH_HUNTING_NAME', 'Hunting', 'en_US'),
('LOC_TECH_IRON_WORKING_NAME', 'Iron Working', 'en_US'),
('LOC_TECH_KNOWLEDGE_OF_THE_ETHER_NAME', 'Knowledge Of The Ether', 'en_US'),
('LOC_TECH_MACHINERY_NAME', 'Machinery', 'en_US'),
('LOC_TECH_MASONRY_NAME', 'Masonry', 'en_US'),
('LOC_TECH_MATHEMATICS_NAME', 'Mathematics', 'en_US'),
('LOC_TECH_MEDICINE_NAME', 'Medicine', 'en_US'),
('LOC_TECH_MINING_NAME', 'Mining', 'en_US'),
('LOC_TECH_MITHRIL_WEAPONS_NAME', 'Mithril Weapons', 'en_US'),
('LOC_TECH_MITHRIL_WORKING_NAME', 'Mithril Working', 'en_US'),
('LOC_TECH_NECROMANCY_NAME', 'Necromancy', 'en_US'),
('LOC_TECH_OMNISCIENCE_NAME', 'Omniscience', 'en_US'),
('LOC_TECH_OPTICS_NAME', 'Optics', 'en_US'),
('LOC_TECH_PASS_THROUGH_THE_ETHER_NAME', 'Pass Through The Ether', 'en_US'),
('LOC_TECH_POISONS_NAME', 'Poisons', 'en_US'),
('LOC_TECH_PRECISION_NAME', 'Precision', 'en_US'),
('LOC_SLTH_TECH_SAILING_NAME', 'Sailing', 'en_US'),
('LOC_TECH_SANITATION_NAME', 'Sanitation', 'en_US'),
('LOC_TECH_SKIP_NAME', 'Skip', 'en_US'),
('LOC_TECH_SMELTING_NAME', 'Smelting', 'en_US'),
('LOC_TECH_SORCERY_NAME', 'Sorcery', 'en_US'),
('LOC_TECH_STIRRUPS_NAME', 'Stirrups', 'en_US'),
('LOC_TECH_STRENGTH_OF_WILL_NAME', 'Strength Of Will', 'en_US'),
('LOC_TECH_TRADE_NAME', 'Trade', 'en_US'),
('LOC_TECH_WARHORSES_NAME', 'Warhorses', 'en_US'),
('LOC_TECH_WRITING_NAME', 'Writing', 'en_US'),
('LOC_TECH_ANIMAL_HANDLING_DESCRIPTION', 'Allows captured Giant Spiders to be used to build a Spider Pen. (NOT_FUNCTIONAL)', 'en_US'),
('LOC_TECH_ANIMAL_MASTERY_DESCRIPTION', 'Unlocks Recon Units to choose the Subdue Beast Promotion.', 'en_US'),
('LOC_TECH_ARCANE_LORE_DESCRIPTION', 'Unlocks the Spell Extension Promotion option for eligible units. First to unlock granted a Great Scientist. (NOT_FUNCTIONAL)', 'en_US'),
('LOC_TECH_ARCHERY_DESCRIPTION', 'Chopping Woods now grants +50% more production. (NOT_FUNCTIONAL)', 'en_US'),
('LOC_TECH_CARTOGRAPHY_DESCRIPTION', 'Unlocks the ability to enforce borders, and grant Open Borders to other civilizations. Also allows map trading between civilizations. (NOT_FUNCTIONAL)', 'en_US'),
('LOC_TECH_CONSTRUCTION_DESCRIPTION', 'Can build bridges across rivers. Allows Farms to spread Irrigation. (NOT_FUNCTIONAL)', 'en_US'),
('LOC_TECH_ENGINEERING_DESCRIPTION', '+1 Movement on Roads (NOT_FUNCTIONAL)', 'en_US'),
('LOC_TECH_FUTURE_TECH_DESCRIPTION', 'Adds +1 [ICON_Amenities]Amenity and [ICON_Housing]Housing per city.', 'en_US'),
('LOC_TECH_MACHINERY_DESCRIPTION', 'First to unlock granted a Great Engineer. (NOT_FUNCTIONAL)', 'en_US'),
('LOC_TECH_MEDICINE_DESCRIPTION', '+1[ICON_Housing]Housing per city', 'en_US'),
('LOC_TECH_MINING_DESCRIPTION', 'Allows chopping of Woods', 'en_US'),
('LOC_TECH_OMNISCIENCE_DESCRIPTION', 'Reveals the world map.', 'en_US'),
('LOC_TECH_OPTICS_DESCRIPTION', 'Units can see +1 further across Coast and Ocean tiles.', 'en_US'),
('LOC_TECH_PRECISION_DESCRIPTION', 'Unlocks Ranged Units to choose the Marksman Promotion.', 'en_US'),
('LOC_TECH_TRADE_DESCRIPTION', 'Grants a Trade route per city. Unlocks the ability to trade techs (NOT_FUNCTIONAL)', 'en_US'),
('LOC_CIVIC_ANCIENT_CHANTS_NAME', 'Ancient Chants', 'en_US'),
('LOC_CIVIC_ARETE_NAME', 'Arete', 'en_US'),
('LOC_CIVIC_CODE_OF_LAWS_NAME', 'Code Of Laws', 'en_US'),
('LOC_CIVIC_COMMUNE_WITH_NATURE_NAME', 'Commune With Nature', 'en_US'),
('LOC_CIVIC_CORRUPTION_OF_SPIRIT_NAME', 'Corruption Of Spirit', 'en_US'),
('LOC_CIVIC_CURRENCY_NAME', 'Currency', 'en_US'),
('LOC_CIVIC_DECEPTION_NAME', 'Deception', 'en_US'),
('LOC_CIVIC_DIVINE_ESSENCE_NAME', 'Divine Essence', 'en_US'),
('LOC_CIVIC_DRAMA_POETRY_NAME', 'Drama', 'en_US'),
('LOC_CIVIC_EDUCATION_NAME', 'Education', 'en_US'),
('LOC_CIVIC_FANATICISM_NAME', 'Fanaticism', 'en_US'),
('LOC_CIVIC_FERAL_BOND_NAME', 'Feral Bond', 'en_US'),
('LOC_CIVIC_FEUDALISM_NAME', 'Feudalism', 'en_US'),
('LOC_CIVIC_GAMES_RECREATION_NAME', 'Festivals', 'en_US'),
('LOC_CIVIC_GUILDS_NAME', 'Guilds', 'en_US'),
('LOC_CIVIC_HIDDEN_PATHS_NAME', 'Hidden Paths', 'en_US'),
('LOC_CIVIC_HONOR_NAME', 'Honor', 'en_US'),
('LOC_CIVIC_INFERNAL_PACT_NAME', 'Infernal Pact', 'en_US'),
('LOC_CIVIC_MALEVOLENT_DESIGNS_NAME', 'Malevolent Designs', 'en_US'),
('LOC_CIVIC_MERCANTILISM_NAME', 'Mercantilism', 'en_US'),
('LOC_CIVIC_MESSAGE_FROM_THE_DEEP_NAME', 'Message From The Deep', 'en_US'),
('LOC_CIVIC_MILITARY_TRADITION_NAME', 'Warfare', 'en_US'),
('LOC_CIVIC_MILITARY_TRAINING_NAME', 'Military Strategy', 'en_US'),
('LOC_CIVIC_MIND_STAPLING_NAME', 'Mind Stapling', 'en_US'),
('LOC_CIVIC_MYSTICISM_NAME', 'Mysticism', 'en_US'),
('LOC_CIVIC_ORDERS_FROM_HEAVEN_NAME', 'Orders From Heaven', 'en_US'),
('LOC_CIVIC_POLITICAL_PHILOSOPHY_NAME', 'Philosophy', 'en_US'),
('LOC_CIVIC_PRIESTHOOD_NAME', 'Priesthood', 'en_US'),
('LOC_CIVIC_RAGE_NAME', 'Rage', 'en_US'),
('LOC_CIVIC_RELIGIOUS_LAW_NAME', 'Religious Law', 'en_US'),
('LOC_CIVIC_RIGHTEOUSNESS_NAME', 'Righteousness', 'en_US'),
('LOC_CIVIC_TAXATION_NAME', 'Taxation', 'en_US'),
('LOC_CIVIC_THEOLOGY_NAME', 'Theology', 'en_US'),
('LOC_CIVIC_WAY_OF_THE_EARTHMOTHER_NAME', 'Way Of The Earthmother', 'en_US'),
('LOC_CIVIC_WAY_OF_THE_FORESTS_NAME', 'Way Of The Forests', 'en_US'),
('LOC_CIVIC_WAY_OF_THE_WICKED_NAME', 'Way Of The Wicked', 'en_US'),
('LOC_CIVIC_WAY_OF_THE_WISE_NAME', 'Way Of The Wise', 'en_US'),
('LOC_CIVIC_ARETE_DESCRIPTION', 'Unlocks the Guerilla II Promotion option for eligible units.', 'en_US'),
('LOC_CIVIC_CORRUPTION_OF_SPIRIT_DESCRIPTION', 'Adds the Ashen Veil religion to a city (NOT_FUNCTIONAL)', 'en_US'),
('LOC_CIVIC_CURRENCY_DESCRIPTION', 'Grants a Trade route per city. Allows Gold trading via diplomacy (NOT_FUNCTIONAL).', 'en_US'),
('LOC_CIVIC_DECEPTION_DESCRIPTION', 'Adds the Council of Esus religion to a city (NOT_FUNCTIONAL)', 'en_US'),
('LOC_CIVIC_DRAMA_POETRY_DESCRIPTION', 'First to unlock granted a Great Bard. (NOT_FUNCTIONAL)', 'en_US'),
('LOC_CIVIC_HONOR_DESCRIPTION', 'Unlocks the ability to form Defensive Pacts. Adds the Empyrean religion to a city (NOT_FUNCTIONAL)', 'en_US'),
('LOC_CIVIC_INFERNAL_PACT_DESCRIPTION', 'First to unlock this technology summons the Infernal Civilization into the game, and gives the player the option to switch to play them. (NOT_FUNCTIONAL)', 'en_US'),
('LOC_CIVIC_MERCANTILISM_DESCRIPTION', 'First to unlock granted a Great Merchant. (NOT_FUNCTIONAL)', 'en_US'),
('LOC_CIVIC_MESSAGE_FROM_THE_DEEP_DESCRIPTION', 'Adds the Octopus Overlords religion to a city (NOT_FUNCTIONAL)', 'en_US'),
('LOC_CIVIC_MILITARY_TRADITION_DESCRIPTION', 'Unlocks the City Raider and Garrison Promotions option for eligible units.', 'en_US'),
('LOC_CIVIC_MILITARY_TRAINING_DESCRIPTION', 'Unlocks the Blitz Promotion option for eligible units. First to unlock granted a Great General. (NOT_FUNCTIONAL)', 'en_US'),
('LOC_CIVIC_ORDERS_FROM_HEAVEN_DESCRIPTION', 'Adds the Order religion to a city (NOT_FUNCTIONAL)', 'en_US'),
('LOC_CIVIC_WAY_OF_THE_EARTHMOTHER_DESCRIPTION', 'Adds the Runes of Kilmorph religion to a city (NOT_FUNCTIONAL)', 'en_US'),
('LOC_CIVIC_WAY_OF_THE_FORESTS_DESCRIPTION', 'Adds the Fellowship of Leaves religion to a city (NOT_FUNCTIONAL)', 'en_US'),
('LOC_CIVIC_WAY_OF_THE_WICKED_DESCRIPTION', 'Unlocks the Scourge Promotion option for eligible units.', 'en_US'),
('LOC_CIVIC_WAY_OF_THE_WISE_DESCRIPTION', 'Unlocks the Demon Slaying and Undead Slaying Promotions option for eligible units.', 'en_US');