INSERT OR REPLACE INTO LocalizedText(Tag, Text, Language) VALUES
('LOC_SLTH_POLICY_AGRARIANISM_NAME', 'Agrarianism', 'en_US'),
('LOC_SLTH_POLICY_APPRENTICESHIP_NAME', 'Apprenticeship', 'en_US'),
('LOC_SLTH_POLICY_ARETE_NAME', 'Arete', 'en_US'),
('LOC_SLTH_POLICY_ARISTOCRACY_NAME', 'Aristocracy', 'en_US'),
('LOC_SLTH_POLICY_CASTE_SYSTEM_NAME', 'Caste System', 'en_US'),
('LOC_SLTH_POLICY_CITY_STATES_NAME', 'City States', 'en_US'),
('LOC_SLTH_POLICY_CONQUEST_NAME', 'Conquest', 'en_US'),
('LOC_SLTH_POLICY_CONSUMPTION_NAME', 'Consumption', 'en_US'),
('LOC_SLTH_POLICY_CRUSADE_NAME', 'Crusade', 'en_US'),
('LOC_SLTH_POLICY_DECENTRALIZATION_NAME', 'Decentralization', 'en_US'),
('LOC_SLTH_POLICY_DESPOTISM_NAME', 'Despotism', 'en_US'),
('LOC_SLTH_POLICY_FOREIGN_TRADE_NAME', 'Foreign Trade', 'en_US'),
('LOC_SLTH_POLICY_GOD_KING_NAME', 'God King', 'en_US'),
('LOC_SLTH_POLICY_GUARDIAN_OF_NATURE_NAME', 'Guardian Of Nature', 'en_US'),
('LOC_SLTH_POLICY_GUILDS_NAME', 'Guilds', 'en_US'),
('LOC_SLTH_POLICY_LIBERTY_NAME', 'Liberty', 'en_US'),
('LOC_SLTH_POLICY_MERCANTILISM_NAME', 'Mercantilism', 'en_US'),
('LOC_SLTH_POLICY_MILITARY_STATE_NAME', 'Military State', 'en_US'),
('LOC_SLTH_POLICY_NATIONHOOD_NAME', 'Nationhood', 'en_US'),
('LOC_SLTH_POLICY_PACIFISM_NAME', 'Pacifism', 'en_US'),
('LOC_SLTH_POLICY_RELIGION_NAME', 'Religion', 'en_US'),
('LOC_SLTH_POLICY_REPUBLIC_NAME', 'Republic', 'en_US'),
('LOC_SLTH_POLICY_SACRIFICE_THE_WEAK_NAME', 'Sacrifice The Weak', 'en_US'),
('LOC_SLTH_POLICY_SCHOLARSHIP_NAME', 'Scholarship', 'en_US'),
('LOC_SLTH_POLICY_SLAVERY_NAME', 'Slavery', 'en_US'),
('LOC_SLTH_POLICY_SOCIAL_ORDER_NAME', 'Social Order', 'en_US'),
('LOC_SLTH_POLICY_THEOCRACY_NAME', 'Theocracy', 'en_US'),
('LOC_SLTH_POLICY_TRIBALISM_NAME', 'Tribalism', 'en_US'),
('LOC_SLTH_POLICY_AGRARIANISM_DESCRIPTION', '+1[ICON_Housing] Housing in all cities. +1 [ICON_Food] Food and -1 [ICON_Production] Production  for each Farm.', 'en_US'),
('LOC_SLTH_POLICY_APPRENTICESHIP_DESCRIPTION', '+2 experience to trained Units. -10% [ICON_Production] Production to Military Units.', 'en_US'),
('LOC_SLTH_POLICY_ARETE_DESCRIPTION', '+1 [ICON_Production] Production for each Mine. Increased GPP.', 'en_US'),
('LOC_SLTH_POLICY_ARISTOCRACY_DESCRIPTION', '-1 [ICON_Food] Food and  +4 [ICON_Gold] Gold for each Farm. Allows the Royal Guard cavalry unit with Feudalism.', 'en_US'),
('LOC_SLTH_POLICY_CASTE_SYSTEM_DESCRIPTION', 'Builders start with +2 charges.', 'en_US'),
('LOC_SLTH_POLICY_CITY_STATES_DESCRIPTION', '80% reduced city Maintenance distance. -20% [ICON_Culture] Culture in all Cities. Accumulate 25% less war weariness than usual.', 'en_US'),
('LOC_SLTH_POLICY_CONQUEST_DESCRIPTION', '+2 experience to trained Units. All military units cost food [UNIMPLEMENTED]', 'en_US'),
('LOC_SLTH_POLICY_CONSUMPTION_DESCRIPTION', '20% [ICON_Gold] Gold in all Cities.  Markets, Taverns and Theatres all give +1 [ICON_Amenities] Amenity.', 'en_US'),
('LOC_SLTH_POLICY_CRUSADE_DESCRIPTION', 'Accumulate -75% less war weariness than usual.', 'en_US'),
('LOC_SLTH_POLICY_DECENTRALIZATION_DESCRIPTION', 'Does nothing', 'en_US'),
('LOC_SLTH_POLICY_DESPOTISM_DESCRIPTION', 'Accumulate -50% less war weariness than usual.', 'en_US'),
('LOC_SLTH_POLICY_FOREIGN_TRADE_DESCRIPTION', '+1 Trade Route Capacity. 20% [ICON_Culture] Culture and -10% [ICON_Gold] Gold in all Cities. +1 Trade Route Capacity per coastal city.', 'en_US'),
('LOC_SLTH_POLICY_GOD_KING_DESCRIPTION', '50% [ICON_Production] Production and [ICON_Gold] Gold in Capital City. 10% increased Distance Maintenance', 'en_US'),
('LOC_SLTH_POLICY_GUARDIAN_OF_NATURE_DESCRIPTION', '+5[ICON_Housing] Housing in all cities.  Groves gives +2 [ICON_Amenities] Amenity. -10% Production towards Military Units.', 'en_US'),
('LOC_SLTH_POLICY_GUILDS_DESCRIPTION', 'Can spend gold to finish production, Unlimited merchant, sage, artist and engineer specialists.', 'en_US'),
('LOC_SLTH_POLICY_LIBERTY_DESCRIPTION', '100% [ICON_Culture] Culture in all Cities. Accumulate 50% less war weariness than usual.', 'en_US'),
('LOC_SLTH_POLICY_MERCANTILISM_DESCRIPTION', '20% [ICON_Gold] Gold in all Cities.  Market gives +1 [ICON_Amenities] Amenity. Foreign Trade routes provide no yields.', 'en_US'),
('LOC_SLTH_POLICY_MILITARY_STATE_DESCRIPTION', '+15% Production towards Military Units. -25% [ICON_Culture] Culture in all Cities.', 'en_US'),
('LOC_SLTH_POLICY_NATIONHOOD_DESCRIPTION', '+10% Production to Military Units. Accumulate -25% less war weariness than usual.  Training Yard gives +1 [ICON_Amenities] Amenity.', 'en_US'),
('LOC_SLTH_POLICY_PACIFISM_DESCRIPTION', '50% Great Person Great People points generated per turn. -20% Bonus Production to Military Units. Accumulate 25% more war weariness than usual.', 'en_US'),
('LOC_SLTH_POLICY_RELIGION_DESCRIPTION', '10% [ICON_Culture] Culture in all Cities. Religious Temples grant +1 [ICON_Amenities] Amenity.', 'en_US'),
('LOC_SLTH_POLICY_REPUBLIC_DESCRIPTION', '25% Great Person Great People points generated per turn. 20% [ICON_Culture] Culture in all Cities.', 'en_US'),
('LOC_SLTH_POLICY_SACRIFICE_THE_WEAK_DESCRIPTION', '+1 [ICON_Food] Food per population. 10% [ICON_Gold] Gold in all Cities. -20% Great Person Great People points generated per turn. -4[ICON_Housing] Housing in all cities.', 'en_US'),
('LOC_SLTH_POLICY_SCHOLARSHIP_DESCRIPTION', '10% [ICON_Science] Science in all Cities.  Library gives +1 [ICON_Amenities] Amenity. Accumulate 20% less war weariness than usual.', 'en_US'),
('LOC_SLTH_POLICY_SLAVERY_DESCRIPTION', '+1 [ICON_Production] Production for each Quarry. Defeating major civilization units has a chance to capture the unit as a Slave.', 'en_US'),
('LOC_SLTH_POLICY_SOCIAL_ORDER_DESCRIPTION', 'Courthouse gives +1 [ICON_Amenities] Amenity.  Basilica gives +1 [ICON_Amenities] Amenity.', 'en_US'),
('LOC_SLTH_POLICY_THEOCRACY_DESCRIPTION', '+2 Experience to units trained in cities with the State Religion. Increased yields from Priest specialists', 'en_US'),
('LOC_SLTH_POLICY_TRIBALISM_DESCRIPTION', 'Does nothing', 'en_US'),
('LOC_SLTH_POLICY_NO_STATE_RELIGION_NAME', 'No State Religion', 'en_US'),
('LOC_SLTH_POLICY_STATE_VEIL_NAME', 'The Ashen Veil', 'en_US'),
('LOC_SLTH_POLICY_STATE_LEAVES_NAME', 'Fellowship of the Leaves', 'en_US'),
('LOC_SLTH_POLICY_STATE_RUNES_NAME', 'Runes of Kilmorph', 'en_US'),
('LOC_SLTH_POLICY_STATE_ORDER_NAME', 'The Order', 'en_US'),
('LOC_SLTH_POLICY_STATE_OCTOPUS_NAME', 'Octopus Overlords', 'en_US'),
('LOC_SLTH_POLICY_STATE_EMPYREAN_NAME', 'The Empyrean', 'en_US'),
('LOC_SLTH_POLICY_STATE_ESUS_NAME', 'Council of Esus', 'en_US'),

('LOC_SLTH_POLICY_NO_STATE_RELIGION_DESCRIPTION', '', 'en_US'),
('LOC_SLTH_POLICY_STATE_VEIL_DESCRIPTION', 'Allows: Diseased Corpses, Beast of Agares, Ritualist, Profane, Rosier, Mardero, Meshabber of Dis.', 'en_US'),
('LOC_SLTH_POLICY_STATE_LEAVES_DESCRIPTION', 'Allows: Fawn, Priest of the Leaves, High Priest of the Leaves, Kithra Kyriel, Yvain. ', 'en_US'),
('LOC_SLTH_POLICY_STATE_RUNES_DESCRIPTION', 'Allows: Soldier of Kilmorph, Paramander, Stonewarden, Runekeeper, Bambur, Arthedain, The Mithril Golem.', 'en_US'),
('LOC_SLTH_POLICY_STATE_ORDER_DESCRIPTION', 'Allows: Crusader, Basilica, Confessor, Prior, Valin Phanuel, Sphener', 'en_US'),
('LOC_SLTH_POLICY_STATE_OCTOPUS_DESCRIPTION', 'Allows:Drown, Stygian Guard, Asylum, Cultist, Speaker, Saverous, Hemah', 'en_US'),
('LOC_SLTH_POLICY_STATE_EMPYREAN_DESCRIPTION', 'Allows: Ratha, Radiant Guard, Vicar, Luridus, Chalid', 'en_US'),
('LOC_SLTH_POLICY_STATE_ESUS_DESCRIPTION', 'Allows: Nightwatch, Shadowrider, Shadow, Gibbon Goetia', 'en_US');