INSERT OR REPLACE INTO LocalizedText(Tag, Text, Language) VALUES
('LOC_BARBARIAN_CLAN_TYPE_SCORPION', 'Scorpion Clan', 'en_US'),
('LOC_BARBARIAN_CLAN_SCORPION_1', 'Goblin Fort', 'en_US'),
('LOC_BARBARIAN_CLAN_TYPE_SKELETON', 'Skeleton', 'en_US'),
('LOC_BARBARIAN_CLAN_SKELETON_1', 'Barrows', 'en_US'),
('LOC_BARBARIAN_CLAN_TYPE_LIZARDMEN', 'Lizardmen Clan', 'en_US'),
('LOC_BARBARIAN_CLAN_LIZARDMEN_1', 'Ruins', 'en_US'),
('LOC_BARBARIAN_CLAN_TYPE_BEARS', 'Bear Den', 'en_US'),
('LOC_BARBARIAN_CLAN_BEAR_1', 'Bear Den', 'en_US'),
('LOC_BARBARIAN_CLAN_TYPE_LION', 'Lion Den', 'en_US'),
('LOC_BARBARIAN_CLAN_LION_1', 'Lion Den', 'en_US');