INSERT OR REPLACE INTO LocalizedText(Tag, Text, Language) VALUES
('LOC_SLTH_UNIT_ABASHI_NAME', 'Abashi', 'en_US'),
('LOC_SLTH_UNIT_ACHERON_NAME', 'Acheron', 'en_US'),
('LOC_SLTH_UNIT_ADEPT_NAME', 'Adept', 'en_US'),
('LOC_SLTH_UNIT_ADVENTURER_NAME', 'Adventurer', 'en_US'),
('LOC_SLTH_UNIT_AIRSHIP_NAME', 'Airship', 'en_US'),
('LOC_SLTH_UNIT_AIR_ELEMENTAL_NAME', 'Air Elemental', 'en_US'),
('LOC_SLTH_UNIT_ALAZKAN_NAME', 'Alazkan', 'en_US'),
('LOC_SLTH_UNIT_ANGEL_NAME', 'Angel', 'en_US'),
('LOC_SLTH_UNIT_ANGEL_OF_DEATH_NAME', 'Angel Of Death', 'en_US'),
('LOC_SLTH_UNIT_ARCANE_BARGE_NAME', 'Arcane Barge', 'en_US'),
('LOC_SLTH_UNIT_ARCHER_NAME', 'Archer', 'en_US'),
('LOC_SLTH_UNIT_ARCHER_SCORPION_CLAN_NAME', 'Archer Scorpion Clan', 'en_US'),
('LOC_SLTH_UNIT_ARCHMAGE_NAME', 'Archmage', 'en_US'),
('LOC_SLTH_UNIT_ARQUEBUS_NAME', 'Arquebus', 'en_US'),
('LOC_SLTH_UNIT_ARS_NAME', 'Ars', 'en_US'),
('LOC_SLTH_UNIT_ARTHENDAIN_NAME', 'Arthendain', 'en_US'),
('LOC_SLTH_UNIT_ARTIST_NAME', 'Artist', 'en_US'),
('LOC_SLTH_UNIT_ASSASSIN_NAME', 'Assassin', 'en_US'),
('LOC_SLTH_UNIT_AUREALIS_NAME', 'Aurealis', 'en_US'),
('LOC_SLTH_UNIT_AURIC_ASCENDED_NAME', 'Auric Ascended', 'en_US'),
('LOC_SLTH_UNIT_AURIC_NAME', 'Auric', 'en_US'),
('LOC_SLTH_UNIT_AZER_NAME', 'Azer', 'en_US'),
('LOC_SLTH_UNIT_BABY_SPIDER_NAME', 'Baby Spider', 'en_US'),
('LOC_SLTH_UNIT_BALOR_NAME', 'Balor', 'en_US'),
('LOC_SLTH_UNIT_BAMBUR_NAME', 'Bambur', 'en_US'),
('LOC_SLTH_UNIT_BARNAXUS_NAME', 'Barnaxus', 'en_US'),
('LOC_SLTH_UNIT_BASIUM_NAME', 'Basium', 'en_US'),
('LOC_SLTH_UNIT_BATTERING_RAM_NAME', 'Battering Ram', 'en_US'),
('LOC_SLTH_UNIT_BATTLEMASTER_NAME', 'Battlemaster', 'en_US'),
('LOC_SLTH_UNIT_BEAR_NAME', 'Bear', 'en_US'),
('LOC_SLTH_UNIT_BEASTMAN_NAME', 'Beastman', 'en_US'),
('LOC_SLTH_UNIT_BEASTMASTER_NAME', 'Beastmaster', 'en_US'),
('LOC_SLTH_UNIT_BEAST_OF_AGARES_NAME', 'Beast Of Agares', 'en_US'),
('LOC_SLTH_UNIT_BERSERKER_NAME', 'Berserker', 'en_US'),
('LOC_SLTH_UNIT_BISON_RIDER_NAME', 'Bison Rider', 'en_US'),
('LOC_SLTH_UNIT_BLACK_WIND_NAME', 'Black Wind', 'en_US'),
('LOC_SLTH_UNIT_BLOODPET_NAME', 'Bloodpet', 'en_US'),
('LOC_SLTH_UNIT_BOARDING_PARTY_NAME', 'Boarding Party', 'en_US'),
('LOC_SLTH_UNIT_BOAR_RIDER_NAME', 'Boar Rider', 'en_US'),
('LOC_SLTH_UNIT_BONE_GOLEM_NAME', 'Bone Golem', 'en_US'),
('LOC_SLTH_UNIT_BRUJAH_NAME', 'Brujah', 'en_US'),
('LOC_SLTH_UNIT_BUBOES_NAME', 'Buboes', 'en_US'),
('LOC_SLTH_UNIT_CAMEL_ARCHER_NAME', 'Camel Archer', 'en_US'),
('LOC_SLTH_UNIT_CANNON_NAME', 'Cannon', 'en_US'),
('LOC_SLTH_UNIT_CARAVEL_NAME', 'Caravel', 'en_US'),
('LOC_SLTH_UNIT_CATAPULT_NAME', 'Catapult', 'en_US'),
('LOC_SLTH_UNIT_CENTAUR_ARCHER_NAME', 'Centaur Archer', 'en_US'),
('LOC_SLTH_UNIT_CENTAUR_CHARGER_NAME', 'Centaur Charger', 'en_US'),
('LOC_SLTH_UNIT_CENTAUR_LANCER_NAME', 'Centaur Lancer', 'en_US'),
('LOC_SLTH_UNIT_CENTAUR_NAME', 'Centaur', 'en_US'),
('LOC_SLTH_UNIT_CHALID_NAME', 'Chalid', 'en_US'),
('LOC_SLTH_UNIT_CHAMPION_NAME', 'Champion', 'en_US'),
('LOC_SLTH_UNIT_CHANTER_NAME', 'Chanter', 'en_US'),
('LOC_SLTH_UNIT_CHAOS_MARAUDER_NAME', 'Chaos Marauder', 'en_US'),
('LOC_SLTH_UNIT_CHARIOT_NAME', 'Chariot', 'en_US'),
('LOC_SLTH_UNIT_CHARIOT_SCORPION_CLAN_NAME', 'Chariot Scorpion Clan', 'en_US'),
('LOC_SLTH_UNIT_CLOCKWORK_GOLEM_NAME', 'Clockwork Golem', 'en_US'),
('LOC_SLTH_UNIT_COMMANDER_NAME', 'Commander', 'en_US'),
('LOC_SLTH_UNIT_CORLINDALE_NAME', 'Corlindale', 'en_US'),
('LOC_SLTH_UNIT_COURTESAN_NAME', 'Courtesan', 'en_US'),
('LOC_SLTH_UNIT_CROSSBOWMAN_NAME', 'Crossbowman', 'en_US'),
('LOC_SLTH_UNIT_CRUSADER_NAME', 'Crusader', 'en_US'),
('LOC_SLTH_UNIT_DEATH_KNIGHT_NAME', 'Death Knight', 'en_US'),
('LOC_SLTH_UNIT_DECIUS_NAME', 'Decius', 'en_US'),
('LOC_SLTH_UNIT_DEMAGOG_NAME', 'Demagog', 'en_US'),
('LOC_SLTH_UNIT_DEVOUT_NAME', 'Devout', 'en_US'),
('LOC_SLTH_UNIT_DISCIPLE_EMPYREAN_NAME', 'Disciple Empyrean', 'en_US'),
('LOC_SLTH_UNIT_DISCIPLE_FELLOWSHIP_OF_LEAVES_NAME', 'Disciple Fellowship Of Leaves', 'en_US'),
('LOC_SLTH_UNIT_DISCIPLE_OCTOPUS_OVERLORDS_NAME', 'Disciple Octopus Overlords', 'en_US'),
('LOC_SLTH_UNIT_DISCIPLE_OF_ACHERON_NAME', 'Disciple Of Acheron', 'en_US'),
('LOC_SLTH_UNIT_DISCIPLE_RUNES_OF_KILMORPH_NAME', 'Disciple Runes Of Kilmorph', 'en_US'),
('LOC_SLTH_UNIT_DISCIPLE_THE_ASHEN_VEIL_NAME', 'Disciple The Ashen Veil', 'en_US'),
('LOC_SLTH_UNIT_DISCIPLE_THE_ORDER_NAME', 'Disciple The Order', 'en_US'),
('LOC_SLTH_UNIT_DISEASED_CORPSE_NAME', 'Diseased Corpse', 'en_US'),
('LOC_SLTH_UNIT_DIVIDED_SOUL_NAME', 'Divided Soul', 'en_US'),
('LOC_SLTH_UNIT_DJINN_NAME', 'Djinn', 'en_US'),
('LOC_SLTH_UNIT_DONAL_NAME', 'Donal', 'en_US'),
('LOC_SLTH_UNIT_DRAGON_SLAYER_NAME', 'Dragon Slayer', 'en_US'),
('LOC_SLTH_UNIT_DRIFA_NAME', 'Drifa', 'en_US'),
('LOC_SLTH_UNIT_DROWN_NAME', 'Drown', 'en_US'),
('LOC_SLTH_UNIT_DRUID_NAME', 'Druid', 'en_US'),
('LOC_SLTH_UNIT_DUIN_NAME', 'Duin', 'en_US'),
('LOC_SLTH_UNIT_DWARVEN_CANNON_NAME', 'Dwarven Cannon', 'en_US'),
('LOC_SLTH_UNIT_DWARVEN_DRUID_NAME', 'Dwarven Druid', 'en_US'),
('LOC_SLTH_UNIT_DWARVEN_SHADOW_NAME', 'Dwarven Shadow', 'en_US'),
('LOC_SLTH_UNIT_DWARVEN_SLINGER_NAME', 'Dwarven Slinger', 'en_US'),
('LOC_SLTH_UNIT_DWARVEN_SOLDIER_RUNES_NAME', 'Dwarven Soldier Runes', 'en_US'),
('LOC_SLTH_UNIT_EARTH_ELEMENTAL_NAME', 'Earth Elemental', 'en_US'),
('LOC_SLTH_UNIT_EATER_OF_DREAMS_NAME', 'Eater Of Dreams', 'en_US'),
('LOC_SLTH_UNIT_EIDOLON_NAME', 'Eidolon', 'en_US'),
('LOC_SLTH_UNIT_EINHERJAR_NAME', 'Einherjar', 'en_US'),
('LOC_SLTH_UNIT_ELEPHANT_NAME', 'Elephant', 'en_US'),
('LOC_SLTH_UNIT_ENGINEER_NAME', 'Engineer', 'en_US'),
('LOC_SLTH_UNIT_EURABATRES_NAME', 'Eurabatres', 'en_US'),
('LOC_SLTH_UNIT_EYE_NAME', 'Eye', 'en_US'),
('LOC_SLTH_UNIT_FAWN_NAME', 'Fawn', 'en_US'),
('LOC_SLTH_UNIT_FIREBALL_NAME', 'Fireball', 'en_US'),
('LOC_SLTH_UNIT_FIREBOW_NAME', 'Firebow', 'en_US'),
('LOC_SLTH_UNIT_FIRE_ELEMENTAL_NAME', 'Fire Elemental', 'en_US'),
('LOC_SLTH_UNIT_FLAGBEARER_NAME', 'Flagbearer', 'en_US'),
('LOC_SLTH_UNIT_FLESH_GOLEM_NAME', 'Flesh Golem', 'en_US'),
('LOC_SLTH_UNIT_FLURRY_NAME', 'Flurry', 'en_US'),
('LOC_SLTH_UNIT_FREAK_NAME', 'Freak', 'en_US'),
('LOC_SLTH_UNIT_FRIGATE_NAME', 'Frigate', 'en_US'),
('LOC_SLTH_UNIT_FROSTLING_ARCHER_NAME', 'Frostling Archer', 'en_US'),
('LOC_SLTH_UNIT_FROSTLING_NAME', 'Frostling', 'en_US'),
('LOC_SLTH_UNIT_FROSTLING_WOLF_RIDER_NAME', 'Frostling Wolf Rider', 'en_US'),
('LOC_SLTH_UNIT_FYRDWELL_NAME', 'Fyrdwell', 'en_US'),
('LOC_SLTH_UNIT_GAELAN_NAME', 'Gaelan', 'en_US'),
('LOC_SLTH_UNIT_GALLEON_NAME', 'Galleon', 'en_US'),
('LOC_SLTH_UNIT_GALLEY_NAME', 'Galley', 'en_US'),
('LOC_SLTH_UNIT_GARGOYLE_NAME', 'Gargoyle', 'en_US'),
('LOC_SLTH_UNIT_GHOST_NAME', 'Ghost', 'en_US'),
('LOC_SLTH_UNIT_GIANT_SPIDER_NAME', 'Giant Spider', 'en_US'),
('LOC_SLTH_UNIT_GIANT_TORTOISE_NAME', 'Giant Tortoise', 'en_US'),
('LOC_SLTH_UNIT_GIBBON_NAME', 'Gibbon', 'en_US'),
('LOC_SLTH_UNIT_GILDEN_NAME', 'Gilden', 'en_US'),
('LOC_SLTH_UNIT_GOBLIN_NAME', 'Goblin', 'en_US'),
('LOC_SLTH_UNIT_GOBLIN_SCORPION_CLAN_NAME', 'Goblin Scorpion Clan', 'en_US'),
('LOC_SLTH_UNIT_GORILLA_NAME', 'Gorilla', 'en_US'),
('LOC_SLTH_UNIT_GOVANNON_NAME', 'Govannon', 'en_US'),
('LOC_SLTH_UNIT_GREATER_WEREWOLF_NAME', 'Greater Werewolf', 'en_US'),
('LOC_SLTH_UNIT_GRIFFON_NAME', 'Griffon', 'en_US'),
('LOC_SLTH_UNIT_GRIGORI_MEDIC_NAME', 'Grigori Medic', 'en_US'),
('LOC_SLTH_UNIT_GUARDIAN_VINES_NAME', 'Guardian Vines', 'en_US'),
('LOC_SLTH_UNIT_GURID_NAME', 'Gurid', 'en_US'),
('LOC_SLTH_UNIT_GUYBRUSH_NAME', 'Guybrush', 'en_US'),
('LOC_SLTH_UNIT_HARLEQUIN_NAME', 'Harlequin', 'en_US'),
('LOC_SLTH_UNIT_HAWK_NAME', 'Hawk', 'en_US'),
('LOC_SLTH_UNIT_HELLHOUND_NAME', 'Hellhound', 'en_US'),
('LOC_SLTH_UNIT_HEMAH_NAME', 'Hemah', 'en_US'),
('LOC_SLTH_UNIT_HERALD_NAME', 'Herald', 'en_US'),
('LOC_SLTH_UNIT_HERNE_NAME', 'Herne', 'en_US'),
('LOC_SLTH_UNIT_HIGH_PRIEST_OF_KILMORPH_NAME', 'High Priest Of Kilmorph', 'en_US'),
('LOC_SLTH_UNIT_HIGH_PRIEST_OF_LEAVES_NAME', 'High Priest Of Leaves', 'en_US'),
('LOC_SLTH_UNIT_HIGH_PRIEST_OF_THE_EMPYREAN_NAME', 'High Priest Of The Empyrean', 'en_US'),
('LOC_SLTH_UNIT_HIGH_PRIEST_OF_THE_ORDER_NAME', 'High Priest Of The Order', 'en_US'),
('LOC_SLTH_UNIT_HIGH_PRIEST_OF_THE_OVERLORDS_NAME', 'High Priest Of The Overlords', 'en_US'),
('LOC_SLTH_UNIT_HIGH_PRIEST_OF_THE_VEIL_NAME', 'High Priest Of The Veil', 'en_US'),
('LOC_SLTH_UNIT_HIGH_PRIEST_OF_WINTER_NAME', 'High Priest Of Winter', 'en_US'),
('LOC_SLTH_UNIT_HILL_GIANT_NAME', 'Hill Giant', 'en_US'),
('LOC_SLTH_UNIT_HORNGUARD_NAME', 'Hornguard', 'en_US'),
('LOC_SLTH_UNIT_HORSEMAN_NAME', 'Horseman', 'en_US'),
('LOC_SLTH_UNIT_HORSE_ARCHER_NAME', 'Horse Archer', 'en_US'),
('LOC_SLTH_UNIT_HUNTER_NAME', 'Hunter', 'en_US'),
('LOC_SLTH_UNIT_HYBOREM_NAME', 'Hyborem', 'en_US'),
('LOC_SLTH_UNIT_ICE_ELEMENTAL_NAME', 'Ice Elemental', 'en_US'),
('LOC_SLTH_UNIT_ILLUSIONIST_NAME', 'Illusionist', 'en_US'),
('LOC_SLTH_UNIT_IMMORTAL_NAME', 'Immortal', 'en_US'),
('LOC_SLTH_UNIT_IMP_NAME', 'Imp', 'en_US'),
('LOC_SLTH_UNIT_IRA_NAME', 'Ira', 'en_US'),
('LOC_SLTH_UNIT_IRON_GOLEM_NAME', 'Iron Golem', 'en_US'),
('LOC_SLTH_UNIT_JAVELIN_THROWER_NAME', 'Javelin Thrower', 'en_US'),
('LOC_SLTH_UNIT_KITHRA_NAME', 'Kithra', 'en_US'),
('LOC_SLTH_UNIT_KNIGHT_NAME', 'Knight', 'en_US'),
('LOC_SLTH_UNIT_KRAKEN_NAME', 'Kraken', 'en_US'),
('LOC_SLTH_UNIT_LEVIATHAN_NAME', 'Leviathan', 'en_US'),
('LOC_SLTH_UNIT_LICH_NAME', 'Lich', 'en_US'),
('LOC_SLTH_UNIT_LIGHTBRINGER_NAME', 'Lightbringer', 'en_US'),
('LOC_SLTH_UNIT_LIGHTNING_ELEMENTAL_NAME', 'Lightning Elemental', 'en_US'),
('LOC_SLTH_UNIT_LION_NAME', 'Lion', 'en_US'),
('LOC_SLTH_UNIT_LION_PRIDE_NAME', 'Lion Pride', 'en_US'),
('LOC_SLTH_UNIT_LIZARDMAN_ASSASSIN_NAME', 'Lizardman Assassin', 'en_US'),
('LOC_SLTH_UNIT_LIZARDMAN_BEASTMASTER_NAME', 'Lizardman Beastmaster', 'en_US'),
('LOC_SLTH_UNIT_LIZARDMAN_DRUID_NAME', 'Lizardman Druid', 'en_US'),
('LOC_SLTH_UNIT_LIZARDMAN_NAME', 'Lizardman', 'en_US'),
('LOC_SLTH_UNIT_LIZARDMAN_RANGER_NAME', 'Lizardman Ranger', 'en_US'),
('LOC_SLTH_UNIT_LOKI_NAME', 'Loki', 'en_US'),
('LOC_SLTH_UNIT_LONGBOWMAN_NAME', 'Longbowman', 'en_US'),
('LOC_SLTH_UNIT_LOSHA_NAME', 'Losha', 'en_US'),
('LOC_SLTH_UNIT_LUCIAN_NAME', 'Lucian', 'en_US'),
('LOC_SLTH_UNIT_LUNATIC_NAME', 'Lunatic', 'en_US'),
('LOC_SLTH_UNIT_LUONNOTAR_NAME', 'Luonnotar', 'en_US'),
('LOC_SLTH_UNIT_MAGE_NAME', 'Mage', 'en_US'),
('LOC_SLTH_UNIT_MAGNADINE_NAME', 'Magnadine', 'en_US'),
('LOC_SLTH_UNIT_MANES_NAME', 'Manes', 'en_US'),
('LOC_SLTH_UNIT_MANTICORE_NAME', 'Manticore', 'en_US'),
('LOC_SLTH_UNIT_MAN_O_WAR_NAME', 'Man O War', 'en_US'),
('LOC_SLTH_UNIT_MARDERO_NAME', 'Mardero', 'en_US'),
('LOC_SLTH_UNIT_MARGALARD_NAME', 'Margalard', 'en_US'),
('LOC_SLTH_UNIT_MARKSMAN_NAME', 'Marksman', 'en_US'),
('LOC_SLTH_UNIT_MAROS_NAME', 'Maros', 'en_US'),
('LOC_SLTH_UNIT_MARY_NAME', 'Mary', 'en_US'),
('LOC_SLTH_UNIT_MERCENARY_MOUNTED_NAME', 'Mercenary Mounted', 'en_US'),
('LOC_SLTH_UNIT_MERCENARY_NAME', 'Mercenary', 'en_US'),
('LOC_SLTH_UNIT_MERCHANT_NAME', 'Merchant', 'en_US'),
('LOC_SLTH_UNIT_MESHABBER_NAME', 'Meshabber', 'en_US'),
('LOC_SLTH_UNIT_METEOR_NAME', 'Meteor', 'en_US'),
('LOC_SLTH_UNIT_MIMIC_NAME', 'Mimic', 'en_US'),
('LOC_SLTH_UNIT_MINOTAUR_NAME', 'Minotaur', 'en_US'),
('LOC_SLTH_UNIT_MISTFORM_NAME', 'Mistform', 'en_US'),
('LOC_SLTH_UNIT_MITHRIL_GOLEM_NAME', 'Mithril Golem', 'en_US'),
('LOC_SLTH_UNIT_MOBIUS_WITCH_NAME', 'Mobius Witch', 'en_US'),
('LOC_SLTH_UNIT_MOKKA_NAME', 'Mokka', 'en_US'),
('LOC_SLTH_UNIT_MONK_NAME', 'Monk', 'en_US'),
('LOC_SLTH_UNIT_MOROI_NAME', 'Moroi', 'en_US'),
('LOC_SLTH_UNIT_MUD_GOLEM_NAME', 'Mud Golem', 'en_US'),
('LOC_SLTH_UNIT_MUIRIN_NAME', 'Muirin', 'en_US'),
('LOC_SLTH_UNIT_MYCONID_NAME', 'Myconid', 'en_US'),
('LOC_SLTH_UNIT_NIGHTWATCH_NAME', 'Nightwatch', 'en_US'),
('LOC_SLTH_UNIT_NULLSTONE_GOLEM_NAME', 'Nullstone Golem', 'en_US'),
('LOC_SLTH_UNIT_NYXKIN_NAME', 'Nyxkin', 'en_US'),
('LOC_SLTH_UNIT_OGRE_NAME', 'Ogre', 'en_US'),
('LOC_SLTH_UNIT_OGRE_WARCHIEF_NAME', 'Ogre Warchief', 'en_US'),
('LOC_SLTH_UNIT_OPHANIM_NAME', 'Ophanim', 'en_US'),
('LOC_SLTH_UNIT_ORTHUS_NAME', 'Orthus', 'en_US'),
('LOC_SLTH_UNIT_PALADIN_NAME', 'Paladin', 'en_US'),
('LOC_SLTH_UNIT_PARAMANDER_NAME', 'Paramander', 'en_US'),
('LOC_SLTH_UNIT_PHALANX_NAME', 'Phalanx', 'en_US'),
('LOC_SLTH_UNIT_PIRATE_NAME', 'Pirate', 'en_US'),
('LOC_SLTH_UNIT_PIT_BEAST_NAME', 'Pit Beast', 'en_US'),
('LOC_SLTH_UNIT_POLAR_BEAR_NAME', 'Polar Bear', 'en_US'),
('LOC_SLTH_UNIT_PRIEST_OF_KILMORPH_NAME', 'Priest Of Kilmorph', 'en_US'),
('LOC_SLTH_UNIT_PRIEST_OF_LEAVES_NAME', 'Priest Of Leaves', 'en_US'),
('LOC_SLTH_UNIT_PRIEST_OF_THE_EMPYREAN_NAME', 'Priest Of The Empyrean', 'en_US'),
('LOC_SLTH_UNIT_PRIEST_OF_THE_ORDER_NAME', 'Priest Of The Order', 'en_US'),
('LOC_SLTH_UNIT_PRIEST_OF_THE_OVERLORDS_NAME', 'Priest Of The Overlords', 'en_US'),
('LOC_SLTH_UNIT_PRIEST_OF_THE_VEIL_NAME', 'Priest Of The Veil', 'en_US'),
('LOC_SLTH_UNIT_PRIEST_OF_WINTER_NAME', 'Priest Of Winter', 'en_US'),
('LOC_SLTH_UNIT_PRIVATEER_NAME', 'Privateer', 'en_US'),
('LOC_SLTH_UNIT_PROPHET_NAME', 'Prophet', 'en_US'),
('LOC_SLTH_UNIT_PUPPET_LOKI_NAME', 'Puppet Loki', 'en_US'),
('LOC_SLTH_UNIT_PUPPET_NAME', 'Puppet', 'en_US'),
('LOC_SLTH_UNIT_PYRE_ZOMBIE_NAME', 'Pyre Zombie', 'en_US'),
('LOC_SLTH_UNIT_QUEEN_OF_THE_LINE_NAME', 'Queen Of The Line', 'en_US'),
('LOC_SLTH_UNIT_RADIANT_GUARD_NAME', 'Radiant Guard', 'en_US'),
('LOC_SLTH_UNIT_RANGER_NAME', 'Ranger', 'en_US'),
('LOC_SLTH_UNIT_RANTINE_NAME', 'Rantine', 'en_US'),
('LOC_SLTH_UNIT_RATHA_NAME', 'Ratha', 'en_US'),
('LOC_SLTH_UNIT_RATHUS_NAME', 'Rathus', 'en_US'),
('LOC_SLTH_UNIT_RAVENOUS_WEREWOLF_NAME', 'Ravenous Werewolf', 'en_US'),
('LOC_SLTH_UNIT_REPENTANT_ANGEL_NAME', 'Repentant Angel', 'en_US'),
('LOC_SLTH_UNIT_REVELERS_NAME', 'Revelers', 'en_US'),
('LOC_SLTH_UNIT_ROSIER_NAME', 'Rosier', 'en_US'),
('LOC_SLTH_UNIT_ROYAL_GUARD_NAME', 'Royal Guard', 'en_US'),
('LOC_SLTH_UNIT_SAILORS_DIRGE_NAME', 'Sailors Dirge', 'en_US'),
('LOC_SLTH_UNIT_SAND_LION_NAME', 'Sand Lion', 'en_US'),
('LOC_SLTH_UNIT_SATYR_NAME', 'Satyr', 'en_US'),
('LOC_SLTH_UNIT_SAVEROUS_NAME', 'Saverous', 'en_US'),
('LOC_SLTH_UNIT_SCIENTIST_NAME', 'Scientist', 'en_US'),
('LOC_SLTH_UNIT_SCORPION_NAME', 'Scorpion', 'en_US'),
('LOC_SLTH_UNIT_SCOUT_NAME', 'Scout', 'en_US'),
('LOC_SLTH_UNIT_SEA_SERPENT_NAME', 'Sea Serpent', 'en_US'),
('LOC_SLTH_UNIT_SERAPH_NAME', 'Seraph', 'en_US'),
('LOC_SLTH_UNIT_SEVERED_SOUL_NAME', 'Severed Soul', 'en_US'),
('LOC_SLTH_UNIT_SHADE_NAME', 'Shade', 'en_US'),
('LOC_SLTH_UNIT_SHADOWRIDER_NAME', 'Shadowrider', 'en_US'),
('LOC_SLTH_UNIT_SHADOW_NAME', 'Shadow', 'en_US'),
('LOC_SLTH_UNIT_SHAMAN_NAME', 'Shaman', 'en_US'),
('LOC_SLTH_UNIT_SKELETON_NAME', 'Skeleton', 'en_US'),
('LOC_SLTH_UNIT_SLAVE_NAME', 'Slave', 'en_US'),
('LOC_SLTH_UNIT_SON_OF_THE_INFERNO_NAME', 'Son Of The Inferno', 'en_US'),
('LOC_SLTH_UNIT_SPECTRE_NAME', 'Spectre', 'en_US'),
('LOC_SLTH_UNIT_SPHENER_NAME', 'Sphener', 'en_US'),
('LOC_SLTH_UNIT_SPIDERKIN_NAME', 'Spiderkin', 'en_US'),
('LOC_SLTH_UNIT_STEPHANOS_NAME', 'Stephanos', 'en_US'),
('LOC_SLTH_UNIT_STONESKIN_OGRE_NAME', 'Stoneskin Ogre', 'en_US'),
('LOC_SLTH_UNIT_STYGIAN_GUARD_NAME', 'Stygian Guard', 'en_US'),
('LOC_SLTH_UNIT_SUCCUBUS_NAME', 'Succubus', 'en_US'),
('LOC_SLTH_UNIT_SUPPLIES_NAME', 'Supplies', 'en_US'),
('LOC_SLTH_UNIT_SWORDSMAN_NAME', 'Swordsman', 'en_US'),
('LOC_SLTH_UNIT_TAR_DEMON_NAME', 'Tar Demon', 'en_US'),
('LOC_SLTH_UNIT_TASKMASTER_NAME', 'Taskmaster', 'en_US'),
('LOC_SLTH_UNIT_TEUTORIX_NAME', 'Teutorix', 'en_US'),
('LOC_SLTH_UNIT_TIGER_NAME', 'Tiger', 'en_US'),
('LOC_SLTH_UNIT_TREANT_NAME', 'Treant', 'en_US'),
('LOC_SLTH_UNIT_TREBUCHET_NAME', 'Trebuchet', 'en_US'),
('LOC_SLTH_UNIT_TRIREME_NAME', 'Trireme', 'en_US'),
('LOC_SLTH_UNIT_TUMTUM_NAME', 'Tumtum', 'en_US'),
('LOC_SLTH_UNIT_VALIN_NAME', 'Valin', 'en_US'),
('LOC_SLTH_UNIT_VALKYRIE_NAME', 'Valkyrie', 'en_US'),
('LOC_SLTH_UNIT_VAMPIRE_LORD_NAME', 'Vampire Lord', 'en_US'),
('LOC_SLTH_UNIT_VAMPIRE_NAME', 'Vampire', 'en_US'),
('LOC_SLTH_UNIT_WAR_ELEPHANT_NAME', 'War Elephant', 'en_US'),
('LOC_SLTH_UNIT_WAR_MACHINE_NAME', 'War Machine', 'en_US'),
('LOC_SLTH_UNIT_WAR_TORTOISE_NAME', 'War Tortoise', 'en_US'),
('LOC_SLTH_UNIT_WATER_ELEMENTAL_NAME', 'Water Elemental', 'en_US'),
('LOC_SLTH_UNIT_WEREWOLF_NAME', 'Werewolf', 'en_US'),
('LOC_SLTH_UNIT_WILBOMAN_NAME', 'Wilboman', 'en_US'),
('LOC_SLTH_UNIT_WIZARD_NAME', 'Wizard', 'en_US'),
('LOC_SLTH_UNIT_WOLF_NAME', 'Wolf', 'en_US'),
('LOC_SLTH_UNIT_WOLF_PACK_NAME', 'Wolf Pack', 'en_US'),
('LOC_SLTH_UNIT_WOLF_RIDER_NAME', 'Wolf Rider', 'en_US'),
('LOC_SLTH_UNIT_WOLF_RIDER_SCORPION_CLAN_NAME', 'Wolf Rider Scorpion Clan', 'en_US'),
('LOC_SLTH_UNIT_WOOD_GOLEM_NAME', 'Wood Golem', 'en_US'),
('LOC_SLTH_UNIT_WRAITH_NAME', 'Wraith', 'en_US'),
('LOC_SLTH_UNIT_WRATH_NAME', 'Wrath', 'en_US'),
('LOC_SLTH_UNIT_YERSINIA_NAME', 'Yersinia', 'en_US'),
('LOC_SLTH_UNIT_YVAIN_NAME', 'Yvain', 'en_US'),
('LOC_UNIT_WARRIOR_NAME', 'Warrior', 'en_US'),
('LOC_SLTH_UNIT_ABASHI_DESCRIPTION', 'The Sheaim hero is able to breathe fire, and her roar will convert any surrounding cult of the dragon units to her cause. She is also immune to magic and weaker units will often be too afraid to attack her.', 'en_US'),
('LOC_SLTH_UNIT_ACHERON_DESCRIPTION', 'Acheron is both immune to magic and able to cast the strong ranged ability meteor.', 'en_US'),
('LOC_SLTH_UNIT_ADEPT_DESCRIPTION', 'Adepts have the ability to learn spell spheres when they level up, giving them access to a wide variety of spells.', 'en_US'),
('LOC_SLTH_UNIT_ADVENTURER_DESCRIPTION', 'An Adventurer is a hero unit that can be upgraded to any of the Melee, Archer, Mounted, Recon, or Adept units the owning civilization can build. They will gain 1 experience point per turn up to 100 experience points and can quickly become powerful units.', 'en_US'),
('LOC_SLTH_UNIT_AIRSHIP_DESCRIPTION', 'The Airship allows the Kuriotates to transport units. Its especially important when they arent able to create any cities on a coast and they need to be able to produce transport ships from inland cities.', 'en_US'),
('LOC_SLTH_UNIT_AIR_ELEMENTAL_DESCRIPTION', 'Although weak for a rank 3 summon, an Air Elemental can pass over any terrain, including water tiles, and it can see 2 tiles further than other units. Upon winning a combat, Air Elementals will summon [LINK=UNIT_LIGHTNING_ELEMENTAL]Lightning Elementals[/LINK].', 'en_US'),
('LOC_SLTH_UNIT_ALAZKAN_DESCRIPTION', 'Alazkan starts with the hidden nationality and hero promotions, a potent combination for harassment of supposed allies, but most useful is his mirror ability, which summons an illusionary duplicate. Illusions cannot kill units, but are perfect for weakening any defender for Alazkan to kill without leaving him left weakened for retaliation. Both Alazkan and his mirror image will have the marksman promotion as well.', 'en_US'),
('LOC_SLTH_UNIT_ANGEL_DESCRIPTION', 'Angels are awarded to the Mercurians when good people die. This could be from a good* unit being killed, in which case they are made into an angel and maintain their experience to spend on new skills, or when a good city is razed. Angels are the only units that can be upgraded into the Mercurians most powerful units, so a healthy supply is crucial to their conquest of Erebus.[NEWLINE][NEWLINE]*Good units are those who follow the Empyrean, the Order or the Runes of Kilmorph religion. It also includes any living unit from the Mercurian civilization except for animal units.', 'en_US'),
('LOC_SLTH_UNIT_ANGEL_OF_DEATH_DESCRIPTION', 'Angels of Death are invisible and start with the Reaper promotion, decreasing the population of cities they attack by 1.', 'en_US'),
('LOC_SLTH_UNIT_ARCANE_BARGE_DESCRIPTION', 'Use the Arcane Barges fireballs to destroy other ships and land units that are within range.', 'en_US'),
('LOC_SLTH_UNIT_ARCHER_DESCRIPTION', 'With no resource requirement and a bonus to city defense, archers allow even the most frugal of empires to properly defend their cities. Archers have full access to the City Garrison promotions, making them even more powerful city defenders as they level.', 'en_US'),
('LOC_SLTH_UNIT_ARCHMAGE_DESCRIPTION', 'The games most powerful spellcaster. An archmage can learn rank 3 sorcery spells. A civilization can only have 3 Archmages at once and a Mage has to be at least 6th level before it can be upgraded to an Archmage.', 'en_US'),
('LOC_SLTH_UNIT_ARQUEBUS_DESCRIPTION', 'The Arquebus is the only unit that ignores building defenses, making it perfect for attacks on well defended cities.', 'en_US'),
('LOC_SLTH_UNIT_ARS_DESCRIPTION', 'The 4th Horseman of the Apocalypse.', 'en_US'),
('LOC_SLTH_UNIT_ARTHENDAIN_DESCRIPTION', 'Arthendain will only join Runes of Kilmorph civilizations. He is a healer who is able to cure disease on units in the same stack and is immune to disease himself.', 'en_US'),
('LOC_SLTH_UNIT_ASSASSIN_DESCRIPTION', 'Assassins attack the weakest unit in the defending stack, making them perfect for picking off enemy mages even in the best defended cities and stacks.', 'en_US'),
('LOC_SLTH_UNIT_AUREALIS_DESCRIPTION', 'The Aurealis is the only summon in the game that has affinity 2 to a mana type. Making it very effective for players that concentrate on Sun mana.', 'en_US'),
('LOC_SLTH_UNIT_AURIC_ASCENDED_DESCRIPTION', 'Having Ascended to Godhood, Auric is nearly unstoppable. Unless a relic from ages past can level the playing field.', 'en_US'),
('LOC_SLTH_UNIT_AZER_DESCRIPTION', 'A Fire elemental variant.', 'en_US'),
('LOC_SLTH_UNIT_BABY_SPIDER_DESCRIPTION', 'Produced by a Giant Spider defeating a unit.', 'en_US'),
('LOC_SLTH_UNIT_BALOR_DESCRIPTION', 'Balors do not cause collateral damage, but they start with the stigmata promotion, giving them a bonus equal to half the Armageddon Counter.', 'en_US'),
('LOC_SLTH_UNIT_BAMBUR_DESCRIPTION', 'Bambur will only join Runes of Kilmorph civilizations. Bambur is a warrior and weaponsmith, and is able provide weapons to melee units in his stack.', 'en_US'),
('LOC_SLTH_UNIT_BARNAXUS_DESCRIPTION', 'If Barnaxus has the Combat I-Combat V promotions, all golems in his empire will have a higher strength. Success of the Luchuirp is dependant on the players ability to level up Barnaxus and gain those promotions. If Barnaxus is killed his pieces will be claimed by the unit that destroyed him, a player that can recover those pieces can rebuild him in one of the Luchuirp cities.', 'en_US'),
('LOC_SLTH_UNIT_BASIUM_DESCRIPTION', 'Never one to sit back, Basium is glad to join his troops on the front line. Although powerful, a civilization that wages war with him risks his death. If Basium is lost the civilization suffers the loss of its traits.', 'en_US'),
('LOC_SLTH_UNIT_BATTERING_RAM_DESCRIPTION', 'Battering Rams can only be created by Khazad melee units. To create a Battering Ram the unit must be in a Forest tile and use the Create Battering Ram ability.', 'en_US'),
('LOC_SLTH_UNIT_BATTLEMASTER_DESCRIPTION', 'Battlemasters fill the same roll as Champions from other civilizations, namely bringing force to bear on cities. They do not require buildings, however, and gain a large strength bonus on tundra.', 'en_US'),
('LOC_SLTH_UNIT_BEAR_DESCRIPTION', 'Bears that wander into a terrain that will support a bear den may settle there and form a den. Dens will occasionally spawn new bears that will wander out into the world and settle new dens.', 'en_US'),
('LOC_SLTH_UNIT_BEASTMAN_DESCRIPTION', 'Beastmen gain +20% attacking cities, making them powerful early rush units.', 'en_US'),
('LOC_SLTH_UNIT_BEASTMASTER_DESCRIPTION', 'The top fighter of the Recon line. A Beastmaster combines his own strength with those of the animals that accompany him (and a bizarre crotch biting weasel). He also converts defeated animals and the rare beast class unit. A Grove is required to train this national unit.', 'en_US'),
('LOC_SLTH_UNIT_BEAST_OF_AGARES_DESCRIPTION', 'These fell beasts, exclusive to the [LINK=RELIGION_THE_ASHEN_VEIL]Veil[\\LINK], are great at turning back the holy warriors of other religions, but beware, the Beast will consume 4 population from your cities when it is produced and your citizens will revolt for 4 turns after producing one of these in their city.[NEWLINE][NEWLINE]Infernal players that build Beasts of Agares dont suffer the population loss or the revolt in their cities.', 'en_US'),
('LOC_SLTH_UNIT_BERSERKER_DESCRIPTION', 'A powerful attacking unit that causes collateral damage to units in the opponents stack. Their defense is low, so they are most effective when teamed up with high defense units like archers to protect from enemy retaliation.', 'en_US'),
('LOC_SLTH_UNIT_BISON_RIDER_DESCRIPTION', 'Bison Riders are a bit slower than other knights, but they make up for that with greater strength.', 'en_US'),
('LOC_SLTH_UNIT_BLACK_WIND_DESCRIPTION', 'Starting with hidden nationality and hero allows the Black Wind to become the terror of the seas, regardless of any landlubber "treaties."', 'en_US'),
('LOC_SLTH_UNIT_BLOODPET_DESCRIPTION', 'As good as any warrior at early defense and exploration, when fed upon by a vampire using "feed" the vampire will be granted an extra movement and ability to attack again.', 'en_US'),
('LOC_SLTH_UNIT_BOARDING_PARTY_DESCRIPTION', 'Although capable fighters on their own, Boarding parties are also able to attack naval units. And if they win, the naval unit comes under their control. They require a harbor to train and gain strength from metal resources as with other melee units.', 'en_US'),
('LOC_SLTH_UNIT_BOAR_RIDER_DESCRIPTION', 'Boar Riders are the worst Horseman in the game. But itÃƒâ€šÃ¢â‚¬â„¢s a dwarf on a pig, what do you expect?', 'en_US'),
('LOC_SLTH_UNIT_BONE_GOLEM_DESCRIPTION', 'Bone Golems are Immortal replacements that can be built directly. Being golems, their resurrection wont save you a highly promoted unit, but will save you needing to build another.', 'en_US'),
('LOC_SLTH_UNIT_BRUJAH_DESCRIPTION', 'Brujah are functionally identical to Berserkers, causing collateral damage to four other units when attacking stacks. They also start with the vampire promotion and the abilities that come with it, as well as first level death and body spells.', 'en_US'),
('LOC_SLTH_UNIT_BUBOES_DESCRIPTION', 'The 2nd Horseman.', 'en_US'),
('LOC_SLTH_UNIT_CAMEL_ARCHER_DESCRIPTION', 'Camel Archers are identical to other civilizations Horse Archers except they dont require horses, which are hard to find in the Malakims deserts.', 'en_US'),
('LOC_SLTH_UNIT_CANNON_DESCRIPTION', 'Cannons are more powerful siege engines than catapults, but fill the same roles: lowering city defense bonuses and causing collateral damage. They require the gunpowder resource.', 'en_US'),
('LOC_SLTH_UNIT_CARAVEL_DESCRIPTION', 'The Caravel is a second tier scout ship, with the added ability to explore enemy territory. Its one cargo space allows you to move recon or other units to distant lands, or take the longshoreman promotion for added mobility.', 'en_US'),
('LOC_SLTH_UNIT_CATAPULT_DESCRIPTION', 'Early siege engines can take the place of mages, being useful for lowering city defense bonuses and causing collateral damage to stacks. High withdrawal rates allow them to survive against even well defended stacks. They require no resources but the city must have the expensive siege workshop building.', 'en_US'),
('LOC_SLTH_UNIT_CENTAUR_ARCHER_DESCRIPTION', 'Centaur Archers are great balanced units for harassing your enemies, mobile enough to cross your empire quickly and their defensive strikes make them able city defenders.', 'en_US'),
('LOC_SLTH_UNIT_CENTAUR_CHARGER_DESCRIPTION', 'The Kuriotate Centaur Charger has two advantages over the Chariot it replaces: it requires neither the horse resource, nor the expensive siege workshop building. Their use remains the same. They have good withdrawal and high attack, providing a decent way to soften up advanced enemy units, although their defense is low so consider sending them in with some of their Centaur Archer brethren for protection.', 'en_US'),
('LOC_SLTH_UNIT_CENTAUR_DESCRIPTION', 'The Kuriotate Centaurs require no resource or building, and gain defensive bonuses from terrain or cities, unlike other civs mounted units. So in addition to the Horsemans role of softening up strong foes with withdrawal or pillaging, they can function as mobile defenders for distant settlements. They dont gain any added strength from being built in cities with the Nightmare resource, however.', 'en_US'),
('LOC_SLTH_UNIT_CENTAUR_LANCER_DESCRIPTION', 'Centaur Lancers are just like knights except they dont require access to horses to build and they have access to the Centaur specific Sprint ability.', 'en_US'),
('LOC_SLTH_UNIT_CHALID_DESCRIPTION', 'Chalid is a very versatile Hero. He can cast any spells available to an Empyrean High Priest and Archmage with Sun or Law spheres, and he gains affinity from Sun Mana.', 'en_US'),
('LOC_SLTH_UNIT_CHAMPION_DESCRIPTION', 'Champions are the upgrades of Axemen and Swordsmen. Their main role remains the same, primarily conquest of enemy cities. They can upgrade into any of three or four quite different units, so consider your goal when choosing promotions for them.', 'en_US'),
('LOC_SLTH_UNIT_CHANTER_DESCRIPTION', 'The Chanter not only has the abilities typical of an assassin, but the ability to teleport back to his capital if needed.', 'en_US'),
('LOC_SLTH_UNIT_CHAOS_MARAUDER_DESCRIPTION', 'Chaos Marauders may appear in Sheaim cities with Planar Gates and Carnivals.', 'en_US'),
('LOC_SLTH_UNIT_CHARIOT_DESCRIPTION', 'Chariots require both a siege workshop and horses, but provide a unit a decent way to soften up advanced enemy units with their strong attack and withdrawal. They lack much defensive strength, though, so they need a protected place to retreat to if they are to survive retaliation.', 'en_US'),
('LOC_SLTH_UNIT_CLOCKWORK_GOLEM_DESCRIPTION', 'Clockwork Golems are functionally identical to Berserkers, causing collateral damage to four other units when attacking stacks. They require the Machinery technology instead of Rage, however, and start with higher strength. Being golems prevents leveling up to take promotions.', 'en_US'),
('LOC_SLTH_UNIT_COMMANDER_DESCRIPTION', 'Great Generals can be used to draft units from a city in a pinch, or build a city a Command Post, which adds experience to units. It also buffs adjacent units combat strength.', 'en_US'),
('LOC_SLTH_UNIT_CORLINDALE_DESCRIPTION', 'Corlindale makes a superb mage, though if his magic cant protect you, his diplomacy will. He can be sacrificed to make peace between your civ and all current enemies, pushing their troops outside your borders. Beware of enemy assassins, because he will be simple to eliminate should one piece your defenses.', 'en_US'),
('LOC_SLTH_UNIT_COURTESAN_DESCRIPTION', 'The courtesan is invisible to most units, and attacks the weakest unit in a stack. The perfect counter to powerful High Priests or Archmages.', 'en_US'),
('LOC_SLTH_UNIT_CROSSBOWMAN_DESCRIPTION', 'Crossbowmen are the ultimate city defenders, and a well promoted one will make a city nearly impenetrable without a lengthy siege or fearsome magic-so it may prove wise to back them up with a handful of assassins or marksmen to eliminate these threats.', 'en_US'),
('LOC_SLTH_UNIT_CRUSADER_DESCRIPTION', 'Use the Crusader to counter your opponents Demonic units. Not only do they get a strength bonus against demons, but they are immune to disease, making them perfect to send into an area to eliminate any diseases the Ashen Veil and their Diseased Corpses have spread.', 'en_US'),
('LOC_SLTH_UNIT_DEATH_KNIGHT_DESCRIPTION', 'The Death Knight combines the strength and mobility of a typical knight with the ability to cast Death Spells.', 'en_US'),
('LOC_SLTH_UNIT_DEMAGOG_DESCRIPTION', 'The Demagog is designed for fast mobilization, costing half as much as a champion. But they will abandon you when the crusade is over.', 'en_US'),
('LOC_SLTH_UNIT_DEVOUT_DESCRIPTION', 'Devouts can travel through rival territory without open borders and start with sanctify, so they are useful to keep the Armageddon counter low despite foreign wars by sanctifying city ruins. The do not have the marksman promotion, however.', 'en_US'),
('LOC_SLTH_UNIT_DISCIPLE_EMPYREAN_DESCRIPTION', 'Starts with the Medic Promotion, buffing adjacent healing, and can spread the Empyrean religion to cities.', 'en_US'),
('LOC_SLTH_UNIT_DISCIPLE_FELLOWSHIP_OF_LEAVES_DESCRIPTION', 'Starts with the Medic Promotion, buffing adjacent healing, and can spread the Fellowship Of Leaves religion to cities.', 'en_US'),
('LOC_SLTH_UNIT_DISCIPLE_OCTOPUS_OVERLORDS_DESCRIPTION', 'Starts with the Medic Promotion, buffing adjacent healing, and can spread the Octopus Overlords religion to cities.', 'en_US'),
('LOC_SLTH_UNIT_DISCIPLE_OF_ACHERON_DESCRIPTION', 'Obsessed with the Dragon Acheron, this units can upgrade to the dangerous Sons of the Inferno spellcasters if left unchecked.', 'en_US'),
('LOC_SLTH_UNIT_DISCIPLE_RUNES_OF_KILMORPH_DESCRIPTION', 'Starts with the Medic Promotion, buffing adjacent healing, and can spread the Runes of Kilmorph religion to cities.', 'en_US'),
('LOC_SLTH_UNIT_DISCIPLE_THE_ASHEN_VEIL_DESCRIPTION', 'Starts with the Medic Promotion, buffing adjacent healing, and can spread the Ashen Veil religion to cities.', 'en_US'),
('LOC_SLTH_UNIT_DISCIPLE_THE_ORDER_DESCRIPTION', 'Starts with the Medic Promotion, buffing adjacent healing, and can spread the Order religion to cities.', 'en_US'),
('LOC_SLTH_UNIT_DISEASED_CORPSE_DESCRIPTION', 'Use them to spread disease to your opponents units.', 'en_US'),
('LOC_SLTH_UNIT_DIVIDED_SOUL_DESCRIPTION', 'Divided Souls can separate their souls from their body and allow them to wander immune to attack or notice. If the Severed Soul is in a place the Divided Soul can enter it can call the Divided Soul to it.', 'en_US'),
('LOC_SLTH_UNIT_DJINN_DESCRIPTION', 'Djinn have affinity with all mana types, they become very powerful for players with access to a lot of mana.', 'en_US'),
('LOC_SLTH_UNIT_DONAL_DESCRIPTION', 'The Bannor hero can recruit a random assortment of units. This ability is regained once he kills a demon or undead. He also has a defense increase from his unique equipment.', 'en_US'),
('LOC_SLTH_UNIT_DRAGON_SLAYER_DESCRIPTION', 'Dont let the name fool you, Dragon Slayers are proficient fighters against human opponents as well, and their courage promotion takes some burden off of your spell casters.', 'en_US'),
('LOC_SLTH_UNIT_DRIFA_DESCRIPTION', 'The Illian Dragon, only buildable once the Illians have destroyed a civilization.', 'en_US'),
('LOC_SLTH_UNIT_DROWN_DESCRIPTION', 'The Overlords special unit is the games earliest Undead unit. They are just as strong as Axeman but capable of traveling through coast tiles. As Undead they are also immune to disease, making them a good counter for an opponent fond of Diseased Corpse units.', 'en_US'),
('LOC_SLTH_UNIT_DRUID_DESCRIPTION', 'Druids are the only units outside of the Disciple line that have the Medic I promotion. They also have a high strength for a spell casting unit and have access to all levels of Nature magic.', 'en_US'),
('LOC_SLTH_UNIT_DUIN_DESCRIPTION', 'Reborn in the land by unknown means, Duin has been cursed with Lycanthropy: every living unit he slays becomes a Ravenous Werewolf that will follow him.', 'en_US'),
('LOC_SLTH_UNIT_DWARVEN_CANNON_DESCRIPTION', 'The Khazad have the most powerful cannons in the game. They are the fastest way to destroy your enemies cities defenses.', 'en_US'),
('LOC_SLTH_UNIT_DWARVEN_DRUID_DESCRIPTION', 'Less attuned to the workings of ecosystems and organisms, Dwarven druids instead command the earth sphere of magic.', 'en_US'),
('LOC_SLTH_UNIT_DWARVEN_HORNGUARD_DESCRIPTION', 'What can be more fearsome than a charging rhinoceros with a yelling, drinking, dwarven rider? Well, the dwarf isnt "riding" so much as hanging on for dear life. Compared to other Knights Hornguards are slower but more powerful.', 'en_US'),
('LOC_SLTH_UNIT_DWARVEN_SHADOW_DESCRIPTION', 'Council of Esus recon unit that is Invisible. Causes collateral damage. Can do operations in foreign cities. A civ can have a max of 4.', 'en_US'),
('LOC_SLTH_UNIT_DWARVEN_SLINGER_DESCRIPTION', 'COPY ARCHER', 'en_US'),
('LOC_SLTH_UNIT_EARTH_ELEMENTAL_DESCRIPTION', 'A powerful but slow unit. The summoner has to get close to unleash it on its victims, but it is a formidable city or unit attacker, and even better, the summoner can summon a new one next turn.', 'en_US'),
('LOC_SLTH_UNIT_EATER_OF_DREAMS_DESCRIPTION', 'The Eater of Dreams can sacrifice population in cities to regain the ability to cast with his "Consume Souls" ability. This makes him a powerful defender in large cities, and able to summon multiple Balors or Fire Elementals if the city is big enough to provide him fresh victims.', 'en_US'),
('LOC_SLTH_UNIT_EIDOLON_DESCRIPTION', 'Eidolons are demon disciple units that offer alternate upgrades for Champions and Priests. They require Iron or Mithril and an evil alignment, but no specific building. Priest upgraded Eidolons keep their spells, and melee upgraded Eidolons keep any melee-only promotions they have acquired, so consider upgrading rather than building directly. In any case, they multi-use units with high strength and free march promotion.', 'en_US'),
('LOC_SLTH_UNIT_EINHERJAR_DESCRIPTION', 'Summon Einherjar to wipe out hordes of weaker units. Their duration is increased by a turn if they defeat an opponent in combat, allowing them to remain indefinitely if they fight every turn.', 'en_US'),
('LOC_SLTH_UNIT_ELEPHANT_DESCRIPTION', 'Elephants roam the wilds of Erebus. These massive behemoths are obstacles to early exploration, but will not attack. If captured they can be upgraded to units quite capable on the offense, though.', 'en_US'),
('LOC_SLTH_UNIT_EURABATRES_DESCRIPTION', 'Cmon, its a dragon! Build him already, Eurabatres strength is unmatched.', 'en_US'),
('LOC_SLTH_UNIT_EYE_DESCRIPTION', 'Floating Eyes are created by the Floating Eye spell. Use them to uncover invisible units and safely explore the surrounding lands.', 'en_US'),
('LOC_SLTH_UNIT_FAWN_DESCRIPTION', 'Fawns are terrific defenders in wooded tiles for their time, and make useful troops for players who have rushed the Fellowship of the Leaves religion before being able to build many tier two units. They can be upgraded to Satyrs later.', 'en_US'),
('LOC_SLTH_UNIT_FIREBALL_DESCRIPTION', 'Although not as powerful as some summons fireballs are favored by mages for their utility. They do collateral damage to stacks and can bombard city defenses. Since they fly they can strike distant targets, even those across water like nearby enemy ships. Also unlike other summons your enemies wont gain any experience for defeating fireballs, making them perfect for wearing away at their defenses.', 'en_US'),
('LOC_SLTH_UNIT_FIREBOW_DESCRIPTION', 'The Amurite longbowman is as proficient with fire magic as he is with his bow, making for a deadly defender and collateral damage attacker. Even better, it can do both at the same time, hitting nearby opponents with fireballs on its turn and being available to defend its city or stack on opponents turns.', 'en_US'),
('LOC_SLTH_UNIT_FIRE_ELEMENTAL_DESCRIPTION', 'Fire Elementals grow more powerful for each Fire node you own. Players wishing to equip their archmages with these summons would do well to concentrate on fire mana, battle for additional nodes they can convert and build a tower of elements which will make all of their elementals stronger. Although Fire elementals are immune to fire damage they are notoriously ill behaved and refuse to enter frozen areas.', 'en_US'),
('LOC_SLTH_UNIT_FLAGBEARER_DESCRIPTION', 'Useful added to your stacks, Flagbearers will give allied units nearby a bonus to attack and city attack.', 'en_US'),
('LOC_SLTH_UNIT_FLESH_GOLEM_DESCRIPTION', 'Flesh Golems are created with the Graft Flesh spell. Their strength can be increased by sacrificing other units to add their body parts to the Flesh Golem.', 'en_US'),
('LOC_SLTH_UNIT_FLURRY_DESCRIPTION', 'A Flurry starts with the Blitz promotion and a 2 movement rate making it an excellent way to kill separate units, or clean up a stack after an Archmage has weakened it. Because of the Blitz promotion, the Flurry becomes even more powerful as it gains Mobility promotions.', 'en_US'),
('LOC_SLTH_UNIT_FREAK_DESCRIPTION', 'Freaks start mutated, giving them a wide range of random good and bad promotions. Use freaks with strong military promotions to supplement and army and sacrifice your weak freaks to create Freak Shows in your cities.', 'en_US'),
('LOC_SLTH_UNIT_FRIGATE_DESCRIPTION', 'Build to transport units safely, or bombard coastal cities defensive bonus.', 'en_US'),
('LOC_SLTH_UNIT_FROSTLING_ARCHER_DESCRIPTION', 'Spawned by Samhain, these ornery units will raid anyone.', 'en_US'),
('LOC_SLTH_UNIT_FROSTLING_DESCRIPTION', 'Spawned by Samhain, these ornery units will raid anyone.', 'en_US'),
('LOC_SLTH_UNIT_FROSTLING_WOLF_RIDER_DESCRIPTION', 'Spawned by Samhain, these ornery units will raid anyone.', 'en_US'),
('LOC_SLTH_UNIT_FYRDWELL_DESCRIPTION', 'Frydwell units are functionally identical to the Horse Archers that they replace but require deer instead of horses. They are still excellent at weakening strong units with their withdrawal chance or hitting invaders who show up in unexpected locations.', 'en_US'),
('LOC_SLTH_UNIT_GAELAN_DESCRIPTION', 'WHO?', 'en_US'),
('LOC_SLTH_UNIT_GALLEON_DESCRIPTION', 'DEBUG unit to transport units, kinda irrelevant given embark', 'en_US'),
('LOC_SLTH_UNIT_GALLEY_DESCRIPTION', 'Ancient era melee naval combat unit. Can only operate on Coastal waters until Astronomy is researched.', 'en_US'),
('LOC_SLTH_UNIT_GARGOYLE_DESCRIPTION', 'Gargoyles are perfect defenders for cities, as they start with the defensive promotion, allowing for an additional 25% fortification bonus. And your foes will never walk past a cathedral or mausoleum again.', 'en_US'),
('LOC_SLTH_UNIT_GHOST_DESCRIPTION', 'Ghosts have the same uses as assassins, starting with the marksman promotion which causes them to target weaker units first. Additionally, they can turn invisible at will, unless they have attacked this turn. This allows them to get to their target with ease, though surviving retribution may prove more challenging. They will keep this ability should they upgrade to Marksmen.', 'en_US'),
('LOC_SLTH_UNIT_GIANT_SPIDER_DESCRIPTION', 'Giant Spiders can produce Baby Spiders when killing a unit, and is invisible except next to True Sight enemies or Recon units. A capturable barbarian Animal unit that spawns in Woods, can be used to build a Spider Den that provides Silk in cities with a Carnival', 'en_US'),
('LOC_SLTH_UNIT_GIANT_TORTOISE_DESCRIPTION', 'DEBUG UHH', 'en_US'),
('LOC_SLTH_UNIT_GIBBON_DESCRIPTION', 'The Council of Esus Hero, this shapeshifter can Impersonate the leader of another Civ, granting brief control of the civ. Gibbon is also an early Channeling III spellcaster.', 'en_US'),
('LOC_SLTH_UNIT_GILDEN_DESCRIPTION', 'The Ljosalfar hero is one of the earliest, allowing the elves to go on the offensive before city defense of their opponents forces them to bring along arcane units. If built after the Ljosalfar archery range, he should benefit from the +1 bonus attack strength it supplies to archers.', 'en_US'),
('LOC_SLTH_UNIT_GOBLIN_DESCRIPTION', 'Goblins that defeat wolves in combat are automatically upgraded to Wolf Riders.', 'en_US'),
('LOC_SLTH_UNIT_GORILLA_DESCRIPTION', 'A capturable barbarian Animal unit that spawns in Rainforest, can be used to build a Gorilla Cage in cities with a Carnival.', 'en_US'),
('LOC_SLTH_UNIT_GOVANNON_DESCRIPTION', 'Govannon is a capable spell caster in his own right, all the more so as a hero. But his true use lies in teaching several useful adept spells to any unit once he learns them himself, including haste, dance of blades, and raise skeleton.', 'en_US'),
('LOC_SLTH_UNIT_GREATER_WEREWOLF_DESCRIPTION', 'A Werewolf unit, any unit it kills summons a Ravenous Werewolf.', 'en_US'),
('LOC_SLTH_UNIT_GREAT_ARTIST_DESCRIPTION', 'Use Great Bards to Culture Bomb cities, add to cities for consistent Culture.', 'en_US'),
('LOC_SLTH_UNIT_GREAT_ENGINEER_DESCRIPTION', 'Great Engineers can be used to hurry a Wonders production, or added to a city for GPP points and Production.', 'en_US'),
('LOC_SLTH_UNIT_GREAT_MERCHANT_DESCRIPTION', 'Great Merchants can conduct a Trade Mission to foreign cities, earning a gold based on the distance and city size. They can also join a city, providing GPP, gold and a little food.', 'en_US'),
('LOC_SLTH_UNIT_GREAT_PROPHET_DESCRIPTION', 'Great Prophets can be used to build the Wonder associated with a Religion in its Holy City. It can also be used to build a tier of Altar of Luonottar.', 'en_US'),
('LOC_SLTH_UNIT_GREAT_SCIENTIST_DESCRIPTION', 'Great Scientists can found an Academy in a city, increasing Science by 50%. They can also be used to contribute Science to a Technology. They can also join a city, providing Science and GPP.', 'en_US'),
('LOC_SLTH_UNIT_GRIFFON_DESCRIPTION', 'A capturable barbarian Animal unit that can Fly.', 'en_US'),
('LOC_SLTH_UNIT_GRIGORI_MEDIC_DESCRIPTION', 'Use to provide increased healing and the ability to cure disease to your units.', 'en_US'),
('LOC_SLTH_UNIT_GUARDIAN_VINES_DESCRIPTION', 'Guardian Vines are a summonable debuff that prevent movement?DEBUG', 'en_US'),
('LOC_SLTH_UNIT_GUYBRUSH_DESCRIPTION', 'Guybrush starts with Hero and Boarders promotions, making him excellent at capturing opponents naval units.', 'en_US'),
('LOC_SLTH_UNIT_HARLEQUIN_DESCRIPTION', 'Being able to capture animals for the Balseraph carnivals and use the Taunt ability to cause nearby enemy units to attack their stack, Harlequins are useful in times of war or peace.', 'en_US'),
('LOC_SLTH_UNIT_HAWK_DESCRIPTION', 'They can be carried by Rangers, Hunters, and Druids. They can recon into unknown or enemy territory, expanding on their hosts already considerable recon abilities and reveal any hidden Shadows in the area.', 'en_US'),
('LOC_SLTH_UNIT_HELLHOUND_DESCRIPTION', 'Hell Hounds are faster than the Hunters they replace, allowing them to slip quickly into enemy lands for exploration or to harass enemies.', 'en_US'),
('LOC_SLTH_UNIT_HEMAH_DESCRIPTION', 'Hemah is an excellent spell caster available to Octopus Overlords followers only. He can take Archmage spells even though he only requires the Arcane Lore technology, giving you a head start on your rivals, and like other heroic spell casters, can take the powerful twincast promotion.', 'en_US'),
('LOC_SLTH_UNIT_HERALD_DESCRIPTION', 'Heralds have the Heralds Call ability. With it they grant every allied living unit in their plot the Blessed, Valor, Courage and Loyalty promotions. But the unit dies at the end of the turn. For most civilizations this would be devastating in all but the most extreme circumstances, but living units that die in the Mercurians service are reborn as Angels.', 'en_US'),
('LOC_SLTH_UNIT_HERNE_DESCRIPTION', 'The Centaur Hero of the Kuriotates. Like all Centaurs, he can use Sprint to cover more distance, but then most recover from a weakened Fatigue state.', 'en_US'),
('LOC_SLTH_UNIT_HIGH_PRIEST_OF_LEAVES_DESCRIPTION', 'High Priests of Leaves have all the abilities of Priests of Leaves as well as being able to summon [LINK=literal]Treant[\\LINK]s when they are in Forest of Ancient forest tiles.', 'en_US'),
('LOC_SLTH_UNIT_HIGH_PRIEST_OF_THE_EMPYREAN_DESCRIPTION', 'The High Priests of the Empyrean, the Luridus, have all the abilities of a Vicar as well as being able to use the [LINK=literal]Crown of Brilliance[\\LINK] spell. The crown does damage to all surrounding enemies and allows the caster to see invisible units.', 'en_US'),
('LOC_SLTH_UNIT_HIGH_PRIEST_OF_WINTER_DESCRIPTION', 'The apex Illian Disciple , only available by upgrading a Level 6+ , in addition to the Priest of Winter abilities, it can do somethine else DEBUG. It requires [ICON_RESOURCE_INCENSE] Incense. Only 4 allowed in a civ at any given time.', 'en_US'),
('LOC_SLTH_UNIT_HILL_GIANT_DESCRIPTION', 'A Beast unit that can effectively Siege cities, but does not benefit from defensive bonuses.', 'en_US'),
('LOC_SLTH_UNIT_HORSEMAN_DESCRIPTION', 'Useful for pillaging or rapid response to enemy incursion, or you can use their withdrawal chance to weaken an entrenched defender.', 'en_US'),
('LOC_SLTH_UNIT_HORSE_ARCHER_DESCRIPTION', 'The Horse Archer does everything the Horseman does, but better. More withdrawal chance, more strength and the addition of a first strike and first strike immune abilities make them flexible troops.', 'en_US'),
('LOC_SLTH_UNIT_HUNTER_DESCRIPTION', 'Hunters continue the Scout tradition of 2 movement and bonus strength against animals. They can also carry Hawks and use them to scout out areas without having to waste time or risk their lives investigating it themselves.', 'en_US'),
('LOC_SLTH_UNIT_HYBOREM_DESCRIPTION', 'The Infernal Demon Hero starts with the Gela .', 'en_US'),
('LOC_SLTH_UNIT_ICE_ELEMENTAL_DESCRIPTION', 'Ice Elementals get stronger if you have access to more types of Ice mana. They are unable to enter Desert or Burning Sands tiles but are stronger on Tundra and Snow tiles.', 'en_US'),
('LOC_SLTH_UNIT_ILLUSIONIST_DESCRIPTION', 'Illusionists are similar to mages except that any creature they summon is an illusionary version of the creature. Illusions are unable to kill opponents in combat, but can reduce them almost to the point of death. This may seem like disadvantage until you consider that it leaves an opponent weakened an available to be killed by another, which can then gain experience from the battle.', 'en_US'),
('LOC_SLTH_UNIT_IMMORTAL_DESCRIPTION', 'Most believe the Immortals to be insane or undying, they are the first into battle and the last to leave. They are left to guard the cities soon to fall and sent alone deep behind enemy lines looking for exposed troops. They are not insane, and they do die, but after each death they are reborn in the capital of their civilization. A civilization can only have four Immortals at once.', 'en_US'),
('LOC_SLTH_UNIT_IMP_DESCRIPTION', 'This cheap spellcaster is Demonic, with Fire Resistance and +1 Unholy Combat.', 'en_US'),
('LOC_SLTH_UNIT_IRA_DESCRIPTION', 'Ira are special units that are only created by the Avatar of Wrath. Although they start relatively weak, they go stronger whenever they kill an opponent.', 'en_US'),
('LOC_SLTH_UNIT_IRON_GOLEM_DESCRIPTION', 'Iron Golems are likely to form the bulk of a Luchuirp army. They have high strength but as golems will not gain promotions from combat. They arent going to end up as powerful as a highly promoted Champion, but losing any one particular iron golem isnt likely to be a huge setback.', 'en_US'),
('LOC_SLTH_UNIT_JAVELIN_THROWER_DESCRIPTION', 'The Javelin Thrower is an Archer variant without the Archery Range requirement.', 'en_US'),
('LOC_SLTH_UNIT_KITHRA_DESCRIPTION', 'Kithra will only join Fellowship of the Leaves civilizations. Kithra is a very mobile horse archer combining a high move rate and the powerful Hero promotion.', 'en_US'),
('LOC_SLTH_UNIT_KNIGHT_DESCRIPTION', 'High strength, high movement rate, and a decent withdrawal rate combine to form a strong utility unit. There is no best use for a Knight, its the fact that they can do many things so well that make them so valuable.', 'en_US'),
('LOC_SLTH_UNIT_KRAKEN_DESCRIPTION', 'Dwelling beneath the waves, the powerful krakens will only answer to the summons of the Cultists. Once they are summoned, they can travel across the seas, fulfilling their masters demands.', 'en_US'),
('LOC_SLTH_UNIT_LEVIATHAN_DESCRIPTION', 'UH', 'en_US'),
('LOC_SLTH_UNIT_LICH_DESCRIPTION', 'An Archmage with the Death III promotion can cast Lichdom to convert to a Lich. A Lich has the Undead promotion.', 'en_US'),
('LOC_SLTH_UNIT_LIGHTBRINGER_DESCRIPTION', 'Lightbringers have extra visibility, making them useful for scouting or to prevent barbarian spawning.', 'en_US'),
('LOC_SLTH_UNIT_LIGHTNING_ELEMENTAL_DESCRIPTION', 'Lightning Elementals are spawned when Air Elementals win a combat. They are weak, but fast and since they start with the Blitz promotion they can attack until they are dead.', 'en_US'),
('LOC_SLTH_UNIT_LION_DESCRIPTION', 'Over time a lion that survives the wild will grow into a pride. A pride that ends up in terrain that will support a den will create a den that will occasionally spawn new lions that will go out to explore the world, grow into new prides and form more dens.', 'en_US'),
('LOC_SLTH_UNIT_LION_PRIDE_DESCRIPTION', 'Lion Prides form when a Lion unit defeats another unit. Lion Prides can spawn a Lion Den improvement, which spawns more Lions.', 'en_US'),
('LOC_SLTH_UNIT_LIZARDMAN_DESCRIPTION', 'Lizardmen are identical to hunters, except their orc promotion gives them an edge in jungles.', 'en_US'),
('LOC_SLTH_UNIT_LOKI_DESCRIPTION', 'Fun to play with, horrible to play against, most leaders would rather see a berserker horde wander into their lands than the clown prince. Loki can take gold from rival cities or cause unrest in the cities and flip them to the Balseraphs if their culture gets low enough.[PARAGRAPH:1]Loki can investigate cities and has effective spells for charming enemy units, but his most frustrating ability is that he is the most difficult unit in the game to kill. When attacked he simply runs away to any open tiles around him. Loki must be cornered or completely surrounded before he can be killed in combat.', 'en_US'),
('LOC_SLTH_UNIT_LONGBOWMAN_DESCRIPTION', 'The best non-limited city defender is the Longbowman. They start with a high bonus to city defense and like all archers have access to the City Garrison promotions which make them even better.', 'en_US'),
('LOC_SLTH_UNIT_LOSHA_DESCRIPTION', 'Losha is the Calabim hero and a powerful vampire in her own right. But even beyond this she gains the Immortal promotion each time she defeats a living unit in combat, meaning she is very difficult to kill if she is kept fed.', 'en_US'),
('LOC_SLTH_UNIT_LUCIAN_DESCRIPTION', 'The Doviello Hero that the Doviello start with, unlike other Heroes, Lucian does not gain passive experience.', 'en_US'),
('LOC_SLTH_UNIT_LUNATIC_DESCRIPTION', 'Many different kind of people go into the asylum, but only one type comes out, the Lunatic. Lunatics are powerful attackers, even doing collateral damage to the stacks they attack. But their madness does cause them to run off from time to time and attack enemies with little regard to their own safety.', 'en_US'),
('LOC_SLTH_UNIT_LUONNOTAR_DESCRIPTION', 'The Luonnotar are the most powerful disciple units the Grigori have access to, though they lack priests and high priests spell abilities. They can still act as effective healers for your armies and inquisition your cities to remove religions that have spread into them.', 'en_US'),
('LOC_SLTH_UNIT_MAGE_DESCRIPTION', 'With enough experience, an adept can be upgraded to a mage, who has access to more powerful spells and is one step closer to becoming the powerful archmage. An Adept has to be at least 4th level before it can be upgraded to a Mage.', 'en_US'),
('LOC_SLTH_UNIT_MAGNADINE_DESCRIPTION', 'A Superlative mounted unit, Magnadine can also recruit mercenary units to clean up behind him as he pushes deep into enemy territory or harries an assaulting force.', 'en_US'),
('LOC_SLTH_UNIT_MANES_DESCRIPTION', 'Manes have a chance of being automatically created when an evil* unit dies or a neutral or evil city is razed. They are gifted to Infernal civilizations and can either be upgraded to other units or sacrificed to add population to the city.[NEWLINE][NEWLINE]*Evil units are those with the Ashen Veil, Council of Esus or Octopus overlords religion. Or spellcasters that practice Death or Entropy magic.', 'en_US'),
('LOC_SLTH_UNIT_MANTICORE_DESCRIPTION', 'Manticores have a chance of appearing in Sheaim cities with a Planar Gate and a Grove.', 'en_US'),
('LOC_SLTH_UNIT_MAN_O_WAR_DESCRIPTION', 'The ultimate warship, the Man-O-War comes equipped with experimental weaponry, all manner of enchanted or machined siege craft. Few lesser ships will withstand its assault, and city defenses will crumble when it starts to bombard.', 'en_US'),
('LOC_SLTH_UNIT_MARDERO_DESCRIPTION', 'Mardero will only join the Ashen Veil civilizations. Mardero and his rival Sphener are the latest and most powerful heroes in the game. Mardero has a bonus against disciples and makes short work of paladins, priests, and monks.', 'en_US'),
('LOC_SLTH_UNIT_MARGALARD_DESCRIPTION', 'Unique Beast, much stronger than other equivalents.', 'en_US'),
('LOC_SLTH_UNIT_MARKSMAN_DESCRIPTION', 'The marksman ability allows these snipers to pick off enemy stragglers, but even more useful, they can spot invisible units hunting your mages.', 'en_US'),
('LOC_SLTH_UNIT_MAROS_DESCRIPTION', 'The Khazad Hero, Maros is three times as strong on defense as offense. Use him to protect the Khazads powerful siege units.', 'en_US'),
('LOC_SLTH_UNIT_MARY_DESCRIPTION', 'Bearer of the Plague. Mary transmits the Plague to stacks she attacks. She is the only unit that can transmit the plague but the negative heal rate it gives will leave them vulnerable until they can reach a priest or source of sacred water.', 'en_US'),
('LOC_SLTH_UNIT_MERCENARY_DESCRIPTION', 'Mercenaries can be hired in any city if you control the Guild of the Nine wonder.', 'en_US'),
('LOC_SLTH_UNIT_MERCENARY_MOUNTED_DESCRIPTION', 'Hirable Mercenaries from the Hippus are mounted, and so can cover far more ground.', 'en_US'),
('LOC_SLTH_UNIT_MESHABBER_DESCRIPTION', 'An enormous demon of strength unmatched by mortal units, if other leaders have been making fun of you for your heresies, this ought to shut them up once and for all.', 'en_US'),
('LOC_SLTH_UNIT_METEOR_DESCRIPTION', 'UHH its a dragon summon', 'en_US'),
('LOC_SLTH_UNIT_MIMIC_DESCRIPTION', 'Mimics can steal a random promotion from units they defeat in combat.', 'en_US'),
('LOC_SLTH_UNIT_MINOTAUR_DESCRIPTION', 'Minotaurs have a chance of appearing in Sheaim cities with a Planar Gate and an Obsidian Gate building.', 'en_US'),
('LOC_SLTH_UNIT_MISTFORM_DESCRIPTION', 'Mistforms start with invisibility and with hidden nationality, allowing them to sneak past other civilizations defenses and attack allied or enemy units.', 'en_US'),
('LOC_SLTH_UNIT_MITHRIL_GOLEM_DESCRIPTION', 'Formed of mithril and infused with the power of Kilmorph herself, the Mithril Golem is an avatar unit and one of the most powerful units in the game.', 'en_US'),
('LOC_SLTH_UNIT_MOBIUS_WITCH_DESCRIPTION', 'Mobius Witches have a chance of appearing in Sheaim cities with a Planar Gate and Mage Guild buildings. They have a chance of starting with a few spells.', 'en_US'),
('LOC_SLTH_UNIT_MOKKA_DESCRIPTION', 'Mokka can only be created by the Illian Samhain ritual.', 'en_US'),
('LOC_SLTH_UNIT_MONK_DESCRIPTION', 'Monks are great for fighting demonic units. They also have the Medic promotion, making them decent healers. They dont need a building to train so they can be created in any city.', 'en_US'),
('LOC_SLTH_UNIT_MOROI_DESCRIPTION', 'Upgraded bloodpets have some hope of being chosen to become vampires themselves. They also have a self-only version of the dangerous spell burning blood, which gives added move and strength, but may drive them to the barbarians.', 'en_US'),
('LOC_SLTH_UNIT_MUD_GOLEM_DESCRIPTION', 'The mud golems offer two bonuses to make up for their expense-they work faster than other workers, and cities can grow while building them.', 'en_US'),
('LOC_SLTH_UNIT_MYCONID_DESCRIPTION', 'Myconids replace Beastmasters for the Khazad. They dont receive subdue beast or subdue animal promotions, but they can immobilize foes with their Spores spell.', 'en_US'),
('LOC_SLTH_UNIT_NIGHTWATCH_DESCRIPTION', 'Nightwatch units always start with the Council of Esus religion and can spread it without being consumed for a gold fee. They can later upgrade to Assassins or Shadow Riders. Take city garrison promotions if you expect to keep them as defensive units, or go for combat or drill for more offensive units later on.', 'en_US'),
('LOC_SLTH_UNIT_NULLSTONE_GOLEM_DESCRIPTION', 'Starting with Magic Immune gives the Nullstone Golem an obvious use of defending cities against attackers who favor direct damage spells. They will also be better than their strength would predict against any unit that relies on strength of a specific type. Golem promotion gives them additional immunities, forcing foes to take them down head on.', 'en_US'),
('LOC_SLTH_UNIT_NYXKIN_DESCRIPTION', 'Horse Archer variant without the [ICON_RESOURCE_HORSE] Horses requirement.', 'en_US'),
('LOC_SLTH_UNIT_OGRE_DESCRIPTION', 'Horsemen can cover ground very swiftly, taking the fight to enemies across the realm. Few orcs have the patience or aptitude for animal training however, and the Clan of Embers fields no mounted regiments past the early wolf riders and goblin chariots. The Ogres, huge brutes with giant strides, fill the heavy cavalry niche quite effectively, slamming into enemy formations with more mass, if less speed.', 'en_US'),
('LOC_SLTH_UNIT_OGRE_WARCHIEF_DESCRIPTION', 'Say what you will about the lumbering Ogre Warchief, but they are to crafty to be trapped in battle. They will reappear in your capital if they are defeated.', 'en_US'),
('LOC_SLTH_UNIT_OPHANIM_DESCRIPTION', 'The Ophanim is a flying angelic chariot. Use it to attack across water and land alike.', 'en_US'),
('LOC_SLTH_UNIT_ORTHUS_DESCRIPTION', 'Orthus is the first Barbarian hero, spawning on turn 50. He spawns with Orthus Axe.', 'en_US'),
('LOC_SLTH_UNIT_PALADIN_DESCRIPTION', 'The perfect heathen slaying unit for those following the noble path, the Paladin is immune to disease and gets a bonus against demons.', 'en_US'),
('LOC_SLTH_UNIT_PARAMANDER_DESCRIPTION', 'Paramanders are specific to those that have the Runes of Kilmorph state religion. They are upgrades to soldiers of Kilmorph and start with medic and demon slaying.', 'en_US'),
('LOC_SLTH_UNIT_PHALANX_DESCRIPTION', 'With the second highest Melee strength and a bonus to city attack, they were made to attack cities. Soften up the city with siege weapons, magic, or disease, then send them in.', 'en_US'),
('LOC_SLTH_UNIT_PIRATE_DESCRIPTION', 'Pirates and Privateers are useful units for weakening rivals without declaring war. They can blockade cities, eliminating traderoutes and stealing a small amount of gold, and they can attack any ships without declaring war. Even though they have cargo space, remember that they can only carry other Hidden Nationality units, such as Council of Esus units, unless they declare nationality.', 'en_US'),
('LOC_SLTH_UNIT_PIT_BEAST_DESCRIPTION', 'Pit Beasts are abominations made from the pieces of various slain demons. They ache for a chance to avenge their destruction, and will heed any call to return to the mortal realm. As long as they taste blood, they can continue their assault indefinitely.', 'en_US'),
('LOC_SLTH_UNIT_POLAR_BEAR_DESCRIPTION', 'A capturable barbarian Animal unit that spawns in Tundra and Snow, can be used to build a Dancing Bear in cities with a Carnival.', 'en_US'),
('LOC_SLTH_UNIT_PRIEST_OF_KILMORPH_DESCRIPTION', 'Use your Stonewardens to speed healing, build a temple, or for their divine spells, cure disease and shield of faith. With promotions they can also remove unwanted religions from cities or get a chance to convert defeated foes.', 'en_US'),
('LOC_SLTH_UNIT_PRIEST_OF_LEAVES_DESCRIPTION', 'Use your Priests of Leaves to speed healing, build a temple, or for their divine spells, cure disease, summon tiger, and bloom. With promotions they can also remove unwanted religions from cities or get a chance to convert defeated foes.', 'en_US'),
('LOC_SLTH_UNIT_PRIEST_OF_THE_EMPYREAN_DESCRIPTION', 'Use your Vicars to speed healing, build a temple, or for their divine spells, cure disease and revelation. With promotions they can also remove unwanted religions from cities or get a chance to convert defeated foes.', 'en_US'),
('LOC_SLTH_UNIT_PRIEST_OF_THE_ORDER_DESCRIPTION', 'Use your Confessors to speed healing, build a temple, or for their divine spells, cure disease and Bless. With promotions they can also remove unwanted religions from cities or get a chance to convert defeated foes.', 'en_US'),
('LOC_SLTH_UNIT_PRIEST_OF_THE_OVERLORDS_DESCRIPTION', 'Use your Cultists to speed healing, build a temple, or for their divine spells, cure disease and tsunami. With promotions they can also remove unwanted religions from cities or get a chance to convert defeated foes.', 'en_US'),
('LOC_SLTH_UNIT_PRIEST_OF_THE_VEIL_DESCRIPTION', 'Use your priests to speed healing, build a temple, or for their divine spells, cure disease and ring of flames. With promotions they can also remove unwanted religions from cities or get a chance to convert defeated foes.', 'en_US'),
('LOC_SLTH_UNIT_PRIEST_OF_WINTER_DESCRIPTION', 'Priests of Winter are only available to the Illian civilization, and are gifted when [LINK=literal]the White Hand[\\LINK] ritual is completed. Use them to heal your units and they can use the special [LINK=literal]Call Blizzard[\\LINK] ability.', 'en_US'),
('LOC_SLTH_UNIT_PRIOR_DESCRIPTION', 'The apex Order Disciple ,only available by upgrading a Level 6+ , in addition to the Confessor abilities, can cast Unyielding Order, making a city Ecstatic. It requires [ICON_RESOURCE_INCENSE] Incense. Only 4 allowed in a civ at any given time.', 'en_US'),
('LOC_SLTH_UNIT_PRIVATEER_DESCRIPTION', 'Privateers stat with Hidden Nationality, so appear as a Barbarian to other nations. In this way, its possible to weakn an unsuspecting ally or raid their trade routes.', 'en_US'),
('LOC_SLTH_UNIT_PROFANE_DESCRIPTION', 'The apex Veil Disciple , only available by upgrading a Level 6+ , in addition to the Ritualist abilities, can summon Balors, a strong Demonic Melee . It can also create the Hellfire Improvement, which spawns barbarian units. It requires [ICON_RESOURCE_INCENSE] Incense. Only 4 allowed in a civ at any given time.', 'en_US'),
('LOC_SLTH_UNIT_PUPPET_DESCRIPTION', 'Puppets gain the spell casting abilities of their creator. Which allows casters to send their puppets into dangerous situations while remaining well away from the battle. They are also useful for casting spells that can be dangerous for the caster like Wonder or Domination.', 'en_US'),
('LOC_SLTH_UNIT_PYRE_ZOMBIE_DESCRIPTION', 'Use Pyre Zombies as expendable front line troops. They are as strong as Axemen, but when they are killed they explode, damaging all units (enemy and friendly) within a tile of the zombie.', 'en_US'),
('LOC_SLTH_UNIT_QUEEN_OF_THE_LINE_DESCRIPTION', 'Carries a lot of units. No idea how that works for us with embarking. Maybe it can form escort and go fast? DEBUG', 'en_US'),
('LOC_SLTH_UNIT_RADIANT_GUARD_DESCRIPTION', 'Radiant Guards have three advantages over axemen. They do not require a specific building, they can see invisible, and they can cast the Blinding Light spell to hold enemies in place. They do require the Empyrean state religion as well as the religion present in the city. They can upgrade into Champions or Rathas.', 'en_US'),
('LOC_SLTH_UNIT_RANGER_DESCRIPTION', 'Rangers can carry hawks, and carry on a Scouts increased movement rate. Use them to scout the map, especially to clear off barbarian units that are to strong for your hunters. Although Rangers are powerful units but they get a penalty when attacking cities. So use them to clear the unsettled lands around your enemies cities and leave city attacks to your melee units.', 'en_US'),
('LOC_SLTH_UNIT_RANTINE_DESCRIPTION', 'Rantine is a powerful early weapon against any enemies of the Clan of Embers, and a great tool against their allies, with his ability to convert barbarian cities if he is the strongest unit in it.', 'en_US'),
('LOC_SLTH_UNIT_RATHA_DESCRIPTION', 'Rathas have three advantages over chariots. They do not require a specific building, they can see invisible, and they can cast the Blinding Light spell to hold enemies in place. They do require the Empyrean state religion as well as the religion present in the city.', 'en_US'),
('LOC_SLTH_UNIT_RATHUS_DESCRIPTION', 'Rathus Denmora has the same special abilities as the Sidar Ghosts: The ability to become invisible until he attacks, and the Marksman promotion for targeting the weakest unit in a stack. He does not have a low defensive strength, though, and he starts with a unique piece of equipment, the Netherblade, which gives a large bonus against other hero units.', 'en_US'),
('LOC_SLTH_UNIT_RAVENOUS_WEREWOLF_DESCRIPTION', 'Ravenous Werewolfs are spawned for the owner of a Werewolf unit when it kills another unit. They spawn uncontrollable in a rage, and target any opponent enemy. Once a Ravenous Werewolf kills a unit, it converts to a Blooded Werewolf and is controllable once more.', 'en_US'),
('LOC_SLTH_UNIT_REPENTANT_ANGEL_DESCRIPTION', 'Repentant Angels are unusually strong, but lose [ICON_Strength] Strength on killing a unit.', 'en_US'),
('LOC_SLTH_UNIT_REVELERS_DESCRIPTION', 'Revelers are automatically created in Sheaim cities that contain a Planar Gate and a Gambling House. Use them as scouts and despite the caecus cloth that cover their eyes, they can see very well, even detecting invisible units around them.', 'en_US'),
('LOC_SLTH_UNIT_ROSIER_DESCRIPTION', 'Rosier will only join the Ashen Veil civilizations. Rosier used to be a knight in the service of the Order, but has since fallen into serving the Veil. The reason for his fall is unknown.', 'en_US'),
('LOC_SLTH_UNIT_ROYAL_GUARD_DESCRIPTION', 'Royal Guards require the Aristocracy civic to build, and will leave you if you change civics-so dont bother building them if you plan to change government civics soon. They are very nice units if you meet the requirements, however, as they protect stacks against enemies with Marksman promotion and they can cast the Hope spell to add happiness and culture to a city.', 'en_US'),
('LOC_SLTH_UNIT_RUNEKEEPER_DESCRIPTION', 'The apex Runes of Kilmorph Disciple , only available by upgrading a Level 6+ , in addition to the Stonewarden abilities, can cast Earthquake, pillaging adjacent improvements and potentially destroying adjacent buildings. Unlike other apex Disciples, it only requires [ICON_RESOURCE_GEMS]. Only 4 allowed in a civ at any given time. (NOT_IMPLEMENTED)', 'en_US'),
('LOC_SLTH_UNIT_SAILORS_DIRGE_DESCRIPTION', 'The Sailors Dirge is a Barbarian , on defeating this unit, the wreck can be looted.', 'en_US'),
('LOC_SLTH_UNIT_SAND_LION_DESCRIPTION', 'Sand Lions can only be summoned by Malakim Mages, and only on desert tiles. Despite those restrictions, when they are summoned they are powerful attackers with a high movement that allow them to surprise victims.', 'en_US'),
('LOC_SLTH_UNIT_SATYR_DESCRIPTION', 'Satyrs require Fellowship of the Leaves religion, but no buildings, so young cities can build quickly. They can also convert any animal units without needing to attack with their mesmerize ability.', 'en_US'),
('LOC_SLTH_UNIT_SAVEROUS_DESCRIPTION', 'Saverous will only join Octopus Overlords civilizations. Saverous is a powerful warrior with a high strength and a built in bonus against melee troops, he frequently leads the Overlords into battle.', 'en_US'),
('LOC_SLTH_UNIT_SCORPION_DESCRIPTION', 'A barbarian Animal unit that spawns in Desert tiles.', 'en_US'),
('LOC_SLTH_UNIT_SCOUT_DESCRIPTION', 'The earliest Recon unit. He can be upgraded to a hunter or a horseman and is best used to explore the early map.', 'en_US'),
('LOC_SLTH_UNIT_SEA_SERPENT_DESCRIPTION', 'A barbarian Animal unit that spawns in Ocean tiles.', 'en_US'),
('LOC_SLTH_UNIT_SERAPH_DESCRIPTION', 'The sons of fire are powerful attackers, they do collateral damage to stacks they attack and can even learn to cast fire spells. They are a terror to enemy units and can decimate entire armies.', 'en_US'),
('LOC_SLTH_UNIT_SEVERED_SOUL_DESCRIPTION', 'These are the wandering souls of the Divided Soul unit. They can only be created by that units Sever Soul ability. Since they are invisible they can explore the area near their Divided Soul in safety, and summon their body to them if they find something interesting.', 'en_US'),
('LOC_SLTH_UNIT_SHADE_DESCRIPTION', 's that have attained level 6 or greater can opt to retire as a shade. These faint souls no longer engage in war or directly with the world, instead choosing to join a city to study as their profession allows. Use them to create specialists in your cities, but be careful to defend your city well. If you lose it your specialists will be gone forever.', 'en_US'),
('LOC_SLTH_UNIT_SHADOWRIDER_DESCRIPTION', 'Shadowriders are national units that must be built or upgraded in a city with the Council of Esus religion. They begin with hidden nationality, one of the few land units to do so and easily the strongest. They also have affinity for Shadow mana, gaining additional strength with every additional source gained.', 'en_US'),
('LOC_SLTH_UNIT_SHADOW_DESCRIPTION', 'The Shadow is invisible to most units, and attacks the weakest unit in a stack. The perfect counter to powerful Summoners or Archmages.', 'en_US'),
('LOC_SLTH_UNIT_SHAMAN_DESCRIPTION', 'The Shaman comes with all the advantages of an Adept, without the Mage Guild requirement.', 'en_US'),
('LOC_SLTH_UNIT_SKELETON_DESCRIPTION', 'Kept alive by dark and ancient magic, Skeletons are the spirits of explorers who never found their way home, condemned to wander the frozen wastes for eternity. Though they seldom foray into the lands of the living, they will not hesitate to attack hapless wanderers of the wild.', 'en_US'),
('LOC_SLTH_UNIT_SLAVE_DESCRIPTION', 'A civilization with the Slavery civic will capture 25% of the units it defeats in combat and convert them into slave units. A slave acts like a worker, but builds at half the normal speed. Slaves can also be sacrificed to add a small amount of production to a citys current production.', 'en_US'),
('LOC_SLTH_UNIT_SOLDIER_OF_KILMORPH_DESCRIPTION', 'Soldiers of Kilmorph are useful for rushing production in new cities and for early defense if a player has rushed for the Runes of Kilmorph religion before being able to produce second tier units.', 'en_US'),
('LOC_SLTH_UNIT_SON_OF_THE_INFERNO_DESCRIPTION', 'Barbarian Channeling III unit that support Acheron.', 'en_US'),
('LOC_SLTH_UNIT_SPEAKER_DESCRIPTION', 'The apex Octopus Overlords Disciple , only available by upgrading a Level 6+ , in addition to the Cultist abilities, it can summon a Kraken. It requires [ICON_RESOURCE_INCENSE] Incense. Only 4 allowed in a civ at any given time.', 'en_US'),
('LOC_SLTH_UNIT_SPECTRE_DESCRIPTION', 'Spectres start with the Fear promotion, meaning most living units will not attack them unless they are much more powerful than the Spectre and the can be used to scatter enemy stacks they attack.', 'en_US'),
('LOC_SLTH_UNIT_SPHENER_DESCRIPTION', 'Sphener will only join the Order civilizations. Sphener and his rival Mardero are the latest and most powerful heroes in the game. Sphener has a bonus against demons and makes short work of Eidolons and Beasts of Agares.', 'en_US'),
('LOC_SLTH_UNIT_SPIDERKIN_DESCRIPTION', 'LMAO WHO CARES', 'en_US'),
('LOC_SLTH_UNIT_STEPHANOS_DESCRIPTION', '1st Horseman of the Apocalypse. Converts defeated units to his side.', 'en_US'),
('LOC_SLTH_UNIT_STONESKIN_OGRE_DESCRIPTION', 'Ogres have tremendous regenerative ability and a very high tolerance for pain. Long lived ogres will typically be covered in scars, but these old wounds give them a thick layer of calluses, further reducing their susceptibility to pain. Their reflexes tend to be dulled somewhat, but killing a Stone-skin ogre is a tremendously difficult task. Even wounding one is rare, and is not recommended without a great withdrawal rate.', 'en_US'),
('LOC_SLTH_UNIT_STYGIAN_GUARD_DESCRIPTION', 'Stygian Guards require a Temple to the Overlords and Copper to train. They are Immune to Disease, like all Demons, and heal faster than men, as indicated by their March promotion.', 'en_US'),
('LOC_SLTH_UNIT_SUCCUBUS_DESCRIPTION', 'Succubus have a chance of appearing in Sheaim cities with a Planar Gate and Public Baths buildings.', 'en_US'),
('LOC_SLTH_UNIT_SUPPLIES_DESCRIPTION', 'Supplies can be used in any of your cities to immediately build several buildings.', 'en_US'),
('LOC_SLTH_UNIT_SWORDSMAN_DESCRIPTION', 'Strong Classical era melee unit', 'en_US'),
('LOC_SLTH_UNIT_TAR_DEMON_DESCRIPTION', 'Tar Demons have a chance of appearing in Sheaim cities with a Planar Gate and Temple of the Veil buildings. When killed large enough tar demons will split into two smaller tar demons.', 'en_US'),
('LOC_SLTH_UNIT_TASKMASTER_DESCRIPTION', 'The taskmaster will turn defeated units into slaves, which can be used as workers or added to a Balseraph city. Taskmasters also start with marksmen promotion, meaning that they will target the weakest units first.', 'en_US'),
('LOC_SLTH_UNIT_TEUTORIX_DESCRIPTION', 'The Malakim Hero uhhh', 'en_US'),
('LOC_SLTH_UNIT_TIGER_DESCRIPTION', 'Though far less dangerous than the humanoid and occasionally undead denizens of the wilderness, wild animals are nevertheless a constant hazard to those who dare venture beyond the pale.', 'en_US'),
('LOC_SLTH_UNIT_TREANT_DESCRIPTION', 'Treants wield the power of nature, and so start with the Woodsman promotions, being stronger and faster in Woods. However, they are vulnerable to fire.', 'en_US'),
('LOC_SLTH_UNIT_TREBUCHET_DESCRIPTION', 'Medieval era siege unit, ideal for attacking cities. Cannot move and attack on the same turn unless theyve earned the Expert Crew promotion.', 'en_US'),
('LOC_SLTH_UNIT_TRIREME_DESCRIPTION', 'Triremes are the first ship able to bombard coastal cities, making them an alternate to siege engines in some environments. They start with a cargo space as well, allowing you to take escorted settlers with a skeleton crew configuration.', 'en_US'),
('LOC_SLTH_UNIT_TUMTUM_DESCRIPTION', 'Many orcish charges have been lead by the mighty TumTum. Opposing armies, facing chants of TumTum, TumTum, TumTum! only to have a huge ogre on the back of a wild boar come bursting through the ranks at them are more likely to start laughing than be afraid. But once battle is joined TumTum is a powerful weapon for the barbarians of Erebus, and will topple unprepared empires.', 'en_US'),
('LOC_SLTH_UNIT_VALIN_DESCRIPTION', 'The Order Hero is mounted, with high [ICON_Movement]movement. Starts with Demon Slaying and is Immune to Disease.', 'en_US'),
('LOC_SLTH_UNIT_VALKYRIE_DESCRIPTION', 'Valkyries are immortal units and will be reborn in your capital if killed. As such they are great defenders of your units in the field, sacrificing themselves to save their allies.', 'en_US'),
('LOC_SLTH_UNIT_VAMPIRE_DESCRIPTION', 'Capable fighters with a handful of useful spells, vampires true strength lies in their ability to grow in power from feasting on city population-and to pass this power on to worthy allies. (s level six or higher)', 'en_US'),
('LOC_SLTH_UNIT_VAMPIRE_LORD_DESCRIPTION', 'All vampires have unnaturally long life-spans, but the vampire lords have learned to cheat death itself. Whether through massive feasting or some more arcane ritual, the body of a vampire lord is recreated upon destruction. Some spend their stolen years further honing their martial prowess, but many, having experienced everything else in life, study forbidden knowledge, learning to cast advanced death and body spells without mana. A few take the final step towards immortality, and become a Lich.', 'en_US'),
('LOC_SLTH_UNIT_WAR_ELEPHANT_DESCRIPTION', 'The Elephant is the king of the early cavalry units. Granted, it is slow, but what matter, when a lumbering elephant can crush anyone foolish enough to attempt to stand their ground beneath its monstrous feet?', 'en_US'),
('LOC_SLTH_UNIT_WAR_MACHINE_DESCRIPTION', 'The war machine can mow down mounted units with ease, and has a good chance of withdrawal if combat goes poorly. However, it does not get defensive bonuses, so it may be wise to keep a crossbowman nearby for protected healing. Note that the War Machine automatically destroys any enemy improvements in travels over.', 'en_US'),
('LOC_SLTH_UNIT_WAR_TORTOISE_DESCRIPTION', 'The Lanun Knight replacement lacks the mobility of the Knight, but has no reduced Combat Strength when embarked.', 'en_US'),
('LOC_SLTH_UNIT_WATER_ELEMENTAL_DESCRIPTION', 'Water Elementals are capable of attacking on land or sea, and if they are defeated in combat they will split into two smaller water elementals.', 'en_US'),
('LOC_SLTH_UNIT_WEREWOLF_DESCRIPTION', 'Any unit killed by a werewolf becomes a Ravenous Werewolf, newly born, weak and hungry. After a Ravenous Werewolf has killed a unit it becomes a Blooded Werewolf. If a Blooded Werewolf kills enough victims it can become the powerful Greater Werewolf.', 'en_US'),
('LOC_SLTH_UNIT_WILBOMAN_DESCRIPTION', 'The Illian Hero is an Ice Giant, who has 25% bonus in Tundra and Snow and is Immune to Cold. However, he is Vulnerable to Fire and cannot enter Desert tiles.', 'en_US'),
('LOC_SLTH_UNIT_WIZARD_DESCRIPTION', 'The Amurite Mage replacement, the Wizard spawns with the SpellStaff equipment, increasing passive experience gain, and can be broken to cast again.', 'en_US'),
('LOC_SLTH_UNIT_WOLF_DESCRIPTION', 'Wolves occasionally grow into wolf packs. Wolf Packs can spawn new wolves that split off and hunt on their own, making them mobile monster lairs.', 'en_US'),
('LOC_SLTH_UNIT_WOLF_PACK_DESCRIPTION', 'Wolves upgrade to Wolf Packs on combat victory, can spawn a Wolf Den improvement on eligible tiles, spawning more Wolves.', 'en_US'),
('LOC_SLTH_UNIT_WOLF_RIDER_DESCRIPTION', 'Wolf Riders are fast units that are able to quickly cut into enemy lands to steal workers and cities without adequate defense. If a goblin defeats a wolf, he will automatically be upgraded to a wolf rider, often allowing Clan of Ember players to get wolf riders very early.', 'en_US'),
('LOC_SLTH_UNIT_WOOD_GOLEM_DESCRIPTION', 'The Luchuirps first golem unit, Wood golems are good as attackers or defenders, being stronger than the units most civs are likely to have access to at the same time. Like all golems, however, they cannot level up to gain promotions. Beware their vulnerability to fire.', 'en_US'),
('LOC_SLTH_UNIT_WRAITH_DESCRIPTION', 'Summonable by Channeling units with Death III, this Undead unit starts with Fear, scattering units in combat, and Vile Touch, passing the Withered debuff to enemies in combat, weakening units, reducing experience gain, and limiting healing.', 'en_US'),
('LOC_SLTH_UNIT_WRATH_DESCRIPTION', 'Spawned for the Barbarians once the Armageddon score reaches 100, the Avatar of Wrath is very powerful, and can summon 4 Iras per turn, bloodthirsty spirits.', 'en_US'),
('LOC_SLTH_UNIT_YERSINIA_DESCRIPTION', 'The 3rd Horseman, Yersinia spreads the Plagued promotion to enemies in combat, weakening them substantially. They are also Magic Immune.', 'en_US'),
('LOC_SLTH_UNIT_YVAIN_DESCRIPTION', 'Yvain can move in mountains, summon treants, and is a powerful defender when fighting in forests.', 'en_US'),
('LOC_UNIT_WARRIOR_DESCRIPTION', 'Warriors are your earliest units and make reasonable city attackers and defenders. But beware that they will obsolete quickly. Seeks out archers for more effective defense and Axemen for more effective attacks.', 'en_US');