INSERT OR REPLACE INTO LocalizedText(Tag, Text, Language) VALUES
('LOC_ALTAR_VICTORY_SHORT', 'Altar', 'en_US'),
('LOC_TOWER_VICTORY_SHORT', 'Tower', 'en_US'),
('LOC_VICTORY_TOWER_OF_MASTERY_NAME', 'Tower of Mastery', 'en_US'),
('LOC_VICTORY_ALTAR_OF_LUONNOTAR_NAME', 'Altar of the Luonnotar', 'en_US'),
('LOC_VICTORY_TOWER_OF_MASTERY_TEXT', 'Altar of the Luonnotar', 'en_US'),
('LOC_VICTORY_ALTAR_OF_LUONNOTAR_TEXT', 'Altar of the Luonnotar', 'en_US'),
('LOC_VICTORY_TOWER_OF_MASTERY_DESCRIPTION', 'Gather Mana Sources to allow building powerful Tower National Wonders. Once you have all 4 Towers, build the Tower Of Mastery to become unbound from the rules of magic, shaping reality to your whim, winning the game.', 'en_US'),
('LOC_VICTORY_ALTAR_OF_LUONNOTAR_DESCRIPTION', 'Activate Great Prophets to build up tiers of the Altar of Luonnotar, once you have the corresponding civic. Altar tiers make priest specialists stronger and grant xp to Disciple units. Once the Exalted altar is built, manually build the Final Altar to reconvene with the One, winning the game.', 'en_US'),
('LOC_USE_GP', 'Use Great Prophet to grant ', 'en_US'),
('LOC_SLTH_BUILD', 'Build ', 'en_US'),
('LOC_MAINTAIN_MANA', 'Maintain a source of ', 'en_US'),
('LOC_ERA_ANCIENT_DESCRIPTION', 'The Age of Ice is ended and fertile lands are newly exposed by retreating sheets of ice. The glory of the Age of Magic is long past and your people set forth to build a civilization to recapture that lost knowledge. Your people have vested absolute power in you, trusting you to lead them into the next age, the Age of Rebirth.', 'en_US'),
('LOC_LOADING_INFO_LEADER_IMPRACTICAL_DAIN', 'The worlds best mages come from the Amurites. The Cave of Ancestors gives +1 xp per mana type in the city to adepts created there and their wizards start with a spellstaff for free. Their Firebow units are a replacement for Longbowmen that are able to learn to cast fireballs and their hero Govannon can train Amurite units how to cast spells. Their World Spell will grant their arcane units experience at the expense of downgraded mana nodes until rebuilt-perfect for that last few points before upgrading to archmages.', 'en_US'),
('LOC_LOADING_INFO_LEADER_DAIN', 'The world''s best mages come from the Amurites. The Cave of Ancestors gives +1 xp per mana type in the city to adepts created there and their wizards start with a spellstaff for free. Their Firebow units are a Longbowmen replacement that can learn to cast fireballs and their hero Govannon can train Amurite units how to cast spells. Their World Spell will grant their arcane units experience at the expense of downgraded mana nodes until rebuilt-perfect for that last few points before upgrading to archmages.', 'en_US'),
('LOC_LOADING_INFO_LEADER_KEELYN', 'Keelyn''s Summoner Trait allows her to abuse puppets to have exceptional range. Her powerful summons are supplemented by her strong cultural output with Creative, allowing early access to religions with summons. She can still take advantage of the Balseraph unique recon line to build up slave cages in her cities to support her strong cultural output.', 'en_US'),
('LOC_LOADING_INFO_LEADER_IMPRACTICAL_KEELYN', 'The Balseraphs give a whole new meaning to the term culture war. Balseraph Catapults (or cowtapults as they are sometimes called due to their unusual ammunition) have a high withdrawal rate, allowing them to cause collateral damage multiple times with near-impunity, and Harlequins can utilize low-to-mid level Chaos and Mind spells. Mimics are Champion units that begin weaker than their counterparts, but gain promotions through combat, copying their foes and growing in unexpected ways. Freaks start mutated, and can build freak shows in cities. Finally, consider their arcane line of units, which employ puppets to extend spell range. The Balseraphs also enjoy unique benefits of slavery, with extra culture for each slave cage you build in that city. For these reasons, you should consider adopting the slavery civic when you play as the Balseraphs, though you can make do with Taskmasters, the Balseraph replacement for the Assassin, which can enslave enemies regardless of civic options. Any religion that allows you to keep an evil or neutral alignment will allow an alternate source of slaves once you join the Undercouncil.[PARAGRAPH:1]Oh, and if you''re playing Perpentach-he is Insane, so his three traits are randomly selected and may or may not change at any time, without any advance warning. Enjoy.', 'en_US'),
('LOC_LOADING_INFO_LEADER_DECIUS_BANNOR', 'The Bannor are a pretty generalist, law-oriented civilization. When led by Sabathiel (Organized/Charismatic), they are well-suited for warfare, while Capria (Industrial/Spiritual) lends well for a more peaceful playing style. Of the two extremes, however, they''re a bit more suited towards warfare-guardsmen promotion on melee units helps keep support units alive, and their unique Crusade civic brings frequent recruits from towns and allows unique flagbearer support units. Think twice before turning a standard war into a crusade, however, for once begun the Bannor player cannot initiate diplomacy with any of their foes. Their hero makes them especially well suited towards warring with demon- or undead-using civilizations.', 'en_US'),
('LOC_LOADING_INFO_LEADER_DECIUS_CALABIM', 'Your vampires (gained at Feudalism) can be fed either through building a couple of big farm cities, or simply by taking over enemy cities and gobbling up their entire population (bon appetit). Spread the gift to as many of your units as you can (your Moroi units can gain vampirism earlier than other unit, which usually requires level six) to allow other unit types access to this easy experience method. With their unique Breeding Pit building, the Calabim also have synergies with the slavery civic; whenever your citizens aren''t being used for vampire food, they can be whipped away for production. (Your citizens may feel a bit unhappy, but they''ll still be productive with a governor''s manor in the city.)', 'en_US'),
('LOC_LOADING_INFO_LEADER_SHEELBA', 'The Clan isn''t likely to outbuild the other civs. They don''t have access to special buildings and suffer a -10% to their tech rate. But starting at peace with the barbarians* means they can explore without fear and not needing to protect cities, except Animals. At Masonry, they can double their unit production with Warrens, and their For the Horde! World Spell has a 50 pct chance of converting any barbarian orc.', 'en_US'),
('LOC_LOADING_INFO_LEADER_MAHALA', 'The Doviello don''t have the requirements on buildings that other civilizations do. This makes them less reliant on their cities and more able to build units in newly conquered towns. Their battlemaster unit is able to perform upgrades in the field, allowing them to keep their advance going. Charadon starts with the Barbarian trait, and its -10% research rate, while Mahala is better at researching but will find the barbarians to be less hospitable. Also, they begin with the Lucian unit, an axeman equivalent at the time of warriors and scouts. Enjoy an early conquest, you''ll need it later.', 'en_US'),
('LOC_LOADING_INFO_LEADER_EINION', 'The Defensive trait helps a Builder style of play as repelling invasions gets easier. Monks are decent units fighters and healers regardless of your religion, and by building reliquary buildings your units will pass on their experience. Their hero and World Spell can both save your empire from an unexpected declaration of war. Once the Elohim start claiming cities from other leaders, their Tolerant trait starts to shine, allowing them to build those civilizations'' unique units and unique buildings.', 'en_US'),
('LOC_LOADING_INFO_LEADER_CASSIEL', 'The Grigori lack a unique Hero, and the inability to have a State Religion makes it difficult to get allies or take advantage of Religion''s unique units, priests and hero. However, their unique Adventurer Great Person acts as a customisable Hero Unit, so they can use Pacifism to generate them ASAP. They are the units with the most potential in the game. Early melee or recon heroes are a tempting choice, but consider arcane upgrades as well, for their hero promotion allows access to twincast (with Combat V) for twice the summoned units or fireballs.', 'en_US'),
('LOC_LOADING_INFO_LEADER_RHOANNA', 'The Hippus start with horses and all of their mounted units are upgraded versions of the normal giving them an amazingly mobile army. Should the Hippus gain a branch of the Guild of the Nine, they will find mercenaries they hire to be swift mounted units as well. Rhoanna''s traits are well suited to teching peacefully until she decides to go to war, though Tasunke may need to rely on his raider trait to gain a financial edge from pillaging.', 'en_US'),
('LOC_LOADING_INFO_LEADER_KANDROS', 'Use your bonuses from hoarding gold to churn out a powerful small empire. Runes of Kilmorph aids in making money, and the Khazad''s powerful Siege weapons offset their lack of spellcaster units beyond adepts.', 'en_US'),
('LOC_LOADING_INFO_LEADER_CARDITH', 'The Kuriotates have a lot of hard stuff to mod. Currently, they do not have an increased ring of tiles, and so they settle cities normally. They still have some interesting features, able to be econ powerhouses with Enclaves, more Housing. Their Centaur mounted units benefit from defensive bonuses.* Your Adaptive trait also allows you to change your Philosophical trait into something else, and reconsider that choice every 100 turns, should you desire*.', 'en_US'),
('LOC_LOADING_INFO_LEADER_IMPRACTICAL_CARDITH', 'Playing as the Kuriotates, you will have a group of big cities producing everything in your empire. All the rest will serve mostly as buffer zones and as ways to grab resources. Cardith Lorda''s adaptive trait enables him to tailor his economy should he choose to pursue a cottage strategy and benefit from unique town upgrades, enclaves, or a great person strategy and benefit from huge populations. When waging a war, you may want to raze cities a lot, since otherwise they''ll become Settlements-and you can''t build units in them to help hold them. When you need to defend far flung settlements, though, take advantage of their centaur unique units, which unlike other fast-moving units, benefit from defense bonuses.[PARAGRAPH:1]Your Adaptive trait also allows you to change your Philosophical trait into something else, and reconsider that choice every 100 turns, should you desire. Remember to choose carefully whether you want your new cities to become cities or settlements, as you only get a limited number of cities. In the late game, when rivals are out-producing you with their large numbers of cities, burn them down with your dragon, the strongest unit buildable.', 'en_US'),
('LOC_LOADING_INFO_LEADER_HANNAH', 'The Lanun are a sea people, capable of dominating the seas in any map with water present. They gain extra food from sea tiles, losing food from farms in exchange. The Lanun capital gets increased ship production, so it better be built on the coast. Though they''re somewhat more oriented towards warmongering, they also have viable hybrid strategies. Led by Falamar they''ll grow quickly thanks to rapid border expansion and cheaper lighthouses. Led by Hannah coastal tiles with their three food and commerce will be incredibly profitable for them, not to mention their extra income from pillaging.', 'en_US'),
('LOC_LOADING_INFO_LEADER_THESSA', 'The Ljosalfar are a defensive civilization-after all, they can''t build any siege weapons. Instead, the Light Elves are capable of effectively mounting a war of attrition, using their forested infrastructure to overwhelm the opponent with units and pillage his lands until he''s as good as dead. There are alternative methods as well-getting the Baron from the Feral Bond tech and unleashing a horde of Werewolves is an effective way of taking down enemy cities, and mages always exist. With their ability to build things in forests, the Elves have a good synergy with the Fellowship of the Leaves'' forest bonuses-but a Fellowship strategy isn''t strictly necessary, and following an aggressive religion like the Octopus Overlords will give good early attack units in the form of the Drown.', 'en_US'),
('LOC_LOADING_INFO_LEADER_BEERI', 'Golems gain no experience, but a combination of the different golem-boosting buildings and Barnaxus will make them pretty mean anyway. Should you lose Barnaxus, you still have a chance of rebuilding him if you can kill the unit that destroyed him.', 'en_US'),
('LOC_LOADING_INFO_LEADER_DECIUS_MALAKIM', 'Varn Gosam starts with the Creative and Financial traits, a powerful combination in vanilla Civ, and useful here as well. Quick expansion yields good results, as monuments aren''t necessary for Malakim cities to expand. Cottage-spammers will enjoy this Civ, but other strategies are viable as well. Malakim units also start with the nomad promotion, allowing them to ignore the negative effect of deserts. The Malakim''s World Spell will help them reach powerful priest units quickly if they spread it well and build temples beforehand.', 'en_US'),
('LOC_LOADING_INFO_LEADER_OS_GABELLA', 'The Sheaim are masters of summoning, with the powerful Archmage replacment, Eater of Dreams. In the midgame, they have access to Pyre Zombies, powerful Undead which explode when killed, damaging units around them. The Sheaim lack some late melee units but are summoned through Planar Gates, increasing as the Armageddon Counter rises.', 'en_US'),
('LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_KEELYN_ANY', 'Thank you, I won''t vote for you in the tribal council.', 'en_US'),
('LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_DECIUS_BANNOR_ANY', 'A just and equitable deal for us both, I think.', 'en_US'),
('LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_DECIUS_CALABIM_ANY', 'Very well.', 'en_US'),
('LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_SHEELBA_ANY', 'This will do for now.', 'en_US'),
('LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_DECIUS_ANY', 'I believe that deal benefited both sides.', 'en_US'),
('LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_MAHALA_ANY', 'Hmph. I guess we can do this the easy way. The hard way is so much more fun.', 'en_US'),
('LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_EINION_ANY', 'We most humbly accept your generous proposal.', 'en_US'),
('LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_ETHNE_ANY', 'We most humbly accept your generous proposal.', 'en_US'),
('LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_CASSIEL_ANY', 'See, it wasn''t so hard to think for yourself, now was it?', 'en_US'),
('LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_HANNAH_ANY', 'The seas are ever hungry-but my people are satisfied with this... for now.', 'en_US'),
('LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_RHOANNA_ANY', 'Aye, and you''re a shrewd negotiator.', 'en_US'),
('LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_AURIC_ANY', 'Trying to appear too useful to destroy? Well, for once you''ve succeeded!', 'en_US'),
('LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_HYBOREM_ANY', 'This will do for now. Your next request can be paid in blood and souls, my friend.', 'en_US'),
('LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_KEELYN_ANY', 'Oh, presents for me? How kind of you.', 'en_US'),
('LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_KANDROS_ANY', 'I know a bargain when I see one!', 'en_US'),
('LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_CARDITH_ANY', 'Let''s hope this will draw our people closer.', 'en_US'),
('LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_HANNAH_ANY', 'It''s a deal, you salty old dog.', 'en_US'),
('LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_THESSA_ANY', 'You are wise beyond your years.', 'en_US'),
('LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_BEERI_ANY', 'What is it?... that?... sure you can, why not?', 'en_US'),
('LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_DECIUS_MALAKIM_ANY', 'Sounds like a good deal, I would be foolish to turn it down.', 'en_US'),
('LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_BASIUM_ANY', 'Done. Now be gone. The bargaining table is a waste of time, as Hell''s power grows by the hour.', 'en_US'),
('LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_PERPENTACH_ANY', 'Such is life that leads a man to his desire.[NEWLINE]Such is art that fuels this raging fire.[NEWLINE]Such is compassion that another can fill this need.[NEWLINE]Such is my joy to see this deal agreed.', 'en_US'),
('LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_OS_GABELLA_ANY', '''Til the end of time...', 'en_US'),
('LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_SANDALPHON_ANY', 'This deal will do, for a time, though all things pass... except us, of course.', 'en_US'),
('LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_FAERYL_ANY', 'Well, I suppose trade is quicker than theft, though I fear my reflexes dulling.', 'en_US'),
('LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_DAIN_ANY', 'Prepare to be added to the long list of tribes who wouldn''t leave us alone, and paid the price for it.', 'en_US'),
('LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_ARENDEL_ANY', 'The shining legions of the Elven court have unsheathed their graceful blades. They march to purge the rot you have become.', 'en_US'),
('LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_KEELYN_ANY', 'Toy soldiers are no fun without battles to fight with them.', 'en_US'),
('LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_DECIUS_BANNOR_ANY', 'War does not determine who is right-only who is left.', 'en_US'),
('LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_DECIUS_CALABIM_ANY', 'My people are getting hungry, and I envision your empire as a ripe red apple, the juices of which will surely serve to still their thirst. Bloodthirsty warriors, in their most literal incarnations, will be claiming your lands shortly. Resistance will of course be useless, except perhaps to provide me with some brief amusement before I can finally get a taste of your jugular.', 'en_US'),
('LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_SHEELBA_ANY', 'You have something I want. Now I''m coming for it. And I''m going to kill your pathetic soldiers while I''m at it.', 'en_US'),
('LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_DECIUS_ANY', 'Profane or pious, they act no differently on the battlefield.', 'en_US'),
('LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_MAHALA_ANY', 'You''re weak. And my pack is hungry.', 'en_US'),
('LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_EINION_ANY', 'We have tried everything to deter you from your futile path of meaningless destruction and corruption of all that was once pure. We have sought to sway you with gentle means, yet you have kept resisting us. Alas, you leave us no choice but to end this madness once and for all.', 'en_US'),
('LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_ETHNE_ANY', 'We have tried everything to deter you from your futile path of meaningless destruction and corruption of all that was once pure. We have sought to sway you with gentle means, yet you have kept resisting us. Alas, you leave us no choice but to end this madness once and for all.', 'en_US'),
('LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_FALAMAR_ANY', 'You look like a monkey in a negligee.', 'en_US'),
('LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_CASSIEL_ANY', 'Pray to your gods for mercy. Doubtless, your lamentations will fall upon deaf ears. But it will make you easier to strike down as you babble on in vain.', 'en_US'),
('LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_HANNAH_ANY', 'Only a fool would arouse the tempest. And a fool thou art.', 'en_US'),
('LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_RHOANNA_ANY', 'Nothing personal, business is business, and you are a prime target.', 'en_US'),
('LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_AURIC_ANY', 'You opposed me. Your people do not deserve to see my glory reborn.', 'en_US'),
('LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_HYBOREM_ANY', 'I will make your death quick. Torture can wait until we meet in Hell.', 'en_US'),
('LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_KEELYN_ANY', 'Ohhh, you''ve made me mad! Time for my armies to get you... Someone summon us an army! Now!', 'en_US'),
('LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_KANDROS_ANY', 'Our warriors will have much to sing about after this war. Let''s hope your boys don''t embarrass themselves.', 'en_US'),
('LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_CARDITH_ANY', 'You are a bully, plain and simple. If war is the only way to show you the error of you ways, we will not shy away from it!', 'en_US'),
('LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_HANNAH_ANY', 'I can see a mere raid won''t fix you. See those thousand sails over yonder? They''re coming for your wine, your riches, your women, and your life!', 'en_US'),
('LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_THESSA_ANY', 'Everything in its season as the cycle of nature turns. Now is the time for war.', 'en_US'),
('LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_BEERI_ANY', 'Have you seen our golems? Magnificent works of art, examples of the finest craftsmanship known to dwarf. These things can keep going for centuries without tiring and their resilient bodies can tolerate all kinds of weather without getting the least bit rusty. And their power... well, it is almost indescribable, but I assure you that you''ll be able to experience it first hand soon...wait, did I forget to mention that?... We declare war, as of this moment.', 'en_US'),
('LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_DECIUS_MALAKIM_ANY', 'When I look at you, I cannot see light. Your soul is dark and twisted, your empire the same. The time has come for the Malakim to fulfill our obligation and destroy your civilization. The sun will burn your impure nations to cinders, only to be rebuilt in its glorious light. Dawn has come in all its glittering glory, and you will do best to avert your eyes.', 'en_US'),
('LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_BASIUM_ANY', 'You have never lived until you have almost died; for those who fought for it, life has a flavor the protected will never know.', 'en_US'),
('LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_PERPENTACH_ANY', 'As the moon takes the sky in its blood-drawn embrace[NEWLINE]As our cages will fill up with men of each race[NEWLINE]As the dancers and singers take blades to the show[NEWLINE]As apocalypse greets us with its fiery glow[NEWLINE]It''s now time for you to be out of the game[NEWLINE]But don''t die too quickly, that would be a shame[NEWLINE]Step into the darkness, in there you will stay[NEWLINE]For your death is at hand and your doom is today!', 'en_US'),
('LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_OS_GABELLA_ANY', 'I am afraid our patience with you has ended. Of course, your empire has always been scheduled for annihilation, as we all are, but your words and actions have demanded that your destruction shall come much earlier than planned.', 'en_US'),
('LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_SANDALPHON_ANY', 'The shadow of death covers your lands. The Sidar have come to end you.', 'en_US'),
('LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_FAERYL_ANY', 'Diplomacy is a slow and subtle dance. We prefer a faster tempo.', 'en_US'),
('LOC_DIPLO_AI_REFUSE_DEMAND_LEADER_DAIN_ANY', 'We prefer to investigate the mysteries of creation, but to get what we need, we are more than willing to use the arcane forces at our disposal.', 'en_US'),
('LOC_DIPLO_AI_REFUSE_DEMAND_LEADER_ARENDEL_ANY', 'Do you really think you can stand long as our enemy? Recognize the rightful Lady of this land!', 'en_US'),
('LOC_DIPLO_AI_REFUSE_DEMAND_LEADER_KEELYN_ANY', 'Not sharing makes you a bad playmate.', 'en_US'),
('LOC_DIPLO_AI_REFUSE_DEMAND_LEADER_DECIUS_BANNOR_ANY', 'It was simply a request. You have every right to refuse. It simply saddens me to note your increasingly scornful attitude.', 'en_US'),
('LOC_DIPLO_AI_REFUSE_DEMAND_LEADER_DECIUS_CALABIM_ANY', 'You wish to make this a test of wills? I have not lasted through the ages by backing down.', 'en_US'),
('LOC_DIPLO_AI_REFUSE_DEMAND_LEADER_SHEELBA_ANY', 'I didn''t have to ask. Next time I won''t.', 'en_US'),
('LOC_DIPLO_AI_REFUSE_DEMAND_LEADER_DECIUS_ANY', 'A man who stands on principle will often find the world turned against him.', 'en_US'),
('LOC_DIPLO_AI_REFUSE_DEMAND_LEADER_MAHALA_ANY', 'I was only looking for a reason.', 'en_US'),
('LOC_DIPLO_AI_REFUSE_DEMAND_LEADER_EINION_ANY', 'It was not for my own sake that I ask, but for the good of all. You hinder our mission with your stubbornness, and I urge you to think beyond your own position!', 'en_US'),
('LOC_DIPLO_AI_REFUSE_DEMAND_LEADER_ETHNE_ANY', 'It was not for my own sake that I ask, but for the good of all. You hinder our mission with your stubbornness, and I urge you to think beyond your own position!', 'en_US'),
('LOC_DIPLO_AI_REFUSE_DEMAND_LEADER_CASSIEL_ANY', 'You refuse me this petty tribute? I have always advocated self-sufficiency. Just hope I don''t decide to take what I need by force.', 'en_US'),
('LOC_DIPLO_AI_REFUSE_DEMAND_LEADER_HANNAH_ANY', 'So like a man to shout defiance into the face of the tempest. Prepare for the tempest to respond.', 'en_US'),
('LOC_DIPLO_AI_REFUSE_DEMAND_LEADER_RHOANNA_ANY', 'No? Very well. If a company of mercenaries rides through your land and happens to burn a few villages, remember this day.', 'en_US'),
('LOC_DIPLO_AI_REFUSE_DEMAND_LEADER_AURIC_ANY', 'In time, you WILL come to regret your impertinence, mortal.', 'en_US'),
('LOC_DIPLO_AI_REFUSE_DEMAND_LEADER_HYBOREM_ANY', 'Each word you offer in defiance will merit a lifetime of torture when your soul falls into my hands. Enjoy well your bravado.', 'en_US'),
('LOC_DIPLO_AI_REFUSE_DEMAND_LEADER_KEELYN_ANY', 'Would it help if I asked nicely? No? How about if my friends asks? They probably won''t ask nicely, though.', 'en_US'),
('LOC_DIPLO_AI_REFUSE_DEMAND_LEADER_KANDROS_ANY', 'We would prefer to fill our vaults through trade but conquest works as well.', 'en_US'),
('LOC_DIPLO_AI_REFUSE_DEMAND_LEADER_CARDITH_ANY', 'Come now, don''t get upset over this. We are building an edifice to last the ages, and I gave you a chance to be a part. The loss is yours.', 'en_US'),
('LOC_DIPLO_AI_REFUSE_DEMAND_LEADER_HANNAH_ANY', 'Ah, so I can''t charm the goods outta ye, huh? My mateys are much less charming, but they can be even more persuasive, I''ve found.', 'en_US'),
('LOC_DIPLO_AI_REFUSE_DEMAND_LEADER_THESSA_ANY', 'We do not wish war to ravage this land again... But I will do anything to ensure our survival.', 'en_US'),
('LOC_DIPLO_AI_REFUSE_DEMAND_LEADER_BEERI_ANY', 'Well, I had hoped to save my beauties some wear and tear, but with your refusal looks like we''ll get to see them in action sooner or later.', 'en_US'),
('LOC_DIPLO_AI_REFUSE_DEMAND_LEADER_DECIUS_MALAKIM_ANY', 'You can try to hide your secrets from us, but dawn has come and the light shall reveal all.', 'en_US'),
('LOC_DIPLO_AI_REFUSE_DEMAND_LEADER_BASIUM_ANY', 'You must not understand the severity of the times. This land has become a battleground and if you do not aid us, you side with the enemy. So be it.', 'en_US'),
('LOC_DIPLO_AI_REFUSE_DEMAND_LEADER_PERPENTACH_ANY', 'This was a gift I dearly needed,[NEWLINE]Yet my demand has gone unheeded.[NEWLINE]Is it for arrogance that you''re not paying,[NEWLINE]Or are you confused as to what I''m saying?', 'en_US'),
('LOC_DIPLO_AI_REFUSE_DEMAND_LEADER_OS_GABELLA_ANY', 'One more reason to cheer when the end takes you.', 'en_US'),
('LOC_DIPLO_AI_REFUSE_DEMAND_LEADER_SANDALPHON_ANY', 'Do you think we are unable to fulfill the threat I implied? Sidar are all around us, even now. You see, but do not perceive.', 'en_US'),
('LOC_DIPLO_AI_REFUSE_DEMAND_LEADER_FAERYL_ANY', 'You would presume to deny me? The Winter Queen? You are no longer amusing.', 'en_US'),
('LOC_DIPLO_FIRST_MEET_LEADER_DAIN_ANY', 'We are students of the arcane, not warlords. We will be good neighbors as long as you realize that mana nodes belong to us.', 'en_US'),
('LOC_DIPLO_FIRST_MEET_LEADER_ARENDEL_ANY', 'Winter has faded and the sun is again warm. You do well to pay homage to the Summer Throne.', 'en_US'),
('LOC_DIPLO_FIRST_MEET_LEADER_KEELYN_ANY', 'The game has only begun. Imagine what delights lie in store for us.', 'en_US'),
('LOC_DIPLO_FIRST_MEET_LEADER_DECIUS_BANNOR_ANY', 'You will find our cities gracious and well maintained, and our friendship unwavering, as long as you remain equally loyal.', 'en_US'),
('LOC_DIPLO_FIRST_MEET_LEADER_DECIUS_CALABIM_ANY', 'Welcome to the lands of the Calabim. I trust you will recognize our nations as joyful places, where all men and women are allowed to fulfill their potential and purpose in life - as well as in death. Here, no people go hungry, and we have the most tasteful remedies against overpopulation.', 'en_US'),
('LOC_DIPLO_FIRST_MEET_LEADER_SHEELBA_ANY', 'Do not confuse us with our wild brothers. We are both more civilized - and more deadly.', 'en_US'),
('LOC_DIPLO_FIRST_MEET_LEADER_DECIUS_ANY', 'Thrones sit easily beneath me. If you remain loyal I will allow you to keep yours.', 'en_US'),
('LOC_DIPLO_FIRST_MEET_LEADER_MAHALA_ANY', 'Long has this tundra been ours to hunt, and you think now you can just claim it?', 'en_US'),
('LOC_DIPLO_FIRST_MEET_LEADER_EINION_ANY', 'Welcome to you, friend. I am Einion, leader of the Elohim. Our quest is one of peaceful preservation of these lands, and I trust you come to us in peace as well.', 'en_US'),
('LOC_DIPLO_FIRST_MEET_LEADER_ETHNE_ANY', 'Welcome to you, friend. I am Ethne, leader of the Elohim. Our quest is one of peaceful preservation of these lands, and I trust you come to us in peace as well.', 'en_US'),
('LOC_DIPLO_FIRST_MEET_LEADER_CASSIEL_ANY', 'I respect more the sheep who flees the shepherd than the one that remains to be mutton. Which sort are you?', 'en_US'),
('LOC_DIPLO_FIRST_MEET_LEADER_HANNAH_ANY', 'The mother ocean calls the Lanun. Keep your feet in the dirt, and we''ll get along fine.', 'en_US'),
('LOC_DIPLO_FIRST_MEET_LEADER_RHOANNA_ANY', 'Well met. We will be fast friends indeed, for as long as you can afford it.', 'en_US'),
('LOC_DIPLO_FIRST_MEET_LEADER_AURIC_ANY', 'This age will be short, you should spend it preparing for what is to come.', 'en_US'),
('LOC_DIPLO_FIRST_MEET_LEADER_HYBOREM_ANY', 'Ahh... a new tribe slinking across creation, still in that twilight between birth and the recruitment of hell.', 'en_US'),
('LOC_DIPLO_FIRST_MEET_LEADER_KEELYN_ANY', 'Oh, welcome to our festive land! Won''t you stay and chat with me? Puppets, make them stay! Forever!', 'en_US'),
('LOC_DIPLO_FIRST_MEET_LEADER_KANDROS_ANY', 'The Dwarven Nation was never dimmed by the Age of Ice as winter has no hold on the underhome.', 'en_US'),
('LOC_DIPLO_FIRST_MEET_LEADER_CARDITH_ANY', 'Only by standing together can we hope to remain through the challenges of the coming age.', 'en_US'),
('LOC_DIPLO_FIRST_MEET_LEADER_HANNAH_ANY', 'Enjoy well your continents and crowded cities, but leave the islands to us.', 'en_US'),
('LOC_DIPLO_FIRST_MEET_LEADER_THESSA_ANY', 'Greetings! You are a welcome neighbor, as long as you respect us and the land we share.', 'en_US'),
('LOC_DIPLO_FIRST_MEET_LEADER_BEERI_ANY', 'Excuse our rusty manners, we are more accustomed to fashioned friends than those of tissue and tendon.', 'en_US'),
('LOC_DIPLO_FIRST_MEET_LEADER_DECIUS_MALAKIM_ANY', 'As dawn marks the beginning of day, whose outcome is unknown, so does our friendship start here.', 'en_US'),
('LOC_DIPLO_FIRST_MEET_LEADER_BASIUM_ANY', 'We come to wage war with the Infernal, your fate is inconsequential.', 'en_US'),
('LOC_DIPLO_FIRST_MEET_LEADER_PERPENTACH_ANY', 'I welcome you to us[NEWLINE]Fresh part of the show[NEWLINE]Perpentach greets you warmly[NEWLINE]your intent we shall know[NEWLINE]So tell us your wish, do not seek to beguile,[NEWLINE]To be prey for amusement[NEWLINE]or to live for a while?', 'en_US'),
('LOC_DIPLO_FIRST_MEET_LEADER_OS_GABELLA_ANY', 'Ah, what have we here, another feeble civilization awaiting the apocalypse?', 'en_US'),
('LOC_DIPLO_FIRST_MEET_LEADER_SANDALPHON_ANY', 'You must have keen eyes to spot the Sidar for many times have we walked through your lands unnoticed.', 'en_US'),
('LOC_DIPLO_FIRST_MEET_LEADER_FAERYL_ANY', 'Do not listen to the stories spread to discredit us; we don''t betray and kill ALL of our allies.', 'en_US'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_KEELYN_HAPPY', 'Well... I would but you see I already promised to help someone else.', 'en_US'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_DECIUS_CALABIM_HAPPY', 'I am afraid that is not an option, mortal.', 'en_US'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_SHEELBA_HAPPY', 'Not interested.', 'en_US'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_EINION_HAPPY', 'I am truly sorry, but such a deal would be impossible at this time.', 'en_US'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_CASSIEL_HAPPY', 'The Grigori stand to gain nothing by this, my friend.', 'en_US'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_HANNAH_HAPPY', 'Hmmph. Not going to cut it, but I''ll give ye credit for trying.', 'en_US'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_RHOANNA_HAPPY', 'After all we''ve been through? Can''t you do any better?', 'en_US'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_AURIC_HAPPY', 'You''d best dig a little deeper if you want to stay on my good side, mortal.', 'en_US'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_KEELYN_HAPPY', 'Not EVERYTHING comes from ether, dear. I just can''t give that up!', 'en_US'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_HANNAH_HAPPY', 'Aye, it''s a good deal, but we just can''t take it right now.', 'en_US'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_THESSA_HAPPY', 'This is not a balanced offer, friend. Please improve upon it.', 'en_US'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_BEERI_HAPPY', 'No can do, I''m afraid. It would violate our principles of fair trading.', 'en_US'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_DECIUS_MALAKIM_HAPPY', 'Sorry, friend, but that cannot be done at the moment. Perhaps another time.', 'en_US'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_BASIUM_HAPPY', 'You have not proven your devotion to our cause.', 'en_US'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_PERPENTACH_HAPPY', 'These were your charms, sweet; sports like these,[NEWLINE]With sweet succession, taught even toil to please;[NEWLINE]These were your bowers, their cheerful influence shed,[NEWLINE]These were your charms-but all these charms are fled.', 'en_US'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_OS_GABELLA_HAPPY', 'I am afraid your proposal is unacceptable at this time.', 'en_US'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_FAERYL_HAPPY', 'This is not the respect one shows their betters. I had thought you knew your place in the world.', 'en_US'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_DECIUS_CALABIM_UNHAPPY', 'Do you want to be feed for my fellow vampires? Then why do you keep pestering me with unreasonable demands?', 'en_US'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_SHEELBA_UNHAPPY', 'You think I''m dumb? Even I can count well enough to see that that is a bad deal!', 'en_US'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_EINION_UNHAPPY', 'Why do you waste our time? You know we can never agree to this proposal.', 'en_US'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_CASSIEL_UNHAPPY', 'I need no revelation to spot a scam. Return when you wish to truly barter.', 'en_US'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_HANNAH_UNHAPPY', 'Ye wish to insult me? Truly? Pray ye have power to match your guts.', 'en_US'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_RHOANNA_UNHAPPY', 'That? You want me to accept that? There''s got to be someone who''d appreciate our friendship more.', 'en_US'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_AURIC_UNHAPPY', 'You have no idea who you are insulting with this absurd proposal, do you?', 'en_US'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_KEELYN_UNHAPPY', 'You no longer amuse me. Puppets, show them out!', 'en_US'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_HANNAH_UNHAPPY', 'Blast you! You haven''t enough loot to make me accept that!', 'en_US'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_THESSA_UNHAPPY', 'Have you even considered our side at all? Be gone with this insult.', 'en_US'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_BEERI_UNHAPPY', 'Heh, you must think the Luchuirp foolish. Of course such a deal is impossible. Now, please stop disturbing me.', 'en_US'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_DECIUS_MALAKIM_UNHAPPY', 'Please stop wasting our time. We would get no benefit from such a deal.', 'en_US'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_BASIUM_UNHAPPY', 'You seek to buy me off? After your transgressions?', 'en_US'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_OS_GABELLA_UNHAPPY', 'Your insolence knows no bounds, it seems. I would be mad to accept such an offer.', 'en_US'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_FAERYL_UNHAPPY', 'How long does it take you to prepare for war? The Svartalfar are always ready, and you are set to give us cause as well.', 'en_US'),
('LOC_DIPLO_DEAL_INTRO_LEADER_DAIN_HAPPY', 'Well met. Let us share our secrets, hmmm?', 'en_US'),
('LOC_DIPLO_GREETING_LEADER_DAIN_HAPPY', 'Well met. Let us share our secrets, hmmm?', 'en_US'),
('LOC_DIPLO_DEAL_INTRO_LEADER_ARENDEL_HAPPY', 'The true queen of the elves shall ever welcome her friends into the warmth of her presence.', 'en_US'),
('LOC_DIPLO_GREETING_LEADER_ARENDEL_HAPPY', 'The true queen of the elves shall ever welcome her friends into the warmth of her presence.', 'en_US'),
('LOC_DIPLO_DEAL_INTRO_LEADER_KEELYN_HAPPY', 'Do you have time for a game of Somnium?', 'en_US'),
('LOC_DIPLO_GREETING_LEADER_KEELYN_HAPPY', 'Do you have time for a game of Somnium?', 'en_US'),
('LOC_DIPLO_DEAL_INTRO_LEADER_DECIUS_BANNOR_HAPPY', 'Come, make your case, but be quick. Evil''s reach grows by the year, and we must all prepare for the end.', 'en_US'),
('LOC_DIPLO_GREETING_LEADER_DECIUS_BANNOR_HAPPY', 'Come, make your case, but be quick. Evil''s reach grows by the year, and we must all prepare for the end.', 'en_US'),
('LOC_DIPLO_DEAL_INTRO_LEADER_DECIUS_CALABIM_HAPPY', 'Greetings, mortal. Can I offer you a drink?', 'en_US'),
('LOC_DIPLO_GREETING_LEADER_DECIUS_CALABIM_HAPPY', 'Greetings, mortal. Can I offer you a drink?', 'en_US'),
('LOC_DIPLO_DEAL_INTRO_LEADER_SHEELBA_HAPPY', 'If you have something useful to say, say it now. I''m feeling friendly.', 'en_US'),
('LOC_DIPLO_GREETING_LEADER_SHEELBA_HAPPY', 'If you have something useful to say, say it now. I''m feeling friendly.', 'en_US'),
('LOC_DIPLO_DEAL_INTRO_LEADER_DECIUS_HAPPY', 'In my history of betrayal and lost friends you remain steadfast. I pray that it will remain so.', 'en_US'),
('LOC_DIPLO_GREETING_LEADER_DECIUS_HAPPY', 'In my history of betrayal and lost friends you remain steadfast. I pray that it will remain so.', 'en_US'),
('LOC_DIPLO_DEAL_INTRO_LEADER_MAHALA_HAPPY', 'I''m glad to have strong friends. Makes the betrayal more exciting once we vanquish our foes.', 'en_US'),
('LOC_DIPLO_GREETING_LEADER_MAHALA_HAPPY', 'I''m glad to have strong friends. Makes the betrayal more exciting once we vanquish our foes.', 'en_US'),
('LOC_DIPLO_DEAL_INTRO_LEADER_EINION_HAPPY', 'I bid you welcome, friend of the Elohim. Pray tell, what can I do for you?', 'en_US'),
('LOC_DIPLO_GREETING_LEADER_EINION_HAPPY', 'I bid you welcome, friend of the Elohim. Pray tell, what can I do for you?', 'en_US'),
('LOC_DIPLO_DEAL_INTRO_LEADER_CASSIEL_HAPPY', 'As flies to wanton boys, are we to the gods; They kill us for their sport.', 'en_US'),
('LOC_DIPLO_GREETING_LEADER_CASSIEL_HAPPY', 'As flies to wanton boys, are we to the gods; They kill us for their sport.', 'en_US'),
('LOC_DIPLO_DEAL_INTRO_LEADER_HANNAH_HAPPY', 'I hope you are having a pleasant voyage. The waters around here can be rough on those more accustomed to frog ponds.', 'en_US'),
('LOC_DIPLO_GREETING_LEADER_HANNAH_HAPPY', 'I hope you are having a pleasant voyage. The waters around here can be rough on those more accustomed to frog ponds.', 'en_US'),
('LOC_DIPLO_DEAL_INTRO_LEADER_RHOANNA_HAPPY', 'Need the services of the Hippus?', 'en_US'),
('LOC_DIPLO_GREETING_LEADER_RHOANNA_HAPPY', 'Need the services of the Hippus?', 'en_US'),
('LOC_DIPLO_DEAL_INTRO_LEADER_AURIC_HAPPY', 'Between you and me, I think you''d better put on something a bit warmer.', 'en_US'),
('LOC_DIPLO_GREETING_LEADER_AURIC_HAPPY', 'Between you and me, I think you''d better put on something a bit warmer.', 'en_US'),
('LOC_DIPLO_DEAL_INTRO_LEADER_HYBOREM_HAPPY', 'Tell me what you need. Power? Yes, I believe we can make an arrangement...', 'en_US'),
('LOC_DIPLO_GREETING_LEADER_HYBOREM_HAPPY', 'Tell me what you need. Power? Yes, I believe we can make an arrangement...', 'en_US'),
('LOC_DIPLO_DEAL_INTRO_LEADER_KEELYN_HAPPY', 'You''ve come back to see me, how delightful! Shall we watch the skeletons dance?', 'en_US'),
('LOC_DIPLO_GREETING_LEADER_KEELYN_HAPPY', 'You''ve come back to see me, how delightful! Shall we watch the skeletons dance?', 'en_US'),
('LOC_DIPLO_DEAL_INTRO_LEADER_KANDROS_HAPPY', 'Ah. Come, we''ve much to discuss!', 'en_US'),
('LOC_DIPLO_GREETING_LEADER_KANDROS_HAPPY', 'Ah. Come, we''ve much to discuss!', 'en_US'),
('LOC_DIPLO_DEAL_INTRO_LEADER_CARDITH_HAPPY', 'It is good to speak with you again.', 'en_US'),
('LOC_DIPLO_GREETING_LEADER_CARDITH_HAPPY', 'It is good to speak with you again.', 'en_US'),
('LOC_DIPLO_DEAL_INTRO_LEADER_HANNAH_HAPPY', 'Ahoy there! Can I offer you some rum?', 'en_US'),
('LOC_DIPLO_GREETING_LEADER_HANNAH_HAPPY', 'Ahoy there! Can I offer you some rum?', 'en_US'),
('LOC_DIPLO_DEAL_INTRO_LEADER_THESSA_HAPPY', 'Ah. I was just thinking how much I value your support.', 'en_US'),
('LOC_DIPLO_GREETING_LEADER_THESSA_HAPPY', 'Ah. I was just thinking how much I value your support.', 'en_US'),
('LOC_DIPLO_DEAL_INTRO_LEADER_BEERI_HAPPY', 'Hello again. What business do you have with the Luchuirp?', 'en_US'),
('LOC_DIPLO_GREETING_LEADER_BEERI_HAPPY', 'Hello again. What business do you have with the Luchuirp?', 'en_US'),
('LOC_DIPLO_DEAL_INTRO_LEADER_DECIUS_MALAKIM_HAPPY', 'Greetings again. As ever, your presence brings light to our lands. What can the Malakim do for you?', 'en_US'),
('LOC_DIPLO_GREETING_LEADER_DECIUS_MALAKIM_HAPPY', 'Greetings again. As ever, your presence brings light to our lands. What can the Malakim do for you?', 'en_US'),
('LOC_DIPLO_DEAL_INTRO_LEADER_BASIUM_HAPPY', 'You. Well, speak already.', 'en_US'),
('LOC_DIPLO_GREETING_LEADER_BASIUM_HAPPY', 'You. Well, speak already.', 'en_US'),
('LOC_DIPLO_DEAL_INTRO_LEADER_PERPENTACH_HAPPY', 'Take this kiss upon the brow![NEWLINE] And, in parting from you now,[NEWLINE]Thus much let me avow-[NEWLINE]You are not wrong who deem[NEWLINE]That my days have been a dream;[NEWLINE]Yet if hope has flown away[NEWLINE]In a night, or in a day,[NEWLINE]In a vision, or in none,[NEWLINE]Is it therefore the less gone?[NEWLINE]All that we see or seem[NEWLINE]Is but a dream within a dream.', 'en_US'),
('LOC_DIPLO_GREETING_LEADER_PERPENTACH_HAPPY', 'Take this kiss upon the brow![NEWLINE] And, in parting from you now,[NEWLINE]Thus much let me avow-[NEWLINE]You are not wrong who deem[NEWLINE]That my days have been a dream;[NEWLINE]Yet if hope has flown away[NEWLINE]In a night, or in a day,[NEWLINE]In a vision, or in none,[NEWLINE]Is it therefore the less gone?[NEWLINE]All that we see or seem[NEWLINE]Is but a dream within a dream.', 'en_US'),
('LOC_DIPLO_DEAL_INTRO_LEADER_OS_GABELLA_HAPPY', 'Welcome once again, fellow horseman of the apocalypse. What do you need from the Sheaim?', 'en_US'),
('LOC_DIPLO_GREETING_LEADER_OS_GABELLA_HAPPY', 'Welcome once again, fellow horseman of the apocalypse. What do you need from the Sheaim?', 'en_US'),
('LOC_DIPLO_DEAL_INTRO_LEADER_SANDALPHON_HAPPY', 'You? I''m glad you are still around. Our friends tend to die off before we Sidar notice.', 'en_US'),
('LOC_DIPLO_GREETING_LEADER_SANDALPHON_HAPPY', 'You? I''m glad you are still around. Our friends tend to die off before we Sidar notice.', 'en_US'),
('LOC_DIPLO_DEAL_INTRO_LEADER_FAERYL_HAPPY', 'You are wise to keep us close.', 'en_US'),
('LOC_DIPLO_GREETING_LEADER_FAERYL_HAPPY', 'You are wise to keep us close.', 'en_US'),
('LOC_DIPLO_DEAL_INTRO_LEADER_DAIN_UNHAPPY', 'I guess I could spare a moment to listen to you... but you had better be more civil than before.', 'en_US'),
('LOC_DIPLO_GREETING_LEADER_DAIN_UNHAPPY', 'I guess I could spare a moment to listen to you... but you had better be more civil than before.', 'en_US'),
('LOC_DIPLO_DEAL_INTRO_LEADER_KEELYN_UNHAPPY', 'I bet you''ve come to beg for more favors.', 'en_US'),
('LOC_DIPLO_GREETING_LEADER_KEELYN_UNHAPPY', 'I bet you''ve come to beg for more favors.', 'en_US'),
('LOC_DIPLO_DEAL_INTRO_LEADER_DECIUS_BANNOR_UNHAPPY', 'There could have been nobility to your people. But it appears you take the easy path to power, the sure road to corruption.', 'en_US'),
('LOC_DIPLO_GREETING_LEADER_DECIUS_BANNOR_UNHAPPY', 'There could have been nobility to your people. But it appears you take the easy path to power, the sure road to corruption.', 'en_US'),
('LOC_DIPLO_DEAL_INTRO_LEADER_DECIUS_CALABIM_UNHAPPY', 'You? I do not wish to see you here, mortal. I hope you have something serious to discuss, otherwise your usefulness as a bargaining partner will soon be surpassed by the merits of your bodily nectar.', 'en_US'),
('LOC_DIPLO_GREETING_LEADER_DECIUS_CALABIM_UNHAPPY', 'You? I do not wish to see you here, mortal. I hope you have something serious to discuss, otherwise your usefulness as a bargaining partner will soon be surpassed by the merits of your bodily nectar.', 'en_US'),
('LOC_DIPLO_DEAL_INTRO_LEADER_SHEELBA_UNHAPPY', 'This had better be very, very good, or your envoy''s life is worth very, very little.', 'en_US'),
('LOC_DIPLO_GREETING_LEADER_SHEELBA_UNHAPPY', 'This had better be very, very good, or your envoy''s life is worth very, very little.', 'en_US'),
('LOC_DIPLO_DEAL_INTRO_LEADER_DECIUS_UNHAPPY', 'You are nothing but another in a long line of pampered bureaucrats trading your nation''s resources for your own petty desires.', 'en_US'),
('LOC_DIPLO_GREETING_LEADER_DECIUS_UNHAPPY', 'You are nothing but another in a long line of pampered bureaucrats trading your nation''s resources for your own petty desires.', 'en_US'),
('LOC_DIPLO_DEAL_INTRO_LEADER_MAHALA_UNHAPPY', 'Shouldn''t you be preparing for our war?', 'en_US'),
('LOC_DIPLO_GREETING_LEADER_MAHALA_UNHAPPY', 'Shouldn''t you be preparing for our war?', 'en_US'),
('LOC_DIPLO_DEAL_INTRO_LEADER_EINION_UNHAPPY', 'You should not be coming here. Your violent stature is an abomination to the Elohim.', 'en_US'),
('LOC_DIPLO_GREETING_LEADER_EINION_UNHAPPY', 'You should not be coming here. Your violent stature is an abomination to the Elohim.', 'en_US'),
('LOC_DIPLO_DEAL_INTRO_LEADER_CASSIEL_UNHAPPY', 'So, you wish to barter with the heathen do you? Out with it, then.', 'en_US'),
('LOC_DIPLO_GREETING_LEADER_CASSIEL_UNHAPPY', 'So, you wish to barter with the heathen do you? Out with it, then.', 'en_US'),
('LOC_DIPLO_DEAL_INTRO_LEADER_HANNAH_UNHAPPY', 'Ye''re on the wrong side of the Kraken of Fields.', 'en_US'),
('LOC_DIPLO_GREETING_LEADER_HANNAH_UNHAPPY', 'Ye''re on the wrong side of the Kraken of Fields.', 'en_US'),
('LOC_DIPLO_DEAL_INTRO_LEADER_RHOANNA_UNHAPPY', 'You? I suppose we could help you, though you''ll pay plenty for it.', 'en_US'),
('LOC_DIPLO_GREETING_LEADER_RHOANNA_UNHAPPY', 'You? I suppose we could help you, though you''ll pay plenty for it.', 'en_US'),
('LOC_DIPLO_DEAL_INTRO_LEADER_AURIC_UNHAPPY', 'The howling winds cry of the wrongs done to me. We forget nothing.', 'en_US'),
('LOC_DIPLO_GREETING_LEADER_AURIC_UNHAPPY', 'The howling winds cry of the wrongs done to me. We forget nothing.', 'en_US'),
('LOC_DIPLO_DEAL_INTRO_LEADER_HYBOREM_UNHAPPY', 'Please, come a little closer. Come to my world, where the rules aren''t stacked in favor of pathetic motes like yourself.', 'en_US'),
('LOC_DIPLO_GREETING_LEADER_HYBOREM_UNHAPPY', 'Please, come a little closer. Come to my world, where the rules aren''t stacked in favor of pathetic motes like yourself.', 'en_US'),
('LOC_DIPLO_DEAL_INTRO_LEADER_KEELYN_UNHAPPY', 'My friends think that you don''t like me... Hurry up and tell me what you want this time.', 'en_US'),
('LOC_DIPLO_GREETING_LEADER_KEELYN_UNHAPPY', 'My friends think that you don''t like me... Hurry up and tell me what you want this time.', 'en_US'),
('LOC_DIPLO_DEAL_INTRO_LEADER_KANDROS_UNHAPPY', 'You think you''re so high-and-mighty, eh? Well you''d better not overlook the dwarves, I''ll tell ye!', 'en_US'),
('LOC_DIPLO_GREETING_LEADER_KANDROS_UNHAPPY', 'You think you''re so high-and-mighty, eh? Well you''d better not overlook the dwarves, I''ll tell ye!', 'en_US'),
('LOC_DIPLO_DEAL_INTRO_LEADER_CARDITH_UNHAPPY', 'Greatness comes from building up, not tearing down.', 'en_US'),
('LOC_DIPLO_GREETING_LEADER_CARDITH_UNHAPPY', 'Greatness comes from building up, not tearing down.', 'en_US'),
('LOC_DIPLO_DEAL_INTRO_LEADER_HANNAH_UNHAPPY', 'If you do not impress me, you WILL be swimming home.', 'en_US'),
('LOC_DIPLO_GREETING_LEADER_HANNAH_UNHAPPY', 'If you do not impress me, you WILL be swimming home.', 'en_US'),
('LOC_DIPLO_DEAL_INTRO_LEADER_THESSA_UNHAPPY', 'It is only a matter of time until your arrogance destroys you.', 'en_US'),
('LOC_DIPLO_GREETING_LEADER_THESSA_UNHAPPY', 'It is only a matter of time until your arrogance destroys you.', 'en_US'),
('LOC_DIPLO_DEAL_INTRO_LEADER_BEERI_UNHAPPY', 'Ahh! Why do you keep pestering me?! How am I to get any research done at this rate, can you tell me that? No? Then I propose you tell me why you''ve chosen to disturb me once again. I hope for your sake that it is important very important.', 'en_US'),
('LOC_DIPLO_GREETING_LEADER_BEERI_UNHAPPY', 'Ahh! Why do you keep pestering me?! How am I to get any research done at this rate, can you tell me that? No? Then I propose you tell me why you''ve chosen to disturb me once again. I hope for your sake that it is important very important.', 'en_US'),
('LOC_DIPLO_DEAL_INTRO_LEADER_DECIUS_MALAKIM_UNHAPPY', 'Hmm, it seems a shadow is cast in this room, blocking out the sun. I wonder what it will take for it to go away.', 'en_US'),
('LOC_DIPLO_GREETING_LEADER_DECIUS_MALAKIM_UNHAPPY', 'Hmm, it seems a shadow is cast in this room, blocking out the sun. I wonder what it will take for it to go away.', 'en_US'),
('LOC_DIPLO_DEAL_INTRO_LEADER_BASIUM_UNHAPPY', 'My patience is razor thin with you. Let''s hope I like what you have to say.', 'en_US'),
('LOC_DIPLO_GREETING_LEADER_BASIUM_UNHAPPY', 'My patience is razor thin with you. Let''s hope I like what you have to say.', 'en_US'),
('LOC_DIPLO_DEAL_INTRO_LEADER_PERPENTACH_UNHAPPY', 'That is not dead which can eternal lie,[NEWLINE]And with strange aeons, even death may die.', 'en_US'),
('LOC_DIPLO_GREETING_LEADER_PERPENTACH_UNHAPPY', 'That is not dead which can eternal lie,[NEWLINE]And with strange aeons, even death may die.', 'en_US'),
('LOC_DIPLO_DEAL_INTRO_LEADER_OS_GABELLA_UNHAPPY', 'Oh, it''s you again. Don''t mind the screams, it''s just our newest recruits being conditioned. Apparently the process takes some getting used to. State your business quickly, or you might just find yourself joining them.', 'en_US'),
('LOC_DIPLO_GREETING_LEADER_OS_GABELLA_UNHAPPY', 'Oh, it''s you again. Don''t mind the screams, it''s just our newest recruits being conditioned. Apparently the process takes some getting used to. State your business quickly, or you might just find yourself joining them.', 'en_US'),
('LOC_DIPLO_DEAL_INTRO_LEADER_SANDALPHON_UNHAPPY', 'We will live to see your demise.', 'en_US'),
('LOC_DIPLO_GREETING_LEADER_SANDALPHON_UNHAPPY', 'We will live to see your demise.', 'en_US'),
('LOC_DIPLO_DEAL_INTRO_LEADER_FAERYL_UNHAPPY', 'Twelve assassins loyal to me reside in your palace alone. Get to the point and make it worth my while.', 'en_US'),
('LOC_DIPLO_GREETING_LEADER_FAERYL_UNHAPPY', 'Twelve assassins loyal to me reside in your palace alone. Get to the point and make it worth my while.', 'en_US'),
('LOC_DIPLO_MAKE_PEACE_AI_REFUSE_DEAL_LEADER_DAIN_ANY', 'You have awakened the blood of heroes coursing through our veins. It is too late for you to call this off!', 'en_US'),
('LOC_DIPLO_MAKE_PEACE_AI_REFUSE_DEAL_LEADER_ARENDEL_ANY', 'We know the side you have chosen. Peace between us is sundered.', 'en_US'),
('LOC_DIPLO_MAKE_PEACE_AI_REFUSE_DEAL_LEADER_KEELYN_ANY', 'But we are having so much fun.', 'en_US'),
('LOC_DIPLO_MAKE_PEACE_AI_REFUSE_DEAL_LEADER_DECIUS_BANNOR_ANY', 'The Crusade has been launched. Every man has taken to his sword. The legions are at march to eradicate your evil. There shall be no peace until you are broken.', 'en_US'),
('LOC_DIPLO_MAKE_PEACE_AI_REFUSE_DEAL_LEADER_DECIUS_CALABIM_ANY', 'Well, well, well... You want it to end, you say? I''m afraid that is not an option. The Calabim thirst for blood, and our own cities are all but sucked dry.', 'en_US'),
('LOC_DIPLO_MAKE_PEACE_AI_REFUSE_DEAL_LEADER_SHEELBA_ANY', 'HAH! Forget it! Don''t make the mistake of thinking I won''t finish this. When I finally catch you, your head will hang on my spear.', 'en_US'),
('LOC_DIPLO_MAKE_PEACE_AI_REFUSE_DEAL_LEADER_DECIUS_ANY', 'You are unfit for your throne, and I mean to remove you from it.', 'en_US'),
('LOC_DIPLO_MAKE_PEACE_AI_REFUSE_DEAL_LEADER_MAHALA_ANY', 'I smell blood.', 'en_US'),
('LOC_DIPLO_MAKE_PEACE_AI_REFUSE_DEAL_LEADER_EINION_ANY', 'We have seen that your nature is destructive, and any solace we would gain by such a deal would only be temporary. Much as I regret it, you will have to be put down.', 'en_US'),
('LOC_DIPLO_MAKE_PEACE_AI_REFUSE_DEAL_LEADER_ETHNE_ANY', 'We have seen that your nature is destructive, and any solace we would gain by such a deal would only be temporary. Much as I regret it, you will have to be put down.', 'en_US'),
('LOC_DIPLO_MAKE_PEACE_AI_REFUSE_DEAL_LEADER_CASSIEL_ANY', 'Alas, I offered reason, you responded with fanaticism. For my people''s sake, I must break you.', 'en_US'),
('LOC_DIPLO_MAKE_PEACE_AI_REFUSE_DEAL_LEADER_HANNAH_ANY', 'Ye seek to stop the wave from falling? To quell the storm at the peak of its fury? To stay the maw of the kraken once opened?', 'en_US'),
('LOC_DIPLO_MAKE_PEACE_AI_REFUSE_DEAL_LEADER_RHOANNA_ANY', 'When there is plunder to be had from your fields? Nah...', 'en_US'),
('LOC_DIPLO_MAKE_PEACE_AI_REFUSE_DEAL_LEADER_AURIC_ANY', 'I would not dream of quitting-I grow closer to this world by the season.', 'en_US'),
('LOC_DIPLO_MAKE_PEACE_AI_REFUSE_DEAL_LEADER_HYBOREM_ANY', 'Why should the son of fire fall down before a son of clay?', 'en_US'),
('LOC_DIPLO_MAKE_PEACE_AI_REFUSE_DEAL_LEADER_KEELYN_ANY', 'But your men look so funny when they flee my puppets! I think we''ll see a bit more of it!', 'en_US'),
('LOC_DIPLO_MAKE_PEACE_AI_REFUSE_DEAL_LEADER_KANDROS_ANY', 'What''re you trying to pull? No, enough of that, stand and fight!', 'en_US'),
('LOC_DIPLO_MAKE_PEACE_AI_REFUSE_DEAL_LEADER_CARDITH_ANY', 'If I let you go now, you''ll only threaten us again. Much as it goes against my nature, you must be devoured.', 'en_US'),
('LOC_DIPLO_MAKE_PEACE_AI_REFUSE_DEAL_LEADER_HANNAH_ANY', 'Stop now? But my ships haven''t sampled the hospitality of all your harbors yet!', 'en_US'),
('LOC_DIPLO_MAKE_PEACE_AI_REFUSE_DEAL_LEADER_THESSA_ANY', 'We are gentle creatures by nature, but you have aroused our wrath, and it has yet to be spent.', 'en_US'),
('LOC_DIPLO_MAKE_PEACE_AI_REFUSE_DEAL_LEADER_BEERI_ANY', 'You want peace, eh? Should''ve thought of that before angering me, I think. We wouldn''t want our golems standing idle, would we? Especially not when we can send them to kill annoying people like yourself.', 'en_US'),
('LOC_DIPLO_MAKE_PEACE_AI_REFUSE_DEAL_LEADER_DECIUS_MALAKIM_ANY', 'I am afraid it is too late to turn back now. Our soldiers are on the march, the light has illumined their path, and they are determined to eliminate the dread shadow that your nation casts over these lands. Your people will surely be happier once they find themselves in sunlight once again.', 'en_US'),
('LOC_DIPLO_MAKE_PEACE_AI_REFUSE_DEAL_LEADER_BASIUM_ANY', 'Mercy is for the innocent. Join your friends in Hell.', 'en_US'),
('LOC_DIPLO_MAKE_PEACE_AI_REFUSE_DEAL_LEADER_PERPENTACH_ANY', 'Why stop here already? We''ve had so much fun.[NEWLINE]We''ve seen you do battle, now let''s see you run.', 'en_US'),
('LOC_DIPLO_MAKE_PEACE_AI_REFUSE_DEAL_LEADER_OS_GABELLA_ANY', 'I think not. You have chosen the path of fire yourself, now walk it all the way to the end.', 'en_US'),
('LOC_DIPLO_MAKE_PEACE_AI_REFUSE_DEAL_LEADER_SANDALPHON_ANY', 'This conquest is a novel experience for Sidar. We cannot stop now.', 'en_US'),
('LOC_DIPLO_MAKE_PEACE_AI_REFUSE_DEAL_LEADER_FAERYL_ANY', 'You shall have peace. The peace of the grave.', 'en_US'),
('OC_DIPLO_MAKE_PEACE_FROM_AI_LEADER_KEELYN_ANY', 'Let''s play another game instead.', 'en_US'),
('OC_DIPLO_MAKE_PEACE_FROM_AI_LEADER_DECIUS_BANNOR_ANY', 'I''m tired of old men dreaming up wars for young men to die in.', 'en_US'),
('OC_DIPLO_MAKE_PEACE_FROM_AI_LEADER_DECIUS_CALABIM_ANY', 'I believe the time where war could be of benefit to us is past. For now, I would strongly advise you to cease hostilities, and perhaps we will even be inclined to do the same.', 'en_US'),
('OC_DIPLO_MAKE_PEACE_FROM_AI_LEADER_SHEELBA_ANY', 'Let''s call this one a draw.', 'en_US'),
('OC_DIPLO_MAKE_PEACE_FROM_AI_LEADER_DECIUS_ANY', 'Long have we labored in opposition, let us turn our strength to other tasks instead.', 'en_US'),
('OC_DIPLO_MAKE_PEACE_FROM_AI_LEADER_EINION_ANY', 'This war is tearing our people apart, body and soul. Please, I beg of you, let us end this meaningless conflict before naught but ashes remains of both our nations.', 'en_US'),
('OC_DIPLO_MAKE_PEACE_FROM_AI_LEADER_ETHNE_ANY', 'This war is tearing our people apart, body and soul. Please, I beg of you, let us end this meaningless conflict before naught but ashes remains of both our nations.', 'en_US'),
('OC_DIPLO_MAKE_PEACE_FROM_AI_LEADER_CASSIEL_ANY', 'Have you finished, or do your priests seek my head as well?', 'en_US'),
('OC_DIPLO_MAKE_PEACE_FROM_AI_LEADER_HANNAH_ANY', 'The seas have calmed, and so should we.', 'en_US'),
('OC_DIPLO_MAKE_PEACE_FROM_AI_LEADER_RHOANNA_ANY', 'Perhaps we should renegotiate this war?', 'en_US'),
('OC_DIPLO_MAKE_PEACE_FROM_AI_LEADER_AURIC_ANY', 'This is getting a bit too hot for me. Accept peace now and we will remember you in the next age.', 'en_US'),
('OC_DIPLO_MAKE_PEACE_FROM_AI_LEADER_KEELYN_ANY', 'My beasties are up for more... but daddy might be back any day now, so let''s stop, okay?', 'en_US'),
('OC_DIPLO_MAKE_PEACE_FROM_AI_LEADER_HANNAH_ANY', 'Shiver me timbers! It seems I find myself a bit short-handed. Now, beating me like this wouldn''t be any sport, would it?', 'en_US'),
('OC_DIPLO_MAKE_PEACE_FROM_AI_LEADER_THESSA_ANY', 'We would fight you still, but we abhor your presence in these sacred places. Shall we break off?', 'en_US'),
('OC_DIPLO_MAKE_PEACE_FROM_AI_LEADER_BEERI_ANY', 'Ahh! I am sick and tired of war! We just want to be left in peace, why won''t you let us be? Seeing our creations employed for such destructive purposes, and often destroyed in the process, is very aggravating. Let us end this now!', 'en_US'),
('OC_DIPLO_MAKE_PEACE_FROM_AI_LEADER_DECIUS_MALAKIM_ANY', 'The time has come for this horrible war to end. There''s nothing to gain for either of us, further hostilities will just lead to further destruction, until darkness and death have engulfed our lands completely. I urge you to reconsider your position, and to agree to cease hostilities once and for all.', 'en_US'),
('OC_DIPLO_MAKE_PEACE_FROM_AI_LEADER_BASIUM_ANY', 'The blood drenching the field of battle is recompense for your misjudgments. We need not meet again, if you turn your back on your former evil.', 'en_US'),
('OC_DIPLO_MAKE_PEACE_FROM_AI_LEADER_PERPENTACH_ANY', 'Bring in the force you thought I would ignore[NEWLINE]Or hold back as you ought have done before.[NEWLINE]What truth does lie on the next embroidered page[NEWLINE]Will you watch the show or walk onto our stage?', 'en_US'),
('OC_DIPLO_MAKE_PEACE_FROM_AI_LEADER_OS_GABELLA_ANY', 'You have shown great prowess in the arts of destruction, and I am much impressed. But I trust you are wise enough to know when you''ve gone too far, and that this time is now. I hope we can come to an agreement on ending this war, lest it destroys us both prematurely.', 'en_US'),
('OC_DIPLO_MAKE_PEACE_FROM_AI_LEADER_FAERYL_ANY', 'You have slipped from my web. Why don''t you retreat while I spin another?', 'en_US'),
('LOC_DIPLO_MAKE_PEACE_AI_ACCEPT_DEAL_LEADER_DAIN_ANY', 'Good, without warfare we can continue our studies. I trust you can find your own way out?', 'en_US'),
('LOC_DIPLO_MAKE_PEACE_AI_ACCEPT_DEAL_LEADER_KEELYN_ANY', 'You''re my new best friend. I broke my last one.', 'en_US'),
('LOC_DIPLO_MAKE_PEACE_AI_ACCEPT_DEAL_LEADER_DECIUS_BANNOR_ANY', 'The noble halls of the Bannor lands will ever be open to those who love justice and goodness.', 'en_US'),
('LOC_DIPLO_MAKE_PEACE_AI_ACCEPT_DEAL_LEADER_DECIUS_CALABIM_ANY', 'I suppose we can delay the inevitable massacre a little, if only to give your people time to grow healthy and numerous.', 'en_US'),
('LOC_DIPLO_MAKE_PEACE_AI_ACCEPT_DEAL_LEADER_SHEELBA_ANY', 'Ok, so you want to run away from this fight? Lucky for you, I''ve more important things to concentrate on.', 'en_US'),
('LOC_DIPLO_MAKE_PEACE_AI_ACCEPT_DEAL_LEADER_DECIUS_ANY', 'I have spent too many summers on the battlefield, this break will do our people well.', 'en_US'),
('LOC_DIPLO_MAKE_PEACE_AI_ACCEPT_DEAL_LEADER_MAHALA_ANY', 'There is no reason for us to fight when weaker prey is so abundant.', 'en_US'),
('LOC_DIPLO_MAKE_PEACE_AI_ACCEPT_DEAL_LEADER_EINION_ANY', 'We are grateful that you have accepted the only true path to wisdom. May the years of peace between our nations stretch throughout the ages, as a glorious example for all other creeds and nations.', 'en_US'),
('LOC_DIPLO_MAKE_PEACE_AI_ACCEPT_DEAL_LEADER_ETHNE_ANY', 'We are grateful that you have accepted the only true path to wisdom. May the years of peace between our nations stretch throughout the ages, as a glorious example for all other creeds and nations.', 'en_US'),
('LOC_DIPLO_MAKE_PEACE_AI_ACCEPT_DEAL_LEADER_CASSIEL_ANY', 'It is good to see peace. We play into the hands of the manipulators when we are at each other''s throats.', 'en_US'),
('LOC_DIPLO_MAKE_PEACE_AI_ACCEPT_DEAL_LEADER_HANNAH_ANY', 'Time to return to the sea. My warriors are ill at ease on land for so long.', 'en_US'),
('LOC_DIPLO_MAKE_PEACE_AI_ACCEPT_DEAL_LEADER_RHOANNA_ANY', 'Well, we''re always up for a raid. Do you know any other good targets?', 'en_US'),
('LOC_DIPLO_MAKE_PEACE_AI_ACCEPT_DEAL_LEADER_AURIC_ANY', 'If you are wise, you''ll use this peace to placate me.', 'en_US'),
('LOC_DIPLO_MAKE_PEACE_AI_ACCEPT_DEAL_LEADER_HYBOREM_ANY', 'Brute force has its charm. But intimidation and seduction are just as effective.', 'en_US'),
('LOC_DIPLO_MAKE_PEACE_AI_ACCEPT_DEAL_LEADER_KEELYN_ANY', 'Visit again, but remember to bring a present.', 'en_US'),
('LOC_DIPLO_MAKE_PEACE_AI_ACCEPT_DEAL_LEADER_KANDROS_ANY', 'Don''t think I''m a-trustin'' you yet, but we can save the battle for another day, aye?', 'en_US'),
('LOC_DIPLO_MAKE_PEACE_AI_ACCEPT_DEAL_LEADER_CARDITH_ANY', 'Let this age be one of trust and harmony, as the Age of Magic never was.', 'en_US'),
('LOC_DIPLO_MAKE_PEACE_AI_ACCEPT_DEAL_LEADER_HANNAH_ANY', 'It''s good to be friends. It makes your ships easier to plunder.', 'en_US'),
('LOC_DIPLO_MAKE_PEACE_AI_ACCEPT_DEAL_LEADER_THESSA_ANY', 'Let us now work together to repair the harm suffered by our lands.', 'en_US'),
('LOC_DIPLO_MAKE_PEACE_AI_ACCEPT_DEAL_LEADER_BEERI_ANY', 'So we are at peace all well and good can you please leave me to my experiments now?', 'en_US'),
('LOC_DIPLO_MAKE_PEACE_AI_ACCEPT_DEAL_LEADER_DECIUS_MALAKIM_ANY', 'It gladdens my heart that we have come to this agreement. Peace is more pleasant than warfare, and less expensive. Let us hope the sun will illumine our two nations for many years to come.', 'en_US'),
('LOC_DIPLO_MAKE_PEACE_AI_ACCEPT_DEAL_LEADER_BASIUM_ANY', 'Your life has been spared. Use it wisely.', 'en_US'),
('LOC_DIPLO_MAKE_PEACE_AI_ACCEPT_DEAL_LEADER_PERPENTACH_ANY', 'When at last the cast departs the stage[NEWLINE]To cheering crowds and accolades[NEWLINE]Fear not for fun when lights do fade[NEWLINE]To plays like this encores are made.', 'en_US'),
('LOC_DIPLO_MAKE_PEACE_AI_ACCEPT_DEAL_LEADER_OS_GABELLA_ANY', 'It seems there will be no exchange of fiery death between us in the immediate future. A pity...', 'en_US'),
('LOC_DIPLO_MAKE_PEACE_AI_ACCEPT_DEAL_LEADER_SANDALPHON_ANY', 'All done? Good, then we shall return. There is much to discover, and it takes much concentration to remain in this world.', 'en_US'),
('LOC_DIPLO_MAKE_PEACE_AI_ACCEPT_DEAL_LEADER_FAERYL_ANY', 'Yes, we are locked into eternal bonds of peace, dear. You can bet your life on it.', 'en_US'),
('LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_DAIN_ANY', 'Why do you keep coming here? It is suspicious... I''d rather not see you for awhile.', 'en_US'),
('LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_KEELYN_ANY', 'Oh, I was hoping it was someone else.', 'en_US'),
('LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_DECIUS_BANNOR_ANY', 'Civilized men know talk is preferable to warfare. But treating with you is getting us nowhere.', 'en_US'),
('LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_DECIUS_CALABIM_ANY', 'Bad blood runs between us. We have nothing to discuss.', 'en_US'),
('LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_SHEELBA_ANY', 'Get lost, vermin!', 'en_US'),
('LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_DECIUS_ANY', 'I am experienced enough to recognize when diplomacy is only a pretense for actions you have already committed to.', 'en_US'),
('LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_MAHALA_ANY', 'Diplomacy is a trick of the weak to tie down the strong.', 'en_US'),
('LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_EINION_ANY', 'You stray too far from the path of peace. We do not wish to speak with you.', 'en_US'),
('LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_ETHNE_ANY', 'You stray too far from the path of peace. We do not wish to speak with you.', 'en_US'),
('LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_CASSIEL_ANY', 'If I wish not to see gods, why would I parley with their puppets?', 'en_US'),
('LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_HANNAH_ANY', 'Aw, ye got your feet wet for nothing. Take a swim.', 'en_US'),
('LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_RHOANNA_ANY', 'Idle chat is for old women, not warriors.', 'en_US'),
('LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_AURIC_ANY', 'I tire of your empty prattle echoing through these sacred caverns. Return to your lands.', 'en_US'),
('LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_HYBOREM_ANY', 'Do I look like that friendly to you? Be gone, lest my flames do the talking!', 'en_US'),
('LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_KEELYN_ANY', 'Talk to the imp!', 'en_US'),
('LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_KANDROS_ANY', 'Ach, more of your blabbing? I much prefer the sound of hammer and steel.', 'en_US'),
('LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_CARDITH_ANY', 'There are matters for me to attend to more urgent than your talk. Another time.', 'en_US'),
('LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_HANNAH_ANY', 'Found sea-legs, have you? Well, take them elsewhere.', 'en_US'),
('LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_THESSA_ANY', 'Must you traipse about bellowing so? I know you are there. I simply have no desire for your company.', 'en_US'),
('LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_BEERI_ANY', 'You wish to speak with us? What a shame. We do not wish to speak with you.', 'en_US'),
('LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_DECIUS_MALAKIM_ANY', 'You walk in the darkness. Our path is too bright for you.', 'en_US'),
('LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_BASIUM_ANY', 'Do I look eager to see you?', 'en_US'),
('LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_PERPENTACH_ANY', 'We have nothing more to discuss.[NEWLINE]Why talk when you clearly have no love for us?', 'en_US'),
('LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_OS_GABELLA_ANY', 'You are naught but a puny weakling, be gone from my sight.', 'en_US'),
('LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_SANDALPHON_ANY', 'We have nothing to learn from you. You merely repeat the same lines I''ve heard from your people for generations.', 'en_US'),
('LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_FAERYL_ANY', 'Scurry along back to whatever hovel you dwell in.', 'en_US'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_DAIN_ANY', 'You see us as weak. Many do, all fools who can see only outward signs of power. We have brought the demise of stronger than you.', 'en_US'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_ARENDEL_ANY', 'This is not a path you wish to tread. The summer elves reject your threats.', 'en_US'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_KEELYN_ANY', 'That hardly seems fair.', 'en_US'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_DECIUS_BANNOR_ANY', 'A just ruler provides for the needs of his people. But not like this. Slink away, thief.', 'en_US'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_DECIUS_CALABIM_ANY', 'We''re quite afraid that we cannot accede to this... request. But you came all this way, do stick around for a bite.', 'en_US'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_SHEELBA_ANY', 'Your people have always looked down on us. Expected that we would be content with the scraps left for us. That will not continue.', 'en_US'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_DECIUS_ANY', 'You will have to do better.', 'en_US'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_MAHALA_ANY', 'Start running.', 'en_US'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_EINION_ANY', 'Why do you provoke us so? Having renounced violence makes us more resolute in resisting evil, not less.', 'en_US'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_ETHNE_ANY', 'Why do you provoke us so? Having renounced violence makes us more resolute in resisting evil, not less.', 'en_US'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_CASSIEL_ANY', 'You must be mistaken-I do not answer prayers.', 'en_US'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_HANNAH_ANY', 'The restless void fills me with hunger. Your presumption fills me with anger. Not a good combination for you', 'en_US'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_RHOANNA_ANY', 'You aren''t as persuasive as you think you are. Let''s see how well you make your case one the field.', 'en_US'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_AURIC_ANY', 'In time, you WILL come to regret your impertinence, mortal.', 'en_US'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_HYBOREM_ANY', 'Demand? You demand? The flames do not give, they consume.', 'en_US'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_KEELYN_ANY', 'You can''t do that. You don''t know my Word of Command, and I''m not telling!', 'en_US'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_KANDROS_ANY', 'Ah, no, these dwarves won''t be shoved around by the likes of you!', 'en_US'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_CARDITH_ANY', 'This isn''t the way we do things around here. Take your bullying elsewhere.', 'en_US'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_HANNAH_ANY', 'That deal''s all wet. And you''re about to be.', 'en_US'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_THESSA_ANY', 'The oak does not bend with every blustering breeze.', 'en_US'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_BEERI_ANY', 'Hee hee. Hahaha. Oh sorry, but that is not a wall you are leaning against as you threaten me.', 'en_US'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_DECIUS_MALAKIM_ANY', 'These dark desires shall lead you to your destruction.', 'en_US'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_BASIUM_ANY', 'I will not waste my breath responding to this nonsense.', 'en_US'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_OS-GABELLA_ANY', 'I have refused the demands of the gods themselves, why do you believe I would bear your yoke.', 'en_US'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_PERPENTACH_ANY', 'Could it be that my infectious mirth,[NEWLINE]After all this time has given birth,[NEWLINE]To a second wit just as grand?[NEWLINE]Or do you mean this arrogant demand?', 'en_US'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_OS_GABELLA_ANY', 'What a petty threat. And so very idle.', 'en_US'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_SANDALPHON_ANY', 'Ah, yes, jealousy. I had forgotten its hold upon the living.', 'en_US'),
('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_FAERYL_ANY', 'We have academies dedicated to the art of persuasion, you lack the talent to even qualify for entrance.', 'en_US'),
('LOC_DIPLO_ACCEPT_OPEN_BORDERS_FROM_HUMAN_LEADER_KEELYN_ANY', 'You''re the best!', 'en_US'),
('LOC_DIPLO_ACCEPT_OPEN_BORDERS_FROM_HUMAN_LEADER_DECIUS_CALABIM_ANY', 'I am most grateful.', 'en_US'),
('LOC_DIPLO_ACCEPT_OPEN_BORDERS_FROM_HUMAN_LEADER_SHEELBA_ANY', 'I''m glad you can see reason.', 'en_US'),
('LOC_DIPLO_ACCEPT_OPEN_BORDERS_FROM_HUMAN_LEADER_EINION_ANY', 'Thank you, noble friend.', 'en_US'),
('LOC_DIPLO_ACCEPT_OPEN_BORDERS_FROM_HUMAN_LEADER_ETHNE_ANY', 'Thank you, noble friend.', 'en_US'),
('LOC_DIPLO_ACCEPT_OPEN_BORDERS_FROM_HUMAN_LEADER_CASSIEL_ANY', 'I''m glad to see you can be reasonable after all.', 'en_US'),
('LOC_DIPLO_ACCEPT_OPEN_BORDERS_FROM_HUMAN_LEADER_HANNAH_ANY', 'Well, we are grateful for a safe port.', 'en_US'),
('LOC_DIPLO_ACCEPT_OPEN_BORDERS_FROM_HUMAN_LEADER_RHOANNA_ANY', 'You are an honorable friend.', 'en_US'),
('LOC_DIPLO_ACCEPT_OPEN_BORDERS_FROM_HUMAN_LEADER_AURIC_ANY', 'Yes, this is a fitting offering.', 'en_US'),
('LOC_DIPLO_ACCEPT_OPEN_BORDERS_FROM_HUMAN_LEADER_KEELYN_ANY', 'Thank you! This calls for a party, I''d better start conjuring the guests!', 'en_US'),
('LOC_DIPLO_ACCEPT_OPEN_BORDERS_FROM_HUMAN_LEADER_HANNAH_ANY', 'I told the lads you''d be a good man. You have the Lanun''s thanks.', 'en_US'),
('LOC_DIPLO_ACCEPT_OPEN_BORDERS_FROM_HUMAN_LEADER_THESSA_ANY', 'You are a true friend. You have our loyalty.', 'en_US'),
('LOC_DIPLO_ACCEPT_OPEN_BORDERS_FROM_HUMAN_LEADER_BEERI_ANY', 'Gee, thanks.', 'en_US'),
('LOC_DIPLO_ACCEPT_OPEN_BORDERS_FROM_HUMAN_LEADER_DECIUS_MALAKIM_ANY', 'I am most grateful.', 'en_US'),
('LOC_DIPLO_ACCEPT_OPEN_BORDERS_FROM_HUMAN_LEADER_BASIUM_ANY', 'It seems some mortals have wisdom after all.', 'en_US'),
('LOC_DIPLO_ACCEPT_OPEN_BORDERS_FROM_HUMAN_LEADER_PERPENTACH_ANY', 'He that is your friend indeed,[NEWLINE]He will help you in your need:[NEWLINE]If you sorrow, he will weep;[NEWLINE]If you wake, he cannot sleep:[NEWLINE]Thus of every grief in heart[NEWLINE]He with you does bear a part.[NEWLINE]These are certain signs to know[NEWLINE]Faithful friend from flattering foe.', 'en_US'),
('LOC_DIPLO_ACCEPT_OPEN_BORDERS_FROM_HUMAN_LEADER_OS_GABELLA_ANY', 'You have our gratitude, known widely to be a temporary safeguard against sudden showers of meteors. Temporary.', 'en_US'),
('LOC_DIPLO_ACCEPT_OPEN_BORDERS_FROM_HUMAN_LEADER_FAERYL_ANY', 'Hmm. Unpleasant as it is to admit, even you have your uses.', 'en_US'),
('LOC_DIPLO_DEFEAT_FROM_AI_LEADER_DAIN_ANY', 'It seems the mysteries of creation are to be forever shrouded from man. May your glories turn to ruin for this betrayal.', 'en_US'),
('LOC_DIPLO_DEFEAT_FROM_AI_LEADER_KEELYN_ANY', 'Without props how am I to pretend?Without actors this glorious play must end.Without me this war has no sense of humor.Without the Balseraphs this game will be over sooner.', 'en_US'),
('LOC_DIPLO_DEFEAT_FROM_AI_LEADER_DECIUS_BANNOR_ANY', 'We do not regret our battle to the death, however vain it was. I served the good, and your vile reign shall be ended... Somehow...', 'en_US'),
('LOC_DIPLO_DEFEAT_FROM_AI_LEADER_DECIUS_CALABIM_ANY', 'The hunter''s fate is to be tracked down and destroyed? NO! I''ve lived too long to be done in by you!', 'en_US'),
('LOC_DIPLO_DEFEAT_FROM_AI_LEADER_SHEELBA_ANY', 'Grrrr. I would crush your skull if not for all those swords and spells. Curse you and your civilization.', 'en_US'),
('LOC_DIPLO_DEFEAT_FROM_AI_LEADER_DECIUS_ANY', 'I have risen once from exile to king. I will do so again.', 'en_US'),
('LOC_DIPLO_DEFEAT_FROM_AI_LEADER_MAHALA_ANY', 'The pack will never die. Someday, you will leave your ''civilization,'' and we will be there to tear you to shreds.', 'en_US'),
('LOC_DIPLO_DEFEAT_FROM_AI_LEADER_EINION_ANY', 'I fear for this world without us to tend to it. Do you have any clue what you have wrought?', 'en_US'),
('LOC_DIPLO_DEFEAT_FROM_AI_LEADER_ETHNE_ANY', 'I fear for this world without us to tend to it. Do you have any clue what you have wrought?', 'en_US'),
('LOC_DIPLO_DEFEAT_FROM_AI_LEADER_CASSIEL_ANY', 'I had meant to free you from your strings. So you killed me for it. Farewell, puppet, enjoy your dance.', 'en_US'),
('LOC_DIPLO_DEFEAT_FROM_AI_LEADER_HANNAH_ANY', 'So, the Kraken of the Fields is destroyed? It matters not. Mother Ocean will consume you all.', 'en_US'),
('LOC_DIPLO_DEFEAT_FROM_AI_LEADER_RHOANNA_ANY', 'We could have been an asset to you. Yet you kill us all. The spirits of the Hippus shall guide your enemies to you.', 'en_US'),
('LOC_DIPLO_DEFEAT_FROM_AI_LEADER_AURIC_ANY', 'No! I was so close to returning! You cannot truly finish me, mortal, and I will see your end!', 'en_US'),
('LOC_DIPLO_DEFEAT_FROM_AI_LEADER_HYBOREM_ANY', 'So I am banished from the earth. I will await you in hell, worm. Hahahahahaha!', 'en_US'),
('LOC_DIPLO_DEFEAT_FROM_AI_LEADER_KEELYN_ANY', 'Oh! Is it time for me to be unsummoned too?', 'en_US'),
('LOC_DIPLO_DEFEAT_FROM_AI_LEADER_KANDROS_ANY', 'My gold! You''ve taken all my gold! Kill me if you will, vermin, there are dwarves untouchable in the Underhome.', 'en_US'),
('LOC_DIPLO_DEFEAT_FROM_AI_LEADER_CARDITH_ANY', 'Our proud cities lay in ashes. Our noble dragon is never to lead again. And I... do what you will with me, it matters not now that my people are destroyed.', 'en_US'),
('LOC_DIPLO_DEFEAT_FROM_AI_LEADER_HANNAH_ANY', 'Cities! Who needs ''em? Venture on the waves again, ''mate'' and you''ll walk the plank!', 'en_US'),
('LOC_DIPLO_DEFEAT_FROM_AI_LEADER_THESSA_ANY', 'Nature is truly heartless. Even her champions are feasted on upon our defeat.', 'en_US'),
('LOC_DIPLO_DEFEAT_FROM_AI_LEADER_BEERI_ANY', 'All our wonderful creations, destroyed. Why have you done this?', 'en_US'),
('LOC_DIPLO_DEFEAT_FROM_AI_LEADER_DECIUS_MALAKIM_ANY', 'I am but the servant, dark one. Lugus shall bring the end to you.', 'en_US'),
('LOC_DIPLO_DEFEAT_FROM_AI_LEADER_BASIUM_ANY', 'You finish me, before my mission is complete? Fool, the Infernal shall make your empire a living hell.', 'en_US'),
('LOC_DIPLO_DEFEAT_FROM_AI_LEADER_OS_GABELLA_ANY', 'The end will come, even if we do not bring it. Your own actions attest to that. Even in destroying us, you help achieve our goal.', 'en_US'),
('LOC_DIPLO_DEFEAT_FROM_AI_LEADER_SANDALPHON_ANY', 'So, this is what death truly tastes like. What did we fear it for? What a release, at last!', 'en_US'),
('LOC_DIPLO_DEFEAT_FROM_AI_LEADER_FAERYL_ANY', 'You think you got the last of us? Truly, you are as blind as I believed. We will always be in the forests, lurking, waiting to return.', 'en_US'),
('LOC_RELIGION_THE_ORDER', 'Order', 'en_US'),
('LOC_RELIGION_EMPYREAN', 'Empyrean', 'en_US'),
('LOC_RELIGION_KILMORPH', 'Runes of Kilmorph', 'en_US'),
('LOC_RELIGION_LEAVES', 'Fellowship of the Leaves', 'en_US'),
('LOC_RELIGION_OVERLORDS', 'Octopus Overlords', 'en_US'),
('LOC_RELIGION_ESUS', 'Council of Esus', 'en_US'),
('LOC_RELIGION_VEIL', 'Ashen Veil', 'en_US'),
('LOC_PEDIA_GOVERNMENTS_PAGEGROUP_CULTURAL_POLICIES_NAME', 'Economy', 'en_US'),
('LOC_PEDIA_GOVERNMENTS_PAGEGROUP_STATE_RELIGION_POLICIES_NAME', 'State Religion', 'en_US'),
('LOC_PEDIA_GOVERNMENTS_PAGEGROUP_MILITARY_POLICIES_NAME', 'Labor', 'en_US'),
('LOC_PEDIA_GOVERNMENTS_PAGEGROUP_ECONOMIC_POLICES_NAME', 'Cultural Values', 'en_US'),
('LOC_PEDIA_GOVERNMENTS_PAGEGROUP_DIPLOMATIC_POLICIES_NAME', 'Government', 'en_US'),
('LOC_GREATPERSON_HURRY_WONDER', 'Hurry Wonder', 'en_US'),
('LOC_GREATPERSON_BUILD_COMMAND_POST', 'Build Command Post', 'en_US'),
('LOC_GREATPERSON_BUILD_LUONNOTAR', 'Upgrade Altar of Luonnotar', 'en_US'),
('LOC_GREATPERSON_ADD_SUPER_SPECIALIST_MERCHANT', 'Add Great Merchant to city. Grants +6 [ICON_Gold] Gold, +1 [ICON_Food]Food, and +1 [ICON_GreatPerson]Great Merchant Point per turn.', 'en_US'),
('LOC_GREATPERSON_ADD_SUPER_SPECIALIST_SCIENTIST', 'Add Great Sage to city. Grants +6 [ICON_Science]Science, +1 [ICON_Production]Production, and +1 [ICON_GreatPerson]Great Sage Point per turn.', 'en_US'),
('LOC_GREATPERSON_ADD_SUPER_SPECIALIST_ARTIST', 'Add Great Bard to city. Grants +12 [ICON_Culture]Culture, +3 [ICON_Gold]Gold, and +1 [ICON_GreatPerson]Great Bard Point per turn.', 'en_US'),
('LOC_GREATPERSON_ADD_SUPER_SPECIALIST_ENGINEER', 'Add Great Engineer to city. Grants +3 [ICON_Science]Science, +3 [ICON_Production]Production, and +1 [ICON_GreatPerson]Great Engineer Point per turn.', 'en_US'),
('LOC_GREATPERSON_ADD_SUPER_SPECIALIST_PROPHET', 'Add Great Prophet to city. Grants +5 [ICON_Gold]Gold, +2 [ICON_Production]Production, and +1 [ICON_GreatPerson]Great Prophet Point per turn.', 'en_US'),
('LOC_PEDIA_CONCEPTS_PAGE_CITIES_9_CHAPTER_CONTENT_PARA_1', 'Specialists are alternative assignments for [ICON_Citizen] Citizens, which involve working a district tile instead of a normal tile. As a general rule, specialists are a good way to get yields otherwise hard to find on normal tiles, but the city needs a solid support base of [ICON_Food] Food to support them in the long term. Specialists are also particularly useful when a city grows large later in the game, and has more [ICON_Citizen] Population than there are normal tiles to work. There are different types of specialists, each with different effects. All specialist types except the generic [ICON_Citizen] Citizen have a limit on how many assignments there can be in a city.Normally, you can slot additional specialists from buildings in the district associated with that specialist type, but some Wonders or policies allow more. Check the building''s page to see if they add to the district additional [ICON_Citizen] Citizens yields.', 'en_US'),
('LOC_PEDIA_CONCEPTS_PAGE_CITIES_9_CHAPTER_CONTENT_PARA_2', 'Sages work in the Campus and provide +3 [ICON_Science]Science and +1 [ICON_GreatPerson]Great Sage Point per turn.', 'en_US'),
('LOC_PEDIA_CONCEPTS_PAGE_CITIES_9_CHAPTER_CONTENT_PARA_3', 'Priests work in the Holy Site and provide +1 [ICON_Gold]Gold, +1 [ICON_Production]Production and +1 [ICON_GreatPerson]Great Prophet Point per turn.', 'en_US'),
('LOC_PEDIA_CONCEPTS_PAGE_CITIES_9_CHAPTER_CONTENT_PARA_6', 'Merchants work in the Commercial Hub and provide +3 [ICON_Gold] Gold and +1 [ICON_GreatPerson]Great Merchant Point per turn.', 'en_US'),
('LOC_PEDIA_CONCEPTS_PAGE_CITIES_9_CHAPTER_CONTENT_PARA_7', 'Engineers work in the Industrial Zone and provide +2 [ICON_Production] Production  and +1 [ICON_GreatPerson]Great Engineer Point per turn.', 'en_US'),
('LOC_PEDIA_CONCEPTS_PAGE_CITIES_9_CHAPTER_CONTENT_PARA_8', 'Bards work in the Theater Square and provide +4 [ICON_Culture] Culture, +1 [ICON_Science]Science and +1 [ICON_GreatPerson]Great Bard Point per turn.', 'en_US'),
('LOC_PEDIA_CONCEPTS_PAGE_FAITH_4_CHAPTER_CONTENT_PARA_1', '[ICON_GreatProphet] Great Prophets can be used to upgrade the Altar of the Luonnotar, leading towards a Religious victory, if you have the Tech/Civic unlock. They can also be used to make Holy City Wonders, if you have a city that founded that Religion. They can also be placed as a Super Specialist.', 'en_US'),
('LOC_PEDIA_CONCEPTS_PAGE_GOVT_4_CHAPTER_CONTENT_PARA_5', 'State Religion: This Policy determines which religion your government works with. This allows you to build the unique units, special abilities and heroes of the religion.', 'en_US'),
('LOC_PEDIA_CONCEPTS_PAGE_COMMERCE_CHAPTER_CONTENT_TITLE', 'Commerce', 'en_US'),
('LOC_PEDIA_CONCEPTS_PAGE_COMMERCE_CHAPTER_CONTENT_PARA_1', 'In Civilization IV, [ICON_Science]Science, [ICON_Culture]Culture and [ICON_Gold]Gold were earned most oftenly from [ICON_Faith]Commerce. [ICON_Faith]Commerce was a yield that could be adjusted in the proportions of [ICON_Science]Science, and later [ICON_Culture]Culture, that could be converted from this [ICON_Faith]Commerce, the rest going to [ICON_Gold]Gold.', 'en_US'),
('LOC_PEDIA_CONCEPTS_PAGE_COMMERCE_CHAPTER_CONTENT_PARA_2', 'In VI, this has been approximated by using the unused [ICON_Faith]Faith yield, as Commerce. By default, your cities will convert this yield into a third [ICON_Science]Science, a third [ICON_Culture]Culture, and a third [ICON_Gold]Gold. In future, this will be adjustable with sliders in the UI, like Soren Johnson intended all those years ago.', 'en_US'),
('LOC_TOP_PANEL_FAITH_YIELD', 'Commerce per [ICON_Turn] Turn', 'en_US'),
('LOC_YIELD_FAITH_NAME', 'Commerce', 'en_US'),
('LOC_WORLDSPELL_BUTTON', 'Cast World Spell', 'en_US'),
('LOC_UPGRADE_LEVEL_FAILED', 'Requires level {1_Amount}.', 'en_US'),
('LOC_UPGRADE_NATIONAL_FAILED', 'You can only have {1_Amount} of this Unit Type.', 'en_US'),
('LOC_TOP_PANEL_GOLD_YIELD_TOOLTIP_COSTS_CITY_MAINTENANCE', '{1_LostGoldRate} from number of Cities', 'en_US'),
('LOC_TOP_PANEL_GOLD_YIELD_TOOLTIP_COSTS_CITY_DISTANCE_MAINTENANCE', '{1_LostGoldRate} from City Distance from Palaces', 'en_US'),
('LOC_TOP_PANEL_GOLD_YIELD_TOOLTIP_COSTS_UNIT_SUPPORT', '-{1_LostGoldRate} from Units. (Unit Count = {2_Unit_Count}. Offset = {2_Unit_Count} - ({3_Pop}(Pop) / 4) + {5_Handicap}(Handicap) = {7_UnMultiplied}. {7_UnMultiplied} / {6_HandiMult} = {1_LostGoldRate}.', 'en_US'),
('LOC_TOP_PANEL_GOLD_YIELD_TOOLTIP_COSTS_UNIT_AWAY_SUPPORT', '-{1_LostGoldRate} from Units in Foreign Territory. ({2_Unit_Count} Units away - 4) / 2 = {1_LostGoldRate}', 'en_US'),
('LOC_TOOLTIP_SAMPLE_DIPLOMACY_EVIL_HATES_GOOD', 'You are Good, Evil hates you', 'en_US'),
('LOC_TOOLTIP_SAMPLE_DIPLOMACY_EVIL_LOVES_EVIL', 'You are a fellow Evil player', 'en_US'),
('LOC_TOOLTIP_SAMPLE_DIPLOMACY_EVIL_NEUTRAL', 'You are Neutral, Evil players dislike you haven''t picked a side', 'en_US'),
('LOC_TOOLTIP_SAMPLE_DIPLOMACY_GOOD_NEUTRAL', 'You are Neutral, Good players dislike you haven''t picked a side', 'en_US'),
('LOC_TOOLTIP_SAMPLE_DIPLOMACY_EVIL_HATES_GOOD', 'You are Good, Evil hates you', 'en_US'),
('LOC_DIPLO_EVIL_HATES_GOOD', 'You are Good, they are Evil', 'en_US'),
('LOC_DIPLO_EVIL_DISLIKES_NEUTRAL', 'You are Neutral, they are Evil', 'en_US'),
('LOC_DIPLO_EVIL_LOVES_EVIL', 'You are Evil, they are Evil', 'en_US'),
('LOC_DIPLO_GOOD_HATES_EVIL', 'You are Evil, they are Good', 'en_US'),
('LOC_DIPLO_GOOD_DISLIKES_NEUTRAL', 'You are Neutral, they are Good', 'en_US'),
('LOC_DIPLO_GOOD_LOVES_GOOD', 'You are Good, they are Good', 'en_US'),
('LOC_RELIGION_FOUNDED_NOTIFICATION_TITLE', 'Religion Founded', 'en_US'),
('LOC_RELIGION_CONFUCIANISM_FOUNDED_NOTIFICATION_DESCRIPTION', 'Runes of Kilmorph was founded in a distant land', 'en_US'),
('LOC_RELIGION_PROTESTANTISM_FOUNDED_NOTIFICATION_DESCRIPTION', 'The Order was founded in a distant land', 'en_US'),
('LOC_RELIGION_JUDAISM_FOUNDED_NOTIFICATION_DESCRIPTION', 'The Empyrean was founded in a distant land', 'en_US'),
('LOC_RELIGION_CATHOLICISM_FOUNDED_NOTIFICATION_DESCRIPTION', 'Fellowship of the Leaves was founded in a distant land', 'en_US'),
('LOC_RELIGION_HINDUISM_FOUNDED_NOTIFICATION_DESCRIPTION', 'Octopus Overlords was founded in a distant land', 'en_US'),
('LOC_RELIGION_ISLAM_FOUNDED_NOTIFICATION_DESCRIPTION', 'Council of Esus was founded in a distant land', 'en_US'),
('LOC_RELIGION_BUDDHISM_FOUNDED_NOTIFICATION_DESCRIPTION', 'The Ashen Veil was founded in a distant land', 'en_US'),
('LOC_INCREMENT_GOLD_SLIDER', 'Increase ratio of [ICON_Faith]Commerce Converted into [ICON_Gold]Gold', 'en_US'),
('LOC_INCREMENT_SCIENCE_SLIDER', 'Increase ratio of [ICON_Faith]Commerce converted into [ICON_Science]Science', 'en_US'),
('LOC_COMMERCE_SLIDER', 'Commerce Sliders', 'en_US'),
('LOC_TOOLTIP_SAMPLE_DIPLOMACY_RUNES_SAME_STATE_RELIGION', 'We appreciate our brothers and sisters in the faith. (You both worship Runes of Kilmorph)', 'en_US'),
('LOC_TOOLTIP_SAMPLE_DIPLOMACY_RUNES_DIFFERENT_STATE_RELIGION', 'You are a heathen. (You worship another religion)', 'en_US'),
('LOC_DIPLO_SAME_RELIGION_RUNES', 'We appreciate our brothers and sisters in the faith.', 'en_US'),
('LOC_DIPLO_DIFFERENT_RELIGION_RUNES', 'You follow a different Religion than ours (Runes of Kilmorph).', 'en_US'),
('LOC_TOOLTIP_SAMPLE_DIPLOMACY_OCTOPUS_SAME_STATE_RELIGION', 'We appreciate our brothers and sisters in the faith. (You both worship Octopus Overlords)', 'en_US'),
('LOC_TOOLTIP_SAMPLE_DIPLOMACY_OCTOPUS_DIFFERENT_STATE_RELIGION', 'You are a heathen. (You worship another religion)', 'en_US'),
('LOC_DIPLO_SAME_RELIGION_OCTOPUS', 'We appreciate our brothers and sisters in the faith.', 'en_US'),
('LOC_DIPLO_DIFFERENT_RELIGION_OCTOPUS', 'You follow a different Religion than ours (Octopus Overlords).', 'en_US'),
('LOC_TOOLTIP_SAMPLE_DIPLOMACY_ORDER_SAME_STATE_RELIGION', 'We appreciate our brothers and sisters in the faith. (You both worship The Order)', 'en_US'),
('LOC_TOOLTIP_SAMPLE_DIPLOMACY_ORDER_DIFFERENT_STATE_RELIGION', 'You are a heathen. (You worship another religion)', 'en_US'),
('LOC_DIPLO_SAME_RELIGION_ORDER', 'We appreciate our brothers and sisters in the faith.', 'en_US'),
('LOC_DIPLO_DIFFERENT_RELIGION_ORDER', 'You follow a different Religion than ours (Order).', 'en_US'),
('LOC_TOOLTIP_SAMPLE_DIPLOMACY_VEIL_SAME_STATE_RELIGION', 'We appreciate our brothers and sisters in the faith. (You both worship The Ashen Veil)', 'en_US'),
('LOC_TOOLTIP_SAMPLE_DIPLOMACY_VEIL_DIFFERENT_STATE_RELIGION', 'You are a heathen. (You worship another religion)', 'en_US'),
('LOC_DIPLO_SAME_RELIGION_VEIL', 'We appreciate our brothers and sisters in the faith.', 'en_US'),
('LOC_DIPLO_DIFFERENT_RELIGION_VEIL', 'You follow a different Religion than ours (Ashen Veil).', 'en_US'),
('LOC_TOOLTIP_SAMPLE_DIPLOMACY_LEAVES_SAME_STATE_RELIGION', 'We appreciate our brothers and sisters in the faith. (You both worship Fellowship of the Leaves)', 'en_US'),
('LOC_TOOLTIP_SAMPLE_DIPLOMACY_LEAVES_DIFFERENT_STATE_RELIGION', 'You follow a different Religion than ours (Fellowship of Leaves).', 'en_US'),
('LOC_DIPLO_SAME_RELIGION_LEAVES', 'We appreciate our brothers and sisters in the faith.', 'en_US'),
('LOC_DIPLO_DIFFERENT_RELIGION_LEAVES', 'You are a heathen.', 'en_US'),
('LOC_TOOLTIP_SAMPLE_DIPLOMACY_EMPYREAN_SAME_STATE_RELIGION', 'We appreciate our brothers and sisters in the faith. (You both worship The Empyrean)', 'en_US'),
('LOC_TOOLTIP_SAMPLE_DIPLOMACY_EMPYREAN_DIFFERENT_STATE_RELIGION', 'You are a heathen. (You worship another religion)', 'en_US'),
('LOC_DIPLO_SAME_RELIGION_EMPYREAN', 'We appreciate our brothers and sisters in the faith.', 'en_US'),
('LOC_DIPLO_DIFFERENT_RELIGION_EMPYREAN', 'You follow a different Religion than ours (Empyrean).', 'en_US'),
('LOC_TOOLTIP_SAMPLE_DIPLOMACY_ESUS_SAME_STATE_RELIGION', 'We appreciate our brothers and sisters in the faith. (You both worship Council of Esus)', 'en_US'),
('LOC_TOOLTIP_SAMPLE_DIPLOMACY_ESUS_DIFFERENT_STATE_RELIGION', 'You are a heathen. (You worship another religion)', 'en_US'),
('LOC_DIPLO_SAME_RELIGION_ESUS', 'We appreciate our brothers and sisters in the faith.', 'en_US'),
('LOC_DIPLO_DIFFERENT_RELIGION_ESUS', 'You follow a different Religion than ours (Council of Esus).', 'en_US'),
('LOC_SLTH_TRIBE_BANNER_NAME', '{1_ClanName}', 'en_US'),
('LOC_GOLDEN_AGE_ENDED_NOTIFICATION_TITLE', 'Player Golden Age Over', 'en_US'),
('LOC_GOLDEN_AGE_ENDED_NOTIFICATION_DESCRIPTION', '{1_LeaderType}{2_Ownership} Golden Age has ended', 'en_US'),
('LOC_INSANE_CHANGE_TRAIT_NOTIFICATION_TITLE', '{1_LeaderType} {2_Ownership} changed Traits', 'en_US'),
('LOC_INSANE_CHANGE_TRAIT_NOTIFICATION_DESCRIPTION', '{1_LeaderType} {2_Ownership} Traits have changed from {3_trait}, {4_trait}, {5_trait} to {6_trait}, {7_trait}, {8_trait}', 'en_US'),
('LOC_CAST_WORLD_SPELL', 'Cast your One time World Spell?[NEWLINE][NEWLINE]{1_Description}', 'en_US');
