INSERT OR REPLACE INTO LocalizedText(Tag, Text, Language) VALUES
('LOC_BUILDING_ALCHEMICAL_SOCIETY_NAME', 'Academy', 'en_US'),
('LOC_BUILDING_AMPHITHEATER_NAME', 'Theatre', 'en_US'),
('LOC_BUILDING_ANGKOR_WAT_NAME', 'Dies Diei', 'en_US'),
('LOC_BUILDING_ARENA_NAME', 'Arena', 'en_US'),
('LOC_BUILDING_BANK_NAME', 'Moneychanger', 'en_US'),
('LOC_BUILDING_BARRACKS_NAME', 'Training Yard', 'en_US'),
('LOC_BUILDING_BIG_BEN_NAME', 'Tower Of Complacency', 'en_US'),
('LOC_BUILDING_BOLSHOI_THEATRE_NAME', 'Theatre Of Dreams', 'en_US'),
('LOC_BUILDING_CATHEDRAL_NAME', 'Temple Of The Order', 'en_US'),
('LOC_BUILDING_CHANCERY_NAME', 'Infirmary', 'en_US'),
('LOC_BUILDING_CONSULATE_NAME', 'Inn', 'en_US'),
('LOC_BUILDING_CRISTO_REDENTOR_NAME', 'Shrine Of Sirona', 'en_US'),
('LOC_BUILDING_EIFFEL_TOWER_NAME', 'Tower Of Mastery', 'en_US'),
('LOC_BUILDING_FORBIDDEN_CITY_NAME', 'Forbidden Palace', 'en_US'),
('LOC_BUILDING_GILDED_VAULT_NAME', 'Tax Office', 'en_US'),
('LOC_BUILDING_GOV_FAITH_NAME', 'Chancel Of Guardians', 'en_US'),
('LOC_BUILDING_GRANARY_NAME', 'Granary', 'en_US'),
('LOC_BUILDING_GRAND_BAZAAR_NAME', 'Bazaar Of Mammon', 'en_US'),
('LOC_BUILDING_GREAT_LIBRARY_NAME', 'Great Library', 'en_US'),
('LOC_BUILDING_GREAT_LIGHTHOUSE_NAME', 'Great Lighthouse', 'en_US'),
('LOC_BUILDING_GROVE_NAME', 'Grove', 'en_US'),
('LOC_BUILDING_GURDWARA_NAME', 'Temple Of The Empyrean', 'en_US'),
('LOC_BUILDING_HAGIA_SOPHIA_NAME', 'Temple Of Temporence', 'en_US'),
('LOC_BUILDING_HALICARNASSUS_MAUSOLEUM_NAME', 'Heron Throne', 'en_US'),
('LOC_BUILDING_JEBEL_BARKAL_NAME', 'Mines Of Galdur', 'en_US'),
('LOC_BUILDING_KOTOKU_IN_NAME', 'Shrine Of The Champion', 'en_US'),
('LOC_BUILDING_LIBRARY_NAME', 'Library', 'en_US'),
('LOC_BUILDING_LIGHTHOUSE_NAME', 'Lighthouse', 'en_US'),
('LOC_BUILDING_MADRASA_NAME', 'Mage Guild', 'en_US'),
('LOC_BUILDING_MAHABODHI_TEMPLE_NAME', 'Tower Of Alteration', 'en_US'),
('LOC_BUILDING_MARAE_NAME', 'Hunting Lodge', 'en_US'),
('LOC_BUILDING_MARKET_NAME', 'Market', 'en_US'),
('LOC_BUILDING_MEETING_HOUSE_NAME', 'Herbalist', 'en_US'),
('LOC_BUILDING_MONUMENT_NAME', 'Monument', 'en_US'),
('LOC_BUILDING_MOSQUE_NAME', 'Temple Of The Overlords', 'en_US'),
('LOC_BUILDING_OLD_GOD_OBELISK_NAME', 'Demons Altar', 'en_US'),
('LOC_BUILDING_ORACLE_NAME', 'Tower Of Divination', 'en_US'),
('LOC_BUILDING_ORDU_NAME', 'Breeding Pit', 'en_US'),
('LOC_BUILDING_ORSZAGHAZ_NAME', 'Winter Palace', 'en_US'),
('LOC_BUILDING_PALGUM_NAME', 'Brewery', 'en_US'),
('LOC_BUILDING_PETRA_NAME', 'Catacomb Libralus', 'en_US'),
('LOC_BUILDING_QUEENS_BIBLIOTHEQUE_NAME', 'Courthouse', 'en_US'),
('LOC_BUILDING_RESEARCH_LAB_NAME', 'Alchemy Lab', 'en_US'),
('LOC_BUILDING_SANCTUARY_NAME', 'Temple Of Leaves', 'en_US'),
('LOC_BUILDING_SHIPYARD_NAME', 'Shipyard', 'en_US'),
('LOC_BUILDING_SHRINE_NAME', 'Pagan Temple', 'en_US'),
('LOC_BUILDING_STABLE_NAME', 'Stable', 'en_US'),
('LOC_BUILDING_STUPA_NAME', 'Temple Of The Veil', 'en_US'),
('LOC_BUILDING_ST_BASILS_CATHEDRAL_NAME', 'Hall Of Kings', 'en_US'),
('LOC_BUILDING_SYNAGOGUE_NAME', 'Basilica', 'en_US'),
('LOC_BUILDING_TAJ_MAHAL_NAME', 'Bone Palace', 'en_US'),
('LOC_BUILDING_TLACHTLI_NAME', 'Grand Menagerie', 'en_US'),
('LOC_BUILDING_TSIKHE_NAME', 'Wall Of Stone', 'en_US'),
('LOC_BUILDING_UNIVERSITY_SANKORE_NAME', 'Guild Of The Nine', 'en_US'),
('LOC_BUILDING_WALLS_NAME', 'Palisade', 'en_US'),
('LOC_BUILDING_WAT_NAME', 'Temple Of Kilmorph', 'en_US'),
('LOC_BUILDING_WORKSHOP_NAME', 'Forge', 'en_US'),
('LOC_SLTH_BUILDING_ADULARIA_CHAMBER_NAME', 'Adularia Chamber', 'en_US'),
('LOC_SLTH_BUILDING_ADVENTURERS_GUILD_NAME', 'Adventurers Guild', 'en_US'),
('LOC_SLTH_BUILDING_ALTAR_OF_THE_LUONNOTAR_ANOINTED_NAME', 'Altar Of The Luonnotar Anointed', 'en_US'),
('LOC_SLTH_BUILDING_ALTAR_OF_THE_LUONNOTAR_BLESSED_NAME', 'Altar Of The Luonnotar Blessed', 'en_US'),
('LOC_SLTH_BUILDING_ALTAR_OF_THE_LUONNOTAR_CONSECRATED_NAME', 'Altar Of The Luonnotar Consecrated', 'en_US'),
('LOC_SLTH_BUILDING_ALTAR_OF_THE_LUONNOTAR_DIVINE_NAME', 'Altar Of The Luonnotar Divine', 'en_US'),
('LOC_SLTH_BUILDING_ALTAR_OF_THE_LUONNOTAR_EXALTED_NAME', 'Altar Of The Luonnotar Exalted', 'en_US'),
('LOC_SLTH_BUILDING_ALTAR_OF_THE_LUONNOTAR_FINAL_NAME', 'Altar Of The Luonnotar Final', 'en_US'),
('LOC_SLTH_BUILDING_ALTAR_OF_THE_LUONNOTAR_NAME', 'Altar Of The Luonnotar', 'en_US'),
('LOC_SLTH_BUILDING_AQUAE_SUCELLUS_NAME', 'Aquae Sucellus', 'en_US'),
('LOC_SLTH_BUILDING_AQUEDUCT_NAME', 'Aqueduct', 'en_US'),
('LOC_SLTH_BUILDING_ARCHERY_RANGE_NAME', 'Archery Range', 'en_US'),
('LOC_SLTH_BUILDING_ASYLUM_NAME', 'Asylum', 'en_US'),
('LOC_SLTH_BUILDING_BLASTING_WORKSHOP_NAME', 'Blasting Workshop', 'en_US'),
('LOC_SLTH_BUILDING_CARNIVAL_NAME', 'Carnival', 'en_US'),
('LOC_SLTH_BUILDING_CAVE_OF_ANCESTORS_NAME', 'Cave Of Ancestors', 'en_US'),
('LOC_SLTH_BUILDING_CELESTIAL_COMPASS_NAME', 'Celestial Compass', 'en_US'),
('LOC_SLTH_BUILDING_CITADEL_OF_LIGHT_NAME', 'Citadel Of Light', 'en_US'),
('LOC_SLTH_BUILDING_CITY_OF_A_THOUSAND_SLUMS_NAME', 'City Of A Thousand Slums', 'en_US'),
('LOC_SLTH_BUILDING_CODE_OF_JUNIL_NAME', 'Code Of Junil', 'en_US'),
('LOC_SLTH_BUILDING_COMMAND_POST_NAME', 'Command Post', 'en_US'),
('LOC_SLTH_BUILDING_CROWN_OF_AKHARIEN_NAME', 'Crown Of Akharien', 'en_US'),
('LOC_SLTH_BUILDING_DANCING_BEAR_NAME', 'Dancing Bear', 'en_US'),
('LOC_SLTH_BUILDING_DEMONIC_CITIZENS_NAME', 'Demonic Citizens', 'en_US'),
('LOC_SLTH_BUILDING_DESERT_SHRINE_NAME', 'Desert Shrine', 'en_US'),
('LOC_SLTH_BUILDING_DUNGEON_NAME', 'Dungeon', 'en_US'),
('LOC_SLTH_BUILDING_DWARF_CAGE_NAME', 'Dwarf Cage', 'en_US'),
('LOC_SLTH_BUILDING_DWARVEN_SMITHY_NAME', 'Dwarven Smithy', 'en_US'),
('LOC_SLTH_BUILDING_DWARVEN_VAULT_ABUNDANT_NAME', 'Dwarven Vault Abundant', 'en_US'),
('LOC_SLTH_BUILDING_DWARVEN_VAULT_EMPTY_NAME', 'Dwarven Vault Empty', 'en_US'),
('LOC_SLTH_BUILDING_DWARVEN_VAULT_FULL_NAME', 'Dwarven Vault Full', 'en_US'),
('LOC_SLTH_BUILDING_DWARVEN_VAULT_LOW_NAME', 'Dwarven Vault Low', 'en_US'),
('LOC_SLTH_BUILDING_DWARVEN_VAULT_NAME', 'Dwarven Vault', 'en_US'),
('LOC_SLTH_BUILDING_DWARVEN_VAULT_OVERFLOWING_NAME', 'Dwarven Vault Overflowing', 'en_US'),
('LOC_SLTH_BUILDING_DWARVEN_VAULT_STOCKED_NAME', 'Dwarven Vault Stocked', 'en_US'),
('LOC_SLTH_BUILDING_ELDER_COUNCIL_NAME', 'Elder Council', 'en_US'),
('LOC_SLTH_BUILDING_ELF_CAGE_NAME', 'Elf Cage', 'en_US'),
('LOC_SLTH_BUILDING_EYES_AND_EARS_NETWORK_NAME', 'Eyes And Ears Network', 'en_US'),
('LOC_SLTH_BUILDING_FORM_OF_THE_TITAN_NAME', 'Form Of The Titan', 'en_US'),
('LOC_SLTH_BUILDING_FREAK_SHOW_NAME', 'Freak Show', 'en_US'),
('LOC_SLTH_BUILDING_GAMBLING_HOUSE_NAME', 'Gambling House', 'en_US'),
('LOC_SLTH_BUILDING_GORILLA_CAGE_NAME', 'Gorilla Cage', 'en_US'),
('LOC_SLTH_BUILDING_GOVERNORS_MANOR_NAME', 'Governors Manor', 'en_US'),
('LOC_SLTH_BUILDING_GUILD_OF_HAMMERS_NAME', 'Guild Of Hammers', 'en_US'),
('LOC_SLTH_BUILDING_HALL_OF_MIRRORS_NAME', 'Hall Of Mirrors', 'en_US'),
('LOC_SLTH_BUILDING_HARBOR_LANUN_NAME', 'Sea Haven', 'en_US'),
('LOC_SLTH_BUILDING_HARBOR_NAME', 'Harbor', 'en_US'),
('LOC_SLTH_BUILDING_HEROIC_EPIC_NAME', 'Heroic Epic', 'en_US'),
('LOC_SLTH_BUILDING_HOPE_NAME', 'Hope', 'en_US'),
('LOC_SLTH_BUILDING_HUMAN_CAGE_NAME', 'Human Cage', 'en_US'),
('LOC_SLTH_BUILDING_INFERNAL_GRIMOIRE_NAME', 'Infernal Grimoire', 'en_US'),
('LOC_SLTH_BUILDING_INSPIRATION_NAME', 'Inspiration', 'en_US'),
('LOC_SLTH_BUILDING_JEWELER_NAME', 'Jeweler', 'en_US'),
('LOC_SLTH_BUILDING_LION_CAGE_NAME', 'Lion Cage', 'en_US'),
('LOC_SLTH_BUILDING_MERCURIAN_GATE_NAME', 'Mercurian Gate', 'en_US'),
('LOC_SLTH_BUILDING_MOKKAS_CAULDRON_NAME', 'Mokkas Cauldron', 'en_US'),
('LOC_SLTH_BUILDING_NATIONAL_EPIC_NAME', 'National Epic', 'en_US'),
('LOC_SLTH_BUILDING_NOX_NOCTIS_NAME', 'Nox Noctis', 'en_US'),
('LOC_SLTH_BUILDING_NULL_NAME', 'ZZ_Banned for Civ', 'en_US'),
('LOC_SLTH_BUILDING_OBSIDIAN_GATE_NAME', 'Obsidian Gate', 'en_US'),
('LOC_SLTH_BUILDING_ORC_CAGE_NAME', 'Orc Cage', 'en_US'),
('LOC_SLTH_BUILDING_PALLENS_ENGINE_NAME', 'Pallens Engine', 'en_US'),
('LOC_SLTH_BUILDING_PILLAR_OF_CHAINS_NAME', 'Pillar Of Chains', 'en_US'),
('LOC_SLTH_BUILDING_PLANAR_GATE_NAME', 'Planar Gate', 'en_US'),
('LOC_SLTH_BUILDING_PROPHECY_OF_RAGNAROK_NAME', 'Prophecy Of Ragnarok', 'en_US'),
('LOC_SLTH_BUILDING_PUBLIC_BATHS_NAME', 'Public Baths', 'en_US'),
('LOC_SLTH_BUILDING_RELIQUARY_NAME', 'Reliquary', 'en_US'),
('LOC_SLTH_BUILDING_RIDE_OF_THE_NINE_KINGS_NAME', 'Ride Of The Nine Kings', 'en_US'),
('LOC_SLTH_BUILDING_SCULPTORS_STUDIO_NAME', 'Sculptors Studio', 'en_US'),
('LOC_SLTH_BUILDING_SIEGE_WORKSHOP_NAME', 'Siege Workshop', 'en_US'),
('LOC_SLTH_BUILDING_SMOKEHOUSE_NAME', 'Smokehouse', 'en_US'),
('LOC_SLTH_BUILDING_SMUGGLERS_PORT_NAME', 'Smugglers Port', 'en_US'),
('LOC_SLTH_BUILDING_SONG_OF_AUTUMN_NAME', 'Song Of Autumn', 'en_US'),
('LOC_SLTH_BUILDING_SOUL_FORGE_NAME', 'Soul Forge', 'en_US'),
('LOC_SLTH_BUILDING_SPIDER_PEN_NAME', 'Spider Pen', 'en_US'),
('LOC_SLTH_BUILDING_STIGMATA_ON_THE_UNBORN_NAME', 'Stigmata On The Unborn', 'en_US'),
('LOC_SLTH_BUILDING_SYLIVENS_PERFECT_LYRE_NAME', 'Sylivens Perfect Lyre', 'en_US'),
('LOC_SLTH_BUILDING_TABLETS_OF_BAMBUR_NAME', 'Tablets Of Bambur', 'en_US'),
('LOC_SLTH_BUILDING_TAILOR_NAME', 'Tailor', 'en_US'),
('LOC_SLTH_BUILDING_TAVERN_GRIGORI_NAME', 'Tavern Grigori', 'en_US'),
('LOC_SLTH_BUILDING_TAVERN_NAME', 'Tavern', 'en_US'),
('LOC_SLTH_BUILDING_TEMPLE_OF_THE_HAND_NAME', 'Temple Of The Hand', 'en_US'),
('LOC_SLTH_BUILDING_THE_DRAGONS_HORDE_NAME', 'The Dragons Horde', 'en_US'),
('LOC_SLTH_BUILDING_THE_NECRONOMICON_NAME', 'The Necronomicon', 'en_US'),
('LOC_SLTH_BUILDING_THE_NEXUS_NAME', 'The Nexus', 'en_US'),
('LOC_SLTH_BUILDING_TIGER_CAGE_NAME', 'Tiger Cage', 'en_US'),
('LOC_SLTH_BUILDING_TOWER_OF_EYES_NAME', 'Tower Of Eyes', 'en_US'),
('LOC_SLTH_BUILDING_TOWER_OF_NECROMANCY_NAME', 'Tower Of Necromancy', 'en_US'),
('LOC_SLTH_BUILDING_TOWER_OF_THE_ELEMENTS_NAME', 'Tower Of The Elements', 'en_US'),
('LOC_SLTH_BUILDING_UNYIELDING_ORDER_NAME', 'Unyielding Order', 'en_US'),
('LOC_SLTH_BUILDING_WALLS_NAME', 'Walls', 'en_US'),
('LOC_SLTH_BUILDING_WARRENS_NAME', 'Warrens', 'en_US'),
('LOC_SLTH_BUILDING_WOLF_PEN_NAME', 'Wolf Pen', 'en_US'),
('LOC_BUILDING_ALCHEMICAL_SOCIETY_DESCRIPTION', '50% [ICON_Science] Science in this City.', 'en_US'),
('LOC_BUILDING_ANGKOR_WAT_DESCRIPTION', 'Grants a source of Sun Mana. Disciple Units trained in this city gain +2 experience. Can support a Priest and a Sage. Reveals invisible units within your borders (NOT IMPLEMENTED).', 'en_US'),
('LOC_BUILDING_BANK_DESCRIPTION', '25% [ICON_Gold] Gold in this City.', 'en_US'),
('LOC_BUILDING_BARRACKS_DESCRIPTION', 'Required to train Axemen, Champion, Phalanx and Berserkers. grants +1[ICON_Amenity] Amenity with Nationhood.', 'en_US'),
('LOC_BUILDING_BIG_BEN_DESCRIPTION', '-10% Bonus Production to Military Units.', 'en_US'),
('LOC_BUILDING_BOLSHOI_THEATRE_DESCRIPTION', '+1 Amenities per city.', 'en_US'),
('LOC_BUILDING_CATHEDRAL_DESCRIPTION', '+10% Bonus Production to Military Units. 20% [ICON_Culture] Culture in this City.', 'en_US'),
('LOC_BUILDING_CONSULATE_DESCRIPTION', '+1 Trade Route Capacity. +25 to all international Trade Route yields.', 'en_US'),
('LOC_BUILDING_EIFFEL_TOWER_DESCRIPTION', 'Building this Wonder wins you the Tower of Mastery Victory. Requires the 4 preceding Towers, Tower of Elements, Tower of Divination, Tower of Alteration. Tower of Necromancy.', 'en_US'),
('LOC_BUILDING_GILDED_VAULT_DESCRIPTION', '25% [ICON_Gold] Gold in this City.', 'en_US'),
('LOC_BUILDING_GRAND_BAZAAR_DESCRIPTION', '100% [ICON_Gold] Gold in this City.', 'en_US'),
('LOC_BUILDING_GREAT_LIGHTHOUSE_DESCRIPTION', '+2 Trade Route Capacity per coastal city.', 'en_US'),
('LOC_BUILDING_GROVE_DESCRIPTION', 'Required to train Beastmasters and Druids. They also grants +2[ICON_Amenity] Amenities with the Guardian of Nature Policy. (NOT IMPLEMENTED)', 'en_US'),
('LOC_BUILDING_GURDWARA_DESCRIPTION', '10% [ICON_Science] Science in this City. 20% [ICON_Culture] Culture in this City.', 'en_US'),
('LOC_BUILDING_HALICARNASSUS_MAUSOLEUM_DESCRIPTION', '+1 PRODUCTION on plots of type unspecified in this city.', 'en_US'),
('LOC_BUILDING_JEBEL_BARKAL_DESCRIPTION', '+3 Iron from city.', 'en_US'),
('LOC_BUILDING_LIBRARY_DESCRIPTION', '25% [ICON_Science] Science in this City.', 'en_US'),
('LOC_BUILDING_LIGHTHOUSE_DESCRIPTION', '+1 Trade Route Capacity. +1 FOOD on plots of type unspecified in this city.', 'en_US'),
('LOC_BUILDING_MADRASA_DESCRIPTION', 'Required to train Adepts.', 'en_US'),
('LOC_BUILDING_MAHABODHI_TEMPLE_DESCRIPTION', 'This tower both increases your own units resistance to spells and reduces your enemies resistance to your spells.', 'en_US'),
('LOC_BUILDING_MARAE_DESCRIPTION', 'Required to traain Hunters, Hawks, Rangers and Assassins.', 'en_US'),
('LOC_BUILDING_MARKET_DESCRIPTION', 'Cheap easy way to bankroll a civ. Comes at a Science penalty.', 'en_US'),
('LOC_BUILDING_MOSQUE_DESCRIPTION', '20% [ICON_Culture] Culture in this City.', 'en_US'),
('LOC_BUILDING_ORACLE_DESCRIPTION', 'Grant a random technology.', 'en_US'),
('LOC_BUILDING_ORDU_DESCRIPTION', 'Increases the food available to the city, making it grow faster. Little care is given to the nutritional value or method of delivery of the food, however, and the health of the city is lowered by one.', 'en_US'),
('LOC_BUILDING_PALGUM_DESCRIPTION', '+2 Ale from city.', 'en_US'),
('LOC_BUILDING_PETRA_DESCRIPTION', 'Grant free BuildingMageGuild in all cities.', 'en_US'),
('LOC_BUILDING_RESEARCH_LAB_DESCRIPTION', '10% [ICON_Science] Science in this City.', 'en_US'),
('LOC_BUILDING_SANCTUARY_DESCRIPTION', '20% [ICON_Culture] Culture in this City.', 'en_US'),
('LOC_BUILDING_SHIPYARD_DESCRIPTION', 'Naval units are granted +4 experience. +25% production towards Naval units in this city. Required to train Queen of the Line.', 'en_US'),
('LOC_BUILDING_SHRINE_DESCRIPTION', '10% [ICON_Culture] Culture in this City.', 'en_US'),
('LOC_BUILDING_SHRINE_OF_SIRONA_DESCRIPTION', 'Allows you to heal one of your units per turn.', 'en_US'),
('LOC_BUILDING_STABLE_DESCRIPTION', 'Required to train Horsemen, Horse Archers and Knights.', 'en_US'),
('LOC_BUILDING_STUPA_DESCRIPTION', '20% [ICON_Culture] Culture in this City.', 'en_US'),
('LOC_BUILDING_TLACHTLI_DESCRIPTION', 'Grant free BuildingCarnival in all cities. +2 Amenities per city. 20% [ICON_Culture] Culture in this City.', 'en_US'),
('LOC_BUILDING_WALLS_DESCRIPTION', 'While not as strong as Walls, Palisades provide a cheap defense of a city to fend off early aggression.', 'en_US'),
('LOC_BUILDING_WAT_DESCRIPTION', '20% [ICON_Culture] Culture in this City.', 'en_US'),
('LOC_BUILDING_WORKSHOP_DESCRIPTION', '25% [ICON_Production] Production in this City.', 'en_US'),
('LOC_SLTH_BUILDING_ADVENTURERS_GUILD_DESCRIPTION', '25% Great Person Great People points generated per turn. Land units trained in this city get +2 experience.', 'en_US'),
('LOC_SLTH_BUILDING_ALTAR_OF_THE_LUONNOTAR_ANOINTED_DESCRIPTION', 'New Disciple units recieve +4 experience. Can support a Priest Specialist.', 'en_US'),
('LOC_SLTH_BUILDING_ALTAR_OF_THE_LUONNOTAR_BLESSED_DESCRIPTION', '+1 Amenities in all your cities. +1 production to all Priest Specialists and this city can host one more Priests. Free Blessed Ability for all Units produced in this city. New Disciple class Units trained in this city receive +6 experience.', 'en_US'),
('LOC_SLTH_BUILDING_ALTAR_OF_THE_LUONNOTAR_CONSECRATED_DESCRIPTION', '+2 Amenities in all your cities. +1 production to all Priest Specialists and this city can host two more Priests. Free Blessed Ability for all Units produced in this city. New Disciple class Units trained in this city receive +8 experience.', 'en_US'),
('LOC_SLTH_BUILDING_ALTAR_OF_THE_LUONNOTAR_DESCRIPTION', 'Disciple units trained in this city gain +2 experience. Can support a Priest Specialist.', 'en_US'),
('LOC_SLTH_BUILDING_ALTAR_OF_THE_LUONNOTAR_DIVINE_DESCRIPTION', '+2 Amenities in all your cities. +2 production to all Priest Specialists and this city can host two more Priests. Free Blessed Ability for all Units produced in this city. New Disciple class Units trained in this city receive +10 experience.', 'en_US'),
('LOC_SLTH_BUILDING_ALTAR_OF_THE_LUONNOTAR_EXALTED_DESCRIPTION', '+3 Amenities in all your cities. +2 production to all Priest Specialists and this city can host two more Priests. Free Blessed Ability for all Units produced in this city. New Disciple class Units trained in this city receive +12 experience.', 'en_US'),
('LOC_SLTH_BUILDING_ALTAR_OF_THE_LUONNOTAR_FINAL_DESCRIPTION', '+3 Amenities in all your cities. +3 production to all Priest Specialists. Free Blessed Ability for all Units produced in this city. New Disciple class Units trained in this city receive +14 experience. Starts a Golden Age.', 'en_US'),
('LOC_SLTH_BUILDING_AQUAE_SUCELLUS_DESCRIPTION', '+1[ICON_Housing] Housing per city.', 'en_US'),
('LOC_SLTH_BUILDING_ARCHERY_RANGE_DESCRIPTION', 'Required to train Archers, Longbowmen, Crossbowmen and Marksmen.', 'en_US'),
('LOC_SLTH_BUILDING_ASYLUM_DESCRIPTION', 'Accumulate -25% less war weariness than usual. 15% [ICON_Science] Science in this City.', 'en_US'),
('LOC_SLTH_BUILDING_CARNIVAL_DESCRIPTION', '20% [ICON_Culture] Culture in this City.', 'en_US'),
('LOC_SLTH_BUILDING_CELESTIAL_COMPASS_DESCRIPTION', '50% Production Bonus to Projects in all cities', 'en_US'),
('LOC_SLTH_BUILDING_CITADEL_OF_LIGHT_DESCRIPTION', 'Apparently just grants a fireball when enemies are close lol.', 'en_US'),
('LOC_SLTH_BUILDING_CODE_OF_JUNIL_DESCRIPTION', '+1 Law Mana from city.', 'en_US'),
('LOC_SLTH_BUILDING_COMMAND_POST_DESCRIPTION', '+20% Bonus Production to Military Units. +2 experience to all trained units.', 'en_US'),
('LOC_SLTH_BUILDING_CROWN_OF_AKHARIEN_DESCRIPTION', '100% [ICON_Science] Science in this City.', 'en_US'),
('LOC_SLTH_BUILDING_DANCING_BEAR_DESCRIPTION', 'Built by a captured Bear unit, grants +1[ICON_Amenity] Amenity.', 'en_US'),
('LOC_SLTH_BUILDING_DESERT_SHRINE_DESCRIPTION', '10% [ICON_Culture] Culture in this City. +2 experience to trained Disciple units. +1 Amenity from Incense.', 'en_US'),
('LOC_SLTH_BUILDING_DUNGEON_DESCRIPTION', 'Accumulate -25% less war weariness than usual.', 'en_US'),
('LOC_SLTH_BUILDING_DWARF_CAGE_DESCRIPTION', 'Built by a captured Slave with the Dwarf promotion, grants +1[ICON_Amenity] Amenity', 'en_US'),
('LOC_SLTH_BUILDING_DWARVEN_SMITHY_DESCRIPTION', '20% [ICON_Production] Production in this City.', 'en_US'),
('LOC_SLTH_BUILDING_DWARVEN_VAULT_ABUNDANT_DESCRIPTION', '10% [ICON_Production] Production in this City.', 'en_US'),
('LOC_SLTH_BUILDING_DWARVEN_VAULT_FULL_DESCRIPTION', '25% [ICON_Production] Production in this City.', 'en_US'),
('LOC_SLTH_BUILDING_DWARVEN_VAULT_OVERFLOWING_DESCRIPTION', '25% Great Person Great People points generated per turn. 40% [ICON_Production] Production in this City.', 'en_US'),
('LOC_SLTH_BUILDING_ELDER_COUNCIL_DESCRIPTION', 'Cheap, simple Science building.', 'en_US'),
('LOC_SLTH_BUILDING_ELF_CAGE_DESCRIPTION', 'Built by a captured Slave with the Elf promotion, grants +1[ICON_Amenity] Amenity', 'en_US'),
('LOC_SLTH_BUILDING_EYES_AND_EARS_NETWORK_DESCRIPTION', 'Grants a technology to your civilization for free, if three players you have open borders agreements with already have it.', 'en_US'),
('LOC_SLTH_BUILDING_FORM_OF_THE_TITAN_DESCRIPTION', '+2 experience to all trained units. Requires a unit of level 6 or more to train. Produced twice as fast with Copper.', 'en_US'),
('LOC_SLTH_BUILDING_GAMBLING_HOUSE_DESCRIPTION', 'A Gambling House grants some happiness per 10% of the gold rate. It does tend to draw crime and increases the maintenance cost of the city. Countries that have come to depend on the happiness boost from Gambling Houses should be wary of reducing their Gold rate, doing so may start riots in their cities.', 'en_US'),
('LOC_SLTH_BUILDING_GORILLA_CAGE_DESCRIPTION', 'Built by a captured Gorilla unit, grants +1[ICON_Amenity] Amenity.', 'en_US'),
('LOC_SLTH_BUILDING_GOVERNORS_MANOR_DESCRIPTION', 'Accumulate -25% less war weariness than usual.', 'en_US'),
('LOC_SLTH_BUILDING_GUILD_OF_HAMMERS_DESCRIPTION', 'Grant free BuildingForge in all cities.', 'en_US'),
('LOC_SLTH_BUILDING_HARBOR_DESCRIPTION', '+50% to all international Trade Route yields.', 'en_US'),
('LOC_SLTH_BUILDING_HARBOR_LANUN_DESCRIPTION', 'International Trade Route yields grant 50% more yields. +25% production towards Naval units in this city.', 'en_US'),
('LOC_SLTH_BUILDING_HEROIC_EPIC_DESCRIPTION', '+100% Bonus Production to Military Units.', 'en_US'),
('LOC_SLTH_BUILDING_HOPE_DESCRIPTION', 'Free Courage ability for units trained in this city.', 'en_US'),
('LOC_SLTH_BUILDING_HUMAN_CAGE_DESCRIPTION', 'Built by a captured Slave without any racial promotion, grants +1[ICON_Amenity] Amenity', 'en_US'),
('LOC_SLTH_BUILDING_INFERNAL_GRIMOIRE_DESCRIPTION', 'Grant a random technology.', 'en_US'),
('LOC_SLTH_BUILDING_JEWELER_DESCRIPTION', '+1 Jewels from city.', 'en_US'),
('LOC_SLTH_BUILDING_LION_CAGE_DESCRIPTION', 'Built by a captured Lion unit, grants +1[ICON_Amenity] Amenity.', 'en_US'),
('LOC_SLTH_BUILDING_MERCURIAN_GATE_DESCRIPTION', 'Accumulate -100% less war weariness than usual.', 'en_US'),
('LOC_SLTH_BUILDING_MOKKAS_CAULDRON_DESCRIPTION', 'Raises units that die in the city as demons.', 'en_US'),
('LOC_SLTH_BUILDING_NATIONAL_EPIC_DESCRIPTION', '100% Great Person Great People points generated per turn.', 'en_US'),
('LOC_SLTH_BUILDING_NOX_NOCTIS_DESCRIPTION', 'Grants a source of Shadow Mana. +2 experience to Recon units. Makes units in your borders not in cities invisible (NOT IMPLEMENTED). Supports a Bard and a Merchant. +1 Gold per city with Council of Esus.', 'en_US'),
('LOC_SLTH_BUILDING_OBSIDIAN_GATE_DESCRIPTION', '+1 Trade Route Capacity.', 'en_US'),
('LOC_SLTH_BUILDING_ORC_CAGE_DESCRIPTION', 'Built by a captured Slave with the Orc ability, grants +1[ICON_Amenity] Amenity', 'en_US'),
('LOC_SLTH_BUILDING_PILLAR_OF_CHAINS_DESCRIPTION', 'Accumulate -10% less war weariness than usual.', 'en_US'),
('LOC_SLTH_BUILDING_PROPHECY_OF_RAGNAROK_DESCRIPTION', 'Units trained in this city gain the Prophecy Mark ability, increasing Armageddon count by 1 while alive. Can support an additional Priest.', 'en_US'),
('LOC_SLTH_BUILDING_PUBLIC_BATHS_DESCRIPTION', 'A lot more than bathing goes on at a Public Bathhouse. Because of these side activities, the happiness of the city is increased, but the health is reduced.', 'en_US'),
('LOC_SLTH_BUILDING_RELIQUARY_DESCRIPTION', 'All Units built in city receive free Spirit Guide promotion.', 'en_US'),
('LOC_SLTH_BUILDING_RIDE_OF_THE_NINE_KINGS_DESCRIPTION', 'Free Morale ability applied to all units trained in this city. +10 Experience to all mounted units trained in this City.', 'en_US'),
('LOC_SLTH_BUILDING_SCULPTORS_STUDIO_DESCRIPTION', 'The Luichuirp replacement for the Training Yard is unlocked at Construction, and allows the production of Golems.', 'en_US'),
('LOC_SLTH_BUILDING_SHRINE_OF_THE_CHAMPION_DESCRIPTION', 'City gives free promotion.', 'en_US'),
('LOC_SLTH_BUILDING_SIEGE_WORKSHOP_DESCRIPTION', 'Required to train Chariots, Catapults and Cannons.', 'en_US'),
('LOC_SLTH_BUILDING_SMUGGLERS_PORT_DESCRIPTION', '+1 Trade Route Capacity. 25% [ICON_Gold] Gold in this City.', 'en_US'),
('LOC_SLTH_BUILDING_SONG_OF_AUTUMN_DESCRIPTION', '+1 Nature Mana from city.', 'en_US'),
('LOC_SLTH_BUILDING_SOUL_FORGE_DESCRIPTION', '+1 Death Mana from city.', 'en_US'),
('LOC_SLTH_BUILDING_SPIDER_PEN_DESCRIPTION', '+1 Silk from city.', 'en_US'),
('LOC_SLTH_BUILDING_STIGMATA_ON_THE_UNBORN_DESCRIPTION', 'Grants a source of Entropy Mana. Free Stigmata ability granted to all units trained in the city. Supports two Priests and one Sage. NOT IMPLEMENTED: +5 to Armageddon Count. +1 Science per city with Veil Religion. ', 'en_US'),
('LOC_SLTH_BUILDING_SYLIVENS_PERFECT_LYRE_DESCRIPTION', '100% [ICON_Culture] Culture in this City.', 'en_US'),
('LOC_SLTH_BUILDING_TABLETS_OF_BAMBUR_DESCRIPTION', '+1 Earth Mana from city.', 'en_US'),
('LOC_SLTH_BUILDING_TAILOR_DESCRIPTION', '+1 Fine Clothes from city.', 'en_US'),
('LOC_SLTH_BUILDING_TAVERN_DESCRIPTION', '+1 Trade Route Capacity. +25 to all international Trade Route yields.', 'en_US'),
('LOC_SLTH_BUILDING_TAVERN_GRIGORI_DESCRIPTION', '+1 Trade Route Capacity. +25 to all international Trade Route yields.', 'en_US'),
('LOC_SLTH_BUILDING_TEMPLE_OF_THE_HAND_DESCRIPTION', '10% [ICON_Culture] Culture in this City.', 'en_US'),
('LOC_SLTH_BUILDING_THE_DRAGONS_HORDE_DESCRIPTION', '+1 Gems resource. +1 Gold resource. Grants Enchanted Blade ability to units trained in the city.', 'en_US'),
('LOC_SLTH_BUILDING_THE_NECRONOMICON_DESCRIPTION', '+1 Water Mana from city.', 'en_US'),
('LOC_SLTH_BUILDING_THE_NEXUS_DESCRIPTION', 'Grant free BuildingObsidianGate in all cities.', 'en_US'),
('LOC_SLTH_BUILDING_TIGER_CAGE_DESCRIPTION', 'Built by a captured Tiger unit, grants +1[ICON_Amenity] Amenity.', 'en_US'),
('LOC_SLTH_BUILDING_TOWER_OF_EYES_DESCRIPTION', 'Grants free Dungeon in all cities. All trained units in this city gain the Sentry promotion.', 'en_US'),
('LOC_SLTH_BUILDING_TOWER_OF_NECROMANCY_DESCRIPTION', '+1 Death Mana from city.', 'en_US'),
('LOC_SLTH_BUILDING_TOWER_OF_THE_ELEMENTS_DESCRIPTION', 'Increases the strength of all your Air, Earth, Fire, Nature and Water summons by 1.', 'en_US'),
('LOC_SLTH_BUILDING_WALLS_DESCRIPTION', 'Stronger walls, that allow ranged attacks and protect a city from attack.', 'en_US'),
('LOC_SLTH_BUILDING_WOLF_PEN_DESCRIPTION', 'Built by a captured Wolf unit, grants +1[ICON_Amenity] Amenity.', 'en_US');