INSERT OR REPLACE INTO LocalizedText(Tag, Text, Language) VALUES
('LOC_SLTH_CIVILIZATION_HIPPUS_ABILITY_SLTH_TRAIT_HORSELORD_NAME', 'Civilization Hippus Trait Horselord', 'en_US'),
('LOC_SLTH_CIVILIZATION_LJOSALFAR_ABILITY_SLTH_TRAIT_DEXTEROUS_NAME', 'Civilization Ljosalfar Trait Dexterous', 'en_US'),
('LOC_SLTH_CIVILIZATION_SVARTALFAR_ABILITY_SLTH_TRAIT_SINISTER_NAME', 'Civilization Svartalfar Trait Sinister', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_BUILDING_ADULARIA_CHAMBER_NAME', 'Building Adularia Chamber', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_BUILDING_ADVENTURERS_GUILD_NAME', 'Building Adventurers Guild', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_BUILDING_ARENA_NAME', 'Building Arena', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_BUILDING_BLASTING_WORKSHOP_NAME', 'Building Blasting Workshop', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_BUILDING_BREEDING_PIT_NAME', 'Building Breeding Pit', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_BUILDING_CAVE_OF_ANCESTORS_NAME', 'Building Cave Of Ancestors', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_BUILDING_CHANCEL_OF_GUARDIANS_NAME', 'Building Chancel Of Guardians', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_BUILDING_CITADEL_OF_LIGHT_NAME', 'Building Citadel Of Light', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_BUILDING_DESERT_SHRINE_NAME', 'Building Desert Shrine', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_BUILDING_DWARVEN_SMITHY_NAME', 'Building Dwarven Smithy', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_BUILDING_FREAK_SHOW_NAME', 'Building Freak Show', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_BUILDING_GOVERNORS_MANOR_NAME', 'Building Governors Manor', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_BUILDING_HALL_OF_MIRRORS_NAME', 'Building Hall Of Mirrors', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_BUILDING_HARBOR_LANUN_NAME', 'Building Sea Haven', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_BUILDING_JEWELER_NAME', 'Building Jeweler', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_BUILDING_PALLENS_ENGINE_NAME', 'Building Pallens Engine', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_BUILDING_PLANAR_GATE_NAME', 'Building Planar Gate', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_BUILDING_RELIQUARY_NAME', 'Building Reliquary', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_BUILDING_SCULPTORS_STUDIO_NAME', 'Building Sculptors Studio', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_BUILDING_TAILOR_NAME', 'Building Tailor', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_BUILDING_TAVERN_GRIGORI_NAME', 'Building Tavern Grigori', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_BUILDING_TEMPLE_OF_THE_HAND_NAME', 'Building Temple Of The Hand', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_BUILDING_WARRENS_NAME', 'Building Warrens', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_ABASHI_NAME', 'Unit Abashi', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_ADVENTURER_NAME', 'Unit Adventurer', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_AIRSHIP_NAME', 'Unit Airship', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_ALAZKAN_NAME', 'Unit Alazkan', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_ANGEL_OF_DEATH_NAME', 'Unit Angel Of Death', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_ARCHER_SCORPION_CLAN_NAME', 'Unit Archer Scorpion Clan', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_BALOR_NAME', 'Unit Balor', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_BARNAXUS_NAME', 'Unit Barnaxus', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_BASIUM_NAME', 'Unit Basium', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_BATTLEMASTER_NAME', 'Unit Battlemaster', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_BEASTMAN_NAME', 'Unit Beastman', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_BISON_RIDER_NAME', 'Unit Bison Rider', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_BLACK_WIND_NAME', 'Unit Black Wind', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_BLOODPET_NAME', 'Unit Bloodpet', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_BOARDING_PARTY_NAME', 'Unit Boarding Party', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_BOAR_RIDER_NAME', 'Unit Boar Rider', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_BONE_GOLEM_NAME', 'Unit Bone Golem', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_BRUJAH_NAME', 'Unit Brujah', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_CAMEL_ARCHER_NAME', 'Unit Camel Archer', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_CENTAUR_ARCHER_NAME', 'Unit Centaur Archer', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_CENTAUR_CHARGER_NAME', 'Unit Centaur Charger', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_CENTAUR_LANCER_NAME', 'Unit Centaur Lancer', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_CENTAUR_NAME', 'Unit Centaur', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_CHANTER_NAME', 'Unit Chanter', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_CHARIOT_SCORPION_CLAN_NAME', 'Unit Chariot Scorpion Clan', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_CIRCLE_OF_URD_NAME', 'Unit Circle Of Urd', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_CLOCKWORK_GOLEM_NAME', 'Unit Ckwork Golem', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_CORLINDALE_NAME', 'Unit Corlindale', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_COURTESAN_NAME', 'Unit Courtesan', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_DEATH_KNIGHT_NAME', 'Unit Death Knight', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_DECIUS_NAME', 'Unit Decius', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_DEMAGOG_NAME', 'Unit Demagog', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_DEVOUT_NAME', 'Unit Devout', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_DIVIDED_SOUL_NAME', 'Unit Divided Soul', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_DONAL_NAME', 'Unit Donal', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_DRAGON_SLAYER_NAME', 'Unit Dragon Slayer', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_DWARVEN_CANNON_NAME', 'Unit Dwarven Cannon', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_DWARVEN_DRUID_NAME', 'Unit Dwarven Druid', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_DWARVEN_SHADOW_NAME', 'Unit Dwarven Shadow', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_DWARVEN_SLINGER_NAME', 'Unit Dwarven Slinger', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_EATER_OF_DREAMS_NAME', 'Unit Eater Of Dreams', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_EURABATRES_NAME', 'Unit Eurabatres', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_FIREBOW_NAME', 'Unit Firebow', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_FLAGBEARER_NAME', 'Unit Flagbearer', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_FLURRY_NAME', 'Unit Flurry', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_FREAK_NAME', 'Unit Freak', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_FYRDWELL_NAME', 'Unit Fyrdwell', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_GARGOYLE_NAME', 'Unit Gargoyle', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_GHOST_NAME', 'Unit Ghost', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_GILDEN_NAME', 'Unit Gilden', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_GOBLIN_NAME', 'Unit Goblin', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_GOBLIN_SCORPION_CLAN_NAME', 'Unit Goblin Scorpion Clan', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_GOVANNON_NAME', 'Unit Govannon', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_GRIGORI_MEDIC_NAME', 'Unit Grigori Medic', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_GUYBRUSH_NAME', 'Unit Guybrush', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_HARLEQUIN_NAME', 'Unit Harlequin', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_HELLHOUND_NAME', 'Unit Hellhound', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_HERALD_NAME', 'Unit Herald', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_HERNE_NAME', 'Unit Herne', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_HIGH_PRIEST_OF_WINTER_NAME', 'Unit High Priest Of Winter', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_HORNGUARD_NAME', 'Unit Hornguard', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_HYBOREM_NAME', 'Unit Hyborem', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_ILLUSIONIST_NAME', 'Unit Illusionist', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_IMP_NAME', 'Unit Imp', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_IRON_GOLEM_NAME', 'Unit Iron Golem', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_JAVELIN_THROWER_NAME', 'Unit Javelin Thrower', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_LIGHTBRINGER_NAME', 'Unit Lightbringer', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_LIZARDMAN_ASSASSIN_NAME', 'Unit Lizardman Assassin', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_LIZARDMAN_BEASTMASTER_NAME', 'Unit Lizardman Beastmaster', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_LIZARDMAN_DRUID_NAME', 'Unit Lizardman Druid', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_LIZARDMAN_NAME', 'Unit Lizardman', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_LIZARDMAN_RANGER_NAME', 'Unit Lizardman Ranger', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_LOKI_NAME', 'Unit Loki', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_LOSHA_NAME', 'Unit Losha', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_LUCIAN_NAME', 'Unit Lucian', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_LUONNOTAR_NAME', 'Unit Luonnotar', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_MAGNADINE_NAME', 'Unit Magnadine', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_MAROS_NAME', 'Unit Maros', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_MERCENARY_MOUNTED_NAME', 'Unit Mercenary Mounted', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_MIMIC_NAME', 'Unit Mimic', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_MONK_NAME', 'Unit Monk', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_MOROI_NAME', 'Unit Moroi', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_MUD_GOLEM_NAME', 'Unit Mud Golem', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_MYCONID_NAME', 'Unit Myconid', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_NULLSTONE_GOLEM_NAME', 'Unit Nullstone Golem', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_NYXKIN_NAME', 'Unit Nyxkin', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_OGRE_NAME', 'Unit Ogre', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_OGRE_WARCHIEF_NAME', 'Unit Ogre Warchief', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_OPHANIM_NAME', 'Unit Ophanim', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_PIRATE_NAME', 'Unit Pirate', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_POLAR_BEAR_NAME', 'Unit Polar Bear', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_PYRE_ZOMBIE_NAME', 'Unit Pyre Zombie', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_RANTINE_NAME', 'Unit Rantine', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_RATHUS_NAME', 'Unit Rathus', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_REPENTANT_ANGEL_NAME', 'Unit Repentant Angel', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_SERAPH_NAME', 'Unit Seraph', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_SHAMAN_NAME', 'Unit Shaman', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_SKULD_NAME', 'Unit Skuld', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_SPIDERKIN_NAME', 'Unit Spiderkin', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_STONESKIN_OGRE_NAME', 'Unit Stoneskin Ogre', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_TASKMASTER_NAME', 'Unit Taskmaster', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_TEUTORIX_NAME', 'Unit Teutorix', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_TREBUCHET_NAME', 'Unit Trebuchet', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_VALKYRIE_NAME', 'Unit Valkyrie', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_VAMPIRE_LORD_NAME', 'Unit Vampire Lord', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_VAMPIRE_NAME', 'Unit Vampire', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_VERDANDI_NAME', 'Unit Verdandi', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_WAR_MACHINE_NAME', 'Unit War Machine', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_WAR_TORTOISE_NAME', 'Unit War Tortoise', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_WILBOMAN_NAME', 'Unit Wilboman', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_WIZARD_NAME', 'Unit Wizard', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_WOLF_RIDER_NAME', 'Unit Wolf Rider', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_WOLF_RIDER_SCORPION_CLAN_NAME', 'Unit Wolf Rider Scorpion Clan', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_UNIT_WOOD_GOLEM_NAME', 'Unit Wood Golem', 'en_US'),
('LOC_SLTH_TRAIT_RELIGION_UNIT_ARTHENDAIN_NAME', 'Unit Arthendain', 'en_US'),
('LOC_SLTH_TRAIT_RELIGION_UNIT_BAMBUR_NAME', 'Unit Bambur', 'en_US'),
('LOC_SLTH_TRAIT_RELIGION_UNIT_CRUSADER_NAME', 'Unit Crusader', 'en_US'),
('LOC_SLTH_TRAIT_RELIGION_UNIT_DEMAGOG_NAME', 'Unit Demagog', 'en_US'),
('LOC_SLTH_TRAIT_RELIGION_UNIT_DISCIPLE_OCTOPUS_OVERLORDS_NAME', 'Unit Disciple Octopus Overlords', 'en_US'),
('LOC_SLTH_TRAIT_RELIGION_UNIT_DISCIPLE_THE_ORDER_NAME', 'Unit Disciple The Order', 'en_US'),
('LOC_SLTH_TRAIT_RELIGION_UNIT_DROWN_NAME', 'Unit Drown', 'en_US'),
('LOC_SLTH_TRAIT_RELIGION_UNIT_HEMAH_NAME', 'Unit Hemah', 'en_US'),
('LOC_SLTH_TRAIT_RELIGION_UNIT_HIGH_PRIEST_OF_KILMORPH_NAME', 'Unit High Priest Of Kilmorph', 'en_US'),
('LOC_SLTH_TRAIT_RELIGION_UNIT_HIGH_PRIEST_OF_THE_ORDER_NAME', 'Unit High Priest Of The Order', 'en_US'),
('LOC_SLTH_TRAIT_RELIGION_UNIT_HIGH_PRIEST_OF_THE_OVERLORDS_NAME', 'Unit High Priest Of The Overlords', 'en_US'),
('LOC_SLTH_TRAIT_RELIGION_UNIT_LUNATIC_NAME', 'Unit Lunatic', 'en_US'),
('LOC_SLTH_TRAIT_RELIGION_UNIT_MITHRIL_GOLEM_NAME', 'Unit Mithril Golem', 'en_US'),
('LOC_SLTH_TRAIT_RELIGION_UNIT_PARAMANDER_NAME', 'Unit Paramander', 'en_US'),
('LOC_SLTH_TRAIT_RELIGION_UNIT_PRIEST_OF_KILMORPH_NAME', 'Unit Priest Of Kilmorph', 'en_US'),
('LOC_SLTH_TRAIT_RELIGION_UNIT_PRIEST_OF_THE_ORDER_NAME', 'Unit Priest Of The Order', 'en_US'),
('LOC_SLTH_TRAIT_RELIGION_UNIT_PRIEST_OF_THE_OVERLORDS_NAME', 'Unit Priest Of The Overlords', 'en_US'),
('LOC_SLTH_TRAIT_RELIGION_UNIT_SAVEROUS_NAME', 'Unit Saverous', 'en_US'),
('LOC_SLTH_TRAIT_RELIGION_UNIT_VALIN_NAME', 'Unit Valin', 'en_US'),
('LOC_CIVILIZATION_LJOSALFAR_ABILITY_SLTH_TRAIT_DEXTEROUS_DESCRIPTION', '+5[ICON_STRENGTH] Combat Strength.', 'en_US'),
('LOC_CIVILIZATION_SVARTALFAR_ABILITY_SLTH_TRAIT_SINISTER_DESCRIPTION', '+5[ICON_STRENGTH] Combat Strength.', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_AMURITES_COOL_NAME', 'Masters of Sorcery', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_BALSERAPHS_COOL_NAME', 'Twister Carnival', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_BANNOR_COOL_NAME', 'Holy Crusaders', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_CALABIM_COOL_NAME', 'Vampiric Aristocracy', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_CLAN_OF_EMBERS_COOL_NAME', 'Bestial Tribes', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_DOVIELLO_COOL_NAME', 'Wolves of Winter', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_ELOHIM_COOL_NAME', 'Tolerant', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_GRIGORI_COOL_NAME', 'Agnostic Heroes', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_HIPPUS_COOL_NAME', 'Horselords', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_ILLIANS_COOL_NAME', 'Resurrectionists of Fallen Winter', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_INFERNAL_COOL_NAME', 'Fallow', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_KHAZAD_COOL_NAME', 'Dwarven Misers', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_KURIOTATES_COOL_NAME', 'Sprawling', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_LANUN_COOL_NAME', 'Seafaring', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_LJOSALFAR_COOL_NAME', 'Elven Forest Defenders', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_LUCHUIRP_COOL_NAME', 'Golem Crafters', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_MALAKIM_COOL_NAME', 'Desert Nomads', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_MERCURIANS_COOL_NAME', 'Angelic Warriors', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_SHEAIM_COOL_NAME', 'Seekers of Armageddon', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_SIDAR_COOL_NAME', 'Ghostly Spirits', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_SVARTALFAR_COOL_NAME', 'Elven Assassins', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_AMURITES_COOL_DESCRIPTION', 'Grants a source of [ICON_RESOURCE_MANA_METAMAGIC]Metamagic, [ICON_RESOURCE_MANA_FIRE]Fire and [ICON_RESOURCE_MANA_BODY]Body Mana.', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_BALSERAPHS_COOL_DESCRIPTION', 'Can enslave the sentient races for extra Amenities, and magic units can summon Puppets, short-lived duplicates that can cast T1 spells. Starts with a source of [ICON_RESOURCE_MANA_AIR]Air, [ICON_RESOURCE_MANA_CHAOS]Chaos and [ICON_RESOURCE_MANA_MIND]Mind Mana.', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_BANNOR_COOL_DESCRIPTION', 'The Bannor can adopt the Crusade Policy when using the Order state religion. Starts with a source of [ICON_RESOURCE_MANA_EARTH]Earth, [ICON_RESOURCE_MANA_LAW]Law and [ICON_RESOURCE_MANA_SPIRIT]Spirit Mana. Accumulate -10% less war weariness than usual.', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_CALABIM_COOL_DESCRIPTION', 'Starts with a source of [ICON_RESOURCE_MANA_BODY]Body, [ICON_RESOURCE_MANA_LAW]Law and [ICON_RESOURCE_MANA_SHADOW]Shadow Mana. Accumulate -10% less war weariness than usual.', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_CLAN_OF_EMBERS_COOL_DESCRIPTION', 'Starts at peace with the Barbarians and can treat with Goblin Forts and Lizardmen ruins. Recon line units are Lizardmen, starting with the Amphibious ability. Starts with a source of [ICON_RESOURCE_MANA_BODY]Body, [ICON_RESOURCE_MANA_FIRE]Fire and [ICON_RESOURCE_MANA_NATURE]Nature Mana. Accumulate -40% less war weariness than usual.', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_DOVIELLO_COOL_DESCRIPTION', 'Starts at peace with the Barbarians. Starts with a source of [ICON_RESOURCE_MANA_BODY]Body, [ICON_RESOURCE_MANA_CHAOS]Chaos and [ICON_RESOURCE_MANA_EARTH]Earth Mana. Accumulate -40% less war weariness than usual.', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_ELOHIM_COOL_DESCRIPTION', 'Their cities can produce units and building of the original city founder. NOT IMPLEMENTED Starts with a source of [ICON_RESOURCE_MANA_NATURE]Nature, [ICON_RESOURCE_MANA_SPIRIT]Spirit and [ICON_RESOURCE_MANA_WATER]Water Mana. Accumulate 20% less war weariness than usual.', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_GRIGORI_COOL_DESCRIPTION', '15% increased [ICON_GreatPerson]Great Person Great People points. Can recruit Great Adventurers, Heroes that gain experience per turn and can upgrade along any unit class. Cannot adopt any state religion, or build any religious temples. Starts with a source of [ICON_RESOURCE_MANA_ENCHANTMENT]Enchantment,[ICON_RESOURCE_MANA_SPIRIT]Spirit and [ICON_RESOURCE_MANA_WATER]Water Mana.', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_HIPPUS_COOL_DESCRIPTION', 'Mounted units have +1 [ICON_MOVEMENT]Movement and +5 [ICON_Strength]Strength. Starts with a source of [ICON_RESOURCE_MANA_AIR]Air and [ICON_RESOURCE_MANA_NATURE]Nature Mana, as well as a source of [ICON_RESOURCE_HORSES]Horse.', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_ILLIANS_COOL_DESCRIPTION', 'Has access to a series of Projects, eventually leading to the near unstoppable Auric Ascended. +2[ICON_FOOD] on Snow tiles. Cannot adopt any state religion, or build any religious temples. Units are Winterborn, resisting cold and are stronger on Snow and Tundra. Starts with a source of [ICON_RESOURCE_MANA_ICE]Ice, [ICON_RESOURCE_MANA_ENCHANTMENT]Enchantment and [ICON_RESOURCE_MANA_LAW]Law Mana.', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_INFERNAL_COOL_DESCRIPTION', 'The hellspawn of Infernal cities do not reproduce like the mortal rabble, but also require no sustenance, so cities are unaffected by Food. Instead, the souls of dead Evil units enter Erebus through Infernal lands as lowly Manes, who can be used to increase city Population, or upgraded into strong Demonic units. Accumulate -100% less war weariness than usual. 50% [ICON_Production] Production in Capital City. Starts with a source of [ICON_RESOURCE_MANA_FIRE]Fire and Entropy Mana.They also start with a source of [ICON_RESOURCE_IRON]Iron.', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_KHAZAD_COOL_DESCRIPTION', 'Khazad cities gain maluses or bonuses, based on their current Gold divided by their number of cities. Overflowing Vaults of gold inspire production bonuses, happiness and even helps inspire Great People. An empty vault leads to unhappiness. Units are Dwarven, gaining defensive bonuses and increased movement on Hill terrain. Starts with a source of [ICON_RESOURCE_MANA_EARTH]Earth and [ICON_RESOURCE_MANA_LAW]Law Mana. Also starts with a source of [ICON_RESOURCE_GOLD]Gold. Accumulate -10% less war weariness than usual.', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_KURIOTATES_COOL_DESCRIPTION', 'Cities can work up to 4 tiles away. But has a limited number of cities based on map size. +1 [ICON_Housing] Housing in all cities. Starts with a source of [ICON_RESOURCE_MANA_SPIRIT]Spirit, [ICON_RESOURCE_MANA_SUN]Sun and [ICON_RESOURCE_MANA_WATER]Water Mana. Accumulate 20% less war weariness than usual.', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_LANUN_COOL_DESCRIPTION', '+1 [ICON_Food] on Coast tiles. Can see a unique Luxury sea resource, Pearls. Starts with a source of [ICON_RESOURCE_MANA_AIR]Air, [ICON_RESOURCE_MANA_NATURE]Nature and [ICON_RESOURCE_MANA_WATER]Water Mana.', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_LJOSALFAR_COOL_DESCRIPTION', 'Elven units can build all improvements on Forested tiles. But start with one less Build Charge. Units are Elven, traversing faster through Forest, Jungle and Ancient Forest, and gaining combat bonuses. Starts with a source of [ICON_RESOURCE_MANA_AIR]Air, [ICON_RESOURCE_MANA_LIFE]Life and [ICON_RESOURCE_MANA_NATURE]Nature Mana. Accumulate 10% less war weariness than usual.', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_LUCHUIRP_COOL_DESCRIPTION', 'Many units are replaced with Golems, which cannot upgrade or gain experience but are immune to many sources of damage and spells. Units are Dwarven, gaining defensive bonuses and increased movement on Hill terrain. Starts with a source of [ICON_RESOURCE_MANA_EARTH]Earth, [ICON_RESOURCE_MANA_ENCHANTMENT]Enchantment and [ICON_RESOURCE_MANA_LIFE]Life Mana. Accumulate 10% less war weariness than usual. Magic class units can repair Golems.', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_MALAKIM_COOL_DESCRIPTION', '+2 [ICON_Gold] Gold on Desert tiles. Units are Nomads, traversing faster through Desert, and gaining combat bonuses. Starts with a source of [ICON_RESOURCE_MANA_MIND]Mind, [ICON_RESOURCE_MANA_LIFE]Life and [ICON_RESOURCE_MANA_SUN]Sun Mana. Accumulate 10% less war weariness than usual.', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_MERCURIANS_COOL_DESCRIPTION', '+40% Bonus [ICON_Production]Production to Military Units. Mercurians are banned from producing many basic units, but the souls of any players Good and Neutral units can be reborn as Angels at the Mercurian gate, and upgraded into powerful angelic units. Starts with a source of [ICON_RESOURCE_MANA_EARTH]Earth and [ICON_RESOURCE_MANA_LIFE]Life Mana. They also start with a source of [ICON_RESOURCE_IRON]Iron. Accumulate -50% less war weariness than usual.', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_SHEAIM_COOL_DESCRIPTION', 'Sheaim Arcane and Disciple units start with the Summoner ability, allowing their summoned units to survive an additional turn. Starts with a source of [ICON_RESOURCE_MANA_CHAOS]Chaos, Death and [ICON_RESOURCE_MANA_FIRE]Fire Mana. Accumulate -10% less war weariness than usual.', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_SIDAR_COOL_DESCRIPTION', 'Level 6+ Sidar units can Wane, providing the yields of any Great Person to a city. Starts with a source of [ICON_RESOURCE_MANA_SPIRIT]Spirit, [ICON_RESOURCE_MANA_ENCHANTMENT]Enchantment and [ICON_RESOURCE_MANA_SHADOW]Shadow Mana.', 'en_US'),
('LOC_SLTH_TRAIT_CIVILIZATION_SVARTALFAR_COOL_DESCRIPTION', 'Recon Promoclass units have +5 [ICON_Strength]Strength on attack, and can kidnap settled [ICON_GreatPerson]Great People. Units are Elven, traversing faster through Forest, Jungle and Ancient Forest, and gaining combat bonuses. Starts with a source of [ICON_RESOURCE_MANA_MIND]Mind, [ICON_RESOURCE_MANA_NATURE]Nature and [ICON_RESOURCE_MANA_SHADOW]Shadow Mana. Accumulate -10% less war weariness than usual.', 'en_US');