INSERT OR REPLACE INTO LocalizedText(Tag, Text, Language) VALUES
('LOC_DEATH_ONE_NAME', 'DE', 'en_US'),
('LOC_FIRE_ONE_NAME', 'FI', 'en_US'),
('LOC_AIR_ONE_NAME', 'AI', 'en_US'),
('LOC_BODY_ONE_NAME', 'BO', 'en_US'),
('LOC_CHAOS_ONE_NAME', 'CH', 'en_US'),
('LOC_EARTH_ONE_NAME', 'EA', 'en_US'),
('LOC_ENCHANTMENT_ONE_NAME', 'EN', 'en_US'),
('LOC_ENTROPY_ONE_NAME', 'EN', 'en_US'),
('LOC_ICE_ONE_NAME', 'IC', 'en_US'),
('LOC_LAW_ONE_NAME', 'LA', 'en_US'),
('LOC_LIFE_ONE_NAME', 'LI', 'en_US'),
('LOC_METAMAGIC_ONE_NAME', 'ME', 'en_US'),
('LOC_MIND_ONE_NAME', 'MI', 'en_US'),
('LOC_NATURE_ONE_NAME', 'NA', 'en_US'),
('LOC_SPIRIT_ONE_NAME', 'SP', 'en_US'),
('LOC_WATER_ONE_NAME', 'WA', 'en_US'),
('LOC_SUN_ONE_NAME', 'SU', 'en_US'),
('LOC_SHADOW_ONE_NAME', 'SH', 'en_US'),
('LOC_DEATH_TWO_NAME', 'DE2', 'en_US'),
('LOC_FIRE_TWO_NAME', 'FI2', 'en_US'),
('LOC_AIR_TWO_NAME', 'AI2', 'en_US'),
('LOC_BODY_TWO_NAME', 'BO2', 'en_US'),
('LOC_CHAOS_TWO_NAME', 'CH2', 'en_US'),
('LOC_EARTH_TWO_NAME', 'EA2', 'en_US'),
('LOC_ENCHANTMENT_TWO_NAME', 'EN2', 'en_US'),
('LOC_ENTROPY_TWO_NAME', 'EN2', 'en_US'),
('LOC_ICE_TWO_NAME', 'IC2', 'en_US'),
('LOC_LAW_TWO_NAME', 'LA2', 'en_US'),
('LOC_LIFE_TWO_NAME', 'LI2', 'en_US'),
('LOC_METAMAGIC_TWO_NAME', 'ME2', 'en_US'),
('LOC_MIND_TWO_NAME', 'MI2', 'en_US'),
('LOC_NATURE_TWO_NAME', 'NA2', 'en_US'),
('LOC_SPIRIT_TWO_NAME', 'SP2', 'en_US'),
('LOC_WATER_TWO_NAME', 'WA2', 'en_US'),
('LOC_SUN_TWO_NAME', 'SU2', 'en_US'),
('LOC_SHADOW_TWO_NAME', 'SH2', 'en_US'),
('LOC_DEATH_THREE_NAME', 'DE3', 'en_US'),
('LOC_FIRE_THREE_NAME', 'FI3', 'en_US'),
('LOC_AIR_THREE_NAME', 'AI3', 'en_US'),
('LOC_BODY_THREE_NAME', 'BO3', 'en_US'),
('LOC_CHAOS_THREE_NAME', 'CH3', 'en_US'),
('LOC_EARTH_THREE_NAME', 'EA3', 'en_US'),
('LOC_ENCHANTMENT_THREE_NAME', 'EN3', 'en_US'),
('LOC_ENTROPY_THREE_NAME', 'EN3', 'en_US'),
('LOC_ICE_THREE_NAME', 'IC3', 'en_US'),
('LOC_LAW_THREE_NAME', 'LA3', 'en_US'),
('LOC_LIFE_THREE_NAME', 'LI3', 'en_US'),
('LOC_METAMAGIC_THREE_NAME', 'ME3', 'en_US'),
('LOC_MIND_THREE_NAME', 'MI3', 'en_US'),
('LOC_NATURE_THREE_NAME', 'NA3', 'en_US'),
('LOC_SPIRIT_THREE_NAME', 'SP3', 'en_US'),
('LOC_WATER_THREE_NAME', 'WA3', 'en_US'),
('LOC_SUN_THREE_NAME', 'SU3', 'en_US'),
('LOC_SHADOW_THREE_NAME', 'SH3', 'en_US'),
('LOC_DEATH_ONE_DESCRIPTION', 'Skeleton', 'en_US'),
('LOC_FIRE_ONE_DESCRIPTION', 'Blaze', 'en_US'),
('LOC_AIR_ONE_DESCRIPTION', 'Fair Winds', 'en_US'),
('LOC_BODY_ONE_DESCRIPTION', 'Haste', 'en_US'),
('LOC_CHAOS_ONE_DESCRIPTION', 'Dance of Blades', 'en_US'),
('LOC_EARTH_ONE_DESCRIPTION', 'Walls of Stone', 'en_US'),
('LOC_ENCHANTMENT_ONE_DESCRIPTION', 'Enchanted Blade', 'en_US'),
('LOC_ENTROPY_ONE_DESCRIPTION', 'Rust', 'en_US'),
('LOC_ICE_ONE_DESCRIPTION', 'Slow', 'en_US'),
('LOC_LAW_ONE_DESCRIPTION', 'Loyalty', 'en_US'),
('LOC_LIFE_ONE_DESCRIPTION', 'Sanctify', 'en_US'),
('LOC_METAMAGIC_ONE_DESCRIPTION', 'Eye', 'en_US'),
('LOC_MIND_ONE_DESCRIPTION', 'Inspiration', 'en_US'),
('LOC_NATURE_ONE_DESCRIPTION', 'Treetop Defense', 'en_US'),
('LOC_SPIRIT_ONE_DESCRIPTION', 'Courage', 'en_US'),
('LOC_WATER_ONE_DESCRIPTION', 'Spring', 'en_US'),
('LOC_SUN_ONE_DESCRIPTION', 'Scorch', 'en_US'),
('LOC_SHADOW_ONE_DESCRIPTION', 'Blur', 'en_US'),
('LOC_DEATH_TWO_DESCRIPTION', 'Spectre', 'en_US'),
('LOC_FIRE_TWO_DESCRIPTION', 'Fireball', 'en_US'),
('LOC_AIR_TWO_DESCRIPTION', 'Maelstrom', 'en_US'),
('LOC_BODY_TWO_DESCRIPTION', 'Regeneration', 'en_US'),
('LOC_CHAOS_TWO_DESCRIPTION', 'Mutate', 'en_US'),
('LOC_EARTH_TWO_DESCRIPTION', 'Stoneskin', 'en_US'),
('LOC_ENCHANTMENT_TWO_DESCRIPTION', 'Flaming Arrows', 'en_US'),
('LOC_ENTROPY_TWO_DESCRIPTION', 'Pit Beast', 'en_US'),
('LOC_ICE_TWO_DESCRIPTION', 'Ice Elemental', 'en_US'),
('LOC_LAW_TWO_DESCRIPTION', 'Einerhjar', 'en_US'),
('LOC_LIFE_TWO_DESCRIPTION', 'Destroy Undead', 'en_US'),
('LOC_METAMAGIC_TWO_DESCRIPTION', 'Dispel Magic', 'en_US'),
('LOC_MIND_TWO_DESCRIPTION', 'Charm', 'en_US'),
('LOC_NATURE_TWO_DESCRIPTION', 'Poison Blade', 'en_US'),
('LOC_SPIRIT_TWO_DESCRIPTION', 'Hope', 'en_US'),
('LOC_WATER_TWO_DESCRIPTION', 'Water-Walk', 'en_US'),
('LOC_SUN_TWO_DESCRIPTION', 'Blinding Light', 'en_US'),
('LOC_SHADOW_TWO_DESCRIPTION', 'Shadow Walk', 'en_US'),
('LOC_DEATH_THREE_DESCRIPTION', 'Wraith', 'en_US'),
('LOC_FIRE_THREE_DESCRIPTION', 'Fire Elemental', 'en_US'),
('LOC_AIR_THREE_DESCRIPTION', 'Air Elemental', 'en_US'),
('LOC_BODY_THREE_DESCRIPTION', 'Flesh Golem', 'en_US'),
('LOC_CHAOS_THREE_DESCRIPTION', 'Wonder', 'en_US'),
('LOC_EARTH_THREE_DESCRIPTION', 'Earth Elemental', 'en_US'),
('LOC_ENCHANTMENT_THREE_DESCRIPTION', 'Enchant Spellstaff', 'en_US'),
('LOC_ENTROPY_THREE_DESCRIPTION', 'Wither', 'en_US'),
('LOC_ICE_THREE_DESCRIPTION', 'Snowfall', 'en_US'),
('LOC_LAW_THREE_DESCRIPTION', 'Valor', 'en_US'),
('LOC_LIFE_THREE_DESCRIPTION', 'Resurrection', 'en_US'),
('LOC_METAMAGIC_THREE_DESCRIPTION', 'Djinn', 'en_US'),
('LOC_MIND_THREE_DESCRIPTION', 'Domination', 'en_US'),
('LOC_NATURE_THREE_DESCRIPTION', 'Vitalize', 'en_US'),
('LOC_SPIRIT_THREE_DESCRIPTION', 'Mistform', 'en_US'),
('LOC_WATER_THREE_DESCRIPTION', 'Water Elemental', 'en_US'),
('LOC_SUN_THREE_DESCRIPTION', 'Aurealis', 'en_US'),
('LOC_SHADOW_THREE_DESCRIPTION', 'Mistform', 'en_US');