INSERT INTO UnitUpgrades(Unit, UpgradeUnit) VALUES
('SLTH_UNIT_ADEPT',                         'SLTH_UNIT_MAGE'),            -- promotion only, but kept for the AI
('UNIT_GREAT_WRITER',                       'UNIT_WARRIOR'),
('SLTH_UNIT_ANGEL',                         'SLTH_UNIT_VALKYRIE'),
('SLTH_UNIT_ARCHER',                        'SLTH_UNIT_LONGBOWMAN'),
('SLTH_UNIT_ASSASSIN',                      'SLTH_UNIT_SHADOW'),
('SLTH_UNIT_SWORDSMAN',                     'SLTH_UNIT_CHAMPION'),
('SLTH_UNIT_CARAVEL',                       'SLTH_UNIT_GALLEON'),
('SLTH_UNIT_CATAPULT',                      'SLTH_UNIT_CANNON'),
('SLTH_UNIT_CHARIOT',                       'SLTH_UNIT_KNIGHT'),
('SLTH_UNIT_CRUSADER',                      'SLTH_UNIT_PALADIN'),
('SLTH_UNIT_LIGHTBRINGER',                  'SLTH_UNIT_DISCIPLE_EMPYREAN'),
('SLTH_UNIT_DISCIPLE_EMPYREAN',             'SLTH_UNIT_PRIEST_OF_THE_EMPYREAN'),
('SLTH_UNIT_DISCIPLE_FELLOWSHIP_OF_LEAVES', 'SLTH_UNIT_PRIEST_OF_LEAVES'),
('SLTH_UNIT_DISCIPLE_OCTOPUS_OVERLORDS',    'SLTH_UNIT_PRIEST_OF_THE_OVERLORDS'),
('SLTH_UNIT_DISCIPLE_OF_ACHERON',           'SLTH_UNIT_SON_OF_THE_INFERNO'),
('SLTH_UNIT_DISCIPLE_RUNES_OF_KILMORPH',    'SLTH_UNIT_PRIEST_OF_KILMORPH'),
('SLTH_UNIT_DISCIPLE_THE_ASHEN_VEIL',       'SLTH_UNIT_PRIEST_OF_THE_VEIL'),
('SLTH_UNIT_DISCIPLE_THE_ORDER',            'SLTH_UNIT_PRIEST_OF_THE_ORDER'),
('SLTH_UNIT_DROWN',                         'SLTH_UNIT_STYGIAN_GUARD'),
('SLTH_UNIT_DWARVEN_SOLDIER_RUNES',         'SLTH_UNIT_PARAMANDER'),
('SLTH_UNIT_ELEPHANT',                      'SLTH_UNIT_WAR_ELEPHANT'),
('SLTH_UNIT_FAWN',                          'SLTH_UNIT_SATYR'),
('SLTH_UNIT_FREAK',                         'SLTH_UNIT_SWORDSMAN'),
('SLTH_UNIT_FRIGATE',                       'SLTH_UNIT_MAN_O_WAR'),
('SLTH_UNIT_GALLEY',                        'SLTH_UNIT_CARAVEL'),
('SLTH_UNIT_TRIREME',                       'SLTH_UNIT_PRIVATEER'),
('SLTH_UNIT_GAELAN',                        'SLTH_UNIT_ARCHMAGE'),
('SLTH_UNIT_HORSE_ARCHER',                  'SLTH_UNIT_KNIGHT'),
('SLTH_UNIT_HORSEMAN',                      'SLTH_UNIT_HORSE_ARCHER'),
('SLTH_UNIT_WOLF_RIDER',                    'SLTH_UNIT_CHARIOT'),
('SLTH_UNIT_HUNTER',                        'SLTH_UNIT_RANGER'),
('SLTH_UNIT_LONGBOWMAN',                    'SLTH_UNIT_CROSSBOWMAN'),
('SLTH_UNIT_LUNATIC',                       'SLTH_UNIT_BERSERKER'),
('SLTH_UNIT_MAGE',                          'SLTH_UNIT_ARCHMAGE'),              -- needs promotions
('SLTH_UNIT_MANES',                         'UNIT_WARRIOR'),
('SLTH_UNIT_MOBIUS_WITCH',                  'SLTH_UNIT_ARCHMAGE'),
('SLTH_UNIT_MONK',                          'SLTH_UNIT_IMMORTAL'),
('SLTH_UNIT_NIGHTWATCH',                    'SLTH_UNIT_ASSASSIN'),
('SLTH_UNIT_PRIEST_OF_KILMORPH',            'SLTH_UNIT_HIGH_PRIEST_OF_KILMORPH'),
('SLTH_UNIT_PRIEST_OF_LEAVES',              'SLTH_UNIT_HIGH_PRIEST_OF_LEAVES'),
('SLTH_UNIT_PRIEST_OF_THE_EMPYREAN',        'SLTH_UNIT_HIGH_PRIEST_OF_THE_EMPYREAN'),
('SLTH_UNIT_PRIEST_OF_THE_ORDER',           'SLTH_UNIT_HIGH_PRIEST_OF_THE_ORDER'),
('SLTH_UNIT_PRIEST_OF_THE_OVERLORDS',       'SLTH_UNIT_HIGH_PRIEST_OF_THE_OVERLORDS'),
('SLTH_UNIT_PRIEST_OF_THE_VEIL',            'SLTH_UNIT_HIGH_PRIEST_OF_THE_VEIL'),
('SLTH_UNIT_PRIEST_OF_WINTER',              'SLTH_UNIT_HIGH_PRIEST_OF_WINTER'),
('SLTH_UNIT_RADIANT_GUARD',                 'SLTH_UNIT_CHAMPION'),
('SLTH_UNIT_RANGER',                        'SLTH_UNIT_BEASTMASTER'),
('SLTH_UNIT_RATHA',                         'SLTH_UNIT_KNIGHT'),
('SLTH_UNIT_ROYAL_GUARD',                   'SLTH_UNIT_KNIGHT'),
('SLTH_UNIT_GOBLIN',                        'SLTH_UNIT_HORSEMAN'),
('SLTH_UNIT_SCOUT',                         'SLTH_UNIT_HUNTER'),
('SLTH_UNIT_SLAVE',                         'SLTH_UNIT_LUNATIC'),
('UNIT_WARRIOR',                            'SLTH_UNIT_SWORDSMAN'),
('SLTH_UNIT_CHAMPION',                      'SLTH_UNIT_PHALANX'),
('SLTH_UNIT_TREBUCHET',                     'SLTH_UNIT_CANNON'),
('SLTH_UNIT_IMP',                           'SLTH_UNIT_MAGE'),
('SLTH_UNIT_SHAMAN',                        'SLTH_UNIT_MAGE'),
('SLTH_UNIT_DWARVEN_SLINGER',               'SLTH_UNIT_CROSSBOWMAN'),
('SLTH_UNIT_JAVELIN_THROWER',               'SLTH_UNIT_LONGBOWMAN'),
('SLTH_UNIT_MOROI',                         'SLTH_UNIT_CHAMPION'),
('SLTH_UNIT_SONS_OF_ASENA',                 'SLTH_UNIT_CHAMPION'),
('SLTH_UNIT_BATTLEMASTER',                  'SLTH_UNIT_BERSERKER'),
('SLTH_UNIT_BOARDING_PARTY',                'SLTH_UNIT_BERSERKER'),
('SLTH_UNIT_DRAGON_SLAYER',                 'SLTH_UNIT_BERSERKER'),
('SLTH_UNIT_MIMIC',                         'SLTH_UNIT_BERSERKER'),
('SLTH_UNIT_OGRE',                          'SLTH_UNIT_BERSERKER'),
('SLTH_UNIT_VAMPIRE',                       'SLTH_UNIT_BRUJAH'),
('SLTH_UNIT_CENTAUR_CHARGER',               'SLTH_UNIT_KNIGHT'),
('SLTH_UNIT_CAMEL_ARCHER',                  'SLTH_UNIT_KNIGHT'),
('SLTH_UNIT_CENTAUR_ARCHER',                'SLTH_UNIT_KNIGHT'),
('SLTH_UNIT_FYRDWELL',                      'SLTH_UNIT_KNIGHT'),
('SLTH_UNIT_NYXKIN',                        'SLTH_UNIT_KNIGHT'),
('SLTH_UNIT_BOAR_RIDER',                    'SLTH_UNIT_CHARIOT'),
('SLTH_UNIT_CENTAUR',                       'SLTH_UNIT_HORSE_ARCHER'),
('SLTH_UNIT_DIVIDED_SOUL',                  'SLTH_UNIT_RANGER'),
('SLTH_UNIT_HELLHOUND',                     'SLTH_UNIT_RANGER'),
('SLTH_UNIT_LIZARDMAN',                     'SLTH_UNIT_RANGER'),
('SLTH_UNIT_FIREBOW',                       'SLTH_UNIT_CROSSBOWMAN'),
('SLTH_UNIT_ILLUSIONIST',                   'SLTH_UNIT_ARCHMAGE'),
('SLTH_UNIT_WIZARD',                        'SLTH_UNIT_ARCHMAGE'),
('SLTH_UNIT_HARLEQUIN',                     'SLTH_UNIT_BEASTMASTER'),
('SLTH_UNIT_BEASTMAN',                      'SLTH_UNIT_SWORDSMAN');

CREATE TABLE IF NOT EXISTS UnitUpgradesAlt(
    Unit text primary key,
    UpgradeUnit text);


INSERT INTO UnitUpgradesAlt(Unit, UpgradeUnit) VALUES
('UNIT_GREAT_WRITER',                       'SLTH_UNIT_ADEPT'),
('SLTH_UNIT_ANGEL',                         'SLTH_UNIT_SERAPH'),
('SLTH_UNIT_ARCHER',                        'SLTH_UNIT_CROSSBOWMAN'),               -- SLTH_UNIT_FLURRY
('SLTH_UNIT_ASSASSIN',                      'SLTH_UNIT_MARKSMAN'),
('SLTH_UNIT_DEVOUT',                        'SLTH_UNIT_PRIEST_OF_KILMORPH'),
('SLTH_UNIT_SWORDSMAN',                     'SLTH_UNIT_CHARIOT'),
('SLTH_UNIT_CHAMPION',                      'SLTH_UNIT_BERSERKER'),                 -- balor
('SLTH_UNIT_DISCIPLE_FELLOWSHIP_OF_LEAVES', 'SLTH_UNIT_RANGER'),                    -- SLTH_UNIT_HARLEQUIN
('SLTH_UNIT_DISCIPLE_OCTOPUS_OVERLORDS',    'SLTH_UNIT_STYGIAN_GUARD'),
('SLTH_UNIT_DISCIPLE_RUNES_OF_KILMORPH',    'SLTH_UNIT_PARAMANDER'),
('SLTH_UNIT_DISCIPLE_THE_ASHEN_VEIL',       'SLTH_UNIT_MAGE'),                      -- wizard, illusionist
('SLTH_UNIT_DISCIPLE_THE_ORDER',            'SLTH_UNIT_CRUSADER'),
('SLTH_UNIT_DISEASED_CORPSE',               'SLTH_UNIT_EIDOLON'),
('SLTH_UNIT_FREAK',                         'SLTH_UNIT_HUNTER'),
('SLTH_UNIT_FRIGATE',                       'SLTH_UNIT_QUEEN_OF_THE_LINE'),
('SLTH_UNIT_GALLEY',                        'SLTH_UNIT_PRIVATEER'),
('SLTH_UNIT_GRIGORI_MEDIC',                 'SLTH_UNIT_DRUID'),
('SLTH_UNIT_HORSEMAN',                      'SLTH_UNIT_CHARIOT'),
('SLTH_UNIT_HUNTER',                        'SLTH_UNIT_ASSASSIN'),                      -- SLTH_UNIT_CHANTER, SLTH_UNIT_TASKMASTER
('SLTH_UNIT_LIGHTBRINGER',                  'SLTH_UNIT_DISCIPLE_OCTOPUS_OVERLORDS'),
('SLTH_UNIT_LONGBOWMAN',                    'SLTH_UNIT_MARKSMAN'),
('SLTH_UNIT_MANES',                         'SLTH_UNIT_SCOUT'),
('SLTH_UNIT_MONK',                          'SLTH_UNIT_PALADIN'),
('SLTH_UNIT_NIGHTWATCH',                    'SLTH_UNIT_SHADOWRIDER'),
('SLTH_UNIT_PARAMANDER',                    'SLTH_UNIT_PALADIN'),
('SLTH_UNIT_PRIEST_OF_KILMORPH',            'SLTH_UNIT_PALADIN'),
('SLTH_UNIT_PRIEST_OF_LEAVES',              'SLTH_UNIT_PALADIN'),
('SLTH_UNIT_PRIEST_OF_THE_EMPYREAN',        'SLTH_UNIT_PALADIN'),
('SLTH_UNIT_PRIEST_OF_THE_ORDER',           'SLTH_UNIT_PALADIN'),
('SLTH_UNIT_PRIEST_OF_THE_OVERLORDS',       'SLTH_UNIT_PALADIN'),
('SLTH_UNIT_PRIEST_OF_THE_VEIL',            'SLTH_UNIT_PALADIN'),
('SLTH_UNIT_RADIANT_GUARD',                 'SLTH_UNIT_RATHA'),
('SLTH_UNIT_RANGER',                        'SLTH_UNIT_DRUID'),                     -- dwarven druid, SLTH_UNIT_LUONNOTAR
('SLTH_UNIT_SCOUT',                         'SLTH_UNIT_HORSEMAN'),                  -- boar rider
('SLTH_UNIT_STYGIAN_GUARD',                 'SLTH_UNIT_EIDOLON'),
('SLTH_UNIT_TRIREME',                       'SLTH_UNIT_FRIGATE'),
('UNIT_WARRIOR',                            'SLTH_UNIT_ARCHER'),                    -- wb slinger/javelin
('SLTH_UNIT_JAVELIN_THROWER',               'SLTH_UNIT_CROSSBOWMAN'),
('SLTH_UNIT_CHANTER',                       'SLTH_UNIT_MARKSMAN'),
('SLTH_UNIT_GHOST',                         'SLTH_UNIT_MARKSMAN'),
('SLTH_UNIT_TASKMASTER',                    'SLTH_UNIT_MARKSMAN'),
('SLTH_UNIT_MOROI',                         'SLTH_UNIT_CHARIOT'),
('SLTH_UNIT_SONS_OF_ASENA',                 'SLTH_UNIT_CHARIOT'),
('SLTH_UNIT_BATTLEMASTER',                  'SLTH_UNIT_IMMORTAL'),
('SLTH_UNIT_BOARDING_PARTY',                'SLTH_UNIT_IMMORTAL'),
('SLTH_UNIT_DRAGON_SLAYER',                 'SLTH_UNIT_IMMORTAL'),
('SLTH_UNIT_MIMIC',                         'SLTH_UNIT_IMMORTAL'),
('SLTH_UNIT_OGRE',                          'SLTH_UNIT_OGRE_WARCHIEF'),
('SLTH_UNIT_VAMPIRE',                       'SLTH_UNIT_VAMPIRE_LORD'),
('SLTH_UNIT_CENTAUR',                       'SLTH_UNIT_CHARIOT'),
('SLTH_UNIT_DIVIDED_SOUL',                  'SLTH_UNIT_ASSASSIN'),
('SLTH_UNIT_HELLHOUND',                     'SLTH_UNIT_ASSASSIN'),
('SLTH_UNIT_LIZARDMAN',                     'SLTH_UNIT_ASSASSIN'),
('SLTH_UNIT_FIREBOW',                       'SLTH_UNIT_MARKSMAN'),
('SLTH_UNIT_HARLEQUIN',                     'SLTH_UNIT_DRUID'),
('SLTH_UNIT_ADEPT',                         'SLTH_UNIT_MAGE'),            -- promotion only, but kept for the AI
('SLTH_UNIT_IMP',                           'SLTH_UNIT_MAGE'),
('SLTH_UNIT_SHAMAN',                        'SLTH_UNIT_MAGE');

CREATE TABLE IF NOT EXISTS UnitUpgradesAltTwo(
    Unit text primary key,
    UpgradeUnit text);

INSERT INTO UnitUpgradesAltTwo(Unit, UpgradeUnit) VALUES
('UNIT_GREAT_WRITER',                 'SLTH_UNIT_SCOUT'),
('SLTH_UNIT_ANGEL',                   'SLTH_UNIT_HERALD'),
('SLTH_UNIT_ARCHER',                  'SLTH_UNIT_HORSE_ARCHER'),            -- SLTH_UNIT_FYRDWELL, SLTH_UNIT_NYXKIN, SLTH_UNIT_CENTAUR_ARCHER, SLTH_UNIT_CAMEL_ARCHER
('SLTH_UNIT_DEVOUT',                  'SLTH_UNIT_PRIEST_OF_THE_ORDER'),
('SLTH_UNIT_FREAK',                   'SLTH_UNIT_ARCHER'),
('SLTH_UNIT_GALLEY',                  'SLTH_UNIT_FRIGATE'),
('SLTH_UNIT_LIGHTBRINGER',            'SLTH_UNIT_DISCIPLE_RUNES_OF_KILMORPH'),
('SLTH_UNIT_LONGBOWMAN',              'SLTH_UNIT_ARQUEBUS'),
('SLTH_UNIT_MANES',                   'SLTH_UNIT_ADEPT'),
('SLTH_UNIT_PRIEST_OF_KILMORPH',      'SLTH_UNIT_DRUID'),
('SLTH_UNIT_PRIEST_OF_LEAVES',        'SLTH_UNIT_DRUID'),
('SLTH_UNIT_PRIEST_OF_THE_EMPYREAN',  'SLTH_UNIT_DRUID'),
('SLTH_UNIT_PRIEST_OF_THE_ORDER',     'SLTH_UNIT_DRUID'),
('SLTH_UNIT_PRIEST_OF_THE_OVERLORDS', 'SLTH_UNIT_DRUID'),
('SLTH_UNIT_PRIEST_OF_THE_VEIL',      'SLTH_UNIT_DRUID'),
('SLTH_UNIT_JAVELIN_THROWER',         'SLTH_UNIT_HORSE_ARCHER'),
('SLTH_UNIT_BATTLEMASTER',            'SLTH_UNIT_IMMORTAL'),
('SLTH_UNIT_BOARDING_PARTY',          'SLTH_UNIT_IMMORTAL'),
('SLTH_UNIT_DRAGON_SLAYER',           'SLTH_UNIT_IMMORTAL'),
('SLTH_UNIT_MIMIC',                   'SLTH_UNIT_IMMORTAL'),
('SLTH_UNIT_OGRE',                    'SLTH_UNIT_STONESKIN_OGRE'),
('SLTH_UNIT_VAMPIRE',                 'SLTH_UNIT_PALADIN'),
('SLTH_UNIT_FIREBOW',                 'SLTH_UNIT_ARQUEBUS'),
('SLTH_UNIT_CHAMPION',                'SLTH_UNIT_IMMORTAL');

CREATE TABLE IF NOT EXISTS UnitUpgradesAltThree(
    Unit text primary key,
    UpgradeUnit text);

INSERT INTO UnitUpgradesAltThree(Unit, UpgradeUnit) VALUES
('SLTH_UNIT_ANGEL',                   'SLTH_UNIT_OPHANIM'),
('SLTH_UNIT_DEVOUT',                  'SLTH_UNIT_PRIEST_OF_LEAVES'),
('SLTH_UNIT_CHAMPION',                'SLTH_UNIT_PALADIN'),
('SLTH_UNIT_LIGHTBRINGER',            'SLTH_UNIT_DISCIPLE_THE_ASHEN_VEIL'),
('SLTH_UNIT_PRIEST_OF_KILMORPH',      'SLTH_UNIT_EIDOLON'),
('SLTH_UNIT_PRIEST_OF_LEAVES',        'SLTH_UNIT_EIDOLON'),
('SLTH_UNIT_PRIEST_OF_THE_EMPYREAN',  'SLTH_UNIT_EIDOLON'),
('SLTH_UNIT_PRIEST_OF_THE_ORDER',     'SLTH_UNIT_EIDOLON'),
('SLTH_UNIT_PRIEST_OF_THE_OVERLORDS', 'SLTH_UNIT_EIDOLON'),
('SLTH_UNIT_PRIEST_OF_THE_VEIL',      'SLTH_UNIT_EIDOLON'),
('SLTH_UNIT_BATTLEMASTER',            'SLTH_UNIT_PALADIN'),
('SLTH_UNIT_BOARDING_PARTY',          'SLTH_UNIT_PALADIN'),
('SLTH_UNIT_DRAGON_SLAYER',           'SLTH_UNIT_PALADIN'),
('SLTH_UNIT_MIMIC',                   'SLTH_UNIT_PALADIN'),
('SLTH_UNIT_VAMPIRE',                 'SLTH_UNIT_EIDOLON');

CREATE TABLE IF NOT EXISTS UnitUpgradesAltFour(
    Unit text primary key,
    UpgradeUnit text);

INSERT INTO UnitUpgradesAltFour(Unit, UpgradeUnit) VALUES
('SLTH_UNIT_ANGEL',          'SLTH_UNIT_REPENTANT_ANGEL'),
('SLTH_UNIT_DEVOUT',         'SLTH_UNIT_PRIEST_OF_THE_EMPYREAN'),
('SLTH_UNIT_CHAMPION',       'SLTH_UNIT_EIDOLON'),
('SLTH_UNIT_LIGHTBRINGER',   'SLTH_UNIT_DISCIPLE_THE_ORDER'),
('SLTH_UNIT_BATTLEMASTER',   'SLTH_UNIT_EIDOLON'),
('SLTH_UNIT_BOARDING_PARTY', 'SLTH_UNIT_EIDOLON'),
('SLTH_UNIT_DRAGON_SLAYER',  'SLTH_UNIT_EIDOLON'),
('SLTH_UNIT_MIMIC',          'SLTH_UNIT_EIDOLON'),
('SLTH_UNIT_VAMPIRE',        'SLTH_UNIT_KNIGHT');

CREATE TABLE IF NOT EXISTS UnitUpgradesAltFive(
    Unit text primary key,
    UpgradeUnit text);

INSERT INTO UnitUpgradesAltFive(Unit, UpgradeUnit) VALUES
('SLTH_UNIT_ANGEL',          'SLTH_UNIT_ANGEL_OF_DEATH'),
('SLTH_UNIT_CHAMPION',       'SLTH_UNIT_KNIGHT'),
('SLTH_UNIT_LIGHTBRINGER',   'SLTH_UNIT_DISCIPLE_FELLOWSHIP_OF_LEAVES'),
('SLTH_UNIT_BATTLEMASTER',   'SLTH_UNIT_BISON_RIDER'),
('SLTH_UNIT_BOARDING_PARTY', 'SLTH_UNIT_WAR_TORTOISE'),
('SLTH_UNIT_DRAGON_SLAYER',  'SLTH_UNIT_KNIGHT'),
('SLTH_UNIT_MIMIC',          'SLTH_UNIT_KNIGHT');


-- angel of death gets free vile touch and invis, huh


CREATE TABLE IF NOT EXISTS PromotionGatedUpgrades(
    UnitType text primary key,
    UnitLevel integer default 1);

INSERT INTO PromotionGatedUpgrades(UnitType, UnitLevel) VALUES
('SLTH_UNIT_REPENTANT_ANGEL',               3),
('SLTH_UNIT_ANGEL_OF_DEATH',                4),
('SLTH_UNIT_HERALD',                        4),
('SLTH_UNIT_ILLUSIONIST',                   4),
('SLTH_UNIT_MAGE',                          4),
('SLTH_UNIT_WIZARD',                        4),
('SLTH_UNIT_OPHANIM',                       4),
('SLTH_UNIT_SATYR',                         4),
('SLTH_UNIT_SERAPH',                        4),
('SLTH_UNIT_ARCHMAGE',                      6),
('SLTH_UNIT_EATER_OF_DREAMS',               6),
('SLTH_UNIT_LUONNOTAR',                     6),
('SLTH_UNIT_HIGH_PRIEST_OF_KILMORPH',       6),
('SLTH_UNIT_HIGH_PRIEST_OF_THE_OVERLORDS',  6),
('SLTH_UNIT_HIGH_PRIEST_OF_LEAVES',         6),
('SLTH_UNIT_HIGH_PRIEST_OF_THE_EMPYREAN',   6),
('SLTH_UNIT_HIGH_PRIEST_OF_THE_VEIL',       6),
('SLTH_UNIT_HIGH_PRIEST_OF_THE_ORDER',      6),
('SLTH_UNIT_HIGH_PRIEST_OF_WINTER',         6),
('SLTH_UNIT_IMMORTAL',                      6),
('SLTH_UNIT_OGRE_WARCHIEF',                 6),
('SLTH_UNIT_MARKSMAN',                      6),
('SLTH_UNIT_VALKYRIE',                      6),
('SLTH_UNIT_VAMPIRE_LORD',                  12);

CREATE TABLE IF NOT EXISTS NationalUnits(
    UnitType text primary key,
    Amount integer default 4);

INSERT INTO NationalUnits(UnitType, Amount) VALUES
('SLTH_UNIT_REPENTANT_ANGEL',               3),
('SLTH_UNIT_PHALANX',                       4),
('SLTH_UNIT_NULLSTONE_GOLEM',               4),
('SLTH_UNIT_STONESKIN_OGRE',                4),
('SLTH_UNIT_BERSERKER',                     4),
('SLTH_UNIT_BRUJAH',                        4),
('SLTH_UNIT_CLOCKWORK_GOLEM',               4),
('SLTH_UNIT_BALOR',                         4),
('SLTH_UNIT_BEASTMASTER',                   4),
('SLTH_UNIT_MYCONID',                       4),
('SLTH_UNIT_KNIGHT',                        4),
('SLTH_UNIT_DEATH_KNIGHT',                  4),
('SLTH_UNIT_BISON_RIDER',                   4),
('SLTH_UNIT_CENTAUR_LANCER',                4),
('SLTH_UNIT_HORNGUARD',                     4),
('SLTH_UNIT_WAR_TORTOISE',                  4),
('SLTH_UNIT_ARCHMAGE',                      4),
('SLTH_UNIT_EATER_OF_DREAMS',               4),
('SLTH_UNIT_LICH',                          4),
('SLTH_UNIT_IMMORTAL',                      4),
('SLTH_UNIT_VAMPIRE_LORD',                  4),
('SLTH_UNIT_BONE_GOLEM',                    4),
('SLTH_UNIT_OGRE_WARCHIEF',                 4),
('SLTH_UNIT_OPHANIM',                       4),
('SLTH_UNIT_ANGEL_OF_DEATH',                4),
('SLTH_UNIT_SERAPH',                        4),
('SLTH_UNIT_VALKYRIE',                      4),
('SLTH_UNIT_HERALD',                        4),
('SLTH_UNIT_SHADOW',                        4),
('SLTH_UNIT_DWARVEN_SHADOW',                4),
('SLTH_UNIT_COURTESAN',                     4),
('SLTH_UNIT_SHADOWRIDER',                   4),
('SLTH_BEAST_OF_AGARES',                    4),
('SLTH_UNIT_HIGH_PRIEST_OF_WINTER',         4),
('SLTH_UNIT_HIGH_PRIEST_OF_KILMORPH',       4),
('SLTH_UNIT_HIGH_PRIEST_OF_LEAVES',         4),
('SLTH_UNIT_HIGH_PRIEST_OF_THE_VEIL',       4),
('SLTH_UNIT_HIGH_PRIEST_OF_THE_OVERLORDS',  4),
('SLTH_UNIT_HIGH_PRIEST_OF_THE_EMPYREAN',   4),
('SLTH_UNIT_HIGH_PRIEST_OF_THE_ORDER',      4),
('SLTH_UNIT_MARKSMAN',                      4),
('SLTH_UNIT_EIDOLON',                       4),
('SLTH_UNIT_PALADIN',                       4),
('SLTH_UNIT_DRUID',                         4),
('SLTH_UNIT_DWARVEN_DRUID',                 4),
('SLTH_UNIT_LUONNOTAR',                     4),
('SLTH_UNIT_CROSSBOWMAN',                   4),
('SLTH_UNIT_FLURRY',                        4),
('SLTH_UNIT_ROYAL_GUARD',                   4);


-- also need a table for unit replacements per civ for fast lookups.
CREATE TABLE IF NOT EXISTS CivUnitReplaces(CivilizationType text ,
    CivUniqueUnitType text,
    ReplacesUnitType integer default 4,
primary key (CivilizationType, CivUniqueUnitType));

INSERT INTO CivUnitReplaces(CivilizationType, CivUniqueUnitType, ReplacesUnitType) VALUES
('SLTH_CIVILIZATION_DOVIELLO', 'SLTH_UNIT_SHAMAN', 'SLTH_UNIT_ADEPT'),
('SLTH_CIVILIZATION_CLAN_OF_EMBERS', 'SLTH_UNIT_SHAMAN', 'SLTH_UNIT_ADEPT'),
('SLTH_CIVILIZATION_DOVIELLO','SLTH_UNIT_JAVELIN_THROWER', 'SLTH_UNIT_ARCHER'),
('SLTH_CIVILIZATION_ILLIANS','SLTH_UNIT_JAVELIN_THROWER', 'SLTH_UNIT_ARCHER'),
('SLTH_CIVILIZATION_INFERNAL', 'SLTH_UNIT_BALOR', 'SLTH_UNIT_BERSERKER'),
('SLTH_CIVILIZATION_CLAN_OF_EMBERS', 'SLTH_UNIT_OGRE', 'SLTH_UNIT_CHAMPION'),
('SLTH_CIVILIZATION_CLAN_OF_EMBERS', 'SLTH_UNIT_WOLF_RIDER', 'SLTH_UNIT_HORSEMAN'),
('SLTH_CIVILIZATION_CLAN_OF_EMBERS', 'SLTH_UNIT_OGRE_WARCHIEF', 'SLTH_UNIT_IMMORTAL'),
('SLTH_CIVILIZATION_LUCHUIRP', 'SLTH_UNIT_GARGOYLE', 'SLTH_UNIT_LONGBOWMAN'),
('SLTH_CIVILIZATION_CLAN_OF_EMBERS', 'SLTH_UNIT_STONESKIN_OGRE', 'SLTH_UNIT_PHALANX'),
('SLTH_CIVILIZATION_KURIOTATES', 'SLTH_UNIT_AIRSHIP', 'SLTH_UNIT_QUEEN_OF_THE_LINE'),
('SLTH_CIVILIZATION_CLAN_OF_EMBERS', 'SLTH_UNIT_GOBLIN', 'SLTH_UNIT_SCOUT'),

('SLTH_CIVILIZATION_AMURITES', 'SLTH_UNIT_WIZARD', 'SLTH_UNIT_MAGE'),
('SLTH_CIVILIZATION_AMURITES', 'SLTH_UNIT_FIREBOW', 'SLTH_UNIT_LONGBOWMAN'),
('SLTH_CIVILIZATION_AMURITES', 'SLTH_UNIT_CHANTER', 'SLTH_UNIT_ASSASSIN'),

('SLTH_CIVILIZATION_BALSERAPHS', 'SLTH_UNIT_MIMIC', 'SLTH_UNIT_CHAMPION'),
('SLTH_CIVILIZATION_BALSERAPHS', 'SLTH_UNIT_COURTESAN', 'SLTH_UNIT_SHADOW'),
('SLTH_CIVILIZATION_BALSERAPHS', 'SLTH_UNIT_TASKMASTER', 'SLTH_UNIT_ASSASSIN'),
('SLTH_CIVILIZATION_BALSERAPHS', 'SLTH_UNIT_HARLEQUIN', 'SLTH_UNIT_RANGER'),

('SLTH_CIVILIZATION_CALABIM', 'SLTH_UNIT_MOROI', 'SLTH_UNIT_SWORDSMAN'),
('SLTH_CIVILIZATION_CALABIM', 'SLTH_UNIT_BRUJAH', 'SLTH_UNIT_BERSERKER'),
('SLTH_CIVILIZATION_CALABIM', 'SLTH_UNIT_VAMPIRE_LORD', 'SLTH_UNIT_IMMORTAL'),
('SLTH_CIVILIZATION_CALABIM', 'SLTH_UNIT_VAMPIRE', 'SLTH_UNIT_CHAMPION'),

('SLTH_CIVILIZATION_ELOHIM', 'SLTH_UNIT_DEVOUT', 'SLTH_UNIT_ASSASSIN'),

('SLTH_CIVILIZATION_GRIGORI', 'SLTH_UNIT_DRAGON_SLAYER', 'SLTH_UNIT_CHAMPION'),
('SLTH_CIVILIZATION_GRIGORI', 'SLTH_UNIT_LUONNOTAR', 'SLTH_UNIT_DRUID'),

('SLTH_CIVILIZATION_HIPPUS', 'SLTH_UNIT_MERCENARY_MOUNTED', 'SLTH_UNIT_MERCENARY'),

('SLTH_CIVILIZATION_INFERNAL', 'SLTH_UNIT_IMP', 'SLTH_UNIT_ADEPT'),
('SLTH_CIVILIZATION_INFERNAL', 'SLTH_UNIT_HELLHOUND', 'SLTH_UNIT_HUNTER'),
('SLTH_CIVILIZATION_INFERNAL', 'SLTH_UNIT_DEATH_KNIGHT', 'SLTH_UNIT_KNIGHT'),

('SLTH_CIVILIZATION_KURIOTATES', 'SLTH_UNIT_CENTAUR_CHARGER', 'SLTH_UNIT_CHARIOT'),
('SLTH_CIVILIZATION_KURIOTATES', 'SLTH_UNIT_CENTAUR_ARCHER', 'SLTH_UNIT_HORSE_ARCHER'),
('SLTH_CIVILIZATION_KURIOTATES', 'SLTH_UNIT_CENTAUR', 'SLTH_UNIT_HORSEMAN'),
('SLTH_CIVILIZATION_KURIOTATES', 'SLTH_UNIT_CENTAUR_LANCER', 'SLTH_UNIT_KNIGHT'),

('SLTH_CIVILIZATION_LANUN', 'SLTH_UNIT_BOARDING_PARTY', 'SLTH_UNIT_CHAMPION'),
('SLTH_CIVILIZATION_LANUN', 'SLTH_UNIT_WAR_TORTOISE', 'SLTH_UNIT_KNIGHT'),
('SLTH_CIVILIZATION_LANUN', 'SLTH_UNIT_PIRATE', 'SLTH_UNIT_PRIVATEER'),

('SLTH_CIVILIZATION_MALAKIM', 'SLTH_UNIT_CAMEL_ARCHER', 'SLTH_UNIT_HORSE_ARCHER'),

('SLTH_CIVILIZATION_SHEAIM', 'SLTH_UNIT_PYRE_ZOMBIE', 'SLTH_UNIT_SWORDSMAN'),
('SLTH_CIVILIZATION_SHEAIM', 'SLTH_UNIT_EATER_OF_DREAMS', 'SLTH_UNIT_ARCHMAGE'),

('SLTH_CIVILIZATION_SIDAR', 'SLTH_UNIT_GHOST', 'SLTH_UNIT_ASSASSIN'),
('SLTH_CIVILIZATION_SIDAR', 'SLTH_UNIT_DIVIDED_SOUL', 'SLTH_UNIT_HUNTER'),

('SLTH_CIVILIZATION_KHAZAD', 'SLTH_UNIT_DWARVEN_SLINGER', 'SLTH_UNIT_ARCHER'),
('SLTH_CIVILIZATION_LUCHUIRP', 'SLTH_UNIT_DWARVEN_SLINGER', 'SLTH_UNIT_ARCHER'),
('SLTH_CIVILIZATION_KHAZAD', 'SLTH_UNIT_DWARVEN_DRUID', 'SLTH_UNIT_DRUID'),                               -- should these be luchuirp too
('SLTH_CIVILIZATION_KHAZAD', 'SLTH_UNIT_BOAR_RIDER', 'SLTH_UNIT_HORSEMAN'),
('SLTH_CIVILIZATION_KHAZAD', 'SLTH_UNIT_DWARVEN_SHADOW', 'SLTH_UNIT_SHADOW'),
('SLTH_CIVILIZATION_KHAZAD', 'SLTH_UNIT_HORNGUARD', 'SLTH_UNIT_KNIGHT'),

('SLTH_CIVILIZATION_KHAZAD', 'SLTH_UNIT_MYCONID', 'SLTH_UNIT_BEASTMASTER'),
('SLTH_CIVILIZATION_KHAZAD', 'SLTH_UNIT_DWARVEN_CANNON', 'SLTH_UNIT_CANNON'),
('SLTH_CIVILIZATION_KHAZAD', 'SLTH_UNIT_TREBUCHET', 'SLTH_UNIT_CATAPULT'),

('SLTH_CIVILIZATION_LUCHUIRP', 'SLTH_UNIT_MUD_GOLEM', 'UNIT_BUILDER'),

('SLTH_CIVILIZATION_LJOSALFAR', 'SLTH_UNIT_FYRDWELL', 'SLTH_UNIT_HORSE_ARCHER'),
('SLTH_CIVILIZATION_LJOSALFAR', 'SLTH_UNIT_FLURRY', 'SLTH_UNIT_CROSSBOWMAN'),

('SLTH_CIVILIZATION_SVARTALFAR', 'SLTH_UNIT_NYXKIN', 'SLTH_UNIT_HORSE_ARCHER'),
('SLTH_CIVILIZATION_SVARTALFAR', 'SLTH_UNIT_ILLUSIONIST', 'SLTH_UNIT_MAGE'),

('SLTH_CIVILIZATION_DOVIELLO', 'SLTH_UNIT_BATTLEMASTER', 'SLTH_UNIT_CHAMPION'),
('SLTH_CIVILIZATION_DOVIELLO', 'SLTH_UNIT_BISON_RIDER', 'SLTH_UNIT_KNIGHT'),
('SLTH_CIVILIZATION_DOVIELLO', 'SLTH_UNIT_SONS_OF_ASENA', 'SLTH_UNIT_SWORDSMAN'),
('SLTH_CIVILIZATION_DOVIELLO', 'SLTH_UNIT_BEASTMAN', 'UNIT_WARRIOR');