INSERT INTO Buildings(BuildingType, Name, PrereqTech, PrereqCivic, Cost, PrereqDistrict, Description, OuterDefenseHitPoints, Housing, Entertainment, TraitType, CitizenSlots, AdvisorType) VALUES
('BUILDING_RESEARCH_LAB', 'LOC_BUILDING_RESEARCH_LAB_NAME', 'TECH_SORCERY', NULL, '300', 'DISTRICT_CAMPUS', 'LOC_BUILDING_RESEARCH_LAB_DESCRIPTION', '0', '0', '0', NULL, '1', 'ADVISOR_TECHNOLOGY'),
('SLTH_BUILDING_AQUEDUCT', 'LOC_SLTH_BUILDING_AQUEDUCT_NAME', 'TECH_SANITATION', NULL, '180', 'DISTRICT_CITY_CENTER', 'LOC_NULL_DESCRIPTION', '0', '2', '0', NULL, NULL, 'ADVISOR_GENERIC'),
('SLTH_BUILDING_ARCHERY_RANGE', 'LOC_SLTH_BUILDING_ARCHERY_RANGE_NAME', 'SLTH_TECH_ARCHERY', NULL, '100', 'DISTRICT_CITY_CENTER', 'LOC_SLTH_BUILDING_ARCHERY_RANGE_DESCRIPTION', '80', '0', '0', NULL, NULL, 'ADVISOR_CONQUEST'),
('SLTH_BUILDING_ASYLUM', 'LOC_SLTH_BUILDING_ASYLUM_NAME', NULL, 'CIVIC_MIND_STAPLING', '150', 'DISTRICT_CAMPUS', 'LOC_SLTH_BUILDING_ASYLUM_DESCRIPTION', '0', '0', '-1', NULL, '1', 'ADVISOR_TECHNOLOGY'),
('BUILDING_SYNAGOGUE', 'LOC_BUILDING_SYNAGOGUE_NAME', NULL, 'CIVIC_RELIGIOUS_LAW', '200', 'DISTRICT_CITY_CENTER', 'LOC_BUILDING_BASILICA_DESCRIPTION', '0', '0', '0', NULL, NULL, 'ADVISOR_GENERIC'),
('SLTH_BUILDING_CARNIVAL', 'LOC_SLTH_BUILDING_CARNIVAL_NAME', NULL, 'CIVIC_GAMES_RECREATION', '120', 'DISTRICT_THEATER', 'LOC_SLTH_BUILDING_CARNIVAL_DESCRIPTION', '0', '0', '1', NULL, '1', 'ADVISOR_CULTURE'),
('BUILDING_QUEENS_BIBLIOTHEQUE', 'LOC_BUILDING_QUEENS_BIBLIOTHEQUE_NAME', NULL, 'CIVIC_CODE_OF_LAWS', '120', 'DISTRICT_CITY_CENTER', 'LOC_BUILDING_COURTHOUSE_DESCRIPTION', '0', '0', '0', NULL, NULL, 'ADVISOR_GENERIC'),
('SLTH_BUILDING_DEMONS_ALTAR', 'LOC_SLTH_BUILDING_DEMONS_ALTAR_NAME', NULL, 'CIVIC_INFERNAL_PACT', '150', 'DISTRICT_CITY_CENTER', 'LOC_SLTH_BUILDING_DEMONS_ALTAR_DESCRIPTION', '0', '0', '-1', NULL, NULL, 'ADVISOR_RELIGIOUS'),
('SLTH_BUILDING_DUNGEON', 'LOC_SLTH_BUILDING_DUNGEON_NAME', 'TECH_MASONRY', NULL, '160', 'DISTRICT_CITY_CENTER', 'LOC_SLTH_BUILDING_DUNGEON_DESCRIPTION', '0', '0', '0', NULL, NULL, 'ADVISOR_CONQUEST'),
('SLTH_BUILDING_ELDER_COUNCIL', 'LOC_SLTH_BUILDING_ELDER_COUNCIL_NAME', NULL, 'CIVIC_MYSTICISM', '60', 'DISTRICT_CAMPUS', 'LOC_SLTH_BUILDING_ELDER_COUNCIL_DESCRIPTION', '0', '0', '0', NULL, '1', 'ADVISOR_TECHNOLOGY'),
('BUILDING_WORKSHOP', 'LOC_BUILDING_FORGE_NAME', 'TECH_SMELTING', NULL, '250', 'DISTRICT_INDUSTRIAL_ZONE', 'LOC_BUILDING_FORGE_DESCRIPTION', '0', '-1', '0', NULL, '1', 'ADVISOR_GENERIC'),
('SLTH_BUILDING_GAMBLING_HOUSE', 'LOC_SLTH_BUILDING_GAMBLING_HOUSE_NAME', 'TECH_MATHEMATICS', NULL, '200', 'DISTRICT_CITY_CENTER', 'LOC_SLTH_BUILDING_GAMBLING_HOUSE_DESCRIPTION', '0', '0', '0', NULL, NULL, 'ADVISOR_GENERIC'),
('BUILDING_GRANARY', 'LOC_BUILDING_GRANARY_NAME', 'TECH_AGRICULTURE', NULL, '120', 'DISTRICT_CITY_CENTER', 'LOC_BUILDING_GRANARY_DESCRIPTION', '0', '0', '0', NULL, NULL, 'ADVISOR_GENERIC'),
('BUILDING_GROVE', 'LOC_BUILDING_GROVE_NAME', NULL, 'CIVIC_FERAL_BOND', '300', 'DISTRICT_CITY_CENTER', 'LOC_BUILDING_GROVE_DESCRIPTION', '0', '0', '0', NULL, NULL, 'ADVISOR_CONQUEST'),
('SLTH_BUILDING_HARBOR', 'LOC_SLTH_BUILDING_HARBOR_NAME', 'TECH_FISHING', NULL, '120', 'DISTRICT_CITY_CENTER', 'LOC_SLTH_BUILDING_HARBOR_DESCRIPTION', '0', '0', '0', NULL, NULL, 'ADVISOR_GENERIC'),
('BUILDING_MEETING_HOUSE', 'LOC_BUILDING_MEETING_HOUSE_NAME', 'TECH_AGRICULTURE', NULL, '90', 'DISTRICT_CITY_CENTER', 'LOC_BUILDING_HERBALIST_DESCRIPTION', '0', '1', '0', NULL, NULL, 'ADVISOR_GENERIC'),
('SLTH_BUILDING_HUNTING_LODGE', 'LOC_SLTH_BUILDING_HUNTING_LODGE_NAME', 'TECH_HUNTING', NULL, '100', 'DISTRICT_CITY_CENTER', 'LOC_SLTH_BUILDING_HUNTING_LODGE_DESCRIPTION', '0', '0', '0', NULL, NULL, 'ADVISOR_CONQUEST'),
('SLTH_BUILDING_INFIRMARY', 'LOC_SLTH_BUILDING_INFIRMARY_NAME', 'TECH_MEDICINE', NULL, '300', 'DISTRICT_CITY_CENTER', 'LOC_SLTH_BUILDING_INFIRMARY_DESCRIPTION', '0', '3', '0', NULL, NULL, 'ADVISOR_GENERIC'),
('SLTH_BUILDING_INN', 'LOC_SLTH_BUILDING_INN_NAME', 'TECH_TRADE', NULL, '250', 'DISTRICT_CITY_CENTER', 'LOC_SLTH_BUILDING_INN_DESCRIPTION', '0', '0', '0', NULL, NULL, 'ADVISOR_GENERIC'),
('BUILDING_LIBRARY', 'LOC_BUILDING_LIBRARY_NAME', 'TECH_WRITING', NULL, '120', 'DISTRICT_CAMPUS', 'LOC_BUILDING_LIBRARY_DESCRIPTION', '0', '0', '0', NULL, '1', 'ADVISOR_TECHNOLOGY'),
('BUILDING_LIGHTHOUSE', 'LOC_BUILDING_LIGHTHOUSE_NAME', 'SLTH_TECH_SAILING', NULL, '160', 'DISTRICT_CITY_CENTER', 'LOC_BUILDING_LIGHTHOUSE_DESCRIPTION', '0', '0', '0', NULL, NULL, 'ADVISOR_GENERIC'),
('BUILDING_MAGE_GUILD', 'LOC_BUILDING_MAGE_GUILD_NAME', 'TECH_KNOWLEDGE_OF_THE_ETHER', NULL, '120', 'DISTRICT_CITY_CENTER', 'LOC_BUILDING_MAGE_GUILD_DESCRIPTION', '0', '0', '0', NULL, NULL, 'ADVISOR_CONQUEST'),
('BUILDING_MARKET', 'LOC_BUILDING_MARKET_NAME', NULL, 'CIVIC_GAMES_RECREATION', '60', 'DISTRICT_COMMERCIAL_HUB', 'LOC_BUILDING_MARKET_DESCRIPTION', '0', '0', '0', NULL, '1', 'ADVISOR_GENERIC'),
('BUILDING_BANK', 'LOC_BUILDING_BANK_NAME', NULL, 'CIVIC_CURRENCY', '250', 'DISTRICT_COMMERCIAL_HUB', 'LOC_BUILDING_BANK_DESCRIPTION', '0', '0', '0', NULL, '1', 'ADVISOR_GENERIC'),
('BUILDING_MONUMENT', 'LOC_BUILDING_MONUMENT_NAME', NULL, 'CIVIC_ANCIENT_CHANTS', '60', 'DISTRICT_CITY_CENTER', 'LOC_SLTH_BUILDING_MONUMENT_DESCRIPTION', '0', '0', '0', NULL, NULL, 'ADVISOR_CULTURE'),
('SLTH_BUILDING_OBSIDIAN_GATE', 'LOC_SLTH_BUILDING_OBSIDIAN_GATE_NAME', 'TECH_PASS_THROUGH_THE_ETHER', NULL, '300', 'DISTRICT_CITY_CENTER', 'LOC_SLTH_BUILDING_OBSIDIAN_GATE_DESCRIPTION', '0', '0', '0', NULL, NULL, 'ADVISOR_GENERIC'),
('BUILDING_SHRINE', 'LOC_BUILDING_SHRINE_NAME', NULL, 'CIVIC_MYSTICISM', '100', 'DISTRICT_HOLY_SITE', 'LOC_BUILDING_SHRINE_DESCRIPTION', '0', '0', '0', NULL, '1', 'ADVISOR_CULTURE'),
('BUILDING_WALLS', 'LOC_BUILDING_WALLS_NAME', NULL, NULL, '40', 'DISTRICT_CITY_CENTER', 'LOC_BUILDING_WALLS_DESCRIPTION', '80', '0', '0', NULL, NULL, 'ADVISOR_CONQUEST'),
('SLTH_BUILDING_PUBLIC_BATHS', 'LOC_SLTH_BUILDING_PUBLIC_BATHS_NAME', 'TECH_SANITATION', NULL, '150', 'DISTRICT_CITY_CENTER', 'LOC_SLTH_BUILDING_PUBLIC_BATHS_DESCRIPTION', '0', '-1', '3', NULL, NULL, 'ADVISOR_GENERIC'),
('BUILDING_SHIPYARD', 'LOC_BUILDING_SHIPYARD_NAME', 'TECH_IRON_WORKING', NULL, '200', 'DISTRICT_CITY_CENTER', 'LOC_BUILDING_SHIPYARD_DESCRIPTION', '0', '0', '0', NULL, NULL, 'ADVISOR_CONQUEST'),
('SLTH_BUILDING_SIEGE_WORKSHOP', 'LOC_SLTH_BUILDING_SIEGE_WORKSHOP_NAME', 'TECH_CONSTRUCTION', NULL, '120', 'DISTRICT_CITY_CENTER', 'LOC_SLTH_BUILDING_SIEGE_WORKSHOP_DESCRIPTION', '0', '0', '0', NULL, NULL, 'ADVISOR_CONQUEST'),
('SLTH_BUILDING_SMOKEHOUSE', 'LOC_SLTH_BUILDING_SMOKEHOUSE_NAME', 'TECH_ANIMAL_HUSBANDRY', NULL, '120', 'DISTRICT_CITY_CENTER', 'LOC_SLTH_BUILDING_SMOKEHOUSE_DESCRIPTION', '0', '0', '0', NULL, NULL, 'ADVISOR_GENERIC'),
('SLTH_BUILDING_SMUGGLERS_PORT', 'LOC_SLTH_BUILDING_SMUGGLERS_PORT_NAME', NULL, NULL, '120', 'DISTRICT_COMMERCIAL_HUB', 'LOC_SLTH_BUILDING_SMUGGLERS_PORT_DESCRIPTION', '0', '0', '0', NULL, '1', 'ADVISOR_GENERIC'),
('SLTH_BUILDING_SOUL_FORGE', 'LOC_SLTH_BUILDING_SOUL_FORGE_NAME', NULL, 'CIVIC_MALEVOLENT_DESIGNS', '600', 'DISTRICT_CITY_CENTER', 'LOC_SLTH_BUILDING_SOUL_FORGE_DESCRIPTION', '0', '-2', '0', NULL, NULL, 'ADVISOR_GENERIC'),
('BUILDING_STABLE', 'LOC_BUILDING_STABLE_NAME', 'TECH_HORSEBACK_RIDING', NULL, '100', 'DISTRICT_CITY_CENTER', 'LOC_BUILDING_STABLE_DESCRIPTION', '0', '0', '0', NULL, NULL, 'ADVISOR_CONQUEST'),
('SLTH_BUILDING_TAVERN', 'LOC_SLTH_BUILDING_TAVERN_NAME', NULL, 'CIVIC_MERCANTILISM', '250', 'DISTRICT_CITY_CENTER', 'LOC_SLTH_BUILDING_TAVERN_DESCRIPTION', '0', '0', '0', NULL, NULL, 'ADVISOR_GENERIC'),
('BUILDING_GILDED_VAULT', 'LOC_BUILDING_TAX_OFFICE_NAME', NULL, 'CIVIC_TAXATION', '200', 'DISTRICT_CITY_CENTER', 'LOC_BUILDING_TAX_OFFICE_DESCRIPTION', '0', '0', '-1', NULL, NULL, 'ADVISOR_GENERIC'),
('BUILDING_WAT', 'LOC_BUILDING_TEMPLE_OF_KILMORPH_NAME', NULL, 'CIVIC_WAY_OF_THE_EARTHMOTHER', '120', 'DISTRICT_HOLY_SITE', 'LOC_BUILDING_TEMPLE_OF_KILMORPH_DESCRIPTION', '0', '0', '0', NULL, '1', 'ADVISOR_RELIGIOUS'),
('BUILDING_SANCTUARY', 'LOC_BUILDING_TEMPLE_OF_LEAVES_NAME', NULL, 'CIVIC_WAY_OF_THE_FORESTS', '120', 'DISTRICT_HOLY_SITE', 'LOC_BUILDING_TEMPLE_OF_LEAVES_DESCRIPTION', '0', '1', '0', NULL, '1', 'ADVISOR_RELIGIOUS'),
('BUILDING_GURDWARA', 'LOC_BUILDING_TEMPLE_OF_THE_EMPYREAN_NAME', NULL, 'CIVIC_HONOR', '120', 'DISTRICT_HOLY_SITE', 'LOC_BUILDING_TEMPLE_OF_THE_EMPYREAN_DESCRIPTION', '0', '0', '0', NULL, '2', 'ADVISOR_RELIGIOUS'),
('BUILDING_CATHEDRAL', 'LOC_BUILDING_TEMPLE_OF_THE_ORDER_NAME', NULL, 'CIVIC_ORDERS_FROM_HEAVEN', '120', 'DISTRICT_HOLY_SITE', 'LOC_BUILDING_TEMPLE_OF_THE_ORDER_DESCRIPTION', '0', '0', '0', NULL, '2', 'ADVISOR_RELIGIOUS'),
('BUILDING_MOSQUE', 'LOC_BUILDING_TEMPLE_OF_THE_OVERLORDS_NAME', NULL, 'CIVIC_MESSAGE_FROM_THE_DEEP', '120', 'DISTRICT_HOLY_SITE', 'LOC_BUILDING_TEMPLE_OF_THE_OVERLORDS_DESCRIPTION', '0', '0', '0', NULL, '1', 'ADVISOR_RELIGIOUS'),
('BUILDING_STUPA', 'LOC_BUILDING_TEMPLE_OF_THE_VEIL_NAME', NULL, 'CIVIC_CORRUPTION_OF_SPIRIT', '120', 'DISTRICT_HOLY_SITE', 'LOC_BUILDING_TEMPLE_OF_THE_VEIL_DESCRIPTION', '0', '0', '0', NULL, '1', 'ADVISOR_RELIGIOUS'),
('BUILDING_AMPHITHEATER', 'LOC_BUILDING_AMPHITHEATER_NAME', NULL, 'CIVIC_DRAMA_POETRY', '250', 'DISTRICT_THEATER', 'LOC_BUILDING_AMPHITHEATER_DESCRIPTION', '0', '0', '0', NULL, '1', 'ADVISOR_CULTURE'),
('BUILDING_BARRACKS', 'LOC_BUILDING_TRAINING_YARD_NAME', 'TECH_BRONZE_WORKING', NULL, '100', 'DISTRICT_CITY_CENTER', 'LOC_BUILDING_TRAINING_YARD_DESCRIPTION', '0', '0', '0', NULL, NULL, 'ADVISOR_CONQUEST'),
('BUILDING_CASTLE', 'LOC_BUILDING_CASTLE_NAME', 'TECH_MASONRY', NULL, '120', 'DISTRICT_CITY_CENTER', 'LOC_BUILDING_CASTLE_DESCRIPTION', '200', '0', '0', NULL, NULL, 'ADVISOR_CONQUEST');


INSERT INTO Building_YieldChanges(BuildingType, YieldType, YieldChange) VALUES
('BUILDING_MONUMENT', 'YIELD_CULTURE', '2');

INSERT INTO Building_YieldChanges(BuildingType, YieldType, YieldChange) VALUES
('BUILDING_PALACE', 'YIELD_CULTURE', '3'),
('BUILDING_PALACE', 'YIELD_PRODUCTION', '1'),
('BUILDING_PALACE', 'YIELD_FAITH', '8');
-- Wonders
INSERT INTO Buildings(BuildingType, Name, PrereqTech, PrereqCivic, Cost, PrereqDistrict, Description, OuterDefenseHitPoints, Housing, Entertainment, TraitType, CitizenSlots, AdvisorType, RequiresPlacement, IsWonder, MaxWorldInstances, Quote) VALUES
('BUILDING_HANGING_GARDENS', 'LOC_BUILDING_AQUAE_SUCELLUS_NAME', 'TECH_SANITATION', NULL, '600', NULL, 'LOC_BUILDING_AQUAE_SUCELLUS_DESCRIPTION', '0', '2', '0', NULL, NULL, 'ADVISOR_GENERIC', '1', '1', '1', 'LOC_PLACEHOLDER_QUOTE'),
('BUILDING_GRAND_BAZAAR', 'LOC_BUILDING_BAZAAR_OF_MAMMON_NAME', 'TECH_MATHEMATICS', NULL, '600', NULL, 'LOC_BUILDING_BAZAAR_OF_MAMMON_DESCRIPTION', '0', '0', '0', NULL, '3', 'ADVISOR_GENERIC', '1', '1', '1', 'LOC_PLACEHOLDER_QUOTE'),
('BUILDING_TAJ_MAHAL', 'LOC_BUILDING_BONE_PALACE_NAME', NULL, 'CIVIC_POLITICAL_PHILOSOPHY', '700', NULL, 'LOC_BUILDING_BONE_PALACE_DESCRIPTION', '0', '0', '0', NULL, NULL, 'ADVISOR_GENERIC', '1', '1', '1', 'LOC_PLACEHOLDER_QUOTE'),
('BUILDING_PETRA', 'LOC_BUILDING_CATACOMB_LIBRALUS_NAME', 'TECH_KNOWLEDGE_OF_THE_ETHER', NULL, '600', NULL, 'LOC_BUILDING_CATACOMB_LIBRALUS_DESCRIPTION', '0', '0', '0', NULL, '1', 'ADVISOR_TECHNOLOGY', '1', '1', '1', 'LOC_PLACEHOLDER_QUOTE'),
('SLTH_BUILDING_CELESTIAL_COMPASS', 'LOC_SLTH_BUILDING_CELESTIAL_COMPASS_NAME', 'TECH_ASTRONOMY', NULL, '500', NULL, 'LOC_SLTH_BUILDING_CELESTIAL_COMPASS_DESCRIPTION', '0', '0', '0', NULL, NULL, 'ADVISOR_RELIGIOUS', '1', '1', '1', 'LOC_PLACEHOLDER_QUOTE'),
('BUILDING_HERMITAGE', 'LOC_BUILDING_CITY_OF_A_THOUSAND_SLUMS_NAME', 'TECH_ENGINEERING', NULL, '500', NULL, 'LOC_BUILDING_CITY_OF_A_THOUSAND_SLUMS_DESCRIPTION', '0', '0', '0', NULL, NULL, 'ADVISOR_RELIGIOUS', '1', '1', '1', 'LOC_PLACEHOLDER_QUOTE'),
('BUILDING_COLOSSUS', 'LOC_SLTH_BUILDING_FORM_OF_THE_TITAN_NAME', NULL, 'CIVIC_MILITARY_TRADITION', '500', NULL, 'LOC_SLTH_BUILDING_FORM_OF_THE_TITAN_DESCRIPTION', '0', '0', '0', NULL, NULL, 'ADVISOR_CONQUEST', '1', '1', '1', 'LOC_PLACEHOLDER_QUOTE'),
('BUILDING_GREAT_ZIMBABWE', 'LOC_BUILDING_GRAND_MENAGERIE_NAME', NULL, 'CIVIC_GAMES_RECREATION', '120', NULL, 'LOC_BUILDING_GRAND_MENAGERIE_DESCRIPTION', '0', '0', '0', NULL, NULL, 'ADVISOR_CULTURE', '1', '1', '1', 'LOC_PLACEHOLDER_QUOTE'),
('BUILDING_GREAT_LIGHTHOUSE', 'LOC_BUILDING_GREAT_LIGHTHOUSE_NAME', 'SLTH_TECH_SAILING', NULL, '600', NULL, 'LOC_BUILDING_GREAT_LIGHTHOUSE_DESCRIPTION', '0', '0', '0', NULL, NULL, 'ADVISOR_GENERIC', '1', '1', '1', 'LOC_PLACEHOLDER_QUOTE'),
('SLTH_BUILDING_GUILD_OF_HAMMERS', 'LOC_SLTH_BUILDING_GUILD_OF_HAMMERS_NAME', 'TECH_ENGINEERING', NULL, '550', NULL, 'LOC_SLTH_BUILDING_GUILD_OF_HAMMERS_DESCRIPTION', '0', '0', '0', NULL, NULL, 'ADVISOR_GENERIC', '1', '1', '1', 'LOC_PLACEHOLDER_QUOTE'),
('BUILDING_UNIVERSITY_SANKORE', 'LOC_BUILDING_GUILD_OF_THE_NINE_NAME', NULL, 'CIVIC_CURRENCY', '500', NULL, 'LOC_BUILDING_GUILD_OF_THE_NINE_DESCRIPTION', '200', '0', '0', NULL, NULL, 'ADVISOR_GENERIC', '1', '1', '1', 'LOC_PLACEHOLDER_QUOTE'),
('BUILDING_HALICARNASSUS_MAUSOLEUM', 'LOC_BUILDING_HERON_THRONE_NAME', 'TECH_FISHING', NULL, '250', NULL, 'LOC_BUILDING_HERON_THRONE_DESCRIPTION', '200', '0', '0', NULL, NULL, 'ADVISOR_GENERIC', '1', '1', '1', 'LOC_PLACEHOLDER_QUOTE'),
('BUILDING_ST_BASILS_CATHEDRAL', 'LOC_BUILDING_HALL_OF_KINGS_NAME', NULL, 'CIVIC_FEUDALISM', '600', NULL, 'LOC_BUILDING_HALL_OF_KINGS_DESCRIPTION', '0', '0', '0', NULL, NULL, 'ADVISOR_CULTURE', '1', '1', '1', 'LOC_PLACEHOLDER_QUOTE'),
('BUILDING_JEBEL_BARKAL', 'LOC_BUILDING_MINES_OF_GALDUR_NAME', NULL, 'CIVIC_ARETE', '700', NULL, 'LOC_BUILDING_MINES_OF_GALDUR_DESCRIPTION', '0', '-2', '0', NULL, '3', 'ADVISOR_GENERIC', '1', '1', '1', 'LOC_PLACEHOLDER_QUOTE'),
('BUILDING_CHICHEN_ITZA', 'LOC_BUILDING_PILLAR_OF_CHAINS_NAME', NULL, 'CIVIC_TAXATION', '500', NULL, 'LOC_BUILDING_PILLAR_OF_CHAINS_DESCRIPTION', '0', '0', '0', NULL, NULL, 'ADVISOR_GENERIC', '1', '1', '1', 'LOC_PLACEHOLDER_QUOTE'),
('BUILDING_ETEMENANKI', 'LOC_SLTH_BUILDING_PROPHECY_OF_RAGNAROK_NAME', NULL, 'CIVIC_WAY_OF_THE_WICKED', '500', NULL, 'LOC_SLTH_BUILDING_PROPHECY_OF_RAGNAROK_DESCRIPTION', '0', '0', '0', NULL, '1', 'ADVISOR_RELIGIOUS', '1', '1', '1', 'LOC_PLACEHOLDER_QUOTE'),
('SLTH_BUILDING_RIDE_OF_THE_NINE_KINGS', 'LOC_SLTH_BUILDING_RIDE_OF_THE_NINE_KINGS_NAME', 'TECH_WARHORSES', NULL, '600', NULL, 'LOC_SLTH_BUILDING_RIDE_OF_THE_NINE_KINGS_DESCRIPTION', '0', '0', '0', NULL, NULL, 'ADVISOR_CONQUEST', '1', '1', '1', 'LOC_PLACEHOLDER_QUOTE'),
('BUILDING_CRISTO_REDENTOR', 'LOC_BUILDING_SHRINE_OF_SIRONA_NAME', 'TECH_DIVINATION', NULL, '500', NULL, 'LOC_BUILDING_SHRINE_OF_SIRONA_DESCRIPTION', '0', '0', '0', NULL, NULL, 'ADVISOR_RELIGIOUS', '1', '1', '1', 'LOC_PLACEHOLDER_QUOTE'),
('SLTH_BUILDING_THE_NEXUS', 'LOC_SLTH_BUILDING_THE_NEXUS_NAME', 'TECH_PASS_THROUGH_THE_ETHER', NULL, '600', NULL, 'LOC_SLTH_BUILDING_THE_NEXUS_DESCRIPTION', '0', '0', '0', NULL, NULL, 'ADVISOR_CONQUEST', '1', '1', '1', 'LOC_PLACEHOLDER_QUOTE'),
('BUILDING_BIG_BEN', 'LOC_BUILDING_TOWER_OF_COMPLACENCY_NAME', NULL, 'CIVIC_MIND_STAPLING', '750', NULL, 'LOC_BUILDING_TOWER_OF_COMPLACENCY_DESCRIPTION', '0', '0', '70', NULL, NULL, 'ADVISOR_GENERIC', '1', '1', '1', 'LOC_PLACEHOLDER_QUOTE'),
('BUILDING_MONT_ST_MICHEL', 'LOC_BUILDING_TOWER_OF_EYES_NAME', 'TECH_OPTICS', NULL, '700', NULL, 'LOC_BUILDING_TOWER_OF_EYES_DESCRIPTION', '0', '0', '0', NULL, NULL, 'ADVISOR_CONQUEST', '1', '1', '1', 'LOC_PLACEHOLDER_QUOTE'),
('BUILDING_HAGIA_SOPHIA', 'LOC_BUILDING_TEMPLE_OF_TEMPORENCE_NAME', NULL, 'CIVIC_RELIGIOUS_LAW', '650', NULL, 'LOC_BUILDING_TEMPLE_OF_TEMPORENCE_DESCRIPTION', '0', '0', '0', NULL, NULL, 'ADVISOR_GENERIC',  '1', '1', '1', 'LOC_PLACEHOLDER_QUOTE');

INSERT INTO Building_YieldChanges(BuildingType, YieldType, YieldChange) VALUES
('BUILDING_TAJ_MAHAL', 'YIELD_CULTURE', '10'),
('BUILDING_PETRA', 'YIELD_CULTURE', '4'),
('BUILDING_PETRA', 'YIELD_SCIENCE', '4'),
('SLTH_BUILDING_CELESTIAL_COMPASS', 'YIELD_CULTURE', '4'),
('BUILDING_GREAT_ZIMBABWE', 'YIELD_CULTURE', '8'),
('SLTH_BUILDING_GUILD_OF_HAMMERS', 'YIELD_CULTURE', '8'),
('BUILDING_UNIVERSITY_SANKORE', 'YIELD_CULTURE', '4'),
('BUILDING_ST_BASILS_CATHEDRAL', 'YIELD_CULTURE', '10'),
('BUILDING_HALICARNASSUS_MAUSOLEUM', 'YIELD_CULTURE', '8'),
('BUILDING_CHICHEN_ITZA', 'YIELD_CULTURE', '4'),
('BUILDING_ETEMENANKI', 'YIELD_CULTURE', '8'),
('SLTH_BUILDING_RIDE_OF_THE_NINE_KINGS', 'YIELD_CULTURE', '4'),
('BUILDING_CRISTO_REDENTOR', 'YIELD_CULTURE', '10'),
('BUILDING_HAGIA_SOPHIA', 'YIELD_CULTURE', '10'),
('BUILDING_GREAT_LIGHTHOUSE', 'YIELD_CULTURE', '6'),
('BUILDING_MONT_ST_MICHEL', 'YIELD_CULTURE', '3');

-- National Wonders that should stay in city centre
INSERT INTO Buildings(BuildingType, Name, PrereqTech, PrereqCivic, Cost, PrereqDistrict, Description, OuterDefenseHitPoints, Housing, Entertainment, TraitType, CitizenSlots, AdvisorType, MaxPlayerInstances) VALUES
('BUILDING_KOTOKU_IN', 'LOC_SLTH_BUILDING_SHRINE_OF_THE_CHAMPION_NAME', NULL, NULL, '250', 'DISTRICT_CITY_CENTER', 'LOC_SLTH_BUILDING_SHRINE_OF_THE_CHAMPION_DESCRIPTION', '0', '0', '0', NULL, NULL, 'ADVISOR_CONQUEST', '1'),
('SLTH_BUILDING_HEROIC_EPIC', 'LOC_SLTH_BUILDING_HEROIC_EPIC_NAME', NULL, 'CIVIC_MILITARY_TRAINING', '200', 'DISTRICT_CITY_CENTER', 'LOC_SLTH_BUILDING_HEROIC_EPIC_DESCRIPTION', '0', '0', '0', NULL, NULL, 'ADVISOR_CONQUEST', '1'),
('SLTH_BUILDING_NATIONAL_EPIC', 'LOC_SLTH_BUILDING_NATIONAL_EPIC_NAME', NULL, 'CIVIC_MILITARY_TRADITION', '250', 'DISTRICT_CITY_CENTER', 'LOC_SLTH_BUILDING_NATIONAL_EPIC_DESCRIPTION', '0', '0', '0', NULL, NULL, 'ADVISOR_CULTURE', '1');

INSERT INTO Building_YieldChanges(BuildingType, YieldType, YieldChange) VALUES
('BUILDING_KOTOKU_IN', 'YIELD_CULTURE', '5'),
('SLTH_BUILDING_NATIONAL_EPIC', 'YIELD_CULTURE', '4'),
('SLTH_BUILDING_HEROIC_EPIC', 'YIELD_CULTURE', 4);

INSERT INTO Buildings(BuildingType, Name, PrereqTech, Cost, PrereqDistrict, Description, AdvisorType, MaxPlayerInstances, RequiresAdjacentRiver) VALUES
('BUILDING_PALGUM', 'LOC_BUILDING_PALGUM_NAME', 'TECH_CRAFTING', '240', 'DISTRICT_CITY_CENTER', 'LOC_BUILDING_PALGUM_DESCRIPTION', 'ADVISOR_GENERIC', '1', '1');

-- coastal unlock for buildings
INSERT INTO Buildings
		(BuildingType,						PrereqDistrict,				Cost,	PurchaseYield, MustPurchase,	AdvisorType,		Name,				Description)
VALUES  ('BUILDING_CITY_IS_COASTAL',		'DISTRICT_CITY_CENTER',		0,		NULL,          '1',			    'ADVISOR_GENERIC',	'LOC_NULL',			'LOC_NULL');

INSERT OR IGNORE INTO Buildings_XP2(BuildingType, Pillage)VALUES
('BUILDING_CITY_IS_COASTAL', '0');

INSERT OR IGNORE INTO BuildingPrereqs
		(Building,							PrereqBuilding)
VALUES	('BUILDING_LIGHTHOUSE',		'BUILDING_CITY_IS_COASTAL'),
		('BUILDING_SHIPYARD',		'BUILDING_CITY_IS_COASTAL'),
		('SLTH_BUILDING_HARBOR',		'BUILDING_CITY_IS_COASTAL'),
		('SLTH_BUILDING_SMUGGLERS_PORT',		'BUILDING_CITY_IS_COASTAL');

INSERT OR IGNORE INTO Modifiers
		(ModifierId,						ModifierType,											SubjectRequirementSetId)
VALUES	('SLTH_GRANT_DUMMY_COAST',		'MODIFIER_SINGLE_CITY_GRANT_BUILDING_IN_CITY_IGNORE',	'PLOT_IS_ADJACENT_TO_COAST');

INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,						Name,			Value)
VALUES	('SLTH_GRANT_DUMMY_COAST',		'BuildingType',	'BUILDING_CITY_IS_COASTAL');

INSERT OR IGNORE INTO DistrictModifiers
		(DistrictType,				ModifierId)
VALUES	('DISTRICT_CITY_CENTER',	'SLTH_GRANT_DUMMY_COAST');

-- Event Triggered only
INSERT INTO Buildings(BuildingType, Name, PrereqTech, PrereqCivic, Cost, PrereqDistrict, Description, OuterDefenseHitPoints, Housing, Entertainment, TraitType, CitizenSlots, AdvisorType, PurchaseYield, MustPurchase) VALUES
('SLTH_BUILDING_DANCING_BEAR', 'LOC_SLTH_BUILDING_DANCING_BEAR_NAME', NULL, NULL, '1', 'DISTRICT_CITY_CENTER', 'LOC_SLTH_BUILDING_DANCING_BEAR_DESCRIPTION', '0', '0', '1', NULL, NULL, 'ADVISOR_CULTURE', NULL, '1'),
('SLTH_BUILDING_GORILLA_CAGE', 'LOC_SLTH_BUILDING_GORILLA_CAGE_NAME', NULL, NULL, '1', 'DISTRICT_CITY_CENTER', 'LOC_SLTH_BUILDING_GORILLA_CAGE_DESCRIPTION', '0', '0', '1', NULL, NULL, 'ADVISOR_CULTURE', NULL, '1'),
('SLTH_BUILDING_LION_CAGE', 'LOC_SLTH_BUILDING_LION_CAGE_NAME', NULL, NULL, '1', 'DISTRICT_CITY_CENTER', 'LOC_SLTH_BUILDING_LION_CAGE_DESCRIPTION', '0', '0', '1', NULL, NULL, 'ADVISOR_CULTURE', NULL, '1'),
('SLTH_BUILDING_SPIDER_PEN', 'LOC_SLTH_BUILDING_SPIDER_PEN_NAME', 'TECH_ANIMAL_HANDLING', NULL, '1', 'DISTRICT_CITY_CENTER', 'LOC_SLTH_BUILDING_SPIDER_PEN_DESCRIPTION', '0', '0', '0', NULL, NULL, 'ADVISOR_GENERIC', NULL, '1'),
('SLTH_BUILDING_TIGER_CAGE', 'LOC_SLTH_BUILDING_TIGER_CAGE_NAME', NULL, NULL, '1', 'DISTRICT_CITY_CENTER', 'LOC_SLTH_BUILDING_TIGER_CAGE_DESCRIPTION', '0', '0', '1', NULL, NULL, 'ADVISOR_CULTURE', NULL, '1'),
('SLTH_BUILDING_WOLF_PEN', 'LOC_SLTH_BUILDING_WOLF_PEN_NAME', NULL, NULL, '1', 'DISTRICT_CITY_CENTER', 'LOC_SLTH_BUILDING_WOLF_PEN_DESCRIPTION', '0', '0', '0', NULL, NULL, 'ADVISOR_CULTURE', NULL, '1');

INSERT INTO Building_YieldChanges(BuildingType, YieldType, YieldChange) VALUES
('SLTH_BUILDING_DANCING_BEAR', 'YIELD_CULTURE', '3'),
('SLTH_BUILDING_GORILLA_CAGE', 'YIELD_CULTURE', '3'),
('SLTH_BUILDING_LION_CAGE', 'YIELD_CULTURE', '3'),
('SLTH_BUILDING_TIGER_CAGE', 'YIELD_CULTURE', '3'),
('SLTH_BUILDING_WOLF_PEN', 'YIELD_CULTURE', '2');

INSERT INTO BuildingPrereqs(Building,							PrereqBuilding)
VALUES	                   ('BUILDING_GREAT_ZIMBABWE',		'SLTH_BUILDING_DANCING_BEAR'),
                           ('BUILDING_GREAT_ZIMBABWE',		'SLTH_BUILDING_GORILLA_CAGE'),
                           ('BUILDING_GREAT_ZIMBABWE',		'SLTH_BUILDING_LION_CAGE'),
                           ('BUILDING_GREAT_ZIMBABWE',		'SLTH_BUILDING_TIGER_CAGE'),
                           ('BUILDING_GREAT_ZIMBABWE',		'SLTH_BUILDING_WOLF_PEN');

-- item
INSERT INTO Buildings(BuildingType, Name, PrereqTech, PrereqCivic, Cost, PrereqDistrict, Description, OuterDefenseHitPoints, Housing, Entertainment, TraitType, CitizenSlots, AdvisorType) VALUES
('SLTH_BUILDING_INFERNAL_GRIMOIRE', 'LOC_SLTH_BUILDING_INFERNAL_GRIMOIRE_NAME', NULL, 'CIVIC_INFERNAL_PACT', '400', 'DISTRICT_CITY_CENTER', 'LOC_SLTH_BUILDING_INFERNAL_GRIMOIRE_DESCRIPTION', '0', '0', '0', NULL, NULL, 'ADVISOR_CONQUEST'),
('SLTH_BUILDING_CROWN_OF_AKHARIEN', 'LOC_SLTH_BUILDING_CROWN_OF_AKHARIEN_NAME', 'TECH_ARCANE_LORE', NULL, '900', 'DISTRICT_CITY_CENTER', 'LOC_SLTH_BUILDING_CROWN_OF_AKHARIEN_DESCRIPTION', '0', '0', '0', NULL, NULL, 'ADVISOR_TECHNOLOGY'),
('SLTH_BUILDING_SYLIVENS_PERFECT_LYRE', 'LOC_SLTH_BUILDING_SYLIVENS_PERFECT_LYRE_NAME', NULL, 'CIVIC_DRAMA_POETRY', '900', 'DISTRICT_CITY_CENTER', 'LOC_SLTH_BUILDING_SYLIVENS_PERFECT_LYRE_DESCRIPTION', '0', '0', '0', NULL, NULL, 'ADVISOR_CULTURE');

INSERT INTO Buildings(BuildingType, Name, PrereqTech, PrereqCivic, Cost, PrereqDistrict, Description, OuterDefenseHitPoints, Housing, Entertainment, TraitType, CitizenSlots, AdvisorType, PurchaseYield, MustPurchase) VALUES
('SLTH_BUILDING_MOKKAS_CAULDRON', 'LOC_SLTH_BUILDING_MOKKAS_CAULDRON_NAME', NULL, NULL, '600', 'DISTRICT_CITY_CENTER', 'LOC_SLTH_BUILDING_MOKKAS_CAULDRON_DESCRIPTION', '0', '0', '0', NULL, NULL, 'ADVISOR_CONQUEST', NULL, '1'),
('SLTH_BUILDING_THE_DRAGONS_HORDE', 'LOC_SLTH_BUILDING_THE_DRAGONS_HORDE_NAME', NULL, NULL, '1', 'DISTRICT_CITY_CENTER', 'LOC_SLTH_BUILDING_THE_DRAGONS_HORDE_DESCRIPTION', '0', '0', '0', NULL, NULL, 'ADVISOR_CONQUEST', NULL, '1');

INSERT INTO Building_YieldChanges(BuildingType, YieldType, YieldChange) VALUES
('SLTH_BUILDING_MOKKAS_CAULDRON', 'YIELD_CULTURE', '2'),
('SLTH_BUILDING_THE_DRAGONS_HORDE', 'YIELD_CULTURE', '8'),
('SLTH_BUILDING_THE_DRAGONS_HORDE', 'YIELD_GOLD', '4');

INSERT INTO Buildings(BuildingType, Name, PrereqTech, PrereqCivic, Cost, PrereqDistrict, Description, OuterDefenseHitPoints, Housing, Entertainment, TraitType, CitizenSlots, AdvisorType) VALUES
('SLTH_BUILDING_NULL_CIVILIZATION_KURIOTATES_STABLE', 'LOC_SLTH_BUILDING_NULL_NAME', NULL, NULL, '500', 'DISTRICT_CITY_CENTER', 'LOC_SLTH_BUILDING_NULLDESCRIPTION', '0', '0', '0', 'NULL_CIVILIZATION_KURIOTATES', NULL, 'ADVISOR_RELIGIOUS'),
('SLTH_BUILDING_NULL_CIVILIZATION_HIPPUS_ALCHEMY_LAB', 'LOC_SLTH_BUILDING_NULL_NAME', NULL, NULL, '500', 'DISTRICT_CITY_CENTER', 'LOC_SLTH_BUILDING_NULLDESCRIPTION', '0', '0', '0', 'NULL_CIVILIZATION_HIPPUS', NULL, 'ADVISOR_RELIGIOUS'),
('SLTH_BUILDING_NULL_CIVILIZATION_DOVIELLO_ALCHEMY_LAB', 'LOC_SLTH_BUILDING_NULL_NAME', NULL, NULL, '500', 'DISTRICT_CITY_CENTER', 'LOC_SLTH_BUILDING_NULLDESCRIPTION', '0', '0', '0', 'NULL_CIVILIZATION_DOVIELLO', NULL, 'ADVISOR_RELIGIOUS'),
('SLTH_BUILDING_NULL_CIVILIZATION_DOVIELLO_LIBRARY', 'LOC_SLTH_BUILDING_NULL_NAME', NULL, NULL, '500', 'DISTRICT_CITY_CENTER', 'LOC_SLTH_BUILDING_NULLDESCRIPTION', '0', '0', '0', 'NULL_CIVILIZATION_DOVIELLO', NULL, 'ADVISOR_RELIGIOUS'),
('SLTH_BUILDING_NULL_CIVILIZATION_DOVIELLO_MAGE_GUILD', 'LOC_SLTH_BUILDING_NULL_NAME', NULL, NULL, '500', 'DISTRICT_CITY_CENTER', 'LOC_SLTH_BUILDING_NULLDESCRIPTION', '0', '0', '0', 'NULL_CIVILIZATION_DOVIELLO', NULL, 'ADVISOR_RELIGIOUS'),
('SLTH_BUILDING_NULL_CIVILIZATION_CLAN_OF_EMBERS_ALCHEMY_LAB', 'LOC_SLTH_BUILDING_NULL_NAME', NULL, NULL, '500', 'DISTRICT_CITY_CENTER', 'LOC_SLTH_BUILDING_NULLDESCRIPTION', '0', '0', '0', 'NULL_CIVILIZATION_CLAN_OF_EMBERS', NULL, 'ADVISOR_RELIGIOUS'),
('SLTH_BUILDING_NULL_CIVILIZATION_CLAN_OF_EMBERS_LIBRARY', 'LOC_SLTH_BUILDING_NULL_NAME', NULL, NULL, '500', 'DISTRICT_CITY_CENTER', 'LOC_SLTH_BUILDING_NULLDESCRIPTION', '0', '0', '0', 'NULL_CIVILIZATION_CLAN_OF_EMBERS', NULL, 'ADVISOR_RELIGIOUS'),
('SLTH_BUILDING_NULL_CIVILIZATION_CLAN_OF_EMBERS_MAGE_GUILD', 'LOC_SLTH_BUILDING_NULL_NAME', NULL, NULL, '500', 'DISTRICT_CITY_CENTER', 'LOC_SLTH_BUILDING_NULLDESCRIPTION', '0', '0', '0', 'NULL_CIVILIZATION_CLAN_OF_EMBERS', NULL, 'ADVISOR_RELIGIOUS'),
('SLTH_BUILDING_NULL_CIVILIZATION_CLAN_OF_EMBERS_STABLE', 'LOC_SLTH_BUILDING_NULL_NAME', NULL, NULL, '500', 'DISTRICT_CITY_CENTER', 'LOC_SLTH_BUILDING_NULLDESCRIPTION', '0', '0', '0', 'NULL_CIVILIZATION_CLAN_OF_EMBERS', NULL, 'ADVISOR_RELIGIOUS'),
('SLTH_BUILDING_NULL_CIVILIZATION_CALABIM_ALCHEMY_LAB', 'LOC_SLTH_BUILDING_NULL_NAME', NULL, NULL, '500', 'DISTRICT_CITY_CENTER', 'LOC_SLTH_BUILDING_NULLDESCRIPTION', '0', '0', '0', 'NULL_CIVILIZATION_CALABIM', NULL, 'ADVISOR_RELIGIOUS'),
('SLTH_BUILDING_NULL_CIVILIZATION_CALABIM_ELDER_COUNCIL', 'LOC_SLTH_BUILDING_NULL_NAME', NULL, NULL, '500', 'DISTRICT_CITY_CENTER', 'LOC_SLTH_BUILDING_NULLDESCRIPTION', '0', '0', '0', 'NULL_CIVILIZATION_CALABIM', NULL, 'ADVISOR_RELIGIOUS'),
('SLTH_BUILDING_NULL_CIVILIZATION_INFERNAL_AQUEDUCT', 'LOC_SLTH_BUILDING_NULL_NAME', NULL, NULL, '500', 'DISTRICT_CITY_CENTER', 'LOC_SLTH_BUILDING_NULLDESCRIPTION', '0', '0', '0', 'NULL_CIVILIZATION_INFERNAL', NULL, 'ADVISOR_RELIGIOUS'),
('SLTH_BUILDING_NULL_CIVILIZATION_INFERNAL_GRANARY', 'LOC_SLTH_BUILDING_NULL_NAME', NULL, NULL, '500', 'DISTRICT_CITY_CENTER', 'LOC_SLTH_BUILDING_NULLDESCRIPTION', '0', '0', '0', 'NULL_CIVILIZATION_INFERNAL', NULL, 'ADVISOR_RELIGIOUS'),
('SLTH_BUILDING_NULL_CIVILIZATION_INFERNAL_HERBALIST', 'LOC_SLTH_BUILDING_NULL_NAME', NULL, NULL, '500', 'DISTRICT_CITY_CENTER', 'LOC_SLTH_BUILDING_NULLDESCRIPTION', '0', '0', '0', 'NULL_CIVILIZATION_INFERNAL', NULL, 'ADVISOR_RELIGIOUS'),
('SLTH_BUILDING_NULL_CIVILIZATION_INFERNAL_INFIRMARY', 'LOC_SLTH_BUILDING_NULL_NAME', NULL, NULL, '500', 'DISTRICT_CITY_CENTER', 'LOC_SLTH_BUILDING_NULLDESCRIPTION', '0', '0', '0', 'NULL_CIVILIZATION_INFERNAL', NULL, 'ADVISOR_RELIGIOUS'),
('SLTH_BUILDING_NULL_CIVILIZATION_INFERNAL_PUBLIC_BATHS', 'LOC_SLTH_BUILDING_NULL_NAME', NULL, NULL, '500', 'DISTRICT_CITY_CENTER', 'LOC_SLTH_BUILDING_NULLDESCRIPTION', '0', '0', '0', 'NULL_CIVILIZATION_INFERNAL', NULL, 'ADVISOR_RELIGIOUS'),
('SLTH_BUILDING_NULL_CIVILIZATION_INFERNAL_SMOKEHOUSE', 'LOC_SLTH_BUILDING_NULL_NAME', NULL, NULL, '500', 'DISTRICT_CITY_CENTER', 'LOC_SLTH_BUILDING_NULLDESCRIPTION', '0', '0', '0', 'NULL_CIVILIZATION_INFERNAL', NULL, 'ADVISOR_RELIGIOUS');

INSERT INTO Building_GreatPersonPoints(BuildingType, GreatPersonClassType, PointsPerTurn) VALUES
('SLTH_BUILDING_ASYLUM', 'GREAT_PERSON_CLASS_PROPHET', '1'),
('BUILDING_SYNAGOGUE', 'GREAT_PERSON_CLASS_GENERAL', '1'),
('BUILDING_GRAND_BAZAAR', 'GREAT_PERSON_CLASS_MERCHANT', '2'),
('BUILDING_TAJ_MAHAL', 'GREAT_PERSON_CLASS_ENGINEER', '2'),
('BUILDING_PETRA', 'GREAT_PERSON_CLASS_SCIENTIST', '2'),
('SLTH_BUILDING_CELESTIAL_COMPASS', 'GREAT_PERSON_CLASS_PROPHET', '2'),
('SLTH_BUILDING_CROWN_OF_AKHARIEN', 'GREAT_PERSON_CLASS_SCIENTIST', '2'),
('BUILDING_COLOSSUS', 'GREAT_PERSON_CLASS_GENERAL', '2'),
('BUILDING_GREAT_LIGHTHOUSE', 'GREAT_PERSON_CLASS_MERCHANT', '2'),
('SLTH_BUILDING_GUILD_OF_HAMMERS', 'GREAT_PERSON_CLASS_ENGINEER', '2'),
('BUILDING_UNIVERSITY_SANKORE', 'GREAT_PERSON_CLASS_GENERAL', '1'),
('BUILDING_ST_BASILS_CATHEDRAL', 'GREAT_PERSON_CLASS_ARTIST', '2'),
('SLTH_BUILDING_HEROIC_EPIC', 'GREAT_PERSON_CLASS_GENERAL', '1'),
('SLTH_BUILDING_INFERNAL_GRIMOIRE', 'GREAT_PERSON_CLASS_SCIENTIST', '1'),
('BUILDING_JEBEL_BARKAL', 'GREAT_PERSON_CLASS_ENGINEER', '1'),
('SLTH_BUILDING_NATIONAL_EPIC', 'GREAT_PERSON_CLASS_GENERAL', '1'),
('BUILDING_ETEMENANKI', 'GREAT_PERSON_CLASS_PROPHET', '2'),
('SLTH_BUILDING_RIDE_OF_THE_NINE_KINGS', 'GREAT_PERSON_CLASS_GENERAL', '2'),
('BUILDING_CRISTO_REDENTOR', 'GREAT_PERSON_CLASS_PROPHET', '2'),
('BUILDING_KOTOKU_IN', 'GREAT_PERSON_CLASS_PROPHET', '3'),
('SLTH_BUILDING_SOUL_FORGE', 'GREAT_PERSON_CLASS_ENGINEER', '2'),
('SLTH_BUILDING_SYLIVENS_PERFECT_LYRE', 'GREAT_PERSON_CLASS_ARTIST', '2'),
('SLTH_BUILDING_TAVERN', 'GREAT_PERSON_CLASS_ARTIST', '1'),
('BUILDING_HAGIA_SOPHIA', 'GREAT_PERSON_CLASS_ARTIST', '2'),
('SLTH_BUILDING_THE_NEXUS', 'GREAT_PERSON_CLASS_SCIENTIST', '1'),
('BUILDING_BIG_BEN', 'GREAT_PERSON_CLASS_GENERAL', '1'),
('BUILDING_MONT_ST_MICHEL', 'GREAT_PERSON_CLASS_GENERAL', '1');

INSERT INTO Building_YieldChanges(BuildingType, YieldType, YieldChange) VALUES
('BUILDING_RESEARCH_LAB', 'YIELD_SCIENCE', '4'),
('SLTH_BUILDING_CROWN_OF_AKHARIEN', 'YIELD_SCIENCE', '2'),
('SLTH_BUILDING_CROWN_OF_AKHARIEN', 'YIELD_CULTURE', '2'),
('SLTH_BUILDING_SYLIVENS_PERFECT_LYRE', 'YIELD_CULTURE', '4'),
('SLTH_BUILDING_ELDER_COUNCIL', 'YIELD_SCIENCE', '2'),
('SLTH_BUILDING_GAMBLING_HOUSE', 'YIELD_GOLD', '3'),
('BUILDING_MARKET', 'YIELD_GOLD', '3'),
('BUILDING_MARKET', 'YIELD_SCIENCE', '-1'),
('BUILDING_WAT', 'YIELD_GOLD', '2'),
('BUILDING_STUPA', 'YIELD_SCIENCE', '2'),
('BUILDING_MOSQUE', 'YIELD_CULTURE', '3'),
('BUILDING_AMPHITHEATER', 'YIELD_CULTURE', '3');
INSERT INTO BuildingConditions(BuildingType, UnlocksFromEffect) VALUES
('SLTH_BUILDING_MOKKAS_CAULDRON', '1'),
('SLTH_BUILDING_THE_DRAGONS_HORDE', '1'),
('BUILDING_KOTOKU_IN', '1'),
('SLTH_BUILDING_SMUGGLERS_PORT', '1');

INSERT INTO BuildingModifiers(BuildingType, ModifierId) VALUES
('BUILDING_RESEARCH_LAB', 'MODIFIER_BUILDING_RESEARCH_LAB_ADD_SCIENCEYIELD'),
('BUILDING_HANGING_GARDENS', 'MODIFIER_BUILDING_HANGING_GARDENS_ADJUST_HOUSING'),
('SLTH_BUILDING_ASYLUM', 'MODIFIER_SLTH_BUILDING_ASYLUM_ADJUST_WAR_WEARINESS'),
('SLTH_BUILDING_ASYLUM', 'MODIFIER_SLTH_BUILDING_ASYLUM_ADD_SCIENCEYIELD'),
('BUILDING_GRAND_BAZAAR', 'MODIFIER_BUILDING_GRAND_BAZAAR_ADD_GOLDYIELD'),
('BUILDING_PALGUM', 'MODIFIER_BUILDING_PALGUM_GRANT_ALE'),
('SLTH_BUILDING_CARNIVAL', 'MODIFIER_SLTH_BUILDING_CARNIVAL_ADD_CULTUREYIELD'),
('BUILDING_PETRA', 'MODIFIER_ALL_CITIES_FREE_BUILDING_PETRA'),
('BUILDING_PETRA', 'MODIFIER_FREE_BUILDING_PETRA'),
('SLTH_BUILDING_CELESTIAL_COMPASS', 'MODIFIER_SLTH_BUILDING_CELESTIAL_COMPASS_PROJECT_PROD_MULT'),
('SLTH_BUILDING_CROWN_OF_AKHARIEN', 'MODIFIER_SLTH_BUILDING_CROWN_OF_AKHARIEN_ADD_SCIENCEYIELD'),
('SLTH_BUILDING_DEMONS_ALTAR', 'MODIFIER_SLTH_BUILDING_DEMONS_ALTAR_MILITARY_EXPERIENCE'),
('SLTH_BUILDING_DUNGEON', 'MODIFIER_SLTH_BUILDING_DUNGEON_ADJUST_WAR_WEARINESS'),
('BUILDING_WORKSHOP', 'MODIFIER_BUILDING_WORKSHOP_ADD_PRODUCTIONYIELD'),
('BUILDING_COLOSSUS', 'GRANT_EXPERIENCE_ABILITY_SMALL_TITAN'),
('BUILDING_GREAT_ZIMBABWE', 'MODIFIER_ALL_CITIES_FREE_BUILDING_GREAT_ZIMBABWE'),
('BUILDING_GREAT_ZIMBABWE', 'MODIFIER_FREE_BUILDING_GREAT_ZIMBABWE'),
('BUILDING_GREAT_ZIMBABWE', 'MODIFIER_BUILDING_GREAT_ZIMBABWE_ADD_AMENITIES'),
('BUILDING_GREAT_ZIMBABWE', 'MODIFIER_BUILDING_GREAT_ZIMBABWE_ADD_CULTUREYIELD'),
('BUILDING_GREAT_LIGHTHOUSE', 'MODIFIER_BUILDING_GREAT_LIGHTHOUSE_ADJUST_TRADE_ROUTE_CAPACITY_COASTAL'),
('SLTH_BUILDING_GUILD_OF_HAMMERS', 'MODIFIER_ALL_CITIES_FREE_SLTH_BUILDING_GUILD_OF_HAMMERS'),
('SLTH_BUILDING_GUILD_OF_HAMMERS', 'MODIFIER_FREE_SLTH_BUILDING_GUILD_OF_HAMMERS'),
('BUILDING_HALICARNASSUS_MAUSOLEUM', 'MODIFIER_BUILDING_HALICARNASSUS_MAUSOLEUM_PLOT_YIELD_CHANGE_PRODUCTION'),
('SLTH_BUILDING_HARBOR', 'MODIFIER_SLTH_BUILDING_HARBOR_TRADE_ROUTE_YIELD_MULT'),
('SLTH_BUILDING_HEROIC_EPIC', 'MODIFIER_SLTH_BUILDING_HEROIC_EPIC_MILITARY_PRODUCTION'),
('SLTH_BUILDING_INFERNAL_GRIMOIRE', 'MODIFIER_SLTH_BUILDING_INFERNAL_GRIMOIRE_FREE_TECH'),
('SLTH_BUILDING_INN', 'MODIFIER_SLTH_BUILDING_INN_ADJUST_TRADE_ROUTE_CAPACITY'),
('SLTH_BUILDING_INN', 'MODIFIER_SLTH_BUILDING_INN_TRADE_ROUTE_YIELD_MULT'),
('BUILDING_LIBRARY', 'MODIFIER_BUILDING_LIBRARY_ADD_SCIENCEYIELD'),
('BUILDING_LIGHTHOUSE', 'MODIFIER_BUILDING_LIGHTHOUSE_ADJUST_TRADE_ROUTE_CAPACITY'),
('BUILDING_LIGHTHOUSE', 'MODIFIER_BUILDING_LIGHTHOUSE_PLOT_YIELD_CHANGE_FOOD'),
('BUILDING_JEBEL_BARKAL', 'MODIFIER_BUILDING_JEBEL_BARKAL_GRANT_IRON'),
('BUILDING_BANK', 'MODIFIER_BUILDING_BANK_ADD_GOLDYIELD'),
('SLTH_BUILDING_NATIONAL_EPIC', 'MODIFIER_NATIONAL_EPIC_INCREASE_GPP_MULT'),
('SLTH_BUILDING_OBSIDIAN_GATE', 'MODIFIER_SLTH_BUILDING_OBSIDIAN_GATE_ADJUST_TRADE_ROUTE_CAPACITY'),
('BUILDING_SHRINE', 'MODIFIER_BUILDING_SHRINE_ADD_CULTUREYIELD'),
('BUILDING_CHICHEN_ITZA', 'MODIFIER_BUILDING_CHICHEN_ITZA_ADJUST_WAR_WEARINESS'),
('BUILDING_ETEMENANKI', 'MODIFIER_BUILDING_ETEMENANKI_MILITARY_EXPERIENCE'),
('SLTH_BUILDING_RIDE_OF_THE_NINE_KINGS', 'GRANT_EXPERIENCE_ABILITY_SMALL_RIDE_OF_KINGS_CAV'),
('BUILDING_SHIPYARD', 'GRANT_EXPERIENCE_ABILITY_SMALL_SHIPYARD_NAVAL'),
('BUILDING_SHIPYARD', 'MODIFIER_BUILDING_SHIPYARD_DOMAIN_SEA_PROD_MULT'),
('BUILDING_KOTOKU_IN', 'MODIFIER_BUILDING_KOTOKU_IN_MILITARY_EXPERIENCE'),
('SLTH_BUILDING_SMUGGLERS_PORT', 'MODIFIER_SLTH_BUILDING_SMUGGLERS_PORT_ADJUST_TRADE_ROUTE_CAPACITY'),
('SLTH_BUILDING_SMUGGLERS_PORT', 'MODIFIER_SLTH_BUILDING_SMUGGLERS_PORT_ADD_GOLDYIELD'),
('SLTH_BUILDING_SOUL_FORGE', 'MODIFIER_SLTH_BUILDING_SOUL_FORGE_GRANT_MANA_DEATH'),
('SLTH_BUILDING_SPIDER_PEN', 'MODIFIER_SLTH_BUILDING_SPIDER_PEN_GRANT_SILK'),
('SLTH_BUILDING_SYLIVENS_PERFECT_LYRE', 'MODIFIER_SLTH_BUILDING_SYLIVENS_PERFECT_LYRE_ADD_CULTUREYIELD'),
('SLTH_BUILDING_TAVERN', 'MODIFIER_SLTH_BUILDING_TAVERN_ADJUST_TRADE_ROUTE_CAPACITY'),
('SLTH_BUILDING_TAVERN', 'MODIFIER_SLTH_BUILDING_TAVERN_TRADE_ROUTE_YIELD_MULT'),
('BUILDING_GILDED_VAULT', 'MODIFIER_BUILDING_GILDED_VAULT_ADD_GOLDYIELD'),
('BUILDING_WAT', 'MODIFIER_BUILDING_WAT_ADD_CULTUREYIELD'),
('BUILDING_SANCTUARY', 'MODIFIER_BUILDING_SANCTUARY_ADD_CULTUREYIELD'),
('BUILDING_GURDWARA', 'MODIFIER_BUILDING_GURDWARA_ADD_SCIENCEYIELD'),
('BUILDING_GURDWARA', 'MODIFIER_YieldType_ADD_CULTUREYIELD'),
('BUILDING_CATHEDRAL', 'MODIFIER_BUILDING_CATHEDRAL_MILITARY_PRODUCTION'),
('BUILDING_CATHEDRAL', 'MODIFIER_BUILDING_CATHEDRAL_ADD_CULTUREYIELD'),
('BUILDING_MOSQUE', 'MODIFIER_BUILDING_MOSQUE_ADD_CULTUREYIELD'),
('BUILDING_STUPA', 'MODIFIER_BUILDING_STUPA_ADD_CULTUREYIELD'),
('SLTH_BUILDING_THE_DRAGONS_HORDE', 'MODIFIER_SLTH_BUILDING_THE_DRAGONS_HORDE_GRANT_GEMS'),
('SLTH_BUILDING_THE_DRAGONS_HORDE', 'MODIFIER_SLTH_BUILDING_THE_DRAGONS_HORDE_MILITARY_EXPERIENCE'),
('SLTH_BUILDING_THE_DRAGONS_HORDE', 'MODIFIER_SLTH_BUILDING_THE_DRAGONS_HORDE_GRANT_GOLD'),
('SLTH_BUILDING_THE_NEXUS', 'MODIFIER_ALL_CITIES_FREE_SLTH_BUILDING_THE_NEXUS'),
('SLTH_BUILDING_THE_NEXUS', 'MODIFIER_FREE_SLTH_BUILDING_THE_NEXUS'),
('BUILDING_BIG_BEN', 'MODIFIER_BUILDING_BIG_BEN_MILITARY_PRODUCTION'),
('BUILDING_ORACLE', 'MODIFIER_BUILDING_ORACLE_FREE_TECH'),
('BUILDING_MONT_ST_MICHEL', 'MODIFIER_ALL_CITIES_FREE_BUILDING_MONT_ST_MICHEL'),
('BUILDING_MONT_ST_MICHEL', 'MODIFIER_FREE_BUILDING_MONT_ST_MICHEL'),
('BUILDING_MONT_ST_MICHEL', 'MODIFIER_BUILDING_MONT_ST_MICHEL_MILITARY_EXPERIENCE'),
('BUILDING_HUEY_TEOCALLI', 'MODIFIER_BUILDING_HUEY_TEOCALLI_GRANT_MANA_DEATH'),
('BUILDING_GRANARY', 'BREEDING_PIT_GROWTH_RATE'),
('SLTH_BUILDING_SMOKEHOUSE', 'BREEDING_PIT_GROWTH_RATE');


-- Reliquary grants Spirit Guide ability

INSERT INTO Modifiers(ModifierId, ModifierType, RunOnce, Permanent, SubjectRequirementSetId) VALUES
('MODIFIER_BUILDING_RESEARCH_LAB_ADD_SCIENCEYIELD', 'MODIFIER_SINGLE_CITY_ADJUST_CITY_YIELD_MODIFIER', '0', '0', NULL),
('MODIFIER_BUILDING_HANGING_GARDENS_ADJUST_HOUSING', 'MODIFIER_PLAYER_CITIES_ADJUST_POLICY_HOUSING', '0', '0', NULL),
('MODIFIER_SLTH_BUILDING_ASYLUM_ADJUST_WAR_WEARINESS', 'MODIFIER_PLAYER_ADJUST_WAR_WEARINESS', '0', '0', NULL),
('MODIFIER_SLTH_BUILDING_ASYLUM_ADD_SCIENCEYIELD', 'MODIFIER_SINGLE_CITY_ADJUST_CITY_YIELD_MODIFIER', '0', '0', NULL),
('MODIFIER_BUILDING_GRAND_BAZAAR_ADD_GOLDYIELD', 'MODIFIER_SINGLE_CITY_ADJUST_CITY_YIELD_MODIFIER', '0', '0', NULL),
('MODIFIER_BUILDING_PALGUM_GRANT_ALE', 'MODIFIER_FREE_RESOURCE_IN_CAPITAL', '0', '0', NULL),
('MODIFIER_SLTH_BUILDING_CARNIVAL_ADD_CULTUREYIELD', 'MODIFIER_SINGLE_CITY_ADJUST_CITY_YIELD_MODIFIER', '0', '0', NULL),
('MODIFIER_ALL_CITIES_FREE_BUILDING_PETRA', 'MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER', '0', '0', NULL),
('MODIFIER_FREE_BUILDING_PETRA', 'MODIFIER_SINGLE_CITY_GRANT_BUILDING_IN_CITY_IGNORE', '1', '1', NULL),
('MODIFIER_SLTH_BUILDING_CELESTIAL_COMPASS_PROJECT_PROD_MULT', 'MODIFIER_PLAYER_CITIES_ADJUST_ALL_PROJECTS_PRODUCTION', '0', '0', NULL),
('MODIFIER_MILITARY_EXPERIENCE_DOMAIN_DOMAIN_LAND', 'MODIFIER_CITY_TRAINED_UNITS_ADJUST_GRANT_EXPERIENCE', '0', '0', 'UNIT_IS_DOMAIN_LAND'),
('MODIFIER_SLTH_BUILDING_CROWN_OF_AKHARIEN_ADD_SCIENCEYIELD', 'MODIFIER_SINGLE_CITY_ADJUST_CITY_YIELD_MODIFIER', '0', '0', NULL),
('MODIFIER_SLTH_BUILDING_DEMONS_ALTAR_MILITARY_EXPERIENCE', 'MODIFIER_CITY_TRAINED_UNITS_ADJUST_GRANT_EXPERIENCE', '0', '0', NULL),
('MODIFIER_SLTH_BUILDING_DUNGEON_ADJUST_WAR_WEARINESS', 'MODIFIER_PLAYER_ADJUST_WAR_WEARINESS', '0', '0', NULL),
('MODIFIER_BUILDING_WORKSHOP_ADD_PRODUCTIONYIELD', 'MODIFIER_SINGLE_CITY_ADJUST_CITY_YIELD_MODIFIER', '0', '0', NULL),
('MODIFIER_ALL_CITIES_FREE_BUILDING_GREAT_ZIMBABWE', 'MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER', '0', '0', NULL),
('MODIFIER_FREE_BUILDING_GREAT_ZIMBABWE', 'MODIFIER_SINGLE_CITY_GRANT_BUILDING_IN_CITY_IGNORE', '1', '1', NULL),
('MODIFIER_BUILDING_GREAT_ZIMBABWE_ADD_AMENITIES', 'MODIFIER_ALL_CITY_ADJUST_ENTERTAINMENT', '0', '0', NULL),
('MODIFIER_BUILDING_GREAT_ZIMBABWE_ADD_CULTUREYIELD', 'MODIFIER_SINGLE_CITY_ADJUST_CITY_YIELD_MODIFIER', '0', '0', NULL),
('MODIFIER_BUILDING_GREAT_LIGHTHOUSE_ADJUST_TRADE_ROUTE_CAPACITY_COASTAL_PER_CITY', 'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_CAPACITY', '0', '0', 'PLOT_IS_ADJACENT_TO_COAST'),
('MODIFIER_BUILDING_GREAT_LIGHTHOUSE_ADJUST_TRADE_ROUTE_CAPACITY_COASTAL', 'MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER', '0', '0', NULL),
('MODIFIER_ALL_CITIES_FREE_SLTH_BUILDING_GUILD_OF_HAMMERS', 'MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER', '0', '0', NULL),
('MODIFIER_FREE_SLTH_BUILDING_GUILD_OF_HAMMERS', 'MODIFIER_SINGLE_CITY_GRANT_BUILDING_IN_CITY_IGNORE', '1', '1', NULL),
('MODIFIER_BUILDING_HALICARNASSUS_MAUSOLEUM_PLOT_YIELD_CHANGE_PRODUCTION', 'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD', '0', '0', 'PLOT_HAS_COAST_REQUIREMENTS'),
('MODIFIER_SLTH_BUILDING_HARBOR_TRADE_ROUTE_YIELD_MULT', 'trade_route_modifier', '0', '0', NULL),
('MODIFIER_SLTH_BUILDING_HEROIC_EPIC_MILITARY_PRODUCTION', 'MODIFIER_PLAYER_CITIES_ADJUST_MILITARY_UNITS_PRODUCTION', '0', '0', NULL),
('MODIFIER_SLTH_BUILDING_INFERNAL_GRIMOIRE_FREE_TECH', 'MODIFIER_PLAYER_GRANT_RANDOM_TECHNOLOGY', '1', '1', NULL),
('MODIFIER_SLTH_BUILDING_INN_ADJUST_TRADE_ROUTE_CAPACITY', 'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_CAPACITY', '0', '0', NULL),
('MODIFIER_SLTH_BUILDING_INN_TRADE_ROUTE_YIELD_MULT', 'trade_route_modifier', '0', '0', NULL),
('MODIFIER_BUILDING_LIBRARY_ADD_SCIENCEYIELD', 'MODIFIER_SINGLE_CITY_ADJUST_CITY_YIELD_MODIFIER', '0', '0', NULL),
('MODIFIER_BUILDING_LIGHTHOUSE_ADJUST_TRADE_ROUTE_CAPACITY', 'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_CAPACITY', '0', '0', NULL),
('MODIFIER_BUILDING_LIGHTHOUSE_PLOT_YIELD_CHANGE_FOOD', 'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD', '0', '0', 'PLOT_HAS_COAST_REQUIREMENTS'),
('MODIFIER_BUILDING_JEBEL_BARKAL_GRANT_IRON', 'MODIFIER_FREE_RESOURCE_EXTRACTION_IN_CAPITAL', '0', '0', NULL),
('MODIFIER_BUILDING_BANK_ADD_GOLDYIELD', 'MODIFIER_SINGLE_CITY_ADJUST_CITY_YIELD_MODIFIER', '0', '0', NULL),
('MODIFIER_NATIONAL_EPIC_INCREASE_GPP_MULT', 'MODIFIER_CITY_INCREASE_GREAT_PERSON_POINT_BONUS', '0', '0', NULL),
('MODIFIER_SLTH_BUILDING_OBSIDIAN_GATE_ADJUST_TRADE_ROUTE_CAPACITY', 'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_CAPACITY', '0', '0', NULL),
('MODIFIER_BUILDING_SHRINE_ADD_CULTUREYIELD', 'MODIFIER_SINGLE_CITY_ADJUST_CITY_YIELD_MODIFIER', '0', '0', NULL),
('MODIFIER_BUILDING_CHICHEN_ITZA_ADJUST_WAR_WEARINESS', 'MODIFIER_PLAYER_ADJUST_WAR_WEARINESS', '0', '0', NULL),
('MODIFIER_BUILDING_ETEMENANKI_MILITARY_EXPERIENCE', 'MODIFIER_CITY_TRAINED_UNITS_ADJUST_GRANT_EXPERIENCE', '0', '0', NULL),
('MODIFIER_BUILDING_SHIPYARD_DOMAIN_SEA_PROD_MULT', 'MODIFIER_CITY_ADJUST_UNIT_DOMAIN_PRODUCTION', '0', '0', NULL),
('MODIFIER_BUILDING_KOTOKU_IN_MILITARY_EXPERIENCE', 'MODIFIER_CITY_TRAINED_UNITS_ADJUST_GRANT_EXPERIENCE', '0', '0', NULL),
('MODIFIER_SLTH_BUILDING_SMUGGLERS_PORT_ADJUST_TRADE_ROUTE_CAPACITY', 'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_CAPACITY', '0', '0', NULL),
('MODIFIER_SLTH_BUILDING_SMUGGLERS_PORT_ADD_GOLDYIELD', 'MODIFIER_SINGLE_CITY_ADJUST_CITY_YIELD_MODIFIER', '0', '0', NULL),
('MODIFIER_SLTH_BUILDING_SOUL_FORGE_GRANT_MANA_DEATH', 'MODIFIER_FREE_RESOURCE_IN_CAPITAL', '0', '0', NULL),
('MODIFIER_SLTH_BUILDING_SPIDER_PEN_GRANT_SILK', 'MODIFIER_FREE_RESOURCE_IN_CAPITAL', '0', '0', NULL),
('MODIFIER_SLTH_BUILDING_SYLIVENS_PERFECT_LYRE_ADD_CULTUREYIELD', 'MODIFIER_SINGLE_CITY_ADJUST_CITY_YIELD_MODIFIER', '0', '0', NULL),
('MODIFIER_SLTH_BUILDING_TAVERN_ADJUST_TRADE_ROUTE_CAPACITY', 'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_CAPACITY', '0', '0', NULL),
('MODIFIER_SLTH_BUILDING_TAVERN_TRADE_ROUTE_YIELD_MULT', 'trade_route_modifier', '0', '0', NULL),
('MODIFIER_BUILDING_GILDED_VAULT_ADD_GOLDYIELD', 'MODIFIER_SINGLE_CITY_ADJUST_CITY_YIELD_MODIFIER', '0', '0', NULL),
('MODIFIER_BUILDING_WAT_ADD_CULTUREYIELD', 'MODIFIER_SINGLE_CITY_ADJUST_CITY_YIELD_MODIFIER', '0', '0', NULL),
('MODIFIER_BUILDING_SANCTUARY_ADD_CULTUREYIELD', 'MODIFIER_SINGLE_CITY_ADJUST_CITY_YIELD_MODIFIER', '0', '0', NULL),
('MODIFIER_BUILDING_GURDWARA_ADD_SCIENCEYIELD', 'MODIFIER_SINGLE_CITY_ADJUST_CITY_YIELD_MODIFIER', '0', '0', NULL),
('MODIFIER_BUILDING_CATHEDRAL_MILITARY_PRODUCTION', 'MODIFIER_PLAYER_CITIES_ADJUST_MILITARY_UNITS_PRODUCTION', '0', '0', NULL),
('MODIFIER_BUILDING_CATHEDRAL_ADD_CULTUREYIELD', 'MODIFIER_SINGLE_CITY_ADJUST_CITY_YIELD_MODIFIER', '0', '0', NULL),
('MODIFIER_BUILDING_MOSQUE_ADD_CULTUREYIELD', 'MODIFIER_SINGLE_CITY_ADJUST_CITY_YIELD_MODIFIER', '0', '0', NULL),
('MODIFIER_BUILDING_STUPA_ADD_CULTUREYIELD', 'MODIFIER_SINGLE_CITY_ADJUST_CITY_YIELD_MODIFIER', '0', '0', NULL),
('MODIFIER_SLTH_BUILDING_THE_DRAGONS_HORDE_GRANT_GEMS', 'MODIFIER_FREE_RESOURCE_IN_CAPITAL', '0', '0', NULL),
('MODIFIER_SLTH_BUILDING_THE_DRAGONS_HORDE_MILITARY_EXPERIENCE', 'MODIFIER_CITY_TRAINED_UNITS_ADJUST_GRANT_EXPERIENCE', '0', '0', NULL),
('MODIFIER_SLTH_BUILDING_THE_DRAGONS_HORDE_GRANT_GOLD', 'MODIFIER_FREE_RESOURCE_IN_CAPITAL', '0', '0', NULL),
('MODIFIER_ALL_CITIES_FREE_SLTH_BUILDING_THE_NEXUS', 'MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER', '0', '0', NULL),
('MODIFIER_FREE_SLTH_BUILDING_THE_NEXUS', 'MODIFIER_SINGLE_CITY_GRANT_BUILDING_IN_CITY_IGNORE', '1', '1', NULL),
('MODIFIER_BUILDING_BIG_BEN_MILITARY_PRODUCTION', 'MODIFIER_PLAYER_CITIES_ADJUST_MILITARY_UNITS_PRODUCTION', '0', '0', NULL),
('MODIFIER_ALL_CITIES_FREE_BUILDING_MONT_ST_MICHEL', 'MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER', '0', '0', NULL),
('MODIFIER_FREE_BUILDING_MONT_ST_MICHEL', 'MODIFIER_SINGLE_CITY_GRANT_BUILDING_IN_CITY_IGNORE', '1', '1', NULL),
('MODIFIER_BUILDING_MONT_ST_MICHEL_MILITARY_EXPERIENCE', 'MODIFIER_CITY_TRAINED_UNITS_ADJUST_GRANT_EXPERIENCE', '0', '0', NULL);
INSERT INTO ModifierArguments(ModifierId, Name, Type, Value) VALUES
('MODIFIER_BUILDING_RESEARCH_LAB_ADD_SCIENCEYIELD', 'Amount', 'ARGTYPE_IDENTITY', '10'),
('MODIFIER_BUILDING_RESEARCH_LAB_ADD_SCIENCEYIELD', 'YieldType', 'ARGTYPE_IDENTITY', 'YIELD_SCIENCE'),
('MODIFIER_BUILDING_HANGING_GARDENS_ADJUST_HOUSING', 'Amount', 'ARGTYPE_IDENTITY', '1'),
('MODIFIER_SLTH_BUILDING_ASYLUM_ADJUST_WAR_WEARINESS', 'Amount', 'ARGTYPE_IDENTITY', '-25'),
('MODIFIER_SLTH_BUILDING_ASYLUM_ADJUST_WAR_WEARINESS', 'Overall', 'ARGTYPE_IDENTITY', '1'),
('MODIFIER_SLTH_BUILDING_ASYLUM_ADD_SCIENCEYIELD', 'Amount', 'ARGTYPE_IDENTITY', '15'),
('MODIFIER_SLTH_BUILDING_ASYLUM_ADD_SCIENCEYIELD', 'YieldType', 'ARGTYPE_IDENTITY', 'YIELD_SCIENCE'),
('MODIFIER_BUILDING_GRAND_BAZAAR_ADD_GOLDYIELD', 'Amount', 'ARGTYPE_IDENTITY', '100'),
('MODIFIER_BUILDING_GRAND_BAZAAR_ADD_GOLDYIELD', 'YieldType', 'ARGTYPE_IDENTITY', 'YIELD_GOLD'),
('MODIFIER_BUILDING_PALGUM_GRANT_ALE', 'Amount', 'ARGTYPE_IDENTITY', '2'),
('MODIFIER_BUILDING_PALGUM_GRANT_ALE', 'ResourceType', 'ARGTYPE_IDENTITY', 'RESOURCE_ALE'),
('MODIFIER_SLTH_BUILDING_CARNIVAL_ADD_CULTUREYIELD', 'Amount', 'ARGTYPE_IDENTITY', '20'),
('MODIFIER_SLTH_BUILDING_CARNIVAL_ADD_CULTUREYIELD', 'YieldType', 'ARGTYPE_IDENTITY', 'YIELD_CULTURE'),
('MODIFIER_ALL_CITIES_FREE_BUILDING_PETRA', 'ModifierId', 'ARGTYPE_IDENTITY', 'MODIFIER_FREE_BUILDING_PETRA'),
('MODIFIER_FREE_BUILDING_PETRA', 'BuildingType', 'ARGTYPE_IDENTITY', 'BUILDING_MAGE_GUILD'),
('MODIFIER_SLTH_BUILDING_CELESTIAL_COMPASS_PROJECT_PROD_MULT', 'Amount', 'ARGTYPE_IDENTITY', '50'),
('MODIFIER_MILITARY_EXPERIENCE_DOMAIN_DOMAIN_LAND', 'Amount', 'ARGTYPE_IDENTITY', '-1'),
('MODIFIER_SLTH_BUILDING_CROWN_OF_AKHARIEN_ADD_SCIENCEYIELD', 'Amount', 'ARGTYPE_IDENTITY', '100'),
('MODIFIER_SLTH_BUILDING_CROWN_OF_AKHARIEN_ADD_SCIENCEYIELD', 'YieldType', 'ARGTYPE_IDENTITY', 'YIELD_SCIENCE'),
('MODIFIER_SLTH_BUILDING_DEMONS_ALTAR_MILITARY_EXPERIENCE', 'Amount', 'ARGTYPE_IDENTITY', '-1'),
('MODIFIER_SLTH_BUILDING_DUNGEON_ADJUST_WAR_WEARINESS', 'Amount', 'ARGTYPE_IDENTITY', '-25'),
('MODIFIER_SLTH_BUILDING_DUNGEON_ADJUST_WAR_WEARINESS', 'Overall', 'ARGTYPE_IDENTITY', '1'),
('MODIFIER_BUILDING_WORKSHOP_ADD_PRODUCTIONYIELD', 'Amount', 'ARGTYPE_IDENTITY', '25'),
('MODIFIER_BUILDING_WORKSHOP_ADD_PRODUCTIONYIELD', 'YieldType', 'ARGTYPE_IDENTITY', 'YIELD_PRODUCTION'),
('MODIFIER_ALL_CITIES_FREE_BUILDING_GREAT_ZIMBABWE', 'ModifierId', 'ARGTYPE_IDENTITY', 'MODIFIER_FREE_BUILDING_GREAT_ZIMBABWE'),
('MODIFIER_FREE_BUILDING_GREAT_ZIMBABWE', 'BuildingType', 'ARGTYPE_IDENTITY', 'SLTH_BUILDING_CARNIVAL'),
('MODIFIER_BUILDING_GREAT_ZIMBABWE_ADD_AMENITIES', 'BUILDING_GREAT_ZIMBABWE', 'ARGTYPE_IDENTITY', '2'),
('MODIFIER_BUILDING_GREAT_ZIMBABWE_ADD_CULTUREYIELD', 'Amount', 'ARGTYPE_IDENTITY', '20'),
('MODIFIER_BUILDING_GREAT_ZIMBABWE_ADD_CULTUREYIELD', 'YieldType', 'ARGTYPE_IDENTITY', 'YIELD_CULTURE'),
('MODIFIER_BUILDING_GREAT_LIGHTHOUSE_ADJUST_TRADE_ROUTE_CAPACITY_COASTAL_PER_CITY', 'Amount', 'ARGTYPE_IDENTITY', '2'),
('MODIFIER_BUILDING_GREAT_LIGHTHOUSE_ADJUST_TRADE_ROUTE_CAPACITY_COASTAL', 'ModifierId', 'ARGTYPE_IDENTITY', 'MODIFIER_BUILDING_GREAT_LIGHTHOUSE_ADJUST_TRADE_ROUTE_CAPACITY_COASTAL_PER_CITY'),
('MODIFIER_ALL_CITIES_FREE_SLTH_BUILDING_GUILD_OF_HAMMERS', 'ModifierId', 'ARGTYPE_IDENTITY', 'MODIFIER_FREE_SLTH_BUILDING_GUILD_OF_HAMMERS'),
('MODIFIER_FREE_SLTH_BUILDING_GUILD_OF_HAMMERS', 'BuildingType', 'ARGTYPE_IDENTITY', 'BUILDING_WORKSHOP'),
('MODIFIER_BUILDING_HALICARNASSUS_MAUSOLEUM_PLOT_YIELD_CHANGE_PRODUCTION', 'YieldType', 'ARGTYPE_IDENTITY', 'YIELD_PRODUCTION'),
('MODIFIER_BUILDING_HALICARNASSUS_MAUSOLEUM_PLOT_YIELD_CHANGE_PRODUCTION', 'Amount', 'ARGTYPE_IDENTITY', '1'),
('MODIFIER_SLTH_BUILDING_HARBOR_TRADE_ROUTE_YIELD_MULT', 'YIELD_PRODUCTION, YIELD_FOOD, YIELD_SCIENCE, YIELD_CULTURE, YIELD_GOLD, YIELD_FAITH', 'YieldType', 'YIELD_PRODUCTION, YIELD_FOOD, YIELD_SCIENCE, YIELD_CULTURE, YIELD_GOLD, YIELD_FAITH'),
('MODIFIER_SLTH_BUILDING_HARBOR_TRADE_ROUTE_YIELD_MULT', '50, 50, 50, 50, 50, 50', 'Amount', '50, 50, 50, 50, 50, 50'),
('MODIFIER_SLTH_BUILDING_HEROIC_EPIC_MILITARY_PRODUCTION', 'Amount', 'ARGTYPE_IDENTITY', '100'),
('MODIFIER_SLTH_BUILDING_INFERNAL_GRIMOIRE_FREE_TECH', 'Amount', 'ARGTYPE_IDENTITY', '1'),
('MODIFIER_SLTH_BUILDING_INN_ADJUST_TRADE_ROUTE_CAPACITY', 'Amount', 'ARGTYPE_IDENTITY', '1'),
('MODIFIER_SLTH_BUILDING_INN_TRADE_ROUTE_YIELD_MULT', 'YIELD_PRODUCTION, YIELD_FOOD, YIELD_SCIENCE, YIELD_CULTURE, YIELD_GOLD, YIELD_FAITH', 'YieldType', 'YIELD_PRODUCTION, YIELD_FOOD, YIELD_SCIENCE, YIELD_CULTURE, YIELD_GOLD, YIELD_FAITH'),
('MODIFIER_SLTH_BUILDING_INN_TRADE_ROUTE_YIELD_MULT', '25, 25, 25, 25, 25, 25', 'Amount', '25, 25, 25, 25, 25, 25'),
('MODIFIER_BUILDING_LIBRARY_ADD_SCIENCEYIELD', 'Amount', 'ARGTYPE_IDENTITY', '25'),
('MODIFIER_BUILDING_LIBRARY_ADD_SCIENCEYIELD', 'YieldType', 'ARGTYPE_IDENTITY', 'YIELD_SCIENCE'),
('MODIFIER_BUILDING_LIGHTHOUSE_ADJUST_TRADE_ROUTE_CAPACITY', 'Amount', 'ARGTYPE_IDENTITY', '1'),
('MODIFIER_BUILDING_LIGHTHOUSE_PLOT_YIELD_CHANGE_FOOD', 'YieldType', 'ARGTYPE_IDENTITY', 'YIELD_FOOD'),
('MODIFIER_BUILDING_LIGHTHOUSE_PLOT_YIELD_CHANGE_FOOD', 'Amount', 'ARGTYPE_IDENTITY', '1'),
('MODIFIER_BUILDING_JEBEL_BARKAL_GRANT_IRON', 'Amount', 'ARGTYPE_IDENTITY', '3'),
('MODIFIER_BUILDING_JEBEL_BARKAL_GRANT_IRON', 'ResourceType', 'ARGTYPE_IDENTITY', 'RESOURCE_IRON'),
('MODIFIER_BUILDING_BANK_ADD_GOLDYIELD', 'Amount', 'ARGTYPE_IDENTITY', '25'),
('MODIFIER_BUILDING_BANK_ADD_GOLDYIELD', 'YieldType', 'ARGTYPE_IDENTITY', 'YIELD_GOLD'),
('MODIFIER_NATIONAL_EPIC_INCREASE_GPP_MULT', 'Amount', 'ARGTYPE_IDENTITY', '100'),
('MODIFIER_SLTH_BUILDING_OBSIDIAN_GATE_ADJUST_TRADE_ROUTE_CAPACITY', 'Amount', 'ARGTYPE_IDENTITY', '1'),
('MODIFIER_BUILDING_SHRINE_ADD_CULTUREYIELD', 'Amount', 'ARGTYPE_IDENTITY', '10'),
('MODIFIER_BUILDING_SHRINE_ADD_CULTUREYIELD', 'YieldType', 'ARGTYPE_IDENTITY', 'YIELD_CULTURE'),
('MODIFIER_BUILDING_CHICHEN_ITZA_ADJUST_WAR_WEARINESS', 'Amount', 'ARGTYPE_IDENTITY', '-10'),
('MODIFIER_BUILDING_CHICHEN_ITZA_ADJUST_WAR_WEARINESS', 'Overall', 'ARGTYPE_IDENTITY', '1'),
('MODIFIER_BUILDING_ETEMENANKI_MILITARY_EXPERIENCE', 'Amount', 'ARGTYPE_IDENTITY', '-1'),
('MODIFIER_BUILDING_SHIPYARD_DOMAIN_SEA_PROD_MULT', 'Domain', 'ARGTYPE_IDENTITY', 'DOMAIN_SEA'),
('MODIFIER_BUILDING_SHIPYARD_DOMAIN_SEA_PROD_MULT', 'Amount', 'ARGTYPE_IDENTITY', '25'),
('MODIFIER_BUILDING_KOTOKU_IN_MILITARY_EXPERIENCE', 'Amount', 'ARGTYPE_IDENTITY', '-1'),
('MODIFIER_SLTH_BUILDING_SMUGGLERS_PORT_ADJUST_TRADE_ROUTE_CAPACITY', 'Amount', 'ARGTYPE_IDENTITY', '1'),
('MODIFIER_SLTH_BUILDING_SMUGGLERS_PORT_ADD_GOLDYIELD', 'Amount', 'ARGTYPE_IDENTITY', '25'),
('MODIFIER_SLTH_BUILDING_SMUGGLERS_PORT_ADD_GOLDYIELD', 'YieldType', 'ARGTYPE_IDENTITY', 'YIELD_GOLD'),
('MODIFIER_SLTH_BUILDING_SOUL_FORGE_GRANT_MANA_DEATH', 'Amount', 'ARGTYPE_IDENTITY', '1'),
('MODIFIER_SLTH_BUILDING_SOUL_FORGE_GRANT_MANA_DEATH', 'ResourceType', 'ARGTYPE_IDENTITY', 'RESOURCE_MANA_DEATH'),
('MODIFIER_SLTH_BUILDING_SPIDER_PEN_GRANT_SILK', 'Amount', 'ARGTYPE_IDENTITY', '1'),
('MODIFIER_SLTH_BUILDING_SPIDER_PEN_GRANT_SILK', 'ResourceType', 'ARGTYPE_IDENTITY', 'RESOURCE_SILK'),
('MODIFIER_SLTH_BUILDING_SYLIVENS_PERFECT_LYRE_ADD_CULTUREYIELD', 'Amount', 'ARGTYPE_IDENTITY', '100'),
('MODIFIER_SLTH_BUILDING_SYLIVENS_PERFECT_LYRE_ADD_CULTUREYIELD', 'YieldType', 'ARGTYPE_IDENTITY', 'YIELD_CULTURE'),
('MODIFIER_SLTH_BUILDING_TAVERN_ADJUST_TRADE_ROUTE_CAPACITY', 'Amount', 'ARGTYPE_IDENTITY', '1'),
('MODIFIER_SLTH_BUILDING_TAVERN_TRADE_ROUTE_YIELD_MULT', 'YIELD_PRODUCTION, YIELD_FOOD, YIELD_SCIENCE, YIELD_CULTURE, YIELD_GOLD, YIELD_FAITH', 'YieldType', 'YIELD_PRODUCTION, YIELD_FOOD, YIELD_SCIENCE, YIELD_CULTURE, YIELD_GOLD, YIELD_FAITH'),
('MODIFIER_SLTH_BUILDING_TAVERN_TRADE_ROUTE_YIELD_MULT', '25, 25, 25, 25, 25, 25', 'Amount', '25, 25, 25, 25, 25, 25'),
('MODIFIER_BUILDING_GILDED_VAULT_ADD_GOLDYIELD', 'Amount', 'ARGTYPE_IDENTITY', '25'),
('MODIFIER_BUILDING_GILDED_VAULT_ADD_GOLDYIELD', 'YieldType', 'ARGTYPE_IDENTITY', 'YIELD_GOLD'),
('MODIFIER_BUILDING_WAT_ADD_CULTUREYIELD', 'Amount', 'ARGTYPE_IDENTITY', '20'),
('MODIFIER_BUILDING_WAT_ADD_CULTUREYIELD', 'YieldType', 'ARGTYPE_IDENTITY', 'YIELD_CULTURE'),
('MODIFIER_BUILDING_SANCTUARY_ADD_CULTUREYIELD', 'Amount', 'ARGTYPE_IDENTITY', '20'),
('MODIFIER_BUILDING_SANCTUARY_ADD_CULTUREYIELD', 'YieldType', 'ARGTYPE_IDENTITY', 'YIELD_CULTURE'),
('MODIFIER_BUILDING_GURDWARA_ADD_SCIENCEYIELD', 'Amount', 'ARGTYPE_IDENTITY', '10'),
('MODIFIER_BUILDING_GURDWARA_ADD_SCIENCEYIELD', 'YieldType', 'ARGTYPE_IDENTITY', 'YIELD_SCIENCE'),
('MODIFIER_BUILDING_CATHEDRAL_MILITARY_PRODUCTION', 'Amount', 'ARGTYPE_IDENTITY', '10'),
('MODIFIER_BUILDING_CATHEDRAL_ADD_CULTUREYIELD', 'Amount', 'ARGTYPE_IDENTITY', '20'),
('MODIFIER_BUILDING_CATHEDRAL_ADD_CULTUREYIELD', 'YieldType', 'ARGTYPE_IDENTITY', 'YIELD_CULTURE'),
('MODIFIER_BUILDING_MOSQUE_ADD_CULTUREYIELD', 'Amount', 'ARGTYPE_IDENTITY', '20'),
('MODIFIER_BUILDING_MOSQUE_ADD_CULTUREYIELD', 'YieldType', 'ARGTYPE_IDENTITY', 'YIELD_CULTURE'),
('MODIFIER_BUILDING_STUPA_ADD_CULTUREYIELD', 'Amount', 'ARGTYPE_IDENTITY', '20'),
('MODIFIER_BUILDING_STUPA_ADD_CULTUREYIELD', 'YieldType', 'ARGTYPE_IDENTITY', 'YIELD_CULTURE'),
('MODIFIER_SLTH_BUILDING_THE_DRAGONS_HORDE_GRANT_GEMS', 'Amount', 'ARGTYPE_IDENTITY', '1'),
('MODIFIER_SLTH_BUILDING_THE_DRAGONS_HORDE_GRANT_GEMS', 'ResourceType', 'ARGTYPE_IDENTITY', 'RESOURCE_DIAMONDS'),
('MODIFIER_SLTH_BUILDING_THE_DRAGONS_HORDE_MILITARY_EXPERIENCE', 'Amount', 'ARGTYPE_IDENTITY', '-1'),
('MODIFIER_SLTH_BUILDING_THE_DRAGONS_HORDE_GRANT_GOLD', 'Amount', 'ARGTYPE_IDENTITY', '1'),
('MODIFIER_SLTH_BUILDING_THE_DRAGONS_HORDE_GRANT_GOLD', 'ResourceType', 'ARGTYPE_IDENTITY', 'RESOURCE_GOLD'),
('MODIFIER_ALL_CITIES_FREE_SLTH_BUILDING_THE_NEXUS', 'ModifierId', 'ARGTYPE_IDENTITY', 'MODIFIER_FREE_SLTH_BUILDING_THE_NEXUS'),
('MODIFIER_FREE_SLTH_BUILDING_THE_NEXUS', 'BuildingType', 'ARGTYPE_IDENTITY', 'SLTH_BUILDING_OBSIDIAN_GATE'),
('MODIFIER_BUILDING_BIG_BEN_MILITARY_PRODUCTION', 'Amount', 'ARGTYPE_IDENTITY', '-10'),
('MODIFIER_ALL_CITIES_FREE_BUILDING_MONT_ST_MICHEL', 'ModifierId', 'ARGTYPE_IDENTITY', 'MODIFIER_FREE_BUILDING_MONT_ST_MICHEL'),
('MODIFIER_FREE_BUILDING_MONT_ST_MICHEL', 'BuildingType', 'ARGTYPE_IDENTITY', 'SLTH_BUILDING_DUNGEON'),
('MODIFIER_BUILDING_MONT_ST_MICHEL_MILITARY_EXPERIENCE', 'Amount', 'ARGTYPE_IDENTITY', '-1');

-- ability granters

INSERT INTO Modifiers(ModifierId, ModifierType, RunOnce, Permanent) VALUES
('GRANT_EXPERIENCE_SMALL', 'MODIFIER_PLAYER_UNIT_ADJUST_GRANT_EXPERIENCE', '1', '1'),
('GRANT_EXPERIENCE_MEDIUM', 'MODIFIER_PLAYER_UNIT_ADJUST_GRANT_EXPERIENCE', '1', '1'),
('GRANT_EXPERIENCE_HUGE', 'MODIFIER_PLAYER_UNIT_ADJUST_GRANT_EXPERIENCE', '1', '1');

INSERT INTO ModifierArguments(ModifierId, Name, Type, Value) VALUES
('GRANT_EXPERIENCE_SMALL', 'Amount', 'ARGTYPE_IDENTITY', '16'),
('GRANT_EXPERIENCE_MEDIUM', 'Amount', 'ARGTYPE_IDENTITY', '33'),
('GRANT_EXPERIENCE_HUGE', 'Amount', 'ARGTYPE_IDENTITY', '41');

INSERT INTO Modifiers(ModifierId, ModifierType, RunOnce, Permanent, SubjectRequirementSetId) VALUES
('GRANT_EXPERIENCE_ABILITY_SMALL_TITAN', 'MODIFIER_SINGLE_CITY_GRANT_ABILITY_FOR_TRAINED_UNITS', '0', '0', NULL),
('GRANT_EXPERIENCE_ABILITY_SMALL_SHIPYARD_NAVAL', 'MODIFIER_SINGLE_CITY_GRANT_ABILITY_FOR_TRAINED_UNITS', '0', '0', NULL),
('GRANT_EXPERIENCE_ABILITY_SMALL_RIDE_OF_KINGS_CAV', 'MODIFIER_SINGLE_CITY_GRANT_ABILITY_FOR_TRAINED_UNITS', '0', '0', NULL);


INSERT INTO ModifierArguments(ModifierId, Name, Type, Value) VALUES
('GRANT_EXPERIENCE_ABILITY_SMALL_TITAN', 'AbilityType', 'ARGTYPE_IDENTITY', 'GRANT_EXPERIENCE_SMALL_ABILITY_TITAN'),
('GRANT_EXPERIENCE_ABILITY_SMALL_SHIPYARD_NAVAL', 'AbilityType', 'ARGTYPE_IDENTITY', 'GRANT_EXPERIENCE_SMALL_ABILITY_SHIPYARD_NAVAL'),
('GRANT_EXPERIENCE_ABILITY_SMALL_RIDE_OF_KINGS_CAV', 'AbilityType', 'ARGTYPE_IDENTITY', 'GRANT_EXPERIENCE_SMALL_ABILITY_RIDE_OF_KINGS_CAV');


INSERT INTO UnitAbilities(UnitAbilityType, Name, Description, Inactive, Permanent) VALUES
('GRANT_EXPERIENCE_SMALL_ABILITY_TITAN', 'LOC_GRANT_EXPERIENCE_ABILITY_NAME', 'LOC_NULL', '1', '1'),
('GRANT_EXPERIENCE_SMALL_ABILITY_SHIPYARD_NAVAL', 'LOC_GRANT_EXPERIENCE_ABILITY_NAME', 'LOC_NULL', '1', '1'),
('GRANT_EXPERIENCE_SMALL_ABILITY_RIDE_OF_KINGS_CAV', 'LOC_GRANT_EXPERIENCE_ABILITY_NAME', 'LOC_NULL', '1', '1');


INSERT INTO UnitAbilityModifiers(UnitAbilityType, ModifierId) VALUES
('GRANT_EXPERIENCE_SMALL_ABILITY_TITAN', 'GRANT_EXPERIENCE_SMALL'),
('GRANT_EXPERIENCE_SMALL_ABILITY_SHIPYARD_NAVAL', 'GRANT_EXPERIENCE_MEDIUM'),
('GRANT_EXPERIENCE_SMALL_ABILITY_RIDE_OF_KINGS_CAV', 'GRANT_EXPERIENCE_HUGE');


INSERT INTO TypeTags(Type, Tag) VALUES
('GRANT_EXPERIENCE_SMALL_ABILITY_TITAN', 'CLASS_ALL_UNITS'),
('GRANT_EXPERIENCE_SMALL_ABILITY_SHIPYARD_NAVAL', 'CLASS_NAVAL_MELEE'),
('GRANT_EXPERIENCE_SMALL_ABILITY_RIDE_OF_KINGS_CAV', 'CLASS_LIGHT_CAVALRY');


INSERT INTO Types(Type, Kind) VALUES
('GRANT_EXPERIENCE_SMALL_ABILITY_TITAN', 'KIND_ABILITY'),
('GRANT_EXPERIENCE_SMALL_ABILITY_SHIPYARD_NAVAL', 'KIND_ABILITY'),
('GRANT_EXPERIENCE_SMALL_ABILITY_RIDE_OF_KINGS_CAV', 'KIND_ABILITY');


INSERT INTO Types(Type, Kind) VALUES
('SLTH_BUILDING_AQUEDUCT', 'KIND_BUILDING'),
('SLTH_BUILDING_ARCHERY_RANGE', 'KIND_BUILDING'),
('SLTH_BUILDING_ASYLUM', 'KIND_BUILDING'),
('SLTH_BUILDING_CARNIVAL', 'KIND_BUILDING'),
('SLTH_BUILDING_CELESTIAL_COMPASS', 'KIND_BUILDING'),
('SLTH_BUILDING_CROWN_OF_AKHARIEN', 'KIND_BUILDING'),
('SLTH_BUILDING_DANCING_BEAR', 'KIND_BUILDING'),
('SLTH_BUILDING_DUNGEON', 'KIND_BUILDING'),
('SLTH_BUILDING_ELDER_COUNCIL', 'KIND_BUILDING'),
('SLTH_BUILDING_GAMBLING_HOUSE', 'KIND_BUILDING'),
('SLTH_BUILDING_GORILLA_CAGE', 'KIND_BUILDING'),
('SLTH_BUILDING_GUILD_OF_HAMMERS', 'KIND_BUILDING'),
('SLTH_BUILDING_HARBOR', 'KIND_BUILDING'),
('SLTH_BUILDING_HEROIC_EPIC', 'KIND_BUILDING'),
('BUILDING_MAGE_GUILD', 'KIND_BUILDING'),
('SLTH_BUILDING_INFERNAL_GRIMOIRE', 'KIND_BUILDING'),
('SLTH_BUILDING_LION_CAGE', 'KIND_BUILDING'),
('SLTH_BUILDING_MOKKAS_CAULDRON', 'KIND_BUILDING'),
('SLTH_BUILDING_NATIONAL_EPIC', 'KIND_BUILDING'),
('SLTH_BUILDING_OBSIDIAN_GATE', 'KIND_BUILDING'),
('SLTH_BUILDING_PUBLIC_BATHS', 'KIND_BUILDING'),
('SLTH_BUILDING_RIDE_OF_THE_NINE_KINGS', 'KIND_BUILDING'),
('SLTH_BUILDING_SIEGE_WORKSHOP', 'KIND_BUILDING'),
('SLTH_BUILDING_SMOKEHOUSE', 'KIND_BUILDING'),
('SLTH_BUILDING_SMUGGLERS_PORT', 'KIND_BUILDING'),
('SLTH_BUILDING_SOUL_FORGE', 'KIND_BUILDING'),
('SLTH_BUILDING_SPIDER_PEN', 'KIND_BUILDING'),
('SLTH_BUILDING_SYLIVENS_PERFECT_LYRE', 'KIND_BUILDING'),
('SLTH_BUILDING_TAVERN', 'KIND_BUILDING'),
('SLTH_BUILDING_THE_DRAGONS_HORDE', 'KIND_BUILDING'),
('SLTH_BUILDING_THE_NEXUS', 'KIND_BUILDING'),
('SLTH_BUILDING_TIGER_CAGE', 'KIND_BUILDING'),
('SLTH_BUILDING_WOLF_PEN', 'KIND_BUILDING'),
('SLTH_BUILDING_INFIRMARY', 'KIND_BUILDING'),
('SLTH_BUILDING_INN', 'KIND_BUILDING'),
('SLTH_BUILDING_CHANCEL', 'KIND_BUILDING'),
('SLTH_BUILDING_HUNTING_LODGE', 'KIND_BUILDING'),
('SLTH_BUILDING_NULL_CIVILIZATION_KURIOTATES_STABLE', 'KIND_BUILDING'),
('SLTH_BUILDING_NULL_CIVILIZATION_HIPPUS_ALCHEMY_LAB', 'KIND_BUILDING'),
('SLTH_BUILDING_NULL_CIVILIZATION_DOVIELLO_ALCHEMY_LAB', 'KIND_BUILDING'),
('SLTH_BUILDING_NULL_CIVILIZATION_DOVIELLO_LIBRARY', 'KIND_BUILDING'),
('SLTH_BUILDING_NULL_CIVILIZATION_DOVIELLO_MAGE_GUILD', 'KIND_BUILDING'),
('SLTH_BUILDING_NULL_CIVILIZATION_CLAN_OF_EMBERS_ALCHEMY_LAB', 'KIND_BUILDING'),
('SLTH_BUILDING_NULL_CIVILIZATION_CLAN_OF_EMBERS_LIBRARY', 'KIND_BUILDING'),
('SLTH_BUILDING_NULL_CIVILIZATION_CLAN_OF_EMBERS_MAGE_GUILD', 'KIND_BUILDING'),
('SLTH_BUILDING_NULL_CIVILIZATION_CLAN_OF_EMBERS_STABLE', 'KIND_BUILDING'),
('SLTH_BUILDING_NULL_CIVILIZATION_CALABIM_ALCHEMY_LAB', 'KIND_BUILDING'),
('SLTH_BUILDING_NULL_CIVILIZATION_CALABIM_ELDER_COUNCIL', 'KIND_BUILDING'),
('SLTH_BUILDING_NULL_CIVILIZATION_INFERNAL_AQUEDUCT', 'KIND_BUILDING'),
('SLTH_BUILDING_NULL_CIVILIZATION_INFERNAL_GRANARY', 'KIND_BUILDING'),
('SLTH_BUILDING_NULL_CIVILIZATION_INFERNAL_HERBALIST', 'KIND_BUILDING'),
('SLTH_BUILDING_NULL_CIVILIZATION_INFERNAL_INFIRMARY', 'KIND_BUILDING'),
('SLTH_BUILDING_NULL_CIVILIZATION_INFERNAL_PUBLIC_BATHS', 'KIND_BUILDING'),
('SLTH_BUILDING_NULL_CIVILIZATION_INFERNAL_SMOKEHOUSE', 'KIND_BUILDING'),
('BUILDING_CITY_IS_COASTAL', 'KIND_BUILDING');

-- secret society buildings
INSERT INTO Types(Type, Kind) VALUES
('SLTH_BUILDING_DEMONS_ALTAR', 'KIND_BUILDING'),
('BUILDING_ALCHEMICAL_SOCIETY', 'KIND_BUILDING'),
('BUILDING_GILDED_VAULT', 'KIND_BUILDING');

