-- TOWERS
INSERT INTO Buildings(BuildingType, Name, PrereqTech, Cost, Description, AdvisorType, RequiresPlacement, IsWonder, MaxPlayerInstances) VALUES
('BUILDING_MAHABODHI_TEMPLE', 'LOC_SLTH_BUILDING_TOWER_OF_ALTERATION_NAME', 'TECH_ALTERATION', '800', 'LOC_SLTH_BUILDING_TOWER_OF_ALTERATION_DESCRIPTION', 'ADVISOR_TECHNOLOGY', '1', '1', '1'),
('BUILDING_ORACLE', 'LOC_SLTH_BUILDING_TOWER_OF_DIVINATION_NAME', 'TECH_DIVINATION', '800', 'LOC_SLTH_BUILDING_TOWER_OF_DIVINATION_DESCRIPTION', 'ADVISOR_TECHNOLOGY', '1', '1', '1'),
('BUILDING_EIFFEL_TOWER', 'LOC_SLTH_BUILDING_TOWER_OF_MASTERY_NAME', 'TECH_STRENGTH_OF_WILL', '4000', 'LOC_SLTH_BUILDING_TOWER_OF_MASTERY_DESCRIPTION', 'ADVISOR_TECHNOLOGY', '1', '1', '1'),
('BUILDING_HUEY_TEOCALLI', 'LOC_SLTH_BUILDING_TOWER_OF_NECROMANCY_NAME', 'TECH_NECROMANCY', '800', 'LOC_SLTH_BUILDING_TOWER_OF_NECROMANCY_DESCRIPTION', 'ADVISOR_TECHNOLOGY', '1', '1', '1'),
('BUILDING_MEENAKSHI_TEMPLE', 'LOC_SLTH_BUILDING_TOWER_OF_THE_ELEMENTS_NAME', 'TECH_ELEMENTALISM', '800', 'LOC_SLTH_BUILDING_TOWER_OF_THE_ELEMENTS_DESCRIPTION',  'ADVISOR_TECHNOLOGY', '1', '1', '1');

-- some of these are maybe world unique like Nilhorn, Natures Revolt, Bane Divine? unsure.
INSERT INTO Projects(ProjectType, Name, ShortName, Description, Cost, PrereqTech, PrereqCivic, MaxPlayerInstances, UnlocksFromEffect) VALUES
('PROJECT_BANE_DIVINE', 'LOC_PROJECT_BANE_DIVINE_NAME', 'LOC_PROJECT_BANE_DIVINE_SHORT', 'LOC_PROJECT_BANE_DIVINE_DESCRIPTION', '10000', NULL, 'CIVIC_MALEVOLENT_DESIGNS', NULL, '0'),                  -- UnlocksFromEffect to 0
('PROJECT_GLORY_EVERLASTING', 'LOC_PROJECT_GLORY_EVERLASTING_NAME', 'LOC_PROJECT_GLORY_EVERLASTING_SHORT', 'LOC_PROJECT_GLORY_EVERLASTING_DESCRIPTION', '10000', NULL, 'CIVIC_RIGHTEOUSNESS', NULL, '0'),
('PROJECT_BIRTHRIGHT_REGAINED', 'LOC_PROJECT_BIRTHRIGHT_REGAINED_NAME', 'LOC_PROJECT_BIRTHRIGHT_REGAINED_SHORT', 'LOC_PROJECT_BIRTHRIGHT_REGAINED_DESCRIPTION', '700', 'TECH_OMNISCIENCE', NULL, NULL, '0'),
-- ('PROJECT_PHOENIX', 'LOC_PROJECT_PHOENIX_NAME', 'LOC_PROJECT_PHOENIX_SHORT', 'LOC_PROJECT_PHOENIX_DESCRIPTION', '1000', NULL, 'CIVIC_DIVINE_ESSENCE', '1', '0'),                                         -- disabled as does nothing currently
-- ('PROJECT_GENESIS', 'LOC_PROJECT_GENESIS_NAME', 'LOC_PROJECT_GENESIS_SHORT', 'LOC_PROJECT_GENESIS_DESCRIPTION', '1250', NULL, 'CIVIC_COMMUNE_WITH_NATURE', '1', '0'),
('PROJECT_NATURES_REVOLT', 'LOC_PROJECT_NATURES_REVOLT_NAME', 'LOC_PROJECT_NATURES_REVOLT_SHORT', 'LOC_PROJECT_NATURES_REVOLT_DESCRIPTION', '1000', NULL, 'CIVIC_RIGHTEOUSNESS', NULL, '1'),
('PROJECT_RITES_OGHMA', 'LOC_PROJECT_RITES_OGHMA_NAME', 'LOC_PROJECT_RITES_OGHMA_SHORT', 'LOC_PROJECT_RITES_OGHMA_DESCRIPTION', '2500', 'TECH_STRENGTH_OF_WILL', NULL, NULL, '0'),
('PROJECT_PURGE_THE_UNFAITHFUL', 'LOC_PROJECT_PURGE_THE_UNFAITHFUL_NAME', 'LOC_PROJECT_PURGE_THE_UNFAITHFUL_SHORT', 'LOC_PROJECT_PURGE_THE_UNFAITHFUL_DESCRIPTION', '350', NULL, 'CIVIC_PRIESTHOOD', NULL, '0'),
('PROJECT_PACT_OF_NILHORN', 'LOC_PROJECT_PACT_OF_NILHORN_NAME', 'LOC_PROJECT_PACT_OF_NILHORN_SHORT', 'LOC_PROJECT_PACT_OF_NILHORN_DESCRIPTION', '500', 'TECH_CARTOGRAPHY', NULL, NULL, '0');

INSERT INTO Projects_XP2(ProjectType, UnlocksFromEffect) VALUES
('PROJECT_BANE_DIVINE', '1'),
('PROJECT_GLORY_EVERLASTING', '1'),
('PROJECT_BIRTHRIGHT_REGAINED', '1'),
('PROJECT_NATURES_REVOLT', '1'),
('PROJECT_RITES_OGHMA', '1'),
('PROJECT_PACT_OF_NILHORN', '1');

-- TODO PROJECT_RITES_OGHMA doesnt work
-- TODO PROJECT_PURGE_THE_UNFAITHFUL doesnt work
-- TODO Goblin FORT isnt summoning ARCHERS, attempted fix, needs test. Goblin scouts are working... odd
-- TODO Natures Revolt isnt working

INSERT INTO TraitModifiers(TraitType, ModifierId) VALUES
('TRAIT_LEADER_MAJOR_CIV', 'ALLOW_PACT_NILHORN');

INSERT INTO Modifiers(ModifierId, ModifierType, SubjectRequirementSetId) VALUES
('ALLOW_PACT_NILHORN', 'MODIFIER_PLAYER_ALLOW_PROJECT_CHINA', 'NO_ONE_MADE_NILHORN_PROJECT_REQS');
INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
('ALLOW_PACT_NILHORN', 'ProjectType', 'PROJECT_PACT_OF_NILHORN');

INSERT INTO Requirements(RequirementId, RequirementType, Inverse) VALUES
('REQUIREMENT_NO_ONE_MADE_NILHORN', 'REQUIREMENT_COLLECTION_ANY_MET', '1');

INSERT INTO RequirementArguments(RequirementId, Name, Value) VALUES
('REQUIREMENT_NO_ONE_MADE_NILHORN', 'CollectionType',  'COLLECTION_ALL_PLAYERS'),
('REQUIREMENT_NO_ONE_MADE_NILHORN', 'RequirementSetId',  'NO_ONE_MADE_NILHORN_SUBREQSET');

INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('NO_ONE_MADE_NILHORN_PROJECT_REQS', 'REQUIREMENT_NO_ONE_MADE_NILHORN');

INSERT INTO RequirementSets(RequirementSetId, RequirementSetType) VALUES
('NO_ONE_MADE_NILHORN_PROJECT_REQS', 'REQUIREMENTSET_TEST_ANY');

-- subreqset
INSERT INTO Requirements(RequirementId, RequirementType) VALUES
('REQUIREMENT_PLAYER_BUILT_NILHORN', 'REQUIREMENT_PLAYER_HAS_COMPLETED_PROJECT');

INSERT INTO RequirementArguments(RequirementId, Name, Value) VALUES
('REQUIREMENT_PLAYER_BUILT_NILHORN', 'ProjectType', 'PROJECT_PACT_OF_NILHORN');

INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('NO_ONE_MADE_NILHORN_SUBREQSET', 'REQUIREMENT_PLAYER_BUILT_NILHORN');

INSERT INTO RequirementSets(RequirementSetId, RequirementSetType) VALUES
('NO_ONE_MADE_NILHORN_SUBREQSET', 'REQUIREMENTSET_TEST_ANY');


-- PROJECT_NATURES_REVOLT, PROJECT_RITES_OGHMA
INSERT INTO TraitModifiers(TraitType, ModifierId) VALUES
('TRAIT_LEADER_MAJOR_CIV', 'ALLOW_NATURES_REVOLT'),
('TRAIT_LEADER_MAJOR_CIV', 'ALLOW_RITES_OGHMA');
INSERT INTO Modifiers(ModifierId, ModifierType, SubjectRequirementSetId) VALUES
('ALLOW_NATURES_REVOLT', 'MODIFIER_PLAYER_ALLOW_PROJECT_CHINA', 'NO_ONE_MADE_NATURES_REVOLT_REQS'),
('ALLOW_RITES_OGHMA', 'MODIFIER_PLAYER_ALLOW_PROJECT_CHINA', 'NO_ONE_MADE_RITES_OGHMA_REQS');
INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
('ALLOW_NATURES_REVOLT', 'ProjectType', 'PROJECT_NATURES_REVOLT'),
('ALLOW_RITES_OGHMA', 'ProjectType', 'PROJECT_RITES_OGHMA');

INSERT INTO Requirements(RequirementId, RequirementType, Inverse) VALUES
('REQUIREMENT_NO_ONE_MADE_NATURES_REVOLT', 'REQUIREMENT_COLLECTION_ANY_MET', '1'),
('REQUIREMENT_NO_ONE_MADE_RITES_OGHMA', 'REQUIREMENT_COLLECTION_ANY_MET', '1');

INSERT INTO RequirementArguments(RequirementId, Name, Value) VALUES
('REQUIREMENT_NO_ONE_MADE_NATURES_REVOLT', 'CollectionType',  'COLLECTION_ALL_PLAYERS'),
('REQUIREMENT_NO_ONE_MADE_NATURES_REVOLT', 'RequirementSetId',  'NO_ONE_MADE_NATURES_REVOLT_SUBREQSET'),
('REQUIREMENT_NO_ONE_MADE_RITES_OGHMA', 'CollectionType',  'COLLECTION_ALL_PLAYERS'),
('REQUIREMENT_NO_ONE_MADE_RITES_OGHMA', 'RequirementSetId',  'NO_ONE_MADE_RITES_OGHMA_SUBREQSET');

INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('NO_ONE_MADE_NATURES_REVOLT_REQS', 'REQUIREMENT_NO_ONE_MADE_NATURES_REVOLT'),
('NO_ONE_MADE_RITES_OGHMA_REQS', 'REQUIREMENT_NO_ONE_MADE_RITES_OGHMA');

INSERT INTO RequirementSets(RequirementSetId, RequirementSetType) VALUES
('NO_ONE_MADE_NATURES_REVOLT_REQS', 'REQUIREMENTSET_TEST_ANY'),
('NO_ONE_MADE_RITES_OGHMA_REQS', 'REQUIREMENTSET_TEST_ANY');

-- subreqset
INSERT INTO Requirements(RequirementId, RequirementType) VALUES
('REQUIREMENT_PLAYER_BUILT_NATURES_REVOLT', 'REQUIREMENT_PLAYER_HAS_COMPLETED_PROJECT'),
('REQUIREMENT_PLAYER_BUILT_RITES_OGHMA', 'REQUIREMENT_PLAYER_HAS_COMPLETED_PROJECT');

INSERT INTO RequirementArguments(RequirementId, Name, Value) VALUES
('REQUIREMENT_PLAYER_BUILT_NATURES_REVOLT', 'ProjectType', 'PROJECT_NATURES_REVOLT'),
('REQUIREMENT_PLAYER_BUILT_RITES_OGHMA', 'ProjectType', 'PROJECT_RITES_OGHMA');

INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('NO_ONE_MADE_NATURES_REVOLT_SUBREQSET', 'REQUIREMENT_PLAYER_BUILT_NATURES_REVOLT'),
('NO_ONE_MADE_RITES_OGHMA_SUBREQSET', 'REQUIREMENT_PLAYER_BUILT_RITES_OGHMA');

INSERT INTO RequirementSets(RequirementSetId, RequirementSetType) VALUES
('NO_ONE_MADE_NATURES_REVOLT_SUBREQSET', 'REQUIREMENTSET_TEST_ANY'),
('NO_ONE_MADE_RITES_OGHMA_SUBREQSET', 'REQUIREMENTSET_TEST_ANY');

-- PROJECT_PHOENIX, PROJECT_GENESIS
/*
INSERT INTO TraitModifiers(TraitType, ModifierId) VALUES
('TRAIT_LEADER_MAJOR_CIV', 'ALLOW_PHOENIX'),
('TRAIT_LEADER_MAJOR_CIV', 'ALLOW_GENESIS');
INSERT INTO Modifiers(ModifierId, ModifierType, SubjectRequirementSetId) VALUES
('ALLOW_PHOENIX', 'MODIFIER_PLAYER_ALLOW_PROJECT_CHINA', 'NO_ONE_MADE_PHOENIX_REQS'),
('ALLOW_GENESIS', 'MODIFIER_PLAYER_ALLOW_PROJECT_CHINA', 'NO_ONE_MADE_GENESIS_REQS');
INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
('ALLOW_PHOENIX', 'ProjectType', 'PROJECT_PHOENIX'),
('ALLOW_GENESIS', 'ProjectType', 'PROJECT_GENESIS');

INSERT INTO Requirements(RequirementId, RequirementType, Inverse) VALUES
('REQUIREMENT_NO_ONE_MADE_PHOENIX', 'REQUIREMENT_COLLECTION_ANY_MET', '1'),
('REQUIREMENT_NO_ONE_MADE_GENESIS', 'REQUIREMENT_COLLECTION_ANY_MET', '1');

INSERT INTO RequirementArguments(RequirementId, Name, Value) VALUES
('REQUIREMENT_NO_ONE_MADE_PHOENIX', 'CollectionType',  'COLLECTION_ALL_PLAYERS'),
('REQUIREMENT_NO_ONE_MADE_PHOENIX', 'RequirementSetId',  'NO_ONE_MADE_PHOENIX_SUBREQSET'),
('REQUIREMENT_NO_ONE_MADE_GENESIS', 'CollectionType',  'COLLECTION_ALL_PLAYERS'),
('REQUIREMENT_NO_ONE_MADE_GENESIS', 'RequirementSetId',  'NO_ONE_MADE_GENESIS_SUBREQSET');

INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('NO_ONE_MADE_PHOENIX_REQS', 'REQUIREMENT_NO_ONE_MADE_PHOENIX'),
('NO_ONE_MADE_GENESIS_REQS', 'REQUIREMENT_NO_ONE_MADE_GENESIS');

INSERT INTO RequirementSets(RequirementSetId, RequirementSetType) VALUES
('NO_ONE_MADE_PHOENIX_REQS', 'REQUIREMENTSET_TEST_ANY'),
('NO_ONE_MADE_GENESIS_REQS', 'REQUIREMENTSET_TEST_ANY');

-- subreqset
INSERT INTO Requirements(RequirementId, RequirementType, Inverse) VALUES
('REQUIREMENT_PLAYER_BUILT_PHOENIX', 'REQUIREMENT_PLAYER_HAS_COMPLETED_PROJECT'),
('REQUIREMENT_PLAYER_BUILT_GENESIS', 'REQUIREMENT_PLAYER_HAS_COMPLETED_PROJECT');

INSERT INTO RequirementArguments(RequirementId, Name, Value) VALUES
('REQUIREMENT_PLAYER_BUILT_PHOENIX', 'ProjectType', 'PROJECT_PHOENIX'),
('REQUIREMENT_PLAYER_BUILT_GENESIS', 'ProjectType', 'PROJECT_GENESIS');

INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('NO_ONE_MADE_PHOENIX_SUBREQSET', 'REQUIREMENT_PLAYER_BUILT_PHOENIX'),
('NO_ONE_MADE_GENESIS_SUBREQSET', 'REQUIREMENT_PLAYER_BUILT_GENESIS');

INSERT INTO RequirementSets(RequirementSetId, RequirementSetType) VALUES
('NO_ONE_MADE_PHOENIX_SUBREQSET', 'REQUIREMENTSET_TEST_ANY'),
('NO_ONE_MADE_GENESIS_SUBREQSET', 'REQUIREMENTSET_TEST_ANY');
 */

-- TODO not attached to anything rn, attach with lua, 70 armageddon/ used world spell. Also need to change Unlocks from Effect on those too.
-- A problem is that Bane Divine and Glory Everlasting should be reversible, but the allow project modifier is not reversible.
-- also its a headache to constantly be updating a property on every capital plot every time the armageddon count changes. Maybe just when its more than 70.
INSERT INTO BuildingModifiers(BuildingType, ModifierId) VALUES
('BUILDING_PALACE', 'ALLOW_BANE_DIVINE'),
('BUILDING_PALACE', 'ALLOW_GLORY_EVERLASTING'),
('BUILDING_PALACE', 'ALLOW_BIRTHRIGHT_REGAINED');

INSERT INTO Modifiers(ModifierId, ModifierType, OwnerRequirementSetId, SubjectRequirementSetId) VALUES
('ALLOW_BANE_DIVINE', 'MODIFIER_PLAYER_ALLOW_PROJECT_CHINA', 'ARMA_ABOVE_EIGHTY_REQS', 'NO_ONE_MADE_BANE_DIVINE_REQS'),
('ALLOW_GLORY_EVERLASTING', 'MODIFIER_PLAYER_ALLOW_PROJECT_CHINA', 'ARMA_ABOVE_EIGHTY_REQS', 'NO_ONE_MADE_GLORY_EVERLASTING_REQS'),
('ALLOW_BIRTHRIGHT_REGAINED', 'MODIFIER_PLAYER_ALLOW_PROJECT_CHINA', 'WORLD_SPELL_UNREADY_REQS', 'NO_ONE_MADE_BIRTHRIGHT_REGAINED_REQS');

INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
('ALLOW_BANE_DIVINE', 'ProjectType', 'PROJECT_BANE_DIVINE'),
('ALLOW_GLORY_EVERLASTING', 'ProjectType', 'PROJECT_GLORY_EVERLASTING'),
('ALLOW_BIRTHRIGHT_REGAINED', 'ProjectType', 'PROJECT_BIRTHRIGHT_REGAINED');

INSERT INTO Requirements(RequirementId, RequirementType) VALUES
('WORLD_SPELL_UNREADY', 'REQUIREMENT_PLOT_PROPERTY_MATCHES'),
('ARMA_ABOVE_EIGHTY', 'REQUIREMENT_PLOT_PROPERTY_MATCHES');

INSERT INTO RequirementArguments(RequirementId, Name, Value) VALUES
('WORLD_SPELL_UNREADY', 'PropertyName',     'WorldSpellReady'),
('WORLD_SPELL_UNREADY', 'PropertyMinimum',  '2'),
('ARMA_ABOVE_EIGHTY', 'PropertyName',     'ArmageddonAboveSeventy'),
('ARMA_ABOVE_EIGHTY', 'PropertyMinimum',  '1');

INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('WORLD_SPELL_UNREADY_REQS', 'WORLD_SPELL_UNREADY'),
('ARMA_ABOVE_EIGHTY_REQS', 'ARMA_ABOVE_EIGHTY');

INSERT INTO RequirementSets(RequirementSetId, RequirementSetType) VALUES
('WORLD_SPELL_UNREADY_REQS', 'REQUIREMENTSET_TEST_ANY'),
('ARMA_ABOVE_EIGHTY_REQS', 'REQUIREMENTSET_TEST_ANY');

-- ban once someone cast
INSERT INTO Requirements(RequirementId, RequirementType, Inverse) VALUES
('REQUIREMENT_NO_ONE_MADE_BANE_DIVINE', 'REQUIREMENT_COLLECTION_ANY_MET', '1'),
('REQUIREMENT_NO_ONE_MADE_GLORY_EVERLASTING', 'REQUIREMENT_COLLECTION_ANY_MET', '1'),
('REQUIREMENT_NO_ONE_MADE_BIRTHRIGHT_REGAINED', 'REQUIREMENT_COLLECTION_ANY_MET', '1');

INSERT INTO RequirementArguments(RequirementId, Name, Value) VALUES
('REQUIREMENT_NO_ONE_MADE_BANE_DIVINE', 'CollectionType',  'COLLECTION_ALL_PLAYERS'),
('REQUIREMENT_NO_ONE_MADE_BANE_DIVINE', 'RequirementSetId',  'NO_ONE_MADE_BANE_DIVINE_SUBREQSET'),
('REQUIREMENT_NO_ONE_MADE_GLORY_EVERLASTING', 'CollectionType',  'COLLECTION_ALL_PLAYERS'),
('REQUIREMENT_NO_ONE_MADE_GLORY_EVERLASTING', 'RequirementSetId',  'NO_ONE_MADE_GLORY_EVERLASTING_SUBREQSET'),
('REQUIREMENT_NO_ONE_MADE_BIRTHRIGHT_REGAINED', 'CollectionType',  'COLLECTION_ALL_PLAYERS'),
('REQUIREMENT_NO_ONE_MADE_BIRTHRIGHT_REGAINED', 'RequirementSetId',  'NO_ONE_MADE_BIRTHRIGHT_REGAINED_SUBREQSET');

INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('NO_ONE_MADE_BANE_DIVINE_REQS', 'REQUIREMENT_NO_ONE_MADE_BANE_DIVINE'),
('NO_ONE_MADE_GLORY_EVERLASTING_REQS', 'REQUIREMENT_NO_ONE_MADE_GLORY_EVERLASTING'),
('NO_ONE_MADE_BIRTHRIGHT_REGAINED_REQS', 'REQUIREMENT_NO_ONE_MADE_BIRTHRIGHT_REGAINED');

INSERT INTO RequirementSets(RequirementSetId, RequirementSetType) VALUES
('NO_ONE_MADE_BANE_DIVINE_REQS', 'REQUIREMENTSET_TEST_ANY'),
('NO_ONE_MADE_GLORY_EVERLASTING_REQS', 'REQUIREMENTSET_TEST_ANY'),
('NO_ONE_MADE_BIRTHRIGHT_REGAINED_REQS', 'REQUIREMENTSET_TEST_ANY');

-- subreqset
INSERT INTO Requirements(RequirementId, RequirementType) VALUES
('REQUIREMENT_PLAYER_BUILT_BANE_DIVINE', 'REQUIREMENT_PLAYER_HAS_COMPLETED_PROJECT'),
('REQUIREMENT_PLAYER_BUILT_GLORY_EVERLASTING', 'REQUIREMENT_PLAYER_HAS_COMPLETED_PROJECT'),
('REQUIREMENT_PLAYER_BUILT_BIRTHRIGHT_REGAINED', 'REQUIREMENT_PLAYER_HAS_COMPLETED_PROJECT');

INSERT INTO RequirementArguments(RequirementId, Name, Value) VALUES
('REQUIREMENT_PLAYER_BUILT_BANE_DIVINE', 'ProjectType', 'PROJECT_BANE_DIVINE'),
('REQUIREMENT_PLAYER_BUILT_GLORY_EVERLASTING', 'ProjectType', 'PROJECT_GLORY_EVERLASTING'),
('REQUIREMENT_PLAYER_BUILT_BIRTHRIGHT_REGAINED', 'ProjectType', 'PROJECT_BIRTHRIGHT_REGAINED');

INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('NO_ONE_MADE_BANE_DIVINE_SUBREQSET', 'REQUIREMENT_PLAYER_BUILT_BANE_DIVINE'),
('NO_ONE_MADE_GLORY_EVERLASTING_SUBREQSET', 'REQUIREMENT_PLAYER_BUILT_GLORY_EVERLASTING'),
('NO_ONE_MADE_BIRTHRIGHT_REGAINED_SUBREQSET', 'REQUIREMENT_PLAYER_BUILT_BIRTHRIGHT_REGAINED');

INSERT INTO RequirementSets(RequirementSetId, RequirementSetType) VALUES
('NO_ONE_MADE_BANE_DIVINE_SUBREQSET', 'REQUIREMENTSET_TEST_ANY'),
('NO_ONE_MADE_GLORY_EVERLASTING_SUBREQSET', 'REQUIREMENTSET_TEST_ANY'),
('NO_ONE_MADE_BIRTHRIGHT_REGAINED_SUBREQSET', 'REQUIREMENTSET_TEST_ANY');


-- ProjectCompletionModifiers
INSERT INTO Modifiers(ModifierId, ModifierType, RunOnce, Permanent, OwnerRequirementSetId) VALUES
('GRANT_THREE_GIANTS', 'MODIFIER_PLAYER_GRANT_UNIT_IN_CAPITAL', '1', '1', 'SLTH_PLAYER_HAS_CAPITAL');

INSERT INTO ModifierArguments(ModifierId, Name, "Value") VALUES
('GRANT_THREE_GIANTS', 'UnitType', 'SLTH_UNIT_HILL_GIANT'),
('GRANT_THREE_GIANTS', 'Amount', '3'),
('GRANT_THREE_GIANTS', 'AllowUniqueOverride', '0');

INSERT INTO ProjectCompletionModifiers (ProjectType, ModifierId) VALUES
('PROJECT_PACT_OF_NILHORN', 'GRANT_THREE_GIANTS'),
('PROJECT_GLORY_EVERLASTING', 'KILL_ALL_DEMONS');

INSERT INTO Modifiers(ModifierId, ModifierType, RunOnce, Permanent, SubjectRequirementSetId) VALUES
('MODIFIER_BUILDING_ORACLE_FREE_TECH', 'MODIFIER_PLAYER_GRANT_RANDOM_TECHNOLOGY', '1', '1', NULL),
('MODIFIER_BUILDING_HUEY_TEOCALLI_GRANT_MANA_DEATH', 'MODIFIER_FREE_RESOURCE_IN_CAPITAL', '0', '0', NULL),
('KILL_ALL_DEMONS', 'MODIFIER_WORLD_UNITS_ADJUST_DAMAGE', '1', '1', 'UNIT_IS_DEMON');

INSERT INTO ModifierArguments(ModifierId, Name, Type, Value) VALUES
('MODIFIER_BUILDING_ORACLE_FREE_TECH', 'Amount', 'ARGTYPE_IDENTITY', '1'),
('MODIFIER_BUILDING_HUEY_TEOCALLI_GRANT_MANA_DEATH', 'Amount', 'ARGTYPE_IDENTITY', '1'),
('MODIFIER_BUILDING_HUEY_TEOCALLI_GRANT_MANA_DEATH', 'ResourceType', 'ARGTYPE_IDENTITY', 'RESOURCE_MANA_DEATH'),
('KILL_ALL_DEMONS', 'Amount',  'ARGTYPE_IDENTITY', '100');

-- palaces, but not working
INSERT INTO Buildings(BuildingType, Name, PrereqTech, PrereqCivic, Cost, PrereqDistrict, Description, AdvisorType, RequiresPlacement, IsWonder, MaxPlayerInstances) VALUES
('BUILDING_FORBIDDEN_CITY', 'LOC_BUILDING_SUMMER_PALACE_NAME', NULL, NULL, '300', NULL, 'LOC_BUILDING_SUMMER_PALACE_DESCRIPTION', 'ADVISOR_GENERIC', '1', '1', '1'),
('BUILDING_ORSZAGHAZ', 'LOC_BUILDING_WINTER_PALACE_NAME', NULL, 'CIVIC_CODE_OF_LAWS', '800', 'DISTRICT_CITY_CENTER', 'LOC_BUILDING_WINTER_PALACE_DESCRIPTION', 'ADVISOR_GENERIC', '1', '1', '1');

INSERT INTO Building_YieldChanges(BuildingType, YieldType, YieldChange) VALUES
('BUILDING_FORBIDDEN_CITY', 'YIELD_CULTURE', 4),
('BUILDING_ORSZAGHAZ', 'YIELD_CULTURE', 10);

INSERT INTO MutuallyExclusiveBuildings (Building, MutuallyExclusiveBuilding) VALUES
('BUILDING_FORBIDDEN_CITY', 'BUILDING_PALACE'),
('BUILDING_ORSZAGHAZ', 'BUILDING_PALACE'),
('BUILDING_FORBIDDEN_CITY', 'BUILDING_ORSZAGHAZ'),
('BUILDING_ORSZAGHAZ', 'BUILDING_FORBIDDEN_CITY');

INSERT INTO BuildingConditions(BuildingType, UnlocksFromEffect) VALUES
('BUILDING_MAHABODHI_TEMPLE', '1'),
('BUILDING_ORACLE', '1'),
('BUILDING_HUEY_TEOCALLI', '1'),
('BUILDING_MEENAKSHI_TEMPLE', '1'),
('BUILDING_EIFFEL_TOWER', '1'),
('BUILDING_FORBIDDEN_CITY', '1'),
('BUILDING_ORSZAGHAZ', '1'),
('BUILDING_GREAT_LIBRARY', '1'),
('BUILDING_BOLSHOI_THEATRE', '1'),
('SLTH_BUILDING_EYES_AND_EARS_NETWORK', '1');

INSERT INTO Buildings(BuildingType, Name, Cost, PrereqDistrict, Description, PurchaseYield, MustPurchase) VALUES
('BUILDING_NULL_NECROMANCY', 'LOC_SLTH_NECROMANCY_NO_RSC_BUILDING_NULL_NAME', '500', 'DISTRICT_CITY_CENTER', 'LOC_SLTH_BUILDING_NULLDESCRIPTION', NULL, '1'),
('BUILDING_NULL_ALTERATION', 'LOC_SLTH_ALTERATION_NO_RSC_BUILDING_NULL_NAME', '500', 'DISTRICT_CITY_CENTER', 'LOC_SLTH_BUILDING_NULLDESCRIPTION', NULL, '1'),
('BUILDING_NULL_ELEMENTS', 'LOC_SLTH_ELEMENTS_NO_RSC_BUILDING_NULL_NAME', '500', 'DISTRICT_CITY_CENTER', 'LOC_SLTH_BUILDING_NULLDESCRIPTION', NULL, '1'),
('BUILDING_NULL_DIVINATION', 'LOC_SLTH_DIVINIATION_NO_RSC_BUILDING_NULL_NAME', '500', 'DISTRICT_CITY_CENTER', 'LOC_SLTH_BUILDING_NULLDESCRIPTION', NULL, '1'),
('BUILDING_NULL_MASTERY', 'LOC_SLTH_MASTERY_NO_REQS_BUILDING_NULL_NAME', '500', 'DISTRICT_CITY_CENTER', 'LOC_SLTH_BUILDING_NULLDESCRIPTION', NULL, '1'),
('BUILDING_NULL_SUMMER_PALACE', 'LOC_SLTH_SUMMER_PLC_NOT_CITIES_BUILDING_NULL_NAME', '500', 'DISTRICT_CITY_CENTER', 'LOC_SLTH_BUILDING_NULLDESCRIPTION', NULL, '1'),
('BUILDING_NULL_WINTER_PALACE', 'LOC_SLTH_WINTER_PLC_NOT_CITIES_BUILDING_NULL_NAME', '500', 'DISTRICT_CITY_CENTER', 'LOC_SLTH_BUILDING_NULLDESCRIPTION', NULL, '1'),
('BUILDING_NULL_GREAT_LIBRARY', 'LOC_SLTH_GREAT_LIB_NOT_REQS_BUILDING_NULL_NAME', '500', 'DISTRICT_CITY_CENTER', 'LOC_SLTH_BUILDING_NULLDESCRIPTION', NULL, '1'),
('BUILDING_NULL_THEATRE_OF_DREAMS', 'LOC_SLTH_THEATRE_DREAMS_NOT_REQS_BUILDING_NULL_NAME', '500', 'DISTRICT_CITY_CENTER', 'LOC_SLTH_BUILDING_NULLDESCRIPTION', NULL, '1'),
('BUILDING_NULL_EYES_AND_EARS', 'LOC_SLTH_EYES_EARS_NOT_REQS_BUILDING_NULL_NAME', '500', 'DISTRICT_CITY_CENTER', 'LOC_SLTH_BUILDING_NULLDESCRIPTION', NULL, '1');

INSERT INTO CivilopediaPageExcludes(SectionId, PageId) VALUES
('BUILDINGS','BUILDING_NULL_NECROMANCY'),
('BUILDINGS','BUILDING_NULL_ALTERATION'),
('BUILDINGS','BUILDING_NULL_ELEMENTS'),
('BUILDINGS','BUILDING_NULL_DIVINATION'),
('BUILDINGS','BUILDING_NULL_MASTERY'),
('BUILDINGS','BUILDING_NULL_SUMMER_PALACE'),
('BUILDINGS','BUILDING_NULL_WINTER_PALACE'),
('BUILDINGS','BUILDING_NULL_GREAT_LIBRARY'),
('BUILDINGS','BUILDING_NULL_THEATRE_OF_DREAMS'),
('BUILDINGS','BUILDING_NULL_EYES_AND_EARS');


INSERT INTO Types(Type, Kind) VALUES
('BUILDING_NULL_NECROMANCY', 'KIND_BUILDING'),
('BUILDING_NULL_ALTERATION', 'KIND_BUILDING'),
('BUILDING_NULL_ELEMENTS', 'KIND_BUILDING'),
('BUILDING_NULL_DIVINATION', 'KIND_BUILDING'),
('BUILDING_NULL_MASTERY', 'KIND_BUILDING'),
('BUILDING_NULL_SUMMER_PALACE', 'KIND_BUILDING'),
('BUILDING_NULL_WINTER_PALACE', 'KIND_BUILDING'),
('BUILDING_NULL_GREAT_LIBRARY', 'KIND_BUILDING'),
('BUILDING_NULL_THEATRE_OF_DREAMS', 'KIND_BUILDING'),
('BUILDING_NULL_EYES_AND_EARS', 'KIND_BUILDING'),
('SLTH_BUILDING_EYES_AND_EARS_NETWORK', 'KIND_BUILDING'),
('PROJECT_PHOENIX', 'KIND_PROJECT'),
('PROJECT_BANE_DIVINE', 'KIND_PROJECT'),
('PROJECT_GLORY_EVERLASTING', 'KIND_PROJECT'),
('PROJECT_GENESIS', 'KIND_PROJECT'),
('PROJECT_NATURES_REVOLT', 'KIND_PROJECT'),
('PROJECT_RITES_OGHMA', 'KIND_PROJECT'),
('PROJECT_BIRTHRIGHT_REGAINED', 'KIND_PROJECT'),
('PROJECT_PURGE_THE_UNFAITHFUL', 'KIND_PROJECT'),
('PROJECT_PACT_OF_NILHORN', 'KIND_PROJECT');

INSERT INTO Modifiers(ModifierId, ModifierType, SubjectRequirementSetId) VALUES
('ALLOW_TOWER_NECROMANCY', 'MODIFIER_PLAYER_ADJUST_VALID_BUILDING', 'PLAYER_HAS_ALL_EVIL_MANA'),
('ALLOW_TOWER_ALTERATION', 'MODIFIER_PLAYER_ADJUST_VALID_BUILDING', 'PLAYER_HAS_ALL_ALTERATION_MANA'),
('ALLOW_TOWER_ELEMENTS', 'MODIFIER_PLAYER_ADJUST_VALID_BUILDING', 'PLAYER_HAS_ALL_ELEMENTS_MANA'),
('ALLOW_TOWER_DIVINATION', 'MODIFIER_PLAYER_ADJUST_VALID_BUILDING', 'PLAYER_HAS_ALL_DIVINATION_MANA'),
('ALLOW_TOWER_MASTERY', 'MODIFIER_PLAYER_ADJUST_VALID_BUILDING', 'PLAYER_HAS_ALL_TOWERS'),
('ALLOW_SUMMER_PALACE', 'MODIFIER_PLAYER_ADJUST_VALID_BUILDING', 'PLAYER_HAS_MORE_THAN_SEVEN_CITIES'),
('ALLOW_WINTER_PALACE', 'MODIFIER_PLAYER_ADJUST_VALID_BUILDING', 'PLAYER_HAS_MORE_THAN_ELEVEN_CITIES'),
('ALLOW_GREAT_LIBRARY', 'MODIFIER_PLAYER_ADJUST_VALID_BUILDING', 'PLAYER_HAS_MORE_THAN_TWO_LIBRARIES'),
('ALLOW_THEATRE_OF_DREAMS', 'MODIFIER_PLAYER_ADJUST_VALID_BUILDING', 'PLAYER_HAS_MORE_THAN_TWO_THEATRES'),
('ALLOW_EYES_AND_EARS', 'MODIFIER_PLAYER_ADJUST_VALID_BUILDING', 'PLAYER_HAS_MORE_THAN_FOUR_INNS'),
('DOUBLE_PROD_FORM_OF_TITAN', 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_PRODUCTION', 'PLAYER_HAS_COPPER'),
('DOUBLE_PROD_SHRINE_OF_SIRONA', 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_PRODUCTION', 'PLAYER_HAS_MARBLE'),
('DOUBLE_PROD_BONE_PALACE', 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_PRODUCTION', 'PLAYER_HAS_MARBLE'),
('DOUBLE_PROD_HALL_OF_KINGS', 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_PRODUCTION', 'PLAYER_HAS_MARBLE'),
('DOUBLE_PROD_TEMPLE_OF_TEMPORANCE', 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_PRODUCTION', 'PLAYER_HAS_MARBLE'),
('DOUBLE_PROD_GREAT_LIBRARY', 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_PRODUCTION', 'PLAYER_HAS_MARBLE'),
('DOUBLE_PROD_HEROIC_EPIC', 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_PRODUCTION', 'PLAYER_HAS_MARBLE'),
('DOUBLE_PROD_NATIONAL_EPIC', 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_PRODUCTION', 'PLAYER_HAS_MARBLE'),
('DOUBLE_PROD_PHOENIX', 'MODIFIER_PLAYER_CITIES_ADJUST_PROJECT_PRODUCTION', 'PLAYER_HAS_LIFE_MANA'),
('DOUBLE_PROD_BANE_DIVINE_DEATH', 'MODIFIER_PLAYER_CITIES_ADJUST_PROJECT_PRODUCTION', 'PLAYER_HAS_DEATH_MANA'),
('DOUBLE_PROD_BANE_DIVINE_ENTROPY', 'MODIFIER_PLAYER_CITIES_ADJUST_PROJECT_PRODUCTION', 'PLAYER_HAS_ENTROPY_MANA'),
('DOUBLE_PROD_GLORY_EVERLASTING_LIFE', 'MODIFIER_PLAYER_CITIES_ADJUST_PROJECT_PRODUCTION', 'PLAYER_HAS_LIFE_MANA'),
('DOUBLE_PROD_GLORY_EVERLASTING_LAW', 'MODIFIER_PLAYER_CITIES_ADJUST_PROJECT_PRODUCTION', 'PLAYER_HAS_LAW_MANA'),
('DOUBLE_PROD_GENESIS_NATURE', 'MODIFIER_PLAYER_CITIES_ADJUST_PROJECT_PRODUCTION', 'PLAYER_HAS_NATURE_MANA'),
('DOUBLE_PROD_NATURES_REVOLT_NATURE', 'MODIFIER_PLAYER_CITIES_ADJUST_PROJECT_PRODUCTION', 'PLAYER_HAS_NATURE_MANA'),
('DOUBLE_PROD_RITES_OGHMA', 'MODIFIER_PLAYER_CITIES_ADJUST_PROJECT_PRODUCTION', 'PLAYER_HAS_METAMAGIC_MANA'),
('MODIFIER_BUILDING_BOLSHOI_THEATRE_ADD_AMENITIES', 'MODIFIER_ALL_CITY_ADJUST_ENTERTAINMENT', NULL);

INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
('ALLOW_TOWER_NECROMANCY', 'BuildingType', 'BUILDING_HUEY_TEOCALLI'),
('ALLOW_TOWER_NECROMANCY', 'BuildingTypeToReplace', 'BUILDING_NULL_NECROMANCY'),
('ALLOW_TOWER_ALTERATION', 'BuildingType', 'BUILDING_MAHABODHI_TEMPLE'),
('ALLOW_TOWER_ALTERATION', 'BuildingTypeToReplace', 'BUILDING_NULL_ALTERATION'),
('ALLOW_TOWER_ELEMENTS', 'BuildingType', 'BUILDING_MEENAKSHI_TEMPLE'),
('ALLOW_TOWER_ELEMENTS', 'BuildingTypeToReplace', 'BUILDING_NULL_ELEMENTS'),
('ALLOW_TOWER_DIVINATION', 'BuildingType', 'BUILDING_ORACLE'),
('ALLOW_TOWER_DIVINATION', 'BuildingTypeToReplace', 'BUILDING_NULL_DIVINATION'),
('ALLOW_TOWER_MASTERY', 'BuildingType', 'BUILDING_EIFFEL_TOWER'),
('ALLOW_TOWER_MASTERY', 'BuildingTypeToReplace', 'BUILDING_NULL_MASTERY'),
('ALLOW_SUMMER_PALACE', 'BuildingType', 'BUILDING_FORBIDDEN_CITY'),
('ALLOW_SUMMER_PALACE', 'BuildingTypeToReplace', 'BUILDING_NULL_SUMMER_PALACE'),
('ALLOW_WINTER_PALACE', 'BuildingType', 'BUILDING_ORSZAGHAZ'),
('ALLOW_WINTER_PALACE', 'BuildingTypeToReplace', 'BUILDING_NULL_WINTER_PALACE'),
('ALLOW_GREAT_LIBRARY', 'BuildingType', 'BUILDING_GREAT_LIBRARY'),
('ALLOW_GREAT_LIBRARY', 'BuildingTypeToReplace', 'BUILDING_NULL_GREAT_LIBRARY'),
('ALLOW_THEATRE_OF_DREAMS', 'BuildingType', 'BUILDING_BOLSHOI_THEATRE'),
('ALLOW_THEATRE_OF_DREAMS', 'BuildingTypeToReplace', 'BUILDING_NULL_THEATRE_OF_DREAMS'),
('ALLOW_EYES_AND_EARS', 'BuildingType', 'SLTH_BUILDING_EYES_AND_EARS_NETWORK'),
('ALLOW_EYES_AND_EARS', 'BuildingTypeToReplace', 'BUILDING_NULL_EYES_AND_EARS'),
('DOUBLE_PROD_FORM_OF_TITAN', 'BuildingType', 'BUILDING_COLOSSUS'),
('DOUBLE_PROD_FORM_OF_TITAN', 'Amount', '100'),
('DOUBLE_PROD_SHRINE_OF_SIRONA', 'BuildingType', 'BUILDING_CRISTO_REDENTOR'),
('DOUBLE_PROD_SHRINE_OF_SIRONA', 'Amount', '100'),
('DOUBLE_PROD_BONE_PALACE', 'BuildingType', 'BUILDING_TAJ_MAHAL'),
('DOUBLE_PROD_BONE_PALACE', 'Amount', '100'),
('DOUBLE_PROD_HALL_OF_KINGS', 'BuildingType', 'BUILDING_ST_BASILS_CATHEDRAL'),
('DOUBLE_PROD_HALL_OF_KINGS', 'Amount', '100'),
('DOUBLE_PROD_TEMPLE_OF_TEMPORANCE', 'BuildingType', 'BUILDING_HAGIA_SOPHIA'),
('DOUBLE_PROD_TEMPLE_OF_TEMPORANCE', 'Amount', '100'),
('DOUBLE_PROD_GREAT_LIBRARY', 'BuildingType', 'BUILDING_GREAT_LIBRARY'),
('DOUBLE_PROD_GREAT_LIBRARY', 'Amount', '100'),
('DOUBLE_PROD_HEROIC_EPIC', 'BuildingType', 'SLTH_BUILDING_HEROIC_EPIC'),
('DOUBLE_PROD_HEROIC_EPIC', 'Amount', '100'),
('DOUBLE_PROD_NATIONAL_EPIC', 'BuildingType', 'SLTH_BUILDING_NATIONAL_EPIC'),
('DOUBLE_PROD_NATIONAL_EPIC', 'Amount', '100'),
('DOUBLE_PROD_PHOENIX', 'ProjectType', 'PROJECT_PHOENIX'),
('DOUBLE_PROD_PHOENIX', 'Amount', '100'),
('DOUBLE_PROD_BANE_DIVINE_DEATH', 'ProjectType', 'PROJECT_BANE_DIVINE'),
('DOUBLE_PROD_BANE_DIVINE_DEATH', 'Amount', '100'),
('DOUBLE_PROD_BANE_DIVINE_ENTROPY', 'ProjectType', 'PROJECT_BANE_DIVINE'),
('DOUBLE_PROD_BANE_DIVINE_ENTROPY', 'Amount', '100'),
('DOUBLE_PROD_GLORY_EVERLASTING_LIFE', 'ProjectType', 'PROJECT_GLORY_EVERLASTING'),
('DOUBLE_PROD_GLORY_EVERLASTING_LIFE', 'Amount', '100'),
('DOUBLE_PROD_GLORY_EVERLASTING_LAW', 'ProjectType', 'PROJECT_GLORY_EVERLASTING'),
('DOUBLE_PROD_GLORY_EVERLASTING_LAW', 'Amount', '100'),
('DOUBLE_PROD_GENESIS_NATURE', 'ProjectType', 'PROJECT_GENESIS'),
('DOUBLE_PROD_GENESIS_NATURE', 'Amount', '100'),
('DOUBLE_PROD_NATURES_REVOLT_NATURE', 'ProjectType', 'PROJECT_NATURES_REVOLT'),
('DOUBLE_PROD_NATURES_REVOLT_NATURE', 'Amount', '100'),
('DOUBLE_PROD_RITES_OGHMA', 'ProjectType', 'PROJECT_RITES_OGHMA'),
('DOUBLE_PROD_RITES_OGHMA', 'Amount', '100'),
('MODIFIER_BUILDING_BOLSHOI_THEATRE_ADD_AMENITIES', 'BUILDING_BOLSHOI_THEATRE', '1');

INSERT INTO TechnologyModifiers(TechnologyType, ModifierId) VALUES
('TECH_STRENGTH_OF_WILL', 'ALLOW_TOWER_MASTERY'),
('TECH_WRITING', 'ALLOW_GREAT_LIBRARY');

INSERT INTO BuildingModifiers(BuildingType, ModifierId) VALUES
('BUILDING_PALACE', 'ALLOW_TOWER_NECROMANCY'),                  -- TODO Test this works
('BUILDING_PALACE', 'ALLOW_TOWER_ALTERATION'),
('BUILDING_PALACE', 'ALLOW_TOWER_ELEMENTS'),
('BUILDING_PALACE', 'ALLOW_TOWER_DIVINATION'),
('BUILDING_PALACE', 'DOUBLE_PROD_GREAT_LIBRARY'),
('BUILDING_PALACE', 'DOUBLE_PROD_SHRINE_OF_SIRONA'),
('BUILDING_PALACE', 'DOUBLE_PROD_RITES_OGHMA'),
('BUILDING_PALACE', 'DOUBLE_PROD_FORM_OF_TITAN'),
('BUILDING_PALACE', 'DOUBLE_PROD_BONE_PALACE'),
('BUILDING_PALACE', 'DOUBLE_PROD_HALL_OF_KINGS'),
('BUILDING_PALACE', 'DOUBLE_PROD_TEMPLE_OF_TEMPORANCE'),
('BUILDING_PALACE', 'DOUBLE_PROD_HEROIC_EPIC'),
('BUILDING_PALACE', 'DOUBLE_PROD_NATIONAL_EPIC'),
('BUILDING_PALACE', 'DOUBLE_PROD_PHOENIX'),
('BUILDING_PALACE', 'DOUBLE_PROD_BANE_DIVINE_DEATH'),
('BUILDING_PALACE', 'DOUBLE_PROD_BANE_DIVINE_ENTROPY'),
('BUILDING_PALACE', 'DOUBLE_PROD_GLORY_EVERLASTING_LIFE'),
('BUILDING_PALACE', 'DOUBLE_PROD_GLORY_EVERLASTING_LAW'),
('BUILDING_PALACE', 'DOUBLE_PROD_NATURES_REVOLT_NATURE'),
('BUILDING_PALACE', 'DOUBLE_PROD_GENESIS_NATURE');

INSERT INTO CivicModifiers(CivicType, ModifierId) VALUES
('CIVIC_CODE_OF_LAWS', 'ALLOW_WINTER_PALACE'),
('CIVIC_ANCIENT_CHANTS', 'ALLOW_SUMMER_PALACE'),
('CIVIC_DRAMA_POETRY', 'ALLOW_THEATRE_OF_DREAMS');

INSERT INTO Requirements(RequirementId, RequirementType) VALUES
('REQUIRES_PLAYER_HAS_CHAOS_MANA', 'REQUIREMENT_PLAYER_HAS_RESOURCE_OWNED'),
('REQUIRES_PLAYER_HAS_DEATH_MANA', 'REQUIREMENT_PLAYER_HAS_RESOURCE_OWNED'),
('REQUIRES_PLAYER_HAS_ENTROPY_MANA', 'REQUIREMENT_PLAYER_HAS_RESOURCE_OWNED'),
('REQUIRES_PLAYER_HAS_SHADOW_MANA', 'REQUIREMENT_PLAYER_HAS_RESOURCE_OWNED'),
('REQUIRES_PLAYER_HAS_LAW_MANA', 'REQUIREMENT_PLAYER_HAS_RESOURCE_OWNED'),
('REQUIRES_PLAYER_HAS_MIND_MANA', 'REQUIREMENT_PLAYER_HAS_RESOURCE_OWNED'),
('REQUIRES_PLAYER_HAS_SPIRIT_MANA', 'REQUIREMENT_PLAYER_HAS_RESOURCE_OWNED'),
('REQUIRES_PLAYER_HAS_SUN_MANA', 'REQUIREMENT_PLAYER_HAS_RESOURCE_OWNED'),
('REQUIRES_PLAYER_HAS_AIR_MANA', 'REQUIREMENT_PLAYER_HAS_RESOURCE_OWNED'),
('REQUIRES_PLAYER_HAS_EARTH_MANA', 'REQUIREMENT_PLAYER_HAS_RESOURCE_OWNED'),
('REQUIRES_PLAYER_HAS_FIRE_MANA', 'REQUIREMENT_PLAYER_HAS_RESOURCE_OWNED'),
('REQUIRES_PLAYER_HAS_WATER_MANA', 'REQUIREMENT_PLAYER_HAS_RESOURCE_OWNED'),
('REQUIRES_PLAYER_HAS_BODY_MANA', 'REQUIREMENT_PLAYER_HAS_RESOURCE_OWNED'),
('REQUIRES_PLAYER_HAS_ENCHANTMENT_MANA', 'REQUIREMENT_PLAYER_HAS_RESOURCE_OWNED'),
('REQUIRES_PLAYER_HAS_LIFE_MANA', 'REQUIREMENT_PLAYER_HAS_RESOURCE_OWNED'),
('REQUIRES_PLAYER_HAS_NATURE_MANA', 'REQUIREMENT_PLAYER_HAS_RESOURCE_OWNED'),
('REQUIRES_PLAYER_HAS_METAMAGIC_MANA', 'REQUIREMENT_PLAYER_HAS_RESOURCE_OWNED'),
('REQUIRES_PLAYER_HAS_COPPER', 'REQUIREMENT_PLAYER_HAS_RESOURCE_OWNED'),
('REQUIRES_PLAYER_HAS_MARBLE', 'REQUIREMENT_PLAYER_HAS_RESOURCE_OWNED');

INSERT INTO RequirementArguments(RequirementId, Name, Value) VALUES
('REQUIRES_PLAYER_HAS_CHAOS_MANA', 'ResourceType', 'RESOURCE_MANA_CHAOS'),
('REQUIRES_PLAYER_HAS_DEATH_MANA', 'ResourceType', 'RESOURCE_MANA_DEATH'),
('REQUIRES_PLAYER_HAS_ENTROPY_MANA', 'ResourceType', 'RESOURCE_MANA_ENTROPY'),
('REQUIRES_PLAYER_HAS_SHADOW_MANA', 'ResourceType', 'RESOURCE_MANA_SHADOW'),
('REQUIRES_PLAYER_HAS_LAW_MANA', 'ResourceType', 'RESOURCE_MANA_LAW'),
('REQUIRES_PLAYER_HAS_MIND_MANA', 'ResourceType', 'RESOURCE_MANA_MIND'),
('REQUIRES_PLAYER_HAS_SPIRIT_MANA', 'ResourceType', 'RESOURCE_MANA_SPIRIT'),
('REQUIRES_PLAYER_HAS_SUN_MANA', 'ResourceType', 'RESOURCE_MANA_SUN'),
('REQUIRES_PLAYER_HAS_AIR_MANA', 'ResourceType', 'RESOURCE_MANA_AIR'),
('REQUIRES_PLAYER_HAS_EARTH_MANA', 'ResourceType', 'RESOURCE_MANA_EARTH'),
('REQUIRES_PLAYER_HAS_FIRE_MANA', 'ResourceType', 'RESOURCE_MANA_FIRE'),
('REQUIRES_PLAYER_HAS_WATER_MANA', 'ResourceType', 'RESOURCE_MANA_WATER'),
('REQUIRES_PLAYER_HAS_BODY_MANA', 'ResourceType', 'RESOURCE_MANA_BODY'),
('REQUIRES_PLAYER_HAS_ENCHANTMENT_MANA', 'ResourceType', 'RESOURCE_MANA_ENCHANTMENT'),
('REQUIRES_PLAYER_HAS_LIFE_MANA', 'ResourceType', 'RESOURCE_MANA_LIFE'),
('REQUIRES_PLAYER_HAS_NATURE_MANA', 'ResourceType', 'RESOURCE_MANA_NATURE'),
('REQUIRES_PLAYER_HAS_METAMAGIC_MANA', 'ResourceType', 'RESOURCE_MANA_METAMAGIC'),
('REQUIRES_PLAYER_HAS_COPPER', 'ResourceType', 'RESOURCE_COPPER'),
('REQUIRES_PLAYER_HAS_MARBLE', 'ResourceType', 'RESOURCE_MARBLE');

INSERT INTO Requirements(RequirementId, RequirementType) VALUES
('PLAYER_HAS_TOWER_NECROMANCY_REQUIREMENT', 'REQUIREMENT_PLAYER_HAS_BUILDING'),
('PLAYER_HAS_TOWER_ELEMENTS_REQUIREMENT', 'REQUIREMENT_PLAYER_HAS_BUILDING'),
('PLAYER_HAS_TOWER_DIVINATION_REQUIREMENT', 'REQUIREMENT_PLAYER_HAS_BUILDING'),
('PLAYER_HAS_TOWER_ALTERATION_REQUIREMENT', 'REQUIREMENT_PLAYER_HAS_BUILDING'),
('REQUIRES_PLAYER_HAS_MORE_THAN_SEVEN_CITIES', 'REQUIREMENT_PLAYER_HAS_AT_LEAST_NUMBER_CITIES'),
('REQUIRES_PLAYER_HAS_MORE_THAN_ELEVEN_CITIES', 'REQUIREMENT_PLAYER_HAS_AT_LEAST_NUMBER_CITIES'),
('REQUIREMENT_PLAYER_HAS_MORE_THAN_TWO_LIBRARIES', 'REQUIREMENT_PLAYER_HAS_AT_LEAST_NUM_BUILDINGS'),
('REQUIREMENT_PLAYER_HAS_MORE_THAN_TWO_THEATRES', 'REQUIREMENT_PLAYER_HAS_AT_LEAST_NUM_BUILDINGS'),
('REQUIREMENT_PLAYER_HAS_MORE_THAN_FOUR_INNS', 'REQUIREMENT_PLAYER_HAS_AT_LEAST_NUM_BUILDINGS'),
('REQUIREMENT_UNIT_IS_DEMON_INHERENT', 'REQUIREMENT_UNIT_HAS_ABILITY'),
('REQUIREMENT_UNIT_IS_DEMON_RACIALIZED', 'REQUIREMENT_UNIT_HAS_ABILITY');

INSERT INTO RequirementArguments(RequirementId, Name, Value) VALUES
('PLAYER_HAS_TOWER_NECROMANCY_REQUIREMENT', 'BuildingType', 'BUILDING_HUEY_TEOCALLI'),
('PLAYER_HAS_TOWER_ELEMENTS_REQUIREMENT', 'BuildingType', 'BUILDING_MEENAKSHI_TEMPLE'),
('PLAYER_HAS_TOWER_DIVINATION_REQUIREMENT', 'BuildingType', 'BUILDING_ORACLE'),
('PLAYER_HAS_TOWER_ALTERATION_REQUIREMENT', 'BuildingType', 'BUILDING_MAHABODHI_TEMPLE'),
('REQUIRES_PLAYER_HAS_MORE_THAN_SEVEN_CITIES', 'Amount', '8'),
('REQUIRES_PLAYER_HAS_MORE_THAN_ELEVEN_CITIES', 'Amount', '12'),
('REQUIREMENT_PLAYER_HAS_MORE_THAN_TWO_LIBRARIES', 'BuildingType', 'BUILDING_LIBRARY'),
('REQUIREMENT_PLAYER_HAS_MORE_THAN_TWO_LIBRARIES', 'Amount', '3'),
('REQUIREMENT_PLAYER_HAS_MORE_THAN_TWO_THEATRES', 'BuildingType', 'BUILDING_AMPHITHEATER'),
('REQUIREMENT_PLAYER_HAS_MORE_THAN_TWO_THEATRES', 'Amount', '3'),
('REQUIREMENT_PLAYER_HAS_MORE_THAN_FOUR_INNS', 'BuildingType', 'SLTH_BUILDING_INN'),
('REQUIREMENT_PLAYER_HAS_MORE_THAN_FOUR_INNS', 'Amount', '5'),
('REQUIREMENT_UNIT_IS_DEMON_INHERENT', 'UnitAbilityType', 'ABILITY_DEMON'),
('REQUIREMENT_UNIT_IS_DEMON_RACIALIZED', 'UnitAbilityType', 'DEMON_ABILITY_HELL_TERRAIN_STRENGTH');

INSERT INTO Requirements(RequirementId, RequirementType) VALUES
('MANA_DEATH_PLOT_PROP_POSITIVE', 'REQUIREMENT_PLOT_PROPERTY_MATCHES'),
('MANA_FIRE_PLOT_PROP_POSITIVE', 'REQUIREMENT_PLOT_PROPERTY_MATCHES'),
('MANA_AIR_PLOT_PROP_POSITIVE', 'REQUIREMENT_PLOT_PROPERTY_MATCHES'),
('MANA_BODY_PLOT_PROP_POSITIVE', 'REQUIREMENT_PLOT_PROPERTY_MATCHES'),
('MANA_CHAOS_PLOT_PROP_POSITIVE', 'REQUIREMENT_PLOT_PROPERTY_MATCHES'),
('MANA_EARTH_PLOT_PROP_POSITIVE', 'REQUIREMENT_PLOT_PROPERTY_MATCHES'),
('MANA_ENCHANTMENT_PLOT_PROP_POSITIVE', 'REQUIREMENT_PLOT_PROPERTY_MATCHES'),
('MANA_ENTROPY_PLOT_PROP_POSITIVE', 'REQUIREMENT_PLOT_PROPERTY_MATCHES'),
('MANA_ICE_PLOT_PROP_POSITIVE', 'REQUIREMENT_PLOT_PROPERTY_MATCHES'),
('MANA_LAW_PLOT_PROP_POSITIVE', 'REQUIREMENT_PLOT_PROPERTY_MATCHES'),
('MANA_LIFE_PLOT_PROP_POSITIVE', 'REQUIREMENT_PLOT_PROPERTY_MATCHES'),
('MANA_METAMAGIC_PLOT_PROP_POSITIVE', 'REQUIREMENT_PLOT_PROPERTY_MATCHES'),
('MANA_MIND_PLOT_PROP_POSITIVE', 'REQUIREMENT_PLOT_PROPERTY_MATCHES'),
('MANA_NATURE_PLOT_PROP_POSITIVE', 'REQUIREMENT_PLOT_PROPERTY_MATCHES'),
('MANA_SPIRIT_PLOT_PROP_POSITIVE', 'REQUIREMENT_PLOT_PROPERTY_MATCHES'),
('MANA_WATER_PLOT_PROP_POSITIVE', 'REQUIREMENT_PLOT_PROPERTY_MATCHES'),
('MANA_SUN_PLOT_PROP_POSITIVE', 'REQUIREMENT_PLOT_PROPERTY_MATCHES'),
('MANA_SHADOW_PLOT_PROP_POSITIVE', 'REQUIREMENT_PLOT_PROPERTY_MATCHES'),
('COPPER_PLOT_PROP_POSITIVE', 'REQUIREMENT_PLOT_PROPERTY_MATCHES'),
('MARBLE_PLOT_PROP_POSITIVE', 'REQUIREMENT_PLOT_PROPERTY_MATCHES');

INSERT INTO RequirementArguments(RequirementId, Name, Value) VALUES
('MANA_DEATH_PLOT_PROP_POSITIVE', 'PropertyName','RESOURCE_MANA_DEATH'),
('MANA_DEATH_PLOT_PROP_POSITIVE', 'PropertyMinimum','1'),
('MANA_FIRE_PLOT_PROP_POSITIVE', 'PropertyName','RESOURCE_MANA_FIRE'),
('MANA_FIRE_PLOT_PROP_POSITIVE', 'PropertyMinimum','1'),
('MANA_AIR_PLOT_PROP_POSITIVE', 'PropertyName','RESOURCE_MANA_AIR'),
('MANA_AIR_PLOT_PROP_POSITIVE', 'PropertyMinimum','1'),
('MANA_BODY_PLOT_PROP_POSITIVE', 'PropertyName','RESOURCE_MANA_BODY'),
('MANA_BODY_PLOT_PROP_POSITIVE', 'PropertyMinimum','1'),
('MANA_CHAOS_PLOT_PROP_POSITIVE', 'PropertyName','RESOURCE_MANA_CHAOS'),
('MANA_CHAOS_PLOT_PROP_POSITIVE', 'PropertyMinimum','1'),
('MANA_EARTH_PLOT_PROP_POSITIVE', 'PropertyName','RESOURCE_MANA_EARTH'),
('MANA_EARTH_PLOT_PROP_POSITIVE', 'PropertyMinimum','1'),
('MANA_ENCHANTMENT_PLOT_PROP_POSITIVE', 'PropertyName','RESOURCE_MANA_ENCHANTMENT'),
('MANA_ENCHANTMENT_PLOT_PROP_POSITIVE', 'PropertyMinimum','1'),
('MANA_ENTROPY_PLOT_PROP_POSITIVE', 'PropertyName','RESOURCE_MANA_ENTROPY'),
('MANA_ENTROPY_PLOT_PROP_POSITIVE', 'PropertyMinimum','1'),
('MANA_ICE_PLOT_PROP_POSITIVE', 'PropertyName','RESOURCE_MANA_ICE'),
('MANA_ICE_PLOT_PROP_POSITIVE', 'PropertyMinimum','1'),
('MANA_LAW_PLOT_PROP_POSITIVE', 'PropertyName','RESOURCE_MANA_LAW'),
('MANA_LAW_PLOT_PROP_POSITIVE', 'PropertyMinimum','1'),
('MANA_LIFE_PLOT_PROP_POSITIVE', 'PropertyName','RESOURCE_MANA_LIFE'),
('MANA_LIFE_PLOT_PROP_POSITIVE', 'PropertyMinimum','1'),
('MANA_METAMAGIC_PLOT_PROP_POSITIVE', 'PropertyName','RESOURCE_MANA_METAMAGIC'),
('MANA_METAMAGIC_PLOT_PROP_POSITIVE', 'PropertyMinimum','1'),
('MANA_MIND_PLOT_PROP_POSITIVE', 'PropertyName','RESOURCE_MANA_MIND'),
('MANA_MIND_PLOT_PROP_POSITIVE', 'PropertyMinimum','1'),
('MANA_NATURE_PLOT_PROP_POSITIVE', 'PropertyName','RESOURCE_MANA_NATURE'),
('MANA_NATURE_PLOT_PROP_POSITIVE', 'PropertyMinimum','1'),
('MANA_SPIRIT_PLOT_PROP_POSITIVE', 'PropertyName','RESOURCE_MANA_SPIRIT'),
('MANA_SPIRIT_PLOT_PROP_POSITIVE', 'PropertyMinimum','1'),
('MANA_WATER_PLOT_PROP_POSITIVE', 'PropertyName','RESOURCE_MANA_WATER'),
('MANA_WATER_PLOT_PROP_POSITIVE', 'PropertyMinimum','1'),
('MANA_SUN_PLOT_PROP_POSITIVE', 'PropertyName','RESOURCE_MANA_SUN'),
('MANA_SUN_PLOT_PROP_POSITIVE', 'PropertyMinimum','1'),
('MANA_SHADOW_PLOT_PROP_POSITIVE', 'PropertyName','RESOURCE_MANA_SHADOW'),
('MANA_SHADOW_PLOT_PROP_POSITIVE', 'PropertyMinimum','1'),
('COPPER_PLOT_PROP_POSITIVE', 'PropertyMinimum','1'),
('MARBLE_PLOT_PROP_POSITIVE', 'PropertyName','RESOURCE_MARBLE'),
('MARBLE_PLOT_PROP_POSITIVE', 'PropertyMinimum','1');




INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
/*
('PLAYER_HAS_ALL_EVIL_MANA', 'REQUIRES_PLAYER_HAS_CHAOS_MANA'),
('PLAYER_HAS_ALL_EVIL_MANA', 'REQUIRES_PLAYER_HAS_DEATH_MANA'),
('PLAYER_HAS_ALL_EVIL_MANA', 'REQUIRES_PLAYER_HAS_ENTROPY_MANA'),
('PLAYER_HAS_ALL_EVIL_MANA', 'REQUIRES_PLAYER_HAS_SHADOW_MANA'),
('PLAYER_HAS_ALL_DIVINATION_MANA', 'REQUIRES_PLAYER_HAS_LAW_MANA'),
('PLAYER_HAS_ALL_DIVINATION_MANA', 'REQUIRES_PLAYER_HAS_MIND_MANA'),
('PLAYER_HAS_ALL_DIVINATION_MANA', 'REQUIRES_PLAYER_HAS_SPIRIT_MANA'),
('PLAYER_HAS_ALL_DIVINATION_MANA', 'REQUIRES_PLAYER_HAS_SUN_MANA'),
('PLAYER_HAS_ALL_ELEMENTS_MANA', 'REQUIRES_PLAYER_HAS_AIR_MANA'),
('PLAYER_HAS_ALL_ELEMENTS_MANA', 'REQUIRES_PLAYER_HAS_EARTH_MANA'),
('PLAYER_HAS_ALL_ELEMENTS_MANA', 'REQUIRES_PLAYER_HAS_FIRE_MANA'),
('PLAYER_HAS_ALL_ELEMENTS_MANA', 'REQUIRES_PLAYER_HAS_WATER_MANA'),
('PLAYER_HAS_ALL_ALTERATION_MANA', 'REQUIRES_PLAYER_HAS_BODY_MANA'),
('PLAYER_HAS_ALL_ALTERATION_MANA', 'REQUIRES_PLAYER_HAS_ENCHANTMENT_MANA'),
('PLAYER_HAS_ALL_ALTERATION_MANA', 'REQUIRES_PLAYER_HAS_LIFE_MANA'),
('PLAYER_HAS_ALL_ALTERATION_MANA', 'REQUIRES_PLAYER_HAS_NATURE_MANA'),
 */
('PLAYER_HAS_ALL_EVIL_MANA', 'MANA_CHAOS_PLOT_PROP_POSITIVE'),                -- from affinities
('PLAYER_HAS_ALL_EVIL_MANA', 'MANA_DEATH_PLOT_PROP_POSITIVE'),
('PLAYER_HAS_ALL_EVIL_MANA', 'MANA_ENTROPY_PLOT_PROP_POSITIVE'),
('PLAYER_HAS_ALL_EVIL_MANA', 'MANA_SHADOW_PLOT_PROP_POSITIVE'),
('PLAYER_HAS_ALL_DIVINATION_MANA', 'MANA_LAW_PLOT_PROP_POSITIVE'),
('PLAYER_HAS_ALL_DIVINATION_MANA', 'MANA_MIND_PLOT_PROP_POSITIVE'),
('PLAYER_HAS_ALL_DIVINATION_MANA', 'MANA_SPIRIT_PLOT_PROP_POSITIVE'),
('PLAYER_HAS_ALL_DIVINATION_MANA', 'MANA_SUN_PLOT_PROP_POSITIVE'),
('PLAYER_HAS_ALL_ELEMENTS_MANA', 'MANA_AIR_PLOT_PROP_POSITIVE'),
('PLAYER_HAS_ALL_ELEMENTS_MANA', 'MANA_EARTH_PLOT_PROP_POSITIVE'),
('PLAYER_HAS_ALL_ELEMENTS_MANA', 'MANA_FIRE_PLOT_PROP_POSITIVE'),
('PLAYER_HAS_ALL_ELEMENTS_MANA', 'MANA_WATER_PLOT_PROP_POSITIVE'),
('PLAYER_HAS_ALL_ALTERATION_MANA', 'MANA_BODY_PLOT_PROP_POSITIVE'),
('PLAYER_HAS_ALL_ALTERATION_MANA', 'MANA_ENCHANTMENT_PLOT_PROP_POSITIVE'),
('PLAYER_HAS_ALL_ALTERATION_MANA', 'MANA_LIFE_PLOT_PROP_POSITIVE'),
('PLAYER_HAS_ALL_ALTERATION_MANA', 'MANA_NATURE_PLOT_PROP_POSITIVE'),

('PLAYER_HAS_ALL_TOWERS', 'PLAYER_HAS_TOWER_NECROMANCY_REQUIREMENT'),
('PLAYER_HAS_ALL_TOWERS', 'PLAYER_HAS_TOWER_ELEMENTS_REQUIREMENT'),
('PLAYER_HAS_ALL_TOWERS', 'PLAYER_HAS_TOWER_DIVINATION_REQUIREMENT'),
('PLAYER_HAS_ALL_TOWERS', 'PLAYER_HAS_TOWER_ALTERATION_REQUIREMENT'),
('PLAYER_HAS_MORE_THAN_SEVEN_CITIES', 'REQUIRES_PLAYER_HAS_MORE_THAN_SEVEN_CITIES'),
('PLAYER_HAS_MORE_THAN_ELEVEN_CITIES', 'REQUIRES_PLAYER_HAS_MORE_THAN_ELEVEN_CITIES'),
('PLAYER_HAS_MORE_THAN_TWO_LIBRARIES', 'REQUIREMENT_PLAYER_HAS_MORE_THAN_TWO_LIBRARIES'),
('PLAYER_HAS_MORE_THAN_TWO_THEATRES', 'REQUIREMENT_PLAYER_HAS_MORE_THAN_TWO_THEATRES'),
('PLAYER_HAS_MORE_THAN_FOUR_INNS', 'REQUIREMENT_PLAYER_HAS_MORE_THAN_FOUR_INNS'),
('PLAYER_HAS_LIFE_MANA', 'MANA_LIFE_PLOT_PROP_POSITIVE'),
('PLAYER_HAS_COPPER', 'COPPER_PLOT_PROP_POSITIVE'),
('PLAYER_HAS_MARBLE', 'MARBLE_PLOT_PROP_POSITIVE'),
('PLAYER_HAS_DEATH_MANA', 'MANA_DEATH_PLOT_PROP_POSITIVE'),
('PLAYER_HAS_ENTROPY_MANA', 'MANA_ENTROPY_PLOT_PROP_POSITIVE'),
('PLAYER_HAS_NATURE_MANA', 'MANA_NATURE_PLOT_PROP_POSITIVE'),
('PLAYER_HAS_LAW_MANA', 'MANA_LAW_PLOT_PROP_POSITIVE'),
('PLAYER_HAS_METAMAGIC_MANA', 'MANA_METAMAGIC_PLOT_PROP_POSITIVE'),
('UNIT_IS_DEMON', 'REQUIREMENT_UNIT_IS_DEMON_INHERENT'),
('UNIT_IS_DEMON', 'REQUIREMENT_UNIT_IS_DEMON_RACIALIZED');

INSERT INTO RequirementSets(RequirementSetId, RequirementSetType) VALUES
('PLAYER_HAS_ALL_EVIL_MANA', 'REQUIREMENTSET_TEST_ALL'),
('PLAYER_HAS_ALL_DIVINATION_MANA', 'REQUIREMENTSET_TEST_ALL'),
('PLAYER_HAS_ALL_ELEMENTS_MANA', 'REQUIREMENTSET_TEST_ALL'),
('PLAYER_HAS_ALL_ALTERATION_MANA', 'REQUIREMENTSET_TEST_ALL'),
('PLAYER_HAS_ALL_TOWERS', 'REQUIREMENTSET_TEST_ALL'),
('PLAYER_HAS_MORE_THAN_SEVEN_CITIES', 'REQUIREMENTSET_TEST_ALL'),
('PLAYER_HAS_MORE_THAN_ELEVEN_CITIES', 'REQUIREMENTSET_TEST_ALL'),
('PLAYER_HAS_MORE_THAN_TWO_THEATRES', 'REQUIREMENTSET_TEST_ALL'),
('PLAYER_HAS_MORE_THAN_TWO_LIBRARIES', 'REQUIREMENTSET_TEST_ALL'),
('PLAYER_HAS_MORE_THAN_FOUR_INNS', 'REQUIREMENTSET_TEST_ALL'),
('PLAYER_HAS_LIFE_MANA', 'REQUIREMENTSET_TEST_ALL'),
('PLAYER_HAS_COPPER', 'REQUIREMENTSET_TEST_ALL'),
('PLAYER_HAS_MARBLE', 'REQUIREMENTSET_TEST_ALL'),
('PLAYER_HAS_DEATH_MANA', 'REQUIREMENTSET_TEST_ALL'),
('PLAYER_HAS_ENTROPY_MANA', 'REQUIREMENTSET_TEST_ALL'),
('PLAYER_HAS_NATURE_MANA', 'REQUIREMENTSET_TEST_ALL'),
('PLAYER_HAS_LAW_MANA', 'REQUIREMENTSET_TEST_ALL'),
('PLAYER_HAS_METAMAGIC_MANA', 'REQUIREMENTSET_TEST_ALL'),
('UNIT_IS_DEMON', 'REQUIREMENTSET_TEST_ANY');

INSERT INTO Buildings(BuildingType, Name, PrereqTech, PrereqCivic, Cost, PrereqDistrict, Description, OuterDefenseHitPoints, Housing, Entertainment, TraitType, CitizenSlots, AdvisorType, RequiresPlacement, IsWonder, MaxWorldInstances) VALUES
('BUILDING_GREAT_LIBRARY', 'LOC_BUILDING_GREAT_LIBRARY_NAME', 'TECH_WRITING', NULL, '350', NULL, 'LOC_BUILDING_GREAT_LIBRARY_DESCRIPTION', '0', '0', '0', NULL, NULL, 'ADVISOR_TECHNOLOGY', '1', '1', '1'),
('BUILDING_BOLSHOI_THEATRE', 'LOC_BUILDING_THEATER_OF_DREAMS_NAME', NULL, 'CIVIC_DRAMA_POETRY', '500', 'DISTRICT_THEATER', 'LOC_BUILDING_THEATER_OF_DREAMS_DESCRIPTION', '0', '0', '1', NULL, '2', 'ADVISOR_CULTURE', '1', '1', '1'),
('SLTH_BUILDING_EYES_AND_EARS_NETWORK', 'LOC_SLTH_BUILDING_EYES_AND_EARS_NETWORK_NAME', NULL, 'CIVIC_GUILDS', '1500', NULL, 'LOC_SLTH_BUILDING_EYES_AND_EARS_NETWORK_DESCRIPTION', '0', '0', '0', NULL, NULL, 'ADVISOR_TECHNOLOGY', '1', '1', '1');

INSERT INTO Building_YieldChanges(BuildingType, YieldType, YieldChange) VALUES
('BUILDING_GREAT_LIBRARY', 'YIELD_CULTURE', 8),
('BUILDING_BOLSHOI_THEATRE', 'YIELD_CULTURE', 8);

INSERT INTO Building_GreatPersonPoints(BuildingType, GreatPersonClassType, PointsPerTurn) VALUES
('BUILDING_GREAT_LIBRARY', 'GREAT_PERSON_CLASS_SCIENTIST', '2'),
('BUILDING_BOLSHOI_THEATRE', 'GREAT_PERSON_CLASS_ARTIST', '2');

INSERT INTO BuildingModifiers(BuildingType, ModifierId) VALUES
('BUILDING_BOLSHOI_THEATRE', 'MODIFIER_BUILDING_BOLSHOI_THEATRE_ADD_AMENITIES');

-- Mercurians are in permanent alliance with builder of the gate
-- eyes and ears network Lua, grant tech if 3 other civs you have open borders with has the tech