-- Hell terrain lives here

-- DESERT HELL: Burning Sands

-- DESERT Can also have burning flames on it

-- obsidian plains: Desert floodplains

-- GrassLand: TERRAIN_BROKEN_LANDS

-- Plains: Fields of Perdition

-- not doing shallows (marsh)

INSERT INTO Features (FeatureType, Name, Appeal, Tiles, Adjacent, Settlement) VALUES
('FEATURE_BURNING_SANDS', 'LOC_FEATURE_BURNING_SANDS_NAME', -1, 1, 1, 1),
('FEATURE_BROKEN_LANDS', 'LOC_FEATURE_BROKEN_LANDS_NAME', -1, 1, 1, 1),
('FEATURE_FIELDS_OF_PERDITION', 'LOC_FEATURE_FIELDS_OF_PERDITION_NAME', -1, 1, 1, 1),
('FEATURE_BURNING_FLAME_SANDS', 'LOC_FEATURE_BURNING_SANDS_NAME', -1, 1, 1, 1),
('FEATURE_OBSIDIAN_PLAINS', 'LOC_FEATURE_OBSIDIAN_PLAINS_NAME', -1, 1, 1, 1);

INSERT INTO Feature_ValidTerrains(FeatureType, TerrainType) VALUES
('FEATURE_BURNING_SANDS', 'TERRAIN_DESERT'),
('FEATURE_BURNING_SANDS', 'TERRAIN_DESERT_HILLS'),
('FEATURE_BURNING_FLAME_SANDS', 'TERRAIN_DESERT'),
('FEATURE_BURNING_FLAME_SANDS', 'TERRAIN_DESERT_HILLS'),
('FEATURE_OBSIDIAN_PLAINS', 'TERRAIN_DESERT'),
('FEATURE_BROKEN_LANDS', 'TERRAIN_GRASS'),
('FEATURE_BROKEN_LANDS', 'TERRAIN_GRASS_HILLS'),
('FEATURE_FIELDS_OF_PERDITION', 'TERRAIN_PLAINS'),
('FEATURE_FIELDS_OF_PERDITION', 'TERRAIN_PLAINS_HILLS');

INSERT INTO Feature_YieldChanges(YieldType, FeatureType, YieldChange) VALUES
('YIELD_FOOD', 'FEATURE_OBSIDIAN_PLAINS', '3');

CREATE TABLE IF NOT EXISTS HellFeatureTerrain(
    FeatureType text primary key,
    TerrainType text);

INSERT INTO HellFeatureTerrain (FeatureType, TerrainType) VALUES
('TERRAIN_DESERT', 'FEATURE_BURNING_SANDS'),
('TERRAIN_DESERT_HILLS','FEATURE_BURNING_SANDS'),
('TERRAIN_GRASS', 'FEATURE_BROKEN_LANDS'),
('TERRAIN_GRASS_HILLS', 'FEATURE_BROKEN_LANDS'),
('TERRAIN_PLAINS', 'FEATURE_FIELDS_OF_PERDITION'),
('TERRAIN_PLAINS_HILLS', 'FEATURE_FIELDS_OF_PERDITION');

-- make sure improvements are valid on them

INSERT INTO Improvement_ValidFeatures(ImprovementType, FeatureType) VALUES
('IMPROVEMENT_FARM', 'FEATURE_BURNING_SANDS'),
('IMPROVEMENT_BARBARIAN_CAMP', 'FEATURE_BURNING_SANDS'),
('IMPROVEMENT_MINE', 'FEATURE_BURNING_SANDS'),
('IMPROVEMENT_QUARRY', 'FEATURE_BURNING_SANDS'),
('IMPROVEMENT_FISHING_BOATS', 'FEATURE_BURNING_SANDS'),
('IMPROVEMENT_PASTURE', 'FEATURE_BURNING_SANDS'),
('IMPROVEMENT_PLANTATION', 'FEATURE_BURNING_SANDS'),
('IMPROVEMENT_CAMP', 'FEATURE_BURNING_SANDS'),
('IMPROVEMENT_LUMBER_MILL', 'FEATURE_BURNING_SANDS'),
('IMPROVEMENT_GOODY_HUT', 'FEATURE_BURNING_SANDS'),
('IMPROVEMENT_FORT', 'FEATURE_BURNING_SANDS'),
('IMPROVEMENT_PIRATE_COVE', 'FEATURE_BURNING_SANDS'),
('IMPROVEMENT_PIRATE_HARBOR', 'FEATURE_BURNING_SANDS'),
('IMPROVEMENT_FEITORIA', 'FEATURE_BURNING_SANDS'),
('IMPROVEMENT_CASTLE', 'FEATURE_BURNING_SANDS'),
('IMPROVEMENT_CITADEL', 'FEATURE_BURNING_SANDS'),
('IMPROVEMENT_VILLAGE', 'FEATURE_BURNING_SANDS'),
('IMPROVEMENT_TOWN', 'FEATURE_BURNING_SANDS'),
('IMPROVEMENT_ENCLAVE', 'FEATURE_BURNING_SANDS'),
('IMPROVEMENT_WINDMILL', 'FEATURE_BURNING_SANDS'),
('IMPROVEMENT_WINERY', 'FEATURE_BURNING_SANDS'),
('IMPROVEMENT_WORKSHOP', 'FEATURE_BURNING_SANDS'),
('IMPROVEMENT_MANA_AIR', 'FEATURE_BURNING_SANDS'),
('IMPROVEMENT_MANA_BODY', 'FEATURE_BURNING_SANDS'),
('IMPROVEMENT_MANA_CHAOS', 'FEATURE_BURNING_SANDS'),
('IMPROVEMENT_MANA_DEATH', 'FEATURE_BURNING_SANDS'),
('IMPROVEMENT_MANA_EARTH', 'FEATURE_BURNING_SANDS'),
('IMPROVEMENT_MANA_ENCHANTMENT', 'FEATURE_BURNING_SANDS'),
('IMPROVEMENT_MANA_ENTROPY', 'FEATURE_BURNING_SANDS'),
('IMPROVEMENT_MANA_FIRE', 'FEATURE_BURNING_SANDS'),
('IMPROVEMENT_MANA_LAW', 'FEATURE_BURNING_SANDS'),
('IMPROVEMENT_MANA_LIFE', 'FEATURE_BURNING_SANDS'),
('IMPROVEMENT_MANA_METAMAGIC', 'FEATURE_BURNING_SANDS'),
('IMPROVEMENT_MANA_MIND', 'FEATURE_BURNING_SANDS'),
('IMPROVEMENT_MANA_NATURE', 'FEATURE_BURNING_SANDS'),
('IMPROVEMENT_MANA_SHADOW', 'FEATURE_BURNING_SANDS'),
('IMPROVEMENT_MANA_SPIRIT', 'FEATURE_BURNING_SANDS'),
('IMPROVEMENT_MANA_SUN', 'FEATURE_BURNING_SANDS'),
('IMPROVEMENT_MANA_WATER', 'FEATURE_BURNING_SANDS'),
('IMPROVEMENT_CITY_RUINS', 'FEATURE_BURNING_SANDS'),
('IMPROVEMENT_COTTAGE', 'FEATURE_BURNING_SANDS'),
('IMPROVEMENT_HAMLET', 'FEATURE_BURNING_SANDS'),

('IMPROVEMENT_FARM', 'FEATURE_BROKEN_LANDS'),
('IMPROVEMENT_BARBARIAN_CAMP', 'FEATURE_BROKEN_LANDS'),
('IMPROVEMENT_MINE', 'FEATURE_BROKEN_LANDS'),
('IMPROVEMENT_QUARRY', 'FEATURE_BROKEN_LANDS'),
('IMPROVEMENT_FISHING_BOATS', 'FEATURE_BROKEN_LANDS'),
('IMPROVEMENT_PASTURE', 'FEATURE_BROKEN_LANDS'),
('IMPROVEMENT_PLANTATION', 'FEATURE_BROKEN_LANDS'),
('IMPROVEMENT_CAMP', 'FEATURE_BROKEN_LANDS'),
('IMPROVEMENT_LUMBER_MILL', 'FEATURE_BROKEN_LANDS'),
('IMPROVEMENT_GOODY_HUT', 'FEATURE_BROKEN_LANDS'),
('IMPROVEMENT_FORT', 'FEATURE_BROKEN_LANDS'),
('IMPROVEMENT_PIRATE_COVE', 'FEATURE_BROKEN_LANDS'),
('IMPROVEMENT_PIRATE_HARBOR', 'FEATURE_BROKEN_LANDS'),
('IMPROVEMENT_FEITORIA', 'FEATURE_BROKEN_LANDS'),
('IMPROVEMENT_CASTLE', 'FEATURE_BROKEN_LANDS'),
('IMPROVEMENT_CITADEL', 'FEATURE_BROKEN_LANDS'),
('IMPROVEMENT_VILLAGE', 'FEATURE_BROKEN_LANDS'),
('IMPROVEMENT_TOWN', 'FEATURE_BROKEN_LANDS'),
('IMPROVEMENT_ENCLAVE', 'FEATURE_BROKEN_LANDS'),
('IMPROVEMENT_WINDMILL', 'FEATURE_BROKEN_LANDS'),
('IMPROVEMENT_WINERY', 'FEATURE_BROKEN_LANDS'),
('IMPROVEMENT_WORKSHOP', 'FEATURE_BROKEN_LANDS'),
('IMPROVEMENT_MANA_AIR', 'FEATURE_BROKEN_LANDS'),
('IMPROVEMENT_MANA_BODY', 'FEATURE_BROKEN_LANDS'),
('IMPROVEMENT_MANA_CHAOS', 'FEATURE_BROKEN_LANDS'),
('IMPROVEMENT_MANA_DEATH', 'FEATURE_BROKEN_LANDS'),
('IMPROVEMENT_MANA_EARTH', 'FEATURE_BROKEN_LANDS'),
('IMPROVEMENT_MANA_ENCHANTMENT', 'FEATURE_BROKEN_LANDS'),
('IMPROVEMENT_MANA_ENTROPY', 'FEATURE_BROKEN_LANDS'),
('IMPROVEMENT_MANA_FIRE', 'FEATURE_BROKEN_LANDS'),
('IMPROVEMENT_MANA_LAW', 'FEATURE_BROKEN_LANDS'),
('IMPROVEMENT_MANA_LIFE', 'FEATURE_BROKEN_LANDS'),
('IMPROVEMENT_MANA_METAMAGIC', 'FEATURE_BROKEN_LANDS'),
('IMPROVEMENT_MANA_MIND', 'FEATURE_BROKEN_LANDS'),
('IMPROVEMENT_MANA_NATURE', 'FEATURE_BROKEN_LANDS'),
('IMPROVEMENT_MANA_SHADOW', 'FEATURE_BROKEN_LANDS'),
('IMPROVEMENT_MANA_SPIRIT', 'FEATURE_BROKEN_LANDS'),
('IMPROVEMENT_MANA_SUN', 'FEATURE_BROKEN_LANDS'),
('IMPROVEMENT_MANA_WATER', 'FEATURE_BROKEN_LANDS'),
('IMPROVEMENT_CITY_RUINS', 'FEATURE_BROKEN_LANDS'),
('IMPROVEMENT_COTTAGE', 'FEATURE_BROKEN_LANDS'),
('IMPROVEMENT_HAMLET', 'FEATURE_BROKEN_LANDS'),

('IMPROVEMENT_FARM', 'FEATURE_FIELDS_OF_PERDITION'),
('IMPROVEMENT_BARBARIAN_CAMP', 'FEATURE_FIELDS_OF_PERDITION'),
('IMPROVEMENT_MINE', 'FEATURE_FIELDS_OF_PERDITION'),
('IMPROVEMENT_QUARRY', 'FEATURE_FIELDS_OF_PERDITION'),
('IMPROVEMENT_FISHING_BOATS', 'FEATURE_FIELDS_OF_PERDITION'),
('IMPROVEMENT_PASTURE', 'FEATURE_FIELDS_OF_PERDITION'),
('IMPROVEMENT_PLANTATION', 'FEATURE_FIELDS_OF_PERDITION'),
('IMPROVEMENT_CAMP', 'FEATURE_FIELDS_OF_PERDITION'),
('IMPROVEMENT_LUMBER_MILL', 'FEATURE_FIELDS_OF_PERDITION'),
('IMPROVEMENT_GOODY_HUT', 'FEATURE_FIELDS_OF_PERDITION'),
('IMPROVEMENT_FORT', 'FEATURE_FIELDS_OF_PERDITION'),
('IMPROVEMENT_PIRATE_COVE', 'FEATURE_FIELDS_OF_PERDITION'),
('IMPROVEMENT_PIRATE_HARBOR', 'FEATURE_FIELDS_OF_PERDITION'),
('IMPROVEMENT_FEITORIA', 'FEATURE_FIELDS_OF_PERDITION'),
('IMPROVEMENT_CASTLE', 'FEATURE_FIELDS_OF_PERDITION'),
('IMPROVEMENT_CITADEL', 'FEATURE_FIELDS_OF_PERDITION'),
('IMPROVEMENT_VILLAGE', 'FEATURE_FIELDS_OF_PERDITION'),
('IMPROVEMENT_TOWN', 'FEATURE_FIELDS_OF_PERDITION'),
('IMPROVEMENT_ENCLAVE', 'FEATURE_FIELDS_OF_PERDITION'),
('IMPROVEMENT_WINDMILL', 'FEATURE_FIELDS_OF_PERDITION'),
('IMPROVEMENT_WINERY', 'FEATURE_FIELDS_OF_PERDITION'),
('IMPROVEMENT_WORKSHOP', 'FEATURE_FIELDS_OF_PERDITION'),
('IMPROVEMENT_MANA_AIR', 'FEATURE_FIELDS_OF_PERDITION'),
('IMPROVEMENT_MANA_BODY', 'FEATURE_FIELDS_OF_PERDITION'),
('IMPROVEMENT_MANA_CHAOS', 'FEATURE_FIELDS_OF_PERDITION'),
('IMPROVEMENT_MANA_DEATH', 'FEATURE_FIELDS_OF_PERDITION'),
('IMPROVEMENT_MANA_EARTH', 'FEATURE_FIELDS_OF_PERDITION'),
('IMPROVEMENT_MANA_ENCHANTMENT', 'FEATURE_FIELDS_OF_PERDITION'),
('IMPROVEMENT_MANA_ENTROPY', 'FEATURE_FIELDS_OF_PERDITION'),
('IMPROVEMENT_MANA_FIRE', 'FEATURE_FIELDS_OF_PERDITION'),
('IMPROVEMENT_MANA_LAW', 'FEATURE_FIELDS_OF_PERDITION'),
('IMPROVEMENT_MANA_LIFE', 'FEATURE_FIELDS_OF_PERDITION'),
('IMPROVEMENT_MANA_METAMAGIC', 'FEATURE_FIELDS_OF_PERDITION'),
('IMPROVEMENT_MANA_MIND', 'FEATURE_FIELDS_OF_PERDITION'),
('IMPROVEMENT_MANA_NATURE', 'FEATURE_FIELDS_OF_PERDITION'),
('IMPROVEMENT_MANA_SHADOW', 'FEATURE_FIELDS_OF_PERDITION'),
('IMPROVEMENT_MANA_SPIRIT', 'FEATURE_FIELDS_OF_PERDITION'),
('IMPROVEMENT_MANA_SUN', 'FEATURE_FIELDS_OF_PERDITION'),
('IMPROVEMENT_MANA_WATER', 'FEATURE_FIELDS_OF_PERDITION'),
('IMPROVEMENT_CITY_RUINS', 'FEATURE_FIELDS_OF_PERDITION'),
('IMPROVEMENT_COTTAGE', 'FEATURE_FIELDS_OF_PERDITION'),
('IMPROVEMENT_HAMLET', 'FEATURE_FIELDS_OF_PERDITION');


-- non hell features
INSERT INTO Features(FeatureType, Name, SightThroughModifier, NoCoast, NoRiver, RequiresRiver) VALUES
('FEATURE_FOREST_ANCIENT', 'LOC_SLTH_FEATURE_FOREST_ANCIENT_NAME', '1', '1', '1', '0');

INSERT INTO Feature_ValidTerrains(FeatureType, TerrainType) VALUES
('FEATURE_FOREST_ANCIENT', 'TERRAIN_GRASS'),
('FEATURE_FOREST_ANCIENT', 'TERRAIN_PLAINS'),
('FEATURE_FOREST_ANCIENT', 'TERRAIN_TUNDRA');

INSERT INTO Feature_YieldChanges(YieldType, FeatureType, YieldChange) VALUES
('YIELD_FOOD', 'FEATURE_FOREST_ANCIENT', '1'),
('YIELD_PRODUCTION', 'FEATURE_FOREST_ANCIENT', '1');


INSERT INTO Types(Type, Kind) VALUES
('FEATURE_BURNING_SANDS', 'KIND_FEATURE'),
('FEATURE_BURNING_FLAME_SANDS', 'KIND_FEATURE'),
('FEATURE_OBSIDIAN_PLAINS', 'KIND_FEATURE'),
('FEATURE_BROKEN_LANDS', 'KIND_FEATURE'),
('FEATURE_FIELDS_OF_PERDITION', 'KIND_FEATURE'),
('FEATURE_FOREST_ANCIENT', 'KIND_FEATURE');
