INSERT INTO Traits(TraitType, Name, Description) VALUES
('SLTH_TRAIT_AGGRESSIVE', 'LOC_SLTH_TRAIT_AGGRESSIVE_NAME', 'LOC_SLTH_TRAIT_AGGRESSIVE_DESCRIPTION'),
('SLTH_TRAIT_ARCANE', 'LOC_SLTH_TRAIT_ARCANE_NAME', 'LOC_SLTH_TRAIT_ARCANE_DESCRIPTION'),
('SLTH_TRAIT_CHARISMATIC', 'LOC_SLTH_TRAIT_CHARISMATIC_NAME', 'LOC_SLTH_TRAIT_CHARISMATIC_DESCRIPTION'),
('SLTH_TRAIT_CREATIVE', 'LOC_SLTH_TRAIT_CREATIVE_NAME', 'LOC_SLTH_TRAIT_CREATIVE_DESCRIPTION'),
('SLTH_TRAIT_DEFENDER', 'LOC_SLTH_TRAIT_DEFENDER_NAME', 'LOC_SLTH_TRAIT_DEFENDER_DESCRIPTION'),
('SLTH_TRAIT_EXPANSIVE', 'LOC_SLTH_TRAIT_EXPANSIVE_NAME', 'LOC_SLTH_TRAIT_EXPANSIVE_DESCRIPTION'),
('SLTH_TRAIT_FINANCIAL', 'LOC_SLTH_TRAIT_FINANCIAL_NAME', 'LOC_SLTH_TRAIT_FINANCIAL_DESCRIPTION'),
('SLTH_TRAIT_INDUSTRIOUS', 'LOC_SLTH_TRAIT_INDUSTRIOUS_NAME', 'LOC_SLTH_TRAIT_INDUSTRIOUS_DESCRIPTION'),
('SLTH_TRAIT_INGENUITY', 'LOC_SLTH_TRAIT_INGENUITY_NAME', 'LOC_SLTH_TRAIT_INGENUITY_DESCRIPTION'),
('SLTH_TRAIT_ORGANIZED', 'LOC_SLTH_TRAIT_ORGANIZED_NAME', 'LOC_SLTH_TRAIT_ORGANIZED_DESCRIPTION'),
('SLTH_TRAIT_PHILOSOPHICAL', 'LOC_SLTH_TRAIT_PHILOSOPHICAL_NAME', 'LOC_SLTH_TRAIT_PHILOSOPHICAL_DESCRIPTION'),
('SLTH_TRAIT_SPIRITUAL', 'LOC_SLTH_TRAIT_SPIRITUAL_NAME', 'LOC_SLTH_TRAIT_SPIRITUAL_DESCRIPTION'),
('SLTH_TRAIT_SUMMONER', 'LOC_SLTH_TRAIT_SUMMONER_NAME', 'LOC_SLTH_TRAIT_SUMMONER_DESCRIPTION'),
('SLTH_TRAIT_RAIDERS', 'LOC_SLTH_TRAIT_RAIDERS_NAME', 'LOC_SLTH_TRAIT_RAIDERS_DESCRIPTION'),
('SLTH_TRAIT_BARBARIAN', 'LOC_SLTH_TRAIT_BARBARIAN_NAME', 'LOC_SLTH_TRAIT_BARBARIAN_DESCRIPTION'),
('SLTH_TRAIT_INSANE', 'LOC_SLTH_TRAIT_INSANE_NAME', 'LOC_SLTH_TRAIT_INSANE_DESCRIPTION'),
('SLTH_TRAIT_ADAPTIVE', 'LOC_SLTH_TRAIT_ADAPTIVE_NAME', 'LOC_SLTH_TRAIT_ADAPTIVE_DESCRIPTION');

-- implement perpetach separately
INSERT INTO LeaderTraits(LeaderType, TraitType) VALUES
('LEADER_VALLEDIA', 'SLTH_TRAIT_ARCANE'),
('LEADER_VALLEDIA', 'SLTH_TRAIT_ORGANIZED'),
('LEADER_DAIN', 'SLTH_TRAIT_ARCANE'),
('LEADER_DAIN', 'SLTH_TRAIT_PHILOSOPHICAL'),
('LEADER_KEELYN', 'SLTH_TRAIT_CREATIVE'),
('LEADER_KEELYN', 'SLTH_TRAIT_SUMMONER'),
('LEADER_SABATHIEL', 'SLTH_TRAIT_CHARISMATIC'),
('LEADER_SABATHIEL', 'SLTH_TRAIT_ORGANIZED'),
('LEADER_CAPRIA', 'SLTH_TRAIT_INDUSTRIOUS'),
('LEADER_CAPRIA', 'SLTH_TRAIT_SPIRITUAL'),
('LEADER_DECIUS_BANNOR', 'SLTH_TRAIT_ORGANIZED'),
('LEADER_DECIUS_BANNOR', 'SLTH_TRAIT_RAIDERS'),
('LEADER_DECIUS_MALAKIM', 'SLTH_TRAIT_ORGANIZED'),
('LEADER_DECIUS_MALAKIM', 'SLTH_TRAIT_RAIDERS'),
('LEADER_DECIUS_CALABIM', 'SLTH_TRAIT_ORGANIZED'),
('LEADER_DECIUS_CALABIM', 'SLTH_TRAIT_RAIDERS'),
('LEADER_ALEXIS', 'SLTH_TRAIT_AGGRESSIVE'),
('LEADER_ALEXIS', 'SLTH_TRAIT_PHILOSOPHICAL'),
('LEADER_FLAUROS', 'SLTH_TRAIT_FINANCIAL'),
('LEADER_FLAUROS', 'SLTH_TRAIT_ORGANIZED'),
('LEADER_ETHNE', 'SLTH_TRAIT_CREATIVE'),
('LEADER_ETHNE', 'SLTH_TRAIT_DEFENDER'),
('LEADER_EINION', 'SLTH_TRAIT_PHILOSOPHICAL'),
('LEADER_EINION', 'SLTH_TRAIT_DEFENDER'),
('LEADER_CASSIEL', 'SLTH_TRAIT_INDUSTRIOUS'),
('LEADER_CASSIEL', 'SLTH_TRAIT_ADAPTIVE'),
('LEADER_TASUNKE', 'SLTH_TRAIT_AGGRESSIVE'),
('LEADER_TASUNKE', 'SLTH_TRAIT_RAIDERS'),
('LEADER_RHOANNA', 'SLTH_TRAIT_FINANCIAL'),
('LEADER_RHOANNA', 'SLTH_TRAIT_EXPANSIVE'),
('LEADER_HYBOREM', 'SLTH_TRAIT_EXPANSIVE'),
('LEADER_HYBOREM', 'SLTH_TRAIT_SUMMONER'),
('LEADER_HYBOREM', 'SLTH_TRAIT_BARBARIAN'),
('LEADER_CARDITH', 'SLTH_TRAIT_EXPANSIVE'),
('LEADER_CARDITH', 'SLTH_TRAIT_ADAPTIVE'),
('LEADER_FALAMAR', 'SLTH_TRAIT_CHARISMATIC'),
('LEADER_FALAMAR', 'SLTH_TRAIT_EXPANSIVE'),
('LEADER_HANNAH', 'SLTH_TRAIT_FINANCIAL'),
('LEADER_HANNAH', 'SLTH_TRAIT_RAIDERS'),
('LEADER_VARN', 'SLTH_TRAIT_CREATIVE'),
('LEADER_VARN', 'SLTH_TRAIT_SPIRITUAL'),
('LEADER_BASIUM', 'SLTH_TRAIT_AGGRESSIVE'),
('LEADER_BASIUM', 'SLTH_TRAIT_RAIDERS'),
('LEADER_BASIUM', 'SLTH_TRAIT_INGENUITY'),
('LEADER_TEBRYN', 'SLTH_TRAIT_ARCANE'),
('LEADER_TEBRYN', 'SLTH_TRAIT_SUMMONER'),
('LEADER_OS_GABELLA', 'SLTH_TRAIT_INDUSTRIOUS'),
('LEADER_OS_GABELLA', 'SLTH_TRAIT_SPIRITUAL'),
('LEADER_JONAS', 'SLTH_TRAIT_EXPANSIVE'),
('LEADER_JONAS', 'SLTH_TRAIT_SPIRITUAL'),
('LEADER_JONAS', 'SLTH_TRAIT_BARBARIAN'),
('LEADER_SHEELBA', 'SLTH_TRAIT_ORGANIZED'),
('LEADER_SHEELBA', 'SLTH_TRAIT_AGGRESSIVE'),
('LEADER_SHEELBA', 'SLTH_TRAIT_BARBARIAN'),
('LEADER_AMELANCHIER', 'SLTH_TRAIT_DEFENDER'),
('LEADER_AMELANCHIER', 'SLTH_TRAIT_RAIDERS'),
('LEADER_ARENDEL', 'SLTH_TRAIT_CREATIVE'),
('LEADER_ARENDEL', 'SLTH_TRAIT_SPIRITUAL'),
('LEADER_THESSA', 'SLTH_TRAIT_ARCANE'),
('LEADER_THESSA', 'SLTH_TRAIT_EXPANSIVE'),
('LEADER_FAERYL', 'SLTH_TRAIT_ARCANE'),
('LEADER_FAERYL', 'SLTH_TRAIT_RAIDERS'),
('LEADER_ARTURUS', 'SLTH_TRAIT_INDUSTRIOUS'),
('LEADER_ARTURUS', 'SLTH_TRAIT_ORGANIZED'),
('LEADER_ARTURUS', 'SLTH_TRAIT_INGENUITY'),
('LEADER_KANDROS', 'SLTH_TRAIT_AGGRESSIVE'),
('LEADER_KANDROS', 'SLTH_TRAIT_FINANCIAL'),
('LEADER_KANDROS', 'SLTH_TRAIT_INGENUITY'),
('LEADER_GARRIM', 'SLTH_TRAIT_DEFENDER'),
('LEADER_GARRIM', 'SLTH_TRAIT_FINANCIAL'),
('LEADER_BEERI', 'SLTH_TRAIT_INDUSTRIOUS'),
('LEADER_BEERI', 'SLTH_TRAIT_ORGANIZED'),
('LEADER_SANDALPHON', 'SLTH_TRAIT_INDUSTRIOUS'),
('LEADER_SANDALPHON', 'SLTH_TRAIT_DEFENDER'),
('LEADER_CHARADON', 'SLTH_TRAIT_AGGRESSIVE'),
('LEADER_CHARADON', 'SLTH_TRAIT_BARBARIAN'),
('LEADER_MAHALA', 'SLTH_TRAIT_RAIDERS'),
('LEADER_MAHALA', 'SLTH_TRAIT_INGENUITY'),
('LEADER_AURIC', 'SLTH_TRAIT_CHARISMATIC'),
('LEADER_AURIC', 'SLTH_TRAIT_DEFENDER'),
('LEADER_PERPENTACH', 'SLTH_TRAIT_INSANE');

-- would be nice to do agenda behaviours here too
INSERT INTO TraitModifiers(TraitType, ModifierId) VALUES
('SLTH_TRAIT_AGGRESSIVE', 'SLTH_SHIPYARD_DOUBLE'),
('SLTH_TRAIT_AGGRESSIVE', 'SLTH_SIEGE_WORKSHOP_DOUBLE'),
('SLTH_TRAIT_AGGRESSIVE', 'SLTH_AGGRESSIVE_GRANT_COMBAT_ONE_MELEE'),
('SLTH_TRAIT_AGGRESSIVE', 'SLTH_AGGRESSIVE_GRANT_COMBAT_ONE_CAV'),
('SLTH_TRAIT_ARCANE', 'SLTH_MAGE_GUILD_DOUBLE'),
('SLTH_TRAIT_ARCANE', 'SLTH_ARCANE_POTENCY_ATTACH'),
('SLTH_TRAIT_BARBARIAN', 'SLTH_BARBARIAN_SCIENCE_LOSS'),
('SLTH_TRAIT_CHARISMATIC', 'SLTH_CHARISMATIC_ONE_AMENITY'),
('SLTH_TRAIT_CHARISMATIC', 'SLTH_CHARISMATIC_MORE_XP_ATTACH'),
('SLTH_TRAIT_CREATIVE', 'SLTH_CREATIVE_FREE_CULTURE'),
('SLTH_TRAIT_CREATIVE', 'SLTH_CREATIVE_MONUMENT_DOUBLE'),
('SLTH_TRAIT_CREATIVE', 'SLTH_CREATIVE_CARNIVAL_DOUBLE'),
('SLTH_TRAIT_DEFENDER', 'SLTH_ABILITY_DEFENDER_GRANT_HOMELAND_ATTACH'),
('SLTH_TRAIT_DEFENDER', 'LIMES_WALLSPRODUCTION'),
('SLTH_TRAIT_DEFENDER', 'LIMES_CASTLEPRODUCTION'),
('SLTH_TRAIT_DEFENDER', 'SLTH_ARCHERY_RANGE_DOUBLE'),
('SLTH_TRAIT_EXPANSIVE', 'SLTH_EXPANSIVE_HOUSING'),
('SLTH_TRAIT_EXPANSIVE', 'SLTH_EXPANSIVE_SETTLER_DOUBLE_PRODUCTION'),
('SLTH_TRAIT_EXPANSIVE', 'SLTH_EXPANSIVE_HARBOR_DOUBLE_PROD'),
('SLTH_TRAIT_EXPANSIVE', 'SLTH_EXPANSIVE_GRANARY_DOUBLE_PROD'),
('SLTH_TRAIT_FINANCIAL', 'SLTH_FINANCIAL_MARKET_DOUBLE_PROD'),
('SLTH_TRAIT_FINANCIAL', 'SLTH_FINANCIAL_MONEYCHANGER_DOUBLE_PROD'),
('SLTH_TRAIT_INDUSTRIOUS', 'SLTH_INDUSTRIOUS_WONDER_PROD'),
('SLTH_TRAIT_INDUSTRIOUS', 'SLTH_INDUSTRIOUS_FORGE_DOUBLE_PROD'),
('SLTH_TRAIT_INGENUITY', 'GOODY_GOLD_LARGE_MODIFIER'),                  -- borrowed from goodyHut
('SLTH_TRAIT_INGENUITY', 'PROFESSIONAL_ARMY_UNITUPGRADEDISCOUNT'),      -- Guild Of Hammers on wiki says change extra 25%
('SLTH_TRAIT_ORGANIZED', 'SLTH_ORGANIZED_LIGHTHOUSE_DOUBLE_PROD'),
('SLTH_TRAIT_ORGANIZED', 'SLTH_ORGANIZED_COURTHOUSE_DOUBLE_PROD'),
('SLTH_TRAIT_PHILOSOPHICAL', 'SLTH_PHILOSOPHICAL_DOUBLE_GPP_ATTACH'),
('SLTH_TRAIT_PHILOSOPHICAL', 'SLTH_PHILOSOPHICAL_DOUBLE_ELDER_COUNCIL'),
('SLTH_TRAIT_PHILOSOPHICAL', 'SLTH_PHILOSOPHICAL_DOUBLE_LIBRARY'),
('SLTH_TRAIT_RAIDERS', 'SLTH_RAIDERS_DOUBLEPILLAGEIMPROVE'),
('SLTH_TRAIT_RAIDERS', 'SLTH_RAIDERS_DOUBLEPILLAGEDISTRICT'),
('SLTH_TRAIT_SUMMONER', 'SLTH_SUMMONER_ATTACH'),                        -- May be a Lua check, so need to examine for that
('SLTH_TRAIT_SPIRITUAL', 'SLTH_SPIRITUAL_PAGAN_TEMPLE_DOUBLE_PROD'),
('SLTH_TRAIT_SPIRITUAL', 'SLTH_SPIRITUAL_LEAVES_TEMPLE_DOUBLE_PROD'),
('SLTH_TRAIT_SPIRITUAL', 'SLTH_SPIRITUAL_KILMORPH_TEMPLE_DOUBLE_PROD'),
('SLTH_TRAIT_SPIRITUAL', 'SLTH_SPIRITUAL_OVERLORDS_TEMPLE_DOUBLE_PROD'),
('SLTH_TRAIT_SPIRITUAL', 'SLTH_SPIRITUAL_VEIL_TEMPLE_DOUBLE_PROD'),
('SLTH_TRAIT_SPIRITUAL', 'SLTH_SPIRITUAL_ORDER_TEMPLE_DOUBLE_PROD'),
('SLTH_TRAIT_SPIRITUAL', 'SLTH_SPIRITUAL_EMPYREAN_TEMPLE_DOUBLE_PROD'),
('SLTH_TRAIT_SPIRITUAL', 'SLTH_SPIRITUAL_POTENCY_ATTACH');              -- todo, anarchy free

-- modifiers with reqs
INSERT INTO RequirementSets(RequirementSetId, RequirementSetType) VALUES
('SLTH_DISTRICT_IS_CITY_CENTRE_REQS', 'REQUIREMENTSET_TEST_ALL');
INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('SLTH_DISTRICT_IS_CITY_CENTRE_REQS', 'REQUIRES_DISTRICT_IS_CITY_CENTER');
INSERT INTO Modifiers(ModifierId, ModifierType, SubjectRequirementSetId) VALUES
('SLTH_CREATIVE_FREE_CULTURE', 'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_CHANGE', 'SLTH_DISTRICT_IS_CITY_CENTRE_REQS'),
('SLTH_HOMELAND_BONUS_IN_FRIENDLY_TERRITORY', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', 'FRIENDLY_TERRITORY_REQUIREMENTS');           -- borrowed from global coaltion
INSERT INTO ModifierArguments(ModifierId, Name, "Value") VALUES
('SLTH_CREATIVE_FREE_CULTURE', 'YieldType', 'YIELD_CULTURE'),
('SLTH_CREATIVE_FREE_CULTURE', 'Amount', '2'),
('SLTH_HOMELAND_BONUS_IN_FRIENDLY_TERRITORY', 'Amount', 2);

-- abilitiy attachers
INSERT INTO UnitAbilities(UnitAbilityType, Name, Description, Inactive, ShowFloatTextWhenEarned, Permanent) VALUES
('SLTH_ABILITY_CHARISMATIC_MORE_XP', 'LOC_SLTH_ABILITY_CHARISMATIC_MORE_XP_NAME', 'LOC_SLTH_ABILITY_CHARISMATIC_MORE_XP_DESCRIPTION', '1', '0', '1'),
('SLTH_ABILITY_HOMELAND', 'LOC_SLTH_ABILITY_CHARISMATIC_MORE_XP_NAME', 'LOC_SLTH_ABILITY_CHARISMATIC_MORE_XP_DESCRIPTION', '1', '0', '1'),
('SLTH_ABILITY_SUMMONER', 'LOC_SLTH_ABILITY_SUMMONER_NAME', 'LOC_SLTH_ABILITY_SUMMONER_DESCRIPTION', '1', '0', '1'),
('SLTH_ABILITY_POTENCY', 'LOC_SLTH_ABILITY_POTENCY_NAME', 'LOC_SLTH_ABILITY_POTENCY_DESCRIPTION', '1', '0', '1');

INSERT INTO UnitAbilityModifiers(UnitAbilityType, ModifierId) VALUES
('SLTH_ABILITY_CHARISMATIC_MORE_XP', 'SLTH_CHARISMATIC_MORE_XP'),
('SLTH_ABILITY_HOMELAND', 'SLTH_HOMELAND_BONUS_IN_FRIENDLY_TERRITORY');        -- withdrawal chance not implemented as not relevant

INSERT INTO Modifiers(ModifierId, ModifierType) VALUES
('SLTH_CHARISMATIC_MORE_XP_ATTACH', 'MODIFIER_PLAYER_UNITS_GRANT_ABILITY'),
('SLTH_ABILITY_DEFENDER_GRANT_HOMELAND_ATTACH', 'MODIFIER_PLAYER_UNITS_GRANT_ABILITY'),
('SLTH_SUMMONER_ATTACH', 'MODIFIER_PLAYER_UNITS_GRANT_ABILITY');

INSERT INTO Modifiers(ModifierId, ModifierType, SubjectRequirementSetId) VALUES
('SLTH_SPIRITUAL_POTENCY_ATTACH', 'MODIFIER_PLAYER_UNITS_GRANT_ABILITY', 'UNIT_IS_DISCIPLE_REQS'),
('SLTH_ARCANE_POTENCY_ATTACH', 'MODIFIER_PLAYER_UNITS_GRANT_ABILITY', 'UNIT_IS_ADEPT_REQS'),
('SLTH_AGGRESSIVE_GRANT_COMBAT_ONE_MELEE', 'MODIFIER_PLAYER_UNITS_GRANT_PROMOTION', 'UNIT_IS_PROMO_CLASS_MELEE_REQS'),
('SLTH_AGGRESSIVE_GRANT_COMBAT_ONE_CAV', 'MODIFIER_PLAYER_UNITS_GRANT_PROMOTION', 'UNIT_IS_PROMO_CLASS_CAV_REQS');

INSERT INTO ModifierArguments(ModifierId, Name, Type, Value) VALUES
('SLTH_CHARISMATIC_MORE_XP_ATTACH', 'AbilityType', 'ARGTYPE_IDENTITY', 'SLTH_CHARISMATIC_MORE_XP'),
('SLTH_ABILITY_DEFENDER_GRANT_HOMELAND_ATTACH', 'AbilityType', 'ARGTYPE_IDENTITY', 'SLTH_ABILITY_HOMELAND'),
('SLTH_SUMMONER_ATTACH', 'AbilityType', 'ARGTYPE_IDENTITY', 'SLTH_ABILITY_SUMMONER'),
('SLTH_SPIRITUAL_POTENCY_ATTACH', 'AbilityType', 'ARGTYPE_IDENTITY', 'SLTH_ABILITY_POTENCY'),
('SLTH_ARCANE_POTENCY_ATTACH', 'AbilityType', 'ARGTYPE_IDENTITY', 'SLTH_ABILITY_POTENCY'),
('SLTH_AGGRESSIVE_GRANT_COMBAT_ONE_MELEE', 'PromotionType', 'ARGTYPE_IDENTITY','PROMOTION_COMBAT1_MELEE'),
('SLTH_AGGRESSIVE_GRANT_COMBAT_ONE_CAV', 'PromotionType', 'ARGTYPE_IDENTITY', 'PROMOTION_COMBAT1_LIGHT_CAVALRY');

INSERT INTO Requirements(RequirementId, RequirementType) VALUES
('SLTH_UNIT_IS_DISCIPLE', 'REQUIREMENT_UNIT_PROMOTION_CLASS_MATCHES'),
('SLTH_UNIT_IS_ADEPT_CLASS', 'REQUIREMENT_UNIT_PROMOTION_CLASS_MATCHES');

INSERT INTO RequirementArguments(RequirementId, Name, "Value") VALUES
('SLTH_UNIT_IS_DISCIPLE', 'UnitPromotionClass', 'PROMOTION_CLASS_DISCIPLE'),
('SLTH_UNIT_IS_ADEPT_CLASS', 'UnitPromotionClass', 'PROMOTION_CLASS_ADEPT');

INSERT INTO TypeTags(Type, Tag) VALUES
('SLTH_ABILITY_CHARISMATIC_MORE_XP', 'CLASS_ALL_UNITS'),
('SLTH_ABILITY_HOMELAND', 'CLASS_ALL_UNITS'),    -- its technically more restrictive but oh well
('SLTH_ABILITY_SUMMONER', 'CLASS_ALL_UNITS'),
('SLTH_ABILITY_POTENCY', 'CLASS_DISCIPLE');

INSERT INTO Modifiers(ModifierId, ModifierType) VALUES
('SLTH_SHIPYARD_DOUBLE', 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_PRODUCTION'),
('SLTH_SIEGE_WORKSHOP_DOUBLE', 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_PRODUCTION'),
('SPIRITUAL_GRANT_MOBILITY', 'MODIFIER_PLAYER_UNITS_GRANT_PROMOTION'),
('SLTH_MAGE_GUILD_DOUBLE', 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_PRODUCTION'),
('SLTH_CREATIVE_MONUMENT_DOUBLE', 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_PRODUCTION'),
('SLTH_CREATIVE_CARNIVAL_DOUBLE', 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_PRODUCTION'),
('SLTH_ARCHERY_RANGE_DOUBLE', 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_PRODUCTION'),
('SLTH_EXPANSIVE_HARBOR_DOUBLE_PROD', 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_PRODUCTION'),
('SLTH_EXPANSIVE_GRANARY_DOUBLE_PROD', 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_PRODUCTION'),
('SLTH_FINANCIAL_MARKET_DOUBLE_PROD', 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_PRODUCTION'),
('SLTH_FINANCIAL_MONEYCHANGER_DOUBLE_PROD', 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_PRODUCTION'),
('SLTH_INDUSTRIOUS_FORGE_DOUBLE_PROD', 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_PRODUCTION'),
('SLTH_INDUSTRIOUS_WONDER_PROD', 'MODIFIER_PLAYER_CITIES_ADJUST_WONDER_PRODUCTION'),
('SLTH_CHARISMATIC_MORE_XP', 'MODIFIER_PLAYER_UNIT_ADJUST_UNIT_EXPERIENCE_MODIFIER'),
('SLTH_ORGANIZED_LIGHTHOUSE_DOUBLE_PROD', 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_PRODUCTION'),
('SLTH_ORGANIZED_COURTHOUSE_DOUBLE_PROD', 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_PRODUCTION'),
('SLTH_PHILOSOPHICAL_DOUBLE_ELDER_COUNCIL', 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_PRODUCTION'),
('SLTH_PHILOSOPHICAL_DOUBLE_LIBRARY', 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_PRODUCTION'),
('SLTH_SPIRITUAL_PAGAN_TEMPLE_DOUBLE_PROD', 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_PRODUCTION'),
('SLTH_SPIRITUAL_LEAVES_TEMPLE_DOUBLE_PROD', 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_PRODUCTION'),
('SLTH_SPIRITUAL_KILMORPH_TEMPLE_DOUBLE_PROD', 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_PRODUCTION'),
('SLTH_SPIRITUAL_OVERLORDS_TEMPLE_DOUBLE_PROD', 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_PRODUCTION'),
('SLTH_SPIRITUAL_VEIL_TEMPLE_DOUBLE_PROD', 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_PRODUCTION'),
('SLTH_SPIRITUAL_ORDER_TEMPLE_DOUBLE_PROD', 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_PRODUCTION'),
('SLTH_SPIRITUAL_EMPYREAN_TEMPLE_DOUBLE_PROD', 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_PRODUCTION'),
('SLTH_CHARISMATIC_ONE_AMENITY', 'MODIFIER_PLAYER_CITIES_ADJUST_POLICY_AMENITY'),
('SLTH_EXPANSIVE_SETTLER_DOUBLE_PRODUCTION', 'MODIFIER_PLAYER_UNITS_ADJUST_UNIT_PRODUCTION'),
('SLTH_EXPANSIVE_HOUSING', 'MODIFIER_PLAYER_CITIES_ADJUST_POLICY_HOUSING'),
('SLTH_PHILOSOPHICAL_DOUBLE_GPP_ATTACH', 'MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER'),
('SLTH_RAIDERS_DOUBLEPILLAGEIMPROVE', 'MODIFIER_PLAYER_ADJUST_IMPROVEMENT_PILLAGE'),
('SLTH_RAIDERS_DOUBLEPILLAGEDISTRICT', 'MODIFIER_PLAYER_ADJUST_DISTRICT_PILLAGE'),
('SLTH_BARBARIAN_SCIENCE_LOSS', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER');

INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
('SLTH_SHIPYARD_DOUBLE', 'BuildingType', 'BUILDING_SHIPYARD'),
('SLTH_SHIPYARD_DOUBLE', 'Amount', '100'),
('SLTH_SIEGE_WORKSHOP_DOUBLE', 'BuildingType', 'SLTH_BUILDING_SIEGE_WORKSHOP'),
('SLTH_SIEGE_WORKSHOP_DOUBLE', 'Amount', '100'),
('SLTH_MAGE_GUILD_DOUBLE', 'BuildingType', 'BUILDING_MAGE_GUILD'),
('SLTH_MAGE_GUILD_DOUBLE', 'Amount', '100'),
('SLTH_CREATIVE_MONUMENT_DOUBLE', 'BuildingType', 'BUILDING_MONUMENT'),
('SLTH_CREATIVE_MONUMENT_DOUBLE', 'Amount', '100'),
('SLTH_CREATIVE_CARNIVAL_DOUBLE', 'BuildingType', 'SLTH_BUILDING_CARNIVAL'),
('SLTH_CREATIVE_CARNIVAL_DOUBLE', 'Amount', '100'),
('SLTH_ARCHERY_RANGE_DOUBLE', 'BuildingType', 'SLTH_BUILDING_ARCHERY_RANGE'),
('SLTH_ARCHERY_RANGE_DOUBLE', 'Amount', '100'),
('SLTH_EXPANSIVE_HARBOR_DOUBLE_PROD', 'BuildingType', 'SLTH_BUILDING_HARBOR'),
('SLTH_EXPANSIVE_HARBOR_DOUBLE_PROD', 'Amount', '100'),
('SLTH_EXPANSIVE_GRANARY_DOUBLE_PROD', 'BuildingType', 'BUILDING_GRANARY'),
('SLTH_EXPANSIVE_GRANARY_DOUBLE_PROD', 'Amount', '100'),
('SLTH_FINANCIAL_MARKET_DOUBLE_PROD', 'BuildingType', 'BUILDING_MARKET'),
('SLTH_FINANCIAL_MARKET_DOUBLE_PROD', 'Amount', '100'),
('SLTH_FINANCIAL_MONEYCHANGER_DOUBLE_PROD', 'BuildingType', 'BUILDING_BANK'),
('SLTH_FINANCIAL_MONEYCHANGER_DOUBLE_PROD', 'Amount', '100'),
('SLTH_INDUSTRIOUS_FORGE_DOUBLE_PROD', 'BuildingType', 'BUILDING_WORKSHOP'),
('SLTH_INDUSTRIOUS_FORGE_DOUBLE_PROD', 'Amount', '100'),
('SLTH_ORGANIZED_LIGHTHOUSE_DOUBLE_PROD', 'BuildingType', 'BUILDING_LIGHTHOUSE'),
('SLTH_ORGANIZED_LIGHTHOUSE_DOUBLE_PROD', 'Amount', '100'),
('SLTH_ORGANIZED_COURTHOUSE_DOUBLE_PROD', 'BuildingType', 'BUILDING_QUEENS_BIBLIOTHEQUE'),
('SLTH_ORGANIZED_COURTHOUSE_DOUBLE_PROD', 'Amount', '100'),
('SLTH_PHILOSOPHICAL_DOUBLE_ELDER_COUNCIL', 'BuildingType', 'SLTH_BUILDING_ELDER_COUNCIL'),
('SLTH_PHILOSOPHICAL_DOUBLE_ELDER_COUNCIL', 'Amount', '100'),
('SLTH_PHILOSOPHICAL_DOUBLE_LIBRARY', 'BuildingType', 'BUILDING_LIBRARY'),
('SLTH_PHILOSOPHICAL_DOUBLE_LIBRARY', 'Amount', '100'),
('SLTH_SPIRITUAL_PAGAN_TEMPLE_DOUBLE_PROD', 'BuildingType', 'BUILDING_SHRINE'),
('SLTH_SPIRITUAL_PAGAN_TEMPLE_DOUBLE_PROD', 'Amount', '100'),
('SLTH_SPIRITUAL_LEAVES_TEMPLE_DOUBLE_PROD', 'BuildingType', 'BUILDING_SANCTUARY'),
('SLTH_SPIRITUAL_LEAVES_TEMPLE_DOUBLE_PROD', 'Amount', '100'),
('SLTH_SPIRITUAL_KILMORPH_TEMPLE_DOUBLE_PROD', 'BuildingType', 'BUILDING_WAT'),
('SLTH_SPIRITUAL_KILMORPH_TEMPLE_DOUBLE_PROD', 'Amount', '100'),
('SLTH_SPIRITUAL_OVERLORDS_TEMPLE_DOUBLE_PROD', 'BuildingType', 'BUILDING_MOSQUE'),
('SLTH_SPIRITUAL_OVERLORDS_TEMPLE_DOUBLE_PROD', 'Amount', '100'),
('SLTH_SPIRITUAL_VEIL_TEMPLE_DOUBLE_PROD', 'BuildingType', 'BUILDING_STUPA'),
('SLTH_SPIRITUAL_VEIL_TEMPLE_DOUBLE_PROD', 'Amount', '100'),
('SLTH_SPIRITUAL_ORDER_TEMPLE_DOUBLE_PROD', 'BuildingType', 'BUILDING_CATHEDRAL'),
('SLTH_SPIRITUAL_ORDER_TEMPLE_DOUBLE_PROD', 'Amount', '100'),
('SLTH_SPIRITUAL_EMPYREAN_TEMPLE_DOUBLE_PROD', 'BuildingType', 'BUILDING_GURDWARA'),
('SLTH_SPIRITUAL_EMPYREAN_TEMPLE_DOUBLE_PROD', 'Amount', '100'),
('SLTH_INDUSTRIOUS_WONDER_PROD', 'Amount', '50'),
('SLTH_EXPANSIVE_SETTLER_DOUBLE_PRODUCTION', 'UnitType', 'UNIT_SETTLER'),
('SLTH_EXPANSIVE_SETTLER_DOUBLE_PRODUCTION', 'Amount', '100'),
('SLTH_EXPANSIVE_HOUSING', 'Amount', '3'),
('SLTH_PHILOSOPHICAL_DOUBLE_GPP_ATTACH', 'ModifierId', 'MODIFIER_NATIONAL_EPIC_INCREASE_GPP_MULT'),
('SLTH_RAIDERS_DOUBLEPILLAGEIMPROVE', 'Amount', '100'),
('SLTH_RAIDERS_DOUBLEPILLAGEDISTRICT', 'Amount', '100'),
('SLTH_CHARISMATIC_ONE_AMENITY', 'Amount', '1'),
('SLTH_CHARISMATIC_MORE_XP', 'Amount', '33'),
('SLTH_BARBARIAN_SCIENCE_LOSS', 'YieldType', 'YIELD_SCIENCE'),
('SLTH_BARBARIAN_SCIENCE_LOSS', 'Amount', '-10');

-- diplo modifiers
INSERT INTO TraitModifiers(TraitType, ModifierId) VALUES
('TRAIT_LEADER_MAJOR_CIV', 'STANDARD_DIPLOMATIC_CHARISMATIC_INTERACTION');

INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
('STANDARD_DIPLOMATIC_CHARISMATIC_INTERACTION', 'SimpleModifierDescription', 'LOC_TOOLTIP_SAMPLE_DIPLOMACY_CHARISMATIC'),
('STANDARD_DIPLOMATIC_CHARISMATIC_INTERACTION', 'InitialValue', '5');

INSERT INTO Modifiers(ModifierId, ModifierType, SubjectRequirementSetId) VALUES
('STANDARD_DIPLOMATIC_CHARISMATIC_INTERACTION', 'MODIFIER_PLAYER_DIPLOMACY_SIMPLE_MODIFIER', 'OPPOSING_PLAYER_IS_CHARISMATIC');

INSERT INTO ModifierStrings(ModifierId, Context, Text) VALUES
('STANDARD_DIPLOMATIC_CHARISMATIC_INTERACTION', 'Sample', 'LOC_DIPLO_CHARISMA');

INSERT INTO RequirementSets(RequirementSetId, RequirementSetType) VALUES
('OPPOSING_PLAYER_IS_CHARISMATIC', 'REQUIREMENTSET_TEST_ALL'),
('UNIT_IS_PROMO_CLASS_MELEE_REQS', 'REQUIREMENTSET_TEST_ALL'),
('UNIT_IS_PROMO_CLASS_CAV_REQS', 'REQUIREMENTSET_TEST_ALL');

INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('OPPOSING_PLAYER_IS_CHARISMATIC', 'REQUIRE_PLAYER_IS_CHARISMATIC'),
('OPPOSING_PLAYER_IS_CHARISMATIC', 'REQUIRES_PLAYERS_HAVE_MET'),
('UNIT_IS_PROMO_CLASS_MELEE_REQS', 'REQUIREMENT_UNIT_IS_MELEE'),
('UNIT_IS_PROMO_CLASS_CAV_REQS', 'UNIT_IS_LIGHT_CAVALRY');

INSERT INTO Requirements(RequirementId, RequirementType) VALUES
('REQUIRE_PLAYER_IS_CHARISMATIC', 'REQUIREMENT_REQUIREMENTSET_IS_MET');

INSERT INTO RequirementArguments(RequirementId, Name, Type, Value) VALUES
('REQUIRE_PLAYER_IS_CHARISMATIC', 'RequirementSetId', 'ARGTYPE_IDENTITY', 'IS_ANY_CHARISMATIC_TRAIT_LEADER');

INSERT INTO RequirementSets(RequirementSetId, RequirementSetType) VALUES
('IS_ANY_CHARISMATIC_TRAIT_LEADER', 'REQUIREMENTSET_TEST_ANY'),
('UNIT_IS_DISCIPLE_REQS', 'REQUIREMENTSET_TEST_ANY'),
('UNIT_IS_ADEPT_REQS', 'REQUIREMENTSET_TEST_ANY');


INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('IS_ANY_CHARISMATIC_TRAIT_LEADER', 'FALAMAR_REQUIREMENTS'),
('IS_ANY_CHARISMATIC_TRAIT_LEADER', 'SABATHIEL_REQUIREMENTS'),
('IS_ANY_CHARISMATIC_TRAIT_LEADER', 'AURIC_REQUIREMENTS'),
('UNIT_IS_DISCIPLE_REQS', 'SLTH_UNIT_IS_DISCIPLE'),
('UNIT_IS_ADEPT_REQS', 'SLTH_UNIT_IS_ADEPT_CLASS');

INSERT INTO Requirements(RequirementId, RequirementType) VALUES
('FALAMAR_REQUIREMENTS', 'REQUIREMENT_PLAYER_LEADER_TYPE_MATCHES'),
('SABATHIEL_REQUIREMENTS', 'REQUIREMENT_PLAYER_LEADER_TYPE_MATCHES'),
('AURIC_REQUIREMENTS', 'REQUIREMENT_PLAYER_LEADER_TYPE_MATCHES');

INSERT INTO RequirementArguments(RequirementId, Name, Value) VALUES
('FALAMAR_REQUIREMENTS', 'LeaderType', 'LEADER_FALAMAR'),
('SABATHIEL_REQUIREMENTS', 'LeaderType', 'LEADER_SABATHIEL'),
('AURIC_REQUIREMENTS', 'LeaderType', 'LEADER_AURIC');


INSERT INTO Types(Type, Kind) VALUES
('SLTH_TRAIT_AGGRESSIVE', 'KIND_TRAIT'),
('SLTH_TRAIT_ARCANE', 'KIND_TRAIT'),
('SLTH_TRAIT_CHARISMATIC', 'KIND_TRAIT'),
('SLTH_TRAIT_CREATIVE', 'KIND_TRAIT'),
('SLTH_TRAIT_DEFENDER', 'KIND_TRAIT'),
('SLTH_TRAIT_EXPANSIVE', 'KIND_TRAIT'),
('SLTH_TRAIT_FINANCIAL', 'KIND_TRAIT'),
('SLTH_TRAIT_INDUSTRIOUS', 'KIND_TRAIT'),
('SLTH_TRAIT_INGENUITY', 'KIND_TRAIT'),
('SLTH_TRAIT_ORGANIZED', 'KIND_TRAIT'),
('SLTH_TRAIT_PHILOSOPHICAL', 'KIND_TRAIT'),
('SLTH_TRAIT_SPIRITUAL', 'KIND_TRAIT'),
('SLTH_TRAIT_SUMMONER', 'KIND_TRAIT'),
('SLTH_TRAIT_RAIDERS', 'KIND_TRAIT'),
('SLTH_TRAIT_BARBARIAN', 'KIND_TRAIT'),
('SLTH_TRAIT_INSANE', 'KIND_TRAIT'),
('SLTH_TRAIT_ADAPTIVE', 'KIND_TRAIT'),
('SLTH_ABILITY_CHARISMATIC_MORE_XP', 'KIND_ABILITY'),
('SLTH_ABILITY_SUMMONER', 'KIND_ABILITY'),
('SLTH_ABILITY_POTENCY', 'KIND_ABILITY'),
('SLTH_ABILITY_HOMELAND', 'KIND_ABILITY');
-- arcane, charasmatic, creative, defender, expansive, financial, INDUSTRIOUS, ingenuity, organized,
-- Philosophical, Spiritual, Summoner

-- ACTUALLY ON civ level:  agnostic, barbarian, fallow, horselord, Sprawling,

-- hard: adaptive, insane, cant do property as we only have plot property. Do plot property on capital,
-- Raiders is hard because road movement is free.


-- DuplicateLeaders (Decius)
INSERT INTO DuplicateLeaders(LeaderType, OtherLeaderType) VALUES
('LEADER_DECIUS_BANNOR', 'LEADER_DECIUS_CALABIM'),
('LEADER_DECIUS_CALABIM', 'LEADER_DECIUS_MALAKIM');

-- Perpentach/Adaptive traits have to exist as strange modifiers checking capital city plots

INSERT INTO Modifiers(ModifierId, ModifierType, SubjectRequirementSetId) VALUES
('SHIPYARD_DOUBLE_INSANE', 'MODIFIER_ATTACH_MODIFIER_TO_OWNER_PLAYER', 'PLAYER_HAS_VARIABLE_AGGRESSIVE'),              -- also need to do the free promotion
('SIEGE_WORKSHOP_DOUBLE_INSANE', 'MODIFIER_ATTACH_MODIFIER_TO_OWNER_PLAYER', 'PLAYER_HAS_VARIABLE_AGGRESSIVE'),
('GRANT_MOBILITY', 'MODIFIER_PLAYER_UNITS_GRANT_PROMOTION', 'PLAYER_HAS_VARIABLE_SPIRITUAL'),
('MAGE_GUILD_DOUBLE_INSANE', 'MODIFIER_ATTACH_MODIFIER_TO_OWNER_PLAYER', 'PLAYER_HAS_VARIABLE_ARCANE'),
('MONUMENT_DOUBLE_INSANE', 'MODIFIER_ATTACH_MODIFIER_TO_OWNER_PLAYER', 'PLAYER_HAS_VARIABLE_CREATIVE'),
('CARNIVAL_DOUBLE_INSANE', 'MODIFIER_ATTACH_MODIFIER_TO_OWNER_PLAYER', 'PLAYER_HAS_VARIABLE_CREATIVE'),
('ARCHERY_RANGE_DOUBLE_INSANE', 'MODIFIER_ATTACH_MODIFIER_TO_OWNER_PLAYER', 'PLAYER_HAS_VARIABLE_DEFENDER'),
('HARBOR_DOUBLE_PROD_INSANE', 'MODIFIER_ATTACH_MODIFIER_TO_OWNER_PLAYER', 'PLAYER_HAS_VARIABLE_EXPANSIVE'),
('GRANARY_DOUBLE_PROD_INSANE', 'MODIFIER_ATTACH_MODIFIER_TO_OWNER_PLAYER', 'PLAYER_HAS_VARIABLE_EXPANSIVE'),
('MARKET_DOUBLE_PROD_INSANE', 'MODIFIER_ATTACH_MODIFIER_TO_OWNER_PLAYER', 'PLAYER_HAS_VARIABLE_FINANCIAL'),
('MONEYCHANGER_DOUBLE_PROD_INSANE', 'MODIFIER_ATTACH_MODIFIER_TO_OWNER_PLAYER', 'PLAYER_HAS_VARIABLE_FINANCIAL'),
('FINANCIAL_PLOT_COMMERCE_INSANE', 'MODIFIER_ATTACH_MODIFIER_TO_OWNER_PLAYER', 'PLAYER_HAS_VARIABLE_FINANCIAL'),
('FORGE_DOUBLE_PROD_INSANE', 'MODIFIER_ATTACH_MODIFIER_TO_OWNER_PLAYER', 'PLAYER_HAS_VARIABLE_INDUSTRIOUS'),
('WONDER_PROD_INSANE', 'MODIFIER_ATTACH_MODIFIER_TO_OWNER_PLAYER', 'PLAYER_HAS_VARIABLE_INDUSTRIOUS'),
('MORE_XP_INSANE', 'MODIFIER_ATTACH_MODIFIER_TO_OWNER_PLAYER', 'PLAYER_HAS_VARIABLE_CHARISMATIC'),
('LIGHTHOUSE_DOUBLE_PROD_INSANE', 'MODIFIER_ATTACH_MODIFIER_TO_OWNER_PLAYER', 'PLAYER_HAS_VARIABLE_ORGANIZED'),
('COURTHOUSE_DOUBLE_PROD_INSANE', 'MODIFIER_ATTACH_MODIFIER_TO_OWNER_PLAYER', 'PLAYER_HAS_VARIABLE_ORGANIZED'),
('DOUBLE_ELDER_COUNCIL_INSANE', 'MODIFIER_ATTACH_MODIFIER_TO_OWNER_PLAYER', 'PLAYER_HAS_VARIABLE_PHILOSOPHICAL'),
('DOUBLE_LIBRARY_INSANE', 'MODIFIER_ATTACH_MODIFIER_TO_OWNER_PLAYER', 'PLAYER_HAS_VARIABLE_PHILOSOPHICAL'),
('PAGAN_TEMPLE_DOUBLE_PROD_INSANE', 'MODIFIER_ATTACH_MODIFIER_TO_OWNER_PLAYER', 'PLAYER_HAS_VARIABLE_SPIRITUAL'),
('LEAVES_TEMPLE_DOUBLE_PROD_INSANE', 'MODIFIER_ATTACH_MODIFIER_TO_OWNER_PLAYER', 'PLAYER_HAS_VARIABLE_SPIRITUAL'),
('KILMORPH_TEMPLE_DOUBLE_PROD_INSANE', 'MODIFIER_ATTACH_MODIFIER_TO_OWNER_PLAYER', 'PLAYER_HAS_VARIABLE_SPIRITUAL'),
('OVERLORDS_TEMPLE_DOUBLE_PROD_INSANE', 'MODIFIER_ATTACH_MODIFIER_TO_OWNER_PLAYER', 'PLAYER_HAS_VARIABLE_SPIRITUAL'),
('VEIL_TEMPLE_DOUBLE_PROD_INSANE', 'MODIFIER_ATTACH_MODIFIER_TO_OWNER_PLAYER', 'PLAYER_HAS_VARIABLE_SPIRITUAL'),
('ORDER_TEMPLE_DOUBLE_PROD_INSANE', 'MODIFIER_ATTACH_MODIFIER_TO_OWNER_PLAYER', 'PLAYER_HAS_VARIABLE_SPIRITUAL'),
('EMPYREAN_TEMPLE_DOUBLE_PROD_INSANE', 'MODIFIER_ATTACH_MODIFIER_TO_OWNER_PLAYER', 'PLAYER_HAS_VARIABLE_SPIRITUAL'),
('ONE_AMENITY_INSANE', 'MODIFIER_ATTACH_MODIFIER_TO_OWNER_PLAYER', 'PLAYER_HAS_VARIABLE_CHARISMATIC'),
('SETTLER_DOUBLE_PRODUCTION_INSANE', 'MODIFIER_ATTACH_MODIFIER_TO_OWNER_PLAYER', 'PLAYER_HAS_VARIABLE_EXPANSIVE'),
('HOUSING_INSANE', 'MODIFIER_ATTACH_MODIFIER_TO_OWNER_PLAYER', 'PLAYER_HAS_VARIABLE_EXPANSIVE'),
('DOUBLE_GPP_ATTACH_INSANE', 'MODIFIER_ATTACH_MODIFIER_TO_OWNER_PLAYER', 'PLAYER_HAS_VARIABLE_PHILOSOPHICAL'),
('DOUBLEPILLAGEIMPROVE_INSANE', 'MODIFIER_ATTACH_MODIFIER_TO_OWNER_PLAYER', 'PLAYER_HAS_VARIABLE_RAIDERS'),
('DOUBLEPILLAGEDISTRICT_INSANE', 'MODIFIER_ATTACH_MODIFIER_TO_OWNER_PLAYER', 'PLAYER_HAS_VARIABLE_RAIDERS'),
('FREE_CULTURE_INSANE', 'MODIFIER_ATTACH_MODIFIER_TO_OWNER_PLAYER', 'PLAYER_HAS_VARIABLE_CREATIVE'),
('BONUS_IN_FRIENDLY_TERRITORY_INSANE', 'MODIFIER_ATTACH_MODIFIER_TO_OWNER_PLAYER', 'PLAYER_HAS_VARIABLE_DEFENDER'),
('MORE_XP_ATTACH_INSANE', 'MODIFIER_ATTACH_MODIFIER_TO_OWNER_PLAYER', 'PLAYER_HAS_VARIABLE_CHARISMATIC'),
('GRANT_HOMELAND_ATTACH_INSANE', 'MODIFIER_ATTACH_MODIFIER_TO_OWNER_PLAYER', 'PLAYER_HAS_VARIABLE_DEFENDER'),
('LIMES_WALLSPRODUCTION_INSANE', 'MODIFIER_ATTACH_MODIFIER_TO_OWNER_PLAYER', 'PLAYER_HAS_VARIABLE_DEFENDER'),
('LIMES_CASTLEPRODUCTION_INSANE', 'MODIFIER_ATTACH_MODIFIER_TO_OWNER_PLAYER', 'PLAYER_HAS_VARIABLE_DEFENDER'),
('SUMMONER_ATTACH_INSANE', 'MODIFIER_ATTACH_MODIFIER_TO_OWNER_PLAYER', 'PLAYER_HAS_VARIABLE_SUMMONER'),
('POTENCY_ATTACH_INSANE', 'MODIFIER_ATTACH_MODIFIER_TO_OWNER_PLAYER', 'PLAYER_HAS_VARIABLE_SPIRITUAL'),
('MAGE_POTENCY_ATTACH_INSANE', 'MODIFIER_ATTACH_MODIFIER_TO_OWNER_PLAYER', 'PLAYER_HAS_VARIABLE_ARCANE'),
('GRANT_COMBAT_ONE_MELEE_INSANE', 'MODIFIER_ATTACH_MODIFIER_TO_OWNER_PLAYER', 'PLAYER_HAS_VARIABLE_AGGRESSIVE'),
('GRANT_COMBAT_ONE_CAV_INSANE', 'MODIFIER_ATTACH_MODIFIER_TO_OWNER_PLAYER', 'PLAYER_HAS_VARIABLE_AGGRESSIVE');


INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
('SHIPYARD_DOUBLE_INSANE', 'ModifierId', 'SLTH_SHIPYARD_DOUBLE'),
('SIEGE_WORKSHOP_DOUBLE_INSANE', 'ModifierId', 'SLTH_SIEGE_WORKSHOP_DOUBLE'),
('MAGE_GUILD_DOUBLE_INSANE', 'ModifierId', 'SLTH_MAGE_GUILD_DOUBLE'),
('MONUMENT_DOUBLE_INSANE', 'ModifierId', 'SLTH_CREATIVE_MONUMENT_DOUBLE'),
('CARNIVAL_DOUBLE_INSANE', 'ModifierId', 'SLTH_CREATIVE_CARNIVAL_DOUBLE'),
('ARCHERY_RANGE_DOUBLE_INSANE', 'ModifierId', 'SLTH_ARCHERY_RANGE_DOUBLE'),
('HARBOR_DOUBLE_PROD_INSANE', 'ModifierId', 'SLTH_EXPANSIVE_HARBOR_DOUBLE_PROD'),
('GRANARY_DOUBLE_PROD_INSANE', 'ModifierId', 'SLTH_EXPANSIVE_GRANARY_DOUBLE_PROD'),
('MARKET_DOUBLE_PROD_INSANE', 'ModifierId', 'SLTH_FINANCIAL_MARKET_DOUBLE_PROD'),
('MONEYCHANGER_DOUBLE_PROD_INSANE', 'ModifierId', 'SLTH_FINANCIAL_MONEYCHANGER_DOUBLE_PROD'),
('FINANCIAL_PLOT_COMMERCE_INSANE', 'ModifierId', 'SLTH_FINANCIAL_COMMERCE_ON_PLOTS_WITH_2_COMMERCE'),
('FORGE_DOUBLE_PROD_INSANE', 'ModifierId', 'SLTH_INDUSTRIOUS_FORGE_DOUBLE_PROD'),
('LIGHTHOUSE_DOUBLE_PROD_INSANE', 'ModifierId', 'SLTH_ORGANIZED_LIGHTHOUSE_DOUBLE_PROD'),
('COURTHOUSE_DOUBLE_PROD_INSANE', 'ModifierId', 'SLTH_ORGANIZED_COURTHOUSE_DOUBLE_PROD'),
('DOUBLE_ELDER_COUNCIL_INSANE', 'ModifierId', 'SLTH_PHILOSOPHICAL_DOUBLE_ELDER_COUNCIL'),
('DOUBLE_LIBRARY_INSANE', 'ModifierId', 'SLTH_PHILOSOPHICAL_DOUBLE_LIBRARY'),
('PAGAN_TEMPLE_DOUBLE_PROD_INSANE', 'ModifierId', 'SLTH_SPIRITUAL_PAGAN_TEMPLE_DOUBLE_PROD'),
('LEAVES_TEMPLE_DOUBLE_PROD_INSANE', 'ModifierId', 'SLTH_SPIRITUAL_LEAVES_TEMPLE_DOUBLE_PROD'),
('KILMORPH_TEMPLE_DOUBLE_PROD_INSANE', 'ModifierId', 'SLTH_SPIRITUAL_KILMORPH_TEMPLE_DOUBLE_PROD'),
('OVERLORDS_TEMPLE_DOUBLE_PROD_INSANE', 'ModifierId', 'SLTH_SPIRITUAL_OVERLORDS_TEMPLE_DOUBLE_PROD'),
('VEIL_TEMPLE_DOUBLE_PROD_INSANE', 'ModifierId', 'SLTH_SPIRITUAL_VEIL_TEMPLE_DOUBLE_PROD'),
('ORDER_TEMPLE_DOUBLE_PROD_INSANE', 'ModifierId', 'SLTH_SPIRITUAL_ORDER_TEMPLE_DOUBLE_PROD'),
('EMPYREAN_TEMPLE_DOUBLE_PROD_INSANE', 'ModifierId', 'SLTH_SPIRITUAL_EMPYREAN_TEMPLE_DOUBLE_PROD'),
('WONDER_PROD_INSANE', 'ModifierId', 'SLTH_INDUSTRIOUS_WONDER_PROD'),
('SETTLER_DOUBLE_PRODUCTION_INSANE', 'ModifierId', 'SLTH_EXPANSIVE_SETTLER_DOUBLE_PRODUCTION'),
('HOUSING_INSANE', 'ModifierId', 'SLTH_EXPANSIVE_HOUSING'),
('DOUBLE_GPP_ATTACH_INSANE', 'ModifierId', 'SLTH_PHILOSOPHICAL_DOUBLE_GPP_ATTACH'),
('DOUBLEPILLAGEIMPROVE_INSANE', 'ModifierId', 'SLTH_RAIDERS_DOUBLEPILLAGEIMPROVE'),
('DOUBLEPILLAGEDISTRICT_INSANE', 'ModifierId', 'SLTH_RAIDERS_DOUBLEPILLAGEDISTRICT'),
('ONE_AMENITY_INSANE', 'ModifierId', 'SLTH_CHARISMATIC_ONE_AMENITY'),
('MORE_XP_INSANE', 'ModifierId', 'SLTH_CHARISMATIC_MORE_XP'),
('FREE_CULTURE_INSANE', 'ModifierId', 'SLTH_CREATIVE_FREE_CULTURE'),
('BONUS_IN_FRIENDLY_TERRITORY_INSANE', 'ModifierId', 'SLTH_HOMELAND_BONUS_IN_FRIENDLY_TERRITORY'),
('MORE_XP_ATTACH_INSANE', 'ModifierId', 'SLTH_CHARISMATIC_MORE_XP_ATTACH'),
('GRANT_HOMELAND_ATTACH_INSANE', 'ModifierId', 'SLTH_ABILITY_DEFENDER_GRANT_HOMELAND_ATTACH'),
('LIMES_WALLSPRODUCTION_INSANE', 'ModifierId', 'LIMES_WALLSPRODUCTION'),
('LIMES_CASTLEPRODUCTION_INSANE', 'ModifierId', 'LIMES_CASTLEPRODUCTION'),
('SUMMONER_ATTACH_INSANE', 'ModifierId', 'SLTH_SUMMONER_ATTACH'),
('POTENCY_ATTACH_INSANE', 'ModifierId', 'SLTH_SPIRITUAL_POTENCY_ATTACH'),
('MAGE_POTENCY_ATTACH_INSANE', 'ModifierId', 'SLTH_ARCANE_POTENCY_ATTACH'),
('GRANT_COMBAT_ONE_MELEE_INSANE', 'ModifierId', 'SLTH_AGGRESSIVE_GRANT_COMBAT_ONE_MELEE'),
('GRANT_COMBAT_ONE_CAV_INSANE', 'ModifierId', 'SLTH_AGGRESSIVE_GRANT_COMBAT_ONE_CAV');

INSERT INTO TraitModifiers(TraitType, ModifierId) VALUES
('SLTH_TRAIT_INSANE', 'SHIPYARD_DOUBLE_INSANE'),
('SLTH_TRAIT_INSANE', 'SIEGE_WORKSHOP_DOUBLE_INSANE'),
('SLTH_TRAIT_INSANE', 'GRANT_COMBAT_ONE_MELEE_INSANE'),
('SLTH_TRAIT_INSANE', 'GRANT_COMBAT_ONE_CAV_INSANE'),
('SLTH_TRAIT_INSANE', 'MAGE_GUILD_DOUBLE_INSANE'),
('SLTH_TRAIT_INSANE', 'MAGE_POTENCY_ATTACH_INSANE'),
('SLTH_TRAIT_INSANE', 'ONE_AMENITY_INSANE'),
('SLTH_TRAIT_INSANE', 'MORE_XP_ATTACH_INSANE'),
('SLTH_TRAIT_INSANE', 'FREE_CULTURE_INSANE'),
('SLTH_TRAIT_INSANE', 'MONUMENT_DOUBLE_INSANE'),
('SLTH_TRAIT_INSANE', 'CARNIVAL_DOUBLE_INSANE'),
('SLTH_TRAIT_INSANE', 'GRANT_HOMELAND_ATTACH_INSANE'),
('SLTH_TRAIT_INSANE', 'LIMES_WALLSPRODUCTION_INSANE'),
('SLTH_TRAIT_INSANE', 'LIMES_CASTLEPRODUCTION_INSANE'),
('SLTH_TRAIT_INSANE', 'ARCHERY_RANGE_DOUBLE_INSANE'),
('SLTH_TRAIT_INSANE', 'HOUSING_INSANE'),
('SLTH_TRAIT_INSANE', 'SETTLER_DOUBLE_PRODUCTION_INSANE'),
('SLTH_TRAIT_INSANE', 'HARBOR_DOUBLE_PROD_INSANE'),
('SLTH_TRAIT_INSANE', 'GRANARY_DOUBLE_PROD_INSANE'),
('SLTH_TRAIT_INSANE', 'MARKET_DOUBLE_PROD_INSANE'),
('SLTH_TRAIT_INSANE', 'MONEYCHANGER_DOUBLE_PROD_INSANE'),             -- FINANCE PROPER PLOT STUFF
('SLTH_TRAIT_INSANE', 'FINANCIAL_PLOT_COMMERCE_INSANE'),
('SLTH_TRAIT_INSANE', 'WONDER_PROD_INSANE'),
('SLTH_TRAIT_INSANE', 'FORGE_DOUBLE_PROD_INSANE'),
('SLTH_TRAIT_INSANE', 'LIGHTHOUSE_DOUBLE_PROD_INSANE'),
('SLTH_TRAIT_INSANE', 'COURTHOUSE_DOUBLE_PROD_INSANE'),
('SLTH_TRAIT_INSANE', 'DOUBLE_GPP_ATTACH_INSANE'),
('SLTH_TRAIT_INSANE', 'DOUBLE_ELDER_COUNCIL_INSANE'),
('SLTH_TRAIT_INSANE', 'DOUBLE_LIBRARY_INSANE'),
('SLTH_TRAIT_INSANE', 'DOUBLEPILLAGEIMPROVE_INSANE'),
('SLTH_TRAIT_INSANE', 'DOUBLEPILLAGEDISTRICT_INSANE'),
('SLTH_TRAIT_INSANE', 'SUMMONER_ATTACH_INSANE'),                        -- May be a Lua check, so need to examine for that
('SLTH_TRAIT_INSANE', 'PAGAN_TEMPLE_DOUBLE_PROD_INSANE'),
('SLTH_TRAIT_INSANE', 'LEAVES_TEMPLE_DOUBLE_PROD_INSANE'),
('SLTH_TRAIT_INSANE', 'KILMORPH_TEMPLE_DOUBLE_PROD_INSANE'),
('SLTH_TRAIT_INSANE', 'OVERLORDS_TEMPLE_DOUBLE_PROD_INSANE'),
('SLTH_TRAIT_INSANE', 'VEIL_TEMPLE_DOUBLE_PROD_INSANE'),
('SLTH_TRAIT_INSANE', 'ORDER_TEMPLE_DOUBLE_PROD_INSANE'),
('SLTH_TRAIT_INSANE', 'EMPYREAN_TEMPLE_DOUBLE_PROD_INSANE'),
('SLTH_TRAIT_INSANE', 'POTENCY_ATTACH_INSANE');

INSERT INTO RequirementSets(RequirementSetId, RequirementSetType) VALUES
('PLAYER_HAS_VARIABLE_AGGRESSIVE', 'REQUIREMENTSET_TEST_ALL'),
('PLAYER_HAS_VARIABLE_ARCANE', 'REQUIREMENTSET_TEST_ALL'),
('PLAYER_HAS_VARIABLE_CHARISMATIC', 'REQUIREMENTSET_TEST_ALL'),
('PLAYER_HAS_VARIABLE_CREATIVE', 'REQUIREMENTSET_TEST_ALL'),
('PLAYER_HAS_VARIABLE_DEFENDER', 'REQUIREMENTSET_TEST_ALL'),
('PLAYER_HAS_VARIABLE_EXPANSIVE', 'REQUIREMENTSET_TEST_ALL'),
('PLAYER_HAS_VARIABLE_FINANCIAL', 'REQUIREMENTSET_TEST_ALL'),
('PLAYER_HAS_VARIABLE_INDUSTRIOUS', 'REQUIREMENTSET_TEST_ALL'),
('PLAYER_HAS_VARIABLE_ORGANIZED', 'REQUIREMENTSET_TEST_ALL'),
('PLAYER_HAS_VARIABLE_PHILOSOPHICAL', 'REQUIREMENTSET_TEST_ALL'),
('PLAYER_HAS_VARIABLE_RAIDERS', 'REQUIREMENTSET_TEST_ALL'),
('PLAYER_HAS_VARIABLE_SPIRITUAL', 'REQUIREMENTSET_TEST_ALL'),
('PLAYER_HAS_VARIABLE_SUMMONER', 'REQUIREMENTSET_TEST_ALL');

INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('PLAYER_HAS_VARIABLE_AGGRESSIVE', 'REQUIRE_PLAYER_HAS_CAPITAL_PLOT_AGGRESSIVE'),
('PLAYER_HAS_VARIABLE_ARCANE', 'REQUIRE_PLAYER_HAS_CAPITAL_PLOT_ARCANE'),
('PLAYER_HAS_VARIABLE_CHARISMATIC', 'REQUIRE_PLAYER_HAS_CAPITAL_PLOT_CHARISMATIC'),
('PLAYER_HAS_VARIABLE_CREATIVE', 'REQUIRE_PLAYER_HAS_CAPITAL_PLOT_CREATIVE'),
('PLAYER_HAS_VARIABLE_DEFENDER', 'REQUIRE_PLAYER_HAS_CAPITAL_PLOT_DEFENDER'),
('PLAYER_HAS_VARIABLE_EXPANSIVE', 'REQUIRE_PLAYER_HAS_CAPITAL_PLOT_EXPANSIVE'),
('PLAYER_HAS_VARIABLE_FINANCIAL', 'REQUIRE_PLAYER_HAS_CAPITAL_PLOT_FINANCIAL'),
('PLAYER_HAS_VARIABLE_INDUSTRIOUS', 'REQUIRE_PLAYER_HAS_CAPITAL_PLOT_INDUSTRIOUS'),
('PLAYER_HAS_VARIABLE_ORGANIZED', 'REQUIRE_PLAYER_HAS_CAPITAL_PLOT_ORGANIZED'),
('PLAYER_HAS_VARIABLE_PHILOSOPHICAL', 'REQUIRE_PLAYER_HAS_CAPITAL_PLOT_PHILOSOPHICAL'),
('PLAYER_HAS_VARIABLE_RAIDERS', 'REQUIRE_PLAYER_HAS_CAPITAL_PLOT_RAIDERS'),
('PLAYER_HAS_VARIABLE_SPIRITUAL', 'REQUIRE_PLAYER_HAS_CAPITAL_PLOT_SPIRITUAL'),
('PLAYER_HAS_VARIABLE_SUMMONER', 'REQUIRE_PLAYER_HAS_CAPITAL_PLOT_SUMMONER');

INSERT INTO Requirements(RequirementId, RequirementType) VALUES
('REQUIRE_PLAYER_HAS_CAPITAL_PLOT_AGGRESSIVE', 'REQUIREMENT_COLLECTION_ANY_MET'),
('REQUIRE_PLAYER_HAS_CAPITAL_PLOT_ARCANE', 'REQUIREMENT_COLLECTION_ANY_MET'),
('REQUIRE_PLAYER_HAS_CAPITAL_PLOT_CHARISMATIC', 'REQUIREMENT_COLLECTION_ANY_MET'),
('REQUIRE_PLAYER_HAS_CAPITAL_PLOT_CREATIVE', 'REQUIREMENT_COLLECTION_ANY_MET'),
('REQUIRE_PLAYER_HAS_CAPITAL_PLOT_DEFENDER', 'REQUIREMENT_COLLECTION_ANY_MET'),
('REQUIRE_PLAYER_HAS_CAPITAL_PLOT_EXPANSIVE', 'REQUIREMENT_COLLECTION_ANY_MET'),
('REQUIRE_PLAYER_HAS_CAPITAL_PLOT_FINANCIAL', 'REQUIREMENT_COLLECTION_ANY_MET'),
('REQUIRE_PLAYER_HAS_CAPITAL_PLOT_INDUSTRIOUS', 'REQUIREMENT_COLLECTION_ANY_MET'),
('REQUIRE_PLAYER_HAS_CAPITAL_PLOT_ORGANIZED', 'REQUIREMENT_COLLECTION_ANY_MET'),
('REQUIRE_PLAYER_HAS_CAPITAL_PLOT_PHILOSOPHICAL', 'REQUIREMENT_COLLECTION_ANY_MET'),
('REQUIRE_PLAYER_HAS_CAPITAL_PLOT_RAIDERS', 'REQUIREMENT_COLLECTION_ANY_MET'),
('REQUIRE_PLAYER_HAS_CAPITAL_PLOT_SPIRITUAL', 'REQUIREMENT_COLLECTION_ANY_MET'),
('REQUIRE_PLAYER_HAS_CAPITAL_PLOT_SUMMONER', 'REQUIREMENT_COLLECTION_ANY_MET');

INSERT INTO RequirementArguments(RequirementId, Name, Value) VALUES
('REQUIRE_PLAYER_HAS_CAPITAL_PLOT_AGGRESSIVE', 'CollectionType', 'COLLECTION_PLAYER_CAPITAL_CITY'),
('REQUIRE_PLAYER_HAS_CAPITAL_PLOT_AGGRESSIVE', 'RequirementSetId', 'PLOT_PROP_AGGRESSIVE_REQS'),
('REQUIRE_PLAYER_HAS_CAPITAL_PLOT_ARCANE', 'CollectionType', 'COLLECTION_PLAYER_CAPITAL_CITY'),
('REQUIRE_PLAYER_HAS_CAPITAL_PLOT_ARCANE', 'RequirementSetId', 'PLOT_PROP_ARCANE_REQS'),
('REQUIRE_PLAYER_HAS_CAPITAL_PLOT_CHARISMATIC', 'CollectionType', 'COLLECTION_PLAYER_CAPITAL_CITY'),
('REQUIRE_PLAYER_HAS_CAPITAL_PLOT_CHARISMATIC', 'RequirementSetId', 'PLOT_PROP_CHARISMATIC_REQS'),
('REQUIRE_PLAYER_HAS_CAPITAL_PLOT_CREATIVE', 'CollectionType', 'COLLECTION_PLAYER_CAPITAL_CITY'),
('REQUIRE_PLAYER_HAS_CAPITAL_PLOT_CREATIVE', 'RequirementSetId', 'PLOT_PROP_CREATIVE_REQS'),
('REQUIRE_PLAYER_HAS_CAPITAL_PLOT_DEFENDER', 'CollectionType', 'COLLECTION_PLAYER_CAPITAL_CITY'),
('REQUIRE_PLAYER_HAS_CAPITAL_PLOT_DEFENDER', 'RequirementSetId', 'PLOT_PROP_DEFENDER_REQS'),
('REQUIRE_PLAYER_HAS_CAPITAL_PLOT_EXPANSIVE', 'CollectionType', 'COLLECTION_PLAYER_CAPITAL_CITY'),
('REQUIRE_PLAYER_HAS_CAPITAL_PLOT_EXPANSIVE', 'RequirementSetId', 'PLOT_PROP_EXPANSIVE_REQS'),
('REQUIRE_PLAYER_HAS_CAPITAL_PLOT_FINANCIAL', 'CollectionType', 'COLLECTION_PLAYER_CAPITAL_CITY'),
('REQUIRE_PLAYER_HAS_CAPITAL_PLOT_FINANCIAL', 'RequirementSetId', 'PLOT_PROP_FINANCIAL_REQS'),
('REQUIRE_PLAYER_HAS_CAPITAL_PLOT_INDUSTRIOUS', 'CollectionType', 'COLLECTION_PLAYER_CAPITAL_CITY'),
('REQUIRE_PLAYER_HAS_CAPITAL_PLOT_INDUSTRIOUS', 'RequirementSetId', 'PLOT_PROP_INDUSTRIOUS_REQS'),
('REQUIRE_PLAYER_HAS_CAPITAL_PLOT_ORGANIZED', 'CollectionType', 'COLLECTION_PLAYER_CAPITAL_CITY'),
('REQUIRE_PLAYER_HAS_CAPITAL_PLOT_ORGANIZED', 'RequirementSetId', 'PLOT_PROP_ORGANIZED_REQS'),
('REQUIRE_PLAYER_HAS_CAPITAL_PLOT_PHILOSOPHICAL', 'CollectionType', 'COLLECTION_PLAYER_CAPITAL_CITY'),
('REQUIRE_PLAYER_HAS_CAPITAL_PLOT_PHILOSOPHICAL', 'RequirementSetId', 'PLOT_PROP_PHILOSOPHICAL_REQS'),
('REQUIRE_PLAYER_HAS_CAPITAL_PLOT_RAIDERS', 'CollectionType', 'COLLECTION_PLAYER_CAPITAL_CITY'),
('REQUIRE_PLAYER_HAS_CAPITAL_PLOT_RAIDERS', 'RequirementSetId', 'PLOT_PROP_RAIDERS_REQS'),
('REQUIRE_PLAYER_HAS_CAPITAL_PLOT_SPIRITUAL', 'CollectionType', 'COLLECTION_PLAYER_CAPITAL_CITY'),
('REQUIRE_PLAYER_HAS_CAPITAL_PLOT_SPIRITUAL', 'RequirementSetId', 'PLOT_PROP_SPIRITUAL_REQS'),
('REQUIRE_PLAYER_HAS_CAPITAL_PLOT_SUMMONER', 'CollectionType', 'COLLECTION_PLAYER_CAPITAL_CITY'),
('REQUIRE_PLAYER_HAS_CAPITAL_PLOT_SUMMONER', 'RequirementSetId', 'PLOT_PROP_SUMMONER_REQS');

INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('PLOT_PROP_AGGRESSIVE_REQS', 'PLOT_PROP_AGGRESSIVE_POSITIVE'),
('PLOT_PROP_ARCANE_REQS', 'PLOT_PROP_ARCANE_POSITIVE'),
('PLOT_PROP_CHARISMATIC_REQS', 'PLOT_PROP_CHARISMATIC_POSITIVE'),
('PLOT_PROP_CREATIVE_REQS', 'PLOT_PROP_CREATIVE_POSITIVE'),
('PLOT_PROP_DEFENDER_REQS', 'PLOT_PROP_DEFENDER_POSITIVE'),
('PLOT_PROP_EXPANSIVE_REQS', 'PLOT_PROP_EXPANSIVE_POSITIVE'),
('PLOT_PROP_FINANCIAL_REQS', 'PLOT_PROP_FINANCIAL_POSITIVE'),
('PLOT_PROP_INDUSTRIOUS_REQS', 'PLOT_PROP_INDUSTRIOUS_POSITIVE'),
('PLOT_PROP_ORGANIZED_REQS', 'PLOT_PROP_ORGANIZED_POSITIVE'),
('PLOT_PROP_PHILOSOPHICAL_REQS', 'PLOT_PROP_PHILOSOPHICAL_POSITIVE'),
('PLOT_PROP_RAIDERS_REQS', 'PLOT_PROP_RAIDERS_POSITIVE'),
('PLOT_PROP_SPIRITUAL_REQS', 'PLOT_PROP_SPIRITUAL_POSITIVE'),
('PLOT_PROP_SUMMONER_REQS', 'PLOT_PROP_SUMMONER_POSITIVE');

INSERT INTO RequirementSets(RequirementSetId, RequirementSetType) VALUES
('PLOT_PROP_AGGRESSIVE_REQS', 'REQUIREMENTSET_TEST_ALL'),
('PLOT_PROP_ARCANE_REQS', 'REQUIREMENTSET_TEST_ALL'),
('PLOT_PROP_CHARISMATIC_REQS', 'REQUIREMENTSET_TEST_ALL'),
('PLOT_PROP_CREATIVE_REQS', 'REQUIREMENTSET_TEST_ALL'),
('PLOT_PROP_DEFENDER_REQS', 'REQUIREMENTSET_TEST_ALL'),
('PLOT_PROP_EXPANSIVE_REQS', 'REQUIREMENTSET_TEST_ALL'),
('PLOT_PROP_FINANCIAL_REQS', 'REQUIREMENTSET_TEST_ALL'),
('PLOT_PROP_INDUSTRIOUS_REQS', 'REQUIREMENTSET_TEST_ALL'),
('PLOT_PROP_ORGANIZED_REQS', 'REQUIREMENTSET_TEST_ALL'),
('PLOT_PROP_PHILOSOPHICAL_REQS', 'REQUIREMENTSET_TEST_ALL'),
('PLOT_PROP_RAIDERS_REQS', 'REQUIREMENTSET_TEST_ALL'),
('PLOT_PROP_SPIRITUAL_REQS', 'REQUIREMENTSET_TEST_ALL'),
('PLOT_PROP_SUMMONER_REQS', 'REQUIREMENTSET_TEST_ALL');

INSERT INTO Requirements(RequirementId, RequirementType) VALUES
('PLOT_PROP_AGGRESSIVE_POSITIVE', 'REQUIREMENT_PLOT_PROPERTY_MATCHES'),
('PLOT_PROP_ARCANE_POSITIVE', 'REQUIREMENT_PLOT_PROPERTY_MATCHES'),
('PLOT_PROP_CHARISMATIC_POSITIVE', 'REQUIREMENT_PLOT_PROPERTY_MATCHES'),
('PLOT_PROP_CREATIVE_POSITIVE', 'REQUIREMENT_PLOT_PROPERTY_MATCHES'),
('PLOT_PROP_DEFENDER_POSITIVE', 'REQUIREMENT_PLOT_PROPERTY_MATCHES'),
('PLOT_PROP_EXPANSIVE_POSITIVE', 'REQUIREMENT_PLOT_PROPERTY_MATCHES'),
('PLOT_PROP_FINANCIAL_POSITIVE', 'REQUIREMENT_PLOT_PROPERTY_MATCHES'),
('PLOT_PROP_INDUSTRIOUS_POSITIVE', 'REQUIREMENT_PLOT_PROPERTY_MATCHES'),
('PLOT_PROP_ORGANIZED_POSITIVE', 'REQUIREMENT_PLOT_PROPERTY_MATCHES'),
('PLOT_PROP_PHILOSOPHICAL_POSITIVE', 'REQUIREMENT_PLOT_PROPERTY_MATCHES'),
('PLOT_PROP_RAIDERS_POSITIVE', 'REQUIREMENT_PLOT_PROPERTY_MATCHES'),
('PLOT_PROP_SPIRITUAL_POSITIVE', 'REQUIREMENT_PLOT_PROPERTY_MATCHES'),
('PLOT_PROP_SUMMONER_POSITIVE', 'REQUIREMENT_PLOT_PROPERTY_MATCHES');

INSERT INTO RequirementArguments(RequirementId, Name, Value) VALUES
('PLOT_PROP_AGGRESSIVE_POSITIVE', 'PropertyName', 'SELECTED_AGGRESSIVE'),
('PLOT_PROP_ARCANE_POSITIVE', 'PropertyName', 'SELECTED_ARCANE'),
('PLOT_PROP_CHARISMATIC_POSITIVE', 'PropertyName', 'SELECTED_CHARISMATIC'),
('PLOT_PROP_CREATIVE_POSITIVE', 'PropertyName', 'SELECTED_CREATIVE'),
('PLOT_PROP_DEFENDER_POSITIVE', 'PropertyName', 'SELECTED_DEFENDER'),
('PLOT_PROP_EXPANSIVE_POSITIVE', 'PropertyName', 'SELECTED_EXPANSIVE'),
('PLOT_PROP_FINANCIAL_POSITIVE', 'PropertyName', 'SELECTED_FINANCIAL'),
('PLOT_PROP_INDUSTRIOUS_POSITIVE', 'PropertyName', 'SELECTED_INDUSTRIOUS'),
('PLOT_PROP_ORGANIZED_POSITIVE', 'PropertyName', 'SELECTED_ORGANIZED'),
('PLOT_PROP_PHILOSOPHICAL_POSITIVE', 'PropertyName', 'SELECTED_PHILOSOPHICAL'),
('PLOT_PROP_RAIDERS_POSITIVE', 'PropertyName', 'SELECTED_RAIDERS'),
('PLOT_PROP_SPIRITUAL_POSITIVE', 'PropertyName', 'SELECTED_SPIRITUAL'),
('PLOT_PROP_SUMMONER_POSITIVE', 'PropertyName', 'SELECTED_SUMMONER'),
('PLOT_PROP_AGGRESSIVE_POSITIVE', 'PropertyMinimum','1'),
('PLOT_PROP_ARCANE_POSITIVE', 'PropertyMinimum','1'),
('PLOT_PROP_CHARISMATIC_POSITIVE', 'PropertyMinimum','1'),
('PLOT_PROP_CREATIVE_POSITIVE', 'PropertyMinimum','1'),
('PLOT_PROP_DEFENDER_POSITIVE', 'PropertyMinimum','1'),
('PLOT_PROP_EXPANSIVE_POSITIVE', 'PropertyMinimum','1'),
('PLOT_PROP_FINANCIAL_POSITIVE', 'PropertyMinimum','1'),
('PLOT_PROP_INDUSTRIOUS_POSITIVE', 'PropertyMinimum','1'),
('PLOT_PROP_ORGANIZED_POSITIVE', 'PropertyMinimum','1'),
('PLOT_PROP_PHILOSOPHICAL_POSITIVE', 'PropertyMinimum','1'),
('PLOT_PROP_RAIDERS_POSITIVE', 'PropertyMinimum','1'),
('PLOT_PROP_SPIRITUAL_POSITIVE', 'PropertyMinimum','1'),
('PLOT_PROP_SUMMONER_POSITIVE', 'PropertyMinimum','1');

-- can just adjust charismatic check to do the plot one as an OR: WAIT NEEDS SUBREQ AS A AND B OR C
/*
INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('OPPOSING_PLAYER_IS_CHARISMATIC', 'PLAYER_HAS_VARIABLE_CHARISMATIC');
'SELECTED_AGGRESSIVE',
'SELECTED_ARCANE',
'SELECTED_CHARISMATIC',
'SELECTED_CREATIVE',
'SELECTED_DEFENDER',
'SELECTED_EXPANSIVE',
'SELECTED_FINANCIAL',
'SELECTED_INDUSTRIOUS',
'SELECTED_ORGANIZED',
'SELECTED_PHILOSOPHICAL',
'SELECTED_RAIDERS',
'SELECTED_SPIRITUAL',
'SELECTED_SUMMONER',