-- section for doing the buildings cast by mages
-- Hope, Unyielding Order, Stone Walls, Inspiration
-- HOPE, Spirit II, +4 culture +1 amenity. Units in city radius gain Courage, being immune to fear and healing 10 faster. or on city centre?

-- UNYIELDING ORDER:  Granted on Prior/Sphener by having order religion ability and cast divine spells, presumably t3 channelling.
-- no unhappiness (99 amenities). No city maintenance. -10 crime rate lol. TODO last two not implememented
-- INSPIRATION: Mind I
-- +2 science, +1 GP Science

-- WALLS OF STONE: Earth I
-- 25% city defense, and bombard defense

-- Setup for unyielding Order, grants a new ability, to minimise performance on rechecking if the unit has divine.
INSERT INTO UnitAbilityModifiers(UnitAbilityType, ModifierId) VALUES
('ABILITY_CHANNELING3', 'GRANT_UNIT_UNYIELDING_ORDER'),
('ABILITY_UNYIELDING_ORDER', 'SLTH_UNIT_ADJACENT_CITY_99_AMENITIES');

INSERT INTO Modifiers(ModifierId, ModifierType, RunOnce, Permanent) VALUES
('GRANT_UNIT_UNYIELDING_ORDER', 'MODIFIER_PLAYER_UNIT_GRANT_ABILITY', '1', '1');            --SLTH_UNIT_WORSHIPS_ORDER_REQS

INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
('GRANT_UNIT_UNYIELDING_ORDER', 'AbilityType', 'ABILITY_UNYIELDING_ORDER');

INSERT INTO UnitAbilities(UnitAbilityType, Name, Description, Inactive, Permanent) VALUES
('ABILITY_UNYIELDING_ORDER', 'LOC_ABILITY_UNYIELDING_ORDER_NAME', 'LOC_ABILITY_UNYIELDING_ORDER_DESCRIPTION', '1', '1');

INSERT INTO TypeTags(Type, Tag) VALUES
('ABILITY_UNYIELDING_ORDER', 'CLASS_DIVINE');

INSERT INTO Types(Type, Kind) VALUES
('ABILITY_UNYIELDING_ORDER', 'KIND_ABILITY');

INSERT INTO RequirementSets(RequirementSetId, RequirementSetType) VALUES
('SLTH_UNIT_WORSHIPS_ORDER_REQS', 'REQUIREMENTSET_TEST_ANY');

INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('SLTH_UNIT_WORSHIPS_ORDER_REQS', 'REQUIREMENT_UNIT_WORSHIPS_ORDER'),
('SLTH_UNIT_WORSHIPS_ORDER_REQS', 'REQUIREMENT_UNIT_WORSHIPS_ORDER_INHERENT');

INSERT INTO Requirements(RequirementId, RequirementType) VALUES
('REQUIREMENT_UNIT_WORSHIPS_ORDER', 'REQUIREMENT_UNIT_HAS_ABILITY'),
('REQUIREMENT_UNIT_WORSHIPS_ORDER_INHERENT', 'REQUIREMENT_UNIT_HAS_ABILITY');

INSERT INTO RequirementArguments(RequirementId, Name, Value) VALUES
('REQUIREMENT_UNIT_WORSHIPS_ORDER', 'UnitAbilityType', 'ABILITY_WORSHIPS_ORDER'),
('REQUIREMENT_UNIT_WORSHIPS_ORDER_INHERENT', 'UnitAbilityType', 'ABILITY_INHERENT_WORSHIPS_ORDER');


INSERT INTO UnitPromotionModifiers(UnitPromotionType, ModifierId) VALUES
('SPIRIT_TWO', 'SLTH_UNIT_ADJACENT_CITY_CULTURE'),
('SPIRIT_TWO', 'SLTH_UNIT_ADJACENT_CITY_AMENITY'),
('SPIRIT_TWO', 'SLTH_UNIT_ADJACENT_CITY_COURAGE_ATTACH'),
('MIND_ONE', 'SLTH_UNIT_ADJACENT_CITY_SCIENCE'),
('MIND_ONE', 'SLTH_UNIT_ADJACENT_CITY_GREAT_SCI_POINTS_ATTACH'),
('EARTH_ONE', 'SLTH_UNIT_ADJACENT_CITY_ADJUST_INNER_DEFENSE');

INSERT INTO DynamicModifiers(ModifierType, CollectionType, EffectType) VALUES
('SLTH_NEAREST_CITY_ADJUST_YIELD_TYPE', 'COLLECTION_UNIT_NEAREST_OWNER_CITY', 'EFFECT_ADJUST_CITY_YIELD_CHANGE'),
('SLTH_NEAREST_CITY_ADJUST_AMENITY_TYPE', 'COLLECTION_UNIT_NEAREST_OWNER_CITY', 'EFFECT_ADJUST_IMPROVEMENT_AMENITY'),
('SLTH_NEAREST_CITY_ADJUST_GREAT_PEOPLE_POINTS_TYPE', 'COLLECTION_UNIT_NEAREST_OWNER_CITY', 'EFFECT_ADJUST_GREAT_PERSON_POINTS'),               -- sadly not buffed by great people mods.
('SLTH_NEAREST_CITY_ADJUST_ADJUST_INNER_DEFENSE_TYPE', 'COLLECTION_UNIT_NEAREST_OWNER_CITY', 'EFFECT_ADJUST_CITY_INNER_DEFENSE'),
('SLTH_NEAREST_CITY_ATTACH_MODIFIER_TYPE', 'COLLECTION_UNIT_NEAREST_OWNER_CITY', 'EFFECT_ATTACH_MODIFIER');


INSERT INTO Types(Type, Kind) VALUES
('SLTH_NEAREST_CITY_ADJUST_YIELD_TYPE', 'KIND_MODIFIER'),
('SLTH_NEAREST_CITY_ADJUST_AMENITY_TYPE', 'KIND_MODIFIER'),
('SLTH_NEAREST_CITY_ADJUST_GREAT_PEOPLE_POINTS_TYPE', 'KIND_MODIFIER'),
('SLTH_NEAREST_CITY_ADJUST_ADJUST_INNER_DEFENSE_TYPE', 'KIND_MODIFIER'),
('SLTH_NEAREST_CITY_ATTACH_MODIFIER_TYPE', 'KIND_MODIFIER');

INSERT INTO Modifiers(ModifierId, ModifierType, OwnerRequirementSetId, SubjectStackLimit) VALUES
('SLTH_UNIT_ADJACENT_CITY_CULTURE', 'SLTH_NEAREST_CITY_ADJUST_YIELD_TYPE', 'SLTH_UNIT_ADJACENT_TO_CITY_CENTRE_AND_HOME_TURF_REQS', '1'),
('SLTH_UNIT_ADJACENT_CITY_AMENITY', 'SLTH_NEAREST_CITY_ADJUST_AMENITY_TYPE', 'SLTH_UNIT_ADJACENT_TO_CITY_CENTRE_AND_HOME_TURF_REQS', '1'),
('SLTH_UNIT_ADJACENT_CITY_99_AMENITIES', 'SLTH_NEAREST_CITY_ADJUST_AMENITY_TYPE', 'SLTH_UNIT_ADJACENT_TO_CITY_CENTRE_AND_HOME_TURF_REQS', '1'),
('SLTH_UNIT_ADJACENT_CITY_SCIENCE', 'SLTH_NEAREST_CITY_ADJUST_YIELD_TYPE', 'SLTH_UNIT_ADJACENT_TO_CITY_CENTRE_AND_HOME_TURF_REQS', '1'),
('SLTH_UNIT_ADJACENT_CITY_GREAT_SCI_POINTS_ATTACH', 'SLTH_NEAREST_CITY_ATTACH_MODIFIER_TYPE', 'SLTH_UNIT_ADJACENT_TO_CITY_CENTRE_AND_HOME_TURF_REQS', '1'),
('SLTH_UNIT_ADJACENT_CITY_ADJUST_INNER_DEFENSE', 'SLTH_NEAREST_CITY_ADJUST_ADJUST_INNER_DEFENSE_TYPE', 'SLTH_UNIT_ADJACENT_TO_CITY_CENTRE_AND_HOME_TURF_REQS', '1');

INSERT INTO Modifiers(ModifierId, ModifierType, SubjectRequirementSetId) VALUES
('SLTH_UNIT_ADJACENT_CITY_GREAT_SCI_POINTS', 'MODIFIER_SINGLE_CITY_DISTRICTS_ADJUST_GREAT_PERSON_POINTS', 'SLTH_DISTRICT_IS_CITY_CENTRE_REQS');

INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
('SLTH_UNIT_ADJACENT_CITY_CULTURE', 'Amount', '4'),
('SLTH_UNIT_ADJACENT_CITY_CULTURE', 'YieldType', 'YIELD_CULTURE'),
('SLTH_UNIT_ADJACENT_CITY_AMENITY', 'Amount', '1'),
('SLTH_UNIT_ADJACENT_CITY_99_AMENITIES', 'Amount', '99'),
('SLTH_UNIT_ADJACENT_CITY_SCIENCE', 'Amount', '2'),
('SLTH_UNIT_ADJACENT_CITY_SCIENCE', 'YieldType', 'YIELD_SCIENCE'),
('SLTH_UNIT_ADJACENT_CITY_GREAT_SCI_POINTS_ATTACH', 'ModifierId', 'SLTH_UNIT_ADJACENT_CITY_GREAT_SCI_POINTS'),
('SLTH_UNIT_ADJACENT_CITY_GREAT_SCI_POINTS', 'GreatPersonClassType', 'GREAT_PERSON_CLASS_SCIENTIST'),
('SLTH_UNIT_ADJACENT_CITY_GREAT_SCI_POINTS', 'Amount', '20'),
('SLTH_UNIT_ADJACENT_CITY_ADJUST_INNER_DEFENSE', 'Amount', '5');

INSERT INTO RequirementSets(RequirementSetId, RequirementSetType) VALUES
('SLTH_UNIT_ADJACENT_TO_CITY_CENTRE_AND_HOME_TURF_REQS', 'REQUIREMENTSET_TEST_ALL');

INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('SLTH_UNIT_ADJACENT_TO_CITY_CENTRE_AND_HOME_TURF_REQS', 'UNIT_IN_OWNER_TERRITORY_REQUIREMENT'),
('SLTH_UNIT_ADJACENT_TO_CITY_CENTRE_AND_HOME_TURF_REQS', 'REQUIRES_PLOT_ADJACENT_TO_CITY_CENTER');

-- courage for Hope. needs REQUIREMENT_PLOT_ADJACENT_TO_OWNER and attach.
-- ATTACH TO CITY, then who is Owner? Is this where I get to use OWNER_CITY?
-- Could I make it simpler by just making apply to units within 3 tiles of the actual unit, that are in friendly territory?
-- sadly doesnt work
/*
INSERT INTO Modifiers(ModifierId, ModifierType, SubjectRequirementSetId) VALUES
('SLTH_UNIT_ADJACENT_CITY_COURAGE_ATTACH', 'SLTH_NEAREST_CITY_ATTACH_MODIFIER_TYPE', 'SLTH_UNIT_ADJACENT_TO_CITY_CENTRE_AND_HOME_TURF_REQS');

INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
('SLTH_UNIT_ADJACENT_CITY_COURAGE_ATTACH', 'ModifierId', 'SLTH_GRANT_UNITS_COURAGE');

INSERT INTO Modifiers(ModifierId, ModifierType, SubjectRequirementSetId) VALUES
('SLTH_GRANT_UNITS_COURAGE', 'MODIFIER_PLAYER_UNITS_GRANT_ABILITY', 'UNIT_WITHIN_3_TILES_OF_OWNER_REQS');

INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
('SLTH_GRANT_UNITS_COURAGE', 'AbilityType', 'BUFF_COURAGE');

INSERT INTO Requirements(RequirementId, RequirementType) VALUES
('REQUIREMENT_UNIT_WITHIN_3_TILES_OF_OWNER', 'REQUIREMENT_PLOT_ADJACENT_TO_OWNER');

INSERT INTO RequirementArguments(RequirementId, Name, Value) VALUES
('REQUIREMENT_UNIT_WITHIN_3_TILES_OF_OWNER', 'MinDistance', '0'),
('REQUIREMENT_UNIT_WITHIN_3_TILES_OF_OWNER', 'MaxDistance', '3');

INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('UNIT_WITHIN_3_TILES_OF_OWNER_REQS', 'REQUIREMENT_UNIT_WITHIN_3_TILES_OF_OWNER');

INSERT INTO RequirementSets(RequirementSetId, RequirementSetType) VALUES
('UNIT_WITHIN_3_TILES_OF_OWNER_REQS', 'REQUIREMENTSET_TEST_ALL');

 */