INSERT INTO DynamicModifiers(ModifierType, CollectionType, EffectType) VALUES
('MODIFIER_PLAYER_CAPITAL_CITY_GPP_MULT', 'COLLECTION_PLAYER_CAPITAL_CITY', 'EFFECT_ADJUST_CITY_GREAT_PERSON_POINTS_MODIFIER'),
('MODIFIER_FREE_RESOURCE_IN_CAPITAL', 'COLLECTION_PLAYER_CAPITAL_CITY', 'EFFECT_ADJUST_PLAYER_FREE_RESOURCE_IMPORT'),
('MODIFIER_CITY_ADJUST_TRADE_ROUTE_YIELD_FOR_INTERNATIONAL', 'COLLECTION_OWNER', 'EFFECT_ADJUST_CITY_TRADE_ROUTE_YIELD_FOR_INTERNATIONAL'),
('MODIFIER_FREE_RESOURCE_EXTRACTION_IN_CAPITAL', 'COLLECTION_PLAYER_CAPITAL_CITY', 'EFFECT_ADJUST_PLAYER_FREE_RESOURCE_IMPORT_EXTRACTION'),
('MODIFIER_PLAYER_CAPITAL_CITY_GPP_INCREASE', 'COLLECTION_PLAYER_CAPITAL_CITY', 'EFFECT_ADJUST_GREAT_PERSON_POINTS'),
('MODIFIER_ATTACH_MODIFIER_PLAYER_CAPITAL', 'COLLECTION_PLAYER_CAPITAL_CITY', 'EFFECT_ATTACH_MODIFIER'),            -- used for lua plot prop requirements
('MODIFIER_PLAYER_CITY_ALWAYS_LOYAL', 'COLLECTION_OWNER', 'EFFECT_ADJUST_CITY_ALWAYS_LOYAL');

INSERT INTO Types(Type, Kind) VALUES
('MODIFIER_PLAYER_CAPITAL_CITY_GPP_MULT', 'KIND_MODIFIER'),
('MODIFIER_FREE_RESOURCE_IN_CAPITAL', 'KIND_MODIFIER'),
('MODIFIER_CITY_ADJUST_TRADE_ROUTE_YIELD_FOR_INTERNATIONAL', 'KIND_MODIFIER'),
('MODIFIER_FREE_RESOURCE_EXTRACTION_IN_CAPITAL', 'KIND_MODIFIER'),
('MODIFIER_PLAYER_CAPITAL_CITY_GPP_INCREASE', 'KIND_MODIFIER'),
('MODIFIER_ATTACH_MODIFIER_PLAYER_CAPITAL', 'KIND_MODIFIER'),
('MODIFIER_PLAYER_CITY_ALWAYS_LOYAL', 'KIND_MODIFIER');