
INSERT INTO Units(UnitType, Name, BaseSightRange, BaseMoves, Combat, RangedCombat, Range, Domain, FormationClass, Cost, BuildCharges, Description, TraitType, AllowBarbarians, PromotionClass, PrereqTech, PrereqCivic, CanTrain, Maintenance, Stackable, AirSlots, CanTargetAir, PseudoYieldType, IgnoreMoves, AdvisorType, EnabledByReligion, StrategicResource) VALUES
('SLTH_UNIT_DEATH_KNIGHT', 'LOC_SLTH_UNIT_DEATH_KNIGHT_NAME', '2', '3', '39', '0', '0', 'DOMAIN_LAND', 'FORMATION_CLASS_LAND_COMBAT', '240', '0', 'LOC_SLTH_UNIT_DEATH_KNIGHT_DESCRIPTION', 'SLTH_TRAIT_CIVILIZATION_UNIT_DEATH_KNIGHT', '0', 'PROMOTION_CLASS_LIGHT_CAVALRY', 'TECH_WARHORSES', NULL, '1', '1', '0', '0', '0', NULL, '0', 'ADVISOR_CONQUEST', '0', NULL),
('SLTH_UNIT_KNIGHT', 'LOC_SLTH_UNIT_KNIGHT_NAME', '2', '3', '53', '0', '0', 'DOMAIN_LAND', 'FORMATION_CLASS_LAND_COMBAT', '240', '0', 'LOC_SLTH_UNIT_KNIGHT_DESCRIPTION', NULL, '0', 'PROMOTION_CLASS_LIGHT_CAVALRY', 'TECH_WARHORSES', NULL, '1', '1', '0', '0', '0', NULL, '0', 'ADVISOR_CONQUEST', '0', NULL),      -- was RESOURCE_WARHORSES
('SLTH_UNIT_BEASTMASTER', 'LOC_SLTH_UNIT_BEASTMASTER_NAME', '2', '2', '67', '0', '0', 'DOMAIN_LAND', 'FORMATION_CLASS_LAND_COMBAT', '240', '0', 'LOC_SLTH_UNIT_BEASTMASTER_DESCRIPTION', NULL, '0', 'PROMOTION_CLASS_RECON', 'TECH_ANIMAL_MASTERY', NULL, '1', '1', '0', '1', '0', NULL, '0', 'ADVISOR_GENERIC', '0', NULL),
('SLTH_UNIT_BERSERKER', 'LOC_SLTH_UNIT_BERSERKER_NAME', '2', '1', '53', '0', '0', 'DOMAIN_LAND', 'FORMATION_CLASS_LAND_COMBAT', '240', '0', 'LOC_SLTH_UNIT_BERSERKER_DESCRIPTION', NULL, '0', 'PROMOTION_CLASS_MELEE', NULL, 'CIVIC_RAGE', '1', '1', '0', '0', '0', NULL, '0', 'ADVISOR_CONQUEST', '0', NULL),
('SLTH_UNIT_PHALANX', 'LOC_SLTH_UNIT_PHALANX_NAME', '2', '1', '58', '0', '0', 'DOMAIN_LAND', 'FORMATION_CLASS_LAND_COMBAT', '240', '0', 'LOC_SLTH_UNIT_PHALANX_DESCRIPTION', NULL, '0', 'PROMOTION_CLASS_MELEE', 'TECH_MITHRIL_WEAPONS', NULL, '1', '1', '0', '0', '0', NULL, '0', 'ADVISOR_CONQUEST', '0', NULL);

INSERT INTO Units(UnitType, Name, BaseSightRange, BaseMoves, Combat, RangedCombat, Range, Domain, FormationClass, Cost, BuildCharges, Description, TraitType, AllowBarbarians, PromotionClass, PrereqTech, PrereqCivic, CanTrain, Maintenance, Stackable, AirSlots, CanTargetAir, PseudoYieldType, IgnoreMoves, AdvisorType, EnabledByReligion, StrategicResource, PurchaseYield, MustPurchase) VALUES
('SLTH_UNIT_IMMORTAL', 'LOC_SLTH_UNIT_IMMORTAL_NAME', '2', '1', '43', '0', '0', 'DOMAIN_LAND', 'FORMATION_CLASS_LAND_COMBAT', '240', '0', 'LOC_SLTH_UNIT_IMMORTAL_DESCRIPTION', NULL, '0', 'PROMOTION_CLASS_MELEE', NULL, 'CIVIC_DIVINE_ESSENCE', '1', '1', '0', '0', '0', NULL, '0', 'ADVISOR_CONQUEST', '0', NULL, NULL, '1');

INSERT INTO UnitReplaces(CivUniqueUnitType, ReplacesUnitType) VALUES
('SLTH_UNIT_DEATH_KNIGHT', 'SLTH_UNIT_KNIGHT');

INSERT INTO TypeTags(Type, Tag) VALUES
('SLTH_UNIT_DEATH_KNIGHT', 'CLASS_LIGHT_CAVALRY'),
('SLTH_UNIT_KNIGHT', 'CLASS_LIGHT_CAVALRY'),
('SLTH_UNIT_DEATH_KNIGHT', 'RACE_DEMON'),
('SLTH_UNIT_KNIGHT', 'CAN_BE_RACIALIZED');

INSERT INTO Types(Type, Kind) VALUES
('SLTH_UNIT_DEATH_KNIGHT', 'KIND_UNIT'),
('SLTH_UNIT_KNIGHT', 'KIND_UNIT');

-- template for adding national unit ban. Don't think it covers upgrading sadly.

INSERT INTO TraitModifiers(TraitType, ModifierId) VALUES
('TRAIT_LEADER_MAJOR_CIV', 'MOD_CANT_BUILD_ANYMORE_KNIGHTS');

INSERT INTO Modifiers(ModifierId, ModifierType, SubjectRequirementSetId) VALUES
('MOD_CANT_BUILD_ANYMORE_KNIGHTS', 'MODIFIER_PLAYER_UNIT_BUILD_DISABLED', 'PLAYER_HAS_4_KNIGHTS_REQS');

INSERT INTO ModifierArguments(ModifierId, Name, Type, Value) VALUES
('MOD_CANT_BUILD_ANYMORE_KNIGHTS', 'UnitType', 'ARGTYPE_IDENTITY', 'SLTH_UNIT_KNIGHT');

INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('PLAYER_HAS_4_KNIGHTS_REQS', 'SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_KNIGHTS_REQ');
INSERT INTO RequirementSets(RequirementSetId, RequirementSetType) VALUES ('PLAYER_HAS_4_KNIGHTS_REQS', 'REQUIREMENTSET_TEST_ALL');

INSERT INTO Requirements(RequirementId, RequirementType) VALUES ('SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_KNIGHTS_REQ', 'REQUIREMENT_COLLECTION_COUNT_ATLEAST');

INSERT INTO RequirementArguments(RequirementId, Name, Value) VALUES
('SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_KNIGHTS_REQ', 'CollectionType', 'COLLECTION_PLAYER_UNITS'),
('SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_KNIGHTS_REQ', 'Count', '4'),
('SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_KNIGHTS_REQ', 'RequirementSetId', 'SUBREQSET_KNIGHT_CLASS_UNITS');

INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('SUBREQSET_KNIGHT_CLASS_UNITS', 'SLTH_UNIT_IS_KNIGHT_CLASS');
INSERT INTO RequirementSets(RequirementSetId, RequirementSetType) VALUES ('SUBREQSET_KNIGHT_CLASS_UNITS', 'REQUIREMENTSET_TEST_ALL');
INSERT INTO Requirements(RequirementId, RequirementType) VALUES ('SLTH_UNIT_IS_KNIGHT_CLASS', 'REQUIREMENT_UNIT_TAG_MATCHES');
INSERT INTO RequirementArguments(RequirementId, Name, Value) VALUES
('SLTH_UNIT_IS_KNIGHT_CLASS', 'Tag', 'CLASS_NATIONAL_KNIGHT');

INSERT INTO Tags(Tag, Vocabulary) VALUES
('CLASS_NATIONAL_KNIGHT', 'ABILITY_CLASS');

INSERT INTO TypeTags(Type, Tag) VALUES
('SLTH_UNIT_KNIGHT', 'CLASS_NATIONAL_KNIGHT'),
('SLTH_UNIT_DEATH_KNIGHT', 'CLASS_NATIONAL_KNIGHT'),
('SLTH_UNIT_HORNGUARD', 'CLASS_NATIONAL_KNIGHT'),
('SLTH_UNIT_CENTAUR_LANCER', 'CLASS_NATIONAL_KNIGHT'),
('SLTH_UNIT_WAR_TORTOISE', 'CLASS_NATIONAL_KNIGHT'),
('SLTH_UNIT_CENTAUR_LANCER', 'CLASS_NATIONAL_KNIGHT'),
('SLTH_UNIT_BISON_RIDER', 'CLASS_NATIONAL_KNIGHT');




INSERT INTO TraitModifiers(TraitType, ModifierId) VALUES
('TRAIT_LEADER_MAJOR_CIV', 'MOD_NATIONAL_LIMIT_SHADOW'),
('TRAIT_LEADER_MAJOR_CIV', 'MOD_NATIONAL_LIMIT_CROSSBOWMAN'),
('TRAIT_LEADER_MAJOR_CIV', 'MOD_NATIONAL_LIMIT_MARKSMAN'),
('TRAIT_LEADER_MAJOR_CIV', 'MOD_NATIONAL_LIMIT_ROYAL_GUARD'),
('TRAIT_LEADER_MAJOR_CIV', 'MOD_NATIONAL_LIMIT_BEAST_OF_AGARES'),
('TRAIT_LEADER_MAJOR_CIV', 'MOD_NATIONAL_LIMIT_SHADOWRIDER'),
('TRAIT_LEADER_MAJOR_CIV', 'MOD_NATIONAL_LIMIT_BEASTMASTER'),
('TRAIT_LEADER_MAJOR_CIV', 'MOD_NATIONAL_LIMIT_PHALANX'),
('TRAIT_LEADER_MAJOR_CIV', 'MOD_NATIONAL_LIMIT_EIDOLON'),
('TRAIT_LEADER_MAJOR_CIV', 'MOD_NATIONAL_LIMIT_PALADIN'),                                             -- for performance, move this to good alignment modifier?, same for eidolon/druic
('TRAIT_LEADER_MAJOR_CIV', 'MOD_NATIONAL_LIMIT_DRUID'),
('SLTH_TRAIT_CIVILIZATION_LUCHUIRP_COOL', 'MOD_NATIONAL_LIMIT_BONE_GOLEM'),                                       -- Luichuirp only for performance. If i ever get Elohim working that would need it too
('TRAIT_LEADER_MAJOR_CIV', 'MOD_NATIONAL_LIMIT_BERSERKER');

INSERT INTO Modifiers(ModifierId, ModifierType, SubjectRequirementSetId) VALUES
('MOD_NATIONAL_LIMIT_SHADOW', 'MODIFIER_PLAYER_UNIT_BUILD_DISABLED', 'PLAYER_HAS_4_UNIT_SHADOW_REQS'),
('MOD_NATIONAL_LIMIT_CROSSBOWMAN', 'MODIFIER_PLAYER_UNIT_BUILD_DISABLED', 'PLAYER_HAS_4_UNIT_CROSSBOWMAN_REQS'),
('MOD_NATIONAL_LIMIT_MARKSMAN', 'MODIFIER_PLAYER_UNIT_BUILD_DISABLED', 'PLAYER_HAS_4_UNIT_MARKSMAN_REQS'),
('MOD_NATIONAL_LIMIT_ROYAL_GUARD', 'MODIFIER_PLAYER_UNIT_BUILD_DISABLED', 'PLAYER_HAS_4_UNIT_ROYAL_GUARD_REQS'),
('MOD_NATIONAL_LIMIT_BEAST_OF_AGARES', 'MODIFIER_PLAYER_UNIT_BUILD_DISABLED', 'PLAYER_HAS_4_UNIT_BEAST_OF_AGARES_REQS'),
('MOD_NATIONAL_LIMIT_SHADOWRIDER', 'MODIFIER_PLAYER_UNIT_BUILD_DISABLED', 'PLAYER_HAS_4_UNIT_SHADOWRIDER_REQS'),
('MOD_NATIONAL_LIMIT_BEASTMASTER', 'MODIFIER_PLAYER_UNIT_BUILD_DISABLED', 'PLAYER_HAS_4_UNIT_BEASTMASTER_REQS'),
('MOD_NATIONAL_LIMIT_PHALANX', 'MODIFIER_PLAYER_UNIT_BUILD_DISABLED', 'PLAYER_HAS_4_UNIT_PHALANX_REQS'),
('MOD_NATIONAL_LIMIT_EIDOLON', 'MODIFIER_PLAYER_UNIT_BUILD_DISABLED', 'PLAYER_HAS_4_UNIT_EIDOLON_REQS'),
('MOD_NATIONAL_LIMIT_PALADIN', 'MODIFIER_PLAYER_UNIT_BUILD_DISABLED', 'PLAYER_HAS_4_UNIT_PALADIN_REQS'),
('MOD_NATIONAL_LIMIT_DRUID', 'MODIFIER_PLAYER_UNIT_BUILD_DISABLED', 'PLAYER_HAS_4_UNIT_DRUID_REQS'),
('MOD_NATIONAL_LIMIT_BONE_GOLEM', 'MODIFIER_PLAYER_UNIT_BUILD_DISABLED', 'PLAYER_HAS_4_UNIT_BONE_GOLEM_REQS'),
('MOD_NATIONAL_LIMIT_BERSERKER', 'MODIFIER_PLAYER_UNIT_BUILD_DISABLED', 'PLAYER_HAS_4_UNIT_BERSERKER_REQS');


INSERT INTO ModifierArguments(ModifierId, Name, Type, Value) VALUES
('MOD_NATIONAL_LIMIT_SHADOW', 'UnitType', 'ARGTYPE_IDENTITY', 'SLTH_UNIT_SHADOW'),
('MOD_NATIONAL_LIMIT_CROSSBOWMAN', 'UnitType', 'ARGTYPE_IDENTITY', 'SLTH_UNIT_CROSSBOWMAN'),
('MOD_NATIONAL_LIMIT_MARKSMAN', 'UnitType', 'ARGTYPE_IDENTITY', 'SLTH_UNIT_MARKSMAN'),
('MOD_NATIONAL_LIMIT_ROYAL_GUARD', 'UnitType', 'ARGTYPE_IDENTITY', 'SLTH_UNIT_ROYAL_GUARD'),
('MOD_NATIONAL_LIMIT_BEAST_OF_AGARES', 'UnitType', 'ARGTYPE_IDENTITY', 'SLTH_UNIT_BEAST_OF_AGARES'),
('MOD_NATIONAL_LIMIT_SHADOWRIDER', 'UnitType', 'ARGTYPE_IDENTITY', 'SLTH_UNIT_SHADOWRIDER'),
('MOD_NATIONAL_LIMIT_BEASTMASTER', 'UnitType', 'ARGTYPE_IDENTITY', 'SLTH_UNIT_BEASTMASTER'),
('MOD_NATIONAL_LIMIT_PHALANX', 'UnitType', 'ARGTYPE_IDENTITY', 'SLTH_UNIT_PHALANX'),
('MOD_NATIONAL_LIMIT_EIDOLON', 'UnitType', 'ARGTYPE_IDENTITY', 'SLTH_UNIT_EIDOLON'),
('MOD_NATIONAL_LIMIT_PALADIN', 'UnitType', 'ARGTYPE_IDENTITY', 'SLTH_UNIT_PALADIN'),
('MOD_NATIONAL_LIMIT_DRUID', 'UnitType', 'ARGTYPE_IDENTITY', 'SLTH_UNIT_DRUID'),
('MOD_NATIONAL_LIMIT_BONE_GOLEM', 'UnitType', 'ARGTYPE_IDENTITY', 'SLTH_UNIT_BONE_GOLEM'),
('MOD_NATIONAL_LIMIT_BERSERKER', 'UnitType', 'ARGTYPE_IDENTITY', 'SLTH_UNIT_BERSERKER');

INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('PLAYER_HAS_4_UNIT_SHADOW_REQS', 'SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_UNIT_SHADOW_REQ'),
('PLAYER_HAS_4_UNIT_CROSSBOWMAN_REQS', 'SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_UNIT_CROSSBOWMAN_REQ'),
('PLAYER_HAS_4_UNIT_MARKSMAN_REQS', 'SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_UNIT_MARKSMAN_REQ'),
('PLAYER_HAS_4_UNIT_ROYAL_GUARD_REQS', 'SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_UNIT_ROYAL_GUARD_REQ'),
('PLAYER_HAS_4_UNIT_BEAST_OF_AGARES_REQS', 'SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_UNIT_BEAST_OF_AGARES_REQ'),
('PLAYER_HAS_4_UNIT_SHADOWRIDER_REQS', 'SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_UNIT_SHADOWRIDER_REQ'),
('PLAYER_HAS_4_UNIT_BEASTMASTER_REQS', 'SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_UNIT_BEASTMASTER_REQ'),
('PLAYER_HAS_4_UNIT_PHALANX_REQS', 'SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_UNIT_PHALANX_REQ'),
('PLAYER_HAS_4_UNIT_EIDOLON_REQS', 'SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_UNIT_EIDOLON_REQ'),
('PLAYER_HAS_4_UNIT_PALADIN_REQS', 'SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_UNIT_PALADIN_REQ'),
('PLAYER_HAS_4_UNIT_DRUID_REQS', 'SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_UNIT_DRUID_REQ'),
('PLAYER_HAS_4_UNIT_BONE_GOLEM_REQS', 'SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_UNIT_BONE_GOLEM_REQ'),
('PLAYER_HAS_4_UNIT_BERSERKER_REQS', 'SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_UNIT_BERSERKER_REQ');

INSERT INTO RequirementSets(RequirementSetId, RequirementSetType) VALUES
('PLAYER_HAS_4_UNIT_SHADOW_REQS', 'REQUIREMENTSET_TEST_ALL'),
('PLAYER_HAS_4_UNIT_CROSSBOWMAN_REQS', 'REQUIREMENTSET_TEST_ALL'),
('PLAYER_HAS_4_UNIT_MARKSMAN_REQS', 'REQUIREMENTSET_TEST_ALL'),
('PLAYER_HAS_4_UNIT_ROYAL_GUARD_REQS', 'REQUIREMENTSET_TEST_ALL'),
('PLAYER_HAS_4_UNIT_BEAST_OF_AGARES_REQS', 'REQUIREMENTSET_TEST_ALL'),
('PLAYER_HAS_4_UNIT_SHADOWRIDER_REQS', 'REQUIREMENTSET_TEST_ALL'),
('PLAYER_HAS_4_UNIT_BEASTMASTER_REQS', 'REQUIREMENTSET_TEST_ALL'),
('PLAYER_HAS_4_UNIT_PHALANX_REQS', 'REQUIREMENTSET_TEST_ALL'),
('PLAYER_HAS_4_UNIT_EIDOLON_REQS', 'REQUIREMENTSET_TEST_ALL'),
('PLAYER_HAS_4_UNIT_PALADIN_REQS', 'REQUIREMENTSET_TEST_ALL'),
('PLAYER_HAS_4_UNIT_DRUID_REQS', 'REQUIREMENTSET_TEST_ALL'),
('PLAYER_HAS_4_UNIT_BONE_GOLEM_REQS', 'REQUIREMENTSET_TEST_ALL'),
('PLAYER_HAS_4_UNIT_BERSERKER_REQS', 'REQUIREMENTSET_TEST_ALL');
INSERT INTO Requirements(RequirementId, RequirementType) VALUES
('SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_UNIT_SHADOW_REQ', 'REQUIREMENT_COLLECTION_COUNT_ATLEAST'),
('SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_UNIT_CROSSBOWMAN_REQ', 'REQUIREMENT_COLLECTION_COUNT_ATLEAST'),
('SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_UNIT_MARKSMAN_REQ', 'REQUIREMENT_COLLECTION_COUNT_ATLEAST'),
('SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_UNIT_ROYAL_GUARD_REQ', 'REQUIREMENT_COLLECTION_COUNT_ATLEAST'),
('SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_UNIT_BEAST_OF_AGARES_REQ', 'REQUIREMENT_COLLECTION_COUNT_ATLEAST'),
('SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_UNIT_SHADOWRIDER_REQ', 'REQUIREMENT_COLLECTION_COUNT_ATLEAST'),
('SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_UNIT_BEASTMASTER_REQ', 'REQUIREMENT_COLLECTION_COUNT_ATLEAST'),
('SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_UNIT_PHALANX_REQ', 'REQUIREMENT_COLLECTION_COUNT_ATLEAST'),
('SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_UNIT_EIDOLON_REQ', 'REQUIREMENT_COLLECTION_COUNT_ATLEAST'),
('SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_UNIT_PALADIN_REQ', 'REQUIREMENT_COLLECTION_COUNT_ATLEAST'),
('SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_UNIT_DRUID_REQ', 'REQUIREMENT_COLLECTION_COUNT_ATLEAST'),
('SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_UNIT_BONE_GOLEM_REQ', 'REQUIREMENT_COLLECTION_COUNT_ATLEAST'),
('SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_UNIT_BERSERKER_REQ', 'REQUIREMENT_COLLECTION_COUNT_ATLEAST');
INSERT INTO RequirementArguments(RequirementId, Name, Value) VALUES
('SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_UNIT_SHADOW_REQ', 'CollectionType', 'COLLECTION_PLAYER_UNITS'),
('SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_UNIT_SHADOW_REQ', 'Count', '4'),
('SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_UNIT_SHADOW_REQ', 'RequirementSetId', 'SUBREQSET_NATIONAL_SHADOW_CLASS_UNITS'),
('SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_UNIT_CROSSBOWMAN_REQ', 'CollectionType', 'COLLECTION_PLAYER_UNITS'),
('SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_UNIT_CROSSBOWMAN_REQ', 'Count', '4'),
('SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_UNIT_CROSSBOWMAN_REQ', 'RequirementSetId', 'SUBREQSET_NATIONAL_CROSSBOWMAN_CLASS_UNITS'),
('SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_UNIT_MARKSMAN_REQ', 'CollectionType', 'COLLECTION_PLAYER_UNITS'),
('SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_UNIT_MARKSMAN_REQ', 'Count', '4'),
('SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_UNIT_MARKSMAN_REQ', 'RequirementSetId', 'SUBREQSET_NATIONAL_MARKSMAN_CLASS_UNITS'),
('SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_UNIT_ROYAL_GUARD_REQ', 'CollectionType', 'COLLECTION_PLAYER_UNITS'),
('SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_UNIT_ROYAL_GUARD_REQ', 'Count', '4'),
('SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_UNIT_ROYAL_GUARD_REQ', 'RequirementSetId', 'SUBREQSET_NATIONAL_ROYAL_GUARD_CLASS_UNITS'),
('SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_UNIT_BEAST_OF_AGARES_REQ', 'CollectionType', 'COLLECTION_PLAYER_UNITS'),
('SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_UNIT_BEAST_OF_AGARES_REQ', 'Count', '4'),
('SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_UNIT_BEAST_OF_AGARES_REQ', 'RequirementSetId', 'SUBREQSET_NATIONAL_BEAST_OF_AGARES_CLASS_UNITS'),
('SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_UNIT_SHADOWRIDER_REQ', 'CollectionType', 'COLLECTION_PLAYER_UNITS'),
('SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_UNIT_SHADOWRIDER_REQ', 'Count', '4'),
('SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_UNIT_SHADOWRIDER_REQ', 'RequirementSetId', 'SUBREQSET_NATIONAL_SHADOWRIDER_CLASS_UNITS'),
('SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_UNIT_BEASTMASTER_REQ', 'CollectionType', 'COLLECTION_PLAYER_UNITS'),
('SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_UNIT_BEASTMASTER_REQ', 'Count', '4'),
('SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_UNIT_BEASTMASTER_REQ', 'RequirementSetId', 'SUBREQSET_NATIONAL_BEASTMASTER_CLASS_UNITS'),
('SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_UNIT_PHALANX_REQ', 'CollectionType', 'COLLECTION_PLAYER_UNITS'),
('SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_UNIT_PHALANX_REQ', 'Count', '4'),
('SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_UNIT_PHALANX_REQ', 'RequirementSetId', 'SUBREQSET_NATIONAL_PHALANX_CLASS_UNITS'),
('SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_UNIT_EIDOLON_REQ', 'CollectionType', 'COLLECTION_PLAYER_UNITS'),
('SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_UNIT_EIDOLON_REQ', 'Count', '4'),
('SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_UNIT_EIDOLON_REQ', 'RequirementSetId', 'SUBREQSET_NATIONAL_EIDOLON_CLASS_UNITS'),
('SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_UNIT_PALADIN_REQ', 'CollectionType', 'COLLECTION_PLAYER_UNITS'),
('SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_UNIT_PALADIN_REQ', 'Count', '4'),
('SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_UNIT_PALADIN_REQ', 'RequirementSetId', 'SUBREQSET_NATIONAL_PALADIN_CLASS_UNITS'),
('SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_UNIT_DRUID_REQ', 'CollectionType', 'COLLECTION_PLAYER_UNITS'),
('SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_UNIT_DRUID_REQ', 'Count', '4'),
('SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_UNIT_DRUID_REQ', 'RequirementSetId', 'SUBREQSET_NATIONAL_DRUID_CLASS_UNITS'),
('SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_UNIT_BONE_GOLEM_REQ', 'CollectionType', 'COLLECTION_PLAYER_UNITS'),
('SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_UNIT_BONE_GOLEM_REQ', 'Count', '4'),
('SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_UNIT_BONE_GOLEM_REQ', 'RequirementSetId', 'SUBREQSET_NATIONAL_BONE_GOLEM_CLASS_UNITS'),
('SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_UNIT_BERSERKER_REQ', 'CollectionType', 'COLLECTION_PLAYER_UNITS'),
('SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_UNIT_BERSERKER_REQ', 'Count', '4'),
('SLTH_CHECK_PLAYER_HAS_AT_LEAST_4_UNIT_BERSERKER_REQ', 'RequirementSetId', 'SUBREQSET_NATIONAL_BERSERKER_CLASS_UNITS');

INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('SUBREQSET_NATIONAL_SHADOW_CLASS_UNITS', 'IS_NATIONAL_UNIT_SHADOW_CLASS'),
('SUBREQSET_NATIONAL_CROSSBOWMAN_CLASS_UNITS', 'IS_NATIONAL_UNIT_CROSSBOWMAN_CLASS'),
('SUBREQSET_NATIONAL_MARKSMAN_CLASS_UNITS', 'IS_NATIONAL_UNIT_MARKSMAN_CLASS'),
('SUBREQSET_NATIONAL_ROYAL_GUARD_CLASS_UNITS', 'IS_NATIONAL_UNIT_ROYAL_GUARD_CLASS'),
('SUBREQSET_NATIONAL_BEAST_OF_AGARES_CLASS_UNITS', 'IS_NATIONAL_UNIT_BEAST_OF_AGARES_CLASS'),
('SUBREQSET_NATIONAL_SHADOWRIDER_CLASS_UNITS', 'IS_NATIONAL_UNIT_SHADOWRIDER_CLASS'),
('SUBREQSET_NATIONAL_BEASTMASTER_CLASS_UNITS', 'IS_NATIONAL_UNIT_BEASTMASTER_CLASS'),
('SUBREQSET_NATIONAL_PHALANX_CLASS_UNITS', 'IS_NATIONAL_UNIT_PHALANX_CLASS'),
('SUBREQSET_NATIONAL_EIDOLON_CLASS_UNITS', 'IS_NATIONAL_UNIT_EIDOLON_CLASS'),
('SUBREQSET_NATIONAL_PALADIN_CLASS_UNITS', 'IS_NATIONAL_UNIT_PALADIN_CLASS'),
('SUBREQSET_NATIONAL_DRUID_CLASS_UNITS', 'IS_NATIONAL_UNIT_DRUID_CLASS'),
('SUBREQSET_NATIONAL_BONE_GOLEM_CLASS_UNITS', 'IS_NATIONAL_UNIT_BONE_GOLEM_CLASS'),
('SUBREQSET_NATIONAL_BERSERKER_CLASS_UNITS', 'IS_NATIONAL_UNIT_BERSERKER_CLASS');

INSERT INTO RequirementSets(RequirementSetId, RequirementSetType) VALUES
('SUBREQSET_NATIONAL_SHADOW_CLASS_UNITS', 'REQUIREMENTSET_TEST_ALL'),
('SUBREQSET_NATIONAL_CROSSBOWMAN_CLASS_UNITS', 'REQUIREMENTSET_TEST_ALL'),
('SUBREQSET_NATIONAL_MARKSMAN_CLASS_UNITS', 'REQUIREMENTSET_TEST_ALL'),
('SUBREQSET_NATIONAL_ROYAL_GUARD_CLASS_UNITS', 'REQUIREMENTSET_TEST_ALL'),
('SUBREQSET_NATIONAL_BEAST_OF_AGARES_CLASS_UNITS', 'REQUIREMENTSET_TEST_ALL'),
('SUBREQSET_NATIONAL_SHADOWRIDER_CLASS_UNITS', 'REQUIREMENTSET_TEST_ALL'),
('SUBREQSET_NATIONAL_BEASTMASTER_CLASS_UNITS', 'REQUIREMENTSET_TEST_ALL'),
('SUBREQSET_NATIONAL_PHALANX_CLASS_UNITS', 'REQUIREMENTSET_TEST_ALL'),
('SUBREQSET_NATIONAL_EIDOLON_CLASS_UNITS', 'REQUIREMENTSET_TEST_ALL'),
('SUBREQSET_NATIONAL_PALADIN_CLASS_UNITS', 'REQUIREMENTSET_TEST_ALL'),
('SUBREQSET_NATIONAL_DRUID_CLASS_UNITS', 'REQUIREMENTSET_TEST_ALL'),
('SUBREQSET_NATIONAL_BONE_GOLEM_CLASS_UNITS', 'REQUIREMENTSET_TEST_ALL'),
('SUBREQSET_NATIONAL_BERSERKER_CLASS_UNITS', 'REQUIREMENTSET_TEST_ALL');

INSERT INTO Requirements(RequirementId, RequirementType) VALUES
('IS_NATIONAL_UNIT_SHADOW_CLASS', 'REQUIREMENT_UNIT_TAG_MATCHES'),
('IS_NATIONAL_UNIT_CROSSBOWMAN_CLASS', 'REQUIREMENT_UNIT_TAG_MATCHES'),
('IS_NATIONAL_UNIT_MARKSMAN_CLASS', 'REQUIREMENT_UNIT_TAG_MATCHES'),
('IS_NATIONAL_UNIT_ROYAL_GUARD_CLASS', 'REQUIREMENT_UNIT_TAG_MATCHES'),
('IS_NATIONAL_UNIT_BEAST_OF_AGARES_CLASS', 'REQUIREMENT_UNIT_TAG_MATCHES'),
('IS_NATIONAL_UNIT_SHADOWRIDER_CLASS', 'REQUIREMENT_UNIT_TAG_MATCHES'),
('IS_NATIONAL_UNIT_BEASTMASTER_CLASS', 'REQUIREMENT_UNIT_TAG_MATCHES'),
('IS_NATIONAL_UNIT_PHALANX_CLASS', 'REQUIREMENT_UNIT_TAG_MATCHES'),
('IS_NATIONAL_UNIT_EIDOLON_CLASS', 'REQUIREMENT_UNIT_TAG_MATCHES'),
('IS_NATIONAL_UNIT_PALADIN_CLASS', 'REQUIREMENT_UNIT_TAG_MATCHES'),
('IS_NATIONAL_UNIT_DRUID_CLASS', 'REQUIREMENT_UNIT_TAG_MATCHES'),
('IS_NATIONAL_UNIT_BONE_GOLEM_CLASS', 'REQUIREMENT_UNIT_TAG_MATCHES'),
('IS_NATIONAL_UNIT_BERSERKER_CLASS', 'REQUIREMENT_UNIT_TAG_MATCHES');

INSERT INTO RequirementArguments(RequirementId, Name, Value) VALUES
('IS_NATIONAL_UNIT_SHADOW_CLASS', 'Tag', 'CLASS_NATIONAL_SHADOW'),
('IS_NATIONAL_UNIT_CROSSBOWMAN_CLASS', 'Tag', 'CLASS_NATIONAL_CROSSBOWMAN'),
('IS_NATIONAL_UNIT_MARKSMAN_CLASS', 'Tag', 'CLASS_NATIONAL_MARKSMAN'),
('IS_NATIONAL_UNIT_ROYAL_GUARD_CLASS', 'Tag', 'CLASS_NATIONAL_ROYAL_GUARD'),
('IS_NATIONAL_UNIT_BEAST_OF_AGARES_CLASS', 'Tag', 'CLASS_NATIONAL_BEAST_OF_AGARES'),
('IS_NATIONAL_UNIT_SHADOWRIDER_CLASS', 'Tag', 'CLASS_NATIONAL_SHADOWRIDER'),
('IS_NATIONAL_UNIT_BEASTMASTER_CLASS', 'Tag', 'CLASS_NATIONAL_BEASTMASTER'),
('IS_NATIONAL_UNIT_PHALANX_CLASS', 'Tag', 'CLASS_NATIONAL_PHALANX'),
('IS_NATIONAL_UNIT_EIDOLON_CLASS', 'Tag', 'CLASS_NATIONAL_EIDOLON'),
('IS_NATIONAL_UNIT_PALADIN_CLASS', 'Tag', 'CLASS_NATIONAL_PALADIN'),
('IS_NATIONAL_UNIT_DRUID_CLASS', 'Tag', 'CLASS_NATIONAL_DRUID'),
('IS_NATIONAL_UNIT_BONE_GOLEM_CLASS', 'Tag', 'CLASS_NATIONAL_BONE_GOLEM'),
('IS_NATIONAL_UNIT_BERSERKER_CLASS', 'Tag', 'CLASS_NATIONAL_BERSERKER');


INSERT INTO Tags(Tag, Vocabulary) VALUES
('CLASS_NATIONAL_SHADOW', 'ABILITY_CLASS'),
('CLASS_NATIONAL_CROSSBOWMAN', 'ABILITY_CLASS'),
('CLASS_NATIONAL_MARKSMAN', 'ABILITY_CLASS'),
('CLASS_NATIONAL_ROYAL_GUARD', 'ABILITY_CLASS'),
('CLASS_NATIONAL_BEAST_OF_AGARES', 'ABILITY_CLASS'),
('CLASS_NATIONAL_SHADOWRIDER', 'ABILITY_CLASS'),
('CLASS_NATIONAL_BEASTMASTER', 'ABILITY_CLASS'),
('CLASS_NATIONAL_PHALANX', 'ABILITY_CLASS'),
('CLASS_NATIONAL_EIDOLON', 'ABILITY_CLASS'),
('CLASS_NATIONAL_PALADIN', 'ABILITY_CLASS'),
('CLASS_NATIONAL_DRUID', 'ABILITY_CLASS'),
('CLASS_NATIONAL_BONE_GOLEM', 'ABILITY_CLASS'),
('CLASS_NATIONAL_BERSERKER', 'ABILITY_CLASS');


INSERT INTO TypeTags(Type, Tag) VALUES
('SLTH_UNIT_SHADOW', 'CLASS_NATIONAL_SHADOW'),
('SLTH_UNIT_DWARVEN_SHADOW', 'CLASS_NATIONAL_SHADOW'),
('SLTH_UNIT_COURTESAN', 'CLASS_NATIONAL_SHADOW'),
('SLTH_UNIT_CROSSBOWMAN', 'CLASS_NATIONAL_CROSSBOWMAN'),
('SLTH_UNIT_FLURRY', 'CLASS_NATIONAL_CROSSBOWMAN'),
('SLTH_UNIT_MARKSMAN', 'CLASS_NATIONAL_MARKSMAN'),
('SLTH_UNIT_ROYAL_GUARD', 'CLASS_NATIONAL_ROYAL_GUARD'),
('SLTH_UNIT_BEAST_OF_AGARES', 'CLASS_NATIONAL_BEAST_OF_AGARES'),
('SLTH_UNIT_SHADOWRIDER', 'CLASS_NATIONAL_SHADOWRIDER'),
('SLTH_UNIT_BEASTMASTER', 'CLASS_NATIONAL_BEASTMASTER'),
('SLTH_UNIT_MYCONID', 'CLASS_NATIONAL_BEASTMASTER'),
('SLTH_UNIT_PHALANX', 'CLASS_NATIONAL_PHALANX'),
('SLTH_UNIT_STONESKIN_OGRE', 'CLASS_NATIONAL_PHALANX'),
('SLTH_UNIT_NULLSTONE_GOLEM', 'CLASS_NATIONAL_PHALANX'),
('SLTH_UNIT_EIDOLON', 'CLASS_NATIONAL_EIDOLON'),
('SLTH_UNIT_PALADIN', 'CLASS_NATIONAL_PALADIN'),
('SLTH_UNIT_DRUID', 'CLASS_NATIONAL_DRUID'),
('SLTH_UNIT_DWARVEN_DRUID', 'CLASS_NATIONAL_DRUID'),
('SLTH_UNIT_BONE_GOLEM', 'CLASS_NATIONAL_BONE_GOLEM'),
('SLTH_UNIT_BERSERKER', 'CLASS_NATIONAL_BERSERKER'),
('SLTH_UNIT_BALOR', 'CLASS_NATIONAL_BERSERKER'),
('SLTH_UNIT_BRUJAH', 'CLASS_NATIONAL_BERSERKER'),
('SLTH_UNIT_CLOCKWORK_GOLEM', 'CLASS_NATIONAL_BERSERKER');

--- END

--  Bone Golem
-- Immortal (special case since should be upgrade only... Vampire Lord, Ogre Warchief)

-- not covered
-- Archmage (special case, since can only upgrade   . Eater of Dreams)
-- High Priests (special case, since can only upgrade, including Luonnotar here)
-- Lich (Special case, not covered here)
-- Angel weirdness, as all upgrades. Repentant Angel, Ophanim, Seraph, Angel of Death, Valkyrie, Herald