CREATE TABLE IF NOT EXISTS NatWonders(FeatureType PRIMARY KEY);

INSERT INTO NatWonders(FeatureType)
VALUES ('FEATURE_BERMUDA_TRIANGLE'),
       ('FEATURE_FOUNTAIN_OF_YOUTH'),
       ('FEATURE_IKKIL'),
       ('FEATURE_MATTERHORN'),
       ('FEATURE_TSINGY'),
       ('FEATURE_NWON_TOMB_OF_SUCELLUS'),                              -- FEATURE_HA_LONG_BAY
       ('FEATURE_NWON_YGGDRASIL'),                                     -- was FEATURE_PANTANAL
       ('FEATURE_NWON_REMNANTS_OF_PATRIA'),                            -- was FEATURE_PAITITI
       ('FEATURE_EYE_OF_THE_SAHARA'),
       ('FEATURE_UBSUNUR_HOLLOW'),
       ('FEATURE_NWON_BRADELINES_WELL'),                               -- was GOBUSTAN
       ('FEATURE_DELICATE_ARCH'),
       ('FEATURE_YOSEMITE'),
       ('FEATURE_DEVILSTOWER'),
       ('FEATURE_NWON_SEVEN_PINES'),                                   -- was FEATURE_CHOCOLATEHILLS
       ('FEATURE_TORRES_DEL_PAINE');

UPDATE Features SET Impassable=0, Tiles=1, CustomPlacement= NULL WHERE NaturalWonder = 1;

INSERT INTO Types(Type, Kind) VALUES
('FEATURE_NWON_TOMB_OF_SUCELLUS', 'KIND_FEATURE'),
('FEATURE_NWON_YGGDRASIL', 'KIND_FEATURE'),
('FEATURE_NWON_REMNANTS_OF_PATRIA', 'KIND_FEATURE'),
('FEATURE_NWON_BRADELINES_WELL', 'KIND_FEATURE'),
('FEATURE_NWON_SEVEN_PINES', 'KIND_FEATURE');

UPDATE Features SET Name='LOC_FEATURE_MAELSTROM_NAME', Description='LOC_FEATURE_MAELSTROM_DESCRIPTION', NaturalWonder=0 WHERE FeatureType='FEATURE_BERMUDA_TRIANGLE';
UPDATE Features SET Name='LOC_FEATURE_POOL_OF_TEARS_NAME', Description='LOC_FEATURE_POOL_OF_TEARS_DESCRIPTION', NaturalWonder=0 WHERE FeatureType='FEATURE_FOUNTAIN_OF_YOUTH';
UPDATE Features SET Name='LOC_FEATURE_MIRROR_OF_HEAVEN_NAME', Description='LOC_FEATURE_MIRROR_OF_HEAVEN_DESCRIPTION', NaturalWonder=0 WHERE FeatureType='FEATURE_IKKIL';
UPDATE Features SET Name='LOC_FEATURE_PRISTIN_NAME', Description='LOC_FEATURE_PRISTIN_DESCRIPTION', NaturalWonder=0, Impassable=1 WHERE FeatureType='FEATURE_MATTERHORN';
UPDATE Features SET Name='LOC_FEATURE_STANDING_STONES_NAME', Description='LOC_FEATURE_STANDING_STONES_DESCRIPTION', NaturalWonder=0 WHERE FeatureType='FEATURE_TSINGY';
UPDATE Features SET FeatureType= 'FEATURE_NWON_TOMB_OF_SUCELLUS', Name='LOC_FEATURE_TOMB_NAME', Description='LOC_FEATURE_TOMB_DESCRIPTION', NaturalWonder=0 WHERE FeatureType='FEATURE_HA_LONG_BAY';
UPDATE Features SET FeatureType= 'FEATURE_NWON_YGGDRASIL', Name='LOC_FEATURE_YGGDRASIL_NAME', Description='LOC_FEATURE_YGGDRASIL_DESCRIPTION', NaturalWonder=0 WHERE FeatureType='FEATURE_PANTANAL';
UPDATE Features SET FeatureType= 'FEATURE_NWON_REMNANTS_OF_PATRIA', Name='LOC_FEATURE_PATRIA_NAME', Description='LOC_FEATURE_PATRIA_DESCRIPTION', NaturalWonder=0 WHERE FeatureType='FEATURE_PAITITI';
UPDATE Features SET Name='LOC_FEATURE_FRIGUS_NAME', Description='LOC_FEATURE_FRIGUS_DESCRIPTION', NaturalWonder=0 WHERE FeatureType='FEATURE_UBSUNUR_HOLLOW';
UPDATE Features SET Name='LOC_FEATURE_BONES_NAME', Description='LOC_FEATURE_BONES_DESCRIPTION', NaturalWonder=0 WHERE FeatureType='FEATURE_EYE_OF_THE_SAHARA';
UPDATE Features SET FeatureType= 'FEATURE_NWON_BRADELINES_WELL', Name='LOC_FEATURE_WELL_NAME', Description='LOC_FEATURE_WELL_DESCRIPTION', NaturalWonder=0 WHERE FeatureType='FEATURE_GOBUSTAN';
UPDATE Features SET Name='LOC_FEATURE_SEPULCHER_NAME', Description='LOC_FEATURE_SEPULCHER_DESCRIPTION', NaturalWonder=0 WHERE FeatureType='FEATURE_DELICATE_ARCH';
UPDATE Features SET Name='LOC_FEATURE_PYRE_NAME', Description='LOC_FEATURE_PYRE_DESCRIPTION', NaturalWonder=0 WHERE FeatureType='FEATURE_YOSEMITE';
UPDATE Features SET Name='LOC_FEATURE_MAENALUS_NAME', Description='LOC_FEATURE_MAENALUS_DESCRIPTION', NaturalWonder=0 WHERE FeatureType='FEATURE_BARRIER_REEF';
UPDATE Features SET Name='LOC_FEATURE_ODIO_NAME', Description='LOC_FEATURE_ODIO_DESCRIPTION', NaturalWonder=0 WHERE FeatureType='FEATURE_DEVILSTOWER';
UPDATE Features SET FeatureType= 'FEATURE_NWON_SEVEN_PINES', Name='LOC_FEATURE_PINES_NAME', Description='LOC_FEATURE_PINES_DESCRIPTION', NaturalWonder=0 WHERE FeatureType='FEATURE_CHOCOLATEHILLS';
UPDATE Features SET Name='LOC_FEATURE_CARCER_NAME', Description='LOC_FEATURE_CARCER_DESCRIPTION', NaturalWonder=0 WHERE FeatureType='FEATURE_TORRES_DEL_PAINE';


INSERT INTO Improvement_ValidFeatures (ImprovementType, FeatureType) VALUES
('IMPROVEMENT_BARBARIAN_CAMP', 'FEATURE_UBSUNUR_HOLLOW'),
('IMPROVEMENT_BARBARIAN_CAMP', 'FEATURE_NWON_BRADELINES_WELL'),
('IMPROVEMENT_BARBARIAN_CAMP', 'FEATURE_DELICATE_ARCH'),
('IMPROVEMENT_BARBARIAN_CAMP', 'FEATURE_YOSEMITE');

DELETE FROM Feature_AdjacentYields;
DELETE FROM Feature_YieldChanges WHERE FeatureType NOT IN ('FEATURE_FLOODPLAINS', 'FEATURE_JUNGLE', 'FEATURE_FOREST',
                                                           'FEATURE_OASIS', 'FEATURE_MARSH', 'FEATURE_SHALLOWS',
                                                           'FEATURE_OBSIDIAN_PLAINS', 'FEATURE_FOREST_ANCIENT', 'FEATURE_REEF');

DELETE FROM Feature_ValidTerrains WHERE FeatureType IN ('FEATURE_FOUNTAIN_OF_YOUTH', 'FEATURE_IKKIL',
                                                        'FEATURE_MATTERHORN', 'FEATURE_TSINGY', 'FEATURE_NWON_TOMB_OF_SUCELLUS',
                                                       'FEATURE_NWON_YGGDRASIL', 'FEATURE_NWON_REMNANTS_OF_PATRIA', 'FEATURE_EYE_OF_THE_SAHARA',
                                                       'FEATURE_UBSUNUR_HOLLOW', 'FEATURE_NWON_BRADELINES_WELL', 'FEATURE_DELICATE_ARCH',
                                                       'FEATURE_YOSEMITE', 'FEATURE_DEVILSTOWER', 'FEATURE_NWON_SEVEN_PINES',
                                                       'FEATURE_TORRES_DEL_PAINE');

INSERT INTO Feature_AdjacentFeatures(FeatureType, FeatureTypeAdjacent) VALUES
('FEATURE_NWON_TOMB_OF_SUCELLUS', 'FEATURE_FOREST'),
('FEATURE_NWON_SEVEN_PINES', 'FEATURE_FOREST');

INSERT INTO Feature_ValidTerrains (FeatureType, TerrainType) VALUES
('FEATURE_FOUNTAIN_OF_YOUTH', 'TERRAIN_GRASS'),
('FEATURE_FOUNTAIN_OF_YOUTH', 'TERRAIN_PLAINS'),
('FEATURE_FOUNTAIN_OF_YOUTH', 'TERRAIN_DESERT'),
('FEATURE_IKKIL', 'TERRAIN_DESERT'),
('FEATURE_IKKIL', 'TERRAIN_DESERT_HILLS'),
('FEATURE_MATTERHORN', 'TERRAIN_GRASS'),
('FEATURE_MATTERHORN', 'TERRAIN_GRASS_HILLS'),
('FEATURE_MATTERHORN', 'TERRAIN_PLAINS'),
('FEATURE_MATTERHORN', 'TERRAIN_PLAINS_HILLS'),
('FEATURE_MATTERHORN', 'TERRAIN_DESERT'),
('FEATURE_MATTERHORN', 'TERRAIN_DESERT_HILLS'),
('FEATURE_MATTERHORN', 'TERRAIN_TUNDRA'),
('FEATURE_MATTERHORN', 'TERRAIN_TUNDRA_HILLS'),
('FEATURE_TSINGY', 'TERRAIN_GRASS'),
('FEATURE_TSINGY', 'TERRAIN_PLAINS'),
('FEATURE_TSINGY', 'TERRAIN_DESERT'),
('FEATURE_TSINGY', 'TERRAIN_SNOW'),
('FEATURE_TSINGY', 'TERRAIN_TUNDRA'),
('FEATURE_NWON_TOMB_OF_SUCELLUS', 'TERRAIN_GRASS'),
('FEATURE_NWON_TOMB_OF_SUCELLUS', 'TERRAIN_GRASS_HILLS'),
('FEATURE_NWON_TOMB_OF_SUCELLUS', 'TERRAIN_PLAINS'),
('FEATURE_NWON_TOMB_OF_SUCELLUS', 'TERRAIN_PLAINS_HILLS'),
('FEATURE_NWON_YGGDRASIL', 'TERRAIN_GRASS'),                  --marsh skipped
('FEATURE_NWON_YGGDRASIL', 'TERRAIN_GRASS_HILLS'),
('FEATURE_NWON_YGGDRASIL', 'TERRAIN_TUNDRA'),
('FEATURE_NWON_YGGDRASIL', 'TERRAIN_TUNDRA_HILLS'),
('FEATURE_NWON_REMNANTS_OF_PATRIA', 'TERRAIN_GRASS'),
('FEATURE_NWON_REMNANTS_OF_PATRIA', 'TERRAIN_GRASS_HILLS'),
('FEATURE_NWON_REMNANTS_OF_PATRIA', 'TERRAIN_PLAINS'),
('FEATURE_NWON_REMNANTS_OF_PATRIA', 'TERRAIN_PLAINS_HILLS'),
('FEATURE_NWON_REMNANTS_OF_PATRIA', 'TERRAIN_DESERT'),
('FEATURE_NWON_REMNANTS_OF_PATRIA', 'TERRAIN_DESERT_HILLS'),
('FEATURE_NWON_REMNANTS_OF_PATRIA', 'TERRAIN_TUNDRA'),
('FEATURE_NWON_REMNANTS_OF_PATRIA', 'TERRAIN_TUNDRA_HILLS'),
('FEATURE_EYE_OF_THE_SAHARA', 'TERRAIN_GRASS'),
('FEATURE_EYE_OF_THE_SAHARA', 'TERRAIN_GRASS_HILLS'),
('FEATURE_EYE_OF_THE_SAHARA', 'TERRAIN_PLAINS'),
('FEATURE_EYE_OF_THE_SAHARA', 'TERRAIN_PLAINS_HILLS'),
('FEATURE_EYE_OF_THE_SAHARA', 'TERRAIN_DESERT'),
('FEATURE_EYE_OF_THE_SAHARA', 'TERRAIN_DESERT_HILLS'),
('FEATURE_EYE_OF_THE_SAHARA', 'TERRAIN_TUNDRA'),
('FEATURE_EYE_OF_THE_SAHARA', 'TERRAIN_TUNDRA_HILLS'),
('FEATURE_EYE_OF_THE_SAHARA', 'TERRAIN_SNOW'),
('FEATURE_EYE_OF_THE_SAHARA', 'TERRAIN_SNOW_HILLS'),
('FEATURE_UBSUNUR_HOLLOW', 'TERRAIN_TUNDRA'),
('FEATURE_UBSUNUR_HOLLOW', 'TERRAIN_TUNDRA_HILLS'),
('FEATURE_UBSUNUR_HOLLOW', 'TERRAIN_SNOW'),
('FEATURE_UBSUNUR_HOLLOW', 'TERRAIN_SNOW_HILLS'),
('FEATURE_NWON_BRADELINES_WELL', 'TERRAIN_GRASS'),
('FEATURE_NWON_BRADELINES_WELL', 'TERRAIN_PLAINS'),
('FEATURE_NWON_BRADELINES_WELL', 'TERRAIN_DESERT'),
('FEATURE_NWON_BRADELINES_WELL', 'TERRAIN_SNOW'),
('FEATURE_NWON_BRADELINES_WELL', 'TERRAIN_TUNDRA'),
('FEATURE_DELICATE_ARCH', 'TERRAIN_GRASS'),
('FEATURE_DELICATE_ARCH', 'TERRAIN_GRASS_HILLS'),
('FEATURE_DELICATE_ARCH', 'TERRAIN_PLAINS'),
('FEATURE_DELICATE_ARCH', 'TERRAIN_PLAINS_HILLS'),
('FEATURE_DELICATE_ARCH', 'TERRAIN_DESERT'),
('FEATURE_DELICATE_ARCH', 'TERRAIN_DESERT_HILLS'),
('FEATURE_DELICATE_ARCH', 'TERRAIN_TUNDRA'),
('FEATURE_DELICATE_ARCH', 'TERRAIN_TUNDRA_HILLS'),
('FEATURE_DELICATE_ARCH', 'TERRAIN_SNOW'),
('FEATURE_DELICATE_ARCH', 'TERRAIN_SNOW_HILLS'),
('FEATURE_YOSEMITE', 'TERRAIN_PLAINS'),
('FEATURE_YOSEMITE', 'TERRAIN_DESERT'),
('FEATURE_DEVILSTOWER', 'TERRAIN_GRASS'),
('FEATURE_DEVILSTOWER', 'TERRAIN_PLAINS'),
('FEATURE_DEVILSTOWER', 'TERRAIN_DESERT'),
('FEATURE_DEVILSTOWER', 'TERRAIN_TUNDRA'),
('FEATURE_NWON_SEVEN_PINES', 'TERRAIN_GRASS'),
('FEATURE_NWON_SEVEN_PINES', 'TERRAIN_PLAINS'),
('FEATURE_NWON_SEVEN_PINES', 'TERRAIN_TUNDRA'),
('FEATURE_TORRES_DEL_PAINE', 'TERRAIN_SNOW'),
('FEATURE_TORRES_DEL_PAINE', 'TERRAIN_SNOW_HILLS');

-- maelstrom FEATURE_BERMUDA_TRIANGLE               water, ocean.
-- pool of tears FEATURE_FOUNTAIN_OF_YOUTH          flatland,  grass,plains,desert
-- mirror of heaven FEATURE_IKKIL                   desert, can be hills?
--  guardianspristin  FEATURE_MATTERHORN            mountain, any terrain
-- stones   FEATURE_TSINGY                      flatland, any terrain
-- sucell8s tomb            FEATURE_HA_LONG_BAY, Valid in grass or plains, on forest or jungle
-- yggdrasil    FEATURE_PANTANAL                    grass, marsh, or tundra?
-- remnants     FEATURE_NWON_REMNANTS_OF_PATRIA                     grass, plains, desert, marsh, tundra
-- dragon bones         FEATURE_EYE_OF_THE_SAHARA               any terrain

-- letum frigus         FEATURE_UBSUNUR_HOLLOW                  snow or tundra
-- bradelines well  FEATURE_GOBUSTAN                            flatlands, any terrain
-- broken sepulcher     FEATURE_DELICATE_ARCH                   any terrain,
-- pyre         FEATURE_YOSEMITE                                flatlands, plains, desert


-- maenalus    FEATURE_BARRIER_REEF                             -- not existant?
-- odios prison         FEATURE_DEVILSTOWER                     any terrain but snow, flatland
-- seven pines                  FEATURE_CHOCOLATEHILLS          flatland, grass,plains, tundra, forest
-- ring of carcer               FEATURE_TORRES_DEL_PAINE        snow only


INSERT INTO Feature_YieldChanges(FeatureType, YieldType, YieldChange) VALUES
-- i swore FEATURE_FOUNTAIN_OF_YOUTH, i.e. pool of tears gave yields
('FEATURE_IKKIL', 'YIELD_PRODUCTION', '3'),
('FEATURE_NWON_REMNANTS_OF_PATRIA', 'YIELD_PRODUCTION', '3'),
('FEATURE_NWON_YGGDRASIL', 'YIELD_FOOD', '3'),
('FEATURE_EYE_OF_THE_SAHARA', 'YIELD_FAITH', '3');
-- FEATURE_NWON_YGGDRASIL (3,,) -- also (2,,) after way of forests, (2,,) after commune with nature
-- FEATURE_EYE_OF_THE_SAHARA (,,3) -- also (,,2) after trade, (,,2) after construction
--