INSERT INTO Traits(TraitType, Name, Description) VALUES
('SLTH_TRAIT_RELIGION_UNIT_ARTHENDAIN', 'LOC_SLTH_TRAIT_RELIGION_UNIT_ARTHENDAIN_NAME', 'LOC_SLTH_TRAIT_RELIGION_UNIT_ARTHENDAIN_DESCRIPTION'),
('SLTH_TRAIT_RELIGION_UNIT_BAMBUR', 'LOC_SLTH_TRAIT_RELIGION_UNIT_BAMBUR_NAME', 'LOC_SLTH_TRAIT_RELIGION_UNIT_BAMBUR_DESCRIPTION'),
('SLTH_TRAIT_RELIGION_UNIT_HIGH_PRIEST_OF_KILMORPH', 'LOC_SLTH_TRAIT_RELIGION_UNIT_HIGH_PRIEST_OF_KILMORPH_NAME', 'LOC_SLTH_TRAIT_RELIGION_UNIT_HIGH_PRIEST_OF_KILMORPH_DESCRIPTION'),
('SLTH_TRAIT_RELIGION_UNIT_MITHRIL_GOLEM', 'LOC_SLTH_TRAIT_RELIGION_UNIT_MITHRIL_GOLEM_NAME', 'LOC_SLTH_TRAIT_RELIGION_UNIT_MITHRIL_GOLEM_DESCRIPTION'),
('SLTH_TRAIT_RELIGION_UNIT_PARAMANDER', 'LOC_SLTH_TRAIT_RELIGION_UNIT_PARAMANDER_NAME', 'LOC_SLTH_TRAIT_RELIGION_UNIT_PARAMANDER_DESCRIPTION'),
('SLTH_TRAIT_RELIGION_UNIT_PRIEST_OF_KILMORPH', 'LOC_SLTH_TRAIT_RELIGION_UNIT_PRIEST_OF_KILMORPH_NAME', 'LOC_SLTH_TRAIT_RELIGION_UNIT_PRIEST_OF_KILMORPH_DESCRIPTION'),
('SLTH_TRAIT_RELIGION_UNIT_DISCIPLE_OCTOPUS_OVERLORDS', 'LOC_SLTH_TRAIT_RELIGION_UNIT_DISCIPLE_OCTOPUS_OVERLORDS_NAME', 'LOC_SLTH_TRAIT_RELIGION_UNIT_DISCIPLE_OCTOPUS_OVERLORDS_DESCRIPTION'),
('SLTH_TRAIT_RELIGION_UNIT_DROWN', 'LOC_SLTH_TRAIT_RELIGION_UNIT_DROWN_NAME', 'LOC_SLTH_TRAIT_RELIGION_UNIT_DROWN_DESCRIPTION'),
('SLTH_TRAIT_RELIGION_UNIT_HEMAH', 'LOC_SLTH_TRAIT_RELIGION_UNIT_HEMAH_NAME', 'LOC_SLTH_TRAIT_RELIGION_UNIT_HEMAH_DESCRIPTION'),
('SLTH_TRAIT_RELIGION_UNIT_HIGH_PRIEST_OF_THE_OVERLORDS', 'LOC_SLTH_TRAIT_RELIGION_UNIT_HIGH_PRIEST_OF_THE_OVERLORDS_NAME', 'LOC_SLTH_TRAIT_RELIGION_UNIT_HIGH_PRIEST_OF_THE_OVERLORDS_DESCRIPTION'),
('SLTH_TRAIT_RELIGION_UNIT_LUNATIC', 'LOC_SLTH_TRAIT_RELIGION_UNIT_LUNATIC_NAME', 'LOC_SLTH_TRAIT_RELIGION_UNIT_LUNATIC_DESCRIPTION'),
('SLTH_TRAIT_RELIGION_UNIT_PRIEST_OF_THE_OVERLORDS', 'LOC_SLTH_TRAIT_RELIGION_UNIT_PRIEST_OF_THE_OVERLORDS_NAME', 'LOC_SLTH_TRAIT_RELIGION_UNIT_PRIEST_OF_THE_OVERLORDS_DESCRIPTION'),
('SLTH_TRAIT_RELIGION_UNIT_SAVEROUS', 'LOC_SLTH_TRAIT_RELIGION_UNIT_SAVEROUS_NAME', 'LOC_SLTH_TRAIT_RELIGION_UNIT_SAVEROUS_DESCRIPTION'),
('SLTH_TRAIT_RELIGION_UNIT_CRUSADER', 'LOC_SLTH_TRAIT_RELIGION_UNIT_CRUSADER_NAME', 'LOC_SLTH_TRAIT_RELIGION_UNIT_CRUSADER_DESCRIPTION'),
('SLTH_TRAIT_RELIGION_UNIT_DISCIPLE_THE_ORDER', 'LOC_SLTH_TRAIT_RELIGION_UNIT_DISCIPLE_THE_ORDER_NAME', 'LOC_SLTH_TRAIT_RELIGION_UNIT_DISCIPLE_THE_ORDER_DESCRIPTION'),
('SLTH_TRAIT_RELIGION_UNIT_HIGH_PRIEST_OF_THE_ORDER', 'LOC_SLTH_TRAIT_RELIGION_UNIT_HIGH_PRIEST_OF_THE_ORDER_NAME', 'LOC_SLTH_TRAIT_RELIGION_UNIT_HIGH_PRIEST_OF_THE_ORDER_DESCRIPTION'),
('SLTH_TRAIT_RELIGION_UNIT_PRIEST_OF_THE_ORDER', 'LOC_SLTH_TRAIT_RELIGION_UNIT_PRIEST_OF_THE_ORDER_NAME', 'LOC_SLTH_TRAIT_RELIGION_UNIT_PRIEST_OF_THE_ORDER_DESCRIPTION'),
('SLTH_TRAIT_RELIGION_UNIT_VALIN', 'LOC_SLTH_TRAIT_RELIGION_UNIT_VALIN_NAME', 'LOC_SLTH_TRAIT_RELIGION_UNIT_VALIN_DESCRIPTION');

INSERT INTO Beliefs (BeliefType, Name, Description, BeliefClassType) VALUES
('BELIEF_THE_ORDER_PANTH', 'LOC_BELIEF_THE_ORDER_PANTH_NAME', 'LOC_BELIEF_THE_ORDER_PANTH_DESCRIPTION', 'BELIEF_CLASS_PANTHEON'),
('BELIEF_EMPYREAN_PANTH', 'LOC_BELIEF_EMPYREAN_PANTH_NAME', 'LOC_BELIEF_EMPYREAN_PANTH_DESCRIPTION', 'BELIEF_CLASS_PANTHEON'),
('BELIEF_KILMORPH_PANTH', 'LOC_BELIEF_KILMORPH_PANTH_NAME', 'LOC_BELIEF_KILMORPH_PANTH_DESCRIPTION', 'BELIEF_CLASS_PANTHEON'),
('BELIEF_LEAVES_PANTH', 'LOC_BELIEF_LEAVES_PANTH_NAME', 'LOC_BELIEF_LEAVES_PANTH_DESCRIPTION', 'BELIEF_CLASS_PANTHEON'),
('BELIEF_OVERLORDS_PANTH', 'LOC_BELIEF_OVERLORDS_PANTH_NAME', 'LOC_BELIEF_OVERLORDS_PANTH_DESCRIPTION', 'BELIEF_CLASS_PANTHEON'),
('BELIEF_ESUS_PANTH', 'LOC_BELIEF_ESUS_PANTH_NAME', 'LOC_BELIEF_ESUS_PANTH_DESCRIPTION', 'BELIEF_CLASS_PANTHEON'),
('BELIEF_VEIL_PANTH', 'LOC_BELIEF_VEIL_PANTH_NAME', 'LOC_BELIEF_VEIL_PANTH_DESCRIPTION', 'BELIEF_CLASS_PANTHEON');

INSERT INTO Religions (ReligionType, Name, IconString, Color) VALUES
('RELIGION_THE_ORDER', 'LOC_RELIGION_THE_ORDER', 'Pr', 'COLOR_RELIGION_PROTESTANTISM'),
('RELIGION_EMPYREAN', 'LOC_RELIGION_EMPYREAN', 'Ju', 'COLOR_RELIGION_CUSTOM_4'),            -- Mahayana Buddhism sun if KhmerScenario
('RELIGION_KILMORPH', 'LOC_RELIGION_KILMORPH', 'Co', 'COLOR_RELIGION_JUDAISM'),
('RELIGION_LEAVES', 'LOC_RELIGION_LEAVES', '8', 'COLOR_RELIGION_HINDUISM'),
('RELIGION_OVERLORDS', 'LOC_RELIGION_OVERLORDS', '9', 'COLOR_RELIGION_SIKHISM'),           -- could use Shaivism tentacle icon if KhmerScenario
('RELIGION_ESUS', 'LOC_RELIGION_ESUS', 'Is', 'COLOR_RELIGION_ZOROASTRIANISM'),
('RELIGION_VEIL', 'LOC_RELIGION_VEIL', 'Bu', 'COLOR_RELIGION_CATHOLICISM');


INSERT INTO Types(Type, Kind) VALUES
('BELIEF_THE_ORDER_PANTH', 'KIND_BELIEF'),
('BELIEF_EMPYREAN_PANTH', 'KIND_BELIEF'),
('BELIEF_KILMORPH_PANTH', 'KIND_BELIEF'),
('BELIEF_LEAVES_PANTH', 'KIND_BELIEF'),
('BELIEF_OVERLORDS_PANTH', 'KIND_BELIEF'),
('BELIEF_ESUS_PANTH', 'KIND_BELIEF'),
('BELIEF_VEIL_PANTH', 'KIND_BELIEF'),
('RELIGION_THE_ORDER', 'KIND_RELIGION'),
('RELIGION_EMPYREAN', 'KIND_RELIGION'),
('RELIGION_KILMORPH', 'KIND_RELIGION'),
('RELIGION_LEAVES', 'KIND_RELIGION'),
('RELIGION_OVERLORDS', 'KIND_RELIGION'),
('RELIGION_ESUS', 'KIND_RELIGION'),
('RELIGION_VEIL', 'KIND_RELIGION');

INSERT INTO Types(Type, Kind) VALUES
('SLTH_TRAIT_RELIGION_UNIT_ARTHENDAIN', 'KIND_TRAIT'),
('SLTH_TRAIT_RELIGION_UNIT_BAMBUR', 'KIND_TRAIT'),
('SLTH_TRAIT_RELIGION_UNIT_HIGH_PRIEST_OF_KILMORPH', 'KIND_TRAIT'),
('SLTH_TRAIT_RELIGION_UNIT_MITHRIL_GOLEM', 'KIND_TRAIT'),
('SLTH_TRAIT_RELIGION_UNIT_PARAMANDER', 'KIND_TRAIT'),
('SLTH_TRAIT_RELIGION_UNIT_PRIEST_OF_KILMORPH', 'KIND_TRAIT'),
('SLTH_TRAIT_RELIGION_UNIT_DISCIPLE_OCTOPUS_OVERLORDS', 'KIND_TRAIT'),
('SLTH_TRAIT_RELIGION_UNIT_DROWN', 'KIND_TRAIT'),
('SLTH_TRAIT_RELIGION_UNIT_HEMAH', 'KIND_TRAIT'),
('SLTH_TRAIT_RELIGION_UNIT_HIGH_PRIEST_OF_THE_OVERLORDS', 'KIND_TRAIT'),
('SLTH_TRAIT_RELIGION_UNIT_LUNATIC', 'KIND_TRAIT'),
('SLTH_TRAIT_RELIGION_UNIT_PRIEST_OF_THE_OVERLORDS', 'KIND_TRAIT'),
('SLTH_TRAIT_RELIGION_UNIT_SAVEROUS', 'KIND_TRAIT'),
('SLTH_TRAIT_RELIGION_UNIT_CRUSADER', 'KIND_TRAIT'),
('SLTH_TRAIT_RELIGION_UNIT_DISCIPLE_THE_ORDER', 'KIND_TRAIT'),
('SLTH_TRAIT_RELIGION_UNIT_HIGH_PRIEST_OF_THE_ORDER', 'KIND_TRAIT'),
('SLTH_TRAIT_RELIGION_UNIT_PRIEST_OF_THE_ORDER', 'KIND_TRAIT'),
('SLTH_TRAIT_RELIGION_UNIT_VALIN', 'KIND_TRAIT');
