INSERT INTO UnitCommands (CommandType, Description, Icon, VisibleInUI, HoldCycling, CategoryInUI) VALUES
('UNITCOMMAND_MY_CUSTOM', 'LOC_MY_CUST_DESCRIPTION', 'ICON_UNITCOMMAND_TREAT_WITH_CLAN_DISPERSE', 1, 1, 'BUILD');

INSERT INTO Types(Type, Kind) VALUES
('UNITCOMMAND_MY_CUSTOM', 'KIND_UNITCOMMAND');

