-- modifier on every city to reduce science by a third
-- triple everything that grants science normally
-- grant every thing that grants commerce science
-- main problem. cant do order of operations multiplication.
-- if i had 100% increased science ona  city with 20 science, and have this -66 % science,
-- i would want it to go town to 6 science then go back up to twelve
-- instead it would go -66 + 100 = +34, so 20* 1.34 = 26, so even more. hmmmm



-- INSTEAD LEts do Faith as Commerce.
-- needs to be attach so we can adjust it with capital plot property

INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
('SLTH_COMMERCE_INTO_SCIENCE', 'YieldType', 'YIELD_SCIENCE'),
('SLTH_COMMERCE_INTO_SCIENCE', 'Amount', '35');

INSERT INTO Modifiers(ModifierId, ModifierType) VALUES
('SLTH_COMMERCE_INTO_SCIENCE', 'MODIFIER_PLAYER_CITIES_ADJUST_YIELD_MODIFIER_FROM_FAITH');

INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
('SLTH_COMMERCE_INTO_CULTURE', 'YieldType', 'YIELD_CULTURE'),
('SLTH_COMMERCE_INTO_CULTURE', 'Amount', '35');

INSERT INTO Modifiers(ModifierId, ModifierType) VALUES
('SLTH_COMMERCE_INTO_CULTURE', 'MODIFIER_PLAYER_CITIES_ADJUST_YIELD_MODIFIER_FROM_FAITH');

INSERT INTO ModifierArguments(ModifierId, Name, "Value") VALUES
('SLTH_COMMERCE_INTO_GOLD', 'YieldType', 'YIELD_GOLD'),
('SLTH_COMMERCE_INTO_GOLD', 'Amount', '35');

INSERT INTO Modifiers(ModifierId, ModifierType) VALUES
('SLTH_COMMERCE_INTO_GOLD', 'MODIFIER_PLAYER_CITIES_ADJUST_YIELD_MODIFIER_FROM_FAITH');

INSERT INTO TraitModifiers(TraitType, ModifierId) VALUES
('TRAIT_LEADER_MAJOR_CIV', 'SLTH_COMMERCE_INTO_SCIENCE_ATTACH'),
('TRAIT_LEADER_MAJOR_CIV', 'SLTH_COMMERCE_INTO_CULTURE_ATTACH'),
('TRAIT_LEADER_MAJOR_CIV', 'SLTH_COMMERCE_INTO_GOLD_ATTACH');

-- SLIDER EDITION!
-- First default fallback if custom sliders fail
INSERT INTO Modifiers(ModifierId,     ModifierType,                              SubjectRequirementSetId) VALUES
('SLTH_COMMERCE_INTO_SCIENCE_ATTACH', 'MODIFIER_ATTACH_MODIFIER_PLAYER_CAPITAL', 'NO_CUSTOM_SLIDERS_PLOT_PROP_REQS'),
('SLTH_COMMERCE_INTO_CULTURE_ATTACH', 'MODIFIER_ATTACH_MODIFIER_PLAYER_CAPITAL', 'NO_CUSTOM_SLIDERS_PLOT_PROP_REQS'),
('SLTH_COMMERCE_INTO_GOLD_ATTACH',    'MODIFIER_ATTACH_MODIFIER_PLAYER_CAPITAL', 'NO_CUSTOM_SLIDERS_PLOT_PROP_REQS');

INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
('SLTH_COMMERCE_INTO_SCIENCE_ATTACH', 'ModifierId', 'SLTH_COMMERCE_INTO_SCIENCE'),
('SLTH_COMMERCE_INTO_CULTURE_ATTACH', 'ModifierId', 'SLTH_COMMERCE_INTO_CULTURE'),
('SLTH_COMMERCE_INTO_GOLD_ATTACH',    'ModifierId', 'SLTH_COMMERCE_INTO_GOLD');

INSERT INTO Requirements(RequirementId, RequirementType) VALUES
('REQUIREMENT_NO_CUSTOM_SLIDERS_PLOTPROP', 'REQUIREMENT_PLOT_PROPERTY_MATCHES');
INSERT INTO RequirementArguments(RequirementId, Name, Value) VALUES
('REQUIREMENT_NO_CUSTOM_SLIDERS_PLOTPROP', 'PropertyName','CustomSlidersOff'),
('REQUIREMENT_NO_CUSTOM_SLIDERS_PLOTPROP', 'PropertyMinimum','1');
INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('NO_CUSTOM_SLIDERS_PLOT_PROP_REQS', 'REQUIREMENT_NO_CUSTOM_SLIDERS_PLOTPROP');
INSERT INTO RequirementSets(RequirementSetId, RequirementSetType) VALUES
('NO_CUSTOM_SLIDERS_PLOT_PROP_REQS', 'REQUIREMENTSET_TEST_ALL');

-- Proper modifiers for each slider increment
INSERT INTO TraitModifiers(TraitType, ModifierId) VALUES
('TRAIT_LEADER_MAJOR_CIV', 'SLTH_COMMERCE_INTO_SCIENCE_10_ATTACH'),
('TRAIT_LEADER_MAJOR_CIV', 'SLTH_COMMERCE_INTO_SCIENCE_20_ATTACH'),
('TRAIT_LEADER_MAJOR_CIV', 'SLTH_COMMERCE_INTO_SCIENCE_30_ATTACH'),
('TRAIT_LEADER_MAJOR_CIV', 'SLTH_COMMERCE_INTO_SCIENCE_40_ATTACH'),
('TRAIT_LEADER_MAJOR_CIV', 'SLTH_COMMERCE_INTO_SCIENCE_50_ATTACH'),
('TRAIT_LEADER_MAJOR_CIV', 'SLTH_COMMERCE_INTO_SCIENCE_60_ATTACH'),
('TRAIT_LEADER_MAJOR_CIV', 'SLTH_COMMERCE_INTO_SCIENCE_70_ATTACH'),
('TRAIT_LEADER_MAJOR_CIV', 'SLTH_COMMERCE_INTO_SCIENCE_80_ATTACH'),
('TRAIT_LEADER_MAJOR_CIV', 'SLTH_COMMERCE_INTO_SCIENCE_90_ATTACH'),
('TRAIT_LEADER_MAJOR_CIV', 'SLTH_COMMERCE_INTO_SCIENCE_100_ATTACH');


INSERT INTO Modifiers(ModifierId,     ModifierType,                              SubjectRequirementSetId) VALUES
('SLTH_COMMERCE_INTO_SCIENCE_10_ATTACH', 'MODIFIER_ATTACH_MODIFIER_PLAYER_CAPITAL', '10_SCIENCE_PLOT_PROP_REQS'),
('SLTH_COMMERCE_INTO_SCIENCE_20_ATTACH', 'MODIFIER_ATTACH_MODIFIER_PLAYER_CAPITAL', '20_SCIENCE_PLOT_PROP_REQS'),
('SLTH_COMMERCE_INTO_SCIENCE_30_ATTACH', 'MODIFIER_ATTACH_MODIFIER_PLAYER_CAPITAL', '30_SCIENCE_PLOT_PROP_REQS'),
('SLTH_COMMERCE_INTO_SCIENCE_40_ATTACH', 'MODIFIER_ATTACH_MODIFIER_PLAYER_CAPITAL', '40_SCIENCE_PLOT_PROP_REQS'),
('SLTH_COMMERCE_INTO_SCIENCE_50_ATTACH', 'MODIFIER_ATTACH_MODIFIER_PLAYER_CAPITAL', '50_SCIENCE_PLOT_PROP_REQS'),
('SLTH_COMMERCE_INTO_SCIENCE_60_ATTACH', 'MODIFIER_ATTACH_MODIFIER_PLAYER_CAPITAL', '60_SCIENCE_PLOT_PROP_REQS'),
('SLTH_COMMERCE_INTO_SCIENCE_70_ATTACH', 'MODIFIER_ATTACH_MODIFIER_PLAYER_CAPITAL', '70_SCIENCE_PLOT_PROP_REQS'),
('SLTH_COMMERCE_INTO_SCIENCE_80_ATTACH', 'MODIFIER_ATTACH_MODIFIER_PLAYER_CAPITAL', '80_SCIENCE_PLOT_PROP_REQS'),
('SLTH_COMMERCE_INTO_SCIENCE_90_ATTACH', 'MODIFIER_ATTACH_MODIFIER_PLAYER_CAPITAL', '90_SCIENCE_PLOT_PROP_REQS'),
('SLTH_COMMERCE_INTO_SCIENCE_100_ATTACH','MODIFIER_ATTACH_MODIFIER_PLAYER_CAPITAL', '100_SCIENCE_PLOT_PROP_REQS');

INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
('SLTH_COMMERCE_INTO_SCIENCE_10_ATTACH', 'ModifierId', 'SLTH_COMMERCE_INTO_SCIENCE_10'),
('SLTH_COMMERCE_INTO_SCIENCE_20_ATTACH', 'ModifierId', 'SLTH_COMMERCE_INTO_SCIENCE_20'),
('SLTH_COMMERCE_INTO_SCIENCE_30_ATTACH', 'ModifierId', 'SLTH_COMMERCE_INTO_SCIENCE_30'),
('SLTH_COMMERCE_INTO_SCIENCE_40_ATTACH', 'ModifierId', 'SLTH_COMMERCE_INTO_SCIENCE_40'),
('SLTH_COMMERCE_INTO_SCIENCE_50_ATTACH', 'ModifierId', 'SLTH_COMMERCE_INTO_SCIENCE_50'),
('SLTH_COMMERCE_INTO_SCIENCE_60_ATTACH', 'ModifierId', 'SLTH_COMMERCE_INTO_SCIENCE_60'),
('SLTH_COMMERCE_INTO_SCIENCE_70_ATTACH', 'ModifierId', 'SLTH_COMMERCE_INTO_SCIENCE_70'),
('SLTH_COMMERCE_INTO_SCIENCE_80_ATTACH', 'ModifierId', 'SLTH_COMMERCE_INTO_SCIENCE_80'),
('SLTH_COMMERCE_INTO_SCIENCE_90_ATTACH', 'ModifierId', 'SLTH_COMMERCE_INTO_SCIENCE_90'),
('SLTH_COMMERCE_INTO_SCIENCE_100_ATTACH','ModifierId', 'SLTH_COMMERCE_INTO_SCIENCE_100');

INSERT INTO Modifiers(ModifierId, ModifierType) VALUES
('SLTH_COMMERCE_INTO_SCIENCE_10', 'MODIFIER_PLAYER_CITIES_ADJUST_YIELD_MODIFIER_FROM_FAITH'),
('SLTH_COMMERCE_INTO_SCIENCE_20', 'MODIFIER_PLAYER_CITIES_ADJUST_YIELD_MODIFIER_FROM_FAITH'),
('SLTH_COMMERCE_INTO_SCIENCE_30', 'MODIFIER_PLAYER_CITIES_ADJUST_YIELD_MODIFIER_FROM_FAITH'),
('SLTH_COMMERCE_INTO_SCIENCE_40', 'MODIFIER_PLAYER_CITIES_ADJUST_YIELD_MODIFIER_FROM_FAITH'),
('SLTH_COMMERCE_INTO_SCIENCE_50', 'MODIFIER_PLAYER_CITIES_ADJUST_YIELD_MODIFIER_FROM_FAITH'),
('SLTH_COMMERCE_INTO_SCIENCE_60', 'MODIFIER_PLAYER_CITIES_ADJUST_YIELD_MODIFIER_FROM_FAITH'),
('SLTH_COMMERCE_INTO_SCIENCE_70', 'MODIFIER_PLAYER_CITIES_ADJUST_YIELD_MODIFIER_FROM_FAITH'),
('SLTH_COMMERCE_INTO_SCIENCE_80', 'MODIFIER_PLAYER_CITIES_ADJUST_YIELD_MODIFIER_FROM_FAITH'),
('SLTH_COMMERCE_INTO_SCIENCE_90', 'MODIFIER_PLAYER_CITIES_ADJUST_YIELD_MODIFIER_FROM_FAITH'),
('SLTH_COMMERCE_INTO_SCIENCE_100', 'MODIFIER_PLAYER_CITIES_ADJUST_YIELD_MODIFIER_FROM_FAITH');

INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
('SLTH_COMMERCE_INTO_SCIENCE_10', 'YieldType', 'YIELD_SCIENCE'),
('SLTH_COMMERCE_INTO_SCIENCE_20', 'YieldType', 'YIELD_SCIENCE'),
('SLTH_COMMERCE_INTO_SCIENCE_30', 'YieldType', 'YIELD_SCIENCE'),
('SLTH_COMMERCE_INTO_SCIENCE_40', 'YieldType', 'YIELD_SCIENCE'),
('SLTH_COMMERCE_INTO_SCIENCE_50', 'YieldType', 'YIELD_SCIENCE'),
('SLTH_COMMERCE_INTO_SCIENCE_60', 'YieldType', 'YIELD_SCIENCE'),
('SLTH_COMMERCE_INTO_SCIENCE_70', 'YieldType', 'YIELD_SCIENCE'),
('SLTH_COMMERCE_INTO_SCIENCE_80', 'YieldType', 'YIELD_SCIENCE'),
('SLTH_COMMERCE_INTO_SCIENCE_90', 'YieldType', 'YIELD_SCIENCE'),
('SLTH_COMMERCE_INTO_SCIENCE_100','YieldType', 'YIELD_SCIENCE'),
('SLTH_COMMERCE_INTO_SCIENCE_10', 'Amount', '10'),
('SLTH_COMMERCE_INTO_SCIENCE_20', 'Amount', '10'),
('SLTH_COMMERCE_INTO_SCIENCE_30', 'Amount', '10'),
('SLTH_COMMERCE_INTO_SCIENCE_40', 'Amount', '10'),
('SLTH_COMMERCE_INTO_SCIENCE_50', 'Amount', '10'),
('SLTH_COMMERCE_INTO_SCIENCE_60', 'Amount', '10'),
('SLTH_COMMERCE_INTO_SCIENCE_70', 'Amount', '10'),
('SLTH_COMMERCE_INTO_SCIENCE_80', 'Amount', '10'),
('SLTH_COMMERCE_INTO_SCIENCE_90', 'Amount', '10'),
('SLTH_COMMERCE_INTO_SCIENCE_100','Amount', '10');

INSERT INTO Requirements(RequirementId, RequirementType) VALUES
('REQUIREMENT_COMM_INTO_SCIENCE_10', 'REQUIREMENT_PLOT_PROPERTY_MATCHES'),
('REQUIREMENT_COMM_INTO_SCIENCE_20', 'REQUIREMENT_PLOT_PROPERTY_MATCHES'),
('REQUIREMENT_COMM_INTO_SCIENCE_30', 'REQUIREMENT_PLOT_PROPERTY_MATCHES'),
('REQUIREMENT_COMM_INTO_SCIENCE_40', 'REQUIREMENT_PLOT_PROPERTY_MATCHES'),
('REQUIREMENT_COMM_INTO_SCIENCE_50', 'REQUIREMENT_PLOT_PROPERTY_MATCHES'),
('REQUIREMENT_COMM_INTO_SCIENCE_60', 'REQUIREMENT_PLOT_PROPERTY_MATCHES'),
('REQUIREMENT_COMM_INTO_SCIENCE_70', 'REQUIREMENT_PLOT_PROPERTY_MATCHES'),
('REQUIREMENT_COMM_INTO_SCIENCE_80', 'REQUIREMENT_PLOT_PROPERTY_MATCHES'),
('REQUIREMENT_COMM_INTO_SCIENCE_90', 'REQUIREMENT_PLOT_PROPERTY_MATCHES'),
('REQUIREMENT_COMM_INTO_SCIENCE_100', 'REQUIREMENT_PLOT_PROPERTY_MATCHES');
INSERT INTO RequirementArguments(RequirementId, Name, Value) VALUES
('REQUIREMENT_COMM_INTO_SCIENCE_10', 'PropertyName','CommIntoScience'),
('REQUIREMENT_COMM_INTO_SCIENCE_10', 'PropertyMinimum','1'),
('REQUIREMENT_COMM_INTO_SCIENCE_20', 'PropertyName','CommIntoScience'),
('REQUIREMENT_COMM_INTO_SCIENCE_20', 'PropertyMinimum','2'),
('REQUIREMENT_COMM_INTO_SCIENCE_30', 'PropertyName','CommIntoScience'),
('REQUIREMENT_COMM_INTO_SCIENCE_30', 'PropertyMinimum','3'),
('REQUIREMENT_COMM_INTO_SCIENCE_40', 'PropertyName','CommIntoScience'),
('REQUIREMENT_COMM_INTO_SCIENCE_40', 'PropertyMinimum','4'),
('REQUIREMENT_COMM_INTO_SCIENCE_50', 'PropertyName','CommIntoScience'),
('REQUIREMENT_COMM_INTO_SCIENCE_50', 'PropertyMinimum','5'),
('REQUIREMENT_COMM_INTO_SCIENCE_60', 'PropertyName','CommIntoScience'),
('REQUIREMENT_COMM_INTO_SCIENCE_60', 'PropertyMinimum','6'),
('REQUIREMENT_COMM_INTO_SCIENCE_70', 'PropertyName','CommIntoScience'),
('REQUIREMENT_COMM_INTO_SCIENCE_70', 'PropertyMinimum','7'),
('REQUIREMENT_COMM_INTO_SCIENCE_80', 'PropertyName','CommIntoScience'),
('REQUIREMENT_COMM_INTO_SCIENCE_80', 'PropertyMinimum','8'),
('REQUIREMENT_COMM_INTO_SCIENCE_90', 'PropertyName','CommIntoScience'),
('REQUIREMENT_COMM_INTO_SCIENCE_90', 'PropertyMinimum','9'),
('REQUIREMENT_COMM_INTO_SCIENCE_100', 'PropertyName','CommIntoScience'),
('REQUIREMENT_COMM_INTO_SCIENCE_100', 'PropertyMinimum','10');

INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('10_SCIENCE_PLOT_PROP_REQS', 'REQUIREMENT_COMM_INTO_SCIENCE_10'),
('20_SCIENCE_PLOT_PROP_REQS', 'REQUIREMENT_COMM_INTO_SCIENCE_20'),
('30_SCIENCE_PLOT_PROP_REQS', 'REQUIREMENT_COMM_INTO_SCIENCE_30'),
('40_SCIENCE_PLOT_PROP_REQS', 'REQUIREMENT_COMM_INTO_SCIENCE_40'),
('50_SCIENCE_PLOT_PROP_REQS', 'REQUIREMENT_COMM_INTO_SCIENCE_50'),
('60_SCIENCE_PLOT_PROP_REQS', 'REQUIREMENT_COMM_INTO_SCIENCE_60'),
('70_SCIENCE_PLOT_PROP_REQS', 'REQUIREMENT_COMM_INTO_SCIENCE_70'),
('80_SCIENCE_PLOT_PROP_REQS', 'REQUIREMENT_COMM_INTO_SCIENCE_80'),
('90_SCIENCE_PLOT_PROP_REQS', 'REQUIREMENT_COMM_INTO_SCIENCE_90'),
('100_SCIENCE_PLOT_PROP_REQS','REQUIREMENT_COMM_INTO_SCIENCE_100');

INSERT INTO RequirementSets(RequirementSetId, RequirementSetType) VALUES
('10_SCIENCE_PLOT_PROP_REQS', 'REQUIREMENTSET_TEST_ALL'),
('20_SCIENCE_PLOT_PROP_REQS', 'REQUIREMENTSET_TEST_ALL'),
('30_SCIENCE_PLOT_PROP_REQS', 'REQUIREMENTSET_TEST_ALL'),
('40_SCIENCE_PLOT_PROP_REQS', 'REQUIREMENTSET_TEST_ALL'),
('50_SCIENCE_PLOT_PROP_REQS', 'REQUIREMENTSET_TEST_ALL'),
('60_SCIENCE_PLOT_PROP_REQS', 'REQUIREMENTSET_TEST_ALL'),
('70_SCIENCE_PLOT_PROP_REQS', 'REQUIREMENTSET_TEST_ALL'),
('80_SCIENCE_PLOT_PROP_REQS', 'REQUIREMENTSET_TEST_ALL'),
('90_SCIENCE_PLOT_PROP_REQS', 'REQUIREMENTSET_TEST_ALL'),
('100_SCIENCE_PLOT_PROP_REQS','REQUIREMENTSET_TEST_ALL');

-- COMM into gold
INSERT INTO TraitModifiers(TraitType, ModifierId) VALUES
('TRAIT_LEADER_MAJOR_CIV', 'SLTH_COMMERCE_INTO_GOLD_10_ATTACH'),
('TRAIT_LEADER_MAJOR_CIV', 'SLTH_COMMERCE_INTO_GOLD_20_ATTACH'),
('TRAIT_LEADER_MAJOR_CIV', 'SLTH_COMMERCE_INTO_GOLD_30_ATTACH'),
('TRAIT_LEADER_MAJOR_CIV', 'SLTH_COMMERCE_INTO_GOLD_40_ATTACH'),
('TRAIT_LEADER_MAJOR_CIV', 'SLTH_COMMERCE_INTO_GOLD_50_ATTACH'),
('TRAIT_LEADER_MAJOR_CIV', 'SLTH_COMMERCE_INTO_GOLD_60_ATTACH'),
('TRAIT_LEADER_MAJOR_CIV', 'SLTH_COMMERCE_INTO_GOLD_70_ATTACH'),
('TRAIT_LEADER_MAJOR_CIV', 'SLTH_COMMERCE_INTO_GOLD_80_ATTACH'),
('TRAIT_LEADER_MAJOR_CIV', 'SLTH_COMMERCE_INTO_GOLD_90_ATTACH'),
('TRAIT_LEADER_MAJOR_CIV', 'SLTH_COMMERCE_INTO_GOLD_100_ATTACH');

INSERT INTO Modifiers(ModifierId,     ModifierType,                              SubjectRequirementSetId) VALUES
('SLTH_COMMERCE_INTO_GOLD_10_ATTACH', 'MODIFIER_ATTACH_MODIFIER_PLAYER_CAPITAL', '10_GOLD_PLOT_PROP_REQS'),
('SLTH_COMMERCE_INTO_GOLD_20_ATTACH', 'MODIFIER_ATTACH_MODIFIER_PLAYER_CAPITAL', '20_GOLD_PLOT_PROP_REQS'),
('SLTH_COMMERCE_INTO_GOLD_30_ATTACH', 'MODIFIER_ATTACH_MODIFIER_PLAYER_CAPITAL', '30_GOLD_PLOT_PROP_REQS'),
('SLTH_COMMERCE_INTO_GOLD_40_ATTACH', 'MODIFIER_ATTACH_MODIFIER_PLAYER_CAPITAL', '40_GOLD_PLOT_PROP_REQS'),
('SLTH_COMMERCE_INTO_GOLD_50_ATTACH', 'MODIFIER_ATTACH_MODIFIER_PLAYER_CAPITAL', '50_GOLD_PLOT_PROP_REQS'),
('SLTH_COMMERCE_INTO_GOLD_60_ATTACH', 'MODIFIER_ATTACH_MODIFIER_PLAYER_CAPITAL', '60_GOLD_PLOT_PROP_REQS'),
('SLTH_COMMERCE_INTO_GOLD_70_ATTACH', 'MODIFIER_ATTACH_MODIFIER_PLAYER_CAPITAL', '70_GOLD_PLOT_PROP_REQS'),
('SLTH_COMMERCE_INTO_GOLD_80_ATTACH', 'MODIFIER_ATTACH_MODIFIER_PLAYER_CAPITAL', '80_GOLD_PLOT_PROP_REQS'),
('SLTH_COMMERCE_INTO_GOLD_90_ATTACH', 'MODIFIER_ATTACH_MODIFIER_PLAYER_CAPITAL', '90_GOLD_PLOT_PROP_REQS'),
('SLTH_COMMERCE_INTO_GOLD_100_ATTACH','MODIFIER_ATTACH_MODIFIER_PLAYER_CAPITAL', '100_GOLD_PLOT_PROP_REQS');

INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
('SLTH_COMMERCE_INTO_GOLD_10_ATTACH', 'ModifierId', 'SLTH_COMMERCE_INTO_GOLD_10'),
('SLTH_COMMERCE_INTO_GOLD_20_ATTACH', 'ModifierId', 'SLTH_COMMERCE_INTO_GOLD_20'),
('SLTH_COMMERCE_INTO_GOLD_30_ATTACH', 'ModifierId', 'SLTH_COMMERCE_INTO_GOLD_30'),
('SLTH_COMMERCE_INTO_GOLD_40_ATTACH', 'ModifierId', 'SLTH_COMMERCE_INTO_GOLD_40'),
('SLTH_COMMERCE_INTO_GOLD_50_ATTACH', 'ModifierId', 'SLTH_COMMERCE_INTO_GOLD_50'),
('SLTH_COMMERCE_INTO_GOLD_60_ATTACH', 'ModifierId', 'SLTH_COMMERCE_INTO_GOLD_60'),
('SLTH_COMMERCE_INTO_GOLD_70_ATTACH', 'ModifierId', 'SLTH_COMMERCE_INTO_GOLD_70'),
('SLTH_COMMERCE_INTO_GOLD_80_ATTACH', 'ModifierId', 'SLTH_COMMERCE_INTO_GOLD_80'),
('SLTH_COMMERCE_INTO_GOLD_90_ATTACH', 'ModifierId', 'SLTH_COMMERCE_INTO_GOLD_90'),
('SLTH_COMMERCE_INTO_GOLD_100_ATTACH','ModifierId', 'SLTH_COMMERCE_INTO_GOLD_100');

INSERT INTO Modifiers(ModifierId, ModifierType) VALUES
('SLTH_COMMERCE_INTO_GOLD_10', 'MODIFIER_PLAYER_CITIES_ADJUST_YIELD_MODIFIER_FROM_FAITH'),
('SLTH_COMMERCE_INTO_GOLD_20', 'MODIFIER_PLAYER_CITIES_ADJUST_YIELD_MODIFIER_FROM_FAITH'),
('SLTH_COMMERCE_INTO_GOLD_30', 'MODIFIER_PLAYER_CITIES_ADJUST_YIELD_MODIFIER_FROM_FAITH'),
('SLTH_COMMERCE_INTO_GOLD_40', 'MODIFIER_PLAYER_CITIES_ADJUST_YIELD_MODIFIER_FROM_FAITH'),
('SLTH_COMMERCE_INTO_GOLD_50', 'MODIFIER_PLAYER_CITIES_ADJUST_YIELD_MODIFIER_FROM_FAITH'),
('SLTH_COMMERCE_INTO_GOLD_60', 'MODIFIER_PLAYER_CITIES_ADJUST_YIELD_MODIFIER_FROM_FAITH'),
('SLTH_COMMERCE_INTO_GOLD_70', 'MODIFIER_PLAYER_CITIES_ADJUST_YIELD_MODIFIER_FROM_FAITH'),
('SLTH_COMMERCE_INTO_GOLD_80', 'MODIFIER_PLAYER_CITIES_ADJUST_YIELD_MODIFIER_FROM_FAITH'),
('SLTH_COMMERCE_INTO_GOLD_90', 'MODIFIER_PLAYER_CITIES_ADJUST_YIELD_MODIFIER_FROM_FAITH'),
('SLTH_COMMERCE_INTO_GOLD_100', 'MODIFIER_PLAYER_CITIES_ADJUST_YIELD_MODIFIER_FROM_FAITH');

INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
('SLTH_COMMERCE_INTO_GOLD_10', 'YieldType', 'YIELD_GOLD'),
('SLTH_COMMERCE_INTO_GOLD_20', 'YieldType', 'YIELD_GOLD'),
('SLTH_COMMERCE_INTO_GOLD_30', 'YieldType', 'YIELD_GOLD'),
('SLTH_COMMERCE_INTO_GOLD_40', 'YieldType', 'YIELD_GOLD'),
('SLTH_COMMERCE_INTO_GOLD_50', 'YieldType', 'YIELD_GOLD'),
('SLTH_COMMERCE_INTO_GOLD_60', 'YieldType', 'YIELD_GOLD'),
('SLTH_COMMERCE_INTO_GOLD_70', 'YieldType', 'YIELD_GOLD'),
('SLTH_COMMERCE_INTO_GOLD_80', 'YieldType', 'YIELD_GOLD'),
('SLTH_COMMERCE_INTO_GOLD_90', 'YieldType', 'YIELD_GOLD'),
('SLTH_COMMERCE_INTO_GOLD_100','YieldType', 'YIELD_GOLD'),
('SLTH_COMMERCE_INTO_GOLD_10', 'Amount', '10'),
('SLTH_COMMERCE_INTO_GOLD_20', 'Amount', '10'),
('SLTH_COMMERCE_INTO_GOLD_30', 'Amount', '10'),
('SLTH_COMMERCE_INTO_GOLD_40', 'Amount', '10'),
('SLTH_COMMERCE_INTO_GOLD_50', 'Amount', '10'),
('SLTH_COMMERCE_INTO_GOLD_60', 'Amount', '10'),
('SLTH_COMMERCE_INTO_GOLD_70', 'Amount', '10'),
('SLTH_COMMERCE_INTO_GOLD_80', 'Amount', '10'),
('SLTH_COMMERCE_INTO_GOLD_90', 'Amount', '10'),
('SLTH_COMMERCE_INTO_GOLD_100','Amount', '10');

INSERT INTO Requirements(RequirementId, RequirementType) VALUES
('REQUIREMENT_COMM_INTO_GOLD_10', 'REQUIREMENT_PLOT_PROPERTY_MATCHES'),
('REQUIREMENT_COMM_INTO_GOLD_20', 'REQUIREMENT_PLOT_PROPERTY_MATCHES'),
('REQUIREMENT_COMM_INTO_GOLD_30', 'REQUIREMENT_PLOT_PROPERTY_MATCHES'),
('REQUIREMENT_COMM_INTO_GOLD_40', 'REQUIREMENT_PLOT_PROPERTY_MATCHES'),
('REQUIREMENT_COMM_INTO_GOLD_50', 'REQUIREMENT_PLOT_PROPERTY_MATCHES'),
('REQUIREMENT_COMM_INTO_GOLD_60', 'REQUIREMENT_PLOT_PROPERTY_MATCHES'),
('REQUIREMENT_COMM_INTO_GOLD_70', 'REQUIREMENT_PLOT_PROPERTY_MATCHES'),
('REQUIREMENT_COMM_INTO_GOLD_80', 'REQUIREMENT_PLOT_PROPERTY_MATCHES'),
('REQUIREMENT_COMM_INTO_GOLD_90', 'REQUIREMENT_PLOT_PROPERTY_MATCHES'),
('REQUIREMENT_COMM_INTO_GOLD_100', 'REQUIREMENT_PLOT_PROPERTY_MATCHES');
INSERT INTO RequirementArguments(RequirementId, Name, Value) VALUES
('REQUIREMENT_COMM_INTO_GOLD_10', 'PropertyName','CommIntoGold'),
('REQUIREMENT_COMM_INTO_GOLD_10', 'PropertyMinimum','1'),
('REQUIREMENT_COMM_INTO_GOLD_20', 'PropertyName','CommIntoGold'),
('REQUIREMENT_COMM_INTO_GOLD_20', 'PropertyMinimum','2'),
('REQUIREMENT_COMM_INTO_GOLD_30', 'PropertyName','CommIntoGold'),
('REQUIREMENT_COMM_INTO_GOLD_30', 'PropertyMinimum','3'),
('REQUIREMENT_COMM_INTO_GOLD_40', 'PropertyName','CommIntoGold'),
('REQUIREMENT_COMM_INTO_GOLD_40', 'PropertyMinimum','4'),
('REQUIREMENT_COMM_INTO_GOLD_50', 'PropertyName','CommIntoGold'),
('REQUIREMENT_COMM_INTO_GOLD_50', 'PropertyMinimum','5'),
('REQUIREMENT_COMM_INTO_GOLD_60', 'PropertyName','CommIntoGold'),
('REQUIREMENT_COMM_INTO_GOLD_60', 'PropertyMinimum','6'),
('REQUIREMENT_COMM_INTO_GOLD_70', 'PropertyName','CommIntoGold'),
('REQUIREMENT_COMM_INTO_GOLD_70', 'PropertyMinimum','7'),
('REQUIREMENT_COMM_INTO_GOLD_80', 'PropertyName','CommIntoGold'),
('REQUIREMENT_COMM_INTO_GOLD_80', 'PropertyMinimum','8'),
('REQUIREMENT_COMM_INTO_GOLD_90', 'PropertyName','CommIntoGold'),
('REQUIREMENT_COMM_INTO_GOLD_90', 'PropertyMinimum','9'),
('REQUIREMENT_COMM_INTO_GOLD_100', 'PropertyName','CommIntoGold'),
('REQUIREMENT_COMM_INTO_GOLD_100', 'PropertyMinimum','10');

INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('10_GOLD_PLOT_PROP_REQS', 'REQUIREMENT_COMM_INTO_GOLD_10'),
('20_GOLD_PLOT_PROP_REQS', 'REQUIREMENT_COMM_INTO_GOLD_20'),
('30_GOLD_PLOT_PROP_REQS', 'REQUIREMENT_COMM_INTO_GOLD_30'),
('40_GOLD_PLOT_PROP_REQS', 'REQUIREMENT_COMM_INTO_GOLD_40'),
('50_GOLD_PLOT_PROP_REQS', 'REQUIREMENT_COMM_INTO_GOLD_50'),
('60_GOLD_PLOT_PROP_REQS', 'REQUIREMENT_COMM_INTO_GOLD_60'),
('70_GOLD_PLOT_PROP_REQS', 'REQUIREMENT_COMM_INTO_GOLD_70'),
('80_GOLD_PLOT_PROP_REQS', 'REQUIREMENT_COMM_INTO_GOLD_80'),
('90_GOLD_PLOT_PROP_REQS', 'REQUIREMENT_COMM_INTO_GOLD_90'),
('100_GOLD_PLOT_PROP_REQS','REQUIREMENT_COMM_INTO_GOLD_100');

INSERT INTO RequirementSets(RequirementSetId, RequirementSetType) VALUES
('10_GOLD_PLOT_PROP_REQS', 'REQUIREMENTSET_TEST_ALL'),
('20_GOLD_PLOT_PROP_REQS', 'REQUIREMENTSET_TEST_ALL'),
('30_GOLD_PLOT_PROP_REQS', 'REQUIREMENTSET_TEST_ALL'),
('40_GOLD_PLOT_PROP_REQS', 'REQUIREMENTSET_TEST_ALL'),
('50_GOLD_PLOT_PROP_REQS', 'REQUIREMENTSET_TEST_ALL'),
('60_GOLD_PLOT_PROP_REQS', 'REQUIREMENTSET_TEST_ALL'),
('70_GOLD_PLOT_PROP_REQS', 'REQUIREMENTSET_TEST_ALL'),
('80_GOLD_PLOT_PROP_REQS', 'REQUIREMENTSET_TEST_ALL'),
('90_GOLD_PLOT_PROP_REQS', 'REQUIREMENTSET_TEST_ALL'),
('100_GOLD_PLOT_PROP_REQS','REQUIREMENTSET_TEST_ALL');


-- Culture. Currently unused, as unlocks later, and also makes maths a lot harder (for me, not computer)
/*


INSERT INTO TraitModifiers(TraitType, ModifierId) VALUES
('TRAIT_LEADER_MAJOR_CIV', 'SLTH_COMMERCE_INTO_CULTURE_10_ATTACH'),
('TRAIT_LEADER_MAJOR_CIV', 'SLTH_COMMERCE_INTO_CULTURE_20_ATTACH'),
('TRAIT_LEADER_MAJOR_CIV', 'SLTH_COMMERCE_INTO_CULTURE_30_ATTACH'),
('TRAIT_LEADER_MAJOR_CIV', 'SLTH_COMMERCE_INTO_CULTURE_40_ATTACH'),
('TRAIT_LEADER_MAJOR_CIV', 'SLTH_COMMERCE_INTO_CULTURE_50_ATTACH'),
('TRAIT_LEADER_MAJOR_CIV', 'SLTH_COMMERCE_INTO_CULTURE_60_ATTACH'),
('TRAIT_LEADER_MAJOR_CIV', 'SLTH_COMMERCE_INTO_CULTURE_70_ATTACH'),
('TRAIT_LEADER_MAJOR_CIV', 'SLTH_COMMERCE_INTO_CULTURE_80_ATTACH'),
('TRAIT_LEADER_MAJOR_CIV', 'SLTH_COMMERCE_INTO_CULTURE_90_ATTACH'),
('TRAIT_LEADER_MAJOR_CIV', 'SLTH_COMMERCE_INTO_CULTURE_100_ATTACH');

INSERT INTO Modifiers(ModifierId,     ModifierType,                              SubjectRequirementSetId) VALUES
('SLTH_COMMERCE_INTO_CULTURE_10_ATTACH', 'MODIFIER_ATTACH_MODIFIER_PLAYER_CAPITAL', '10_CULTURE_PLOT_PROP_REQS'),
('SLTH_COMMERCE_INTO_CULTURE_20_ATTACH', 'MODIFIER_ATTACH_MODIFIER_PLAYER_CAPITAL', '20_CULTURE_PLOT_PROP_REQS'),
('SLTH_COMMERCE_INTO_CULTURE_30_ATTACH', 'MODIFIER_ATTACH_MODIFIER_PLAYER_CAPITAL', '30_CULTURE_PLOT_PROP_REQS'),
('SLTH_COMMERCE_INTO_CULTURE_40_ATTACH', 'MODIFIER_ATTACH_MODIFIER_PLAYER_CAPITAL', '40_CULTURE_PLOT_PROP_REQS'),
('SLTH_COMMERCE_INTO_CULTURE_50_ATTACH', 'MODIFIER_ATTACH_MODIFIER_PLAYER_CAPITAL', '50_CULTURE_PLOT_PROP_REQS'),
('SLTH_COMMERCE_INTO_CULTURE_60_ATTACH', 'MODIFIER_ATTACH_MODIFIER_PLAYER_CAPITAL', '60_CULTURE_PLOT_PROP_REQS'),
('SLTH_COMMERCE_INTO_CULTURE_70_ATTACH', 'MODIFIER_ATTACH_MODIFIER_PLAYER_CAPITAL', '70_CULTURE_PLOT_PROP_REQS'),
('SLTH_COMMERCE_INTO_CULTURE_80_ATTACH', 'MODIFIER_ATTACH_MODIFIER_PLAYER_CAPITAL', '80_CULTURE_PLOT_PROP_REQS'),
('SLTH_COMMERCE_INTO_CULTURE_90_ATTACH', 'MODIFIER_ATTACH_MODIFIER_PLAYER_CAPITAL', '90_CULTURE_PLOT_PROP_REQS'),
('SLTH_COMMERCE_INTO_CULTURE_100_ATTACH','MODIFIER_ATTACH_MODIFIER_PLAYER_CAPITAL', '100_CULTURE_PLOT_PROP_REQS');

INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
('SLTH_COMMERCE_INTO_CULTURE_10_ATTACH', 'ModifierId', 'SLTH_COMMERCE_INTO_CULTURE_10'),
('SLTH_COMMERCE_INTO_CULTURE_20_ATTACH', 'ModifierId', 'SLTH_COMMERCE_INTO_CULTURE_20'),
('SLTH_COMMERCE_INTO_CULTURE_30_ATTACH', 'ModifierId', 'SLTH_COMMERCE_INTO_CULTURE_30'),
('SLTH_COMMERCE_INTO_CULTURE_40_ATTACH', 'ModifierId', 'SLTH_COMMERCE_INTO_CULTURE_40'),
('SLTH_COMMERCE_INTO_CULTURE_50_ATTACH', 'ModifierId', 'SLTH_COMMERCE_INTO_CULTURE_50'),
('SLTH_COMMERCE_INTO_CULTURE_60_ATTACH', 'ModifierId', 'SLTH_COMMERCE_INTO_CULTURE_60'),
('SLTH_COMMERCE_INTO_CULTURE_70_ATTACH', 'ModifierId', 'SLTH_COMMERCE_INTO_CULTURE_70'),
('SLTH_COMMERCE_INTO_CULTURE_80_ATTACH', 'ModifierId', 'SLTH_COMMERCE_INTO_CULTURE_80'),
('SLTH_COMMERCE_INTO_CULTURE_90_ATTACH', 'ModifierId', 'SLTH_COMMERCE_INTO_CULTURE_90'),
('SLTH_COMMERCE_INTO_CULTURE_100_ATTACH','ModifierId', 'SLTH_COMMERCE_INTO_CULTURE_100');

INSERT INTO Modifiers(ModifierId, ModifierType) VALUES
('SLTH_COMMERCE_INTO_CULTURE_10', 'MODIFIER_PLAYER_CITIES_ADJUST_YIELD_MODIFIER_FROM_FAITH'),
('SLTH_COMMERCE_INTO_CULTURE_20', 'MODIFIER_PLAYER_CITIES_ADJUST_YIELD_MODIFIER_FROM_FAITH'),
('SLTH_COMMERCE_INTO_CULTURE_30', 'MODIFIER_PLAYER_CITIES_ADJUST_YIELD_MODIFIER_FROM_FAITH'),
('SLTH_COMMERCE_INTO_CULTURE_40', 'MODIFIER_PLAYER_CITIES_ADJUST_YIELD_MODIFIER_FROM_FAITH'),
('SLTH_COMMERCE_INTO_CULTURE_50', 'MODIFIER_PLAYER_CITIES_ADJUST_YIELD_MODIFIER_FROM_FAITH'),
('SLTH_COMMERCE_INTO_CULTURE_60', 'MODIFIER_PLAYER_CITIES_ADJUST_YIELD_MODIFIER_FROM_FAITH'),
('SLTH_COMMERCE_INTO_CULTURE_70', 'MODIFIER_PLAYER_CITIES_ADJUST_YIELD_MODIFIER_FROM_FAITH'),
('SLTH_COMMERCE_INTO_CULTURE_80', 'MODIFIER_PLAYER_CITIES_ADJUST_YIELD_MODIFIER_FROM_FAITH'),
('SLTH_COMMERCE_INTO_CULTURE_90', 'MODIFIER_PLAYER_CITIES_ADJUST_YIELD_MODIFIER_FROM_FAITH'),
('SLTH_COMMERCE_INTO_CULTURE_100', 'MODIFIER_PLAYER_CITIES_ADJUST_YIELD_MODIFIER_FROM_FAITH');

INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
('SLTH_COMMERCE_INTO_CULTURE_10', 'YieldType', 'YIELD_CULTURE'),
('SLTH_COMMERCE_INTO_CULTURE_20', 'YieldType', 'YIELD_CULTURE'),
('SLTH_COMMERCE_INTO_CULTURE_30', 'YieldType', 'YIELD_CULTURE'),
('SLTH_COMMERCE_INTO_CULTURE_40', 'YieldType', 'YIELD_CULTURE'),
('SLTH_COMMERCE_INTO_CULTURE_50', 'YieldType', 'YIELD_CULTURE'),
('SLTH_COMMERCE_INTO_CULTURE_60', 'YieldType', 'YIELD_CULTURE'),
('SLTH_COMMERCE_INTO_CULTURE_70', 'YieldType', 'YIELD_CULTURE'),
('SLTH_COMMERCE_INTO_CULTURE_80', 'YieldType', 'YIELD_CULTURE'),
('SLTH_COMMERCE_INTO_CULTURE_90', 'YieldType', 'YIELD_CULTURE'),
('SLTH_COMMERCE_INTO_CULTURE_100','YieldType', 'YIELD_CULTURE'),
('SLTH_COMMERCE_INTO_CULTURE_10', 'Amount', '10'),
('SLTH_COMMERCE_INTO_CULTURE_20', 'Amount', '10'),
('SLTH_COMMERCE_INTO_CULTURE_30', 'Amount', '10'),
('SLTH_COMMERCE_INTO_CULTURE_40', 'Amount', '10'),
('SLTH_COMMERCE_INTO_CULTURE_50', 'Amount', '10'),
('SLTH_COMMERCE_INTO_CULTURE_60', 'Amount', '10'),
('SLTH_COMMERCE_INTO_CULTURE_70', 'Amount', '10'),
('SLTH_COMMERCE_INTO_CULTURE_80', 'Amount', '10'),
('SLTH_COMMERCE_INTO_CULTURE_90', 'Amount', '10'),
('SLTH_COMMERCE_INTO_CULTURE_100','Amount', '10');

INSERT INTO Requirements(RequirementId, RequirementType) VALUES
('REQUIREMENT_COMM_INTO_CULTURE_10', 'REQUIREMENT_PLOT_PROPERTY_MATCHES'),
('REQUIREMENT_COMM_INTO_CULTURE_20', 'REQUIREMENT_PLOT_PROPERTY_MATCHES'),
('REQUIREMENT_COMM_INTO_CULTURE_30', 'REQUIREMENT_PLOT_PROPERTY_MATCHES'),
('REQUIREMENT_COMM_INTO_CULTURE_40', 'REQUIREMENT_PLOT_PROPERTY_MATCHES'),
('REQUIREMENT_COMM_INTO_CULTURE_50', 'REQUIREMENT_PLOT_PROPERTY_MATCHES'),
('REQUIREMENT_COMM_INTO_CULTURE_60', 'REQUIREMENT_PLOT_PROPERTY_MATCHES'),
('REQUIREMENT_COMM_INTO_CULTURE_70', 'REQUIREMENT_PLOT_PROPERTY_MATCHES'),
('REQUIREMENT_COMM_INTO_CULTURE_80', 'REQUIREMENT_PLOT_PROPERTY_MATCHES'),
('REQUIREMENT_COMM_INTO_CULTURE_90', 'REQUIREMENT_PLOT_PROPERTY_MATCHES'),
('REQUIREMENT_COMM_INTO_CULTURE_100', 'REQUIREMENT_PLOT_PROPERTY_MATCHES');
INSERT INTO RequirementArguments(RequirementId, Name, Value) VALUES
('REQUIREMENT_COMM_INTO_CULTURE_10', 'PropertyName','CommIntoCulture'),
('REQUIREMENT_COMM_INTO_CULTURE_10', 'PropertyMinimum','1'),
('REQUIREMENT_COMM_INTO_CULTURE_20', 'PropertyName','CommIntoCulture'),
('REQUIREMENT_COMM_INTO_CULTURE_20', 'PropertyMinimum','2'),
('REQUIREMENT_COMM_INTO_CULTURE_30', 'PropertyName','CommIntoCulture'),
('REQUIREMENT_COMM_INTO_CULTURE_30', 'PropertyMinimum','3'),
('REQUIREMENT_COMM_INTO_CULTURE_40', 'PropertyName','CommIntoCulture'),
('REQUIREMENT_COMM_INTO_CULTURE_40', 'PropertyMinimum','4'),
('REQUIREMENT_COMM_INTO_CULTURE_50', 'PropertyName','CommIntoCulture'),
('REQUIREMENT_COMM_INTO_CULTURE_50', 'PropertyMinimum','5'),
('REQUIREMENT_COMM_INTO_CULTURE_60', 'PropertyName','CommIntoCulture'),
('REQUIREMENT_COMM_INTO_CULTURE_60', 'PropertyMinimum','6'),
('REQUIREMENT_COMM_INTO_CULTURE_70', 'PropertyName','CommIntoCulture'),
('REQUIREMENT_COMM_INTO_CULTURE_70', 'PropertyMinimum','7'),
('REQUIREMENT_COMM_INTO_CULTURE_80', 'PropertyName','CommIntoCulture'),
('REQUIREMENT_COMM_INTO_CULTURE_80', 'PropertyMinimum','8'),
('REQUIREMENT_COMM_INTO_CULTURE_90', 'PropertyName','CommIntoCulture'),
('REQUIREMENT_COMM_INTO_CULTURE_90', 'PropertyMinimum','9'),
('REQUIREMENT_COMM_INTO_CULTURE_100', 'PropertyName','CommIntoCulture'),
('REQUIREMENT_COMM_INTO_CULTURE_100', 'PropertyMinimum','10');

INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('10_CULTURE_PLOT_PROP_REQS', 'REQUIREMENT_COMM_INTO_CULTURE_10'),
('20_CULTURE_PLOT_PROP_REQS', 'REQUIREMENT_COMM_INTO_CULTURE_20'),
('30_CULTURE_PLOT_PROP_REQS', 'REQUIREMENT_COMM_INTO_CULTURE_30'),
('40_CULTURE_PLOT_PROP_REQS', 'REQUIREMENT_COMM_INTO_CULTURE_40'),
('50_CULTURE_PLOT_PROP_REQS', 'REQUIREMENT_COMM_INTO_CULTURE_50'),
('60_CULTURE_PLOT_PROP_REQS', 'REQUIREMENT_COMM_INTO_CULTURE_60'),
('70_CULTURE_PLOT_PROP_REQS', 'REQUIREMENT_COMM_INTO_CULTURE_70'),
('80_CULTURE_PLOT_PROP_REQS', 'REQUIREMENT_COMM_INTO_CULTURE_80'),
('90_CULTURE_PLOT_PROP_REQS', 'REQUIREMENT_COMM_INTO_CULTURE_90'),
('100_CULTURE_PLOT_PROP_REQS','REQUIREMENT_COMM_INTO_CULTURE_100');

INSERT INTO RequirementSets(RequirementSetId, RequirementSetType) VALUES
('10_CULTURE_PLOT_PROP_REQS', 'REQUIREMENTSET_TEST_ALL'),
('20_CULTURE_PLOT_PROP_REQS', 'REQUIREMENTSET_TEST_ALL'),
('30_CULTURE_PLOT_PROP_REQS', 'REQUIREMENTSET_TEST_ALL'),
('40_CULTURE_PLOT_PROP_REQS', 'REQUIREMENTSET_TEST_ALL'),
('50_CULTURE_PLOT_PROP_REQS', 'REQUIREMENTSET_TEST_ALL'),
('60_CULTURE_PLOT_PROP_REQS', 'REQUIREMENTSET_TEST_ALL'),
('70_CULTURE_PLOT_PROP_REQS', 'REQUIREMENTSET_TEST_ALL'),
('80_CULTURE_PLOT_PROP_REQS', 'REQUIREMENTSET_TEST_ALL'),
('90_CULTURE_PLOT_PROP_REQS', 'REQUIREMENTSET_TEST_ALL'),
('100_CULTURE_PLOT_PROP_REQS','REQUIREMENTSET_TEST_ALL');
 */

INSERT INTO Modifiers(ModifierId, ModifierType, SubjectRequirementSetId) VALUES
('SLTH_FINANCIAL_COMMERCE_ON_PLOTS_WITH_2_COMMERCE', 'MODIFIER_PLAYER_ADJUST_PLOT_YIELD', 'TILE_HAS_TWO_COMMERCE_REQS');

INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
('SLTH_FINANCIAL_COMMERCE_ON_PLOTS_WITH_2_COMMERCE', 'YieldType', 'YIELD_FAITH'),
('SLTH_FINANCIAL_COMMERCE_ON_PLOTS_WITH_2_COMMERCE', 'Amount', '1');

INSERT INTO Modifiers(ModifierId, ModifierType,  SubjectRequirementSetId) VALUES
('SLTH_GOLDEN_AGE_COMMERCE_ATTACH', 'MODIFIER_ATTACH_MODIFIER_PLAYER_CAPITAL', 'PLOT_PROPERTY_IS_GOLD_AGE_REQS'),
('SLTH_GOLDEN_AGE_PRODUCTION_ATTACH', 'MODIFIER_ATTACH_MODIFIER_PLAYER_CAPITAL', 'PLOT_PROPERTY_IS_GOLD_AGE_REQS'),
('SLTH_GOLDEN_AGE_COMMERCE', 'MODIFIER_PLAYER_ADJUST_PLOT_YIELD', 'TILE_HAS_A_COMMERCE_REQS'),
('SLTH_GOLDEN_AGE_PRODUCTION', 'MODIFIER_PLAYER_ADJUST_PLOT_YIELD', 'TILE_HAS_PRODUCTION_REQS');

INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
('SLTH_GOLDEN_AGE_COMMERCE_ATTACH', 'ModifierId', 'SLTH_GOLDEN_AGE_COMMERCE'),
('SLTH_GOLDEN_AGE_PRODUCTION_ATTACH', 'ModifierId', 'SLTH_GOLDEN_AGE_PRODUCTION'),
('SLTH_GOLDEN_AGE_COMMERCE', 'YieldType', 'YIELD_FAITH'),
('SLTH_GOLDEN_AGE_COMMERCE', 'Amount', '1'),
('SLTH_GOLDEN_AGE_PRODUCTION', 'YieldType', 'YIELD_PRODUCTION'),
('SLTH_GOLDEN_AGE_PRODUCTION', 'Amount', '1');


INSERT INTO TraitModifiers(TraitType, ModifierId) VALUES
('TRAIT_LEADER_MAJOR_CIV', 'SLTH_GOLDEN_AGE_COMMERCE_ATTACH'),
('TRAIT_LEADER_MAJOR_CIV', 'SLTH_GOLDEN_AGE_PRODUCTION_ATTACH'),
('SLTH_TRAIT_FINANCIAL', 'SLTH_FINANCIAL_COMMERCE_ON_PLOTS_WITH_2_COMMERCE');

-- gold bonus for financial
--(
-- does tile have an improvement with faith on it. +1

-- is tile next to river and not forested.

-- does tile have natural faith yield (also stuff like Malakim bonus)

-- )
--OR
-- does a tile have an improvement with 2 faith on it.

-- Golden age
-- impovements
-- +2:  PIRATE_COVE, PIRATE_HARBOR, FEITORIA, HAMLET, VILLAGE, TOWN, ENCLAVE
-- +1   COTTAGE, WINDMILL, WORKSHOP

-- tile
-- TERRAIN_COAST, TERRAIN_DESERT(WITH MALAKIM)

-- feature
-- +2 FEATURE_EYE_OF_THE_SAHARA

-- resource
-- +2 Gold, Pearls
-- +1 Dyes, Fur, Cotton, Diamonds, Incense, Silk, Spices, Olives

-- improved resource
-- +2 Fur, Diamonds, Dyes, Silk, Reagents, Cotton, Razorweed, Marble, Whale, Wine
-- +1 Ivory, Horse, Sheep, Toad, Sugar, Gulagarm
INSERT INTO Requirements(RequirementId, RequirementType) VALUES
('SUBREQSET_IMPROVED_FUR', 'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('SUBREQSET_IMPROVED_GEMS', 'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('SUBREQSET_IMPROVED_DYE', 'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('SUBREQSET_IMPROVED_INCENSE', 'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('SUBREQSET_IMPROVED_SILK', 'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('SUBREQSET_IMPROVED_REAGENTS', 'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('SUBREQSET_IMPROVED_COTTON', 'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('SUBREQSET_IMPROVED_RAZORWEED', 'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('SUBREQSET_IMPROVED_MARBLE', 'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('SUBREQSET_IMPROVED_WHALE', 'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('SUBREQSET_IMPROVED_WINE', 'REQUIREMENT_REQUIREMENTSET_IS_MET'),
-- split 2+:1
('SUBREQSET_IMPROVED_HORSE', 'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('SUBREQSET_IMPROVED_SHEEP', 'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('SUBREQSET_IMPROVED_NIGHTMARE', 'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('SUBREQSET_IMPROVED_TOAD', 'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('SUBREQSET_IMPROVED_SUGAR', 'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('SUBREQSET_IMPROVED_GULAGARM', 'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('SUBREQSET_IMPROVED_IVORY', 'REQUIREMENT_REQUIREMENTSET_IS_MET');

INSERT INTO RequirementArguments(RequirementId, Name, Value) VALUES
('SUBREQSET_IMPROVED_FUR', 'RequirementSetId', 'PLOT_HAS_FUR_YIELD_FAITH_TAG_IMPROVED'),
-- already at 2 ('SUBREQSET_IMPROVED_PEARLS', 'RequirementSetId', 'PLOT_HAS_PEARL_YIELD_FAITH_TAG_IMPROVED'),
('SUBREQSET_IMPROVED_GEMS', 'RequirementSetId', 'PLOT_HAS_GEMS_YIELD_FAITH_TAG_IMPROVED'),
-- already at 2 ('SUBREQSET_IMPROVED_GOLD', 'RequirementSetId', 'PLOT_HAS_GOLD_YIELD_FAITH_TAG_IMPROVED'),
('SUBREQSET_IMPROVED_DYE', 'RequirementSetId', 'PLOT_HAS_DYE_YIELD_FAITH_TAG_IMPROVED'),
('SUBREQSET_IMPROVED_INCENSE', 'RequirementSetId', 'PLOT_HAS_INCENSE_YIELD_FAITH_TAG_IMPROVED'),
('SUBREQSET_IMPROVED_SILK', 'RequirementSetId', 'PLOT_HAS_SILK_YIELD_FAITH_TAG_IMPROVED'),
('SUBREQSET_IMPROVED_REAGENTS', 'RequirementSetId', 'PLOT_HAS_REAGENTS_YIELD_FAITH_TAG_IMPROVED'),
('SUBREQSET_IMPROVED_COTTON', 'RequirementSetId', 'PLOT_HAS_COTTON_YIELD_FAITH_TAG_IMPROVED'),
('SUBREQSET_IMPROVED_RAZORWEED', 'RequirementSetId', 'PLOT_HAS_RAZORWEED_YIELD_FAITH_TAG_IMPROVED'),
('SUBREQSET_IMPROVED_MARBLE', 'RequirementSetId', 'PLOT_HAS_MARBLE_YIELD_FAITH_TAG_IMPROVED'),
('SUBREQSET_IMPROVED_WHALE', 'RequirementSetId', 'PLOT_HAS_WHALE_YIELD_FAITH_TAG_IMPROVED'),
('SUBREQSET_IMPROVED_WINE', 'RequirementSetId', 'PLOT_HAS_WINE_YIELD_FAITH_TAG_IMPROVED'),
-- split 2+:1
('SUBREQSET_IMPROVED_HORSE', 'RequirementSetId', 'PLOT_HAS_HORSE_YIELD_FAITH_TAG_IMPROVED'),
('SUBREQSET_IMPROVED_SHEEP', 'RequirementSetId', 'PLOT_HAS_SHEEP_YIELD_FAITH_TAG_IMPROVED'),
('SUBREQSET_IMPROVED_NIGHTMARE', 'RequirementSetId', 'PLOT_HAS_NIGHTMARE_YIELD_FAITH_TAG_IMPROVED'),
('SUBREQSET_IMPROVED_TOAD', 'RequirementSetId', 'PLOT_HAS_TOAD_YIELD_FAITH_TAG_IMPROVED'),
('SUBREQSET_IMPROVED_SUGAR', 'RequirementSetId', 'PLOT_HAS_SUGAR_YIELD_FAITH_TAG_IMPROVED'),
('SUBREQSET_IMPROVED_GULAGARM', 'RequirementSetId', 'PLOT_HAS_GULAGARM_YIELD_FAITH_TAG_IMPROVED'),
('SUBREQSET_IMPROVED_IVORY', 'RequirementSetId', 'PLOT_HAS_IVORY_YIELD_FAITH_TAG_IMPROVED');


INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('TILE_HAS_TWO_COMMERCE_RESOURCE_REQS', 'SUBREQSET_IMPROVED_FUR'),
('TILE_HAS_TWO_COMMERCE_RESOURCE_REQS', 'SUBREQSET_IMPROVED_GEMS'),
('TILE_HAS_TWO_COMMERCE_RESOURCE_REQS', 'SUBREQSET_IMPROVED_DYE'),
('TILE_HAS_TWO_COMMERCE_RESOURCE_REQS', 'SUBREQSET_IMPROVED_INCENSE'),
('TILE_HAS_TWO_COMMERCE_RESOURCE_REQS', 'SUBREQSET_IMPROVED_REAGENTS'),
('TILE_HAS_TWO_COMMERCE_RESOURCE_REQS', 'SUBREQSET_IMPROVED_COTTON'),
('TILE_HAS_TWO_COMMERCE_RESOURCE_REQS', 'SUBREQSET_IMPROVED_RAZORWEED'),
('TILE_HAS_TWO_COMMERCE_RESOURCE_REQS', 'SUBREQSET_IMPROVED_MARBLE'),
('TILE_HAS_TWO_COMMERCE_RESOURCE_REQS', 'SUBREQSET_IMPROVED_WHALE'),
('TILE_HAS_TWO_COMMERCE_RESOURCE_REQS', 'SUBREQSET_IMPROVED_WINE'),
('TILE_HAS_TWO_COMMERCE_RESOURCE_REQS', 'PLOT_HAS_GOLD_YIELD_PRODUCTION_TAG'),            -- just has the resource
('TILE_HAS_TWO_COMMERCE_RESOURCE_REQS', 'PLOT_HAS_PEARL_YIELD_FAITH_TAG');

INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('TILE_HAS_ONE_COMMERCE_RESOURCE_REQS', 'SUBREQSET_IMPROVED_FUR'),
('TILE_HAS_ONE_COMMERCE_RESOURCE_REQS', 'SUBREQSET_IMPROVED_GEMS'),
('TILE_HAS_ONE_COMMERCE_RESOURCE_REQS', 'SUBREQSET_IMPROVED_DYE'),
('TILE_HAS_ONE_COMMERCE_RESOURCE_REQS', 'SUBREQSET_IMPROVED_INCENSE'),
('TILE_HAS_ONE_COMMERCE_RESOURCE_REQS', 'SUBREQSET_IMPROVED_REAGENTS'),
('TILE_HAS_ONE_COMMERCE_RESOURCE_REQS', 'SUBREQSET_IMPROVED_COTTON'),
('TILE_HAS_ONE_COMMERCE_RESOURCE_REQS', 'SUBREQSET_IMPROVED_RAZORWEED'),
('TILE_HAS_ONE_COMMERCE_RESOURCE_REQS', 'SUBREQSET_IMPROVED_MARBLE'),
('TILE_HAS_ONE_COMMERCE_RESOURCE_REQS', 'SUBREQSET_IMPROVED_WHALE'),
('TILE_HAS_ONE_COMMERCE_RESOURCE_REQS', 'SUBREQSET_IMPROVED_WINE'),
('TILE_HAS_ONE_COMMERCE_RESOURCE_REQS', 'SUBREQSET_IMPROVED_HORSE'),
('TILE_HAS_ONE_COMMERCE_RESOURCE_REQS', 'SUBREQSET_IMPROVED_SHEEP'),
('TILE_HAS_ONE_COMMERCE_RESOURCE_REQS', 'SUBREQSET_IMPROVED_NIGHTMARE'),
('TILE_HAS_ONE_COMMERCE_RESOURCE_REQS', 'SUBREQSET_IMPROVED_TOAD'),
('TILE_HAS_ONE_COMMERCE_RESOURCE_REQS', 'SUBREQSET_IMPROVED_SUGAR'),
('TILE_HAS_ONE_COMMERCE_RESOURCE_REQS', 'SUBREQSET_IMPROVED_GULAGARM'),
('TILE_HAS_ONE_COMMERCE_RESOURCE_REQS', 'SUBREQSET_IMPROVED_IVORY'),
('TILE_HAS_ONE_COMMERCE_RESOURCE_REQS', 'PLOT_HAS_DYE_YIELD_FAITH_TAG'),            -- just has the resource
('TILE_HAS_ONE_COMMERCE_RESOURCE_REQS', 'PLOT_HAS_FUR_YIELD_FAITH_TAG'),
('TILE_HAS_ONE_COMMERCE_RESOURCE_REQS', 'PLOT_HAS_COTTON_YIELD_FAITH_TAG'),
('TILE_HAS_ONE_COMMERCE_RESOURCE_REQS', 'PLOT_HAS_GEMS_YIELD_FAITH_TAG'),
('TILE_HAS_ONE_COMMERCE_RESOURCE_REQS', 'PLOT_HAS_INCENSE_YIELD_FAITH_TAG'),
('TILE_HAS_ONE_COMMERCE_RESOURCE_REQS', 'PLOT_HAS_SILK_YIELD_FAITH_TAG'),
('TILE_HAS_ONE_COMMERCE_RESOURCE_REQS', 'PLOT_HAS_REAGENTS_YIELD_FAITH_TAG'),
('TILE_HAS_ONE_COMMERCE_RESOURCE_REQS', 'PLOT_HAS_RAZORWEED_YIELD_FAITH_TAG');

INSERT INTO RequirementSets(RequirementSetId, RequirementSetType) VALUES
('TILE_HAS_TWO_COMMERCE_RESOURCE_REQS', 'REQUIREMENTSET_TEST_ANY'),
('TILE_HAS_ONE_COMMERCE_RESOURCE_REQS', 'REQUIREMENTSET_TEST_ANY');

-- windmills get 2 faith at machinery
INSERT INTO Requirements(RequirementId, RequirementType) VALUES
('REQUIRES_PLOT_HAS_COTTAGE', 'REQUIREMENT_PLOT_IMPROVEMENT_TYPE_MATCHES'),
('REQUIRES_PLOT_HAS_WORKSHOP', 'REQUIREMENT_PLOT_IMPROVEMENT_TYPE_MATCHES'),
('REQUIRES_PLOT_HAS_WINDMILL', 'REQUIREMENT_PLOT_IMPROVEMENT_TYPE_MATCHES'),
('REQUIRES_PLOT_HAS_HAMLET', 'REQUIREMENT_PLOT_IMPROVEMENT_TYPE_MATCHES'),
('REQUIRES_PLOT_HAS_VILLAGE', 'REQUIREMENT_PLOT_IMPROVEMENT_TYPE_MATCHES'),
('REQUIRES_PLOT_HAS_TOWN', 'REQUIREMENT_PLOT_IMPROVEMENT_TYPE_MATCHES'),
('REQUIRES_PLOT_HAS_ENCLAVE', 'REQUIREMENT_PLOT_IMPROVEMENT_TYPE_MATCHES');

INSERT INTO RequirementArguments(RequirementId, Name, Type, Value) VALUES
('REQUIRES_PLOT_HAS_COTTAGE', 'ImprovementType', 'ARGTYPE_IDENTITY', 'IMPROVEMENT_COTTAGE'),
('REQUIRES_PLOT_HAS_WORKSHOP', 'ImprovementType', 'ARGTYPE_IDENTITY', 'IMPROVEMENT_WORKSHOP'),
('REQUIRES_PLOT_HAS_WINDMILL', 'ImprovementType', 'ARGTYPE_IDENTITY', 'IMPROVEMENT_WINDMILL'),
('REQUIRES_PLOT_HAS_HAMLET', 'ImprovementType', 'ARGTYPE_IDENTITY', 'IMPROVEMENT_HAMLET'),
('REQUIRES_PLOT_HAS_VILLAGE', 'ImprovementType', 'ARGTYPE_IDENTITY', 'IMPROVEMENT_VILLAGE'),
('REQUIRES_PLOT_HAS_TOWN', 'ImprovementType', 'ARGTYPE_IDENTITY', 'IMPROVEMENT_TOWN'),
('REQUIRES_PLOT_HAS_ENCLAVE', 'ImprovementType', 'ARGTYPE_IDENTITY', 'IMPROVEMENT_ENCLAVE');

INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('TILE_HAS_TWO_COMMERCE_IMPROVEMENT_REQS', 'REQUIRES_PLOT_HAS_HAMLET'),
('TILE_HAS_TWO_COMMERCE_IMPROVEMENT_REQS', 'REQUIRES_PLOT_HAS_VILLAGE'),
('TILE_HAS_TWO_COMMERCE_IMPROVEMENT_REQS', 'REQUIRES_PLOT_HAS_TOWN'),
('TILE_HAS_TWO_COMMERCE_IMPROVEMENT_REQS', 'REQUIRES_PLOT_HAS_ENCLAVE');            -- TODO possibly windmill with machinery


INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('TILE_HAS_ONE_COMMERCE_IMPROVEMENT_REQS', 'REQUIRES_PLOT_HAS_COTTAGE'),
('TILE_HAS_ONE_COMMERCE_IMPROVEMENT_REQS', 'REQUIRES_PLOT_HAS_WORKSHOP'),
('TILE_HAS_ONE_COMMERCE_IMPROVEMENT_REQS', 'REQUIRES_PLOT_HAS_WINDMILL');

INSERT INTO RequirementSets(RequirementSetId, RequirementSetType) VALUES
('TILE_HAS_TWO_COMMERCE_IMPROVEMENT_REQS', 'REQUIREMENTSET_TEST_ANY'),
('TILE_HAS_ONE_COMMERCE_IMPROVEMENT_REQS', 'REQUIREMENTSET_TEST_ANY');

INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('TILE_HAS_TWO_COMMERCE_FEATURE_REQS', 'REQUIRES_PLOT_HAS_EYE_SAHARA');                 -- tile has dragon bones

INSERT INTO Requirements(RequirementId, RequirementType) VALUES
('SUBREQSET_IS_DESERT', 'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('SUBREQSET_MALAKIM_DESERT', 'REQUIREMENT_REQUIREMENTSET_IS_MET');

INSERT INTO RequirementArguments(RequirementId, Name, Value) VALUES
('SUBREQSET_IS_DESERT', 'RequirementSetId', 'SLTH_IS_DESERT'),
('SUBREQSET_MALAKIM_DESERT', 'RequirementSetId', 'TILE_IS_DESERT_AND_MALAKIM_REQS');

INSERT INTO Requirements(RequirementId, RequirementType) VALUES
('REQUIRES_PLAYER_IS_MALAKIM', 'REQUIREMENT_PLAYER_HAS_CIVILIZATION_OR_LEADER_TRAIT');
INSERT INTO RequirementArguments(RequirementId, Name,Value) VALUES
('REQUIRES_PLAYER_IS_MALAKIM', 'TraitType', 'SLTH_TRAIT_CIVILIZATION_MALAKIM_COOL');

INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('TILE_HAS_ONE_COMMERCE_TERRAIN_REQS', 'REQUIRES_TERRAIN_COAST'),                 -- tile is coast terrain
('TILE_IS_DESERT_AND_MALAKIM_REQS', 'SUBREQSET_IS_DESERT'),                       -- is desert
('TILE_IS_DESERT_AND_MALAKIM_REQS', 'REQUIRES_PLAYER_IS_MALAKIM'),                -- is malakim
('TILE_HAS_ONE_COMMERCE_TERRAIN_REQS', 'SUBREQSET_MALAKIM_DESERT');               -- tile is desert and player is malakim

INSERT INTO RequirementSets(RequirementSetId, RequirementSetType) VALUES
('TILE_HAS_TWO_COMMERCE_FEATURE_REQS', 'REQUIREMENTSET_TEST_ANY'),                  -- feature only grants two, as dragon bones
('TILE_HAS_ONE_COMMERCE_TERRAIN_REQS', 'REQUIREMENTSET_TEST_ANY'),                  -- terrain only grants one, coast or malakim desert
('TILE_IS_DESERT_AND_MALAKIM_REQS', 'REQUIREMENTSET_TEST_ALL');

-- finally collect subreqsets
INSERT INTO Requirements(RequirementId, RequirementType) VALUES
('SUBREQSET_ADJACENT_RIVER_AND_FORESTED', 'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('SUBREQSET_TILE_HAS_ONE_COMMERCE_RESOURCE', 'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('SUBREQSET_TILE_HAS_TWO_COMMERCE_RESOURCE', 'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('SUBREQSET_TILE_HAS_ONE_COMMERCE_IMPROVEMENT', 'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('SUBREQSET_TILE_HAS_TWO_COMMERCE_IMPROVEMENT', 'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('SUBREQSET_TILE_HAS_TWO_COMMERCE_FEATURE', 'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('SUBREQSET_TILE_HAS_ONE_COMMERCE_TERRAIN', 'REQUIREMENT_REQUIREMENTSET_IS_MET');

INSERT INTO RequirementArguments(RequirementId, Name, Value) VALUES
('SUBREQSET_ADJACENT_RIVER_AND_FORESTED', 'RequirementSetId', 'RIVER_ADJACENT_AND_NOT_FORESTED_REQS'),
('SUBREQSET_TILE_HAS_ONE_COMMERCE_RESOURCE', 'RequirementSetId', 'TILE_HAS_ONE_COMMERCE_RESOURCE_REQS'),
('SUBREQSET_TILE_HAS_TWO_COMMERCE_RESOURCE', 'RequirementSetId', 'TILE_HAS_TWO_COMMERCE_RESOURCE_REQS'),
('SUBREQSET_TILE_HAS_ONE_COMMERCE_IMPROVEMENT', 'RequirementSetId', 'TILE_HAS_ONE_COMMERCE_IMPROVEMENT_REQS'),
('SUBREQSET_TILE_HAS_TWO_COMMERCE_IMPROVEMENT', 'RequirementSetId', 'TILE_HAS_TWO_COMMERCE_IMPROVEMENT_REQS'),
('SUBREQSET_TILE_HAS_TWO_COMMERCE_FEATURE', 'RequirementSetId', 'TILE_HAS_TWO_COMMERCE_FEATURE_REQS'),
('SUBREQSET_TILE_HAS_ONE_COMMERCE_TERRAIN', 'RequirementSetId', 'TILE_HAS_ONE_COMMERCE_TERRAIN_REQS');

INSERT INTO RequirementSets(RequirementSetId, RequirementSetType) VALUES
('TILE_HAS_A_COMMERCE_REQS', 'REQUIREMENTSET_TEST_ANY');

INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('TILE_HAS_A_COMMERCE_REQS', 'SUBREQSET_ADJACENT_RIVER_AND_FORESTED'),
('TILE_HAS_A_COMMERCE_REQS', 'SUBREQSET_TILE_HAS_ONE_COMMERCE_RESOURCE'),
('TILE_HAS_A_COMMERCE_REQS', 'SUBREQSET_TILE_HAS_TWO_COMMERCE_RESOURCE'),
('TILE_HAS_A_COMMERCE_REQS', 'SUBREQSET_TILE_HAS_ONE_COMMERCE_IMPROVEMENT'),
('TILE_HAS_A_COMMERCE_REQS', 'SUBREQSET_TILE_HAS_TWO_COMMERCE_IMPROVEMENT'),
('TILE_HAS_A_COMMERCE_REQS', 'SUBREQSET_TILE_HAS_TWO_COMMERCE_FEATURE'),                             -- only one feature grants commerce, dragon bones, so dont need one check
('TILE_HAS_A_COMMERCE_REQS', 'SUBREQSET_TILE_HAS_ONE_COMMERCE_TERRAIN');


-- TWO COMMERCE REquiremetns
INSERT INTO RequirementSets(RequirementSetId, RequirementSetType) VALUES
('TILE_HAS_TWO_COMMERCE_REQS', 'REQUIREMENTSET_TEST_ANY');

INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('TILE_HAS_TWO_COMMERCE_REQS', 'SUBREQSET_TILE_HAS_TWO_COMMERCE_RESOURCE'),
('TILE_HAS_TWO_COMMERCE_REQS', 'SUBREQSET_TILE_HAS_TWO_COMMERCE_IMPROVEMENT'),
('TILE_HAS_TWO_COMMERCE_REQS', 'SUBREQSET_TILE_HAS_TWO_COMMERCE_FEATURE');

INSERT INTO RequirementSets(RequirementSetId, RequirementSetType) VALUES
('TILE_HAS_ADJACENT_RIVER_AND_RESOURCE_COMMERCE_REQS', 'REQUIREMENTSET_TEST_ALL'),
('TILE_HAS_ADJACENT_RIVER_AND_IMPROVEMENT_COMMERCE_REQS', 'REQUIREMENTSET_TEST_ALL'),
('TILE_HAS_ADJACENT_RIVER_AND_TERRAIN_COMMERCE_REQS', 'REQUIREMENTSET_TEST_ALL'),

('TILE_HAS_RESOURCE_COMMERCE_AND_TERRAIN_COMMERCE_REQS', 'REQUIREMENTSET_TEST_ALL'),
--('TILE_HAS_RESOURCE_COMMERCE_AND_IMPROVEMENT_COMMERCE_REQS', 'REQUIREMENTSET_TEST_ALL'),                -- skip this one? no resource gets an improvement that isnt covered
('TILE_HAS_IMPROVEMENT_COMMERCE_AND_TERRAIN_COMMERCE_REQS', 'REQUIREMENTSET_TEST_ALL');


INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('TILE_HAS_ADJACENT_RIVER_AND_RESOURCE_COMMERCE_REQS', 'SUBREQSET_TILE_HAS_ONE_COMMERCE_RESOURCE'),
('TILE_HAS_ADJACENT_RIVER_AND_RESOURCE_COMMERCE_REQS', 'SUBREQSET_ADJACENT_RIVER_AND_FORESTED'),

('TILE_HAS_ADJACENT_RIVER_AND_IMPROVEMENT_COMMERCE_REQS', 'SUBREQSET_TILE_HAS_ONE_COMMERCE_IMPROVEMENT'),
('TILE_HAS_ADJACENT_RIVER_AND_IMPROVEMENT_COMMERCE_REQS', 'SUBREQSET_ADJACENT_RIVER_AND_FORESTED'),

('TILE_HAS_ADJACENT_RIVER_AND_TERRAIN_COMMERCE_REQS', 'SUBREQSET_TILE_HAS_ONE_COMMERCE_TERRAIN'),
('TILE_HAS_ADJACENT_RIVER_AND_TERRAIN_COMMERCE_REQS', 'SUBREQSET_ADJACENT_RIVER_AND_FORESTED'),

('TILE_HAS_RESOURCE_COMMERCE_AND_TERRAIN_COMMERCE_REQS', 'SUBREQSET_TILE_HAS_ONE_COMMERCE_RESOURCE'),
('TILE_HAS_RESOURCE_COMMERCE_AND_TERRAIN_COMMERCE_REQS', 'SUBREQSET_TILE_HAS_ONE_COMMERCE_TERRAIN'),

-- ('TILE_HAS_RESOURCE_COMMERCE_AND_IMPROVEMENT_COMMERCE_REQS', 'SUBREQSET_TILE_HAS_ONE_COMMERCE_RESOURCE'),
-- ('TILE_HAS_RESOURCE_COMMERCE_AND_IMPROVEMENT_COMMERCE_REQS', 'SUBREQSET_TILE_HAS_ONE_COMMERCE_IMPROVEMENT'),

('TILE_HAS_IMPROVEMENT_COMMERCE_AND_TERRAIN_COMMERCE_REQS', 'SUBREQSET_TILE_HAS_ONE_COMMERCE_IMPROVEMENT'),
('TILE_HAS_IMPROVEMENT_COMMERCE_AND_TERRAIN_COMMERCE_REQS', 'SUBREQSET_TILE_HAS_ONE_COMMERCE_TERRAIN');

INSERT INTO Requirements(RequirementId, RequirementType) VALUES
('SUBREQSET_RIVER_RESOURCE_COMMERCE', 'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('SUBREQSET_RIVER_IMPROVEMENT_COMMERCE', 'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('SUBREQSET_RIVER_TERRAIN_COMMERCE', 'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('SUBREQSET_RESOURCE_TERRAIN_COMMERCE', 'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('SUBREQSET_IMPROVEMENT_TERRAIN_COMMERCE', 'REQUIREMENT_REQUIREMENTSET_IS_MET');

INSERT INTO RequirementArguments(RequirementId, Name, Value) VALUES
('SUBREQSET_RIVER_RESOURCE_COMMERCE', 'RequirementSetId', 'TILE_HAS_ADJACENT_RIVER_AND_RESOURCE_COMMERCE_REQS'),
('SUBREQSET_RIVER_IMPROVEMENT_COMMERCE', 'RequirementSetId', 'TILE_HAS_ADJACENT_RIVER_AND_IMPROVEMENT_COMMERCE_REQS'),
('SUBREQSET_RIVER_TERRAIN_COMMERCE', 'RequirementSetId', 'TILE_HAS_ADJACENT_RIVER_AND_TERRAIN_COMMERCE_REQS'),
('SUBREQSET_RESOURCE_TERRAIN_COMMERCE', 'RequirementSetId', 'TILE_HAS_RESOURCE_COMMERCE_AND_TERRAIN_COMMERCE_REQS'),
('SUBREQSET_IMPROVEMENT_TERRAIN_COMMERCE', 'RequirementSetId', 'TILE_HAS_IMPROVEMENT_COMMERCE_AND_TERRAIN_COMMERCE_REQS');

INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('TILE_HAS_TWO_COMMERCE_REQS', 'SUBREQSET_RIVER_RESOURCE_COMMERCE'),
('TILE_HAS_TWO_COMMERCE_REQS', 'SUBREQSET_RIVER_IMPROVEMENT_COMMERCE'),
('TILE_HAS_TWO_COMMERCE_REQS', 'SUBREQSET_RIVER_TERRAIN_COMMERCE'),
('TILE_HAS_TWO_COMMERCE_REQS', 'SUBREQSET_RESOURCE_TERRAIN_COMMERCE'),
('TILE_HAS_TWO_COMMERCE_REQS', 'SUBREQSET_IMPROVEMENT_TERRAIN_COMMERCE');

-- also doing golden age production bonus here too.
INSERT INTO RequirementSets(RequirementSetId, RequirementSetType) VALUES
('TILE_HAS_PRODUCTION_REQS', 'REQUIREMENTSET_TEST_ANY');

INSERT INTO Requirements(RequirementId, RequirementType) VALUES
('REQUIRES_PLOT_HAS_PIRATE_HARBOR', 'REQUIREMENT_PLOT_IMPROVEMENT_TYPE_MATCHES'),
('REQUIRES_PLOT_HAS_FEITORIA', 'REQUIREMENT_PLOT_IMPROVEMENT_TYPE_MATCHES'),
('REQUIRES_PLOT_HAS_LUMBERMILL', 'REQUIREMENT_PLOT_IMPROVEMENT_TYPE_MATCHES');

INSERT INTO RequirementArguments(RequirementId, Name, Type, Value) VALUES
('REQUIRES_PLOT_HAS_PIRATE_HARBOR', 'ImprovementType', 'ARGTYPE_IDENTITY', 'IMPROVEMENT_PIRATE_HARBOR'),
('REQUIRES_PLOT_HAS_FEITORIA', 'ImprovementType', 'ARGTYPE_IDENTITY', 'IMPROVEMENT_FEITORIA'),
('REQUIRES_PLOT_HAS_LUMBERMILL', 'ImprovementType', 'ARGTYPE_IDENTITY', 'IMPROVEMENT_LUMBER_MILL');

INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('TILE_HAS_PRODUCTION_REQS', 'REQUIRES_PLOT_HAS_PIRATE_HARBOR'),
('TILE_HAS_PRODUCTION_REQS', 'REQUIRES_PLOT_HAS_FEITORIA'),
('TILE_HAS_PRODUCTION_REQS', 'REQUIRES_PLOT_HAS_WORKSHOP'),
('TILE_HAS_PRODUCTION_REQS', 'REQUIRES_PLOT_HAS_MINE'),
('TILE_HAS_PRODUCTION_REQS', 'REQUIRES_PLOT_HAS_LUMBERMILL');
-- IMPROVEMENT_QUARRY       -- with slavery


-- lmao i forgot about woods.
INSERT INTO Requirements(RequirementId, RequirementType) VALUES
('REQUIRES_PLOT_HAS_IKKIL', 'REQUIREMENT_PLOT_FEATURE_TYPE_MATCHES'),
('REQUIRES_PLOT_HAS_REMNANTS_PATRIA', 'REQUIREMENT_PLOT_FEATURE_TYPE_MATCHES');

INSERT INTO RequirementArguments(RequirementId, Name, Value) VALUES
('REQUIRES_PLOT_HAS_IKKIL', 'FeatureType', 'FEATURE_IKKIL'),
('REQUIRES_PLOT_HAS_REMNANTS_PATRIA', 'FeatureType', 'FEATURE_NWON_REMNANTS_OF_PATRIA');

INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('TILE_HAS_PRODUCTION_REQS', 'REQUIRES_PLOT_HAS_IKKIL'),
('TILE_HAS_PRODUCTION_REQS', 'REQUIRES_PLOT_HAS_REMNANTS_PATRIA');

INSERT INTO Requirements(RequirementId, RequirementType) VALUES
('SUBREQSET_IS_HILLY', 'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('SLTH_PLOT_IS_PLAINS', 'REQUIREMENT_PLOT_TERRAIN_TYPE_MATCHES');

INSERT INTO RequirementArguments(RequirementId, Name, Value) VALUES
('SUBREQSET_IS_HILLY', 'RequirementSetId', 'ROUGH_RIDER_HILL_TERRAIN_REQUIREMENTS'),
('SLTH_PLOT_IS_PLAINS', 'TerrainType', 'TERRAIN_PLAINS');

INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('TILE_HAS_PRODUCTION_REQS', 'SUBREQSET_IS_HILLY'),
('TILE_HAS_PRODUCTION_REQS', 'SLTH_PLOT_IS_PLAINS');
-- field of perdition

-- resources
INSERT INTO Requirements(RequirementId, RequirementType) VALUES
('REQUIRES_NITER_IN_PLOT', 'REQUIREMENT_PLOT_RESOURCE_TYPE_MATCHES'),
('REQUIRES_COPPER_IN_PLOT', 'REQUIREMENT_PLOT_RESOURCE_TYPE_MATCHES'),
('REQUIRES_IVORY_IN_PLOT', 'REQUIREMENT_PLOT_RESOURCE_TYPE_MATCHES'),
('REQUIRES_HORSES_IN_PLOT', 'REQUIREMENT_PLOT_RESOURCE_TYPE_MATCHES'),
('REQUIRES_IRON_IN_PLOT', 'REQUIREMENT_PLOT_RESOURCE_TYPE_MATCHES'),
('REQUIRES_MARBLE_IN_PLOT', 'REQUIREMENT_PLOT_RESOURCE_TYPE_MATCHES'),
('REQUIRES_NIGHTMARE_IN_PLOT', 'REQUIREMENT_PLOT_RESOURCE_TYPE_MATCHES'),
('REQUIRES_SILVER_IN_PLOT', 'REQUIREMENT_PLOT_RESOURCE_TYPE_MATCHES');

INSERT INTO RequirementArguments(RequirementId, Name, Value) VALUES
('REQUIRES_NITER_IN_PLOT', 'ResourceType', 'RESOURCE_NITER'),
('REQUIRES_COPPER_IN_PLOT', 'ResourceType', 'RESOURCE_COPPER'),
('REQUIRES_IVORY_IN_PLOT', 'ResourceType', 'RESOURCE_IVORY'),
('REQUIRES_HORSES_IN_PLOT', 'ResourceType', 'RESOURCE_HORSES'),
('REQUIRES_IRON_IN_PLOT', 'ResourceType', 'RESOURCE_IRON'),
('REQUIRES_MARBLE_IN_PLOT', 'ResourceType', 'RESOURCE_MARBLE'),
('REQUIRES_NIGHTMARE_IN_PLOT', 'ResourceType', 'RESOURCE_NIGHTMARE'),
('REQUIRES_SILVER_IN_PLOT', 'ResourceType', 'RESOURCE_SILVER');

INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('TILE_HAS_PRODUCTION_REQS', 'REQUIRES_NITER_IN_PLOT'),
('TILE_HAS_PRODUCTION_REQS', 'REQUIRES_COPPER_IN_PLOT'),
('TILE_HAS_PRODUCTION_REQS', 'REQUIRES_IVORY_IN_PLOT'),
('TILE_HAS_PRODUCTION_REQS', 'REQUIRES_HORSES_IN_PLOT'),
('TILE_HAS_PRODUCTION_REQS', 'REQUIRES_IRON_IN_PLOT'),
('TILE_HAS_PRODUCTION_REQS', 'REQUIRES_MARBLE_IN_PLOT'),
('TILE_HAS_PRODUCTION_REQS', 'REQUIRES_NIGHTMARE_IN_PLOT'),
('TILE_HAS_PRODUCTION_REQS', 'REQUIRES_SILVER_IN_PLOT');

-- tagged production
INSERT INTO Requirements(RequirementId, RequirementType) VALUES
('SUBREQSET_IMPROVED_COW', 'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('SUBREQSET_IMPROVED_SHEUT', 'REQUIREMENT_REQUIREMENTSET_IS_MET');

INSERT INTO RequirementArguments(RequirementId, Name, Value) VALUES
('SUBREQSET_IMPROVED_COW', 'RequirementSetId', 'PLOT_HAS_COW_YIELD_PRODUCTION_TAG'),
('SUBREQSET_IMPROVED_SHEUT', 'RequirementSetId', 'PLOT_HAS_SHEUT_STONE_YIELD_PRODUCTION_TAG');

INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('TILE_HAS_PRODUCTION_REQS', 'SUBREQSET_IMPROVED_GEMS'),
('TILE_HAS_PRODUCTION_REQS', 'SUBREQSET_IMPROVED_COW'),
('TILE_HAS_PRODUCTION_REQS', 'SUBREQSET_IMPROVED_SHEUT'),
('TILE_HAS_PRODUCTION_REQS', 'SUBREQSET_IMPROVED_WHALE');
