-- modifier on every city to reduce science by a third
-- triple everything that grants science normally
-- grant every thing that grants commerce science
-- main problem. cant do order of operations multiplication.
-- if i had 100% increased science ona  city with 20 science, and have this -66 % science,
-- i would want it to go town to 6 science then go back up to twelve
-- instead it would go -66 + 100 = +34, so 20* 1.34 = 26, so even more. hmmmm



-- INSTEAD LEts do Faith as Commerce.

INSERT INTO ModifierArguments(ModifierId, Name, "Value") VALUES
('SLTH_COMMERCE_INTO_SCIENCE', 'YieldType', 'YIELD_SCIENCE'),
('SLTH_COMMERCE_INTO_SCIENCE', 'Amount', '35');

INSERT INTO Modifiers(ModifierId, ModifierType) VALUES
('SLTH_COMMERCE_INTO_SCIENCE', 'MODIFIER_PLAYER_CITIES_ADJUST_YIELD_MODIFIER_FROM_FAITH');

INSERT INTO ModifierArguments(ModifierId, Name, "Value") VALUES
('SLTH_COMMERCE_INTO_CULTURE', 'YieldType', 'YIELD_CULTURE'),
('SLTH_COMMERCE_INTO_CULTURE', 'Amount', '35');

INSERT INTO Modifiers(ModifierId, ModifierType) VALUES
('SLTH_COMMERCE_INTO_CULTURE', 'MODIFIER_PLAYER_CITIES_ADJUST_YIELD_MODIFIER_FROM_FAITH');

INSERT INTO ModifierArguments(ModifierId, Name, "Value") VALUES
('SLTH_COMMERCE_INTO_GOLD', 'YieldType', 'YIELD_GOLD'),
('SLTH_COMMERCE_INTO_GOLD', 'Amount', '35');

INSERT INTO Modifiers(ModifierId, ModifierType) VALUES
('SLTH_COMMERCE_INTO_GOLD', 'MODIFIER_PLAYER_CITIES_ADJUST_YIELD_MODIFIER_FROM_FAITH');

INSERT INTO TraitModifiers(TraitType, ModifierId) VALUES
('TRAIT_LEADER_MAJOR_CIV', 'SLTH_COMMERCE_INTO_SCIENCE'),
('TRAIT_LEADER_MAJOR_CIV', 'SLTH_COMMERCE_INTO_CULTURE'),
('TRAIT_LEADER_MAJOR_CIV', 'SLTH_COMMERCE_INTO_GOLD');

INSERT INTO Modifiers(ModifierId, ModifierType, SubjectRequirementSetId) VALUES
('SLTH_FINANCIAL_COMMERCE_ON_PLOTS_WITH_2_COMMERCE', 'MODIFIER_PLAYER_ADJUST_PLOT_YIELD', 'TILE_HAS_TWO_COMMERCE_REQS');

INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
('SLTH_FINANCIAL_COMMERCE_ON_PLOTS_WITH_2_COMMERCE', 'YieldType', 'YIELD_FAITH'),
('SLTH_FINANCIAL_COMMERCE_ON_PLOTS_WITH_2_COMMERCE', 'Amount', '1');

INSERT INTO Modifiers(ModifierId, ModifierType,  SubjectRequirementSetId) VALUES
('SLTH_GOLDEN_AGE_COMMERCE_ATTACH', 'MODIFIER_ATTACH_MODIFIER_PLAYER_CAPITAL', 'PLOT_PROPERTY_IS_GOLD_AGE_REQS'),
('SLTH_GOLDEN_AGE_PRODUCTION_ATTACH', 'MODIFIER_ATTACH_MODIFIER_PLAYER_CAPITAL', 'PLOT_PROPERTY_IS_GOLD_AGE_REQS'),
('SLTH_GOLDEN_AGE_COMMERCE', 'MODIFIER_PLAYER_ADJUST_PLOT_YIELD', 'TILE_HAS_A_COMMERCE_REQS'),
('SLTH_GOLDEN_AGE_PRODUCTION', 'MODIFIER_PLAYER_ADJUST_PLOT_YIELD', 'TILE_HAS_PRODUCTION_REQS');

INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
('SLTH_GOLDEN_AGE_COMMERCE_ATTACH', 'ModifierId', 'SLTH_GOLDEN_AGE_COMMERCE'),
('SLTH_GOLDEN_AGE_PRODUCTION_ATTACH', 'ModifierId', 'SLTH_GOLDEN_AGE_PRODUCTION'),
('SLTH_GOLDEN_AGE_COMMERCE', 'YieldType', 'YIELD_FAITH'),
('SLTH_GOLDEN_AGE_COMMERCE', 'Amount', '1'),
('SLTH_GOLDEN_AGE_PRODUCTION', 'YieldType', 'YIELD_PRODUCTION'),
('SLTH_GOLDEN_AGE_PRODUCTION', 'Amount', '1');


INSERT INTO TraitModifiers(TraitType, ModifierId) VALUES
('TRAIT_LEADER_MAJOR_CIV', 'SLTH_GOLDEN_AGE_COMMERCE_ATTACH'),
('TRAIT_LEADER_MAJOR_CIV', 'SLTH_GOLDEN_AGE_PRODUCTION_ATTACH'),
('SLTH_TRAIT_FINANCIAL', 'SLTH_FINANCIAL_COMMERCE_ON_PLOTS_WITH_2_COMMERCE');

-- gold bonus for financial
--(
-- does tile have an improvement with faith on it. +1

-- is tile next to river and not forested.

-- does tile have natural faith yield (also stuff like Malakim bonus)

-- )
--OR
-- does a tile have an improvement with 2 faith on it.

-- Golden age
-- impovements
-- +2:  PIRATE_COVE, PIRATE_HARBOR, FEITORIA, HAMLET, VILLAGE, TOWN, ENCLAVE
-- +1   COTTAGE, WINDMILL, WORKSHOP

-- tile
-- TERRAIN_COAST, TERRAIN_DESERT(WITH MALAKIM)

-- feature
-- +2 FEATURE_EYE_OF_THE_SAHARA

-- resource
-- +2 Gold, Pearls
-- +1 Dyes, Fur, Cotton, Diamonds, Incense, Silk, Spices, Olives

-- improved resource
-- +2 Fur, Diamonds, Dyes, Silk, Reagents, Cotton, Razorweed, Marble, Whale, Wine
-- +1 Ivory, Horse, Sheep, Toad, Sugar, Gulagarm
INSERT INTO Requirements(RequirementId, RequirementType) VALUES
('SUBREQSET_IMPROVED_FUR', 'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('SUBREQSET_IMPROVED_GEMS', 'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('SUBREQSET_IMPROVED_DYE', 'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('SUBREQSET_IMPROVED_INCENSE', 'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('SUBREQSET_IMPROVED_SILK', 'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('SUBREQSET_IMPROVED_REAGENTS', 'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('SUBREQSET_IMPROVED_COTTON', 'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('SUBREQSET_IMPROVED_RAZORWEED', 'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('SUBREQSET_IMPROVED_MARBLE', 'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('SUBREQSET_IMPROVED_WHALE', 'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('SUBREQSET_IMPROVED_WINE', 'REQUIREMENT_REQUIREMENTSET_IS_MET'),
-- split 2+:1
('SUBREQSET_IMPROVED_HORSE', 'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('SUBREQSET_IMPROVED_SHEEP', 'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('SUBREQSET_IMPROVED_NIGHTMARE', 'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('SUBREQSET_IMPROVED_TOAD', 'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('SUBREQSET_IMPROVED_SUGAR', 'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('SUBREQSET_IMPROVED_GULAGARM', 'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('SUBREQSET_IMPROVED_IVORY', 'REQUIREMENT_REQUIREMENTSET_IS_MET');

INSERT INTO RequirementArguments(RequirementId, Name, Value) VALUES
('SUBREQSET_IMPROVED_FUR', 'RequirementSetId', 'PLOT_HAS_FUR_YIELD_FAITH_TAG_IMPROVED'),
-- already at 2 ('SUBREQSET_IMPROVED_PEARLS', 'RequirementSetId', 'PLOT_HAS_PEARL_YIELD_FAITH_TAG_IMPROVED'),
('SUBREQSET_IMPROVED_GEMS', 'RequirementSetId', 'PLOT_HAS_GEMS_YIELD_FAITH_TAG_IMPROVED'),
-- already at 2 ('SUBREQSET_IMPROVED_GOLD', 'RequirementSetId', 'PLOT_HAS_GOLD_YIELD_FAITH_TAG_IMPROVED'),
('SUBREQSET_IMPROVED_DYE', 'RequirementSetId', 'PLOT_HAS_DYE_YIELD_FAITH_TAG_IMPROVED'),
('SUBREQSET_IMPROVED_INCENSE', 'RequirementSetId', 'PLOT_HAS_INCENSE_YIELD_FAITH_TAG_IMPROVED'),
('SUBREQSET_IMPROVED_SILK', 'RequirementSetId', 'PLOT_HAS_SILK_YIELD_FAITH_TAG_IMPROVED'),
('SUBREQSET_IMPROVED_REAGENTS', 'RequirementSetId', 'PLOT_HAS_REAGENTS_YIELD_FAITH_TAG_IMPROVED'),
('SUBREQSET_IMPROVED_COTTON', 'RequirementSetId', 'PLOT_HAS_COTTON_YIELD_FAITH_TAG_IMPROVED'),
('SUBREQSET_IMPROVED_RAZORWEED', 'RequirementSetId', 'PLOT_HAS_RAZORWEED_YIELD_FAITH_TAG_IMPROVED'),
('SUBREQSET_IMPROVED_MARBLE', 'RequirementSetId', 'PLOT_HAS_MARBLE_YIELD_FAITH_TAG_IMPROVED'),
('SUBREQSET_IMPROVED_WHALE', 'RequirementSetId', 'PLOT_HAS_WHALE_YIELD_FAITH_TAG_IMPROVED'),
('SUBREQSET_IMPROVED_WINE', 'RequirementSetId', 'PLOT_HAS_WINE_YIELD_FAITH_TAG_IMPROVED'),
-- split 2+:1
('SUBREQSET_IMPROVED_HORSE', 'RequirementSetId', 'PLOT_HAS_HORSE_YIELD_FAITH_TAG_IMPROVED'),
('SUBREQSET_IMPROVED_SHEEP', 'RequirementSetId', 'PLOT_HAS_SHEEP_YIELD_FAITH_TAG_IMPROVED'),
('SUBREQSET_IMPROVED_NIGHTMARE', 'RequirementSetId', 'PLOT_HAS_NIGHTMARE_YIELD_FAITH_TAG_IMPROVED'),
('SUBREQSET_IMPROVED_TOAD', 'RequirementSetId', 'PLOT_HAS_TOAD_YIELD_FAITH_TAG_IMPROVED'),
('SUBREQSET_IMPROVED_SUGAR', 'RequirementSetId', 'PLOT_HAS_SUGAR_YIELD_FAITH_TAG_IMPROVED'),
('SUBREQSET_IMPROVED_GULAGARM', 'RequirementSetId', 'PLOT_HAS_GULAGARM_YIELD_FAITH_TAG_IMPROVED'),
('SUBREQSET_IMPROVED_IVORY', 'RequirementSetId', 'PLOT_HAS_IVORY_YIELD_FAITH_TAG_IMPROVED');


INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('TILE_HAS_TWO_COMMERCE_RESOURCE_REQS', 'SUBREQSET_IMPROVED_FUR'),
('TILE_HAS_TWO_COMMERCE_RESOURCE_REQS', 'SUBREQSET_IMPROVED_GEMS'),
('TILE_HAS_TWO_COMMERCE_RESOURCE_REQS', 'SUBREQSET_IMPROVED_DYE'),
('TILE_HAS_TWO_COMMERCE_RESOURCE_REQS', 'SUBREQSET_IMPROVED_INCENSE'),
('TILE_HAS_TWO_COMMERCE_RESOURCE_REQS', 'SUBREQSET_IMPROVED_REAGENTS'),
('TILE_HAS_TWO_COMMERCE_RESOURCE_REQS', 'SUBREQSET_IMPROVED_COTTON'),
('TILE_HAS_TWO_COMMERCE_RESOURCE_REQS', 'SUBREQSET_IMPROVED_RAZORWEED'),
('TILE_HAS_TWO_COMMERCE_RESOURCE_REQS', 'SUBREQSET_IMPROVED_MARBLE'),
('TILE_HAS_TWO_COMMERCE_RESOURCE_REQS', 'SUBREQSET_IMPROVED_WHALE'),
('TILE_HAS_TWO_COMMERCE_RESOURCE_REQS', 'SUBREQSET_IMPROVED_WINE'),
('TILE_HAS_TWO_COMMERCE_RESOURCE_REQS', 'PLOT_HAS_GOLD_YIELD_PRODUCTION_TAG'),            -- just has the resource
('TILE_HAS_TWO_COMMERCE_RESOURCE_REQS', 'PLOT_HAS_PEARL_YIELD_FAITH_TAG');

INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('TILE_HAS_ONE_COMMERCE_RESOURCE_REQS', 'SUBREQSET_IMPROVED_FUR'),
('TILE_HAS_ONE_COMMERCE_RESOURCE_REQS', 'SUBREQSET_IMPROVED_GEMS'),
('TILE_HAS_ONE_COMMERCE_RESOURCE_REQS', 'SUBREQSET_IMPROVED_DYE'),
('TILE_HAS_ONE_COMMERCE_RESOURCE_REQS', 'SUBREQSET_IMPROVED_INCENSE'),
('TILE_HAS_ONE_COMMERCE_RESOURCE_REQS', 'SUBREQSET_IMPROVED_REAGENTS'),
('TILE_HAS_ONE_COMMERCE_RESOURCE_REQS', 'SUBREQSET_IMPROVED_COTTON'),
('TILE_HAS_ONE_COMMERCE_RESOURCE_REQS', 'SUBREQSET_IMPROVED_RAZORWEED'),
('TILE_HAS_ONE_COMMERCE_RESOURCE_REQS', 'SUBREQSET_IMPROVED_MARBLE'),
('TILE_HAS_ONE_COMMERCE_RESOURCE_REQS', 'SUBREQSET_IMPROVED_WHALE'),
('TILE_HAS_ONE_COMMERCE_RESOURCE_REQS', 'SUBREQSET_IMPROVED_WINE'),
('TILE_HAS_ONE_COMMERCE_RESOURCE_REQS', 'SUBREQSET_IMPROVED_HORSE'),
('TILE_HAS_ONE_COMMERCE_RESOURCE_REQS', 'SUBREQSET_IMPROVED_SHEEP'),
('TILE_HAS_ONE_COMMERCE_RESOURCE_REQS', 'SUBREQSET_IMPROVED_NIGHTMARE'),
('TILE_HAS_ONE_COMMERCE_RESOURCE_REQS', 'SUBREQSET_IMPROVED_TOAD'),
('TILE_HAS_ONE_COMMERCE_RESOURCE_REQS', 'SUBREQSET_IMPROVED_SUGAR'),
('TILE_HAS_ONE_COMMERCE_RESOURCE_REQS', 'SUBREQSET_IMPROVED_GULAGARM'),
('TILE_HAS_ONE_COMMERCE_RESOURCE_REQS', 'SUBREQSET_IMPROVED_IVORY'),
('TILE_HAS_ONE_COMMERCE_RESOURCE_REQS', 'PLOT_HAS_DYE_YIELD_FAITH_TAG'),            -- just has the resource
('TILE_HAS_ONE_COMMERCE_RESOURCE_REQS', 'PLOT_HAS_FUR_YIELD_FAITH_TAG'),
('TILE_HAS_ONE_COMMERCE_RESOURCE_REQS', 'PLOT_HAS_COTTON_YIELD_FAITH_TAG'),
('TILE_HAS_ONE_COMMERCE_RESOURCE_REQS', 'PLOT_HAS_GEMS_YIELD_FAITH_TAG'),
('TILE_HAS_ONE_COMMERCE_RESOURCE_REQS', 'PLOT_HAS_INCENSE_YIELD_FAITH_TAG'),
('TILE_HAS_ONE_COMMERCE_RESOURCE_REQS', 'PLOT_HAS_SILK_YIELD_FAITH_TAG'),
('TILE_HAS_ONE_COMMERCE_RESOURCE_REQS', 'PLOT_HAS_REAGENTS_YIELD_FAITH_TAG'),
('TILE_HAS_ONE_COMMERCE_RESOURCE_REQS', 'PLOT_HAS_RAZORWEED_YIELD_FAITH_TAG');

INSERT INTO RequirementSets(RequirementSetId, RequirementSetType) VALUES
('TILE_HAS_TWO_COMMERCE_RESOURCE_REQS', 'REQUIREMENTSET_TEST_ANY'),
('TILE_HAS_ONE_COMMERCE_RESOURCE_REQS', 'REQUIREMENTSET_TEST_ANY');

-- windmills get 2 faith at machinery
INSERT INTO Requirements(RequirementId, RequirementType) VALUES
('REQUIRES_PLOT_HAS_COTTAGE', 'REQUIREMENT_PLOT_IMPROVEMENT_TYPE_MATCHES'),
('REQUIRES_PLOT_HAS_WORKSHOP', 'REQUIREMENT_PLOT_IMPROVEMENT_TYPE_MATCHES'),
('REQUIRES_PLOT_HAS_WINDMILL', 'REQUIREMENT_PLOT_IMPROVEMENT_TYPE_MATCHES'),
('REQUIRES_PLOT_HAS_HAMLET', 'REQUIREMENT_PLOT_IMPROVEMENT_TYPE_MATCHES'),
('REQUIRES_PLOT_HAS_VILLAGE', 'REQUIREMENT_PLOT_IMPROVEMENT_TYPE_MATCHES'),
('REQUIRES_PLOT_HAS_TOWN', 'REQUIREMENT_PLOT_IMPROVEMENT_TYPE_MATCHES'),
('REQUIRES_PLOT_HAS_ENCLAVE', 'REQUIREMENT_PLOT_IMPROVEMENT_TYPE_MATCHES');

INSERT INTO RequirementArguments(RequirementId, Name, Type, Value) VALUES
('REQUIRES_PLOT_HAS_COTTAGE', 'ImprovementType', 'ARGTYPE_IDENTITY', 'IMPROVEMENT_COTTAGE'),
('REQUIRES_PLOT_HAS_WORKSHOP', 'ImprovementType', 'ARGTYPE_IDENTITY', 'IMPROVEMENT_WORKSHOP'),
('REQUIRES_PLOT_HAS_WINDMILL', 'ImprovementType', 'ARGTYPE_IDENTITY', 'IMPROVEMENT_WINDMILL'),
('REQUIRES_PLOT_HAS_HAMLET', 'ImprovementType', 'ARGTYPE_IDENTITY', 'IMPROVEMENT_HAMLET'),
('REQUIRES_PLOT_HAS_VILLAGE', 'ImprovementType', 'ARGTYPE_IDENTITY', 'IMPROVEMENT_VILLAGE'),
('REQUIRES_PLOT_HAS_TOWN', 'ImprovementType', 'ARGTYPE_IDENTITY', 'IMPROVEMENT_TOWN'),
('REQUIRES_PLOT_HAS_ENCLAVE', 'ImprovementType', 'ARGTYPE_IDENTITY', 'IMPROVEMENT_ENCLAVE');

INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('TILE_HAS_TWO_COMMERCE_IMPROVEMENT_REQS', 'REQUIRES_PLOT_HAS_HAMLET'),
('TILE_HAS_TWO_COMMERCE_IMPROVEMENT_REQS', 'REQUIRES_PLOT_HAS_VILLAGE'),
('TILE_HAS_TWO_COMMERCE_IMPROVEMENT_REQS', 'REQUIRES_PLOT_HAS_TOWN'),
('TILE_HAS_TWO_COMMERCE_IMPROVEMENT_REQS', 'REQUIRES_PLOT_HAS_ENCLAVE');            -- TODO possibly windmill with machinery


INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('TILE_HAS_ONE_COMMERCE_IMPROVEMENT_REQS', 'REQUIRES_PLOT_HAS_COTTAGE'),
('TILE_HAS_ONE_COMMERCE_IMPROVEMENT_REQS', 'REQUIRES_PLOT_HAS_WORKSHOP'),
('TILE_HAS_ONE_COMMERCE_IMPROVEMENT_REQS', 'REQUIRES_PLOT_HAS_WINDMILL');

INSERT INTO RequirementSets(RequirementSetId, RequirementSetType) VALUES
('TILE_HAS_TWO_COMMERCE_IMPROVEMENT_REQS', 'REQUIREMENTSET_TEST_ANY'),
('TILE_HAS_ONE_COMMERCE_IMPROVEMENT_REQS', 'REQUIREMENTSET_TEST_ANY');

INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('TILE_HAS_TWO_COMMERCE_FEATURE_REQS', 'REQUIRES_PLOT_HAS_EYE_SAHARA');                 -- tile has dragon bones

INSERT INTO Requirements(RequirementId, RequirementType) VALUES
('SUBREQSET_IS_DESERT', 'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('SUBREQSET_MALAKIM_DESERT', 'REQUIREMENT_REQUIREMENTSET_IS_MET');

INSERT INTO RequirementArguments(RequirementId, Name, Value) VALUES
('SUBREQSET_IS_DESERT', 'RequirementSetId', 'SLTH_IS_DESERT'),
('SUBREQSET_MALAKIM_DESERT', 'RequirementSetId', 'TILE_IS_DESERT_AND_MALAKIM_REQS');

INSERT INTO Requirements(RequirementId, RequirementType) VALUES
('REQUIRES_PLAYER_IS_MALAKIM', 'REQUIREMENT_PLAYER_HAS_CIVILIZATION_OR_LEADER_TRAIT');
INSERT INTO RequirementArguments(RequirementId, Name,Value) VALUES
('REQUIRES_PLAYER_IS_MALAKIM', 'TraitType', 'SLTH_TRAIT_CIVILIZATION_MALAKIM_COOL');

INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('TILE_HAS_ONE_COMMERCE_TERRAIN_REQS', 'REQUIRES_TERRAIN_COAST'),                 -- tile is coast terrain
('TILE_IS_DESERT_AND_MALAKIM_REQS', 'SUBREQSET_IS_DESERT'),                       -- is desert
('TILE_IS_DESERT_AND_MALAKIM_REQS', 'REQUIRES_PLAYER_IS_MALAKIM'),                -- is malakim
('TILE_HAS_ONE_COMMERCE_TERRAIN_REQS', 'SUBREQSET_MALAKIM_DESERT');               -- tile is desert and player is malakim

INSERT INTO RequirementSets(RequirementSetId, RequirementSetType) VALUES
('TILE_HAS_TWO_COMMERCE_FEATURE_REQS', 'REQUIREMENTSET_TEST_ANY'),                  -- feature only grants two, as dragon bones
('TILE_HAS_ONE_COMMERCE_TERRAIN_REQS', 'REQUIREMENTSET_TEST_ANY'),                  -- terrain only grants one, coast or malakim desert
('TILE_IS_DESERT_AND_MALAKIM_REQS', 'REQUIREMENTSET_TEST_ALL');

-- finally collect subreqsets
INSERT INTO Requirements(RequirementId, RequirementType) VALUES
('SUBREQSET_ADJACENT_RIVER_AND_FORESTED', 'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('SUBREQSET_TILE_HAS_ONE_COMMERCE_RESOURCE', 'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('SUBREQSET_TILE_HAS_TWO_COMMERCE_RESOURCE', 'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('SUBREQSET_TILE_HAS_ONE_COMMERCE_IMPROVEMENT', 'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('SUBREQSET_TILE_HAS_TWO_COMMERCE_IMPROVEMENT', 'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('SUBREQSET_TILE_HAS_TWO_COMMERCE_FEATURE', 'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('SUBREQSET_TILE_HAS_ONE_COMMERCE_TERRAIN', 'REQUIREMENT_REQUIREMENTSET_IS_MET');

INSERT INTO RequirementArguments(RequirementId, Name, Value) VALUES
('SUBREQSET_ADJACENT_RIVER_AND_FORESTED', 'RequirementSetId', 'RIVER_ADJACENT_AND_NOT_FORESTED_REQS'),
('SUBREQSET_TILE_HAS_ONE_COMMERCE_RESOURCE', 'RequirementSetId', 'TILE_HAS_ONE_COMMERCE_RESOURCE_REQS'),
('SUBREQSET_TILE_HAS_TWO_COMMERCE_RESOURCE', 'RequirementSetId', 'TILE_HAS_TWO_COMMERCE_RESOURCE_REQS'),
('SUBREQSET_TILE_HAS_ONE_COMMERCE_IMPROVEMENT', 'RequirementSetId', 'TILE_HAS_ONE_COMMERCE_IMPROVEMENT_REQS'),
('SUBREQSET_TILE_HAS_TWO_COMMERCE_IMPROVEMENT', 'RequirementSetId', 'TILE_HAS_TWO_COMMERCE_IMPROVEMENT_REQS'),
('SUBREQSET_TILE_HAS_TWO_COMMERCE_FEATURE', 'RequirementSetId', 'TILE_HAS_TWO_COMMERCE_FEATURE_REQS'),
('SUBREQSET_TILE_HAS_ONE_COMMERCE_TERRAIN', 'RequirementSetId', 'TILE_HAS_ONE_COMMERCE_TERRAIN_REQS');

INSERT INTO RequirementSets(RequirementSetId, RequirementSetType) VALUES
('TILE_HAS_A_COMMERCE_REQS', 'REQUIREMENTSET_TEST_ANY');

INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('TILE_HAS_A_COMMERCE_REQS', 'SUBREQSET_ADJACENT_RIVER_AND_FORESTED'),
('TILE_HAS_A_COMMERCE_REQS', 'SUBREQSET_TILE_HAS_ONE_COMMERCE_RESOURCE'),
('TILE_HAS_A_COMMERCE_REQS', 'SUBREQSET_TILE_HAS_TWO_COMMERCE_RESOURCE'),
('TILE_HAS_A_COMMERCE_REQS', 'SUBREQSET_TILE_HAS_ONE_COMMERCE_IMPROVEMENT'),
('TILE_HAS_A_COMMERCE_REQS', 'SUBREQSET_TILE_HAS_TWO_COMMERCE_IMPROVEMENT'),
('TILE_HAS_A_COMMERCE_REQS', 'SUBREQSET_TILE_HAS_TWO_COMMERCE_FEATURE'),                             -- only one feature grants commerce, dragon bones, so dont need one check
('TILE_HAS_A_COMMERCE_REQS', 'SUBREQSET_TILE_HAS_ONE_COMMERCE_TERRAIN');


-- TWO COMMERCE REquiremetns
INSERT INTO RequirementSets(RequirementSetId, RequirementSetType) VALUES
('TILE_HAS_TWO_COMMERCE_REQS', 'REQUIREMENTSET_TEST_ANY');

INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('TILE_HAS_TWO_COMMERCE_REQS', 'SUBREQSET_TILE_HAS_TWO_COMMERCE_RESOURCE'),
('TILE_HAS_TWO_COMMERCE_REQS', 'SUBREQSET_TILE_HAS_TWO_COMMERCE_IMPROVEMENT'),
('TILE_HAS_TWO_COMMERCE_REQS', 'SUBREQSET_TILE_HAS_TWO_COMMERCE_FEATURE');

INSERT INTO RequirementSets(RequirementSetId, RequirementSetType) VALUES
('TILE_HAS_ADJACENT_RIVER_AND_RESOURCE_COMMERCE_REQS', 'REQUIREMENTSET_TEST_ALL'),
('TILE_HAS_ADJACENT_RIVER_AND_IMPROVEMENT_COMMERCE_REQS', 'REQUIREMENTSET_TEST_ALL'),
('TILE_HAS_ADJACENT_RIVER_AND_TERRAIN_COMMERCE_REQS', 'REQUIREMENTSET_TEST_ALL'),

('TILE_HAS_RESOURCE_COMMERCE_AND_TERRAIN_COMMERCE_REQS', 'REQUIREMENTSET_TEST_ALL'),
--('TILE_HAS_RESOURCE_COMMERCE_AND_IMPROVEMENT_COMMERCE_REQS', 'REQUIREMENTSET_TEST_ALL'),                -- skip this one? no resource gets an improvement that isnt covered
('TILE_HAS_IMPROVEMENT_COMMERCE_AND_TERRAIN_COMMERCE_REQS', 'REQUIREMENTSET_TEST_ALL');


INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('TILE_HAS_ADJACENT_RIVER_AND_RESOURCE_COMMERCE_REQS', 'SUBREQSET_TILE_HAS_ONE_COMMERCE_RESOURCE'),
('TILE_HAS_ADJACENT_RIVER_AND_RESOURCE_COMMERCE_REQS', 'SUBREQSET_ADJACENT_RIVER_AND_FORESTED'),

('TILE_HAS_ADJACENT_RIVER_AND_IMPROVEMENT_COMMERCE_REQS', 'SUBREQSET_TILE_HAS_ONE_COMMERCE_IMPROVEMENT'),
('TILE_HAS_ADJACENT_RIVER_AND_IMPROVEMENT_COMMERCE_REQS', 'SUBREQSET_ADJACENT_RIVER_AND_FORESTED'),

('TILE_HAS_ADJACENT_RIVER_AND_TERRAIN_COMMERCE_REQS', 'SUBREQSET_TILE_HAS_ONE_COMMERCE_TERRAIN'),
('TILE_HAS_ADJACENT_RIVER_AND_TERRAIN_COMMERCE_REQS', 'SUBREQSET_ADJACENT_RIVER_AND_FORESTED'),

('TILE_HAS_RESOURCE_COMMERCE_AND_TERRAIN_COMMERCE_REQS', 'SUBREQSET_TILE_HAS_ONE_COMMERCE_RESOURCE'),
('TILE_HAS_RESOURCE_COMMERCE_AND_TERRAIN_COMMERCE_REQS', 'SUBREQSET_TILE_HAS_ONE_COMMERCE_TERRAIN'),

-- ('TILE_HAS_RESOURCE_COMMERCE_AND_IMPROVEMENT_COMMERCE_REQS', 'SUBREQSET_TILE_HAS_ONE_COMMERCE_RESOURCE'),
-- ('TILE_HAS_RESOURCE_COMMERCE_AND_IMPROVEMENT_COMMERCE_REQS', 'SUBREQSET_TILE_HAS_ONE_COMMERCE_IMPROVEMENT'),

('TILE_HAS_IMPROVEMENT_COMMERCE_AND_TERRAIN_COMMERCE_REQS', 'SUBREQSET_TILE_HAS_ONE_COMMERCE_IMPROVEMENT'),
('TILE_HAS_IMPROVEMENT_COMMERCE_AND_TERRAIN_COMMERCE_REQS', 'SUBREQSET_TILE_HAS_ONE_COMMERCE_TERRAIN');

INSERT INTO Requirements(RequirementId, RequirementType) VALUES
('SUBREQSET_RIVER_RESOURCE_COMMERCE', 'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('SUBREQSET_RIVER_IMPROVEMENT_COMMERCE', 'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('SUBREQSET_RIVER_TERRAIN_COMMERCE', 'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('SUBREQSET_RESOURCE_TERRAIN_COMMERCE', 'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('SUBREQSET_IMPROVEMENT_TERRAIN_COMMERCE', 'REQUIREMENT_REQUIREMENTSET_IS_MET');

INSERT INTO RequirementArguments(RequirementId, Name, Value) VALUES
('SUBREQSET_RIVER_RESOURCE_COMMERCE', 'RequirementSetId', 'TILE_HAS_ADJACENT_RIVER_AND_RESOURCE_COMMERCE_REQS'),
('SUBREQSET_RIVER_IMPROVEMENT_COMMERCE', 'RequirementSetId', 'TILE_HAS_ADJACENT_RIVER_AND_IMPROVEMENT_COMMERCE_REQS'),
('SUBREQSET_RIVER_TERRAIN_COMMERCE', 'RequirementSetId', 'TILE_HAS_ADJACENT_RIVER_AND_TERRAIN_COMMERCE_REQS'),
('SUBREQSET_RESOURCE_TERRAIN_COMMERCE', 'RequirementSetId', 'TILE_HAS_RESOURCE_COMMERCE_AND_TERRAIN_COMMERCE_REQS'),
('SUBREQSET_IMPROVEMENT_TERRAIN_COMMERCE', 'RequirementSetId', 'TILE_HAS_IMPROVEMENT_COMMERCE_AND_TERRAIN_COMMERCE_REQS');

INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('TILE_HAS_TWO_COMMERCE_REQS', 'SUBREQSET_RIVER_RESOURCE_COMMERCE'),
('TILE_HAS_TWO_COMMERCE_REQS', 'SUBREQSET_RIVER_IMPROVEMENT_COMMERCE'),
('TILE_HAS_TWO_COMMERCE_REQS', 'SUBREQSET_RIVER_TERRAIN_COMMERCE'),
('TILE_HAS_TWO_COMMERCE_REQS', 'SUBREQSET_RESOURCE_TERRAIN_COMMERCE'),
('TILE_HAS_TWO_COMMERCE_REQS', 'SUBREQSET_IMPROVEMENT_TERRAIN_COMMERCE');

-- also doing golden age production bonus here too.
INSERT INTO RequirementSets(RequirementSetId, RequirementSetType) VALUES
('TILE_HAS_PRODUCTION_REQS', 'REQUIREMENTSET_TEST_ANY');

INSERT INTO Requirements(RequirementId, RequirementType) VALUES
('REQUIRES_PLOT_HAS_PIRATE_HARBOR', 'REQUIREMENT_PLOT_IMPROVEMENT_TYPE_MATCHES'),
('REQUIRES_PLOT_HAS_FEITORIA', 'REQUIREMENT_PLOT_IMPROVEMENT_TYPE_MATCHES'),
('REQUIRES_PLOT_HAS_LUMBERMILL', 'REQUIREMENT_PLOT_IMPROVEMENT_TYPE_MATCHES');

INSERT INTO RequirementArguments(RequirementId, Name, Type, Value) VALUES
('REQUIRES_PLOT_HAS_PIRATE_HARBOR', 'ImprovementType', 'ARGTYPE_IDENTITY', 'IMPROVEMENT_PIRATE_HARBOR'),
('REQUIRES_PLOT_HAS_FEITORIA', 'ImprovementType', 'ARGTYPE_IDENTITY', 'IMPROVEMENT_FEITORIA'),
('REQUIRES_PLOT_HAS_LUMBERMILL', 'ImprovementType', 'ARGTYPE_IDENTITY', 'IMPROVEMENT_LUMBER_MILL');

INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('TILE_HAS_PRODUCTION_REQS', 'REQUIRES_PLOT_HAS_PIRATE_HARBOR'),
('TILE_HAS_PRODUCTION_REQS', 'REQUIRES_PLOT_HAS_FEITORIA'),
('TILE_HAS_PRODUCTION_REQS', 'REQUIRES_PLOT_HAS_WORKSHOP'),
('TILE_HAS_PRODUCTION_REQS', 'REQUIRES_PLOT_HAS_MINE'),
('TILE_HAS_PRODUCTION_REQS', 'REQUIRES_PLOT_HAS_LUMBERMILL');
-- IMPROVEMENT_QUARRY       -- with slavery


-- lmao i forgot about woods.
INSERT INTO Requirements(RequirementId, RequirementType) VALUES
('REQUIRES_PLOT_HAS_IKKIL', 'REQUIREMENT_PLOT_FEATURE_TYPE_MATCHES'),
('REQUIRES_PLOT_HAS_REMNANTS_PATRIA', 'REQUIREMENT_PLOT_FEATURE_TYPE_MATCHES');

INSERT INTO RequirementArguments(RequirementId, Name, Value) VALUES
('REQUIRES_PLOT_HAS_IKKIL', 'FeatureType', 'FEATURE_IKKIL'),
('REQUIRES_PLOT_HAS_REMNANTS_PATRIA', 'FeatureType', 'FEATURE_NWON_REMNANTS_OF_PATRIA');

INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('TILE_HAS_PRODUCTION_REQS', 'REQUIRES_PLOT_HAS_IKKIL'),
('TILE_HAS_PRODUCTION_REQS', 'REQUIRES_PLOT_HAS_REMNANTS_PATRIA');

INSERT INTO Requirements(RequirementId, RequirementType) VALUES
('SUBREQSET_IS_HILLY', 'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('SLTH_PLOT_IS_PLAINS', 'REQUIREMENT_PLOT_TERRAIN_TYPE_MATCHES');

INSERT INTO RequirementArguments(RequirementId, Name, Value) VALUES
('SUBREQSET_IS_HILLY', 'RequirementSetId', 'ROUGH_RIDER_HILL_TERRAIN_REQUIREMENTS'),
('SLTH_PLOT_IS_PLAINS', 'TerrainType', 'TERRAIN_PLAINS');

INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('TILE_HAS_PRODUCTION_REQS', 'SUBREQSET_IS_HILLY'),
('TILE_HAS_PRODUCTION_REQS', 'SLTH_PLOT_IS_PLAINS');
-- field of perdition

-- resources
INSERT INTO Requirements(RequirementId, RequirementType) VALUES
('REQUIRES_NITER_IN_PLOT', 'REQUIREMENT_PLOT_RESOURCE_TYPE_MATCHES'),
('REQUIRES_COPPER_IN_PLOT', 'REQUIREMENT_PLOT_RESOURCE_TYPE_MATCHES'),
('REQUIRES_IVORY_IN_PLOT', 'REQUIREMENT_PLOT_RESOURCE_TYPE_MATCHES'),
('REQUIRES_HORSES_IN_PLOT', 'REQUIREMENT_PLOT_RESOURCE_TYPE_MATCHES'),
('REQUIRES_IRON_IN_PLOT', 'REQUIREMENT_PLOT_RESOURCE_TYPE_MATCHES'),
('REQUIRES_MARBLE_IN_PLOT', 'REQUIREMENT_PLOT_RESOURCE_TYPE_MATCHES'),
('REQUIRES_NIGHTMARE_IN_PLOT', 'REQUIREMENT_PLOT_RESOURCE_TYPE_MATCHES'),
('REQUIRES_SILVER_IN_PLOT', 'REQUIREMENT_PLOT_RESOURCE_TYPE_MATCHES');

INSERT INTO RequirementArguments(RequirementId, Name, Value) VALUES
('REQUIRES_NITER_IN_PLOT', 'ResourceType', 'RESOURCE_NITER'),
('REQUIRES_COPPER_IN_PLOT', 'ResourceType', 'RESOURCE_COPPER'),
('REQUIRES_IVORY_IN_PLOT', 'ResourceType', 'RESOURCE_IVORY'),
('REQUIRES_HORSES_IN_PLOT', 'ResourceType', 'RESOURCE_HORSES'),
('REQUIRES_IRON_IN_PLOT', 'ResourceType', 'RESOURCE_IRON'),
('REQUIRES_MARBLE_IN_PLOT', 'ResourceType', 'RESOURCE_MARBLE'),
('REQUIRES_NIGHTMARE_IN_PLOT', 'ResourceType', 'RESOURCE_NIGHTMARE'),
('REQUIRES_SILVER_IN_PLOT', 'ResourceType', 'RESOURCE_SILVER');

INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('TILE_HAS_PRODUCTION_REQS', 'REQUIRES_NITER_IN_PLOT'),
('TILE_HAS_PRODUCTION_REQS', 'REQUIRES_COPPER_IN_PLOT'),
('TILE_HAS_PRODUCTION_REQS', 'REQUIRES_IVORY_IN_PLOT'),
('TILE_HAS_PRODUCTION_REQS', 'REQUIRES_HORSES_IN_PLOT'),
('TILE_HAS_PRODUCTION_REQS', 'REQUIRES_IRON_IN_PLOT'),
('TILE_HAS_PRODUCTION_REQS', 'REQUIRES_MARBLE_IN_PLOT'),
('TILE_HAS_PRODUCTION_REQS', 'REQUIRES_NIGHTMARE_IN_PLOT'),
('TILE_HAS_PRODUCTION_REQS', 'REQUIRES_SILVER_IN_PLOT');

-- tagged production
INSERT INTO Requirements(RequirementId, RequirementType) VALUES
('SUBREQSET_IMPROVED_COW', 'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('SUBREQSET_IMPROVED_SHEUT', 'REQUIREMENT_REQUIREMENTSET_IS_MET');

INSERT INTO RequirementArguments(RequirementId, Name, Value) VALUES
('SUBREQSET_IMPROVED_COW', 'RequirementSetId', 'PLOT_HAS_COW_YIELD_PRODUCTION_TAG'),
('SUBREQSET_IMPROVED_SHEUT', 'RequirementSetId', 'PLOT_HAS_SHEUT_STONE_YIELD_PRODUCTION_TAG');

INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('TILE_HAS_PRODUCTION_REQS', 'SUBREQSET_IMPROVED_GEMS'),
('TILE_HAS_PRODUCTION_REQS', 'SUBREQSET_IMPROVED_COW'),
('TILE_HAS_PRODUCTION_REQS', 'SUBREQSET_IMPROVED_SHEUT'),
('TILE_HAS_PRODUCTION_REQS', 'SUBREQSET_IMPROVED_WHALE');
