INSERT INTO District_CitizenGreatPersonPoints(DistrictType, GreatPersonClassType, PointsPerTurn) VALUES
('DISTRICT_CAMPUS', 'GREAT_PERSON_CLASS_SCIENTIST', 1),
('DISTRICT_HOLY_SITE', 'GREAT_PERSON_CLASS_PROPHET', 1),
('DISTRICT_COMMERCIAL_HUB', 'GREAT_PERSON_CLASS_MERCHANT', 1),
('DISTRICT_THEATER', 'GREAT_PERSON_CLASS_ARTIST', 1),
('DISTRICT_INDUSTRIAL_ZONE', 'GREAT_PERSON_CLASS_ENGINEER', 1);
