INSERT INTO Civilizations(CivilizationType, Name, Description, Adjective, RandomCityNameDepth, StartingCivilizationLevelType, Ethnicity) VALUES
('SLTH_CIVILIZATION_LANUN', 'LOC_CIV_LANUN_NAME', 'LOC_CIV_LANUN_DESCRIPTION', 'LOC_SLTH_CIV_LANUN_ADJECTIVE', '10', 'CIVILIZATION_LEVEL_FULL_CIV', 'ETHNICITY_MEDIT');
INSERT INTO Leaders(LeaderType, Name, InheritFrom, SceneLayers, Sex) VALUES
('LEADER_FALAMAR', 'LOC_LEADER_FALAMAR_NAME', 'LEADER_DEFAULT', 4, 'Male'),
('LEADER_HANNAH', 'LOC_LEADER_HANNAH_NAME', 'LEADER_DEFAULT', 0, 'Female');
INSERT INTO CivilizationLeaders(LeaderType, CivilizationType, CapitalName) VALUES
('LEADER_FALAMAR', 'SLTH_CIVILIZATION_LANUN', 'LOC_CITY_LANUN_1_NAME'),
('LEADER_HANNAH', 'SLTH_CIVILIZATION_LANUN', 'LOC_CITY_LANUN_1_NAME');

INSERT INTO	StartBiasTerrains
		(CivilizationType,			TerrainType,			Tier	)
VALUES	('SLTH_CIVILIZATION_LANUN',	'TERRAIN_COAST',		5		);

INSERT INTO	StartBiasFeatures
		(CivilizationType,			FeatureType,			Tier	)
VALUES	('SLTH_CIVILIZATION_LANUN',	'FEATURE_FOREST',	    2		);

-- one civ that doesnt need river bias

INSERT INTO CivilizationTraits(CivilizationType, TraitType) VALUES
('SLTH_CIVILIZATION_LANUN', 'SLTH_TRAIT_SEAFARING'),
('SLTH_CIVILIZATION_LANUN', 'SLTH_TRAIT_CIVILIZATION_BUILDING_HARBOR_LANUN'),
('SLTH_CIVILIZATION_LANUN', 'SLTH_TRAIT_CIVILIZATION_UNIT_BLACK_WIND'),
('SLTH_CIVILIZATION_LANUN', 'SLTH_TRAIT_CIVILIZATION_UNIT_GUYBRUSH'),
('SLTH_CIVILIZATION_LANUN', 'SLTH_TRAIT_CIVILIZATION_UNIT_BOARDING_PARTY'),
('SLTH_CIVILIZATION_LANUN', 'SLTH_TRAIT_CIVILIZATION_UNIT_WAR_TORTOISE'),
('SLTH_CIVILIZATION_LANUN', 'SLTH_TRAIT_CIVILIZATION_UNIT_PIRATE');

INSERT INTO Traits(TraitType, Name, Description) VALUES
('SLTH_TRAIT_SEAFARING', 'LOC_SLTH_TRAIT_SEAFARING_NAME', 'LOC_SLTH_TRAIT_SEAFARING_DESCRIPTION'),
('SLTH_TRAIT_CIVILIZATION_BUILDING_HARBOR_LANUN', 'LOC_SLTH_TRAIT_CIVILIZATION_BUILDING_HARBOR_LANUN_NAME', 'LOC_SLTH_TRAIT_CIVILIZATION_BUILDING_HARBOR_LANUN_DESCRIPTION'),
('SLTH_TRAIT_CIVILIZATION_UNIT_BOARDING_PARTY', 'LOC_SLTH_TRAIT_CIVILIZATION_UNIT_BOARDING_PARTY_NAME', 'LOC_SLTH_TRAIT_CIVILIZATION_UNIT_BOARDING_PARTY_DESCRIPTION'),
('SLTH_TRAIT_CIVILIZATION_UNIT_BLACK_WIND', 'LOC_SLTH_TRAIT_CIVILIZATION_UNIT_BLACK_WIND_NAME', 'LOC_SLTH_TRAIT_CIVILIZATION_UNIT_BLACK_WIND_DESCRIPTION'),
('SLTH_TRAIT_CIVILIZATION_UNIT_GUYBRUSH', 'LOC_SLTH_TRAIT_CIVILIZATION_UNIT_GUYBRUSH_NAME', 'LOC_SLTH_TRAIT_CIVILIZATION_UNIT_GUYBRUSH_DESCRIPTION'),
('SLTH_TRAIT_CIVILIZATION_UNIT_WAR_TORTOISE', 'LOC_SLTH_TRAIT_CIVILIZATION_UNIT_WAR_TORTOISE_NAME', 'LOC_SLTH_TRAIT_CIVILIZATION_UNIT_WAR_TORTOISE_DESCRIPTION'),
('SLTH_TRAIT_CIVILIZATION_UNIT_PIRATE', 'LOC_SLTH_TRAIT_CIVILIZATION_UNIT_PIRATE_NAME', 'LOC_SLTH_TRAIT_CIVILIZATION_UNIT_PIRATE_DESCRIPTION');

INSERT INTO TraitModifiers(TraitType, ModifierId) VALUES
('SLTH_TRAIT_SEAFARING', 'MODIFIER_SLTH_REVEAL_PEARL'),
('SLTH_TRAIT_SEAFARING', 'MODIFIER_SLTH_LANUN_BONUS_FOOD_COAST'),
('SLTH_TRAIT_SEAFARING', 'MODIFIER_SLTH_GRANT_TECH_FISHING'),
('SLTH_TRAIT_SEAFARING', 'MODIFIER_SLTH_GRANT_MANA_WATER'),
('SLTH_TRAIT_SEAFARING', 'MODIFIER_SLTH_GRANT_MANA_CHAOS'),
('SLTH_TRAIT_SEAFARING', 'MODIFIER_SLTH_GRANT_MANA_AIR');


INSERT INTO Modifiers(ModifierId, ModifierType, RunOnce, Permanent, SubjectRequirementSetId) VALUES
('MODIFIER_SLTH_LANUN_BONUS_FOOD_COAST', 'MODIFIER_PLAYER_ADJUST_PLOT_YIELD', '0', '0', 'PLOT_HAS_COAST_REQUIREMENTS'),
('MODIFIER_SLTH_REVEAL_PEARL', 'MODIFIER_PLAYER_GRANT_FREE_RESOURCE_VISIBILITY', '0', '0', NULL),
('MODIFIER_SLTH_BUILDING_HARBOR_LANUN_DOMAIN_SEA_PROD_MULT', 'MODIFIER_CITY_ADJUST_UNIT_DOMAIN_PRODUCTION', '0', '0', NULL),
('MODIFIER_SLTH_GRANT_TECH_FISHING', 'MODIFIER_PLAYER_GRANT_SPECIFIC_TECHNOLOGY', '1', '1', NULL);


INSERT INTO ModifierArguments(ModifierId, Name, Type, Value) VALUES
('MODIFIER_SLTH_LANUN_BONUS_FOOD_COAST', 'YieldType', 'ARGTYPE_IDENTITY', 'YIELD_FOOD'),
('MODIFIER_SLTH_LANUN_BONUS_FOOD_COAST', 'Amount', 'ARGTYPE_IDENTITY', '1'),
('MODIFIER_SLTH_REVEAL_PEARL', 'ResourceType', 'ARGTYPE_IDENTITY', 'RESOURCE_PEARLS'),
('MODIFIER_SLTH_BUILDING_HARBOR_LANUN_DOMAIN_SEA_PROD_MULT', 'Domain', 'ARGTYPE_IDENTITY', 'DOMAIN_SEA'),
('MODIFIER_SLTH_BUILDING_HARBOR_LANUN_DOMAIN_SEA_PROD_MULT', 'Amount', 'ARGTYPE_IDENTITY', '25'),
('MODIFIER_SLTH_GRANT_TECH_FISHING', 'TechType', 'ARGTYPE_IDENTITY', 'TECH_FISHING');

INSERT INTO BuildingReplaces(CivUniqueBuildingType, ReplacesBuildingType) VALUES
('SLTH_BUILDING_HARBOR_LANUN', 'SLTH_BUILDING_HARBOR');

INSERT INTO Buildings(BuildingType, Name, PrereqTech, PrereqCivic, Cost, PrereqDistrict, Description, OuterDefenseHitPoints, Housing, Entertainment, TraitType, CitizenSlots, AdvisorType) VALUES
('SLTH_BUILDING_HARBOR_LANUN', 'LOC_SLTH_BUILDING_HARBOR_LANUN_NAME', 'TECH_FISHING', NULL, '90', 'DISTRICT_CITY_CENTER', 'LOC_SLTH_BUILDING_HARBOR_LANUN_DESCRIPTION', '0', '0', '0', 'SLTH_TRAIT_CIVILIZATION_BUILDING_HARBOR_LANUN', NULL, 'ADVISOR_GENERIC');

INSERT INTO BuildingModifiers(BuildingType, ModifierId) VALUES
('SLTH_BUILDING_HARBOR_LANUN', 'MODIFIER_SLTH_BUILDING_HARBOR_LANUN_DOMAIN_SEA_PROD_MULT'),
('SLTH_BUILDING_HARBOR_LANUN', 'HARBOR_TRADE_ROUTE_YIELD_MULT_DOMESTIC'),
('SLTH_BUILDING_HARBOR_LANUN', 'HARBOR_TRADE_ROUTE_YIELD_MULT_INATIONAL');

INSERT INTO UnitReplaces(CivUniqueUnitType, ReplacesUnitType) VALUES
('SLTH_UNIT_BOARDING_PARTY', 'SLTH_UNIT_CHAMPION'),
('SLTH_UNIT_WAR_TORTOISE', 'SLTH_UNIT_KNIGHT'),
('SLTH_UNIT_PIRATE', 'SLTH_UNIT_PRIVATEER');



INSERT INTO Resource_Conditions (ResourceType, UnlocksFromEffect) VALUES
('RESOURCE_PEARLS', 1);

INSERT INTO Resources(ResourceType, Name, ResourceClassType, Happiness, LakeEligible, SeaFrequency) VALUES
('RESOURCE_PEARLS', 'LOC_RESOURCE_PEARL', 'RESOURCECLASS_LUXURY', '4', '1', '2');

INSERT INTO Resource_ValidTerrains(ResourceType, TerrainType) VALUES
('RESOURCE_PEARLS', 'TERRAIN_COAST');

INSERT INTO Resource_ValidFeatures (ResourceType, FeatureType) VALUES
('RESOURCE_PEARLS', 'FEATURE_REEF');

INSERT INTO Improvements(ImprovementType, Name, Buildable, Description, PlunderType, PlunderAmount, Icon, CanBuildOutsideTerritory, DefenseModifier, TraitType, GrantFortification, Domain, AdjacentToLand, SameAdjacentValid, PrereqTech) VALUES
('IMPROVEMENT_PIRATE_COVE', 'LOC_IMPROVEMENT_PIRATE_COVE_NAME', '1', 'LOC_IMPROVEMENT_PIRATE_COVE_DESCRIPTION', 'PLUNDER_GOLD', '5', 'ICON_IMPROVEMENT_KAMPUNG', '0', '10', 'SLTH_TRAIT_SEAFARING', '2', 'DOMAIN_WATER', '1', '0', 'SLTH_TECH_SAILING'),
('IMPROVEMENT_PIRATE_HARBOR', 'LOC_IMPROVEMENT_PIRATE_HARBOR_NAME', '0', 'LOC_IMPROVEMENT_PIRATE_HARBOR_DESCRIPTION', 'PLUNDER_GOLD', '5', 'ICON_IMPROVEMENT_FEITORIA', '0', '20', 'SLTH_TRAIT_SEAFARING', '2','DOMAIN_WATER', '1', '0', 'SLTH_TECH_SAILING'),
('IMPROVEMENT_FEITORIA', 'LOC_IMPROVEMENT_PIRATE_PORT_NAME', '0', 'LOC_IMPROVEMENT_PIRATE_PORT_DESCRIPTION', 'PLUNDER_GOLD', '5', 'ICON_IMPROVEMENT_FEITORIA', '0', '30',  'SLTH_TRAIT_SEAFARING', '2', 'DOMAIN_WATER', '1', '0', 'SLTH_TECH_SAILING');

INSERT INTO Improvement_ValidTerrains(ImprovementType, TerrainType) VALUES
('IMPROVEMENT_PIRATE_COVE', 'TERRAIN_COAST'),
('IMPROVEMENT_PIRATE_HARBOR', 'TERRAIN_COAST'),
('IMPROVEMENT_FEITORIA', 'TERRAIN_COAST');

INSERT INTO Improvement_ValidBuildUnits(ImprovementType, UnitType, ConsumesCharge) VALUES
('IMPROVEMENT_PIRATE_COVE', 'UNIT_BUILDER', '1');

INSERT INTO Improvement_YieldChanges(ImprovementType, YieldType, YieldChange) VALUES
('IMPROVEMENT_PIRATE_COVE', 'YIELD_FAITH', '2'),
('IMPROVEMENT_PIRATE_HARBOR', 'YIELD_FOOD', '1'),
('IMPROVEMENT_PIRATE_HARBOR', 'YIELD_PRODUCTION', '1'),
('IMPROVEMENT_PIRATE_HARBOR', 'YIELD_FAITH', '3'),
('IMPROVEMENT_FEITORIA', 'YIELD_FOOD', '2'),
('IMPROVEMENT_FEITORIA', 'YIELD_PRODUCTION', '2'),
('IMPROVEMENT_FEITORIA', 'YIELD_FAITH', '4');

INSERT INTO TypeTags(Type, Tag) VALUES
('SLTH_UNIT_BLACK_WIND', 'CLASS_NAVAL_MELEE'),
('SLTH_UNIT_GUYBRUSH', 'CLASS_MELEE'),
('SLTH_UNIT_BOARDING_PARTY', 'CLASS_MELEE'),
('SLTH_UNIT_WAR_TORTOISE', 'CLASS_LIGHT_CAVALRY'),
('SLTH_UNIT_PIRATE', 'CLASS_NAVAL_MELEE'),
('SLTH_UNIT_GUYBRUSH', 'RACE_HUMAN'),
('SLTH_UNIT_BOARDING_PARTY', 'CAN_BE_RACIALIZED'),
('SLTH_UNIT_WAR_TORTOISE', 'CAN_BE_RACIALIZED');

INSERT INTO Types(Type, Kind) VALUES
('SLTH_CIVILIZATION_LANUN', 'KIND_CIVILIZATION'),
('LEADER_FALAMAR', 'KIND_LEADER'),
('LEADER_HANNAH', 'KIND_LEADER'),
('SLTH_TRAIT_CIVILIZATION_BUILDING_HARBOR_LANUN', 'KIND_TRAIT'),
('SLTH_TRAIT_SEAFARING', 'KIND_TRAIT'),
('SLTH_TRAIT_CIVILIZATION_UNIT_BLACK_WIND', 'KIND_TRAIT'),
('SLTH_TRAIT_CIVILIZATION_UNIT_GUYBRUSH', 'KIND_TRAIT'),
('SLTH_TRAIT_CIVILIZATION_UNIT_BOARDING_PARTY', 'KIND_TRAIT'),
('SLTH_TRAIT_CIVILIZATION_UNIT_WAR_TORTOISE', 'KIND_TRAIT'),
('SLTH_TRAIT_CIVILIZATION_UNIT_PIRATE', 'KIND_TRAIT'),
('SLTH_UNIT_BLACK_WIND', 'KIND_UNIT'),
('SLTH_UNIT_GUYBRUSH', 'KIND_UNIT'),
('SLTH_UNIT_BOARDING_PARTY', 'KIND_UNIT'),
('SLTH_UNIT_WAR_TORTOISE', 'KIND_UNIT'),
('SLTH_UNIT_PIRATE', 'KIND_UNIT'),
('SLTH_BUILDING_HARBOR_LANUN', 'KIND_BUILDING');