INSERT INTO Requirements(RequirementId, RequirementType) VALUES
('REQUIRES_PLOT_ADJACENT_TO_CITY_CENTER', 'REQUIREMENT_PLOT_ADJACENT_DISTRICT_TYPE_MATCHES');

INSERT INTO RequirementArguments(RequirementId, Name, Value) VALUES
('REQUIRES_PLOT_ADJACENT_TO_CITY_CENTER', 'DistrictType', 'DISTRICT_CITY_CENTER');

INSERT INTO Modifiers(ModifierId, ModifierType, OwnerRequirementSetId, SubjectRequirementSetId) VALUES
('AGENDA_MODIFIER_CITIES_NEAR_HILLS', 'MODIFIER_PLAYER_DIPLOMACY_AGENDA_ETHIOPIAN_HIGHLANDS', 'ON_TURN_STARTED', 'PLAYER_IS_MAJOR_CIV');

INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
('AGENDA_MODIFIER_CITIES_NEAR_HILLS', 'StatementKey', 'LOC_PLACEHOLDER');

INSERT INTO ModifierStrings(ModifierId, Context, Text) VALUES
('AGENDA_MODIFIER_CITIES_NEAR_HILLS', 'Sample', 'LOC_TOOLTIP_SAMPLE_DIPLOMACY_ALL');
