INSERT INTO Types(Type, Kind) VALUES
('BUILDING_HALICARNASSUS_MAUSOLEUM', 'KIND_BUILDING');

INSERT INTO RequirementSets(RequirementSetId, RequirementSetType) VALUES
('CITY_HAS_CAMPUS_MACEDON', 'REQUIREMENTSET_TEST_ALL'),
('CITY_HAS_THEATER_DISTRICT_MACEDON', 'REQUIREMENTSET_TEST_ALL');

INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('CITY_HAS_CAMPUS_MACEDON', 'REQUIRES_CITY_HAS_CAMPUS'),
('CITY_HAS_THEATER_DISTRICT_MACEDON', 'REQUIRES_CITY_HAS_THEATER_DISTRICT');

INSERT INTO Modifiers(ModifierId, ModifierType) VALUES
('TRAIT_TOWORLDSEND_NO_WAR_WEARINESS', 'MODIFIER_PLAYER_ADJUST_WAR_WEARINESS');

INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
('TRAIT_TOWORLDSEND_NO_WAR_WEARINESS', 'Amount', '-100'),
('TRAIT_TOWORLDSEND_NO_WAR_WEARINESS', 'Overall', 'true');
