------- ELF
INSERT INTO UnitAbilities(UnitAbilityType, Name, Description, Inactive, Permanent) VALUES
('ELF_RACIAL_STRENGTH_ON_FOREST', 'LOC_SLTH_ELF_ABILITY_FEATUREATTACKS_NAME', 'LOC_ELF_ABILITY_FEATUREATTACKS_DESCRIPTION', '1', '1'),
('ELF_RACIAL_MOVEMENT_ON_FOREST', 'LOC_SLTH_ELF_ABILITY_FEATUREDOUBLEMOVES_NAME', 'LOC_ELF_ABILITY_FEATUREDOUBLEMOVES_DESCRIPTION', '1', '1'),
('ELF_STRENGTH_ON_FORESTED', 'LOC_SLTH_ELF_ABILITY_FEATUREATTACKS_NAME', 'LOC_ELF_ABILITY_FEATUREATTACKS_DESCRIPTION', '1', '1'),
('ELF_MOVEMENT_ON_FORESTED', 'LOC_SLTH_ELF_ABILITY_FEATUREDOUBLEMOVES_NAME', 'LOC_ELF_ABILITY_FEATUREDOUBLEMOVES_DESCRIPTION', '1', '1');

INSERT INTO UnitAbilityModifiers(UnitAbilityType, ModifierId) VALUES
('ELF_RACIAL_STRENGTH_ON_FOREST', 'MODIFIER_ELF_ABILITY_FEATUREATTACKS_FEATURE_FOREST'),
('ELF_RACIAL_STRENGTH_ON_FOREST', 'MODIFIER_ELF_ABILITY_FEATUREATTACKS_FEATURE_FOREST_ANCIENT'),
('ELF_RACIAL_MOVEMENT_ON_FOREST', 'MODIFIER_ELF_ABILITY_FEATUREDOUBLEMOVES_FOREST'),
('ELF_STRENGTH_ON_FORESTED', 'MODIFIER_ELF_ABILITY_FEATUREATTACKS_FEATURE_FOREST'),
('ELF_STRENGTH_ON_FORESTED', 'MODIFIER_ELF_ABILITY_FEATUREATTACKS_FEATURE_FOREST_ANCIENT'),
('ELF_MOVEMENT_ON_FORESTED', 'MODIFIER_ELF_ABILITY_FEATUREDOUBLEMOVES_FOREST');

INSERT INTO Modifiers(ModifierId, ModifierType, RunOnce, Permanent, SubjectRequirementSetId) VALUES
('MODIFIER_ELF_ABILITY_FEATUREATTACKS_FEATURE_FOREST', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', '0', '0', 'ELF_ABILITY_FEATUREATTACKS_REQS_FEATURE_FOREST'),
('MODIFIER_ELF_ABILITY_FEATUREATTACKS_FEATURE_FOREST_ANCIENT', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', '0', '0', 'ELF_ABILITY_FEATUREATTACKS_REQS_FEATURE_FOREST_ANCIENT'),
('MODIFIER_ELF_ABILITY_FEATUREDOUBLEMOVES_FOREST', 'MODIFIER_PLAYER_UNIT_ADJUST_MOVEMENT', '0', '0', 'ELF_ABILITY_FEATUREDOUBLEMOVES_FOREST_REQS');

INSERT INTO ModifierArguments(ModifierId, Name, Type, Value) VALUES
('MODIFIER_ELF_ABILITY_FEATUREATTACKS_FEATURE_FOREST', 'Amount', 'ARGTYPE_IDENTITY', '10'),
('MODIFIER_ELF_ABILITY_FEATUREATTACKS_FEATURE_FOREST_ANCIENT', 'Amount', 'ARGTYPE_IDENTITY', '10'),
('MODIFIER_ELF_ABILITY_FEATUREDOUBLEMOVES_FOREST', 'Amount', 'ARGTYPE_IDENTITY', '1');

INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('ELF_ABILITY_FEATUREATTACKS_REQS_FEATURE_FOREST', 'PLAYER_IS_ATTACKER_REQUIREMENTS'),
('ELF_ABILITY_FEATUREATTACKS_REQS_FEATURE_FOREST', 'PLOT_IS_FOREST_REQUIREMENT'),
('ELF_ABILITY_FEATUREATTACKS_REQS_FEATURE_FOREST_ANCIENT', 'PLAYER_IS_ATTACKER_REQUIREMENTS'),
('ELF_ABILITY_FEATUREATTACKS_REQS_FEATURE_FOREST_ANCIENT', 'PLOT_IS_ANCIENT_FOREST_REQUIREMENT'),
('ELF_ABILITY_FEATUREDOUBLEMOVES_FOREST_REQS', 'PLOT_IS_FOREST_REQUIREMENT'),
('ELF_ABILITY_FEATUREDOUBLEMOVES_FOREST_REQS', 'PLOT_IS_ANCIENT_FOREST_REQUIREMENT');

INSERT INTO RequirementSets(RequirementSetId, RequirementSetType) VALUES
('ELF_ABILITY_FEATUREATTACKS_REQS_FEATURE_FOREST', 'REQUIREMENTSET_TEST_ALL'),
('ELF_ABILITY_FEATUREATTACKS_REQS_FEATURE_FOREST_ANCIENT', 'REQUIREMENTSET_TEST_ALL'),
('ELF_ABILITY_FEATUREDOUBLEMOVES_FOREST_REQS', 'REQUIREMENTSET_TEST_ANY');

INSERT INTO TypeTags(Type, Tag) VALUES
('ELF_RACIAL_STRENGTH_ON_FOREST', 'CAN_BE_RACIALIZED'),
('ELF_RACIAL_MOVEMENT_ON_FOREST', 'CAN_BE_RACIALIZED'),
('ELF_STRENGTH_ON_FORESTED', 'RACE_ELVEN'),
('ELF_MOVEMENT_ON_FORESTED', 'RACE_ELVEN');

INSERT INTO ModifierStrings(ModifierId, Context, Text) VALUES
('MODIFIER_ELF_ABILITY_FEATUREATTACKS_FEATURE_FOREST', 'Preview', 'LOC_ELF_ABILITY_FEATUREATTACKS_FEATURE_FOREST_PREVIEW');

INSERT INTO Types(Type, Kind) VALUES
('ELF_RACIAL_STRENGTH_ON_FOREST', 'KIND_ABILITY'),
('ELF_RACIAL_MOVEMENT_ON_FOREST', 'KIND_ABILITY'),
('ELF_STRENGTH_ON_FORESTED', 'KIND_ABILITY'),
('ELF_MOVEMENT_ON_FORESTED', 'KIND_ABILITY');

-------- DWARF
INSERT INTO UnitAbilities(UnitAbilityType, Name, Description, Inactive, Permanent) VALUES
('DWARF_ABILITY_HILLS_DOUBLE_MOVE', 'LOC_SLTH_DWARF_ABILITY_HILLS_DOUBLE_MOVE_NAME', 'LOC_DWARF_ABILITY_HILLS_DOUBLE_MOVE_DESCRIPTION', '1', '1'),
('INHERENT_DWARF_ABILITY_HILLS_DOUBLE_MOVE', 'LOC_SLTH_DWARF_ABILITY_HILLS_DOUBLE_MOVE_NAME', 'LOC_DWARF_ABILITY_HILLS_DOUBLE_MOVE_DESCRIPTION', '0', '1');

INSERT INTO UnitAbilityModifiers(UnitAbilityType, ModifierId) VALUES
('DWARF_ABILITY_HILLS_DOUBLE_MOVE', 'HILLS_DOUBLE_MOVE_MODIFIER'),
('INHERENT_DWARF_ABILITY_HILLS_DOUBLE_MOVE', 'HILLS_DOUBLE_MOVE_MODIFIER');

INSERT INTO Modifiers(ModifierId, ModifierType, RunOnce, Permanent, SubjectRequirementSetId) VALUES
('HILLS_DOUBLE_MOVE_MODIFIER', 'MODIFIER_PLAYER_UNIT_ADJUST_MOVEMENT', '0', '0', 'ROUGH_RIDER_HILL_TERRAIN_REQUIREMENTS');

INSERT INTO ModifierArguments(ModifierId, Name, Type, Value) VALUES
('HILLS_DOUBLE_MOVE_MODIFIER', 'Amount', 'ARGTYPE_IDENTITY', '1');

INSERT INTO TypeTags(Type, Tag) VALUES
('DWARF_ABILITY_HILLS_DOUBLE_MOVE', 'CAN_BE_RACIALIZED'),
('INHERENT_DWARF_ABILITY_HILLS_DOUBLE_MOVE', 'RACE_DWARVEN');

INSERT INTO Types(Type, Kind) VALUES
('DWARF_ABILITY_HILLS_DOUBLE_MOVE', 'KIND_ABILITY'),
('INHERENT_DWARF_ABILITY_HILLS_DOUBLE_MOVE', 'KIND_ABILITY');

-------- DEMON
INSERT INTO UnitAbilities(UnitAbilityType, Name, Description, Inactive, Permanent) VALUES
('DEMON_ABILITY_HELL_TERRAIN_STRENGTH', 'LOC_SLTH_DEMON_ABILITY_HELL_TERRAIN_STRENGTH_NAME', 'LOC_DEMON_ABILITY_HELL_TERRAIN_STRENGTH_DESCRIPTION', '1', '1'),
('ABILITY_DEMON', 'LOC_SLTH_DEMON_ABILITY_HELL_TERRAIN_STRENGTH_NAME', 'LOC_DEMON_ABILITY_HELL_TERRAIN_STRENGTH_DESCRIPTION', '0', '1');

INSERT INTO UnitAbilityModifiers(UnitAbilityType, ModifierId) VALUES
('DEMON_ABILITY_HELL_TERRAIN_STRENGTH', 'MODIFIER_DEMON_ABILITY_HELL_TERRAIN_STRENGTH'),
('ABILITY_DEMON', 'MODIFIER_DEMON_ABILITY_HELL_TERRAIN_STRENGTH');

INSERT INTO Modifiers(ModifierId, ModifierType, RunOnce, Permanent, SubjectRequirementSetId) VALUES
('MODIFIER_DEMON_ABILITY_HELL_TERRAIN_STRENGTH', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', '0', '0', 'DEMON_ABILITY_TERRAIN_REQS');

INSERT INTO ModifierArguments(ModifierId, Name, Type, Value) VALUES
('MODIFIER_DEMON_ABILITY_HELL_TERRAIN_STRENGTH', 'Amount', 'ARGTYPE_IDENTITY', '10');

INSERT INTO RequirementSets(RequirementSetId, RequirementSetType) VALUES
('DEMON_ABILITY_TERRAIN_REQS', 'REQUIREMENTSET_TEST_ANY');

INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('DEMON_ABILITY_TERRAIN_REQS', 'PLOT_IS_BROKEN_LANDS'),
('DEMON_ABILITY_TERRAIN_REQS', 'PLOT_IS_FIELDS_OF_PERDITION'),
('DEMON_ABILITY_TERRAIN_REQS', 'PLOT_IS_BURNING_SANDS'),
('DEMON_ABILITY_TERRAIN_REQS', 'PLOT_IS_BROKEN_LANDS_HILLS'),
('DEMON_ABILITY_TERRAIN_REQS', 'PLOT_IS_FIELDS_OF_PERDITION_HILLS'),
('DEMON_ABILITY_TERRAIN_REQS', 'PLOT_IS_BURNING_SANDS_HILLS');

INSERT INTO Requirements(RequirementId, RequirementType, ProgressWeight) VALUES
('PLOT_IS_BROKEN_LANDS', 'REQUIREMENT_PLOT_TERRAIN_TYPE_MATCHES', '0'),
('PLOT_IS_FIELDS_OF_PERDITION', 'REQUIREMENT_PLOT_TERRAIN_TYPE_MATCHES', '0'),
('PLOT_IS_BURNING_SANDS', 'REQUIREMENT_PLOT_TERRAIN_TYPE_MATCHES', '0'),
('PLOT_IS_BROKEN_LANDS_HILLS', 'REQUIREMENT_PLOT_TERRAIN_TYPE_MATCHES', '0'),
('PLOT_IS_FIELDS_OF_PERDITION_HILLS', 'REQUIREMENT_PLOT_TERRAIN_TYPE_MATCHES', '0'),
('PLOT_IS_BURNING_SANDS_HILLS', 'REQUIREMENT_PLOT_TERRAIN_TYPE_MATCHES', '0');

INSERT INTO RequirementArguments(RequirementId, Name, Type, Value) VALUES
('PLOT_IS_BROKEN_LANDS', 'TerrainType', 'ARGTYPE_IDENTITY', 'TERRAIN_BROKEN_LANDS'),
('PLOT_IS_FIELDS_OF_PERDITION', 'TerrainType', 'ARGTYPE_IDENTITY', 'TERRAIN_FIELDS_OF_PERDITION'),
('PLOT_IS_BURNING_SANDS', 'TerrainType', 'ARGTYPE_IDENTITY', 'TERRAIN_BURNING_SANDS'),
('PLOT_IS_BROKEN_LANDS_HILLS', 'TerrainType', 'ARGTYPE_IDENTITY', 'TERRAIN_BROKEN_LANDS_HILLS'),
('PLOT_IS_FIELDS_OF_PERDITION_HILLS', 'TerrainType', 'ARGTYPE_IDENTITY', 'TERRAIN_FIELDS_OF_PERDITION_HILLS'),
('PLOT_IS_BURNING_SANDS_HILLS', 'TerrainType', 'ARGTYPE_IDENTITY', 'TERRAIN_BURNING_SANDS_HILLS');

INSERT INTO ModifierStrings(ModifierId, Context, Text) VALUES
('MODIFIER_DEMON_ABILITY_HELL_TERRAIN_STRENGTH', 'Preview', 'LOC_SLTH_DEMON_ABILITY_HELL_TERRAIN_STRENGTH_PREVIEW');

INSERT INTO TypeTags(Type, Tag) VALUES
('DEMON_ABILITY_HELL_TERRAIN_STRENGTH', 'CAN_BE_RACIALIZED'),
('ABILITY_DEMON', 'RACE_DEMON');

INSERT INTO Types(Type, Kind) VALUES
('DEMON_ABILITY_HELL_TERRAIN_STRENGTH', 'KIND_ABILITY'),
('ABILITY_DEMON', 'KIND_ABILITY');

-------- FROSTLING
INSERT INTO UnitAbilities(UnitAbilityType, Name, Description, Inactive, Permanent) VALUES
('INHERENT_FROSTLING_ABILITY_ICY_STRENGTH', 'LOC_SLTH_FROSTLING_ABILITY_TERRAIN_STRENGTH_NAME', 'LOC_FROSTLING_ABILITY_TERRAIN_STRENGTH_DESCRIPTION', '0', '1');

INSERT INTO UnitAbilityModifiers(UnitAbilityType, ModifierId) VALUES
('INHERENT_FROSTLING_ABILITY_ICY_STRENGTH', 'MODIFIER_FROSTLING_ABILITY_TERRAIN_STRENGTH_SNOW'),
('INHERENT_FROSTLING_ABILITY_ICY_STRENGTH', 'MODIFIER_FROSTLING_ABILITY_TERRAIN_STRENGTH_TUNDRA'),
('INHERENT_FROSTLING_ABILITY_ICY_STRENGTH', 'MODIFIER_FROSTLING_ABILITY_TERRAIN_WEAKNESS_DESERT'),
('INHERENT_FROSTLING_ABILITY_ICY_STRENGTH', 'MODIFIER_COLD_DAMAGE_MR_CHECKER_1'),
('INHERENT_FROSTLING_ABILITY_ICY_STRENGTH', 'MODIFIER_COLD_DAMAGE_RACIAL_CHECKER_1'),
('INHERENT_FROSTLING_ABILITY_ICY_STRENGTH', 'MODIFIER_COLD_DAMAGE_STONESKIN_CHECKER_1'),
-- ('INHERENT_FROSTLING_ABILITY_ICY_STRENGTH', 'MODIFIER_COLD_DAMAGE_IS_ELF_CHECKER_MORE_1'),
('INHERENT_FROSTLING_ABILITY_ICY_STRENGTH', 'MODIFIER_COLD_DAMAGE_SPECIFIC_RESIST_CHECKER_1');


INSERT INTO Modifiers(ModifierId, ModifierType, RunOnce, Permanent, SubjectRequirementSetId) VALUES
('MODIFIER_FROSTLING_ABILITY_TERRAIN_STRENGTH_SNOW', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', '0', '0', 'FROSTLING_ABILITY_TERRAIN_STRENGTH_SNOW_REQS'),
('MODIFIER_FROSTLING_ABILITY_TERRAIN_STRENGTH_TUNDRA', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', '0', '0', 'PLOT_HAS_TUNDRA_REQUIREMENTS'),
('MODIFIER_FROSTLING_ABILITY_TERRAIN_WEAKNESS_DESERT', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', '0', '0', 'FROSTLING_ABILITY_TERRAIN_WEAKNESS_DESERT_REQS');

INSERT INTO ModifierArguments(ModifierId, Name, Type, Value) VALUES
('MODIFIER_FROSTLING_ABILITY_TERRAIN_STRENGTH_SNOW', 'Amount', 'ARGTYPE_IDENTITY', '25'),
('MODIFIER_FROSTLING_ABILITY_TERRAIN_STRENGTH_TUNDRA', 'Amount', 'ARGTYPE_IDENTITY', '10'),
('MODIFIER_FROSTLING_ABILITY_TERRAIN_WEAKNESS_DESERT', 'Amount', 'ARGTYPE_IDENTITY', '-25');

INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('FROSTLING_ABILITY_TERRAIN_STRENGTH_SNOW_REQS', 'SLTH_PLOT_IS_SNOW'),
('FROSTLING_ABILITY_TERRAIN_STRENGTH_SNOW_REQS', 'SLTH_PLOT_IS_SNOW_HILLS'),
('FROSTLING_ABILITY_TERRAIN_WEAKNESS_DESERT_REQS', 'REQUIRES_PLOT_HAS_DESERT'),
('FROSTLING_ABILITY_TERRAIN_WEAKNESS_DESERT_REQS', 'REQUIRES_PLOT_HAS_DESERT_HILLS');

INSERT INTO RequirementSets(RequirementSetId, RequirementSetType) VALUES
('FROSTLING_ABILITY_TERRAIN_STRENGTH_SNOW_REQS', 'REQUIREMENTSET_TEST_ANY'),
('FROSTLING_ABILITY_TERRAIN_WEAKNESS_DESERT_REQS', 'REQUIREMENTSET_TEST_ANY');

INSERT INTO Requirements(RequirementId, RequirementType, ProgressWeight) VALUES
('SLTH_PLOT_IS_SNOW', 'REQUIREMENT_PLOT_TERRAIN_TYPE_MATCHES', '0'),
('SLTH_PLOT_IS_SNOW_HILLS', 'REQUIREMENT_PLOT_TERRAIN_TYPE_MATCHES', '0');

INSERT INTO RequirementArguments(RequirementId, Name, Type, Value) VALUES
('SLTH_PLOT_IS_SNOW', 'TerrainType', 'ARGTYPE_IDENTITY', 'TERRAIN_SNOW'),
('SLTH_PLOT_IS_SNOW_HILLS', 'TerrainType', 'ARGTYPE_IDENTITY', 'TERRAIN_SNOW_HILLS');

INSERT INTO ModifierStrings(ModifierId, Context, Text) VALUES
('MODIFIER_FROSTLING_ABILITY_TERRAIN_STRENGTH_SNOW', 'Preview', 'LOC_FROSTLING_ABILITY_TERRAIN_STRENGTH_SNOW_PREVIEW'),
('MODIFIER_FROSTLING_ABILITY_TERRAIN_STRENGTH_TUNDRA', 'Preview', 'LOC_FROSTLING_ABILITY_TERRAIN_STRENGTH_TUNDRA_PREVIEW'),
('MODIFIER_FROSTLING_ABILITY_TERRAIN_WEAKNESS_DESERT', 'Preview', 'LOC_FROSTLING_ABILITY_TERRAIN_STRENGTH_DESERT_PREVIEW');

INSERT INTO TypeTags(Type, Tag) VALUES
('INHERENT_FROSTLING_ABILITY_ICY_STRENGTH', 'RACE_FROSTLING');

INSERT INTO Types(Type, Kind) VALUES
('INHERENT_FROSTLING_ABILITY_ICY_STRENGTH', 'KIND_ABILITY');

-------- LIZARDMEN
INSERT INTO UnitAbilities(UnitAbilityType, Name, Description, Inactive, Permanent) VALUES
('INHERENT_LIZARDMAN_ABILITY_MARSH_STRENGTH', 'LOC_SLTH_LIZARDMAN_ABILITY_MARSH_STRENGTH_NAME', 'LOC_LIZARDMAN_ABILITY_MARSH_STRENGTH_DESCRIPTION', '0', '1');

INSERT INTO UnitAbilityModifiers(UnitAbilityType, ModifierId) VALUES
('INHERENT_LIZARDMAN_ABILITY_MARSH_STRENGTH', 'MODIFIER_LIZARDMAN_ABILITY_MARSH_STRENGTH_MARSH'),
('INHERENT_LIZARDMAN_ABILITY_MARSH_STRENGTH', 'MODIFIER_LIZARDMAN_ABILITY_MARSH_DOUBLE_MOVES_MARSH');

INSERT INTO Modifiers(ModifierId, ModifierType, RunOnce, Permanent, SubjectRequirementSetId) VALUES
('MODIFIER_LIZARDMAN_ABILITY_MARSH_STRENGTH_MARSH', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', '0', '0', 'SLTH_PLOT_IS_MARSH_REQS'),
('MODIFIER_LIZARDMAN_ABILITY_MARSH_DOUBLE_MOVES_MARSH', 'MODIFIER_PLAYER_UNIT_ADJUST_MOVEMENT', '0', '0', 'SLTH_PLOT_IS_MARSH_REQS');

INSERT INTO ModifierArguments(ModifierId, Name, Type, Value) VALUES
('MODIFIER_LIZARDMAN_ABILITY_MARSH_STRENGTH_MARSH', 'Amount', 'ARGTYPE_IDENTITY', '10'),
('MODIFIER_LIZARDMAN_ABILITY_MARSH_DOUBLE_MOVES_MARSH', 'Amount', 'ARGTYPE_IDENTITY', '1');

INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('SLTH_PLOT_IS_MARSH_REQS', 'REQUIRES_PLOT_HAS_MARSH');

INSERT INTO RequirementSets(RequirementSetId, RequirementSetType) VALUES
('SLTH_PLOT_IS_MARSH_REQS', 'REQUIREMENTSET_TEST_ANY');

INSERT INTO ModifierStrings(ModifierId, Context, Text) VALUES
('MODIFIER_LIZARDMAN_ABILITY_MARSH_STRENGTH_MARSH', 'Preview', 'LOC_LIZARDMAN_ABILITY_MARSH_STRENGTH_MARSH_PREVIEW');

INSERT INTO TypeTags(Type, Tag) VALUES
('INHERENT_LIZARDMAN_ABILITY_MARSH_STRENGTH', 'RACE_LIZARDMEN');

INSERT INTO Types(Type, Kind) VALUES
('INHERENT_LIZARDMAN_ABILITY_MARSH_STRENGTH', 'KIND_ABILITY');

-------- ORC
INSERT INTO UnitAbilities(UnitAbilityType, Name, Description, Inactive, Permanent) VALUES
('ORC_ABILITY_JUNGLE_ATTACKS', 'LOC_SLTH_ORC_ABILITY_JUNGLE_ATTACKS_NAME', 'LOC_ORC_ABILITY_JUNGLE_ATTACKS_DESCRIPTION', '1', '1'),
('INHERENT_ORC_ABILITY_JUNGLE_ATTACKS', 'LOC_SLTH_ORC_ABILITY_JUNGLE_ATTACKS_NAME', 'LOC_ORC_ABILITY_JUNGLE_ATTACKS_DESCRIPTION', '0', '1');

INSERT INTO UnitAbilityModifiers(UnitAbilityType, ModifierId) VALUES
('ORC_ABILITY_JUNGLE_ATTACKS', 'MODIFIER_ORC_ABILITY_JUNGLE_ATTACKS_FEATURE_JUNGLE'),
('INHERENT_ORC_ABILITY_JUNGLE_ATTACKS', 'MODIFIER_ORC_ABILITY_JUNGLE_ATTACKS_FEATURE_JUNGLE');

INSERT INTO Modifiers(ModifierId, ModifierType, RunOnce, Permanent, SubjectRequirementSetId) VALUES
('MODIFIER_ORC_ABILITY_JUNGLE_ATTACKS_FEATURE_JUNGLE', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', '0', '0', 'ORC_ABILITY_JUNGLE_ATTACKS_REQS_FEATURE_JUNGLE');

INSERT INTO ModifierArguments(ModifierId, Name, Type, Value) VALUES
('MODIFIER_ORC_ABILITY_JUNGLE_ATTACKS_FEATURE_JUNGLE', 'Amount', 'ARGTYPE_IDENTITY', '10');

INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('ORC_ABILITY_JUNGLE_ATTACKS_REQS_FEATURE_JUNGLE', 'PLAYER_IS_ATTACKER_REQUIREMENTS'),
('ORC_ABILITY_JUNGLE_ATTACKS_REQS_FEATURE_JUNGLE', 'REQUIRES_PLOT_HAS_JUNGLE');

INSERT INTO RequirementSets(RequirementSetId, RequirementSetType) VALUES
('ORC_ABILITY_JUNGLE_ATTACKS_REQS_FEATURE_JUNGLE', 'REQUIREMENTSET_TEST_ALL');

INSERT INTO ModifierStrings(ModifierId, Context, Text) VALUES
('MODIFIER_ORC_ABILITY_JUNGLE_ATTACKS_FEATURE_JUNGLE', 'Preview', 'LOC_ORC_ABILITY_JUNGLE_ATTACKS_FEATURE_JUNGLE_PREVIEW');

INSERT INTO TypeTags(Type, Tag) VALUES
('INHERENT_ORC_ABILITY_JUNGLE_ATTACKS', 'RACE_ORCISH'),
('ORC_ABILITY_JUNGLE_ATTACKS', 'CAN_BE_RACIALIZED');

INSERT INTO Types(Type, Kind) VALUES
('ORC_ABILITY_JUNGLE_ATTACKS', 'KIND_ABILITY'),
('INHERENT_ORC_ABILITY_JUNGLE_ATTACKS', 'KIND_ABILITY');

-------- WINTERBORN
INSERT INTO UnitAbilities(UnitAbilityType, Name, Description, Inactive, Permanent) VALUES
('WINTERBORN_ABILITY_TUNDRA_SNOW_STRENGTH', 'LOC_SLTH_WINTERBORN_ABILITY_TUNDRA_SNOW_STRENGTH_NAME', 'LOC_WINTERBORN_ABILITY_TUNDRA_SNOW_STRENGTH_DESCRIPTION', '1', '1'),
('INHERENT_WINTERBORN_ABILITY_TUNDRA_SNOW_STRENGTH', 'LOC_SLTH_WINTERBORN_ABILITY_TUNDRA_SNOW_STRENGTH_NAME', 'LOC_WINTERBORN_ABILITY_TUNDRA_SNOW_STRENGTH_DESCRIPTION', '0', '1');

INSERT INTO UnitAbilityModifiers(UnitAbilityType, ModifierId) VALUES
('WINTERBORN_ABILITY_TUNDRA_SNOW_STRENGTH', 'MODIFIER_WINTERBORN_ABILITY_TUNDRA_SNOW_STRENGTH_SNOW'),
('INHERENT_WINTERBORN_ABILITY_TUNDRA_SNOW_STRENGTH', 'MODIFIER_WINTERBORN_ABILITY_TUNDRA_SNOW_STRENGTH_SNOW');

INSERT INTO Modifiers(ModifierId, ModifierType, RunOnce, Permanent, SubjectRequirementSetId) VALUES
('MODIFIER_WINTERBORN_ABILITY_TUNDRA_SNOW_STRENGTH_SNOW', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', '0', '0', 'SLTH_PLOT_IS_SNOW_OR_TUNDRA');

INSERT INTO ModifierArguments(ModifierId, Name, Type, Value) VALUES
('MODIFIER_WINTERBORN_ABILITY_TUNDRA_SNOW_STRENGTH_SNOW', 'Amount', 'ARGTYPE_IDENTITY', '10');

INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('SLTH_PLOT_IS_SNOW_OR_TUNDRA', 'SLTH_PLOT_IS_SNOW'),
('SLTH_PLOT_IS_SNOW_OR_TUNDRA', 'SLTH_PLOT_IS_SNOW_HILLS'),
('SLTH_PLOT_IS_SNOW_OR_TUNDRA', 'REQUIRES_PLOT_HAS_TUNDRA'),
('SLTH_PLOT_IS_SNOW_OR_TUNDRA', 'REQUIRES_PLOT_HAS_TUNDRA_HILLS');

INSERT INTO RequirementSets(RequirementSetId, RequirementSetType) VALUES
('SLTH_PLOT_IS_SNOW_OR_TUNDRA', 'REQUIREMENTSET_TEST_ANY');

INSERT INTO ModifierStrings(ModifierId, Context, Text) VALUES
('MODIFIER_WINTERBORN_ABILITY_TUNDRA_SNOW_STRENGTH_SNOW', 'Preview', 'LOC_WINTERBORN_ABILITY_TUNDRA_SNOW_STRENGTH_SNOW_PREVIEW');

INSERT INTO TypeTags(Type, Tag) VALUES
('WINTERBORN_ABILITY_TUNDRA_SNOW_STRENGTH', 'CAN_BE_RACIALIZED'),
('INHERENT_WINTERBORN_ABILITY_TUNDRA_SNOW_STRENGTH', 'RACE_WINTERBORN');

INSERT INTO Types(Type, Kind) VALUES
('WINTERBORN_ABILITY_TUNDRA_SNOW_STRENGTH', 'KIND_ABILITY'),
('INHERENT_WINTERBORN_ABILITY_TUNDRA_SNOW_STRENGTH', 'KIND_ABILITY');

------ Angel -----

INSERT INTO UnitAbilities(UnitAbilityType, Name, Description, Inactive, Permanent) VALUES
('ABILITY_ANGEL', 'LOC_SLTH_ABILITY_ANGEL_NAME', 'LOC_DEMON_ABILITY_ANGEL_DESCRIPTION', '0', '1');

INSERT INTO TypeTags(Type, Tag) VALUES
('ABILITY_ANGEL', 'RACE_ANGEL');

INSERT INTO Types(Type, Kind) VALUES
('ABILITY_ANGEL', 'KIND_ABILITY');

INSERT INTO UnitAbilities(UnitAbilityType, Name, Description, Inactive, Permanent) VALUES
('ABILITY_UNDEAD', 'LOC_SLTH_ABILITY_UNDEAD_NAME', 'LOC_ABILITY_UNDEAD_DESCRIPTION', '0', '1');

INSERT INTO TypeTags(Type, Tag) VALUES
('ABILITY_UNDEAD', 'IS_UNDEAD');

INSERT INTO Types(Type, Kind) VALUES
('ABILITY_UNDEAD', 'KIND_ABILITY');

INSERT INTO UnitAbilities(UnitAbilityType, Name, Description, Inactive, Permanent) VALUES
('ABILITY_INHERENT_HUMAN', 'LOC_NULL', 'LOC_NULL', '0', '1'),
('ABILITY_RACIAL_HUMAN', 'LOC_NULL', 'LOC_NULL', '1', '1');

INSERT INTO TypeTags(Type, Tag) VALUES
('ABILITY_INHERENT_HUMAN', 'RACE_HUMAN'),
('ABILITY_RACIAL_HUMAN', 'CAN_BE_RACIALIZED');

INSERT INTO Types(Type, Kind) VALUES
('ABILITY_INHERENT_HUMAN', 'KIND_ABILITY'),
('ABILITY_RACIAL_HUMAN', 'KIND_ABILITY');

-- alive class (for regeneration, haste etc)
INSERT INTO Tags(Tag, Vocabulary) VALUES
('IS_ALIVE', 'ABILITY_CLASS');

INSERT INTO TypeTags (Type, Tag) VALUES
('UNIT_SETTLER', 'IS_ALIVE'),
('UNIT_BUILDER', 'IS_ALIVE'),
('UNIT_TRADER', 'IS_ALIVE'),
('UNIT_GREAT_GENERAL', 'IS_ALIVE'),
('UNIT_GREAT_ENGINEER', 'IS_ALIVE'),
('UNIT_GREAT_MERCHANT', 'IS_ALIVE'),
('UNIT_GREAT_PROPHET', 'IS_ALIVE'),
('UNIT_GREAT_SCIENTIST', 'IS_ALIVE'),
('UNIT_GREAT_WRITER', 'IS_ALIVE'),
('UNIT_GREAT_ARTIST', 'IS_ALIVE'),
('UNIT_WARRIOR', 'IS_ALIVE'),
('SLTH_UNIT_WIZARD', 'IS_ALIVE'),
('SLTH_UNIT_FIREBOW', 'IS_ALIVE'),
('SLTH_UNIT_CHANTER', 'IS_ALIVE'),
('SLTH_UNIT_GOVANNON', 'IS_ALIVE'),
('SLTH_UNIT_LOKI', 'IS_ALIVE'),
('SLTH_UNIT_MIMIC', 'IS_ALIVE'),
('SLTH_UNIT_COURTESAN', 'IS_ALIVE'),
('SLTH_UNIT_TASKMASTER', 'IS_ALIVE'),
('SLTH_UNIT_HARLEQUIN', 'IS_ALIVE'),
('SLTH_UNIT_FREAK', 'IS_ALIVE'),
('SLTH_UNIT_DEMAGOG', 'IS_ALIVE'),
('SLTH_UNIT_FLAGBEARER', 'IS_ALIVE'),
('SLTH_UNIT_DONAL', 'IS_ALIVE'),
('SLTH_UNIT_ACHERON', 'IS_ALIVE'),
('SLTH_UNIT_ARS', 'IS_ALIVE'),                  -- hmmm
('SLTH_UNIT_BUBOES', 'IS_ALIVE'),
('SLTH_UNIT_STEPHANOS', 'IS_ALIVE'),
('SLTH_UNIT_YERSINIA', 'IS_ALIVE'),
('SLTH_UNIT_GURID', 'IS_ALIVE'),
('SLTH_UNIT_MARGALARD', 'IS_ALIVE'),
('SLTH_UNIT_LEVIATHAN', 'IS_ALIVE'),
('SLTH_UNIT_MOKKA', 'IS_ALIVE'),
('SLTH_UNIT_TUMTUM', 'IS_ALIVE'),
('SLTH_UNIT_ORTHUS', 'IS_ALIVE'),
('SLTH_UNIT_FROSTLING', 'IS_ALIVE'),                -- are frostlings living? hmmm
('SLTH_UNIT_FROSTLING_ARCHER', 'IS_ALIVE'),
('SLTH_UNIT_FROSTLING_WOLF_RIDER', 'IS_ALIVE'),
('SLTH_UNIT_BABY_SPIDER', 'IS_ALIVE'),
('SLTH_UNIT_GIANT_SPIDER', 'IS_ALIVE'),
('SLTH_UNIT_BEAR', 'IS_ALIVE'),
('SLTH_UNIT_POLAR_BEAR', 'IS_ALIVE'),
('SLTH_UNIT_ELEPHANT', 'IS_ALIVE'),
('SLTH_UNIT_GIANT_TORTOISE', 'IS_ALIVE'),
('SLTH_UNIT_GORILLA', 'IS_ALIVE'),
('SLTH_UNIT_GRIFFON', 'IS_ALIVE'),
('SLTH_UNIT_KRAKEN', 'IS_ALIVE'),
('SLTH_UNIT_LION', 'IS_ALIVE'),
('SLTH_UNIT_SCORPION', 'IS_ALIVE'),
('SLTH_UNIT_SEA_SERPENT', 'IS_ALIVE'),
('SLTH_UNIT_MANTICORE', 'IS_ALIVE'),
('SLTH_UNIT_TIGER', 'IS_ALIVE'),
('SLTH_UNIT_WOLF', 'IS_ALIVE'),
('SLTH_UNIT_HILL_GIANT', 'IS_ALIVE'),
('SLTH_UNIT_SON_OF_THE_INFERNO', 'IS_ALIVE'),
('SLTH_UNIT_DISCIPLE_OF_ACHERON', 'IS_ALIVE'),
('SLTH_UNIT_RANTINE', 'IS_ALIVE'),
('SLTH_UNIT_WOLF_RIDER', 'IS_ALIVE'),
('SLTH_UNIT_OGRE', 'IS_ALIVE'),
('SLTH_UNIT_OGRE_WARCHIEF', 'IS_ALIVE'),
('SLTH_UNIT_GOBLIN', 'IS_ALIVE'),
('SLTH_UNIT_STONESKIN_OGRE', 'IS_ALIVE'),
('SLTH_UNIT_LIZARDMAN', 'IS_ALIVE'),
('SLTH_UNIT_LOSHA', 'IS_ALIVE'),                    -- vampires still get Body effects, not proper undead
('SLTH_UNIT_MOROI', 'IS_ALIVE'),
('SLTH_UNIT_BRUJAH', 'IS_ALIVE'),
('SLTH_UNIT_VAMPIRE', 'IS_ALIVE'),
('SLTH_UNIT_VAMPIRE_LORD', 'IS_ALIVE'),
('SLTH_UNIT_DWARVEN_SLINGER', 'IS_ALIVE'),
('SLTH_UNIT_DWARVEN_DRUID', 'IS_ALIVE'),
('SLTH_UNIT_BOAR_RIDER', 'IS_ALIVE'),
('SLTH_UNIT_DWARVEN_SHADOW', 'IS_ALIVE'),
('SLTH_UNIT_HORNGUARD', 'IS_ALIVE'),
('SLTH_UNIT_MAROS', 'IS_ALIVE'),
('SLTH_UNIT_MYCONID', 'IS_ALIVE'),
('SLTH_UNIT_TREBUCHET', 'IS_ALIVE'),
('SLTH_UNIT_DEVOUT', 'IS_ALIVE'),
('SLTH_UNIT_MONK', 'IS_ALIVE'),
('SLTH_UNIT_CORLINDALE', 'IS_ALIVE'),
('SLTH_UNIT_GILDEN', 'IS_ALIVE'),
('SLTH_UNIT_FYRDWELL', 'IS_ALIVE'),
('SLTH_UNIT_FLURRY', 'IS_ALIVE'),
('SLTH_UNIT_ALAZKAN', 'IS_ALIVE'),
('SLTH_UNIT_NYXKIN', 'IS_ALIVE'),
('SLTH_UNIT_ILLUSIONIST', 'IS_ALIVE'),
('SLTH_UNIT_DRAGON_SLAYER', 'IS_ALIVE'),
('SLTH_UNIT_LUONNOTAR', 'IS_ALIVE'),
('SLTH_UNIT_GRIGORI_MEDIC', 'IS_ALIVE'),
('SLTH_UNIT_MERCENARY_MOUNTED', 'IS_ALIVE'),
('SLTH_UNIT_MAGNADINE', 'IS_ALIVE'),
('SLTH_UNIT_CENTAUR_ARCHER', 'IS_ALIVE'),
('SLTH_UNIT_CENTAUR_CHARGER', 'IS_ALIVE'),
('SLTH_UNIT_CENTAUR', 'IS_ALIVE'),
('SLTH_UNIT_CENTAUR_LANCER', 'IS_ALIVE'),
('SLTH_UNIT_HERNE', 'IS_ALIVE'),
('SLTH_UNIT_EURABATRES', 'IS_ALIVE'),
('SLTH_UNIT_GUYBRUSH', 'IS_ALIVE'),
('SLTH_UNIT_BOARDING_PARTY', 'IS_ALIVE'),
('SLTH_UNIT_WAR_TORTOISE', 'IS_ALIVE'),
('SLTH_UNIT_PIRATE', 'IS_ALIVE'),
('SLTH_UNIT_TEUTORIX', 'IS_ALIVE'),
('SLTH_UNIT_LIGHTBRINGER', 'IS_ALIVE'),
('SLTH_UNIT_CAMEL_ARCHER', 'IS_ALIVE'),
('SLTH_UNIT_ABASHI', 'IS_ALIVE'),
('SLTH_UNIT_EATER_OF_DREAMS', 'IS_ALIVE'),
('SLTH_UNIT_MOBIUS_WITCH', 'IS_ALIVE'),
('SLTH_UNIT_REVELERS', 'IS_ALIVE'),
('SLTH_UNIT_RATHUS', 'IS_ALIVE'),
('SLTH_UNIT_GHOST', 'IS_ALIVE'),
('SLTH_UNIT_DIVIDED_SOUL', 'IS_ALIVE'),
('SLTH_UNIT_BATTLEMASTER', 'IS_ALIVE'),
('SLTH_UNIT_BISON_RIDER', 'IS_ALIVE'),
('SLTH_UNIT_BEASTMAN', 'IS_ALIVE'),
('SLTH_UNIT_SONS_OF_ASENA', 'IS_ALIVE'),
('SLTH_UNIT_LUCIAN', 'IS_ALIVE'),
('SLTH_UNIT_WILBOMAN', 'IS_ALIVE'),
('SLTH_UNIT_HIGH_PRIEST_OF_WINTER', 'IS_ALIVE'),
('SLTH_UNIT_DRIFA', 'IS_ALIVE'),
('SLTH_UNIT_ROYAL_GUARD', 'IS_ALIVE'),
('SLTH_UNIT_DISCIPLE_EMPYREAN', 'IS_ALIVE'),
('SLTH_UNIT_DISCIPLE_FELLOWSHIP_OF_LEAVES', 'IS_ALIVE'),
('SLTH_UNIT_DISCIPLE_OCTOPUS_OVERLORDS', 'IS_ALIVE'),
('SLTH_UNIT_DISCIPLE_RUNES_OF_KILMORPH', 'IS_ALIVE'),
('SLTH_UNIT_DISCIPLE_THE_ASHEN_VEIL', 'IS_ALIVE'),
('SLTH_UNIT_DISCIPLE_THE_ORDER', 'IS_ALIVE'),
('SLTH_UNIT_PRIEST_OF_WINTER', 'IS_ALIVE'),
('SLTH_UNIT_HIGH_PRIEST_OF_KILMORPH', 'IS_ALIVE'),
('SLTH_UNIT_HIGH_PRIEST_OF_THE_OVERLORDS', 'IS_ALIVE'),
('SLTH_UNIT_HIGH_PRIEST_OF_THE_ORDER', 'IS_ALIVE'),
('SLTH_UNIT_HIGH_PRIEST_OF_LEAVES', 'IS_ALIVE'),
('SLTH_UNIT_HIGH_PRIEST_OF_THE_EMPYREAN', 'IS_ALIVE'),
('SLTH_UNIT_HIGH_PRIEST_OF_THE_VEIL', 'IS_ALIVE'),
('SLTH_UNIT_LUNATIC', 'IS_ALIVE'),
('SLTH_UNIT_ARTHENDAIN', 'IS_ALIVE'),
('SLTH_UNIT_BAMBUR', 'IS_ALIVE'),
('SLTH_UNIT_PARAMANDER', 'IS_ALIVE'),
('SLTH_UNIT_DWARVEN_SOLDIER_RUNES', 'IS_ALIVE'),
('SLTH_UNIT_PRIEST_OF_KILMORPH', 'IS_ALIVE'),
('SLTH_UNIT_PRIEST_OF_THE_OVERLORDS', 'IS_ALIVE'),
('SLTH_UNIT_HEMAH', 'IS_ALIVE'),
('SLTH_UNIT_CRUSADER', 'IS_ALIVE'),
('SLTH_UNIT_PRIEST_OF_THE_ORDER', 'IS_ALIVE'),
('SLTH_UNIT_VALIN', 'IS_ALIVE'),
('SLTH_UNIT_PRIEST_OF_THE_VEIL', 'IS_ALIVE'),
('SLTH_UNIT_ROSIER', 'IS_ALIVE'),
('SLTH_UNIT_PRIEST_OF_LEAVES', 'IS_ALIVE'),
('SLTH_UNIT_FAWN', 'IS_ALIVE'),
('SLTH_UNIT_SATYR', 'IS_ALIVE'),
('SLTH_UNIT_KITHRA', 'IS_ALIVE'),
('SLTH_UNIT_YVAIN', 'IS_ALIVE'),
('SLTH_UNIT_PRIEST_OF_THE_EMPYREAN', 'IS_ALIVE'),
('SLTH_UNIT_RATHA', 'IS_ALIVE'),
('SLTH_UNIT_RADIANT_GUARD', 'IS_ALIVE'),
('SLTH_UNIT_CHALID', 'IS_ALIVE'),
('SLTH_UNIT_SHADOW', 'IS_ALIVE'),
('SLTH_UNIT_SHADOWRIDER', 'IS_ALIVE'),
('SLTH_UNIT_NIGHTWATCH', 'IS_ALIVE'),
('SLTH_UNIT_GIBBON', 'IS_ALIVE'),
('SLTH_UNIT_DRUID', 'IS_ALIVE'),
('SLTH_UNIT_PALADIN', 'IS_ALIVE'),
('SLTH_UNIT_ARCHER', 'IS_ALIVE'),
('SLTH_UNIT_JAVELIN_THROWER', 'IS_ALIVE'),
('SLTH_UNIT_ARQUEBUS', 'IS_ALIVE'),
('SLTH_UNIT_ASSASSIN', 'IS_ALIVE'),
('SLTH_UNIT_SWORDSMAN', 'IS_ALIVE'),
('SLTH_UNIT_CHAMPION', 'IS_ALIVE'),
('SLTH_UNIT_CHARIOT', 'IS_ALIVE'),
('SLTH_UNIT_CROSSBOWMAN', 'IS_ALIVE'),
('SLTH_UNIT_HAWK', 'IS_ALIVE'),
('SLTH_UNIT_HORSE_ARCHER', 'IS_ALIVE'),
('SLTH_UNIT_HORSEMAN', 'IS_ALIVE'),
('SLTH_UNIT_HUNTER', 'IS_ALIVE'),
('SLTH_UNIT_GARGOYLE', 'IS_ALIVE'),
('SLTH_UNIT_LONGBOWMAN', 'IS_ALIVE'),
('SLTH_UNIT_MARKSMAN', 'IS_ALIVE'),
('SLTH_UNIT_DUIN', 'IS_ALIVE'),
('SLTH_UNIT_RANGER', 'IS_ALIVE'),
('SLTH_UNIT_SCOUT', 'IS_ALIVE'),
('SLTH_UNIT_SUPPLIES', 'IS_ALIVE'),
('SLTH_UNIT_TREANT', 'IS_ALIVE'),
('SLTH_UNIT_MARY', 'IS_ALIVE'),
('SLTH_UNIT_GAELAN', 'IS_ALIVE'),
('SLTH_UNIT_MERCENARY', 'IS_ALIVE'),
('SLTH_UNIT_WAR_ELEPHANT', 'IS_ALIVE'),
('SLTH_UNIT_SLAVE', 'IS_ALIVE'),
('SLTH_UNIT_SHADE', 'IS_ALIVE'),
('SLTH_UNIT_RAVENOUS_WEREWOLF', 'IS_ALIVE'),
('SLTH_UNIT_WEREWOLF', 'IS_ALIVE'),
('SLTH_UNIT_GREATER_WEREWOLF', 'IS_ALIVE'),
('SLTH_UNIT_ADEPT', 'IS_ALIVE'),
('SLTH_UNIT_SHAMAN', 'IS_ALIVE'),
('SLTH_UNIT_MAGE', 'IS_ALIVE'),
('SLTH_UNIT_ARCHMAGE', 'IS_ALIVE'),
('SLTH_UNIT_KNIGHT', 'IS_ALIVE'),
('SLTH_UNIT_BEASTMASTER', 'IS_ALIVE'),
('SLTH_UNIT_BERSERKER', 'IS_ALIVE'),
('SLTH_UNIT_PHALANX', 'IS_ALIVE'),
('SLTH_UNIT_IMMORTAL', 'IS_ALIVE');


-- make table of all units that arent alive.
-- all angels, avatars, demons, elemental, golem, illusion, puppet, undead

CREATE TABLE IF NOT EXISTS UnitsNotAlive(
    UnitType text primary key,  -- references Units on update cascade on delete set null,
    Race text );
INSERT INTO UnitsNotAlive(UnitType, Race) VALUES
('SLTH_UNIT_REPENTANT_ANGEL', 'ANGEL'),
('SLTH_UNIT_ANGEL', 'ANGEL'),
('SLTH_UNIT_ANGEL_OF_DEATH', 'ANGEL'),
('SLTH_UNIT_VALKYRIE', 'ANGEL'),
('SLTH_UNIT_BASIUM', 'ANGEL'),
('SLTH_UNIT_HERALD', 'ANGEL'),
('SLTH_UNIT_OPHANIM', 'ANGEL'),
('SLTH_UNIT_SERAPH', 'ANGEL'),
('SLTH_UNIT_SPHENER', 'ANGEL'),
('SLTH_UNIT_EINHERJAR', 'ANGEL'),
('SLTH_UNIT_WRATH', 'AVATAR'),
('SLTH_UNIT_AURIC_ASCENDED', 'AVATAR'),
('SLTH_UNIT_MANES', 'DEMON'),
('SLTH_UNIT_HELLHOUND', 'DEMON'),
('SLTH_UNIT_HYBOREM', 'DEMON'),
('SLTH_UNIT_IMP', 'DEMON'),
('SLTH_UNIT_SUCCUBUS', 'DEMON'),
('SLTH_UNIT_TAR_DEMON', 'DEMON'),
('SLTH_UNIT_MARDERO', 'DEMON'),
('SLTH_UNIT_DEATH_KNIGHT', 'DEMON'),
('SLTH_UNIT_BALOR', 'DEMON'),
('SLTH_UNIT_CHAOS_MARAUDER', 'DEMON'),
('SLTH_UNIT_EIDOLON', 'DEMON'),
('SLTH_UNIT_MESHABBER', 'DEMON'),
('SLTH_UNIT_PIT_BEAST', 'DEMON'),
('SLTH_UNIT_SAVEROUS', 'DEMON'),
('SLTH_UNIT_STYGIAN_GUARD', 'DEMON'),
('SLTH_UNIT_BEAST_OF_AGARES', 'DEMON'),
('SLTH_UNIT_AZER', 'ELEMENTAL'),
('SLTH_UNIT_AIR_ELEMENTAL', 'ELEMENTAL'),
('SLTH_UNIT_DJINN', 'ELEMENTAL'),
('SLTH_UNIT_FIRE_ELEMENTAL', 'ELEMENTAL'),
('SLTH_UNIT_FIREBALL', 'ELEMENTAL'),
('SLTH_UNIT_ICE_ELEMENTAL', 'ELEMENTAL'),
('SLTH_UNIT_LIGHTNING_ELEMENTAL', 'ELEMENTAL'),
('SLTH_UNIT_AUREALIS', 'ELEMENTAL'),
('SLTH_UNIT_MISTFORM', 'ELEMENTAL'),
('SLTH_UNIT_SAND_LION', 'ELEMENTAL'),
('SLTH_UNIT_WATER_ELEMENTAL', 'ELEMENTAL'),
('SLTH_UNIT_PUPPET', 'ELEMENTAL'),
('SLTH_UNIT_WOOD_GOLEM', 'GOLEM'),
('SLTH_UNIT_CLOCKWORK_GOLEM', 'GOLEM'),
('SLTH_UNIT_IRON_GOLEM', 'GOLEM'),
('SLTH_UNIT_BONE_GOLEM', 'GOLEM'),
('SLTH_UNIT_NULLSTONE_GOLEM', 'GOLEM'),
('SLTH_UNIT_BARNAXUS', 'GOLEM'),
('SLTH_UNIT_MUD_GOLEM', 'GOLEM'),
('SLTH_UNIT_MITHRIL_GOLEM', 'GOLEM'),
('SLTH_UNIT_LICH', 'UNDEAD'),
('SLTH_UNIT_SKELETON', 'UNDEAD'),
('SLTH_UNIT_DISEASED_CORPSE', 'UNDEAD'),
('SLTH_UNIT_DROWN', 'UNDEAD'),
('SLTH_UNIT_PYRE_ZOMBIE', 'UNDEAD'),
('SLTH_UNIT_WRAITH', 'UNDEAD'),
('SLTH_UNIT_SAILORS_DIRGE', 'UNDEAD');
