-- Mithril, Iron, Copper bonuses to units when we do it. Also Nightmare, and Sheut stone

-- Sheut stone: If city has access (to implement) 1 death damage, +25% Death resistance and a -10% weakness to holy damage

-- Nightmare: If city has access to Nightmare when building a unit, +1 Unholy combat
-- REQUIREMENT_UNIT_IN_OWNER_TERRITORY
-- AND Player has Any Collection CAPITAL_CITY
-- PLotProperty at Least...

INSERT INTO RequirementSets(RequirementSetId, RequirementSetType) VALUES
('SLTH_UNIT_IN_OWNER_TERRITORY_AND_HAS_COPPER_REQS', 'REQUIREMENTSET_TEST_ALL');

INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('SLTH_UNIT_IN_OWNER_TERRITORY_AND_HAS_COPPER_REQS', 'UNIT_IN_OWNER_TERRITORY_REQUIREMENT'),
('SLTH_UNIT_IN_OWNER_TERRITORY_AND_HAS_COPPER_REQS', 'SLTH_CHECK_PLAYER_HAS_HAS_SOURCE_OF_COPPER_REQ');

INSERT INTO Requirements(RequirementId, RequirementType) VALUES
('SLTH_CHECK_PLAYER_HAS_HAS_SOURCE_OF_COPPER_REQ', 'REQUIREMENT_COLLECTION_ANY_MET');

INSERT INTO RequirementArguments(RequirementId, Name, Value) VALUES
('SLTH_CHECK_PLAYER_HAS_HAS_SOURCE_OF_COPPER_REQ', 'CollectionType',  'COLLECTION_PLAYER_CAPITAL_CITY'),
('SLTH_CHECK_PLAYER_HAS_HAS_SOURCE_OF_COPPER_REQ', 'RequirementSetId',  'PLAYER_HAS_COPPER');                   -- lifted from conditionalBuildings, for Form of Titan double prod


INSERT INTO RequirementSets(RequirementSetId, RequirementSetType) VALUES
('SLTH_UNIT_IN_OWNER_TERRITORY_AND_HAS_IRON_REQS', 'REQUIREMENTSET_TEST_ALL');

INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('SLTH_UNIT_IN_OWNER_TERRITORY_AND_HAS_IRON_REQS', 'UNIT_IN_OWNER_TERRITORY_REQUIREMENT'),
('SLTH_UNIT_IN_OWNER_TERRITORY_AND_HAS_IRON_REQS', 'SLTH_CHECK_PLAYER_HAS_HAS_SOURCE_OF_IRON');

INSERT INTO Requirements(RequirementId, RequirementType) VALUES
('SLTH_CHECK_PLAYER_HAS_HAS_SOURCE_OF_IRON', 'REQUIREMENT_COLLECTION_ANY_MET');

INSERT INTO RequirementArguments(RequirementId, Name, Value) VALUES
('SLTH_CHECK_PLAYER_HAS_HAS_SOURCE_OF_IRON', 'CollectionType',  'COLLECTION_PLAYER_CAPITAL_CITY'),
('SLTH_CHECK_PLAYER_HAS_HAS_SOURCE_OF_IRON', 'RequirementSetId',  'PLAYER_HAS_IRON_REQS');


INSERT INTO RequirementSets(RequirementSetId, RequirementSetType) VALUES
('SLTH_UNIT_IN_OWNER_TERRITORY_AND_HAS_MITHRIL_REQS', 'REQUIREMENTSET_TEST_ALL');

INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('SLTH_UNIT_IN_OWNER_TERRITORY_AND_HAS_MITHRIL_REQS', 'UNIT_IN_OWNER_TERRITORY_REQUIREMENT'),
('SLTH_UNIT_IN_OWNER_TERRITORY_AND_HAS_MITHRIL_REQS', 'SLTH_CHECK_PLAYER_HAS_HAS_SOURCE_OF_MITHRIL');

INSERT INTO Requirements(RequirementId, RequirementType) VALUES
('SLTH_CHECK_PLAYER_HAS_HAS_SOURCE_OF_MITHRIL', 'REQUIREMENT_COLLECTION_ANY_MET');

INSERT INTO RequirementArguments(RequirementId, Name, Value) VALUES
('SLTH_CHECK_PLAYER_HAS_HAS_SOURCE_OF_MITHRIL', 'CollectionType',  'COLLECTION_PLAYER_CAPITAL_CITY'),
('SLTH_CHECK_PLAYER_HAS_HAS_SOURCE_OF_MITHRIL', 'RequirementSetId',  'PLAYER_HAS_MITHRIL_REQS');

INSERT INTO RequirementSets(RequirementSetId, RequirementSetType) VALUES
('SLTH_UNIT_IN_OWNER_TERRITORY_AND_HAS_NIGHTMARE_REQS', 'REQUIREMENTSET_TEST_ALL');

INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('SLTH_UNIT_IN_OWNER_TERRITORY_AND_HAS_NIGHTMARE_REQS', 'UNIT_IN_OWNER_TERRITORY_REQUIREMENT'),
('SLTH_UNIT_IN_OWNER_TERRITORY_AND_HAS_NIGHTMARE_REQS', 'SLTH_CHECK_PLAYER_HAS_HAS_SOURCE_OF_NIGHTMARE');

INSERT INTO Requirements(RequirementId, RequirementType) VALUES
('SLTH_CHECK_PLAYER_HAS_HAS_SOURCE_OF_NIGHTMARE', 'REQUIREMENT_COLLECTION_ANY_MET');

INSERT INTO RequirementArguments(RequirementId, Name, Value) VALUES
('SLTH_CHECK_PLAYER_HAS_HAS_SOURCE_OF_NIGHTMARE', 'CollectionType',  'COLLECTION_PLAYER_CAPITAL_CITY'),
('SLTH_CHECK_PLAYER_HAS_HAS_SOURCE_OF_NIGHTMARE', 'RequirementSetId',  'PLAYER_HAS_NIGHTMARE_REQS');


INSERT INTO Requirements(RequirementId, RequirementType) VALUES
('SLTH_REQUIREMENT_HAS_NIGHTMARE_PROPERTY', 'REQUIREMENT_PLOT_PROPERTY_MATCHES'),
('SLTH_REQUIREMENT_HAS_IRON_PROPERTY', 'REQUIREMENT_PLOT_PROPERTY_MATCHES'),
('SLTH_REQUIREMENT_HAS_MITHRIL_PROPERTY', 'REQUIREMENT_PLOT_PROPERTY_MATCHES');
INSERT INTO RequirementArguments(RequirementId, Name, Value) VALUES
('SLTH_REQUIREMENT_HAS_NIGHTMARE_PROPERTY', 'PropertyName','RESOURCE_NIGHTMARE'),
('SLTH_REQUIREMENT_HAS_NIGHTMARE_PROPERTY', 'PropertyMinimum','1'),
('SLTH_REQUIREMENT_HAS_IRON_PROPERTY', 'PropertyName','RESOURCE_IRON'),
('SLTH_REQUIREMENT_HAS_IRON_PROPERTY', 'PropertyMinimum','1'),
('SLTH_REQUIREMENT_HAS_MITHRIL_PROPERTY', 'PropertyName','RESOURCE_MITHRIL'),
('SLTH_REQUIREMENT_HAS_MITHRIL_PROPERTY', 'PropertyMinimum','1');
INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('PLAYER_HAS_NIGHTMARE_REQS', 'SLTH_REQUIREMENT_HAS_NIGHTMARE_PROPERTY'),
('PLAYER_HAS_IRON_REQS', 'SLTH_REQUIREMENT_HAS_IRON_PROPERTY'),
('PLAYER_HAS_MITHRIL_REQS', 'SLTH_REQUIREMENT_HAS_MITHRIL_PROPERTY');
INSERT INTO RequirementSets(RequirementSetId, RequirementSetType) VALUES
('PLAYER_HAS_NIGHTMARE_REQS', 'REQUIREMENTSET_TEST_ALL'),
('PLAYER_HAS_IRON_REQS', 'REQUIREMENTSET_TEST_ALL'),
('PLAYER_HAS_MITHRIL_REQS', 'REQUIREMENTSET_TEST_ALL');


INSERT INTO Modifiers(ModifierId, ModifierType, SubjectRequirementSetId) VALUES
('MODIFIER_NIGHTMARE_STRENGTH', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', NULL),

('MODIFIER_COPPER_STRENGTH_ATTACH', 'MODIFIER_SINGLE_UNIT_ATTACH_MODIFIER', 'UNIT_DOESNT_HAVE_IRON_OR_MITHRIL_REQS'),
('MODIFIER_COPPER_STRENGTH', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', NULL),
('MODIFIER_IRON_STRENGTH_ATTACH', 'MODIFIER_SINGLE_UNIT_ATTACH_MODIFIER', 'UNIT_DOESNT_HAVE_MITHRIL_REQS'),
('MODIFIER_IRON_STRENGTH', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', NULL),
('MODIFIER_MITHRIL_STRENGTH', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', NULL);

INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
('MODIFIER_NIGHTMARE_STRENGTH', 'Amount', '5'),
('MODIFIER_COPPER_STRENGTH', 'Amount', '5'),
('MODIFIER_IRON_STRENGTH', 'Amount', '10'),             -- also strength on copper fight, but seems impossible to check
('MODIFIER_MITHRIL_STRENGTH', 'Amount', '19'),
('MODIFIER_COPPER_STRENGTH_ATTACH', 'ModifierId', 'MODIFIER_COPPER_STRENGTH'),
('MODIFIER_IRON_STRENGTH_ATTACH', 'ModifierId', 'MODIFIER_IRON_STRENGTH');

INSERT INTO ModifierStrings(ModifierId, Context, Text) VALUES
('MODIFIER_NIGHTMARE_STRENGTH', 'Preview', 'LOC_PROMOTION_NIGHTMARE_DESCRIPTION'),
('MODIFIER_COPPER_STRENGTH', 'Preview', 'LOC_COPPER_STRENGTH_DESCRIPTION'),
('MODIFIER_IRON_STRENGTH', 'Preview', 'LOC_IRON_STRENGTH_DESCRIPTION'),
('MODIFIER_MITHRIL_STRENGTH', 'Preview', 'LOC_MITHRIL_STRENGTH_DESCRIPTION');

INSERT INTO Requirements(RequirementId, RequirementType, Inverse) VALUES
('REQUIREMENT_UNIT_HASNT_IRON_WEAPONS', 'REQUIREMENT_UNIT_HAS_ABILITY', '1'),
('REQUIREMENT_UNIT_HASNT_MITHRIL_WEAPONS', 'REQUIREMENT_UNIT_HAS_ABILITY', '1');
INSERT INTO RequirementArguments(RequirementId, Name, Value) VALUES
('REQUIREMENT_UNIT_HASNT_IRON_WEAPONS', 'UnitAbilityType','ABILITY_IRON_WEAPONS'),
('REQUIREMENT_UNIT_HASNT_MITHRIL_WEAPONS', 'UnitAbilityType','ABILITY_MITHRIL_WEAPONS');
INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
('UNIT_DOESNT_HAVE_IRON_OR_MITHRIL_REQS', 'REQUIREMENT_UNIT_HASNT_IRON_WEAPONS'),
('UNIT_DOESNT_HAVE_IRON_OR_MITHRIL_REQS', 'REQUIREMENT_UNIT_HASNT_MITHRIL_WEAPONS'),
('UNIT_DOESNT_HAVE_MITHRIL_REQS',         'REQUIREMENT_UNIT_HASNT_MITHRIL_WEAPONS');
INSERT INTO RequirementSets(RequirementSetId, RequirementSetType) VALUES
('UNIT_DOESNT_HAVE_IRON_OR_MITHRIL_REQS', 'REQUIREMENTSET_TEST_ALL'),
('UNIT_DOESNT_HAVE_MITHRIL_REQS',         'REQUIREMENTSET_TEST_ALL');

INSERT INTO UnitAbilities(UnitAbilityType, Name, Description, Inactive, Permanent) VALUES
('NIGHTMARE_ABILITY_HELL_TERRAIN_STRENGTH', 'LOC_SLTH_NIGHTMARE_ABILITY_HELL_TERRAIN_STRENGTH_NAME', 'LOC_NIGHTMARE_ABILITY_HELL_TERRAIN_STRENGTH_DESCRIPTION', '1', '1'),
('ABILITY_BRONZE_WEAPONS', 'LOC_ABILITY_BRONZE_WEAPONS_NAME', 'LOC_ABILITY_BRONZE_WEAPONS_DESCRIPTION', '1', '1'),
('ABILITY_IRON_WEAPONS', 'LOC_ABILITY_IRON_WEAPONS_NAME', 'LOC_ABILITY_IRON_WEAPONS_DESCRIPTION', '1', '1'),
('ABILITY_MITHRIL_WEAPONS', 'LOC_ABILITY_MITHRIL_WEAPONS_NAME', 'LOC_ABILITY_MITHRIL_WEAPONS_DESCRIPTION', '1', '1');

INSERT INTO UnitAbilityModifiers(UnitAbilityType, ModifierId) VALUES
('NIGHTMARE_ABILITY_HELL_TERRAIN_STRENGTH', 'MODIFIER_DEMON_ABILITY_HELL_TERRAIN_STRENGTH'), -- borrowed from Demon Race
('NIGHTMARE_ABILITY_HELL_TERRAIN_STRENGTH', 'MODIFIER_NIGHTMARE_STRENGTH'),
('ABILITY_BRONZE_WEAPONS', 'MODIFIER_COPPER_STRENGTH_ATTACH'),
('ABILITY_IRON_WEAPONS', 'MODIFIER_IRON_STRENGTH_ATTACH'),
('ABILITY_MITHRIL_WEAPONS', 'MODIFIER_MITHRIL_STRENGTH');

INSERT INTO Tags(Tag, Vocabulary) VALUES
('CLASS_ABILITY_BRONZE_WEAPONS', 'ABILITY_CLASS'),
('CLASS_ABILITY_IRON_WEAPONS', 'ABILITY_CLASS'),
('CLASS_ABILITY_MITHRIL_WEAPONS', 'ABILITY_CLASS');

INSERT INTO TypeTags(Type, Tag) VALUES
('NIGHTMARE_ABILITY_HELL_TERRAIN_STRENGTH', 'CLASS_LIGHT_CAVALRY'),
('ABILITY_BRONZE_WEAPONS', 'CLASS_ABILITY_BRONZE_WEAPONS'),
('ABILITY_BRONZE_WEAPONS', 'CLASS_ABILITY_IRON_WEAPONS'),
('ABILITY_IRON_WEAPONS', 'CLASS_ABILITY_IRON_WEAPONS'),
('ABILITY_BRONZE_WEAPONS', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
('ABILITY_IRON_WEAPONS', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
('ABILITY_MITHRIL_WEAPONS', 'CLASS_ABILITY_MITHRIL_WEAPONS');

-- give the ability to give the second ability
INSERT INTO TypeTags(Type, Tag) VALUES
('ABILITY_BRONZE_WEAPONS_CHECKER', 'CLASS_ABILITY_BRONZE_WEAPONS'),
('ABILITY_IRON_WEAPONS_CHECKER', 'CLASS_ABILITY_IRON_WEAPONS'),
('ABILITY_MITHRIL_WEAPONS_CHECKER', 'CLASS_ABILITY_MITHRIL_WEAPONS');

-- TODO add Nightmare too. Maybe also Sheut stone?

INSERT INTO UnitAbilities(UnitAbilityType, Name, Description) VALUES
('ABILITY_BRONZE_WEAPONS_CHECKER', 'LOC_ABILITY_BRONZE_WEAPONS_CHECKER_NAME', 'LOC_ABILITY_BRONZE_WEAPONS_CHECKER_DESCRIPTION'),
('ABILITY_IRON_WEAPONS_CHECKER', 'LOC_ABILITY_IRON_WEAPONS_CHECKER_NAME', 'LOC_ABILITY_IRON_WEAPONS_CHECKER_DESCRIPTION'),
('ABILITY_MITHRIL_WEAPONS_CHECKER', 'LOC_ABILITY_MITHRIL_WEAPONS_CHECKER_NAME', 'LOC_ABILITY_MITHRIL_WEAPONS_CHECKER_DESCRIPTION');

INSERT INTO UnitAbilityModifiers(UnitAbilityType, ModifierId) VALUES
('ABILITY_BRONZE_WEAPONS_CHECKER', 'MODIFIER_GRANT_COPPER_WEAPONS'),
('ABILITY_IRON_WEAPONS_CHECKER', 'MODIFIER_GRANT_COPPER_WEAPONS'),
('ABILITY_IRON_WEAPONS_CHECKER', 'MODIFIER_GRANT_IRON_WEAPONS'),
('ABILITY_MITHRIL_WEAPONS_CHECKER', 'MODIFIER_GRANT_COPPER_WEAPONS'),
('ABILITY_MITHRIL_WEAPONS_CHECKER', 'MODIFIER_GRANT_IRON_WEAPONS'),
('ABILITY_MITHRIL_WEAPONS_CHECKER', 'MODIFIER_GRANT_MITHRIL_WEAPONS');

INSERT INTO Modifiers(ModifierId, ModifierType, SubjectRequirementSetId, Permanent, RunOnce) VALUES
('MODIFIER_GRANT_COPPER_WEAPONS', 'MODIFIER_PLAYER_UNIT_GRANT_ABILITY', 'SLTH_UNIT_IN_OWNER_TERRITORY_AND_HAS_COPPER_REQS', '1', '1'),
('MODIFIER_GRANT_IRON_WEAPONS', 'MODIFIER_PLAYER_UNIT_GRANT_ABILITY', 'SLTH_UNIT_IN_OWNER_TERRITORY_AND_HAS_IRON_REQS', '1', '1'),
('MODIFIER_GRANT_MITHRIL_WEAPONS', 'MODIFIER_PLAYER_UNIT_GRANT_ABILITY', 'SLTH_UNIT_IN_OWNER_TERRITORY_AND_HAS_MITHRIL_REQS', '1', '1');

INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
('MODIFIER_GRANT_COPPER_WEAPONS', 'AbilityType', 'ABILITY_BRONZE_WEAPONS'),
('MODIFIER_GRANT_IRON_WEAPONS', 'AbilityType', 'ABILITY_IRON_WEAPONS'),
('MODIFIER_GRANT_MITHRIL_WEAPONS', 'AbilityType', 'ABILITY_MITHRIL_WEAPONS');

-- attrib specific units
INSERT INTO TypeTags(Type, Tag) VALUES
('SLTH_UNIT_ANGEL', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
('SLTH_UNIT_ANGEL_OF_DEATH', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
('SLTH_UNIT_SWORDSMAN', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
('SLTH_UNIT_BALOR', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
('SLTH_UNIT_BATTLEMASTER', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
('SLTH_UNIT_BERSERKER', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
('SLTH_UNIT_BISON_RIDER', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
('SLTH_UNIT_BOARDING_PARTY', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
('SLTH_UNIT_BRUJAH', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
('SLTH_UNIT_CENTAUR_CHARGER', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
('SLTH_UNIT_CENTAUR_LANCER', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
('SLTH_UNIT_CHAMPION', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
('SLTH_UNIT_CHAOS_MARAUDER', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
('SLTH_UNIT_CHARIOT', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
('SLTH_UNIT_DEATH_KNIGHT', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
('SLTH_UNIT_DEMAGOG', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
('SLTH_UNIT_DISEASED_CORPSE', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
('SLTH_UNIT_DRAGON_SLAYER', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
('SLTH_UNIT_DROWN', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
('SLTH_UNIT_DWARVEN_SOLDIER_RUNES', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
('SLTH_UNIT_HORNGUARD', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
('SLTH_UNIT_FLAGBEARER', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
('SLTH_UNIT_GRIGORI_MEDIC', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
('SLTH_UNIT_HERALD', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
('SLTH_UNIT_IMMORTAL', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
('SLTH_UNIT_KNIGHT', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
('SLTH_UNIT_LUNATIC', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
('SLTH_UNIT_MERCENARY', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
('SLTH_UNIT_MIMIC', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
('SLTH_UNIT_MOROI', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
('SLTH_UNIT_MERCENARY_MOUNTED', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
('SLTH_UNIT_OGRE', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
('SLTH_UNIT_OGRE_WARCHIEF', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
('SLTH_UNIT_OPHANIM', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
('SLTH_UNIT_PHALANX', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
('SLTH_UNIT_PYRE_ZOMBIE', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
('SLTH_UNIT_RADIANT_GUARD', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
('SLTH_UNIT_RATHA', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
('SLTH_UNIT_REPENTANT_ANGEL', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
('SLTH_UNIT_ROYAL_GUARD', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
('SLTH_UNIT_SERAPH', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
('SLTH_UNIT_SHADOWRIDER', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
('SLTH_UNIT_SONS_OF_ASENA', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
('SLTH_UNIT_STONESKIN_OGRE', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
('SLTH_UNIT_STYGIAN_GUARD', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
('SLTH_UNIT_SUCCUBUS', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
('SLTH_UNIT_VALKYRIE', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
('SLTH_UNIT_VAMPIRE', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
('SLTH_UNIT_VAMPIRE_LORD', 'CLASS_ABILITY_MITHRIL_WEAPONS'),


('SLTH_UNIT_BAMBUR', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
('SLTH_UNIT_BARNAXUS', 'CLASS_ABILITY_MITHRIL_WEAPONS'),                --????
('SLTH_UNIT_BASIUM', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
-- ('SLTH_UNIT_BRIGIT', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
('SLTH_UNIT_DONAL', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
('SLTH_UNIT_GUYBRUSH', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
('SLTH_UNIT_HERNE', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
('SLTH_UNIT_HYBOREM', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
('SLTH_UNIT_LOSHA', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
('SLTH_UNIT_LUCIAN', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
('SLTH_UNIT_MAGNADINE', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
('SLTH_UNIT_MAROS', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
('SLTH_UNIT_MARY', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
('SLTH_UNIT_MESHABBER', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
('SLTH_UNIT_ORTHUS', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
('SLTH_UNIT_RANTINE', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
('SLTH_UNIT_SAVEROUS', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
('SLTH_UNIT_WILBOMAN', 'CLASS_ABILITY_MITHRIL_WEAPONS'),

('SLTH_UNIT_CROSSBOWMAN', 'CLASS_ABILITY_IRON_WEAPONS'),
('SLTH_UNIT_FIREBOW', 'CLASS_ABILITY_IRON_WEAPONS'),
('SLTH_UNIT_FLURRY', 'CLASS_ABILITY_IRON_WEAPONS'),
('SLTH_UNIT_FREAK', 'CLASS_ABILITY_IRON_WEAPONS'),
('SLTH_UNIT_LONGBOWMAN', 'CLASS_ABILITY_IRON_WEAPONS'),
('SLTH_UNIT_NIGHTWATCH', 'CLASS_ABILITY_IRON_WEAPONS'),

('SLTH_UNIT_BEASTMAN', 'CLASS_ABILITY_BRONZE_WEAPONS'),
('UNIT_WARRIOR', 'CLASS_ABILITY_BRONZE_WEAPONS');

-- ('SLTH_UNIT_SKULD', 'CLASS_ABILITY_MITHRIL_WEAPONS'),
-- ('SLTH_UNIT_VERDANDI', 'CLASS_ABILITY_MITHRIL_WEAPONS'),

/*
CRUSADERS CANT USE ANY
EIDOLONS
PALADIN
PARAMANDER
WAR_TORTOISE
 */

INSERT INTO Types(Type, Kind) VALUES
('NIGHTMARE_ABILITY_HELL_TERRAIN_STRENGTH', 'KIND_ABILITY'),
('ABILITY_BRONZE_WEAPONS', 'KIND_ABILITY'),
('ABILITY_IRON_WEAPONS', 'KIND_ABILITY'),
('ABILITY_MITHRIL_WEAPONS', 'KIND_ABILITY'),
('ABILITY_BRONZE_WEAPONS_CHECKER', 'KIND_ABILITY'),
('ABILITY_IRON_WEAPONS_CHECKER', 'KIND_ABILITY'),
('ABILITY_MITHRIL_WEAPONS_CHECKER', 'KIND_ABILITY')

